### PR TITLE
cdc: remove assertion on the lock start-ts

### LINKED ISSUE #19083: tikv assert panic "assert!(x.get().ts <= start_ts.ts);" on the tikv-cdc
### What version of TiKV are you using?

master

### What did you expect?

the tikv-cdc works normally, no panic

### What did happened?
the tikv-cdc panic, due to `assert!(x.get().ts <= start_ts.ts);` failed

### PR DESCRIPTION
**Pull request by 3AceShowHand**
### What is changed and how it works?

Issue Number: Close #19083 

What's Changed:

```commit-message
* revert #16864 to avoid the TiKV-CDC panic due to assertion failed
```

* The `generation` field is removed by revert the PR, need to do more work about how to support pipelined DML.
* When `push_lock`, just push it like before, and print logs if there is already the lock with the same key.

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [ ] Need to cherry-pick to the release branch

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note

```release-note
revert #16864 to avoid the TiKV-CDC panic due to assertion failed
```

### CODE REVIEW

File: components/cdc/src/delegate.rs [hunk 1]
```diff
@@ -369,29 +367,16 @@ impl Delegate {
...
-                    assert!(x.get().generation <= start_ts.generation);
-                    x.get_mut().ts = start_ts.ts;
-                    x.get_mut().generation = start_ts.generation;
+            LockTracker::Prepared { locks, .. } => match locks.insert(key.clone(), start_ts) {
+                Some(old_lock) => {
+                    info!("cdc push_lock found lock key already exists, overwrite it";
+                        "key" => ?key,
+                        "old_start_ts" => ?old_lock.ts,
+                        "new_start_ts" => ?ts,
+                        "region_id" => self.region_id,
```
Comment (lcwangchao) [inline components/cdc/src/delegate.rs]: I think the generation, txn_source can also be included in the log

Comment (3AceShowHand) [reply components/cdc/src/delegate.rs]: the `generation` is removed, `txn_source` indicate that whether the row comes from ticdc inserted or lightning physical imported, not relevant.

**Comment by cfzjywxk** [comment]
@3AceShowHand 
It seems the `DELETE LOCK` event on non-protected-rollback lock key is not handled in the current PR yet?

**Comment by 3AceShowHand** [comment]
> @3AceShowHand It seems the `DELETE LOCK` event on non-protected-rollback lock key is not handled in the current PR yet?

Yes, I am investigating how to handle the `DELETE LOCK` and also ignore the pessimistic locks, to avoid the #17876

File: components/cdc/src/delegate.rs [hunk 2]
```diff
@@ -1060,26 +1033,25 @@ impl Delegate {
                     let read_old_ts = TimeStamp::from(row.v.commit_ts).prev();
                     row.needs_old_value = Some(read_old_ts);
                 } else {
-                    assert_eq!(row.lock_count_modify, 0);
                     let start_ts = TimeStamp::from(row.v.start_ts);
-                    row.lock_count_modify = self.pop_lock(key, start_ts)?;
+                    let mut modified = self.pop_lock(key, start_ts)?;
```
Comment (3AceShowHand) [inline components/cdc/src/delegate.rs:1037]: This is a important change.

Previous code `assert_eq!(row.lock_count_modify, 0);` make one assumption that there is no 2 put request with the same key in the one batch.

The assertion is removed, and make that it is possible the case above happens. For example, lock cf put key a, and then write cf pop key a.

**Review by cfzjywxk — APPROVED** [review]
LGTM, we may leave the lock cf handling compalitity refactor in the later PR

**Review by overvenus — APPROVED** [review]
