### PR TITLE
raftstore: do not free cached entries if not all of them are persisted

### LINKED ISSUE #17040: tikv panic when run sysbench prepare
### What version of TiKV are you using?
./tikv-server -V
 TiKV 
Release Version:   8.2.0-alpha
Edition:           Community
Git Commit Hash:   34d8b38a17e3003cc5730e8dc53d447db5b7bd31
Git Commit Branch: heads/refs/tags/v8.2.0-alpha
UTC Build Time:    2024-05-20 11:38:26
Rust Version:      rustc 1.77.0-nightly (89e2160c4 2023-12-27)
Enable Features:   memory-engine pprof-fp jemalloc mem-profiling portable sse test-engine-kv-rocksdb test-engine-raft-raft-engine trace-async-tasks openssl-vendored
Profile:           dist_relea

### What operating system and CPU are you using?
8c/48g

### Steps to reproduce
1、run  sysbench prepare
sysbench --db-driver=mysql --time=0 --mysql-db=fordata20240521164538 --mysql-host=tc-tidb.e2e-diskfull-stab-fun-tps-7580383-1-343 --mysql-port=4000 --threads=512 --tables=100 --table-size=10000000 --create_secondary=off --mysql-user=root oltp_read_only prepare

### What did you expect?
no panic

### What did happened?
tikv panic
`{"container":"tikv","pod":"tc-tikv-2","level":"FATAL","namespace":"e2e-diskfull-stab-fun-tps-7580383-1-343","log":"[lib.rs:477] [\"called `Result::unwrap()` on an `Err` value: EntriesUnavailable\"] [backtrace=\"   0: tikv_util::set_panic_hook::{{closure}}\\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/tikv_util/src/lib.rs:476:18\\n   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call\\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2029:9\\n      std::panicking::rust_panic_with_hook\\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:783:13\\n   2: std::panicking::begin_panic_handler::{{closure}}\\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:657:13\\n   3: std::sys_common::backtrace::__rust_end_short_backtrace\\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:171:18\\n   4: rust_begin_unwind\\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:645:5\\n   5: core::panicking::panic_fmt\\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panicking.rs:72:14\\n   6: core::result::unwrap_failed\\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/result.rs:1649:5\\n   7: core::result::Result<T,E>::unwrap\\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/result.rs:1073:23\\n      raftstore::store::fsm::apply::ApplyFsm<EK>::handle_apply\\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/fsm/apply.rs:4021:17\\n   8: raftstore::store::fsm::apply::ApplyFsm<EK>::handle_tasks\\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/fsm/apply.rs:4420:25\\n   9: <raftstore::store::fsm::apply::ApplyPoller<EK> as batch_system::batch::PollHandler<raftstore::store::fsm::apply::ApplyFsm<EK>,raftstore::store::fsm::apply::ControlFsm>>::handle_normal\\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/fsm/apply.rs:4709:9\\n  10: batch_system::batch::Poller<N,C,Handler>::poll\\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/batch-system/src/batch.rs:422:27\\n  11: batch_system::batch::BatchSystem<N,C>::start_poller::{{closure}}\\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/batch-system/src/batch.rs:551:17\\n      <std::thread::Builder as tikv_util::sys::thread::StdThreadBuildWrapper>::spawn_wrapper::{{closure}}\\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/tikv_util/src/sys/thread.rs:438:13\\n      std::sys_common::backtrace::__rust_begin_short_backtrace\\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:155:18\\n  12: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}\\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:529:17\\n      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once\\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panic/unwind_safe.rs:272:9\\n      std::panicking::try::do_call\\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:552:40\\n      std::panicking::try\\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:516:19\\n      std::panic::catch_unwind\\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:142:14\\n      std::thread::Builder::spawn_unchecked_::{{closure}}\\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:528:30\\n      core::ops::function::FnOnce::call_once{{vtable.shim}}\\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5\\n  13: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once\\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2015:9\\n      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once\\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2015:9\\n      std::sys::unix::thread::Thread::new::thread_start\\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys/unix/thread.rs:108:17\\n  14: start_thread\\n  15: clone\\n\"] [location=/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/fsm/apply.rs:4024] [thread_name=apply-0] [thread_id=102]"}`

### PR DESCRIPTION
**Pull request by glorv**
### What is changed and how it works?

Issue Number: Close #17040, ref #16717

What's Changed:

```commit-message
Do not free cached entries if not all of them are persisted. After #16834, it is possible that applying entries are not persisted, so we should avoid evicting these entries while they are not fully persisted.
```

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [ ] Need to cherry-pick to the release branch

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by overvenus** [comment]
Will it cause OOM if persisting is slow?

File: components/raftstore/src/store/entry_storage.rs [hunk 1]
```diff
@@ -248,8 +253,12 @@ impl EntryCache {
                 }
                 break;
             }
-            let (_, dangle_size) = cached_entries.take_entries();
-            mem_size_change -= dangle_size as i64;
+            // keep the applying entries if not all of them are persisted.
+            if cached_entries.range.end <= idx {
```
Comment (overvenus) [inline components/raftstore/src/store/entry_storage.rs:257]: How about keeping these entries only when #16834 is enabled?

File: components/raftstore/src/store/entry_storage.rs [hunk 2]
```diff
@@ -248,8 +253,12 @@ impl EntryCache {
                 }
                 break;
             }
-            let (_, dangle_size) = cached_entries.take_entries();
-            mem_size_change -= dangle_size as i64;
+            // keep the applying entries if not all of them are persisted.
```
Comment (Connor1996) [inline components/raftstore/src/store/entry_storage.rs:256]: If not, where would be a problem?

File: components/raftstore/src/store/entry_storage.rs (hunk 1 above)
Comment (glorv) [reply components/raftstore/src/store/entry_storage.rs:257]: If #16834 is disabled, then the range end is impossible to be bigger than persisted index, this is also the reason that the origin logic does not need to check the range end.

File: components/raftstore/src/store/entry_storage.rs (hunk 2 above)
Comment (glorv) [reply components/raftstore/src/store/entry_storage.rs:256]: If not all of the entries are persisted and these entries are evicted from both the entry_cache and the cached_entries, then ApplyFsm may not be able to fetch the dangling entries from raft-engine because they are not persisted, thus it will cause tikv panic.

Comment (Connor1996) [reply components/raftstore/src/store/entry_storage.rs:256]: You should update above comment 
```
// example, if entries [1, 10), [10, 20), [20, 30) are sent to apply threads and
// `compact_to(15)` is called, only [20, 30) will still be kept in cache.
```

Now `[10,20)` would be kept as well, is that right?

Comment (LykxSassinator) [inline components/raftstore/src/store/entry_storage.rs:256]: Pls add more comments about this change.
```suggestion
            // Do not evict cached entries if not all of them are persisted.
            // Following the changes in #16834, there is a possibility that applying
            // entries are not yet fully persisted. Therefore, it should not free these
            // entries until they are completely persisted.
```

Comment (glorv) [reply components/raftstore/src/store/entry_storage.rs]: No. [10, 20] will be remove from entry_cache, but the entries in CachedEntries(refered by a ApplyMsg) will not be removed.

**Comment by glorv** [comment]
@Connor1996 @overvenus @LykxSassinator  PTAL again, thanks~

**Review by Connor1996 — APPROVED** [review]
LGTM

**Review by LykxSassinator — APPROVED** [review]

**Review by overvenus — COMMENTED** [review]
> Will it cause OOM if persisting is slow?

Please leave an issue for the OOM risk.

**Comment by glorv** [comment]
> > Will it cause OOM if persisting is slow?
> 
> Please leave an issue for the OOM risk.

Done. #17055
