### PR TITLE
cdc, txn: improve CDC old value cache hit ratio in pessimistic txn

### LINKED ISSUE #10032: CDC old value cache does not work effectively for caching pessimistic txn write
## Bug Report

0% old value cache hit for pessimistic transaction write.

This issue may relate to https://github.com/tikv/tikv/issues/9996 and https://github.com/tikv/tikv/issues/9981.

The left is optimistic transaction writes and the right is pessimistic transaction writes.
image
image

### What version of TiKV are you using?

master and v5.0.0

### Steps to reproduce

```
# create a changefeed with old value feature.
sysbench --db-driver=mysql --mysql-host=172.16.5.33 --mysql-port=47904 --mysql-user=root --time=15000 --report-interval=10 --threads=64 --mysql-db=test --tables=1 --table-size=6000000 oltp_write_only prepare
sleep 60 && sysbench --db-driver=mysql --mysql-host=172.16.5.33 --mysql-port=47904 --mysql-user=root --time=15000 --report-interval=10 --threads=64 --mysql-db=test --tables=1 --table-size=6000000 oltp_write_only run
```

### What did you expect?

Old value cache works effectively.

### PR DESCRIPTION
**Pull request by overvenus**
### What problem does this PR solve?

Issue Number: close #10032 
Problem Summary: Improve old value cache hit ratio in pessimistic txn.

### What is changed and how it works?

Get old value in acquire pessimistic lock stage and insert it into old value cache.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)

image
image

```
# create a changefeed with old value enabled.
sysbench --db-driver=mysql --mysql-host=172.16.5.33 --mysql-port=47904 --mysql-user=root --time=15000 --report-interval=10 --threads=64 --mysql-db=test --tables=1 --table-size=6000000 oltp_write_only prepare && \
sleep 60 && sysbench --db-driver=mysql --mysql-host=172.16.5.33 --mysql-port=47904 --mysql-user=root --time=15000 --report-interval=10 --threads=64 --mysql-db=test --tables=1 --table-size=6000000 oltp_write_only run
```

### Release note 

- Improve CDC old value cache hit ratio in pessimistic txn

### CODE REVIEW

File: components/cdc/src/observer.rs [hunk 1]
```diff
@@ -130,32 +130,34 @@ impl<E: KvEngine> CmdObserver<E> for CdcObserver {
...
-                        MutationType::Put | MutationType::Delete => match old_value {
-                            OldValue::None => (None, None),
-                            OldValue::Value {
-                                start_ts,
-                                short_value,
-                            } => {
-                                let mut statistics = None;
-                                let value = short_value.or_else(|| {
-                                    statistics = Some(Statistics::default());
+                        // Old value of an Insert is guaranteed to be None.
```
Comment (5kbpers) [inline components/cdc/src/observer.rs:133]: Sometimes it is not true, the type of mutation is decided by TiDB, see https://github.com/tikv/tikv/pull/9872

File: components/txn_types/src/types.rs [hunk 2]
```diff
@@ -347,10 +346,7 @@ impl OldValue {
 
     pub fn size(&self) -> usize {
         let value_size = match self {
-            OldValue::Value {
-                short_value: Some(v),
-                ..
-            } => v.len(),
+            OldValue::Value { value } => value.len(),
```
Comment (5kbpers) [inline components/txn_types/src/types.rs:349]: The size of `ValueTimeStamp` is not zero.

**Review by 5kbpers — COMMENTED** [review]
rest LGTM

File: components/txn_types/src/types.rs (hunk 2 above)
Comment (overvenus) [reply components/txn_types/src/types.rs:349]: `std::mem::size_of::<OldValue>()` computes OldValue enum size, inlcuding `ValueTimeStamp`.

File: src/storage/txn/actions/acquire_pessimistic_lock.rs [hunk 3]
```diff
@@ -73,10 +114,17 @@ pub fn acquire_pessimistic_lock<S: Snapshot>(
...
+        return Ok((val, old_value));
     }
 
+    // Following seek_write read the previous write.
+    let (prev_write_loaded, mut prev_write) = (true, None);
     if let Some((commit_ts, write)) = reader.seek_write(&key, TimeStamp::max())? {
+        // Find a previous write.
+        if need_old_value {
+            prev_write = Some(write.clone());
+        }
```
Comment (MyonKeminta) [inline src/storage/txn/actions/acquire_pessimistic_lock.rs:126]: There should be some way to avoid the cloning by moving `write` to `prev_write` and use `prev_write` instead of `write` in the if block. But it's ok to me since the current code looks clear.

**Review by MyonKeminta — APPROVED** [review]
LGTM

File: src/storage/txn/actions/acquire_pessimistic_lock.rs (hunk 3 above)
Comment (overvenus) [reply src/storage/txn/actions/acquire_pessimistic_lock.rs:126]: It is possible to avoid clone when need_value is false, though it may make code more complicated.
