### PR TITLE
snapshot: encrypt lock cf correctly in receiving

### LINKED ISSUE #7881: encryption: TiKV crashed due to applying snapshot failed
### What version of TiKV are you using?

latest release-4.0 (2fdb2804bf8ffaab4b18c4996970e19906296497)

### What operating system and CPU are you using?

Linux 3.10.0-957.el7.x86_64
Intel(R) Xeon(R) CPU E5-2630 v4

### Steps to reproduce

I enabled tikv encryption and used sysbench to prepare data, here is the command:
```sh
sysbench oltp_common     --threads=16     --rand-type=uniform     --db-driver=mysql     --mysql-db=sbtest     --mysql-host=$tidb_host     --mysql-port=4000     --mysql-user=root     prepare --tables=16 --table-size=10000000
```

### What did you expect?

No server crashes.

### What did happened?

One of tikv-server crashed with the following log and cannot serve again.
<details>
[2020/05/19 07:50:37.094 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=c9a082e22d3af4b0d5f6c2c4811004ae] [method=Aes192Ctr] [fname=/var/lib/tikv/db/027495.sst]
[2020/05/19 07:50:37.177 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=8b559df2ba111cd9891f247877f14194] [method=Aes192Ctr] [fname=/var/lib/tikv/db/027496.sst]
[2020/05/19 07:50:37.189 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=b99ff1a42c6926849586f7350fe85713] [method=Aes192Ctr] [fname=/var/lib/tikv/db/027497.sst]
[2020/05/19 07:50:37.192 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=fae798c9bafea44f57e024ca499adf86] [method=Aes192Ctr] [fname=/var/lib/tikv/db/027498.sst]
[2020/05/19 07:50:37.197 +00:00] [INFO] [apply.rs:1142] ["execute admin command"] [command="cmd_type: BatchSplit splits { requests { split_key: 7480000000000000FF745F698000000000FF0000010380000000FF0058FEF903800000FF00002B1200000000FC new_region_id: 2613 new_peer_ids: 2614 new_peer_ids: 2615 new_peer_ids: 2616 } right_derive: true }"] [index=8162] [term=9] [peer_id=2270] [region_id=2269]
[2020/05/19 07:50:37.197 +00:00] [INFO] [apply.rs:1710] ["split region"] [keys="key 7480000000000000FF745F698000000000FF0000010380000000FF0058FEF903800000FF00002B1200000000FC"] [region="id: 2269 start_key: 7480000000000000FF745F698000000000FF0000010380000000FF003E09C403800000FF000005CCD5000000FC end_key: 7480000000000000FF745F698000000000FF0000010380000000FF0067A60D03800000FF00000D786C000000FC region_epoch { conf_ver: 5 version: 56 } peers { id: 2270 store_id: 1 } peers { id: 2271 store_id: 4 } peers { id: 2272 store_id: 5 }"] [peer_id=2270] [region_id=2269]
[2020/05/19 07:50:37.234 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=bca753e243e02cbab75c42b6ab2fe6d6] [method=Aes192Ctr] [fname=/var/lib/tikv/snap/rev_2069_8_85311_lock.sst]
[2020/05/19 07:50:37.238 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=5a29f7b91798e923e6812d2f020f8f70] [method=Aes192Ctr] [fname=/var/lib/tikv/snap/rev_2069_8_85311_write.sst]
[2020/05/19 07:50:37.261 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=e730cb7ce92d1b08e28468e589911b3d] [method=Aes192Ctr] [fname=/var/lib/tikv/db/027499.log]
[2020/05/19 07:50:37.265 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=7d1d436048c2fc79a92a1f109fadbdcf] [method=Aes192Ctr] [fname=/var/lib/tikv/db/027500.sst]
[2020/05/19 07:50:37.267 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=85bbc5340114042e2b09e8fd63c19aee] [method=Aes192Ctr] [fname=/var/lib/tikv/db/027501.sst]
[2020/05/19 07:50:37.293 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=dce56f1c9db166c3b08e42a6ec4d3468] [method=Aes192Ctr] [fname=/var/lib/tikv/db/027502.sst]
[2020/05/19 07:50:37.386 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=a809c3db15b7732553993fbe20d5b5b0] [method=Aes192Ctr] [fname=/var/lib/tikv/db/027503.sst]
[2020/05/19 07:50:37.476 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=deadd6c75f0d190370aab598ebc568fd] [method=Aes192Ctr] [fname=/var/lib/tikv/db/027504.sst]
[2020/05/19 07:50:37.654 +00:00] [INFO] [peer.rs:1657] ["insert new region"] [region="id: 2613 start_key: 7480000000000000FF745F698000000000FF0000010380000000FF003E09C403800000FF000005CCD5000000FC end_key: 7480000000000000FF745F698000000000FF0000010380000000FF0058FEF903800000FF00002B1200000000FC region_epoch { conf_ver: 5 version: 57 } peers { id: 2614 store_id: 1 } peers { id: 2615 store_id: 4 } peers { id: 2616 store_id: 5 }"] [region_id=2613]
[2020/05/19 07:50:37.654 +00:00] [INFO] [peer.rs:147] ["create peer"] [peer_id=2614] [region_id=2613]
[2020/05/19 07:50:37.654 +00:00] [INFO] [raft.rs:809] ["became follower at term 5"] [term=5] [raft_id=2614] [region_id=2613]
[2020/05/19 07:50:37.654 +00:00] [INFO] [raft.rs:288] [newRaft] [peers="[(2616, Progress { matched: 0, next_idx: 6, state: Probe, paused: false, pending_snapshot: 0, pending_request_snapshot: 0, recent_active: false, ins: Inflights { start: 0, count: 0, buffer: [] } }), (2614, Progress { matched: 5, next_idx: 6, state: Probe, paused: false, pending_snapshot: 0, pending_request_snapshot: 0, recent_active: false, ins: Inflights { start: 0, count: 0, buffer: [] } }), (2615, Progress { matched: 0, next_idx: 6, state: Probe, paused: false, pending_snapshot: 0, pending_request_snapshot: 0, recent_active: false, ins: Inflights { start: 0, count: 0, buffer: [] } })]"] ["last term"=5] ["last index"=5] [applied=5] [commit=5] [term=5] [raft_id=2614] [region_id=2613]
[2020/05/19 07:50:37.654 +00:00] [INFO] [raw_node.rs:222] ["RawNode created with id 2614."] [id=2614] [raft_id=2614] [region_id=2613]
[2020/05/19 07:50:37.654 +00:00] [INFO] [raft.rs:1218] ["[logterm: 5, index: 5, vote: 0] cast vote for 2615 [logterm: 5, index: 5] at term 5"] ["msg type"=MsgRequestPreVote] [term=5] [msg_index=5] [msg_term=5] [from=2615] [vote=0] [log_index=5] [log_term=5] [raft_id=2614] [region_id=2613]
[2020/05/19 07:50:37.666 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=672afcc63d0ec6e09be3c4710996196f] [method=Aes192Ctr] [fname=/var/lib/tikv/db/027505.sst]
[2020/05/19 07:50:37.685 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=14106b47236381563d811ddf0f0e72fb] [method=Aes192Ctr] [fname=/var/lib/tikv/db/027506.sst]
[2020/05/19 07:50:37.700 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=784f2d9686c3a0da409096298abef96c] [method=Aes192Ctr] [fname=/var/lib/tikv/db/027507.sst]
[2020/05/19 07:50:37.803 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=904ca0b19620c3f28f703b68caf8f8da] [method=Aes192Ctr] [fname=/var/lib/tikv/db/027508.sst]
[2020/05/19 07:50:37.842 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=67f8dd6ae76bc055a7dc65e8db068608] [method=Aes192Ctr] [fname=/var/lib/tikv/raft/015021.log]
[2020/05/19 07:50:37.846 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=33b73309706d4c75dfd0a0e594be8981] [method=Aes192Ctr] [fname=/var/lib/tikv/raft/015022.sst]
[2020/05/19 07:50:37.850 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=786ae8a13c27b1e0e8e5d29de672f7f1] [method=Aes192Ctr] [fname=/var/lib/tikv/db/027509.sst]
[2020/05/19 07:50:37.885 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=9ba300e145c78a989246a09878854541] [method=Aes192Ctr] [fname=/var/lib/tikv/db/027510.sst]
[2020/05/19 07:50:38.072 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=7161efcd5e49ca9bfc54c30252cbd563] [method=Aes192Ctr] [fname=/var/lib/tikv/db/027511.sst]
[2020/05/19 07:50:38.185 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=74ef8b660f6432fb9df8aec1809ecf7b] [method=Aes192Ctr] [fname=/var/lib/tikv/db/027512.sst]
[2020/05/19 07:50:38.287 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=ee07abfe956b9f04f75b932e449d6edb] [method=Aes192Ctr] [fname=/var/lib/tikv/db/027513.log]
[2020/05/19 07:50:38.348 +00:00] [INFO] [mod.rs:194] ["delete encrypted file"] [fname=/var/lib/tikv/db/027305.sst]
[2020/05/19 07:50:38.351 +00:00] [INFO] [mod.rs:194] ["delete encrypted file"] [fname=/var/lib/tikv/db/026845.sst]
[2020/05/19 07:50:38.357 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=11c769c2cfc31e05da8f42815608fafb] [method=Aes192Ctr] [fname=/var/lib/tikv/db/027514.sst]
[2020/05/19 07:50:38.392 +00:00] [INFO] [mod.rs:194] ["delete encrypted file"] [fname=/var/lib/tikv/raft/015019.log]
[2020/05/19 07:50:38.396 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=dc54b69de8ad4aa9eb2acff5e8c847cb] [method=Aes192Ctr] [fname=/var/lib/tikv/db/027515.sst]
[2020/05/19 07:50:38.463 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=07beed912495939b93dac4eb40846255] [method=Aes192Ctr] [fname=/var/lib/tikv/db/027516.sst]
[2020/05/19 07:50:38.529 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=fb5fd492f69caf0b6033e4e70e472cb6] [method=Aes192Ctr] [fname=/var/lib/tikv/db/027517.sst]
[2020/05/19 07:50:38.535 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=7dab6281e40f82c5dfb2902b3b12fabe] [method=Aes192Ctr] [fname=/var/lib/tikv/db/027518.sst]
[2020/05/19 07:50:38.632 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=d22d03b3b8e33a1a9fdcefa7631f36b4] [method=Aes192Ctr] [fname=/var/lib/tikv/db/027519.sst]
[2020/05/19 07:50:38.637 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=fa365da9c39650857844eec77b295a8b] [method=Aes192Ctr] [fname=/var/lib/tikv/snap/rev_2057_7_122496_lock.sst]
[2020/05/19 07:50:38.653 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=5364388acf883c9ac901bc5326cb1e75] [method=Aes192Ctr] [fname=/var/lib/tikv/snap/rev_2057_7_122496_write.sst]
[2020/05/19 07:50:38.661 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=dd3693e4861e43760eea4810d893dd5f] [method=Aes192Ctr] [fname=/var/lib/tikv/db/027520.log]
[2020/05/19 07:50:38.745 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=d4d575053a63ada69b57bedeeefe6479] [method=Aes192Ctr] [fname=/var/lib/tikv/db/027521.sst]
[2020/05/19 07:50:38.771 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=b1d1b288fc1e4491f0ca6b3c8c1bb681] [method=Aes192Ctr] [fname=/var/lib/tikv/db/027522.sst]
[2020/05/19 07:50:38.835 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=22434eb9078f36d617845a15470a978c] [method=Aes192Ctr] [fname=/var/lib/tikv/db/027523.sst]
[2020/05/19 07:50:38.842 +00:00] [INFO] [raft.rs:1029] ["received a message with higher term from 2615"] ["msg type"=MsgHeartbeat] [message_term=6] [term=5] [from=2615] [raft_id=2614] [region_id=2613]
[2020/05/19 07:50:38.842 +00:00] [INFO] [raft.rs:809] ["became follower at term 6"] [term=6] [raft_id=2614] [region_id=2613]
[2020/05/19 07:50:38.942 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=f54dd995977ab528493cadbd4ec67551] [method=Aes192Ctr] [fname=/var/lib/tikv/db/027524.sst]
[2020/05/19 07:50:39.089 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=41e3dabdc4bcc3e68c96cf890a693c9f] [method=Aes192Ctr] [fname=/var/lib/tikv/db/027525.sst]
[2020/05/19 07:50:39.142 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=5101d190f87c16be9d26d18d24d228b6] [method=Aes192Ctr] [fname=/var/lib/tikv/db/027526.sst]
[2020/05/19 07:50:39.255 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=dcf16df7e8b4c26e9f9218e67e2f31cc] [method=Aes192Ctr] [fname=/var/lib/tikv/db/027527.sst]
[2020/05/19 07:50:39.280 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=fb2f0c21063a13325b4074c93084d4cc] [method=Aes192Ctr] [fname=/var/lib/tikv/db/027528.sst]
[2020/05/19 07:50:39.342 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=b4afc19964d34b901ce2ca34484d8a23] [method=Aes192Ctr] [fname=/var/lib/tikv/db/027529.sst]
[2020/05/19 07:50:39.343 +00:00] [INFO] [keys.rs:154] ["approximate keys over threshold, need to do split check"] [threshold=1440000] [keys=1503898] [region_id=2373]
[2020/05/19 07:50:39.429 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=d9fcc6148810b905b087bbe0cc0657cb] [method=Aes192Ctr] [fname=/var/lib/tikv/db/027530.sst]
[2020/05/19 07:50:39.441 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=3effbd22a4be7bbdf0e43343697c57ca] [method=Aes192Ctr] [fname=/var/lib/tikv/raft/015023.sst]
[2020/05/19 07:50:39.444 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=31e4c8af22fc0c65a07c31f5738779a6] [method=Aes192Ctr] [fname=/var/lib/tikv/raft/015024.sst]
[2020/05/19 07:50:39.455 +00:00] [INFO] [mod.rs:194] ["delete encrypted file"] [fname=/var/lib/tikv/db/027476.sst]
[2020/05/19 07:50:39.462 +00:00] [INFO] [mod.rs:194] ["delete encrypted file"] [fname=/var/lib/tikv/db/027455.sst]
[2020/05/19 07:50:39.472 +00:00] [INFO] [mod.rs:194] ["delete encrypted file"] [fname=/var/lib/tikv/db/027450.sst]
[2020/05/19 07:50:39.480 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=97afab6e4cd59cec1150e7e1c19ff7c8] [method=Aes192Ctr] [fname=/var/lib/tikv/db/027531.sst]
[2020/05/19 07:50:39.534 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=16bd407d892be55bfb679fa9a81cb65c] [method=Aes192Ctr] [fname=/var/lib/tikv/db/027532.sst]
[2020/05/19 07:50:39.557 +00:00] [INFO] [mod.rs:194] ["delete encrypted file"] [fname=/var/lib/tikv/db/027500.sst]
[2020/05/19 07:50:39.562 +00:00] [INFO] [mod.rs:194] ["delete encrypted file"] [fname=/var/lib/tikv/db/027479.sst]
[2020/05/19 07:50:39.568 +00:00] [INFO] [mod.rs:194] ["delete encrypted file"] [fname=/var/lib/tikv/db/027478.sst]
[2020/05/19 07:50:39.570 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=fbfa14493976f6daf4ed67925e6e32dd] [method=Aes192Ctr] [fname=/var/lib/tikv/db/027533.sst]
[2020/05/19 07:50:39.574 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=e0676fce91e63f15ea94d09455d6cebe] [method=Aes192Ctr] [fname=/var/lib/tikv/db/027534.log]
[2020/05/19 07:50:39.580 +00:00] [INFO] [mod.rs:194] ["delete encrypted file"] [fname=/var/lib/tikv/db/027465.sst]
[2020/05/19 07:50:39.598 +00:00] [INFO] [mod.rs:194] ["delete encrypted file"] [fname=/var/lib/tikv/db/027463.sst]
[2020/05/19 07:50:39.632 +00:00] [INFO] [mod.rs:194] ["delete encrypted file"] [fname=/var/lib/tikv/db/027396.sst]
[2020/05/19 07:50:39.641 +00:00] [INFO] [mod.rs:194] ["delete encrypted file"] [fname=/var/lib/tikv/db/027348.sst]
[2020/05/19 07:50:39.647 +00:00] [INFO] [mod.rs:194] ["delete encrypted file"] [fname=/var/lib/tikv/db/027311.sst]
[2020/05/19 07:50:39.655 +00:00] [INFO] [mod.rs:194] ["delete encrypted file"] [fname=/var/lib/tikv/db/027306.sst]
[2020/05/19 07:50:39.660 +00:00] [INFO] [mod.rs:194] ["delete encrypted file"] [fname=/var/lib/tikv/db/027304.sst]
[2020/05/19 07:50:39.667 +00:00] [INFO] [mod.rs:194] ["delete encrypted file"] [fname=/var/lib/tikv/db/027302.sst]
[2020/05/19 07:50:39.672 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=ef47e1f3a1d81872bf00ccf68221b9ca] [method=Aes192Ctr] [fname=/var/lib/tikv/raft/015025.sst]
[2020/05/19 07:50:39.676 +00:00] [INFO] [mod.rs:194] ["delete encrypted file"] [fname=/var/lib/tikv/db/027300.sst]
[2020/05/19 07:50:39.681 +00:00] [INFO] [mod.rs:194] ["delete encrypted file"] [fname=/var/lib/tikv/db/027297.sst]
[2020/05/19 07:50:39.688 +00:00] [INFO] [mod.rs:194] ["delete encrypted file"] [fname=/var/lib/tikv/db/027294.sst]
[2020/05/19 07:50:39.693 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=a40412d27a475a6c1abef7da8622cd84] [method=Aes192Ctr] [fname=/var/lib/tikv/db/027535.sst]
[2020/05/19 07:50:39.735 +00:00] [INFO] [mod.rs:194] ["delete encrypted file"] [fname=/var/lib/tikv/db/027291.sst]
[2020/05/19 07:50:39.739 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=7fa386a1c2a9d3a9aabd237815fcac16] [method=Aes192Ctr] [fname=/var/lib/tikv/db/027536.sst]
[2020/05/19 07:50:39.752 +00:00] [INFO] [mod.rs:194] ["delete encrypted file"] [fname=/var/lib/tikv/db/027289.sst]
[2020/05/19 07:50:39.756 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=7b5b2ed68c30b97b09f43745db832720] [method=Aes192Ctr] [fname=/var/lib/tikv/raft/015026.sst]
[2020/05/19 07:50:39.763 +00:00] [INFO] [mod.rs:194] ["delete encrypted file"] [fname=/var/lib/tikv/db/027203.sst]
[2020/05/19 07:50:39.769 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=80c13ba3b98571256d6f06db980440ab] [method=Aes192Ctr] [fname=/var/lib/tikv/raft/015027.sst]
[2020/05/19 07:50:39.773 +00:00] [INFO] [mod.rs:194] ["delete encrypted file"] [fname=/var/lib/tikv/db/027168.sst]
[2020/05/19 07:50:39.781 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=15942cccd236b75f9f2e4dbb809eff8a] [method=Aes192Ctr] [fname=/var/lib/tikv/db/027537.sst]
[2020/05/19 07:50:39.792 +00:00] [INFO] [mod.rs:194] ["delete encrypted file"] [fname=/var/lib/tikv/db/027162.sst]
[2020/05/19 07:50:39.831 +00:00] [INFO] [mod.rs:194] ["delete encrypted file"] [fname=/var/lib/tikv/db/027127.sst]
[2020/05/19 07:50:39.837 +00:00] [INFO] [mod.rs:194] ["delete encrypted file"] [fname=/var/lib/tikv/db/027097.sst]
[2020/05/19 07:50:39.844 +00:00] [INFO] [mod.rs:194] ["delete encrypted file"] [fname=/var/lib/tikv/db/026892.sst]
[2020/05/19 07:50:39.852 +00:00] [INFO] [mod.rs:194] ["delete encrypted file"] [fname=/var/lib/tikv/db/026881.sst]
[2020/05/19 07:50:39.935 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=e975556e3692f0c34e86ea66719fe020] [method=Aes192Ctr] [fname=/var/lib/tikv/raft/015028.sst]
[2020/05/19 07:50:39.964 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=7d4a776237fec9ca2b52e2a47fe5f18f] [method=Aes192Ctr] [fname=/var/lib/tikv/db/027538.sst]
[2020/05/19 07:50:39.968 +00:00] [INFO] [snap.rs:223] ["saving snapshot file"] [file=/var/lib/tikv/snap/rev_2069_8_85311_(default|lock|write).sst] [snap_key=2069_8_85311]
[2020/05/19 07:50:39.968 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=29a5c54e45dfaeffd26868545659073e] [method=Aes192Ctr] [fname=/var/lib/tikv/raft/015029.sst]
[2020/05/19 07:50:39.971 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=18bb0a3e436b2acabb9d31c8896e167a] [method=Aes192Ctr] [fname=/var/lib/tikv/db/027539.sst]
[2020/05/19 07:50:39.988 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=2a733c3c9faca5888d119d4005131379] [method=Aes192Ctr] [fname=/var/lib/tikv/raft/015030.sst]
[2020/05/19 07:50:40.042 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=be1bc214d47bd359221ad474dc5c7902] [method=Aes192Ctr] [fname=/var/lib/tikv/db/027540.sst]
[2020/05/19 07:50:40.061 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=6b1d07875a00b3022fd43cb528a512f0] [method=Aes192Ctr] [fname=/var/lib/tikv/db/027541.sst]
[2020/05/19 07:50:40.067 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=4c396dfa2d3e587644ba098089b51dff] [method=Aes192Ctr] [fname=/var/lib/tikv/db/027542.sst]
[2020/05/19 07:50:40.249 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=c5dd8de66fbaab98774cf94e80bad86a] [method=Aes192Ctr] [fname=/var/lib/tikv/raft/015031.sst]
[2020/05/19 07:50:40.254 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=16083f414b922136d084c2f854bba24b] [method=Aes192Ctr] [fname=/var/lib/tikv/raft/015032.sst]
[2020/05/19 07:50:40.261 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=75cc993ececfd462b88b2a1cf5530eef] [method=Aes192Ctr] [fname=/var/lib/tikv/db/027543.sst]
[2020/05/19 07:50:40.279 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=4c4f169572110305dc2ac00403bc16c3] [method=Aes192Ctr] [fname=/var/lib/tikv/db/027544.sst]
[2020/05/19 07:50:40.286 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=cd0f88e64b55fa1285197072c12ee71e] [method=Aes192Ctr] [fname=/var/lib/tikv/db/027545.sst]
[2020/05/19 07:50:40.286 +00:00] [INFO] [raft.rs:2020] ["[commit: 84530, lastindex: 84530, lastterm: 8] starts to restore snapshot [index: 85311, term: 8]"] [snapshot_term=8] [snapshot_index=85311] [last_term=8] [last_index=84530] [commit=84530] [raft_id=2070] [region_id=2069]
[2020/05/19 07:50:40.286 +00:00] [INFO] [raft_log.rs:487] ["log [committed=84530, applied=84530, unstable.offset=84531, unstable.entries.len()=0] starts to restore snapshot [index: 85311, term: 8]"] [snapshot_term=8] [snapshot_index=85311] [log="committed=84530, applied=84530, unstable.offset=84531, unstable.entries.len()=0"] [raft_id=2070] [region_id=2069]
[2020/05/19 07:50:40.286 +00:00] [INFO] [raft.rs:1956] ["[commit: 85311, term: 8] restored snapshot [index: 85311, term: 8]"] [snapshot_term=8] [snapshot_index=85311] [commit=85311] [term=8] [raft_id=2070] [region_id=2069]
[2020/05/19 07:50:40.287 +00:00] [INFO] [peer_storage.rs:985] ["begin to apply snapshot"] [peer_id=2070] [region_id=2069]
[2020/05/19 07:50:40.371 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=16da2627bd8feef66b7a995293e057d1] [method=Aes192Ctr] [fname=/var/lib/tikv/raft/015033.sst]
[2020/05/19 07:50:40.373 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=7e9819cb16daf4470580bc992ad3d84c] [method=Aes192Ctr] [fname=/var/lib/tikv/raft/015034.sst]
[2020/05/19 07:50:40.472 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=b01a6acc70c0b3e9b0600b9bdd5b29d8] [method=Aes192Ctr] [fname=/var/lib/tikv/raft/015035.sst]
[2020/05/19 07:50:40.477 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=5e41f55bc8784f1cf27fe387cac44975] [method=Aes192Ctr] [fname=/var/lib/tikv/raft/015036.sst]
[2020/05/19 07:50:40.538 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=cc29404b61f97a3833161e0c07a26b5b] [method=Aes192Ctr] [fname=/var/lib/tikv/db/027546.sst]
[2020/05/19 07:50:40.543 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=1bf916706e2c102babe0dcf3b684f8da] [method=Aes192Ctr] [fname=/var/lib/tikv/db/027547.sst]
[2020/05/19 07:50:40.553 +00:00] [INFO] [split_check.rs:283] ["update approximate size and keys with accurate value"] [keys=1535422] [size=102976224] [region_id=2373]
[2020/05/19 07:50:40.555 +00:00] [INFO] [snap.rs:223] ["saving snapshot file"] [file=/var/lib/tikv/snap/rev_2057_7_122496_(default|lock|write).sst] [snap_key=2057_7_122496]
[2020/05/19 07:50:40.561 +00:00] [INFO] [mod.rs:194] ["delete encrypted file"] [fname=/var/lib/tikv/db/027445.sst]
[2020/05/19 07:50:40.568 +00:00] [INFO] [mod.rs:194] ["delete encrypted file"] [fname=/var/lib/tikv/db/027444.sst]
[2020/05/19 07:50:40.573 +00:00] [INFO] [mod.rs:194] ["delete encrypted file"] [fname=/var/lib/tikv/db/027443.sst]
[2020/05/19 07:50:40.577 +00:00] [INFO] [mod.rs:194] ["delete encrypted file"] [fname=/var/lib/tikv/db/027442.sst]
[2020/05/19 07:50:40.578 +00:00] [WARN] [mod.rs:89] ["handle task [split check worker] Split Check Task for 2373, auto_split: true"] [takes=1235]
[2020/05/19 07:50:40.581 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=e352ebdc0a8e62618ed61f007bd124a0] [method=Aes192Ctr] [fname=/var/lib/tikv/raft/015037.sst]
[2020/05/19 07:50:40.661 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=e71a2be39ad9e2cb26142038468c696a] [method=Aes192Ctr] [fname=/var/lib/tikv/raft/015038.sst]
[2020/05/19 07:50:40.703 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=16ef655f6958faee8538536ce5859387] [method=Aes192Ctr] [fname=/var/lib/tikv/raft/015039.sst]
[2020/05/19 07:50:40.736 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=3d81239b8c79b0fb4e5f8abf4d61a494] [method=Aes192Ctr] [fname=/var/lib/tikv/db/027548.sst]
[2020/05/19 07:50:40.784 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=53571b3b41c3a6f366183c11f6882252] [method=Aes192Ctr] [fname=/var/lib/tikv/raft/015040.sst]
[2020/05/19 07:50:40.788 +00:00] [INFO] [mod.rs:194] ["delete encrypted file"] [fname=/var/lib/tikv/db/027489.sst]
[2020/05/19 07:50:40.793 +00:00] [INFO] [mod.rs:194] ["delete encrypted file"] [fname=/var/lib/tikv/db/027464.sst]
[2020/05/19 07:50:40.798 +00:00] [INFO] [mod.rs:194] ["delete encrypted file"] [fname=/var/lib/tikv/db/027456.sst]
[2020/05/19 07:50:40.804 +00:00] [INFO] [mod.rs:194] ["delete encrypted file"] [fname=/var/lib/tikv/db/027452.sst]
[2020/05/19 07:50:40.831 +00:00] [INFO] [mod.rs:194] ["delete encrypted file"] [fname=/var/lib/tikv/db/027373.sst]
[2020/05/19 07:50:40.835 +00:00] [INFO] [mod.rs:194] ["delete encrypted file"] [fname=/var/lib/tikv/db/027370.sst]
[2020/05/19 07:50:40.840 +00:00] [INFO] [mod.rs:194] ["delete encrypted file"] [fname=/var/lib/tikv/db/027367.sst]
[2020/05/19 07:50:40.844 +00:00] [INFO] [mod.rs:194] ["delete encrypted file"] [fname=/var/lib/tikv/db/027364.sst]
[2020/05/19 07:50:40.847 +00:00] [INFO] [mod.rs:194] ["delete encrypted file"] [fname=/var/lib/tikv/db/027362.sst]
[2020/05/19 07:50:40.852 +00:00] [INFO] [mod.rs:194] ["delete encrypted file"] [fname=/var/lib/tikv/db/027360.sst]
[2020/05/19 07:50:40.857 +00:00] [INFO] [mod.rs:194] ["delete encrypted file"] [fname=/var/lib/tikv/db/027192.sst]
[2020/05/19 07:50:40.862 +00:00] [INFO] [mod.rs:194] ["delete encrypted file"] [fname=/var/lib/tikv/db/027169.sst]
[2020/05/19 07:50:40.866 +00:00] [INFO] [mod.rs:194] ["delete encrypted file"] [fname=/var/lib/tikv/db/027167.sst]
[2020/05/19 07:50:40.869 +00:00] [INFO] [mod.rs:194] ["delete encrypted file"] [fname=/var/lib/tikv/db/027165.sst]
[2020/05/19 07:50:40.874 +00:00] [INFO] [mod.rs:194] ["delete encrypted file"] [fname=/var/lib/tikv/db/024743.sst]
[2020/05/19 07:50:40.879 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=32024fd984056213177e426f92f58eaa] [method=Aes192Ctr] [fname=/var/lib/tikv/db/027549.sst]
[2020/05/19 07:50:40.940 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=154ae5ea57e1e2c28dd7d296d1f63163] [method=Aes192Ctr] [fname=/var/lib/tikv/raft/015041.sst]
[2020/05/19 07:50:40.943 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=58d16124623c81bc10cc4c18b39c3f77] [method=Aes192Ctr] [fname=/var/lib/tikv/raft/015042.sst]
[2020/05/19 07:50:40.966 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=b350056b9981c3aff6bb0a49696a700b] [method=Aes192Ctr] [fname=/var/lib/tikv/db/027550.sst]
[2020/05/19 07:50:40.986 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=3da629b22165ba0623c94c21d6e225c9] [method=Aes192Ctr] [fname=/var/lib/tikv/db/027551.sst]
[2020/05/19 07:50:41.036 +00:00] [INFO] [peer_storage.rs:1413] ["finish clear peer meta"] [takes=749.048682ms] [raft_logs=1815] [raft_key=1] [apply_key=1] [meta_key=1] [region_id=2069]
[2020/05/19 07:50:41.046 +00:00] [INFO] [peer_storage.rs:1025] ["apply snapshot with state ok"] [state="applied_index: 85311 last_commit_index: 84525 commit_index: 84530 commit_term: 8 truncated_state { index: 85311 term: 8 }"] [region="id: 2069 start_key: 7480000000000000FF745F728000000000FF4E9A800000000000FA end_key: 7480000000000000FF7A00000000000000F8 region_epoch { conf_ver: 5 version: 65 } peers { id: 2070 store_id: 1 } peers { id: 2071 store_id: 4 } peers { id: 2072 store_id: 5 }"] [peer_id=2070] [region_id=2069]
[2020/05/19 07:50:41.049 +00:00] [INFO] [apply.rs:2531] ["re-register to apply delegates"] [term=8] [peer_id=2070] [region_id=2069]
[2020/05/19 07:50:41.049 +00:00] [INFO] [region_info_accessor.rs:223] ["trying to create region but it already exists, try to update it"] [region_id=2069]
[2020/05/19 07:50:41.049 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=a1eccc8cc1487b5e41e0d88bdde84de4] [method=Aes192Ctr] [fname=/var/lib/tikv/raft/015043.sst]
[2020/05/19 07:50:41.056 +00:00] [INFO] [region.rs:290] ["begin apply snap data"] [region_id=2069]
[2020/05/19 07:50:41.087 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=c0e9e1b1b361c287d08ad61830d136dc] [method=Aes192Ctr] [fname=/var/lib/tikv/db/027552.log]
[2020/05/19 07:50:41.095 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=c37641639be3796efbdccf6ce716515e] [method=Aes192Ctr] [fname=/var/lib/tikv/db/027553.sst]
[2020/05/19 07:50:41.108 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=5fcd849e3af68ae057037d74108e7810] [method=Aes192Ctr] [fname=/var/lib/tikv/raft/015044.sst]
[2020/05/19 07:50:41.146 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=6f33272fc09dae4bd9b0bf68373beaa4] [method=Aes192Ctr] [fname=/var/lib/tikv/db/027554.sst]
[2020/05/19 07:50:41.178 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=db56172dd4865015e729012cc15d710f] [method=Aes192Ctr] [fname=/var/lib/tikv/db/027555.sst]
[2020/05/19 07:50:41.314 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=d67def329cee29ec96c2a18ca462edf7] [method=Aes192Ctr] [fname=/var/lib/tikv/raft/015045.sst]
[2020/05/19 07:50:41.320 +00:00] [INFO] [raft.rs:2020] ["[commit: 121673, lastindex: 121673, lastterm: 7] starts to restore snapshot [index: 122496, term: 7]"] [snapshot_term=7] [snapshot_index=122496] [last_term=7] [last_index=121673] [commit=121673] [raft_id=2058] [region_id=2057]
[2020/05/19 07:50:41.321 +00:00] [INFO] [raft_log.rs:487] ["log [committed=121673, applied=121673, unstable.offset=121674, unstable.entries.len()=0] starts to restore snapshot [index: 122496, term: 7]"] [snapshot_term=7] [snapshot_index=122496] [log="committed=121673, applied=121673, unstable.offset=121674, unstable.entries.len()=0"] [raft_id=2058] [region_id=2057]
[2020/05/19 07:50:41.321 +00:00] [INFO] [raft.rs:1956] ["[commit: 122496, term: 7] restored snapshot [index: 122496, term: 7]"] [snapshot_term=7] [snapshot_index=122496] [commit=122496] [term=7] [raft_id=2058] [region_id=2057]
[2020/05/19 07:50:41.321 +00:00] [INFO] [peer.rs:2200] ["snapshot is applied"] [region="id: 2069 start_key: 7480000000000000FF745F728000000000FF4E9A800000000000FA end_key: 7480000000000000FF7A00000000000000F8 region_epoch { conf_ver: 5 version: 65 } peers { id: 2070 store_id: 1 } peers { id: 2071 store_id: 4 } peers { id: 2072 store_id: 5 }"] [peer_id=2070] [region_id=2069]
[2020/05/19 07:50:41.321 +00:00] [INFO] [peer.rs:2216] ["region changed after applying snapshot"] [region="id: 2069 start_key: 7480000000000000FF745F728000000000FF4E9A800000000000FA end_key: 7480000000000000FF7A00000000000000F8 region_epoch { conf_ver: 5 version: 65 } peers { id: 2070 store_id: 1 } peers { id: 2071 store_id: 4 } peers { id: 2072 store_id: 5 }"] [prev_region="id: 2069 start_key: 7480000000000000FF745F728000000000FF484CE00000000000FA end_key: 7480000000000000FF7A00000000000000F8 region_epoch { conf_ver: 5 version: 64 } peers { id: 2070 store_id: 1 } peers { id: 2071 store_id: 4 } peers { id: 2072 store_id: 5 }"] [peer_id=2070] [region_id=2069]
[2020/05/19 07:50:41.370 +00:00] [INFO] [peer_storage.rs:985] ["begin to apply snapshot"] [peer_id=2058] [region_id=2057]
[2020/05/19 07:50:41.370 +00:00] [WARN] [store.rs:595] ["[store 1] handle 5 pending peers include 5 ready, 2 entries, 7 messages and 1 snapshots"] [takes=1400]
[2020/05/19 07:50:41.370 +00:00] [INFO] [peer.rs:181] ["replicate peer"] [peer_id=2610] [region_id=2609]
[2020/05/19 07:50:41.370 +00:00] [INFO] [raft.rs:809] ["became follower at term 0"] [term=0] [raft_id=2610] [region_id=2609]
[2020/05/19 07:50:41.370 +00:00] [INFO] [raft.rs:288] [newRaft] [peers="[]"] ["last term"=0] ["last index"=0] [applied=0] [commit=0] [term=0] [raft_id=2610] [region_id=2609]
[2020/05/19 07:50:41.370 +00:00] [INFO] [raw_node.rs:222] ["RawNode created with id 2610."] [id=2610] [raft_id=2610] [region_id=2609]
[2020/05/19 07:50:41.442 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=3f920c78891a98b5d2fa5c916869ec73] [method=Aes192Ctr] [fname=/var/lib/tikv/db/027556.sst]
[2020/05/19 07:50:41.485 +00:00] [INFO] [raft.rs:1029] ["received a message with higher term from 2612"] ["msg type"=MsgHeartbeat] [message_term=6] [term=0] [from=2612] [raft_id=2610] [region_id=2609]
[2020/05/19 07:50:41.485 +00:00] [INFO] [raft.rs:809] ["became follower at term 6"] [term=6] [raft_id=2610] [region_id=2609]
[2020/05/19 07:50:41.486 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=29fd752e82034f89cb7b113b991857c2] [method=Aes192Ctr] [fname=/var/lib/tikv/raft/015046.sst]
[2020/05/19 07:50:41.507 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=18ab502c81d556a4db72b40f7d05390f] [method=Aes192Ctr] [fname=/var/lib/tikv/raft/015047.sst]
[2020/05/19 07:50:41.511 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=7f2c764bf79e6f7076f685ffed3ab75c] [method=Aes192Ctr] [fname=/var/lib/tikv/db/027557.sst]
[2020/05/19 07:50:41.548 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=07f3d9948a0452f6383c93224255e53f] [method=Aes192Ctr] [fname=/var/lib/tikv/raft/015048.sst]
[2020/05/19 07:50:41.574 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=67135a45d64e2731a5c6b8d2c428b41f] [method=Aes192Ctr] [fname=/var/lib/tikv/db/027558.sst]
[2020/05/19 07:50:41.607 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=b147e8068d441028a5591750670394e4] [method=Aes192Ctr] [fname=/var/lib/tikv/raft/015049.sst]
[2020/05/19 07:50:41.679 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=fc04f39f69904587e91d82f44ae5290d] [method=Aes192Ctr] [fname=/var/lib/tikv/raft/015050.sst]
[2020/05/19 07:50:41.693 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=973d5481e752fdb07856586f1fed4287] [method=Aes192Ctr] [fname=/var/lib/tikv/db/027559.sst]
[2020/05/19 07:50:41.764 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=c98cce8df91ce844e7197eb187627a0f] [method=Aes192Ctr] [fname=/var/lib/tikv/raft/015051.sst]
[2020/05/19 07:50:41.860 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=59fdfa27fbab5bd8b6312de78757b9f5] [method=Aes192Ctr] [fname=/var/lib/tikv/raft/015052.sst]
[2020/05/19 07:50:41.871 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=f3e0f93fb6e49337a4e22fc05ef4b9e9] [method=Aes192Ctr] [fname=/var/lib/tikv/db/027560.sst]
[2020/05/19 07:50:41.884 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=fcb9708775826c72d014c6c5eca0cc60] [method=Aes192Ctr] [fname=/var/lib/tikv/raft/015053.sst]
[2020/05/19 07:50:41.948 +00:00] [INFO] [peer_storage.rs:1413] ["finish clear peer meta"] [takes=577.652133ms] [raft_logs=2596] [raft_key=1] [apply_key=1] [meta_key=1] [region_id=2057]
[2020/05/19 07:50:41.948 +00:00] [INFO] [peer_storage.rs:1025] ["apply snapshot with state ok"] [state="applied_index: 122496 last_commit_index: 121667 commit_index: 121673 commit_term: 7 truncated_state { index: 122496 term: 7 }"] [region="id: 2057 start_key: 7480000000000000FF735F728000000000FF6D50340000000000FA end_key: 7480000000000000FF7400000000000000F8 region_epoch { conf_ver: 5 version: 69 } peers { id: 2058 store_id: 1 } peers { id: 2059 store_id: 4 } peers { id: 2060 store_id: 5 }"] [peer_id=2058] [region_id=2057]
[2020/05/19 07:50:41.961 +00:00] [INFO] [peer.rs:2200] ["snapshot is applied"] [region="id: 2057 start_key: 7480000000000000FF735F728000000000FF6D50340000000000FA end_key: 7480000000000000FF7400000000000000F8 region_epoch { conf_ver: 5 version: 69 } peers { id: 2058 store_id: 1 } peers { id: 2059 store_id: 4 } peers { id: 2060 store_id: 5 }"] [peer_id=2058] [region_id=2057]
[2020/05/19 07:50:41.961 +00:00] [INFO] [peer.rs:2216] ["region changed after applying snapshot"] [region="id: 2057 start_key: 7480000000000000FF735F728000000000FF6D50340000000000FA end_key: 7480000000000000FF7400000000000000F8 region_epoch { conf_ver: 5 version: 69 } peers { id: 2058 store_id: 1 } peers { id: 2059 store_id: 4 } peers { id: 2060 store_id: 5 }"] [prev_region="id: 2057 start_key: 7480000000000000FF735F728000000000FF6D50340000000000FA end_key: 7480000000000000FF7400000000000000F8 region_epoch { conf_ver: 5 version: 69 } peers { id: 2058 store_id: 1 } peers { id: 2059 store_id: 4 } peers { id: 2060 store_id: 5 }"] [peer_id=2058] [region_id=2057]
[2020/05/19 07:50:41.961 +00:00] [INFO] [region_info_accessor.rs:223] ["trying to create region but it already exists, try to update it"] [region_id=2057]
[2020/05/19 07:50:41.961 +00:00] [WARN] [store.rs:595] ["[store 1] handle 55 pending peers include 21 ready, 43 entries, 61 messages and 1 snapshots"] [takes=1399]
[2020/05/19 07:50:41.969 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=fdd1c32b13d0aa736236fd4e7e2fc7ea] [method=Aes192Ctr] [fname=/var/lib/tikv/raft/015054.sst]
[2020/05/19 07:50:41.977 +00:00] [INFO] [mod.rs:194] ["delete encrypted file"] [fname=/var/lib/tikv/db/027528.sst]
[2020/05/19 07:50:41.980 +00:00] [INFO] [mod.rs:194] ["delete encrypted file"] [fname=/var/lib/tikv/db/027509.sst]
[2020/05/19 07:50:41.984 +00:00] [INFO] [mod.rs:194] ["delete encrypted file"] [fname=/var/lib/tikv/db/027505.sst]
[2020/05/19 07:50:41.988 +00:00] [INFO] [mod.rs:194] ["delete encrypted file"] [fname=/var/lib/tikv/db/027504.sst]
[2020/05/19 07:50:41.997 +00:00] [INFO] [mod.rs:194] ["delete encrypted file"] [fname=/var/lib/tikv/db/027502.sst]
[2020/05/19 07:50:42.002 +00:00] [INFO] [mod.rs:194] ["delete encrypted file"] [fname=/var/lib/tikv/db/027496.sst]
[2020/05/19 07:50:42.028 +00:00] [INFO] [mod.rs:194] ["delete encrypted file"] [fname=/var/lib/tikv/db/027494.sst]
[2020/05/19 07:50:42.033 +00:00] [INFO] [peer.rs:322] ["on split"] [split_keys="key 7480000000000000FF685F698000000000FF0000010380000000FF004892BD03800000FF00001F79E4000000FCFA3750597F37FFFA"] [peer_id=2374] [region_id=2373]
[2020/05/19 07:50:42.037 +00:00] [INFO] [pd.rs:497] ["try to batch split region"] [task=batch_split] [region="id: 2373 start_key: 7480000000000000FF6800000000000000F8 end_key: 7480000000000000FF685F698000000000FF0000010380000000FF0073F62903800000FF0000132D3D000000FC region_epoch { conf_ver: 5 version: 50 } peers { id: 2374 store_id: 1 } peers { id: 2375 store_id: 4 } peers { id: 2376 store_id: 5 }"] [new_region_ids="[new_region_id: 2617 new_peer_ids: 2618 new_peer_ids: 2619 new_peer_ids: 2620]"] [region_id=2373]
[2020/05/19 07:50:42.038 +00:00] [INFO] [mod.rs:194] ["delete encrypted file"] [fname=/var/lib/tikv/db/027491.sst]
[2020/05/19 07:50:42.050 +00:00] [INFO] [mod.rs:194] ["delete encrypted file"] [fname=/var/lib/tikv/db/027488.sst]
[2020/05/19 07:50:42.063 +00:00] [INFO] [mod.rs:194] ["delete encrypted file"] [fname=/var/lib/tikv/db/027199.sst]
[2020/05/19 07:50:42.064 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=7ade273c0338a0b30f6d5b9388c81346] [method=Aes192Ctr] [fname=/var/lib/tikv/db/027561.sst]
[2020/05/19 07:50:42.066 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=2a22a0bc6ad79504212261b8d67d405b] [method=Aes192Ctr] [fname=/var/lib/tikv/raft/015055.sst]
[2020/05/19 07:50:42.069 +00:00] [INFO] [mod.rs:194] ["delete encrypted file"] [fname=/var/lib/tikv/db/023557.sst]
[2020/05/19 07:50:42.074 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=f874f54b79f5d57f3b4902a01e16516f] [method=Aes192Ctr] [fname=/var/lib/tikv/db/027562.sst]
[2020/05/19 07:50:42.086 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=2d974484b91a49ad2daec737686d9d2a] [method=Aes192Ctr] [fname=/var/lib/tikv/raft/015056.sst]
[2020/05/19 07:50:42.172 +00:00] [INFO] [mod.rs:194] ["delete encrypted file"] [fname=/var/lib/tikv/db/027486.sst]
[2020/05/19 07:50:42.174 +00:00] [INFO] [mod.rs:194] ["delete encrypted file"] [fname=/var/lib/tikv/db/027470.sst]
[2020/05/19 07:50:42.176 +00:00] [INFO] [mod.rs:194] ["delete encrypted file"] [fname=/var/lib/tikv/db/027469.sst]
[2020/05/19 07:50:42.178 +00:00] [INFO] [mod.rs:194] ["delete encrypted file"] [fname=/var/lib/tikv/db/027468.sst]
[2020/05/19 07:50:42.181 +00:00] [INFO] [mod.rs:194] ["delete encrypted file"] [fname=/var/lib/tikv/db/027467.sst]
[2020/05/19 07:50:42.197 +00:00] [INFO] [mod.rs:194] ["delete encrypted file"] [fname=/var/lib/tikv/db/027466.sst]
[2020/05/19 07:50:42.197 +00:00] [INFO] [mod.rs:194] ["delete encrypted file"] [fname=/var/lib/tikv/db/027460.sst]
[2020/05/19 07:50:42.197 +00:00] [INFO] [mod.rs:194] ["delete encrypted file"] [fname=/var/lib/tikv/db/027457.sst]
[2020/05/19 07:50:42.198 +00:00] [INFO] [mod.rs:194] ["delete encrypted file"] [fname=/var/lib/tikv/db/027451.sst]
[2020/05/19 07:50:42.198 +00:00] [INFO] [mod.rs:194] ["delete encrypted file"] [fname=/var/lib/tikv/db/027209.sst]
[2020/05/19 07:50:42.400 +00:00] [INFO] [apply.rs:2531] ["re-register to apply delegates"] [term=7] [peer_id=2058] [region_id=2057]
[2020/05/19 07:50:42.491 +00:00] [INFO] [mod.rs:194] ["delete encrypted file"] [fname=/var/lib/tikv/db/027517.sst]
[2020/05/19 07:50:42.495 +00:00] [INFO] [mod.rs:194] ["delete encrypted file"] [fname=/var/lib/tikv/db/027501.sst]
[2020/05/19 07:50:42.495 +00:00] [INFO] [apply.rs:1142] ["execute admin command"] [command="cmd_type: BatchSplit splits { requests { split_key: 7480000000000000FF685F698000000000FF0000010380000000FF004892BD03800000FF00001F79E4000000FC new_region_id: 2617 new_peer_ids: 2618 new_peer_ids: 2619 new_peer_ids: 2620 } right_derive: true }"] [index=2852] [term=6] [peer_id=2374] [region_id=2373]
[2020/05/19 07:50:42.495 +00:00] [INFO] [apply.rs:1710] ["split region"] [keys="key 7480000000000000FF685F698000000000FF0000010380000000FF004892BD03800000FF00001F79E4000000FC"] [region="id: 2373 start_key: 7480000000000000FF6800000000000000F8 end_key: 7480000000000000FF685F698000000000FF0000010380000000FF0073F62903800000FF0000132D3D000000FC region_epoch { conf_ver: 5 version: 50 } peers { id: 2374 store_id: 1 } peers { id: 2375 store_id: 4 } peers { id: 2376 store_id: 5 }"] [peer_id=2374] [region_id=2373]
[2020/05/19 07:50:42.498 +00:00] [INFO] [mod.rs:194] ["delete encrypted file"] [fname=/var/lib/tikv/db/024569.sst]
[2020/05/19 07:50:42.502 +00:00] [INFO] [mod.rs:194] ["delete encrypted file"] [fname=/var/lib/tikv/db/024554.sst]
[2020/05/19 07:50:42.507 +00:00] [INFO] [mod.rs:194] ["delete encrypted file"] [fname=/var/lib/tikv/db/024546.sst]
[2020/05/19 07:50:42.510 +00:00] [INFO] [mod.rs:194] ["delete encrypted file"] [fname=/var/lib/tikv/db/024537.sst]
[2020/05/19 07:50:42.518 +00:00] [INFO] [peer.rs:1615] ["notify pd with split"] [split_count=2] [peer_id=2374] [region_id=2373]
[2020/05/19 07:50:42.518 +00:00] [INFO] [peer.rs:1657] ["insert new region"] [region="id: 2617 start_key: 7480000000000000FF6800000000000000F8 end_key: 7480000000000000FF685F698000000000FF0000010380000000FF004892BD03800000FF00001F79E4000000FC region_epoch { conf_ver: 5 version: 51 } peers { id: 2618 store_id: 1 } peers { id: 2619 store_id: 4 } peers { id: 2620 store_id: 5 }"] [region_id=2617]
[2020/05/19 07:50:42.518 +00:00] [INFO] [peer.rs:147] ["create peer"] [peer_id=2618] [region_id=2617]
[2020/05/19 07:50:42.520 +00:00] [INFO] [raft.rs:809] ["became follower at term 5"] [term=5] [raft_id=2618] [region_id=2617]
[2020/05/19 07:50:42.520 +00:00] [INFO] [raft.rs:288] [newRaft] [peers="[(2620, Progress { matched: 0, next_idx: 6, state: Probe, paused: false, pending_snapshot: 0, pending_request_snapshot: 0, recent_active: false, ins: Inflights { start: 0, count: 0, buffer: [] } }), (2618, Progress { matched: 5, next_idx: 6, state: Probe, paused: false, pending_snapshot: 0, pending_request_snapshot: 0, recent_active: false, ins: Inflights { start: 0, count: 0, buffer: [] } }), (2619, Progress { matched: 0, next_idx: 6, state: Probe, paused: false, pending_snapshot: 0, pending_request_snapshot: 0, recent_active: false, ins: Inflights { start: 0, count: 0, buffer: [] } })]"] ["last term"=5] ["last index"=5] [applied=5] [commit=5] [term=5] [raft_id=2618] [region_id=2617]
[2020/05/19 07:50:42.520 +00:00] [INFO] [raw_node.rs:222] ["RawNode created with id 2618."] [id=2618] [raft_id=2618] [region_id=2617]
[2020/05/19 07:50:42.520 +00:00] [INFO] [raft.rs:1203] ["starting a new election"] [term=5] [raft_id=2618] [region_id=2617]
[2020/05/19 07:50:42.520 +00:00] [INFO] [raft.rs:859] ["became pre-candidate at term 5"] [term=5] [raft_id=2618] [region_id=2617]
[2020/05/19 07:50:42.520 +00:00] [INFO] [raft.rs:928] ["2618 received message from 2618"] [term=5] [msg=MsgRequestPreVote] [from=2618] [id=2618] [raft_id=2618] [region_id=2617]
[2020/05/19 07:50:42.520 +00:00] [INFO] [raft.rs:949] ["[logterm: 5, index: 5] sent request to 2620"] [msg=MsgRequestPreVote] [term=5] [id=2620] [log_index=5] [log_term=5] [raft_id=2618] [region_id=2617]
[2020/05/19 07:50:42.520 +00:00] [INFO] [raft.rs:949] ["[logterm: 5, index: 5] sent request to 2619"] [msg=MsgRequestPreVote] [term=5] [id=2619] [log_index=5] [log_term=5] [raft_id=2618] [region_id=2617]
[2020/05/19 07:50:42.536 +00:00] [INFO] [process.rs:145] ["get snapshot failed"] [err="Request(message: \"EpochNotMatch current epoch of region 2373 is conf_ver: 5 version: 51, but you sent conf_ver: 5 version: 50\" epoch_not_match { current_regions { id: 2373 start_key: 7480000000000000FF685F698000000000FF0000010380000000FF004892BD03800000FF00001F79E4000000FC end_key: 7480000000000000FF685F698000000000FF0000010380000000FF0073F62903800000FF0000132D3D000000FC region_epoch { conf_ver: 5 version: 51 } peers { id: 2374 store_id: 1 } peers { id: 2375 store_id: 4 } peers { id: 2376 store_id: 5 } } current_regions { id: 2617 start_key: 7480000000000000FF6800000000000000F8 end_key: 7480000000000000FF685F698000000000FF0000010380000000FF004892BD03800000FF00001F79E4000000FC region_epoch { conf_ver: 5 version: 51 } peers { id: 2618 store_id: 1 } peers { id: 2619 store_id: 4 } peers { id: 2620 store_id: 5 } } })"] [cid=391525]
[2020/05/19 07:50:42.537 +00:00] [INFO] [raft.rs:1736] ["received from 2620"] [term=5] ["msg type"=MsgRequestPreVoteResponse] [from=2620] [raft_id=2618] [region_id=2617]
[2020/05/19 07:50:42.537 +00:00] [INFO] [raft.rs:833] ["became candidate at term 6"] [term=6] [raft_id=2618] [region_id=2617]
[2020/05/19 07:50:42.538 +00:00] [INFO] [raft.rs:928] ["2618 received message from 2618"] [term=6] [msg=MsgRequestVote] [from=2618] [id=2618] [raft_id=2618] [region_id=2617]
[2020/05/19 07:50:42.538 +00:00] [INFO] [raft.rs:949] ["[logterm: 5, index: 5] sent request to 2620"] [msg=MsgRequestVote] [term=6] [id=2620] [log_index=5] [log_term=5] [raft_id=2618] [region_id=2617]
[2020/05/19 07:50:42.538 +00:00] [INFO] [raft.rs:949] ["[logterm: 5, index: 5] sent request to 2619"] [msg=MsgRequestVote] [term=6] [id=2619] [log_index=5] [log_term=5] [raft_id=2618] [region_id=2617]
[2020/05/19 07:50:42.539 +00:00] [INFO] [raft.rs:1736] ["received from 2619"] [term=6] ["msg type"=MsgRequestVoteResponse] [from=2619] [raft_id=2618] [region_id=2617]
[2020/05/19 07:50:42.540 +00:00] [INFO] [raft.rs:900] ["became leader at term 6"] [term=6] [raft_id=2618] [region_id=2617]
[2020/05/19 07:50:42.554 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=e85f985f4299e5d8fd516d9656788a2c] [method=Aes192Ctr] [fname=/var/lib/tikv/raft/015057.log]
[2020/05/19 07:50:42.562 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=97904933e81ef1d76d36e16c8ea562fe] [method=Aes192Ctr] [fname=/var/lib/tikv/raft/015058.sst]
[2020/05/19 07:50:42.584 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=66a857c110765da37b16560c63fff7fd] [method=Aes192Ctr] [fname=/var/lib/tikv/db/027563.sst]
[2020/05/19 07:50:42.667 +00:00] [ERROR] [region.rs:392] ["failed to apply snap!!!"] [err="snap failed \"[components/raftstore/src/store/snap.rs:802]: \\\"[components/raftstore/src/store/snap.rs:280]: invalid checksum 2126144972 for snapshot cf file /var/lib/tikv/snap/rev_2069_8_85311_lock.sst, expected 4227103119\\\"\""]
[2020/05/19 07:50:42.667 +00:00] [WARN] [mod.rs:89] ["handle task Snap apply for 2069"] [takes=1614]
[2020/05/19 07:50:42.667 +00:00] [INFO] [region.rs:290] ["begin apply snap data"] [region_id=2057]
[2020/05/19 07:50:42.755 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=31a48c7e85d3b3a49e0ae9493d50b199] [method=Aes192Ctr] [fname=/var/lib/tikv/db/027564.log]
[2020/05/19 07:50:42.923 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=1f5214f189ebcbbb3dcbd6de465a1e1f] [method=Aes192Ctr] [fname=/var/lib/tikv/snap/rev_2609_6_6_write.sst]
[2020/05/19 07:50:43.138 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=c826f6490618c48d692d90bfd0a9c27c] [method=Aes192Ctr] [fname=/var/lib/tikv/db/027565.sst]
[2020/05/19 07:50:43.155 +00:00] [INFO] [mod.rs:194] ["delete encrypted file"] [fname=/var/lib/tikv/raft/015021.log]
[2020/05/19 07:50:43.159 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=34e1dc17aaf8158cf03b456d45770ceb] [method=Aes192Ctr] [fname=/var/lib/tikv/db/027566.sst]
[2020/05/19 07:50:43.429 +00:00] [INFO] [snap.rs:223] ["saving snapshot file"] [file=/var/lib/tikv/snap/rev_2609_6_6_(default|lock|write).sst] [snap_key=2609_6_6]
[2020/05/19 07:50:43.549 +00:00] [INFO] [mod.rs:194] ["delete encrypted file"] [fname=/var/lib/tikv/db/027522.sst]
[2020/05/19 07:50:43.553 +00:00] [INFO] [mod.rs:194] ["delete encrypted file"] [fname=/var/lib/tikv/db/027459.sst]
[2020/05/19 07:50:43.556 +00:00] [INFO] [mod.rs:194] ["delete encrypted file"] [fname=/var/lib/tikv/db/027458.sst]
[2020/05/19 07:50:43.560 +00:00] [INFO] [mod.rs:194] ["delete encrypted file"] [fname=/var/lib/tikv/db/027218.sst]
[2020/05/19 07:50:43.563 +00:00] [INFO] [mod.rs:194] ["delete encrypted file"] [fname=/var/lib/tikv/db/027173.sst]
[2020/05/19 07:50:43.567 +00:00] [INFO] [mod.rs:194] ["delete encrypted file"] [fname=/var/lib/tikv/db/026941.sst]
[2020/05/19 07:50:43.570 +00:00] [INFO] [mod.rs:194] ["delete encrypted file"] [fname=/var/lib/tikv/db/025992.sst]
[2020/05/19 07:50:43.576 +00:00] [INFO] [mod.rs:194] ["delete encrypted file"] [fname=/var/lib/tikv/db/017676.sst]
[2020/05/19 07:50:43.585 +00:00] [INFO] [raft.rs:2020] ["[commit: 0, lastindex: 0, lastterm: 0] starts to restore snapshot [index: 6, term: 6]"] [snapshot_term=6] [snapshot_index=6] [last_term=0] [last_index=0] [commit=0] [raft_id=2610] [region_id=2609]
[2020/05/19 07:50:43.585 +00:00] [INFO] [raft_log.rs:487] ["log [committed=0, applied=0, unstable.offset=1, unstable.entries.len()=0] starts to restore snapshot [index: 6, term: 6]"] [snapshot_term=6] [snapshot_index=6] [log="committed=0, applied=0, unstable.offset=1, unstable.entries.len()=0"] [raft_id=2610] [region_id=2609]
[2020/05/19 07:50:43.585 +00:00] [INFO] [raft.rs:1956] ["[commit: 6, term: 6] restored snapshot [index: 6, term: 6]"] [snapshot_term=6] [snapshot_index=6] [commit=6] [term=6] [raft_id=2610] [region_id=2609]
[2020/05/19 07:50:43.585 +00:00] [INFO] [peer_storage.rs:985] ["begin to apply snapshot"] [peer_id=2610] [region_id=2609]
[2020/05/19 07:50:43.585 +00:00] [INFO] [peer_storage.rs:1025] ["apply snapshot with state ok"] [state="applied_index: 6 truncated_state { index: 6 term: 6 }"] [region="id: 2609 start_key: 7480000000000000FF745F728000000000FF484CE00000000000FA end_key: 7480000000000000FF745F728000000000FF4E9A800000000000FA region_epoch { conf_ver: 5 version: 65 } peers { id: 2610 store_id: 1 } peers { id: 2611 store_id: 4 } peers { id: 2612 store_id: 5 }"] [peer_id=2610] [region_id=2609]
[2020/05/19 07:50:43.592 +00:00] [INFO] [peer.rs:2200] ["snapshot is applied"] [region="id: 2609 start_key: 7480000000000000FF745F728000000000FF484CE00000000000FA end_key: 7480000000000000FF745F728000000000FF4E9A800000000000FA region_epoch { conf_ver: 5 version: 65 } peers { id: 2610 store_id: 1 } peers { id: 2611 store_id: 4 } peers { id: 2612 store_id: 5 }"] [peer_id=2610] [region_id=2609]
[2020/05/19 07:50:43.933 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=67337746f185c1f1881fb546d33df99c] [method=Aes192Ctr] [fname=/var/lib/tikv/db/027567.log]
[2020/05/19 07:50:43.940 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=94e03e2bbce89d817b3fe53b2237b6e4] [method=Aes192Ctr] [fname=/var/lib/tikv/db/027568.sst]
[2020/05/19 07:50:44.144 +00:00] [INFO] [mod.rs:171] ["new encrypted file"] [iv=60952838cec0ea9f58704aad9354dfca] [method=Aes192Ctr] [fname=/var/lib/tikv/db/027569.sst]
[2020/05/19 07:50:44.158 +00:00] [INFO] [mod.rs:194] ["delete encrypted file"] [fname=/var/lib/tikv/raft/015018.sst]
[2020/05/19 07:50:44.162 +00:00] [INFO] [mod.rs:194] ["delete encrypted file"] [fname=/var/lib/tikv/raft/015016.sst]
[2020/05/19 07:50:44.191 +00:00] [INFO] [mod.rs:194] ["delete encrypted file"] [fname=/var/lib/tikv/raft/015014.sst]
[2020/05/19 07:50:44.193 +00:00] [INFO] [mod.rs:194] ["delete encrypted file"] [fname=/var/lib/tikv/raft/015011.sst]
[2020/05/19 07:50:44.196 +00:00] [INFO] [mod.rs:194] ["delete encrypted file"] [fname=/var/lib/tikv/raft/015010.sst]
[2020/05/19 07:50:44.199 +00:00] [INFO] [mod.rs:194] ["delete encrypted file"] [fname=/var/lib/tikv/raft/015009.sst]
[2020/05/19 07:50:44.203 +00:00] [INFO] [mod.rs:194] ["delete encrypted file"] [fname=/var/lib/tikv/raft/015008.sst]
[2020/05/19 07:50:44.208 +00:00] [INFO] [mod.rs:194] ["delete encrypted file"] [fname=/var/lib/tikv/raft/015007.sst]
[2020/05/19 07:50:44.212 +00:00] [INFO] [mod.rs:194] ["delete encrypted file"] [fname=/var/lib/tikv/raft/015006.sst]
[2020/05/19 07:50:44.214 +00:00] [FATAL] [lib.rs:480] ["[region 2069] 2070 applying snapshot failed"] [backtrace="stack backtrace:\n   0: tikv_util::set_panic_hook::{{closure}}\n             at components/tikv_util/src/lib.rs:479\n   1: std::panicking::rust_panic_with_hook\n             at src/libstd/panicking.rs:475\n   2: rust_begin_unwind\n             at src/libstd/panicking.rs:375\n   3: std::panicking::begin_panic_fmt\n             at src/libstd/panicking.rs:326\n   4: raftstore::store::peer_storage::PeerStorage::check_applying_snap\n             at home/jenkins/agent/workspace/build-tikv/tikv/<::std::macros::panic macros>:9\n      raftstore::store::peer::Peer::handle_raft_ready_append\n             at home/jenkins/agent/workspace/build-tikv/tikv/components/raftstore/src/store/peer.rs:1103\n   5: raftstore::store::fsm::peer::PeerFsmDelegate<T,C>::collect_ready\n             at home/jenkins/agent/workspace/build-tikv/tikv/components/raftstore/src/store/fsm/peer.rs:628\n      <raftstore::store::fsm::store::RaftPoller<T,C> as batch_system::batch::PollHandler<raftstore::store::fsm::peer::PeerFsm<engine_rocks::engine::RocksEngine>,raftstore::store::fsm::store::StoreFsm>>::handle_normal\n             at home/jenkins/agent/workspace/build-tikv/tikv/components/raftstore/src/store/fsm/store.rs:704\n   6: batch_system::batch::Poller<N,C,Handler>::poll\n             at home/jenkins/agent/workspace/build-tikv/tikv/components/batch-system/src/batch.rs:324\n   7: batch_system::batch::BatchSystem<N,C>::spawn::{{closure}}\n             at home/jenkins/agent/workspace/build-tikv/tikv/components/batch-system/src/batch.rs:398\n      std::sys_common::backtrace::__rust_begin_short_backtrace\n             at rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/sys_common/backtrace.rs:136\n   8: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}\n             at rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/thread/mod.rs:469\n      <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once\n             at rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/panic.rs:318\n      std::panicking::try::do_call\n             at rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/panicking.rs:292\n      std::panicking::try\n             at rustc/0de96d37fbcc54978458c18f5067cd9817669bc8//src/libpanic_unwind/lib.rs:78\n      std::panic::catch_unwind\n             at rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/panic.rs:394\n      std::thread::Builder::spawn_unchecked::{{closure}}\n             at rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/thread/mod.rs:468\n      core::ops::function::FnOnce::call_once{{vtable.shim}}\n             at rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libcore/ops/function.rs:232\n   9: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once\n             at rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/liballoc/boxed.rs:1022\n  10: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once\n             at rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/liballoc/boxed.rs:1022\n      std::sys_common::thread::start_thread\n             at src/libstd/sys_common/thread.rs:13\n      std::sys::unix::thread::Thread::new::thread_start\n             at src/libstd/sys/unix/thread.rs:80\n  11: <unknown>\n  12: clone\n"] [location=components/raftstore/src/store/peer_storage.rs:1112] [thread_name=raftstore-1-1]
</details>

### PR DESCRIPTION
**Pull request by hicqu**
Signed-off-by: qupeng <qupeng@pingcap.com>

### What problem does this PR solve?
TiKV could panic when applying snapshots if encryption is enabled.

### What is changed and how it works?
Encrypt lock cf correctly when receiving snapshots.

Fixes #7881 

### Check List 

Tests 

- Integration test

Side effects

### Release note 

* Encryption: fix snapshot apply failure caused lock CF snapshot file not being encrypted on received.

### CODE REVIEW

File: cmd/src/bin/tikv-ctl.rs [hunk 1]
```diff
@@ -1777,6 +1798,43 @@ fn main() {
...
     }
 
+    if let Some(matches) = matches.subcommand_matches("decrypt-file") {
+        let infile = matches.value_of("file").unwrap();
+        let outfile = matches.value_of("out-file").unwrap();
+        println!("infile: {}, outfile: {}", infile, outfile);
+        let key_manager =
+            DataKeyManager::from_config(&cfg.security.encryption, &cfg.storage.data_dir)
+                .unwrap()
+                .unwrap();
```
Comment (yiwu-arbug) [inline cmd/src/bin/tikv-ctl.rs:1808]: should properly exit if the result is `None`.

File: cmd/src/bin/tikv-ctl.rs [hunk 2]
```diff
@@ -1777,6 +1798,43 @@ fn main() {
         return;
     }
 
+    if let Some(matches) = matches.subcommand_matches("decrypt-file") {
+        let infile = matches.value_of("file").unwrap();
+        let outfile = matches.value_of("out-file").unwrap();
+        println!("infile: {}, outfile: {}", infile, outfile);
+        let key_manager =
+            DataKeyManager::from_config(&cfg.security.encryption, &cfg.storage.data_dir)
```
Comment (yiwu-arbug) [inline cmd/src/bin/tikv-ctl.rs:1806]: I think we need to avoid this key manager update key dictionary or file dictionary. Can you leave a `TODO` here?

**Comment by hicqu** [comment]
@yiwu-arbug PTAL again because I have added 2 test cases for it.

File: components/raftstore/src/store/snap/io.rs [hunk 3]
```diff
@@ -80,20 +80,19 @@ where
...
+        box_try!(BytesEncoder::encode_compact_bytes(&mut writer, b""));
+        let file = if !should_encrypt {
+            file.unwrap()
+        } else {
+            encrypted_file.unwrap().finalize()
+        };
         box_try!(file.sync_all());
     } else {
         drop(file);
         box_try!(fs::remove_file(path));
```
Comment (yiwu-arbug) [inline components/raftstore/src/store/snap/io.rs:93]: Should call `key_manager.delete_file` here?

Comment (hicqu) [reply components/raftstore/src/store/snap/io.rs:93]: `key_manger.delete_file` will be called in `snap.delete()`, so it's unnecessary here.
