### PR TITLE
test: stabilize test_custom_quorum

### LINKED ISSUE #7042: raftstore::test_custom_quorum::test_integration_on_half_fail_quorum_fn ... thread 'main' panicked at 'region 1 must lost leader because quorum fail'
raftstore::test_custom_quorum::test_integration_on_half_fail_quorum_fn

```
[2020-03-09T11:17:59.900Z] test raftstore::test_custom_quorum::test_integration_on_half_fail_quorum_fn ... thread 'main' panicked at 'region 1 must lost leader because quorum fail', tests/integrations/raftstore/test_custom_quorum.rs:28:5

[2020-03-09T11:17:59.900Z] stack backtrace:

[2020-03-09T11:18:00.476Z]    0: backtrace::backtrace::libunwind::trace

[2020-03-09T11:18:00.476Z]              at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88

[2020-03-09T11:18:00.476Z]    1: backtrace::backtrace::trace_unsynchronized

[2020-03-09T11:18:00.476Z]              at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66

[2020-03-09T11:18:00.476Z]    2: std::sys_common::backtrace::_print_fmt

[2020-03-09T11:18:00.476Z]              at src/libstd/sys_common/backtrace.rs:84

[2020-03-09T11:18:00.476Z]    3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt

[2020-03-09T11:18:00.476Z]              at src/libstd/sys_common/backtrace.rs:61

[2020-03-09T11:18:00.476Z]    4: core::fmt::write

[2020-03-09T11:18:00.476Z]              at src/libcore/fmt/mod.rs:1025

[2020-03-09T11:18:00.476Z]    5: std::io::Write::write_fmt

[2020-03-09T11:18:00.476Z]              at src/libstd/io/mod.rs:1426

[2020-03-09T11:18:00.476Z]    6: std::sys_common::backtrace::_print

[2020-03-09T11:18:00.476Z]              at src/libstd/sys_common/backtrace.rs:65

[2020-03-09T11:18:00.476Z]    7: std::sys_common::backtrace::print

[2020-03-09T11:18:00.476Z]              at src/libstd/sys_common/backtrace.rs:50

[2020-03-09T11:18:00.476Z]    8: std::panicking::default_hook::{{closure}}

[2020-03-09T11:18:00.476Z]              at src/libstd/panicking.rs:193

[2020-03-09T11:18:00.476Z]    9: std::panicking::default_hook

[2020-03-09T11:18:00.476Z]              at src/libstd/panicking.rs:210

[2020-03-09T11:18:00.476Z]   10: std::panicking::rust_panic_with_hook

[2020-03-09T11:18:00.476Z]              at src/libstd/panicking.rs:471

[2020-03-09T11:18:00.476Z]   11: std::panicking::begin_panic

[2020-03-09T11:18:00.476Z]              at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/panicking.rs:404

[2020-03-09T11:18:00.476Z]   12: integrations::raftstore::test_custom_quorum::test_integration_on_half_fail_quorum_fn

[2020-03-09T11:18:00.476Z]              at tests/integrations/raftstore/test_custom_quorum.rs:28

[2020-03-09T11:18:00.476Z]   13: integrations::raftstore::test_custom_quorum::test_integration_on_half_fail_quorum_fn::{{closure}}

[2020-03-09T11:18:00.476Z]              at tests/integrations/raftstore/test_custom_quorum.rs:13

[2020-03-09T11:18:00.476Z]   14: core::ops::function::FnOnce::call_once

[2020-03-09T11:18:00.476Z]              at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libcore/ops/function.rs:232

[2020-03-09T11:18:00.476Z]   15: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once

[2020-03-09T11:18:00.476Z]              at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/liballoc/boxed.rs:1022

[2020-03-09T11:18:00.476Z]   16: __rust_maybe_catch_panic

[2020-03-09T11:18:00.476Z]              at src/libpanic_unwind/lib.rs:78

[2020-03-09T11:18:00.476Z]   17: std::panicking::try

[2020-03-09T11:18:00.476Z]              at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/panicking.rs:270

[2020-03-09T11:18:00.476Z]   18: std::panic::catch_unwind

[2020-03-09T11:18:00.476Z]              at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/panic.rs:394

[2020-03-09T11:18:00.476Z]   19: test::run_test_in_process

[2020-03-09T11:18:00.476Z]              at src/libtest/lib.rs:567

[2020-03-09T11:18:00.476Z]   20: test::run_test::run_test_inner::{{closure}}

[2020-03-09T11:18:00.476Z]              at src/libtest/lib.rs:474

[2020-03-09T11:18:00.477Z]   21: test::run_test::run_test_inner

[2020-03-09T11:18:00.477Z]              at src/libtest/lib.rs:495

[2020-03-09T11:18:00.477Z]   22: test::run_test

[2020-03-09T11:18:00.477Z]              at src/libtest/lib.rs:531

[2020-03-09T11:18:00.477Z]   23: test::run_tests

[2020-03-09T11:18:00.477Z]              at src/libtest/lib.rs:300

[2020-03-09T11:18:00.477Z]   24: test::console::run_tests_console

[2020-03-09T11:18:00.477Z]              at src/libtest/console.rs:295

[2020-03-09T11:18:00.477Z]   25: test::test_main

[2020-03-09T11:18:00.477Z]              at src/libtest/lib.rs:121

[2020-03-09T11:18:00.477Z]   26: test::test_main_static

[2020-03-09T11:18:00.477Z]              at src/libtest/lib.rs:140

[2020-03-09T11:18:00.477Z]   27: integrations::main

[2020-03-09T11:18:00.477Z]   28: std::rt::lang_start::{{closure}}

[2020-03-09T11:18:00.477Z]              at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/rt.rs:67

[2020-03-09T11:18:00.477Z]   29: std::rt::lang_start_internal::{{closure}}

[2020-03-09T11:18:00.477Z]              at src/libstd/rt.rs:52

[2020-03-09T11:18:00.477Z]   30: std::panicking::try::do_call

[2020-03-09T11:18:00.477Z]              at src/libstd/panicking.rs:292

[2020-03-09T11:18:00.477Z]   31: __rust_maybe_catch_panic

[2020-03-09T11:18:00.477Z]              at src/libpanic_unwind/lib.rs:78

[2020-03-09T11:18:00.477Z]   32: std::panicking::try

[2020-03-09T11:18:00.477Z]              at src/libstd/panicking.rs:270

[2020-03-09T11:18:00.477Z]   33: std::panic::catch_unwind

[2020-03-09T11:18:00.477Z]              at src/libstd/panic.rs:394

[2020-03-09T11:18:00.477Z]   34: std::rt::lang_start_internal

[2020-03-09T11:18:00.477Z]              at src/libstd/rt.rs:51

[2020-03-09T11:18:00.477Z]   35: std::rt::lang_start

[2020-03-09T11:18:00.477Z]              at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/rt.rs:67

[2020-03-09T11:18:00.477Z]   36: main

[2020-03-09T11:18:00.477Z]   37: __libc_start_main

[2020-03-09T11:18:00.477Z]   38: <unknown>

[2020-03-09T11:18:00.477Z] note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

[2020-03-09T11:18:00.477Z] FAILED

[2020-03-09T11:18:05.724Z] test raftstore::test_multi::test_multi_server_leader_crash ... ok

[2020-03-09T11:18:05.724Z] test raftstore::test_service::test_debug_scan_mvcc ... ok

[2020-03-09T11:18:08.269Z] test raftstore::test_split_region::test_node_split_region ... ok

[2020-03-09T11:18:16.354Z] test raftstore::test_update_region_size::test_server_update_region_size ... ok

[2020-03-09T11:18:16.354Z] 

[2020-03-09T11:18:16.354Z] failures:

[2020-03-09T11:18:16.354Z] 

[2020-03-09T11:18:16.354Z] failures:

[2020-03-09T11:18:16.354Z]     raftstore::test_custom_quorum::test_integration_on_half_fail_quorum_fn
```

https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/18370/pipeline/

### PR DESCRIPTION
**Pull request by hicqu**
Signed-off-by: qupeng <qupeng@pingcap.com>

###  What have you changed?
Stabilize test_custom_quorum by checking election messages with filters.
Close #7042 #7053 .

###  What is the type of the changes?
Engineering.

###  How is the PR tested?
- Unit test

### CODE REVIEW

File: tests/integrations/raftstore/test_custom_quorum.rs [hunk 1]
```diff
@@ -1,31 +1,66 @@
...
+            .direction(Direction::Send)
+            .msg_type(MessageType::MsgAppend)
+            .msg_type(MessageType::MsgAppendResponse)
+            .set_msg_callback(msg_cb)
+            .when(Arc::new(AtomicBool::new(false))),
+    );
+    cluster.sim.wl().add_send_filter(1, filter);
+
+    // No new leader can be elected.
+    if rx.recv_timeout(Duration::from_secs(3)) != Err(mpsc::RecvTimeoutError::Timeout) {
```
Comment (BusyJay) [inline tests/integrations/raftstore/test_custom_quorum.rs]: So the test need to run for 3 seconds?

Comment (hicqu) [reply tests/integrations/raftstore/test_custom_quorum.rs]: So how about waiting 1 election timeout, or do you have any suggestions?

Comment (BusyJay) [reply tests/integrations/raftstore/test_custom_quorum.rs]: election timeout looks good to me.

File: tests/integrations/raftstore/test_custom_quorum.rs [hunk 2]
```diff
@@ -1,31 +1,66 @@
...
-    // After peer 4 and 5 fail, no new leader could be elected.
+    let (tx, rx) = mpsc::sync_channel(1024);
+    let msg_cb = Arc::new(Box::new(move |_: &RaftMessage| drop(tx.send(0)))
+        as Box<dyn Fn(&RaftMessage) + Send + Sync>);
+    let filter = Box::new(
+        RegionPacketFilter::new(1, 1)
+            .direction(Direction::Send)
+            .msg_type(MessageType::MsgRequestPreVote)
+            .set_msg_callback(msg_cb)
+            .when(Arc::new(AtomicBool::new(false))),
```
Comment (Little-Wallace) [inline tests/integrations/raftstore/test_custom_quorum.rs]: Why drop 'MsgRequestPreVote'?

Comment (hicqu) [reply tests/integrations/raftstore/test_custom_quorum.rs]: They won't be dropped because `when` is `false`.

File: components/raftstore/src/store/peer.rs [hunk 3]
```diff
@@ -1803,11 +1803,14 @@ impl Peer {
             }
         }
         let healthy = self.count_healthy_node(progress.voters());
+        let voters_len = progress.voter_ids().len();
         let quorum_after_change = match ctx.cfg.quorum_algorithm {
             QuorumAlgorithm::IntegrationOnHalfFail => {
-                util::integration_on_half_fail_quorum_fn(progress.voter_ids().len())
+                let majority = raft::majority(voters_len);
+                let custom = util::integration_on_half_fail_quorum_fn(voters_len);
+                cmp::min(voters_len, cmp::max(majority, custom))
```
Comment (gengliqi) [inline components/raftstore/src/store/peer.rs]: I think this logic should be moved to below because all quorum numbers must be validated.
`quorum_after_change = cmp::min(voters_len, cmp::max(majority_len, quorum_after_change)`

Comment (hicqu) [reply components/raftstore/src/store/peer.rs]: Is it really necessary? `majority` is in [majority, voters_len] obviously.

Comment (gengliqi) [reply components/raftstore/src/store/peer.rs]: It's because the `quorum algorithm` is an enum. But moving it after adding another new quorum function also looks good to me.
