### PR TITLE
raftstore-v2: fix issues of encryption and merge

### LINKED ISSUE #15052: [Dynamic Region] start ticdc changefeed and pitr task, inject one tikv network isolation 10min and recovery, 3 hours later, one tikv panic repeatedly
### What version of TiKV are you using?
./tikv-server -V
 TiKV 
Release Version:   7.3.0-alpha
Edition:           Community
Git Commit Hash:   56130211bf21cb3aea9c5ecec4952f6fedb33093
Git Commit Branch: heads/refs/tags/v7.3.0-alpha
UTC Build Time:    2023-06-29 11:14:25
Rust Version:      rustc 1.67.0-nightly (96ddd32c4 2022-11-14)
Enable Features:   pprof-fp jemalloc mem-profiling portable sse test-engine-kv-rocksdb test-engine-raft-raft-engine cloud-aws cloud-gcp cloud-azure
Profile:           dist_release
2023-06-30T15:02:34.797+0800

### What operating system and CPU are you using?
8c/32g

### Steps to reproduce
1、start pitr and ticdc
2、run tpcc
3、 inject one tikv network isolation 10min and recovery

### What did you expect?
all tikv are normal after fault recover

### What did happened?
 inject one tikv network isolation 10min and recovery, 3 hours later, one tikv panic repeatedly.

image

[[server2.rs:830](http://server2.rs:830/)] [\"failed to start node: Engine(Engine(Status { code: IoError, sub_code: None, sev: NoError, state: \\\"Corruption: Encryption key manager get file failure: key not found for id 10737154287846016419 in file /var/lib/tikv/data/tablets/2005_10032/MANIFEST-001430\\\" }))\"]

### LINKED ISSUE #15059: [Dynamic Region] raft log lag more and more after inject one tikv network partition for 50m and recover
### What version of TiKV are you using?
./tikv-server -V
 TiKV 
Release Version:   7.3.0-alpha
Edition:           Community
Git Commit Hash:   425f6f262f577425612cf1663ea6cceada72c724
Git Commit Branch: heads/refs/tags/v7.3.0-alpha
UTC Build Time:    2023-06-30 11:15:31
Rust Version:      rustc 1.67.0-nightly (96ddd32c4 2022-11-14)
Enable Features:   pprof-fp jemalloc mem-profiling portable sse test-engine-kv-rocksdb test-engine-raft-raft-engine cloud-aws cloud-gcp cloud-azure
Profile:           dist_release
2023-07-03T09:59:28.474+0800

### What operating system and CPU are you using?
8c/32g

### Steps to reproduce
1、run tpcc
2、inject one tikv network partition for 50m and recover

### What did you expect?
raft log lag can catch up within some time

### What did happened?
raft log lag more and more after inject one tikv network partition for 50m and recover
9f12f8e1-48e0-431b-80b2-b89c02a19250

### PR DESCRIPTION
**Pull request by tabokie**
### What is changed and how it works?

Issue Number: Ref #12842  Fix #15052 Fix #15059
What's Changed:

```commit-message
- Do not try to compact log when peer is destroyed
- Check `apply_scheduler.is_some()` when handling CaptureChange
- Fix encrypted dir deletion unable to traverse directory that was renamed
- Fix a bug that encryption key can be lost when there're racing snapshots for a same region
- Fix a bug that checkpoint of a to-be-destroyed tablet can cause deadlock
```

### Related changes

https://github.com/tikv/rocksdb/pull/338
https://github.com/tikv/rust-rocksdb/pull/747

### Check List 

Tests 

- Unit test

### Release note 

```release-note
None
```

### CODE REVIEW

File: components/raftstore-v2/src/worker/tablet.rs [hunk 1]
```diff
@@ -438,7 +438,7 @@ where
             if r && let Some(cb) = cb.take() {
                 cb();
             }
-            r
+            !r
```
Comment (overvenus) [inline components/raftstore-v2/src/worker/tablet.rs:441]: Is the change covered in tests?

Comment (tabokie) [reply components/raftstore-v2/src/worker/tablet.rs:441]: Added.

File: components/encryption/src/manager/mod.rs [hunk 2]
```diff
@@ -809,10 +809,13 @@ impl DataKeyManager {
...
         }
-        let mut iter = walkdir::WalkDir::new(scan).into_iter().peekable();
+        let mut iter = walkdir::WalkDir::new(scan)
+            .into_iter()
+            .filter(|e| e.as_ref().map_or(true, |e| !e.path().is_dir()))
+            .peekable();
         while let Some(e) = iter.next() {
             let e = e?;
-            if e.path_is_symlink() {
+            if e.path().is_symlink() {
```
Comment (tonyxuqqi) [inline components/encryption/src/manager/mod.rs:818]: question: what's the difference between e.path_is_symlink() and e.path().is_symlink()

File: components/raftstore-v2/src/operation/query/capture.rs [hunk 3]
```diff
@@ -52,14 +52,16 @@ impl<'a, EK: KvEngine, ER: RaftEngine, T: raftstore::store::Transport>
...
-        let apply_router = self.fsm.peer().apply_scheduler().unwrap().clone();
+        let apply_scheduler = self.fsm.peer().apply_scheduler().cloned();
         let (ch, _) = QueryResChannel::with_callback(Box::new(move |res| {
             if let QueryResult::Response(resp) = res && resp.get_header().has_error() {
                 // Return error
                 capture_change.snap_cb.report_error(resp.clone());
                 return;
             }
-            apply_router.send(ApplyTask::CaptureApply(capture_change))
+            if let Some(scheduler) = apply_scheduler {
```
Comment (tonyxuqqi) [inline components/raftstore-v2/src/operation/query/capture.rs:62]: When apply_scheduler is None, ApplyTask::CaptureApply will not be sent. Will it be a problem? @tabokie @overvenus

File: components/encryption/src/manager/mod.rs (hunk 2 above)
Comment (tabokie) [reply components/encryption/src/manager/mod.rs:818]: Implementation is different. Using std implementation is more consistent.

File: components/engine_rocks/src/misc.rs [hunk 4]
```diff
@@ -86,18 +88,23 @@ impl RocksEngine {
...
             if wb.count() > 0 {
-                wb.write()?;
+                wb.write_opt(wopts)?;
             }
         }
         Ok(())
     }
 
-    fn delete_all_in_range_cf_by_key(&self, cf: &str, range: &Range<'_>) -> Result<()> {
+    fn delete_all_in_range_cf_by_key(
```
Comment (overvenus) [inline components/engine_rocks/src/misc.rs:102]: Could you remove `self.should_skip(off, index)` in `Apply::apply_delete_range`? Because delete range no longer be traced by ApplyTrace, without WAL, it may leaks some keys after restart.

File: components/raftstore-v2/src/operation/query/capture.rs (hunk 3 above)
Comment (overvenus) [reply components/raftstore-v2/src/operation/query/capture.rs:62]: Yes, CDC may hang.

I wonder when it will be `None`?

Comment (tabokie) [reply components/raftstore-v2/src/operation/query/capture.rs:62]: When peer is being destroyed.

File: components/engine_rocks/src/misc.rs (hunk 4 above)
Comment (tabokie) [reply components/engine_rocks/src/misc.rs:102]: That would be incorrect, RocksDB write is not idempotent.

> Because delete range no longer be traced by ApplyTrace, without WAL, it may leaks some keys after restart.

How exactly? If memtable isn't flushed after delete range is applied, the log_recovery won't skip to re-apply it after restart.

File: components/raftstore-v2/src/operation/query/capture.rs (hunk 3 above)
Comment (tonyxuqqi) [reply components/raftstore-v2/src/operation/query/capture.rs:62]: @overvenus Then will TiCDC be able to recover from it?

Comment (overvenus) [reply components/raftstore-v2/src/operation/query/capture.rs:62]: Maybe, it should get a `RegionChangeEvent::Destroy` event.
Anyway, it's better to invoke callback actively.

```rust
if let Some(scheduler) = apply_scheduler { ... } else {
    capture_change.snap_cb.report_error(region_not_found)
}
```

File: src/server/service/kv.rs [hunk 5]
```diff
@@ -2296,6 +2296,7 @@ fn needs_reject_raft_append(reject_messages_on_memory_ratio: f64) -> bool {
         if (raft_msg_usage + cached_entries + applying_entries) as f64
             > usage as f64 * reject_messages_on_memory_ratio
         {
+            // FIXME: this doesn't output to logfile.
```
Comment (overvenus) [inline src/server/service/kv.rs:2299]: Something wrong with `slog_global`?

File: components/encryption/src/manager/mod.rs [hunk 6]
```diff
@@ -149,6 +153,7 @@ impl Dicts {
     }
 
     fn save_key_dict(&self, master_key: &dyn Backend) -> Result<()> {
+        let _lk = self.key_dict_file_lock.lock().unwrap();
```
Comment (overvenus) [inline components/encryption/src/manager/mod.rs:156]: When will it be rotated concurrently?

File: components/raftstore-v2/src/operation/command/admin/compact_log.rs [hunk 7]
```diff
@@ -97,7 +97,7 @@ impl CompactLogContext {
 
 impl<'a, EK: KvEngine, ER: RaftEngine, T: Transport> PeerFsmDelegate<'a, EK, ER, T> {
     pub fn on_compact_log_tick(&mut self, force: bool) {
-        if !self.fsm.peer().is_leader() {
+        if !self.fsm.peer().is_leader() || !self.fsm.peer().serving() {
```
Comment (overvenus) [inline components/raftstore-v2/src/operation/command/admin/compact_log.rs:100]: Is there any issue with the tick if peer is not serving?

Should we add the serving check to other ticks?

File: components/encryption/src/manager/mod.rs (hunk 6 above)
Comment (tabokie) [reply components/encryption/src/manager/mod.rs:156]: After keys get bulk imported, `DataKeyImporter` will trigger a force rotate.

File: src/server/service/kv.rs (hunk 5 above)
Comment (tabokie) [reply src/server/service/kv.rs:2299]: I don't know. I only know this branch is taken but no log is found.

File: components/raftstore-v2/src/operation/command/admin/compact_log.rs (hunk 7 above)
Comment (tabokie) [reply components/raftstore-v2/src/operation/command/admin/compact_log.rs:100]: Raft log is cleared and cannot get term.

File: etc/cargo.config.dist [hunk 8]
```diff
@@ -6,7 +6,7 @@
 opt-level = 3
 debug = true
 rpath = false
-lto = true
+lto = false
```
Comment (overvenus) [inline etc/cargo.config.dist:9]: It may affect performance.

**Review by overvenus — APPROVED** [review]

File: components/raftstore-v2/src/operation/query/capture.rs [hunk 9]
```diff
@@ -52,14 +52,24 @@ impl<'a, EK: KvEngine, ER: RaftEngine, T: raftstore::store::Transport>
...
+                scheduler.send(ApplyTask::CaptureApply(capture_change))
+            } else {
+                let mut resp = cmd_resp::err_resp(raftstore::Error::RegionNotFound(id), term);
```
Comment (tonyxuqqi) [inline components/raftstore-v2/src/operation/query/capture.rs:67]: Should we add some logs here since it should be very rare to happen.

**Review by tonyxuqqi — APPROVED** [review]

File: components/raftstore-v2/src/operation/query/capture.rs (hunk 9 above)
Comment (tabokie) [reply components/raftstore-v2/src/operation/query/capture.rs:67]: I presume cdc will handle the error? It's that component's responsibility.
