### PR TITLE
cop: handle unset scan details in store batch

### LINKED ISSUE #14109: cop: some scan details batch are mistakenly dropped
## Bug Report

https://github.com/tikv/tikv/blob/a33eb2d08991f278785e8b3047c643bf07839bce/src/coprocessor/endpoint.rs#L603-L607

The scan details are written into an empty one by the tracker, there are some details already generated in `resp`.

### What version of TiKV are you using?

nightly

### Steps to reproduce

Explain analyze a batched cop query from TiDB.

### What did you expect?

```
cop_task: {num: 1000, ..., iters:1000, tasks:1000}, scan_detail: {total_process_keys: 1000, ...}}}
```

### What did happened?

```
cop_task: {num: 1000, ..., iters:1000, tasks:1000}, scan_detail: {total_process_keys: 91, ...}}}
```

`total_process_keys` is not correct.

### PR DESCRIPTION
**Pull request by you06**
### What is changed and how it works?

Issue Number: Close #14109

What's Changed:

```
Handle the scan details which are mistakenly discarded before.
```

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Manual test (add detailed scripts or steps below)

Run a 1,000 rows query in TiDB, check the scan details:

- Before: `scan_detail: {total_process_keys: 91...}`
- After: `scan_detail: {total_process_keys: 1000...}`

Side effects

### Release note 

```release-note
None
```

### CODE REVIEW

File: src/coprocessor/endpoint.rs [hunk 1]
```diff
@@ -600,6 +600,8 @@ impl<E: Engine> Endpoint<E> {
                                     response.set_locked(lock_info);
                                 }
                                 response.set_other_error(resp.take_other_error());
+                                // keep the exec details already generated.
+                                response.set_exec_details_v2(resp.take_exec_details_v2());
```
Comment (cfzjywxk) [inline src/coprocessor/endpoint.rs:604]: Maybe we could combine the `execution path tracker` together with the `cop task tracker` and set execution details all from one tracker later.

**Review by cfzjywxk — APPROVED** [review]
LGTM

**Review by sticnarf — APPROVED** [review]
