### PR TITLE
In-memory Engine: reload regions evicted by region merge

### LINKED ISSUE #18098: In-memory Engine: Region merging leads to a load split ripple effect and causes latency spikes
## Bug Report

The latency spike in the following metrics is caused by a critical region (13511195) being evicted from IME due to region merge. The eviction causes a ripple effect, leading to load-based region splits and resulting in the server\_is\_busy error, which spikes latency.

Image

| Time | TiKV 1 | TiKV 2 |
|--------|--------|--------|
| 2025/01/07 11:49:19.140 | region 13511195 starts evict due to CommitMerge |  |
| 2025/01/07 11:49:19.493 | region 13511195 evict done |  |
| 2025/01/07 11:49:32.560 | region 13517458 load-splits from region 13511195 |  |
| 2025/01/07 11:49:43.672 | region 13517462 load-splits from region 13517458 |  |
| 2025/01/07 11:50:03.789 | region 13517472 load-splits from region 13517462 |  |
| 2025/01/07 11:50:15.858 | region 13517484 load-splits from region 13517472 |  |
| 2025/01/07 11:52:36.829 |  | region 13517484 became leader due to transfer leader |
| 2025/01/07 11:53:00.760 |  | region 13517523 load-splits from region 13517484 |
| 2025/01/07 11:53:12.829 |  | region 13517532 load-splits from region 13517523 |
| 2025/01/07 11:55:55.644 |  | ime auto load evict triggered |
| 2025/01/07 11:55:55.645 |  | region 13517484 / 13517532 are cached |

### What version of TiKV are you using?

nightly 2025-01-08

### Steps to reproduce

Run read-only high MVCC amplification workload.

### What did you expect?

No spike.

### What did happened?

Spike.

### PR DESCRIPTION
**Pull request by overvenus**
### What is changed and how it works?

Issue Number: Close #18098

What's Changed:

```commit-message
Reload cached regions that be evicted by `CommitMerge` and `RollbackMerge`
to reduce latency spike.
```

### Related changes

- [x] Need to cherry-pick to the release branch

### Check List

Tests 

- [x] Integration test

### Release note

```release-note
Reload cached regions that be evicted by `CommitMerge` and `RollbackMerge` to reduce latency spike.
```

### CODE REVIEW

File: components/hybrid_engine/src/observer/load_eviction.rs [hunk 1]
```diff
@@ -122,6 +137,23 @@ impl LoadEvictionObserver {
         });
     }
 
+    fn merge_region(&self, region: CacheRegion, modified_region: Region) {
```
Comment (LykxSassinator) [inline components/hybrid_engine/src/observer/load_eviction.rs:140]: Please add some necessary annotations here to indicate that this function is used for reloading the merged region or rolled-back region after evicting the corresponding original stale region.

File: components/hybrid_engine/src/observer/load_eviction.rs [hunk 2]
```diff
@@ -74,23 +74,38 @@ impl LoadEvictionObserver {
...
+                    "admin_command" => ?cmd.request.get_admin_request().get_cmd_type(),
+                );
+                self.evict_region(cache_region, EvictReason::PrepareMerge)
+            } else if matches!(
+                cmd.request.get_admin_request().get_cmd_type(),
+                AdminCmdType::CommitMerge | AdminCmdType::RollbackMerge
+            ) {
+                let cache_region = CacheRegion::from_region(ctx.region());
+                debug!(
+                    "ime evict range due to apply commands";
```
Comment (LykxSassinator) [inline components/hybrid_engine/src/observer/load_eviction.rs:103]: How about:
```suggestion
                    "ime evict range followed by reloading due to apply commands";
```

File: components/hybrid_engine/src/observer/load_eviction.rs [hunk 3]
```diff
@@ -74,23 +74,38 @@ impl LoadEvictionObserver {
...
                 "region" => ?cache_region,
-                "is_ingest_sst" => apply.pending_handle_ssts.is_some(),
-                "admin_command" => ?cmd.request.get_admin_request().get_cmd_type(),
             );
-            self.evict_region(cache_region, EvictReason::Merge)
+            self.evict_region(cache_region, EvictReason::IngestSST)
+        }
+        if let Some(modified_region) = &state.modified_region {
+            if matches!(
+                cmd.request.get_admin_request().get_cmd_type(),
```
Comment (LykxSassinator) [inline components/hybrid_engine/src/observer/load_eviction.rs:87]: How about getting the `cmd_type` in advance ?

**Review by LykxSassinator — COMMENTED** [review]
rest LGTM

**Review by glorv — APPROVED** [review]

**Review by LykxSassinator — APPROVED** [review]
