### PR TITLE
raftstore: fix incorrect and misleading index logging in StoreMsg of slowlog.

### LINKED ISSUE #18561: raftstore: incorrect and misleading index logging in StoreMsg when slow logs exist
## Bug Report

When slow logs exist in the processing of `StoreFsm::handle_msgs`, the relevant raftstore
will print the corresponding `StoreMsg` for the developer to confirm which is the slowest
`StoreMsg`.

However, the current implementation prints the `StoreMsg` with incorrect index, generating
misleading debugging log.
```Rust
      // for `StoreFsm::handle_msgs`
      let mut distribution = [0; StoreMsg::<EK>::COUNT];
      for m in msgs.drain(..) {
            distribution[m.discriminant()] += 1;
            ...
      }
       slow_log!(
            T timer,
            "[store {}] handle {} store messages {:?}",
            self.fsm.store.id,
            count,
            StoreMsg::<EK>::VARIANTS.iter().zip(distribution).filter(|(_, c)| *c > 0).format(", "),
        );
```
The root cause is that the `m.discriminant()` mismatches with the definition of `StoreMsg`:

Image

Image

For example, the slow `StoreMsg` should be `StoreMsg::CompactEvent` rather than `StoreMsg::Unreachable`,
but the logs are:
```
[2025/06/15 18:16:38.328 +00:00] [WARN] [store.rs:902] ["[store 22] handle 1 store messages (\"StoreUnreachable\", 1)"] [takes=1330] [thread_id=204]
```

### What version of TiKV are you using?

v7.5.6

### What operating system and CPU are you using?

Centos 7

### What did you expect?

The slow log should be `StoreMsg::CompactEvent` rather than `StoreMsg::Unreachable`.

### What did happened?

The slow log is `StoreMsg::Unreachable`.

### PR DESCRIPTION
**Pull request by LykxSassinator**
### What is changed and how it works?

Issue Number: Close https://github.com/tikv/tikv/issues/18561

What's Changed:

```commit-message
Fix incorrect and misleading index logging in StoreMsg of slowlog.
```

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [ ] Need to cherry-pick to the release branch

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note

```release-note
Fix incorrect and misleading index logging in StoreMsg of slowlog.
```

### CODE REVIEW

**Review by overvenus — APPROVED** [review]

**Review by hbisheng — APPROVED** [review]

File: components/raftstore/src/store/msg.rs [hunk 1]
```diff
@@ -939,15 +939,16 @@ where
...
     ClearRegionSizeInRange {
         start_key: Vec<u8>,
         end_key: Vec<u8>,
     },
-    StoreUnreachable {
-        store_id: u64,
-    },
 
     // Compaction finished event
     CompactedEvent(EK::CompactedEvent),
```
Comment (hbisheng) [inline components/raftstore/src/store/msg.rs]: `CompactedEvent` should be moved up as well? 

```
impl<EK: KvEngine> StoreMsg<EK> {
    pub fn discriminant(&self) -> usize {
        match self {
            StoreMsg::RaftMessage(_) => 0,
            StoreMsg::StoreUnreachable { .. } => 1,
            StoreMsg::CompactedEvent(_) => 2,
            StoreMsg::ClearRegionSizeInRange { .. } => 3,
            StoreMsg::Tick(_) => 4,
```
