### PR TITLE
cmd: add uid flag for TIKV_LOCK_FILES

### LINKED ISSUE #7462: After a user starts TiKV, other users will not be able to start TiKV
### What version of TiKV are you using?

TiKV
Release Version:   4.1.0-alpha
Git Commit Hash:   f2e7a835f61734409c5174a208164348b7326d6d
Git Commit Branch: master
Rust Version:      rustc 1.42.0-nightly (0de96d37f 2019-12-19)
Enable Features:   jemalloc portable sse protobuf-codec
Profile:           release

### What operating system and CPU are you using?

Unable to start

### Steps to reproduce

* User `foo` starts tikv at <ADDRESS 1>
* User `bar` starts tikv at <ADDRESS 2>

### What did you expect?

All started successfully.

### What did happened?

User `bar` cannot start tikv.

**Reason**: Running tikv will create a new lock under `/tmp/TIKV_LOCK_FILES/` to prevent starting multiple tikv at the same address. However, the folder permissions are owned by user `foo` at this time, and `bar` has no permissions.

```
# ll -a TIKV_LOCK_FILES
drwxr-xr-x     2 foo  foo     4096 Apr 14 19:03 .
drwxrwxrwt. 6927 root root 1298432 Apr 15 08:02 ..
-rw-r--r--     1 foo  foo        0 Apr 14 19:03 0.0.0.0_38820
```

### PR DESCRIPTION
**Pull request by hunterlxt**
Signed-off-by: TXXT <hunterlxt@live.com>

### What problem does this PR solve?

To allow multiple users create tikv and get rid of permission problem.
close #7462 

### What is changed and how it works?

Add UID for each TIKV_LOCK_FILES directory

### Related changes

- Need to cherry-pick to the release 4.0

### Check List 

- Unit test
- Integration test

Side effects

No

### CODE REVIEW

File: cmd/src/server.rs [hunk 1]
```diff
@@ -302,9 +302,20 @@ impl TiKVServer {
             .expect("failed to parse into a socket address");
         let cur_ip = cur_addr.ip();
         let cur_port = cur_addr.port();
+        let lock_dir: String;
 
-        let search_base = env::temp_dir().join("TIKV_LOCK_FILES");
-        std::fs::create_dir_all(&search_base).expect("create TIKV_LOCK_FILES failed");
+        #[cfg(target_os = "linux")]
+        {
+            lock_dir = format!("{}_TIKV_LOCK_FILES", unsafe { libc::getuid() });
```
Comment (BusyJay) [inline cmd/src/server.rs:309]: Can it be separated into a function?

File: cmd/src/server.rs [hunk 2]
```diff
@@ -302,9 +302,20 @@ impl TiKVServer {
             .expect("failed to parse into a socket address");
         let cur_ip = cur_addr.ip();
         let cur_port = cur_addr.port();
+        let lock_dir: String;
 
-        let search_base = env::temp_dir().join("TIKV_LOCK_FILES");
-        std::fs::create_dir_all(&search_base).expect("create TIKV_LOCK_FILES failed");
+        #[cfg(target_os = "linux")]
```
Comment (BusyJay) [inline cmd/src/server.rs:307]: I think `cfg(unix)` should be OK.

File: cmd/src/server.rs [hunk 3]
```diff
@@ -302,9 +302,11 @@ impl TiKVServer {
             .expect("failed to parse into a socket address");
         let cur_ip = cur_addr.ip();
         let cur_port = cur_addr.port();
+        let lock_dir = get_lock_dir();
 
-        let search_base = env::temp_dir().join("TIKV_LOCK_FILES");
-        std::fs::create_dir_all(&search_base).expect("create TIKV_LOCK_FILES failed");
+        let search_base = env::temp_dir().join(&lock_dir);
+        std::fs::create_dir_all(&search_base)
+            .unwrap_or_else(|_| panic!("create {} failed", lock_dir));
```
Comment (BusyJay) [inline cmd/src/server.rs:309]: Should be `search_base`.

File: cmd/src/server.rs [hunk 4]
```diff
@@ -920,6 +922,16 @@ fn try_lock_conflict_addr<P: AsRef<Path>>(path: P) -> File {
     f
 }
 
+#[cfg(target_family = "unix")]
```
Comment (BusyJay) [inline cmd/src/server.rs:925]: Why not use `cfg(unix)`?
