### PR TITLE
config: fix unproper online config and check

### LINKED ISSUE #14877: invalid configuration: max_sub_compactions should be greater than 0 and less than or equal to 2
### What version of TiKV are you using?

v6.5.2

### What operating system and CPU are you using?

CPU core >= 8

### Steps to reproduce

using config
```
[rocksdb]
max-background-jobs=2
```

### What did you expect?
start tikv-server without FATAL

### What did happened?
[2023/06/05 15:30:44.244 +08:00] [FATAL] [setup.rs:309] ["invalid configuration: max_sub_compactions should be greater than 0 and less than or equal to 2"]

### PR DESCRIPTION
**Pull request by 3pointer**
### What is changed and how it works?

Issue Number: Close #14877, #14934

What's Changed:
1. make some import config skip online change
2. remove validation of `max_sub_compactions`

```commit-message
```

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Manual test (add detailed scripts or steps below)

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

```release-note
Make TiKV skip and check config correctly. 
```

### CODE REVIEW

File: src/config/mod.rs [hunk 1]
```diff
@@ -1552,14 +1552,8 @@ impl DbConfig {
...
-        if self.max_sub_compactions == 0
-            || self.max_sub_compactions as i32 > self.max_background_jobs
-        {
-            return Err(format!(
-                "max_sub_compactions should be greater than 0 and less than or equal to {:?}",
-                self.max_background_jobs,
-            )
-            .into());
+        if self.max_sub_compactions == 0 {
+            return Err("max_sub_compactions should be greater than 0".into());
```
Comment (tonyxuqqi) [inline src/config/mod.rs:1556]: I think it's better to log a message and reset self.max_sub_compactions = self.max_background_jobs when self.max_background_jobs < self.max_sub_compactions.

Comment (tabokie) [reply src/config/mod.rs:1556]: Those two are actually unrelated. sub compactions are scheduled in temporary threads instead of the shared threadpool.

File: src/config/mod.rs [hunk 2]
```diff
@@ -1552,14 +1552,8 @@ impl DbConfig {
...
         }
-        if self.max_sub_compactions == 0
-            || self.max_sub_compactions as i32 > self.max_background_jobs
-        {
-            return Err(format!(
-                "max_sub_compactions should be greater than 0 and less than or equal to {:?}",
-                self.max_background_jobs,
-            )
-            .into());
+        if self.max_sub_compactions == 0 {
```
Comment (tabokie) [inline src/config/mod.rs:1555]: This restriction can be removed as well. Zero means disabling sub compaction.

**Review by tabokie — APPROVED** [review]

**Review by YuJuncen — APPROVED** [review]
