### PR TITLE
Security: work around race condition between threads updating handshakers

### LINKED ISSUE #7209: TiKV gRPC server coredump when TLS is enabled
## Bug Report

TiKV core dumps in BR TLS tests, see more https://github.com/pingcap/br/pull/202

### What version of TiKV are you using?

```
./tikv-server -V
TiKV
Release Version:   4.1.0-alpha
Git Commit Hash:   e364c57f69151c7fb4b00de591217f9edfedd61b
Git Commit Branch: master
UTC Build Time:    2020-03-21 07:37:31
Rust Version:      rustc 1.42.0-nightly (0de96d37f 2019-12-19)
Enable Features:   jemalloc portable sse protobuf-codec
Profile:           dist_release
```

### Steps to reproduce

Run BR integration tests

### What did you expect?

TiKV should start normally or report an error.

### What did happened?

Core dumped.

### PR DESCRIPTION
**Pull request by hunterlxt**
Signed-off-by: Xintao <hunterlxt@live.com>

### What problem does this PR solve?

Work around race condition between threads updating handshakers.

Multi threads could update `server_handshaker_factory_` in core, and they want to unref the previous `server_handshaker_factory_`. But when 2 more threads come in and try to unref it, something terrible happened.
```c++
    if (server_handshaker_factory_) {
      tsi_ssl_server_handshaker_factory_unref(server_handshaker_factory_);
    }
```
This PR reduced the frequency of updating certificates that 2 more threads will not modify handshaker at the same time.

### What is changed and how it works?

Add timer to record the last time for fetching cert and update every one second.

### Check List 

Tests 

- Unit test
- Integration test

Side effects

- Performance regression
NO
- Breaking backward compatibility
NO
### Release note 
Close #7209 and close pingcap/br#205

### CODE REVIEW

File: components/tikv_util/src/security.rs [hunk 1]
```diff
@@ -137,6 +138,9 @@ impl SecurityManager {
         } else {
             let fetcher = Box::new(Fetcher {
                 cfg: self.cfg.clone(),
+                last_fetch: Arc::new(Mutex::new(
```
Comment (yiwu-arbug) [inline components/tikv_util/src/security.rs]: should the `Mutex` be around the whole `Fetcher`, not just `last_fetch`?

**Comment by BusyJay** [comment]
Has the root cause be confirmed? What is the grpc related issue?

File: components/tikv_util/src/security.rs (hunk 1 above)
Comment (hunterlxt) [reply components/tikv_util/src/security.rs]: This mutex is only for restricting the modification of `last_fetch`. 
If I can add mutex directly to this fecher, it's better. But...This will force grpc-rs users who don't need mutex to use mutex. Maybe they only return `Ok(None)` most of the time. Another important reason is that the callback in grpc-core is not protected by mutex, so it is useless to lock in the callback function itself.

File: components/tikv_util/src/security.rs [hunk 2]
```diff
@@ -158,18 +162,29 @@ impl SecurityManager {
...
     fn fetch(&self) -> Result<Option<ServerCredentialsBuilder>, Box<dyn Error>> {
-        let (ca, cert, key) = self.cfg.load_certs()?;
-        let new_cred = ServerCredentialsBuilder::new()
-            .add_cert(cert, key)
-            .root_cert(
-                ca,
-                CertificateRequestType::RequestAndRequireClientCertificateAndVerify,
-            );
-        Ok(Some(new_cred))
+        if let Ok(mut last) = self.last_fetch.try_lock() {
```
Comment (overvenus) [inline components/tikv_util/src/security.rs]: I am not sure how it solves the problem.

Comment (hunterlxt) [reply components/tikv_util/src/security.rs]: Updated this PR detail.

File: components/tikv_util/src/security.rs (hunk 1 above)
Comment (yiwu-arbug) [reply components/tikv_util/src/security.rs]: If two caller calling `fetch` concurrently, they may both see a timeout and both go to fetch the config. If we lock the whole struct then one of them will wait while the other is fetching config.

Comment (yiwu-arbug) [reply components/tikv_util/src/security.rs]: This is where I find rust confusing.. By the logic, `cfg` is essentially also behind the mutex, since all caller of `fetch` need to wait on the mutex before getting access `cfg`. However the syntax make it appear that only `last_fetch` is behind the mutex. IMHO have the mutex guard the whole struct make the related more clear.

Comment (hunterlxt) [reply components/tikv_util/src/security.rs]: 1. Only one thread can get lock and see a timeout.
2. Locking the entire fetcher has no effect, because grpc-core could handle the result of the callback function concurrently.

Comment (hunterlxt) [reply components/tikv_util/src/security.rs]: Locking the entire Fetcher prevents connections that do not require a certificate update.

In the present case, they can return `Ok(None)` directly after the try fails, which means that they can continue to establish a connection using the previous certificate configuration

File: components/tikv_util/src/security.rs [hunk 3]
```diff
@@ -158,18 +162,29 @@ impl SecurityManager {
 
 struct Fetcher {
     cfg: Arc<SecurityConfig>,
+    last_fetch: Arc<Mutex<Instant>>,
```
Comment (overvenus) [inline components/tikv_util/src/security.rs]: Pre https://github.com/tikv/tikv/pull/7251/files#r398349060

```suggestion
    cfg: Arc<Mutex<(SecurityConfig, Instant)>>,
```

**Comment by overvenus** [comment]
> Multi threads could update server_handshaker_factory_ in core, and they want to unref the previous server_handshaker_factory_. But when 2 more threads come in and try to unref it, something terrible happened.

Sounds like we need to ref `server_handshaker_factory_` before update it.

File: components/tikv_util/src/security.rs (hunk 3 above)
Comment (hunterlxt) [reply components/tikv_util/src/security.rs]: `cfg` is read-only, why mutex protection is needed ?

**Comment by hunterlxt** [comment]
> > Multi threads could update server_handshaker_factory_ in core, and they want to unref the previous server_handshaker_factory_. But when 2 more threads come in and try to unref it, something terrible happened.
> 
> Sounds like we need to ref `server_handshaker_factory_` before update it.

`unref` means destroy original handshaker, why ref it before update?

File: components/tikv_util/src/security.rs (hunk 3 above)
Comment (hunterlxt) [reply components/tikv_util/src/security.rs]: How did you figure `grpc_threads * timeout`. It takes up to 1s after the certificate file is updated which means 0s~1s instead of `grpc_threads * timeout`.

File: components/tikv_util/src/security.rs (hunk 1 above)
Comment (hunterlxt) [reply components/tikv_util/src/security.rs]: > This is where I find rust confusing.. By the logic, `cfg` is essentially also behind the mutex, since all caller of `fetch` need to wait on the mutex before getting access to `cfg`. However the syntax make it appear that only `last_fetch` is behind the mutex. IMHO have the mutex guard the whole struct make the relation more clear.

@wujy-cs I know what you mean, but `cfg` is a read-only variable, adding mutex may cause ambiguity

**Comment by hunterlxt** [comment]
@BusyJay PTAL

File: components/tikv_util/src/security.rs [hunk 4]
```diff
@@ -158,18 +172,28 @@ impl SecurityManager {
...
     fn fetch(&self) -> Result<Option<ServerCredentialsBuilder>, Box<dyn Error>> {
-        let (ca, cert, key) = self.cfg.load_certs()?;
-        let new_cred = ServerCredentialsBuilder::new()
-            .add_cert(cert, key)
-            .root_cert(
-                ca,
-                CertificateRequestType::RequestAndRequireClientCertificateAndVerify,
-            );
-        Ok(Some(new_cred))
+        if let Ok(mut last) = self.last_modified_time.try_lock() {
```
Comment (yiwu-arbug) [inline components/tikv_util/src/security.rs]: `last_modified_time` never get updated?

File: components/tikv_util/src/security.rs (hunk 1 above)
Comment (yiwu-arbug) [reply components/tikv_util/src/security.rs]: > Locking the entire Fetcher prevents connections that do not require a certificate update.
> 
> In the present case, they can return `Ok(None)` directly after the try fails, which means that they can continue to establish a connection using the previous certificate configuration

I didn't notice it is a `try_lock` instead of `lock`. Can you add some inline comment about the "return Ok(None) immediately" behavior?

File: components/tikv_util/src/security.rs (hunk 4 above)
Comment (hunterlxt) [reply components/tikv_util/src/security.rs]: it's updated in `is_modified`

File: components/tikv_util/src/security.rs (hunk 1 above)
Comment (hunterlxt) [reply components/tikv_util/src/security.rs]: OK, done

File: components/tikv_util/src/security.rs [hunk 5]
```diff
@@ -137,6 +150,7 @@ impl SecurityManager {
         } else {
             let fetcher = Box::new(Fetcher {
                 cfg: self.cfg.clone(),
+                last_modified_time: Arc::new(Mutex::new(SystemTime::now())),
```
Comment (BusyJay) [inline components/tikv_util/src/security.rs]: How about using None instead of a specific time?

Comment (hunterlxt) [reply components/tikv_util/src/security.rs]: Fix

**Comment by brson** [comment]
There's no unsafe code in this PR and it fixes a coredump? Seems suspicous. What is the unsafe thing that is causing the dump?

**Comment by hunterlxt** [comment]
> There's no unsafe code in this PR and it fixes a coredump? Seems suspicous. What is the unsafe thing that is causing the dump?

FYI https://github.com/grpc/grpc/issues/22489

**Comment by brson** [comment]
> > There's no unsafe code in this PR and it fixes a coredump? Seems suspicous. What is the unsafe thing that is causing the dump?
> 
> FYI [grpc/grpc#22489](https://github.com/grpc/grpc/issues/22489)

@hunterlxt thanks. Can you add a comment in the code linking to this issue and indicating this is a workaround for a seeming bug in grpc?

File: components/tikv_util/src/security.rs (hunk 4 above)
Comment (BusyJay) [reply components/tikv_util/src/security.rs]: No, it's not.

File: components/tikv_util/src/security.rs [hunk 6]
```diff
@@ -97,6 +98,21 @@ impl SecurityConfig {
...
         Ok((ca, cert, key))
     }
+
+    /// Determine if the cert file has been modified.
+    /// If modified, update the timestamp of this modification.
+    fn is_modified(&self, last: &mut Option<SystemTime>) -> Result<bool, Box<dyn Error>> {
+        let this = fs::metadata(&self.cert_path)?.modified()?;
+        if let Some(last) = last {
+            if *last == this {
+                return Ok(false);
```
Comment (BusyJay) [inline components/tikv_util/src/security.rs]: Any tests?

Comment (hunterlxt) [reply components/tikv_util/src/security.rs]: test for updating certs and No coredump happens?

Comment (BusyJay) [reply components/tikv_util/src/security.rs]: Test for updating modified time.

Comment (hunterlxt) [reply components/tikv_util/src/security.rs]: Done
