### PR TITLE
*: mitigations for Raft Engine encryption key issue (#12892)

### LINKED ISSUE #12890: Encryption keys for WALs are not cleaned up when Raft Engine is enabled
### What version of TiKV are you using?

v6.1.0

### What operating system and CPU are you using?

N/A

### Steps to reproduce

Run write workload for a long time, observe the size of encryption key dictionary. The dictionary will grow indefinitely.

For a typical write workload, there are thousands of new WAL files generated by Raft Engine per day. The encryption keys associated with these files will not be cleaned up. They will occupy memory and disk space until one of them is full. Afterwards the server cannot be booted again.

This bug is not observed on any real cluster yet. Setting the severity to major for now.

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #12892 to release-6.1
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tikv repo:
git pr https://github.com/tikv/tikv/pull/13003
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tikv.git pr/13003:release-6.1-126da29086da
```

---

Signed-off-by: tabokie <xy.tao@outlook.com>

### What is changed and how it works?

Issue Number: Close #12890, #13123

What's Changed:

- Update Raft Engine and implement new trait methods.
  - `delete` ensures encryption keys of new files can be properly cleaned up.
  - `delete_metadata` helps Raft Engine cleans up stale encryption keys left from older version of TiKV.
- Update tikv-ctl to support scanning and purging encryption keys. If the server is shutdown due to OOM or disk full, this operation can still be executed to free up space.

### Related changes

https://github.com/tikv/raft-engine/pull/229

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

### Release note 

```release-note
Fix encryption keys not cleaned up when Raft Engine is enabled
```

### CODE REVIEW

File: components/raft_log_engine/src/lib.rs [hunk 1]
```diff
@@ -21,4 +21,12 @@
...
 mod engine;
+<<<<<<< HEAD
 pub use engine::{RaftEngineConfig, RaftLogBatch, RaftLogEngine, ReadableSize, RecoveryMode};
+=======
+mod perf_context;
+
+pub use engine::{
+    ManagedFileSystem, RaftEngineConfig, RaftLogBatch, RaftLogEngine, ReadableSize, RecoveryMode,
+};
+>>>>>>> 126da2908... *: mitigations for Raft Engine encryption key issue (#12892)
```
Comment (tabokie) [inline components/raft_log_engine/src/lib.rs:32]:
```suggestion

pub use engine::{
    ManagedFileSystem, RaftEngineConfig, RaftLogBatch, RaftLogEngine, ReadableSize, RecoveryMode,
};
```

File: cmd/tikv-ctl/src/cmd.rs [hunk 2]
```diff
@@ -539,6 +541,17 @@ pub enum Cmd {
...
+=======
+    /// Reset data in a TiKV to a certain version
+    ResetToVersion {
+        #[structopt(short = "v")]
+        /// The version to reset TiKV to
+        version: u64,
+    },
+    /// Control for Raft Engine
+    RaftEngineCtl { args: Vec<String> },
+>>>>>>> 126da2908... *: mitigations for Raft Engine encryption key issue (#12892)
```
Comment (tabokie) [inline cmd/tikv-ctl/src/cmd.rs:554]:
```suggestion
    /// Control for Raft Engine
    RaftEngineCtl { args: Vec<String> },
```

File: components/raft_log_engine/src/engine.rs [hunk 3]
```diff
@@ -9,8 +9,14 @@ use std::{
...
 use encryption::{DataKeyManager, DecrypterReader, EncrypterWriter};
 use engine_traits::{
+<<<<<<< HEAD
     CacheStats, EncryptionKeyManager, RaftEngine, RaftEngineDebug, RaftEngineReadOnly,
     RaftLogBatch as RaftLogBatchTrait, RaftLogGCTask, Result,
+=======
+    CacheStats, EncryptionKeyManager, EncryptionMethod, PerfContextExt, PerfContextKind, PerfLevel,
+    RaftEngine, RaftEngineDebug, RaftEngineReadOnly, RaftLogBatch as RaftLogBatchTrait,
+    RaftLogGCTask, Result,
+>>>>>>> 126da2908... *: mitigations for Raft Engine encryption key issue (#12892)
```
Comment (tabokie) [inline components/raft_log_engine/src/engine.rs:19]:
```suggestion
    CacheStats, EncryptionKeyManager, EncryptionMethod, RaftEngine, RaftEngineDebug,
    RaftEngineReadOnly, RaftLogBatch as RaftLogBatchTrait, RaftLogGCTask, Result,
```

**Review by glorv — APPROVED** [review]

**Review by tabokie — APPROVED** [review]
