### PR TITLE
raftstore: fix missing pending peers in region heartbeat after split

### LINKED ISSUE #17992: TiKV panics: [region 15822] 15824 status Some((15824, true)) is not expected
## Bug Report

```
/opt/tidb/kv.log:[2024/12/12 21:11:46.853 +00:00] [FATAL] [lib.rs:480] ["[region 15822] 15824 status Some((15824, true)) is not expected"] [backtrace="   0: tikv_util::set_panic_hook::{{closure}}
             at /home/stn/tikv/components/tikv_util/src/lib.rs:479:18
   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /home/stn/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2029:9
      std::panicking::rust_panic_with_hook
             at /home/stn/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:783:13
   2: std::panicking::begin_panic_handler::{{closure}}
             at /home/stn/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:657:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /home/stn/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:171:18
   4: rust_begin_unwind
             at /home/stn/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:645:5
   5: core::panicking::panic_fmt
             at /home/stn/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panicking.rs:72:14
   6: raftstore::store::fsm::peer::PeerFsmDelegate<EK,ER,T>::check_snapshot
             at /home/stn/tikv/components/raftstore/src/store/fsm/peer.rs:3642:17
   7: raftstore::store::fsm::peer::PeerFsmDelegate<EK,ER,T>::on_raft_message
             at /home/stn/tikv/components/raftstore/src/store/fsm/peer.rs:2771:40
      raftstore::store::fsm::peer::PeerFsmDelegate<EK,ER,T>::handle_msgs
             at /home/stn/tikv/components/raftstore/src/store/fsm/peer.rs:653:37
   8: <raftstore::store::fsm::store::RaftPoller<EK,ER,T> as batch_system::batch::PollHandler<raftstore::store::fsm::peer::PeerFsm<EK,ER>,raftstore::store::fsm::store::StoreFsm<EK>>>::handle_normal
             at /home/stn/tikv/components/raftstore/src/store/fsm/store.rs:1098:9
      batch_system::batch::Poller<N,C,Handler>::poll
             at /home/stn/tikv/components/batch-system/src/batch.rs:458:27
   9: batch_system::batch::BatchSystem<N,C>::start_poller::{{closure}}
             at /home/stn/tikv/components/batch-system/src/batch.rs:589:17
      <std::thread::Builder as tikv_util::sys::thread::StdThreadBuildWrapper>::spawn_wrapper::{{closure}}
             at /home/stn/tikv/components/tikv_util/src/sys/thread.rs:438:13
      std::sys_common::backtrace::__rust_begin_short_backtrace
             at /home/stn/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:155:18
  10: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
             at /home/stn/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:529:17
      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /home/stn/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panic/unwind_safe.rs:272:9
      std::panicking::try::do_call
             at /home/stn/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:552:40
      std::panicking::try
             at /home/stn/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:516:19
      std::panic::catch_unwind
             at /home/stn/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:142:14
      std::thread::Builder::spawn_unchecked_::{{closure}}
             at /home/stn/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:528:30
      core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /home/stn/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5
  11: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /home/stn/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2015:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /home/stn/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2015:9
      std::sys::unix::thread::Thread::new::thread_start
             at /home/stn/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys/unix/thread.rs:108:17
  12: start_thread
  13: clone
"] [location=/home/stn/tikv/components/raftstore/src/store/fsm/peer.rs:3642] [thread_name=raftstore-8-1] [thread_id=144]
```

https://tcms.pingcap.net/dashboard/executions/plan/7698101

### What version of TiKV are you using?

https://github.com/tikv/tikv/pull/17948

### Steps to reproduce

Run jepsen tests.

### What did you expect?

No panic.

### What did happened?

Panic.

### PR DESCRIPTION
**Pull request by hbisheng**
### What is changed and how it works?

Issue Number: Close #17992

Since #7672, TiKV has relied on the guarantee that all merge target peers must exist before PD initiates a merge. However, this guarantee was broken in the scenario in #17992, ultimately leading to a panic. 

PD uses `pending_peers` to verify whether all target peers exist before merging[1][2]. Investigations pointed to an issue in TiKV where it incorrectly reported missing pending peers after a split. More specifically, right after a split, TiKV triggers a new peer to upload a heartbeat[3], but at this point, the peer may not have been elected as the leader yet. Before this PR, a non-leader would always set the `pending_peers` to empty, causing PD to receive an incorrect region state. 

Since a non-leader has no knowledge of the progress of other peers, it should consevatively mark all other peers as pending. This fix ensures that PD receives correct `pending_peers` info, which should prevent the immature merge and avoiding the potential panic.

[1] [components/raftstore/src/store/fsm/peer.rs#L4686](https://github.com/tikv/tikv/blob/caf82d2864d1501af733bf60c99a7732e105144b/components/raftstore/src/store/fsm/peer.rs#L4686)
[2] [schedule/checker/merge_checker.go#L219](https://github.com/tikv/pd/blob/30e8ed7182c9fba1d01fa2437a5fb0937928ab94/pkg/schedule/checker/merge_checker.go#L219)
[3] [schedule/filter/healthy.go#L24](https://github.com/tikv/pd/blob/30e8ed7182c9fba1d01fa2437a5fb0937928ab94/pkg/schedule/filter/healthy.go#L24)

What's Changed:

```commit-message
Fixes an issue where TiKV incorrectly reported missing `pending_peers` after a 
split, causing PD to receive an incorrect region state. This could lead to 
premature merge attempts, violating the guarantee that all target peers must 
exist before merging.
```

Note: This issue is unlikely to occur in production since PD enforces a split-merge-interval (default: 1h) between split and merge operations. The issue only happens if a region is merged immediately after a split.

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [ ] Need to cherry-pick to the release branch

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by hbisheng** [comment]
> Possible fixes:
> 1. Enhance pending_create_peer (introduced in https://github.com/tikv/tikv/pull/8084)
Using the info in pending_create_peer, we can block the snapshot if a conflicting split is about to happen, or block the split if a conflicting snapshot passes the snapshot check.
> 2. Leader ensures all merge target peers exist before proposing a merge:
This might be achieved using an ExtraMessage mechanism. It would allow us to rely on the assumption in https://github.com/tikv/tikv/pull/7672 once again.

I gave up on option 1 because blocking a split after it's committed is non-intuitive and prone to more race conditions. I'm now looking into option 2 to prevent the merge from happening in the first place.

File: components/raftstore/src/store/peer.rs [hunk 1]
```diff
@@ -2109,6 +2109,17 @@ where
         }
 
         if status.progress.is_none() {
+            // If `progress` is None, the current node is not the leader. Since
```
Comment (LykxSassinator) [inline components/raftstore/src/store/peer.rs:2112]: NIT: it's better to add extra annotations here to specify that the calling of this part will only be executed by a new `campaigned` peer, who will most likely be elected as the new leader of the region.

Comment (hbisheng) [reply components/raftstore/src/store/peer.rs]: Added more comment as suggested

File: components/raftstore/src/store/peer.rs [hunk 2]
```diff
@@ -2109,6 +2109,21 @@ where
         }
 
         if status.progress.is_none() {
+            // If `progress` is None, the current node is not the leader.
```
Comment (Connor1996) [inline components/raftstore/src/store/peer.rs:2112]: How about adding an assert here

Comment (hbisheng) [reply components/raftstore/src/store/peer.rs:2112]: Asserting that the peer is not a leader? That should always be the case according to the [logic in rust-rs](https://github.com/tikv/raft-rs/blob/master/src/status.rs#L48). So yeah I can add an assert here.

Comment (hbisheng) [reply components/raftstore/src/store/peer.rs:2112]: It might seem a bit unnecessary though because `status()` was just called a few lines before (on line 2102）

**Review by overvenus — COMMENTED** [review]
Should we also reject PrepareMerge when there is a pending peer to further strengthen the region merge process?

**Comment by hbisheng** [comment]
> Should we also reject PrepareMerge when there is a pending peer to further strengthen the region merge process?

I hoped to do that too but it seems more complex than expected. The PrepareMerge proposal is sent to the merge _source_, but we actually need to check the pending peer on the merge _target_.

File: components/raftstore/src/store/peer.rs (hunk 2 above)
Comment (hbisheng) [reply components/raftstore/src/store/peer.rs:2112]: Added the assertion as suggested

**Comment by hbisheng** [comment]
@Connor1996 @overvenus @LykxSassinator PTAL again, thanks!

**Review by LykxSassinator — APPROVED** [review]
LGTM

**Review by Connor1996 — APPROVED** [review]
LGTM
