### PR TITLE
*: fix issue of modify resolved-ts.advance-ts-interval from 5s to 2s is not work

### LINKED ISSUE #15835: dynamic modify `resolved-ts.advance-ts-interval` from 5s to 2s is not work
### What version of TiKV are you using?

mirror issue of https://github.com/pingcap/tidb/issues/47978

### What did happened?

tikv version: v6.5.5

### PR DESCRIPTION
**Pull request by crazycs520**
### What is changed and how it works?

Issue Number: Close #15835

What's Changed:

```commit-message
```

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

```release-note
Please add a release note.

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

If you don't think this PR needs a release note then fill it with None.
If this PR will be picked to release branch, then a release note is probably required.
```

### CODE REVIEW

**Comment by crazycs520** [comment]
This is work,

image

File: components/resolved_ts/src/advance.rs [hunk 1]
```diff
@@ -106,10 +104,6 @@ impl AdvanceTsWorker {
         let pd_client = self.pd_client.clone();
         let scheduler = self.scheduler.clone();
         let timeout = self.timer.delay(advance_ts_interval);
-        let min_timeout = self.timer.delay(cmp::min(
-            DEFAULT_CHECK_LEADER_TIMEOUT_DURATION,
-            self.advance_ts_interval,
```
Comment (cfzjywxk) [inline components/resolved_ts/src/advance.rs:111]: The `self.advance_ts_interval` is not used any more it could be removed from the struct.

**Review by ekexium — APPROVED** [review]
