### PR TITLE
txn: use crossbeam-skiplist as the lock table implementation

### LINKED ISSUE #8576: Deadlock in the lock table
### What version of TiKV are you using?

Master

### Steps to reproduce

Enable async commit, then do transactions and do scanning at the same time. Then it is possible to cause a deadlock in the lock table. Then, lots of threads (including grpc and scheduler) will be blocked by the lock table, making TiKV unavailable.

### PR DESCRIPTION
**Pull request by sticnarf**
### What problem does this PR solve?

Issue Number: close #8576

### What is changed and how it works?

This PR switches the implementation of the lock table to crossbeam skiplist. Then, we naturally fix the deadlock bug in the previous implementation.

Although crossbeam-skiplist is not released, "the implementation is solid and finished", quoted from what the author said https://github.com/crossbeam-rs/crossbeam/issues/503#issuecomment-631679442.

~~According to https://github.com/crossbeam-rs/crossbeam/issues/204, crossbeam-skiplist does not provide linearizability guarantee. So in our uses in the lock table, I add some `SeqCst` fences to ensure it. I don't know if it's really necessary, however.~~

Our requirement doesn't need linearizability for the whole lock table. So the AcqRel order for a single key suffice. So no extra fences are needed.

Previously I intended to use an adaptive radix tree as the lock table implementation. But finally I find it does not provide good scan performance and it's also difficult to implement an iterator for a concurrent ART. After some benchmark, I find a skiplist can meet our performance requirement. So I decide to just use a concurrent skiplist.

### Check List 

Tests 

- Unit test

### Release note 

Part of async commit.

### CODE REVIEW

File: components/concurrency_manager/src/lock_table.rs [hunk 1]
```diff
@@ -2,28 +2,42 @@
...
-            if let Some(handle) = self.get(key) {
-                return handle.lock().await;
+            let handle = Arc::new(KeyHandle::new(key.clone(), self.clone()));
+            let weak = Arc::downgrade(&handle);
+            let weak2 = weak.clone();
+            let guard = handle.lock().await;
+
+            // SeqCst fences are added to ensure linearizability which crossbeam-skiplist itself
+            // does not provide (https://github.com/crossbeam-rs/crossbeam/issues/204).
+            // TODO: Do we really need this fence or can we use a more relaxed order?
```
Comment (nrc) [inline components/concurrency_manager/src/lock_table.rs:31]: My understanding is that we don't need these, get_or_insert has Acquire and Release Semantics, which seems strong enough to me

File: components/concurrency_manager/src/lock_table.rs [hunk 2]
```diff
@@ -2,28 +2,42 @@
...
+
+            if entry.value().ptr_eq(&weak2) {
+                return guard;
             } else {
-                let handle = Arc::new(KeyHandle::new(key.clone(), self.clone()));
-                let weak = Arc::downgrade(&handle);
-                let guard = handle.lock().await;
-                if self.insert_if_not_exist(key.clone(), weak) {
-                    return guard;
+                if let Some(handle) = entry.value().upgrade() {
```
Comment (nrc) [inline components/concurrency_manager/src/lock_table.rs:39]: nit: use `else if let ...`

**Review by nrc — APPROVED** [review]
lgtm

File: components/concurrency_manager/src/lock_table.rs (hunk 1 above)
Comment (sticnarf) [reply components/concurrency_manager/src/lock_table.rs]: Ah, I think we don't need linearizability for the whole lock table. So the AcqRel order for a single key suffice. So no extra fences are needed.

I've removed it.

File: components/concurrency_manager/src/lock_table.rs [hunk 3]
```diff
@@ -64,23 +70,10 @@ impl LockTable {
...
-                true
-            }
-            Entry::Occupied(_) => false,
-        }
-    }
-
     /// Gets the handle of the key.
     pub fn get<'m>(&'m self, key: &Key) -> Option<Arc<KeyHandle>> {
-        self.0.lock().get(key).and_then(|handle| handle.upgrade())
+        atomic::fence(atomic::Ordering::SeqCst);
```
Comment (MyonKeminta) [inline components/concurrency_manager/src/lock_table.rs:75]: This can also be removed if the fence is not necessary I think 🤔

**Review by MyonKeminta — APPROVED** [review]
Rest LGTM. By the way, since crossbeam claims that the skiplist is not released, I think maybe we can do some fuzz test to make sure it actually works for us

**Review by ti-srebot — APPROVED** [review]

**Comment by sticnarf** [comment]
> Rest LGTM. By the way, since crossbeam claims that the skiplist is not released, I think maybe we can do some fuzz test to make sure it actually works for us

Yes that's also what we should test
