### PR TITLE
raftstore: fix reset follow apply_unpersisted_log_limit when demoting from leader

### LINKED ISSUE #17868: TiKV panic with "assertion failed: cached_last < trunc_to_idx"
## Bug Report

```log
store/TiDB master bank-multitable auto-retry auto-retry-limit :default update-in-place select FOR UPDATE txn-mode pessimistic isolation :repeatable-read nemesis partition-half,partition-pd-leader,partition-ring,schedules/20241119T123842.000Z/node-1.node-peer.jepsen-tps-7527309-1-659/kv.log:[2024/11/19 12:48:10.846 +00:00] [FATAL] [lib.rs:480] ["assertion failed: cached_last < trunc_to_idx"] [backtrace="   0: tikv_util::set_panic_hook::{{closure}}\             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/tikv_util/src/lib.rs:479:18
   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2029:9
      std::panicking::rust_panic_with_hook
             at /rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:783:13
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:649:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:171:18
   4: rust_begin_unwind
             at /rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:645:5
   5: core::panicking::panic_fmt
             at /rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panicking.rs:72:14
   6: core::panicking::panic
             at /rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panicking.rs:144:5
   7: raftstore::store::entry_storage::EntryCache::append_impl
             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/entry_storage.rs:202:21
      raftstore::store::entry_storage::EntryCache::append
             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/entry_storage.rs:156:32
   8: raftstore::store::entry_storage::EntryStorage<EK,ER>::append
             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/entry_storage.rs:1098:9
   9: raftstore::store::peer_storage::PeerStorage<EK,ER>::handle_raft_ready
             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/peer_storage.rs:993:13
      raftstore::store::peer::Peer<EK,ER>::handle_raft_ready_append
             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/peer.rs:2878:37
  10: raftstore::store::fsm::peer::PeerFsmDelegate<EK,ER,T>::collect_ready
             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/fsm/peer.rs:2173:19
      <raftstore::store::fsm::store::RaftPoller<EK,ER,T> as batch_system::batch::PollHandler<raftstore::store::fsm::peer::PeerFsm<EK,ER>,raftstore::store::fsm::store::StoreFsm<EK>>>::handle_normal
             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/fsm/store.rs:1101:13
  11: batch_system::batch::Poller<N,C,Handler>::poll
             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/batch-system/src/batch.rs:416:27
  12: batch_system::batch::BatchSystem<N,C>::start_poller::{{closure}}
             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/batch-system/src/batch.rs:589:17
      <std::thread::Builder as tikv_util::sys::thread::StdThreadBuildWrapper>::spawn_wrapper::{{closure}}
             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/tikv_util/src/sys/thread.rs:438:13
      std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:155:18
  13: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
             at /rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:529:17
      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panic/unwind_safe.rs:272:9
      std::panicking::try::do_call
             at /rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:552:40
      std::panicking::try
             at /rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:516:19
      std::panic::catch_unwind
             at /rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:142:14
      std::thread::Builder::spawn_unchecked_::{{closure}}
             at /rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:528:30
      core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5
  14: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2015:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2015:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys/unix/thread.rs:108:17
  15: start_thread
  16: clone
"] [location=components/raftstore/src/store/entry_storage.rs:202] [thread_name=raftstore-1-1] [thread_id=144]
```

https://tcms.pingcap.net/dashboard/executions/plan/7527309

This panic is found by @SpadeA-Tang , thank you!

### What version of TiKV are you using?

Nightly 2024-11-18

### Steps to reproduce

Run jepsen-bank-tbls-pessimistic

### PR DESCRIPTION
**Pull request by glorv**
### What is changed and how it works?

Issue Number: Close #17868, ref #16717

What's Changed:

NOTE: this PR depends on PR https://github.com/tikv/raft-rs/pull/561

```commit-message
This PR adopt the changes in https://github.com/tikv/raft-rs/pull/561 that directly reset the apply_unpersisted_log_limit limit in raft when leader is demoted. It fix the bug that in the previous impl, the reset is done in "on_role_change" which is called in handle_raft_ready, in the round that leader is demoted, it still return unpersisted comitted entries as at the time, the limit is not reset.
NOTE: once we want to support this feature on follower, we need to remove the original assert as it is incorrect in this case.
```

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [ ] Need to cherry-pick to the release branch

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note

```release-note
None
```

### CODE REVIEW

File: tests/failpoints/cases/test_early_apply.rs [hunk 1]
```diff
@@ -159,3 +166,87 @@ fn test_early_apply_yield_followed_with_many_entries() {
...
+    let leader = cluster.leader_of_region(region.id).unwrap();
+    assert_ne!(leader.store_id, 1);
+
+    cluster.must_put(b"k1", b"v3");
+
+    // Send the dropped msg to store 1.
+    let mut msg = dropped_append.lock().unwrap().clone();
+    assert_eq!(msg.get_message().to, 1);
+    // Advance the committed index of the Append msg to trigger the corner case.
+    // I don't find an easy way to trigger this kind of msg, so direct modify the
```
Comment (hhwyt) [inline tests/failpoints/cases/test_early_apply.rs:232]: A practical solution 👍

**Comment by hhwyt** [comment]
typo in the PR descrption: "on_role_change" -> "on_role_changed"

File: components/raftstore/src/store/peer.rs [hunk 2]
```diff
@@ -806,6 +806,7 @@ where
     /// The index of last scheduled committed raft log.
     pub last_applying_idx: u64,
     pub max_apply_unpersisted_log_limit: u64,
+    enable_apply_unpersisted_log_state: bool,
```
Comment (LykxSassinator) [inline components/raftstore/src/store/peer.rs:809]: nit: is it necessary to add this member solely for triaging the trigger types of the `enable` and `disable` actions related to the "apply unpersisted log" feature?

If necessary, please add some annotations here.

Comment (glorv) [reply components/raftstore/src/store/peer.rs:814]: Done

**Review by Connor1996 — APPROVED** [review]
LGTM

**Review by LykxSassinator — COMMENTED** [review]
LGTM

File: tests/failpoints/cases/test_early_apply.rs [hunk 3]
```diff
@@ -159,3 +166,87 @@ fn test_early_apply_yield_followed_with_many_entries() {
...
     must_get_equal(&cluster.get_engine(3), b"k150", b"v150");
 }
+
+// Test the consistency of EntryCache when partitioned leader constains
+// uncommitted propose, and after the partition is recovered, it can replicate
+// raft entries for new leader correctly. This case test the corner scenario
+// that partitioned leader receive a new Append msg for new elected leader and
+// the new entries are already committed and overlap with existing entries
+// uncomitted entries in the entry cache, it may cause panic if handles
+// incorrectly. See issue https://github.com/tikv/tikv/issues/17868 for more details.
```
Comment (hbisheng) [inline tests/failpoints/cases/test_early_apply.rs:176]: i'm just a spell-checking bot 🤖 
```suggestion
// Test the consistency of EntryCache when partitioned leader contains
// uncommitted propose, and after the partition is recovered, it can replicate
// raft entries for new leader correctly. This case tests the corner scenario
// that partitioned leader receives a new Append msg from new elected leader and
// the new entries are already committed and overlap with existing
// uncommitted entries in the entry cache, it may cause panic if handled
// incorrectly. See issue https://github.com/tikv/tikv/issues/17868 for more details.
```

File: tests/failpoints/cases/test_early_apply.rs [hunk 4]
```diff
@@ -159,3 +166,87 @@ fn test_early_apply_yield_followed_with_many_entries() {
...
+            }))),
+        );
+    }
+
+    // propose a new write, the write should timeout.
+    let ch = cluster.async_put(b"k1", b"v2").unwrap();
+    block_on_timeout(ch, Duration::from_millis(100)).unwrap_err();
+
+    let fp = "pause_on_peer_collect_message";
+    // pause peer 1 to wait for leader timeout, should new leader
```
Comment (hbisheng) [inline tests/failpoints/cases/test_early_apply.rs:216]:
```suggestion
    // pause peer 1 to wait for leader timeout
```

**Review by hbisheng — COMMENTED** [review]
LGTM

**Review by overvenus — COMMENTED** [review]
LGTM, wait for raft-rs change.

**Comment by glorv** [comment]
@hbisheng @LykxSassinator  PTAL again as https://github.com/tikv/raft-rs/pull/561 is merged.

**Review by hbisheng — APPROVED** [review]

**Review by LykxSassinator — APPROVED** [review]
