### PR TITLE
cdc: do not send too much tasks if cannot be handled in time

### LINKED ISSUE #17696: TiDB latency not stable and TiKV OOM if running cdc changefeed when titan is on and average region size is large
### What version of TiKV are you using?
v8.4.0
31aa015dbe96bc5bcd676d7e32450f0205ceb104

### What operating system and CPU are you using?
X84, K8S

### Steps to reproduce
1. Deploy v8.4.0 cluster with 6 TiKV node (16C64G), titan is on.
2. br restore 4000 tables (~10TB)
3. start log backup task
4. create one CDC kafka changefeed to replicate the workload to Kafka
5. run workload

### What did you expect?
TiDB latency should be stable, when running workload

### What did happened?
TiDB latency not stable, and TiKV OOM seen.

image
image

### PR DESCRIPTION
**Pull request by 3AceShowHand**
### What is changed and how it works?

Issue Number: Close #17696 

What's Changed:

```commit-message
* take cdc tasks into memory quota to prevent the TiKV OOM caused by too many pending tasks
```

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [ ] Need to cherry-pick to the release branch

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note

```release-note
fix the TiKV may oom if too much internal pending tasks due to read old value too slow
```

### CODE REVIEW

File: components/cdc/src/endpoint.rs [hunk 1]
```diff
@@ -1334,16 +1366,34 @@ impl<T: 'static + CdcHandle<E>, E: KvEngine, S: StoreRegionMeta + Send> Runnable
...
+            scheduler,
+            memory_quota
+        }
     }
 }
 
 impl TxnExtraScheduler for CdcTxnExtraScheduler {
     fn schedule(&self, txn_extra: TxnExtra) {
+        let size = txn_extra.size();
+        if let Err(e) = self.memory_quota.alloc(size) {
```
Comment (overvenus) [inline components/cdc/src/endpoint.rs:1384]: Please use `alloc_force`.

File: components/cdc/src/endpoint.rs [hunk 2]
```diff
@@ -1334,16 +1338,26 @@ impl<T: 'static + CdcHandle<E>, E: KvEngine, S: StoreRegionMeta + Send> Runnable
...
+            memory_quota,
+        }
     }
 }
 
 impl TxnExtraScheduler for CdcTxnExtraScheduler {
     fn schedule(&self, txn_extra: TxnExtra) {
+        let size = txn_extra.size();
+        if let Err(e) = self.memory_quota.alloc(size) {
+            warn!("cdc schedule txn extra failed on alloc memory quota";
```
Comment (overvenus) [inline components/cdc/src/endpoint.rs:1357]: It may overwhelm tikv logs. How about changing to debug level and record such error in metric?

File: components/txn_types/src/types.rs [hunk 3]
```diff
@@ -567,6 +567,15 @@ impl TxnExtra {
...
         self.old_values.is_empty()
     }
+
+    pub fn size(&self) -> usize {
+        let mut result = 0;
+        for (key, value) in &self.old_values {
+            result += key.len();
+            result += value.0.size();
+        }
+        result + 8
```
Comment (overvenus) [inline components/txn_types/src/types.rs:577]: Why add 8? Please add some comments.

File: components/cdc/src/observer.rs [hunk 4]
```diff
@@ -119,15 +121,16 @@ impl<E: KvEngine> CmdObserver<E> for CdcObserver {
...
         let snapshot = RegionSnapshot::from_snapshot(Arc::new(engine.snapshot()), Arc::new(region));
         let get_old_value = move |key,
                                   query_ts,
                                   old_value_cache: &mut OldValueCache,
                                   statistics: &mut Statistics| {
             old_value::get_old_value(&snapshot, key, query_ts, old_value_cache, statistics)
         };
+
+        let size = cmd_batches.iter().map(|b| b.size()).sum();
+        self.memory_quota.alloc_force(size);
```
Comment (overvenus) [inline components/cdc/src/observer.rs:133]: Please add a test that ensures that too many pending `CmdBatch` causes `TxnExtra` to be dropped due to memory quota.

**Review by overvenus — COMMENTED** [review]
Rest LGTM

File: components/txn_types/src/types.rs (hunk 3 above)
Comment (3AceShowHand) [reply components/txn_types/src/types.rs:577]: +8 for extra 2 boolean fields in the `TxnExtra`

Comment (overvenus) [reply components/txn_types/src/types.rs]: How about `result+std::mem::size_of::<Self>()`?

File: components/txn_types/src/types.rs [hunk 5]
```diff
@@ -567,6 +567,16 @@ impl TxnExtra {
...
         self.old_values.is_empty()
     }
+
+    pub fn size(&self) -> usize {
+        let mut result = 0;
+        for (key, value) in &self.old_values {
+            result += key.len();
+            result += value.0.size();
+        }
+        // add 2 for 2 boolean fields
```
Comment (overvenus) [inline components/txn_types/src/types.rs:577]:
```suggestion
```

**Review by overvenus — APPROVED** [review]

**Review by hicqu — APPROVED** [review]
