### PR TITLE
copr: use criterion-perf-events to get instructions

### LINKED ISSUE #9671: mvcc benchmark will panic
### What version of TiKV are you using?

TiKV master with commit hash f4b03f

### Steps to reproduce

```bash
cargo test --benches -p tests -- mvcc
```

### What did you expect?

All benchmarks run successfully

### What did happened?

```
     Running target/debug/deps/hierarchy-2156d0f6b0bda058
Gnuplot not found, disabling plotting
Testing mvcc_prewrite/BTree_KL64_VL64
Success
Testing mvcc_prewrite/BTree_KL64_VL65
Success

Testing mvcc_commit/BTree_KL64_VL64
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: TxnLockNotFound { start_ts: TimeStamp(1), commit_ts: TimeStamp(1), key: [210, 31, 215, 113, 231, 218, 74, 181, 89, 133, 120, 212, 250, 41, 97, 195, 169, 30, 220, 33, 202, 121, 184, 60, 127, 35, 59, 216, 189, 229, 60, 250, 9, 133, 4, 141, 137, 148, 46, 216, 72, 40, 69, 219, 70, 232, 32, 202, 46, 151, 15, 80, 64, 249, 239, 14, 147, 185, 214, 0, 127, 193, 18, 188] }', tests/benches/hierarchy/mvcc/mod.rs:109:60
```

### PR DESCRIPTION
**Pull request by YangKeao**
Signed-off-by: Yang Keao <keao.yang@yahoo.com>

### What problem does this PR solve?

Remove `PAPI` dependency, which is really out of fashion now :face_with_head_bandage: , as the perf event document gets richer.

### What is changed and how it works?

Use `criterion-perf-events` rather than `criterion-papi` to get instructions counts during the benchmark.

The only degradation is that the unit is displayed as `cycles`, which is hard coded in `criterion-perf-events` :crying_cat_face: . Don't mind it because it doesn't effect the correctness of the result.

```
table_scan_datum_absent_large_row/RocksDB/batch/with_dag/rows=5000                                                                            
                        time:   [117543777.9983 cycles 117816414.1483 cycles 118078450.0667 cycles]

table_scan_long_datum_all/Memory/batch/next=1024                                                                            
                        time:   [1839019.2600 cycles 1839588.7667 cycles 1840377.1964 cycles]
Found 2 outliers among 100 measurements (2.00%)
  2 (2.00%) high severe
table_scan_long_datum_all/RocksDB/normal/with_dag/rows=5000                                                                             
                        time:   [20458704.2422 cycles 20462095.8382 cycles 20466490.3271 cycles]
Found 17 outliers among 100 measurements (17.00%)
  13 (13.00%) low severe
  4 (4.00%) high severe
table_scan_long_datum_all/RocksDB/batch/with_dag/rows=5000                                                                             
                        time:   [20461674.2794 cycles 20463698.1418 cycles 20466326.1559 cycles]
Found 11 outliers among 100 measurements (11.00%)
  2 (2.00%) low severe
  4 (4.00%) low mild
  1 (1.00%) high mild
  4 (4.00%) high severe
```

Besides this change, this PR also:

1. upgrade criterion to 0.3.4 and remove deprecated function calls
2. fix #9671

### Release note 

* No release note

### CODE REVIEW

**Review by breeswish — APPROVED** [review]
Cool!

**Comment by Xuanwo** [comment]
```
[2021-02-19T10:34:51.347Z] error: use of deprecated associated function `criterion::Criterion::<M>::bench_function_over_inputs`: Please use BenchmarkGroups instead.

[2021-02-19T10:34:51.347Z]   --> tests/benches/deadlock_detector/mod.rs:91:7

[2021-02-19T10:34:51.347Z]    |

[2021-02-19T10:34:51.347Z] 91 |     c.bench_function_over_inputs("bench_dense_detect_without_cleanup", bench_detect, cfgs);

[2021-02-19T10:34:51.347Z]    |       ^^^^^^^^^^^^^^^^^^^^^^^^^^

[2021-02-19T10:34:51.347Z]    |

```

Maybe we can solve this warning?

**Comment by YangKeao** [comment]
@Xuanwo Yes. These functions are deprecated on `criterion 0.3.4`, and they are removed now (in this PR).

**Review by sticnarf — APPROVED** [review]
LGTM

File: tests/benches/deadlock_detector/mod.rs [hunk 1]
```diff
@@ -80,28 +82,29 @@ fn bench_dense_detect_without_cleanup(c: &mut Criterion) {
...
-    let mut cfgs = vec![];
     for range in ranges {
-        cfgs.push(Config {
+        let config = Config {
             n: 10,
             range,
             ttl: Duration::from_secs(100000000),
-        });
+        };
+        group.bench_with_input(format!("{:?}", &config), &config, bench_detect);
```
Comment (sticnarf) [inline tests/benches/deadlock_detector/mod.rs:91]: This panics due to "Benchmark IDs must be unique within a group.". It's because the there are two `10_000` in the `ranges` array. :(

Comment (YangKeao) [reply tests/benches/deadlock_detector/mod.rs:90]: Fixed, by removing one of them :cry:

**Comment by YangKeao** [comment]
Oops, found a bug for one benchmark while testing this PR :smiley_cat: 

https://github.com/tikv/tikv/issues/9671, issue has been submitted.

**Comment by sticnarf** [comment]
> Oops, found a bug for one benchmark while testing this PR smiley_cat
> 
> #9671, issue has been submitted.

Could you help fix it in this PR? It is easy to fix :)

```
diff --git a/tests/benches/hierarchy/mvcc/mod.rs b/tests/benches/hierarchy/mvcc/mod.rs
index 47ba221e9..28caa111a 100644
--- a/tests/benches/hierarchy/mvcc/mod.rs
+++ b/tests/benches/hierarchy/mvcc/mod.rs
@@ -36,7 +36,7 @@ where
     .generate(DEFAULT_ITERATIONS);
     for (k, v) in &kvs {
         let txn_props = TransactionProperties {
-            start_ts: TimeStamp::default(),
+            start_ts,
             kind: TransactionKind::Optimistic(false),
             commit_kind: CommitKind::TwoPc,
             primary: &k.clone(),
diff --git a/tests/benches/hierarchy/txn/mod.rs b/tests/benches/hierarchy/txn/mod.rs
index 6fe7574b1..5efee71a3 100644
--- a/tests/benches/hierarchy/txn/mod.rs
+++ b/tests/benches/hierarchy/txn/mod.rs
@@ -32,7 +32,7 @@ where
     let kvs = KvGenerator::new(config.key_length, config.value_length).generate(DEFAULT_ITERATIONS);
     for (k, v) in &kvs {
         let txn_props = TransactionProperties {
-            start_ts: TimeStamp::default(),
+            start_ts,
             kind: TransactionKind::Optimistic(false),
             commit_kind: CommitKind::TwoPc,
             primary: &k.clone(),
```

**Comment by YangKeao** [comment]
@sticnarf Fixed

**Comment by sticnarf** [comment]
@breeswish @Xuanwo PTAL

**Review by Xuanwo — APPROVED** [review]
