### PR TITLE
In-memory Engine: fix the panic in write batch prepare

### LINKED ISSUE #17700: In-memory Engine: assert fails region 26972 is prepared for write before, but it is not the current region
## Bug Report

```
[2024/10/23 10:38:04.229 +08:00] [FATAL] [lib.rs:479] ["region 26972 is prepared for write before, but it is not the current region"] [backtrace="   0: tikv_util::set_panic_hook::{{closure}}
             at workspace/source/tikv/components/tikv_util/src/lib.rs:478:18
   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at root/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2029:9
      std::panicking::rust_panic_with_hook
             at root/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:783:13
   2: std::panicking::begin_panic_handler::{{closure}}
             at root/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:657:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at root/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:171:18
   4: rust_begin_unwind
             at root/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:645:5
   5: core::panicking::panic_fmt
             at root/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panicking.rs:72:14
   6: <in_memory_engine::write_batch::RegionCacheWriteBatch as engine_traits::write_batch::WriteBatch>::prepare_for_region
             at workspace/source/tikv/components/in_memory_engine/src/write_batch.rs:498:13
      <hybrid_engine::observer::write_batch::HybridObservableWriteBatch as engine_traits::write_batch::WriteBatch>::prepare_for_region
             at workspace/source/tikv/components/hybrid_engine/src/observer/write_batch.rs:106:9
   7: <raftstore::coprocessor::read_write::write_batch::WriteBatchWrapper<WB> as engine_traits::write_batch::WriteBatch>::prepare_for_region
             at workspace/source/tikv/components/raftstore/src/coprocessor/read_write/write_batch.rs:119:13
      raftstore::store::fsm::apply::ApplyContext<EK>::prepare_for
             at workspace/source/tikv/components/raftstore/src/store/fsm/apply.rs:546:9
      raftstore::store::fsm::apply::ApplyDelegate<EK>::handle_raft_committed_entries
             at workspace/source/tikv/components/raftstore/src/store/fsm/apply.rs:1133:9
   8: raftstore::store::fsm::apply::ApplyFsm<EK>::handle_apply
             at workspace/source/tikv/components/raftstore/src/store/fsm/apply.rs:4094:9
   9: raftstore::store::fsm::apply::ApplyFsm<EK>::handle_tasks
             at workspace/source/tikv/components/raftstore/src/store/fsm/apply.rs:4448:25
  10: <raftstore::store::fsm::apply::ApplyPoller<EK> as batch_system::batch::PollHandler<raftstore::store::fsm::apply::ApplyFsm<EK>,raftstore::store::fsm::apply::ControlFsm>>::handle_normal
             at workspace/source/tikv/components/raftstore/src/store/fsm/apply.rs:4746:9
  11: batch_system::batch::Poller<N,C,Handler>::poll
             at workspace/source/tikv/components/batch-system/src/batch.rs:422:27
  12: batch_system::batch::BatchSystem<N,C>::start_poller::{{closure}}
             at workspace/source/tikv/components/batch-system/src/batch.rs:551:17
      <std::thread::Builder as tikv_util::sys::thread::StdThreadBuildWrapper>::spawn_wrapper::{{closure}}
             at workspace/source/tikv/components/tikv_util/src/sys/thread.rs:438:13
      std::sys_common::backtrace::__rust_begin_short_backtrace
             at root/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:155:18
  13: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
             at root/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:529:17
      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at root/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panic/unwind_safe.rs:272:9
      std::panicking::try::do_call
             at root/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:552:40
      std::panicking::try
             at root/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:516:19
      std::panic::catch_unwind
             at root/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:142:14
      std::thread::Builder::spawn_unchecked_::{{closure}}
             at root/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:528:30
      core::ops::function::FnOnce::call_once{{vtable.shim}}
             at root/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5
  14: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at root/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2015:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at root/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2015:9
      std::sys::unix::thread::Thread::new::thread_start
             at root/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys/unix/thread.rs:108:17
  15: start_thread
  16: __GI___clone
"] [location=components/in_memory_engine/src/write_batch.rs:498] [thread_name=apply-0] [thread_id=125]
```

### What version of TiKV are you using?

Nightly 4ebb3001b22d13a5ec830aa32c4bb88e385a1ef0

### Steps to reproduce

Run HA test https://tcms.pingcap.net/dashboard/executions/plan/7639559

### What did you expect?

No assert failure

### PR DESCRIPTION
**Pull request by glorv**
### What is changed and how it works?

Issue Number: Close #17700

This panic can happen if the last Msg that ApplyFsm handles is `Msg::Change` or any other msg that explicitly triggers `commit`. Thus,  only ` prepare_for_region` is called but not `write_impl`, leaves the `RegionCacheWriteBatch` in a corrupted state.

What's Changed:

```commit-message
Call `wb.clear` even if the write batch is empty to avoid leaving
`RegionCacheWriteBatch` in a corrupted state.
```

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [ ] Need to cherry-pick to the release branch

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note

```release-note
None
```

### CODE REVIEW

File: components/raftstore/src/store/peer.rs [hunk 1]
```diff
@@ -3158,6 +3158,27 @@ where
             RAFT_APPLY_AHEAD_PERSIST_HISTOGRAM.observe(apply_ahead_delta as f64);
         }
         fail_point!("after_send_to_apply_1003", self.peer_id() == 1003, |_| {});
+        fail_point!(
+            "send_fake_apply_change_after_send_to_apply_1",
```
Comment (overvenus) [inline components/raftstore/src/store/peer.rs:3162]: Consider sending the message in tests to keep the code clean.

Try this in tests.

```rust
    cluster.get_apply_router(store_id);
```

**Comment by glorv** [comment]
@overvenus @SpadeA-Tang PTAL again, thanks~

File: components/test_raftstore/src/server.rs [hunk 2]
```diff
@@ -888,6 +888,10 @@ impl Simulator for ServerCluster {
     fn get_router(&self, node_id: u64) -> Option<RaftRouter<RocksEngine, RaftTestEngine>> {
         self.metas.get(&node_id).map(|m| m.raw_router.clone())
     }
+
+    fn get_apply_router(&self, node_id: u64) -> Option<ApplyRouter<RocksEngine>> {
+        self.metas.get(&node_id).map(|m| m.raw_apply_router.clone())
+    }
```
Comment (overvenus) [inline components/test_raftstore/src/server.rs:894]: Please remove the same method at line 230.

File: components/raftstore/src/store/fsm/apply.rs [hunk 3]
```diff
@@ -592,6 +592,7 @@ where
                 });
             self.pending_ssts = vec![];
         }
+
```
Comment (overvenus) [inline components/raftstore/src/store/fsm/apply.rs:595]: Remove this empty line.

File: components/raftstore/src/store/fsm/apply.rs [hunk 4]
```diff
@@ -629,6 +630,16 @@ where
...
             self.kv_wb_last_keys = 0;
+        } else {
+            fail_point!(
+                "after_write_to_db_skip_write_node_1",
+                self.store_id == 1,
+                |_| { unreachable!() }
+            );
+            // We call `clear` here because some WriteBatch impl may have some interal state
+            // that need to be reset even if the write batch is empty.
+            // Please refer to `RegionCacheWriteBatch::clear` for more details.
```
Comment (overvenus) [inline components/raftstore/src/store/fsm/apply.rs:641]:
```suggestion
            // We call `clear` here because some WriteBatch impl may have some
            // internal state that need to be reset even if the write batch is empty.
            // Please refer to `RegionCacheWriteBatch::clear` for more details.
```

**Review by SpadeA-Tang — APPROVED** [review]

File: components/test_raftstore/src/server.rs (hunk 2 above)
Comment (glorv) [reply components/test_raftstore/src/server.rs:890]: Done

**Review by overvenus — APPROVED** [review]
