### PR TITLE
resolved_ts: reduce network traffic by filter regions

### LINKED ISSUE #14092: Inter-TiKV idle network traffic increases about 100% since v6.5.0
### What version of TiKV are you using?

v6.5.0

The issue is caused by:
  - https://github.com/tikv/tikv/pull/12839
  - https://github.com/tikv/tikv/pull/13657

### Steps to reproduce

Create a cluster that has many regions (>20K).

### What did you expect?

The idle network traffic keeps the same as v6.1.0.
 
### What did happened?

The traffic increases about 100%.

### PR DESCRIPTION
**Pull request by overvenus**
### What is changed and how it works?

Issue Number: Close #14092

What's Changed:

Reduce network traffic by filter regions

```commit-message
resolved_ts: reduce network traffic by filter regions
```

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

### Release note 
 
```release-note
resolved_ts: reduce network traffic by filter regions
```

### CODE REVIEW

**Review by 3pointer — APPROVED** [review]

File: components/resolved_ts/src/advance.rs [hunk 1]
```diff
@@ -149,6 +149,7 @@ pub struct LeadershipResolver {
     region_map: HashMap<u64, Vec<Peer>>,
     // region_id -> peers id, record the responses.
     resp_map: HashMap<u64, Vec<u64>>,
+    checking_regions: HashSet<u64>,
```
Comment (tonyxuqqi) [inline components/resolved_ts/src/advance.rs:152]: There's no need to make checking_regions as struct's field, because its usage is within the resolve function. 
It's more clear and sometimes efficient to keep it inside the resolve function.

**Review by tonyxuqqi — APPROVED** [review]

**Review by Connor1996 — APPROVED** [review]
