### PR TITLE
raftstore: tolerate out-of-order read states from raft ready

### LINKED ISSUE #7402: one of tikv nodes crushed down during testing
## Question

I deployed a tikv cluster with binary files on centos for test env with 1 pd and 3 tikv nodes. After working for about 18 hours, one of the tikv nodes crushed down. I want to know whether is there anything wrong with my operation or configuration.

**Key configuration**

// pd
[replication]
max-replicas = 1
[schedule]
max-merge-region-size = 20
max-merge-region-keys = 200000
split-merge-interval = "1h"
max-snapshot-count = 3
max-pending-peer-count = 16
max-store-down-time = "30m"
leader-schedule-limit = 4
region-schedule-limit = 4
replica-schedule-limit = 8
merge-schedule-limit = 8
tolerant-size-ratio = 5.0

**log when crush down**
```
[2020/04/09 05:36:16.239 +08:00] [INFO] [peer.rs:1415] ["notify pd with change peer region"] [region="id: 21 start_key: 2D73746F72616765BC10B69CC1CEEEFE5B741E5A427247DE457AADF91B19634319D365DFEBB955824C3CD1DF104F941469E8C657C56FD5C26B2202F0 end_key: 2D73746F72616765BC10B69CC1CEEEFE5B741E5A427247DE457AADF91E89FC480698BC1C60905F1561F571667F71313E7DC4C1CD079D3335F9752D67 region_epoch { conf_ver: 10 version: 8 } peers { id: 107 store_id: 4 }"] [peer_id=107] [region_id=21]
[2020/04/09 05:36:28.218 +08:00] [INFO] [peer.rs:450] ["deleting applied snap file"] [snap_file=21_6_1793999] [peer_id=107] [region_id=21]
[2020/04/09 05:36:28.225 +08:00] [INFO] [peer.rs:450] ["deleting applied snap file"] [snap_file=65_6_619110] [peer_id=106] [region_id=65]
[2020/04/09 05:36:32.406 +08:00] [FATAL] [lib.rs:499] ["assertion failed: `(left == right)`\n  left: `[23, 72, 161, 100, 118, 81, 72, 150, 153, 116, 237, 163, 124, 47, 59, 220]`,\n right: `[162, 136, 174, 153, 78, 10, 77, 97, 137, 178, 123, 129, 82, 88, 195, 182]`"] [backtrace="stack backtrace:\n   0:     0x7f472c1faa5d - backtrace::backtrace::libunwind::trace::h958f5f3eb75b2917\n                        at /rust/registry/src/github.com-1ecc6299db9ec823/backtrace-0.2.3/src/backtrace/libunwind.rs:54\n                         - backtrace::backtrace::trace::hdf994f7eb3c12b81\n                        at /rust/registry/src/github.com-1ecc6299db9ec823/backtrace-0.2.3/src/backtrace/mod.rs:70\n   1:     0x7f472c1f0730 - tikv_util::set_panic_hook::{{closure}}::hf6c0260b2e4aea39\n                        at /home/jenkins/.target/release/build/backtrace-e20a32a05fd0b8fe/out/capture.rs:79\n   2:     0x7f472c39a78f - std::panicking::rust_panic_with_hook::h8d2408723e9a2bd4\n                        at src/libstd/panicking.rs:479\n   3:     0x7f472c39a56d - std::panicking::continue_panic_fmt::hb2aaa9386c4e5e80\n                        at src/libstd/panicking.rs:382\n   4:     0x7f472c39a51b - std::panicking::begin_panic_fmt::h1c91fada5a982dcd\n                        at src/libstd/panicking.rs:337\n   5:     0x7f472b8a8231 - tikv::raftstore::store::peer::Peer::handle_raft_ready_apply::h7a466f270c836fdb\n                        at src/raftstore/store/peer.rs:0\n

…………
```

### PR DESCRIPTION
**Pull request by hicqu**
Signed-off-by: qupeng <qupeng@pingcap.com>

### What problem does this PR solve?

Issue Number: close #7402 .

Problem Summary:

TiKV could panic because read states from raft ready are out of order.

### What is changed and how it works?

Tolerate this out-of-order case.

### Check List 

Tests 

- Integration test

Side effects

### Release note
* Tolerate out-of-order read states from raft ready

### CODE REVIEW

File: components/raftstore/src/store/read_queue.rs [hunk 1]
```diff
@@ -165,9 +165,17 @@ impl ReadIndexQueue {
         T: IntoIterator<Item = (Uuid, u64)>,
     {
         for (uuid, index) in states {
-            assert_eq!(uuid, self.reads[self.ready_cnt].id);
-            self.reads[self.ready_cnt].read_index = Some(index);
-            self.ready_cnt += 1;
+            // Read requests can be out-of-order even on leader.
```
Comment (BusyJay) [inline components/raftstore/src/store/read_queue.rs:168]: How?

Comment (hicqu) [reply components/raftstore/src/store/read_queue.rs:168]: Suppose a raft group contains 2 peers. Firstly we propose a read index on leader, it will wait a heartbeat response to get ready. Then we remove the another peer by configuration change, then propose a new read index again. Then the second one can be pushed into read states before the first one.
You can get more details in the new added test case.

Comment (BusyJay) [reply components/raftstore/src/store/read_queue.rs:168]: This seems related to tikv/raft-rs#345. I suggest to fix it in raft-rs, otherwise we can allow unexpected bugs succeed successfully.

Comment (hicqu) [reply components/raftstore/src/store/read_queue.rs:168]: Yes, fix it in raft-rs is better. So let the contributer try it?

File: tests/integrations/raftstore/test_replica_read.rs [hunk 2]
```diff
@@ -280,3 +280,41 @@ fn test_replica_read_on_stale_peer() {
...
+    cluster.must_put(b"k1", b"v1");
+    must_get_equal(&cluster.get_engine(2), b"k1", b"v1");
+
+    cluster.must_transfer_leader(1, new_peer(1, 1));
+
+    let filter = Box::new(
+        RegionPacketFilter::new(1, 1)
+            .direction(Direction::Recv)
+            .msg_type(MessageType::MsgHeartbeatResponse)
+            .when(Arc::new(AtomicBool::new(true))),
```
Comment (BusyJay) [inline tests/integrations/raftstore/test_replica_read.rs:308]: I don't think `when` is necessary.

File: tests/integrations/raftstore/test_replica_read.rs [hunk 3]
```diff
@@ -280,3 +280,41 @@ fn test_replica_read_on_stale_peer() {
...
+    );
+    cluster.sim.wl().add_recv_filter(1, filter);
+
+    let r1 = cluster.get_region(b"k1");
+    let resp = async_read_on_peer(&mut cluster, new_peer(1, 1), r1.clone(), b"k1", true, true);
+    assert!(resp.recv_timeout(Duration::from_secs(2)).is_err());
```
Comment (BusyJay) [inline tests/integrations/raftstore/test_replica_read.rs:314]: How does the case fail without the fix?

Comment (hicqu) [reply tests/integrations/raftstore/test_replica_read.rs:314]: Without the fix the case will panic when waiting at line 319.
