### PR TITLE
config: fix tests resource leak

### LINKED ISSUE #6994: tests resource leak
## Bug Report

After `make test`, there are `last_tikv.toml` in both the project root directory and tests directory. There apparently resource leak during tests. It's probably due to configuration are not generated in temporary directory during tests. I can confirm `test_update_raftstore_config` is one of the source that produces file in tests directory.

### What version of TiKV are you using?
master

### What operating system and CPU are you using?
Linux

### Steps to reproduce
make test

### What did you expect?
A clean workspace.

### What did happened?
git status shows there are dirty untrack files. The stale file in root directory is ignored accidentally by tikv/tikv#5377.

### PR DESCRIPTION
**Pull request by NingLin-P**
###  What have you changed?

Fix #6994 

###  What is the type of the changes?

- Bugfix (a change which fixes an issue)

###  How is the PR tested?
- Unit test

###  Does this PR affect documentation (docs) or should it be mentioned in the release notes?
No

###  Does this PR affect `tidb-ansible`?
No

### CODE REVIEW

**Comment by BusyJay** [comment]
It's not just about whether persist last configuration. Even it doesn't create toml files, it still create several empty folders like "raft", "db".

**Comment by NingLin-P** [comment]
> It's not just about whether persist last configuration. Even it doesn't create toml files, it still create several empty folders like "raft", "db".

Got it, will fix it later.

**Comment by BusyJay** [comment]
Any progress?

**Comment by NingLin-P** [comment]
> Any progress?

Sorry for the delay, will fix it today.

File: src/config.rs [hunk 1]
```diff
@@ -1889,15 +1889,15 @@ impl TiKvConfig {
         self.storage.validate()?;
 
         self.raft_store.region_split_check_diff = self.coprocessor.region_split_size / 16;
+
+        let store_path = Path::new(&self.storage.data_dir).to_owned();
         self.raft_store.raftdb_path = if self.raft_store.raftdb_path.is_empty() {
-            config::canonicalize_sub_path(&self.storage.data_dir, "raft")?
+            format!("{}", store_path.join("raft").display())
```
Comment (BusyJay) [inline src/config.rs]: The reason to `canonicalize_sub_path` is that "data" and "data/../data" won't become two different path, otherwise it will make TiKV fail to be restarted.

**Comment by NingLin-P** [comment]
PTAL @BusyJay

File: components/tikv_util/src/config.rs [hunk 2]
```diff
@@ -425,15 +425,23 @@ pub fn canonicalize_path(path: &str) -> Result<String, Box<dyn Error>> {
 }
 
 pub fn canonicalize_sub_path(path: &str, sub_path: &str) -> Result<String, Box<dyn Error>> {
-    let parent = Path::new(path);
-    let p = parent.join(Path::new(sub_path));
+    let mut p = Path::new(path).to_path_buf();
+    if !sub_path.is_empty() {
```
Comment (BusyJay) [inline components/tikv_util/src/config.rs]: Why need to check if it's empty?

File: components/tikv_util/src/config.rs [hunk 3]
```diff
@@ -425,15 +425,23 @@ pub fn canonicalize_path(path: &str) -> Result<String, Box<dyn Error>> {
...
+        p = p.join(Path::new(sub_path));
+    }
     if p.exists() && p.is_file() {
         return Err(format!("{}/{} is not a directory!", path, sub_path).into());
     }
+    let parent = Path::new(path).canonicalize()?;
```
Comment (BusyJay) [inline components/tikv_util/src/config.rs]: Why not reuse `p`?

File: src/config.rs [hunk 4]
```diff
@@ -1889,11 +1889,13 @@ impl TiKvConfig {
...
 
         self.raft_store.region_split_check_diff = self.coprocessor.region_split_size / 16;
-        self.raft_store.raftdb_path = if self.raft_store.raftdb_path.is_empty() {
-            config::canonicalize_sub_path(&self.storage.data_dir, "raft")?
-        } else {
-            config::canonicalize_path(&self.raft_store.raftdb_path)?
-        };
+
+        let default_raftdb_path = config::canonicalize_sub_path(&self.storage.data_dir, "raft")?;
+        if self.raft_store.raftdb_path.is_empty() {
```
Comment (BusyJay) [inline src/config.rs]: What's wrong with original implement?

File: cmd/src/server.rs [hunk 5]
```diff
@@ -214,6 +215,9 @@ impl TiKVServer {
             Default::default()
         };
 
+        ensure_dir_exist(&config.storage.data_dir).unwrap();
+        ensure_dir_exist(&config.raft_store.raftdb_path).unwrap();
```
Comment (BusyJay) [inline cmd/src/server.rs]: `raftdb_path` maybe empty.

File: components/tikv_util/src/config.rs (hunk 2 above)
Comment (NingLin-P) [reply components/tikv_util/src/config.rs]: If `sub_path ` is empty and `let p2 = p1.join(sub_path)`, `p2` will be a dir path which is different with `p1` and `p2.is_file()` will return `false`, even `p1` is exist and is a file!

File: src/config.rs (hunk 4 above)
Comment (NingLin-P) [reply src/config.rs]: 1.`validate` may run multiple time 
2.`canonicalize_sub_path` will not create dir, and will return error if `parent` not exist
if `raftdb_path` is empty first, it will set to `canonicalize_sub_path(data_dir, "raft")`, in the next run of `validate`, `canonicalize_path("data_dir/raft")` will return error because "data_dir/raft" may not exists, beside this it have the same behavior as master branch.

File: tests/integrations/config/test_config_client.rs [hunk 6]
```diff
@@ -309,9 +310,14 @@ fn test_dispatch_change() {
 fn test_restart_with_invalid_cfg_on_pd() {
     let pd_client = Arc::new(MockPdClient::new());
     let id = "localhost:1080";
+    let mut cfg = TiKvConfig::default();
+    cfg.storage.data_dir = {
+        let path = Builder::new().prefix("config_test").tempdir().unwrap();
```
Comment (BusyJay) [inline tests/integrations/config/test_config_client.rs]: `path` needs to outlive TiKV, otherwise the directory will be removed at L317.
