### PR TITLE
tikv_util: fix RangeLatch invalid memory access

### LINKED ISSUE #18671: tikv v9.0.x maybe  "null pointer dereference occurred" while load by lightning
### What version of TiKV are you using?

tikv v9.0.2-beta

### What operating system and CPU are you using?

Macbook, M1 pro.

### Steps to reproduce

compile tikv v9.0.2-beta by source code. 
use tiup playground build a cluster with 1 tidb v8.5.2, 1 pd v8.5.2, 3 tikv v9.0.2-beta and 0 tiflash.
use lightning load table data with `tidb` mode.  
table struct: `CREATE TABLE test_load (id INT PRIMARY KEY, data VARCHAR(1030));`
data size: 10 GB

### What did you expect?
no null pointer :)

### What did happened?
```
  - tikv quit: exit status 1
  Stamp(459171759227404295), TxnLocks { lock_count: 94, sample_lock: Some(7480000000000000785F7280000000328476F2) }))"] [applied_index=298381] [read_state="ReadState { idx: 282694, ts: 459171748728799240 }"] [gap=40179ms] [region_id=22] [thread_id=67]
  [2025/07/04 11:54:18.096 +08:00] [INFO] [raft.rs:1569] ["starting a new election"] [term=5] [raft_id=743] [region_id=740] [thread_id=101]
  [2025/07/04 11:54:18.096 +08:00] [INFO] [raft.rs:1213] ["became pre-candidate at term 5"] [term=5] [raft_id=743] [region_id=740] [thread_id=101]
  [2025/07/04 11:54:18.097 +08:00] [INFO] [raft.rs:1333] ["broadcasting vote request"] [to="[741, 742]"] [log_index=5] [log_term=5] [term=5] [type=MsgRequestPreVote] [raft_id=743] [region_id=740] [thread_id=101]
  [2025/07/04 11:54:24.546 +08:00] [INFO] [endpoint.rs:609] ["the max gap of leader resolved-ts is large"] [last_resolve_attempt=None] [duration_to_last_update_safe_ts=50103ms] [min_memory_lock="Some((TimeStamp(459171761875058690), 7480000000000000FF785F728000000032FFE7C0F00000000000FA))"] [txn_num=4] [lock_num=376] [min_lock="Some((TimeStamp(459171761848844296), TxnLocks { lock_count: 94, sample_lock: Some(7480000000000000785F728000000032F011D4) }))"] [applied_index=301296] [read_state="ReadState { idx: 282694, ts: 459171748728799240 }"] [gap=50181ms] [region_id=22] [thread_id=67]
  [2025/07/04 11:54:32.068 +08:00] [INFO] [size.rs:180] ["Run size checker"] [policy=Scan] [threshold=402653184] [size=484844140] [region_id=22] [thread_id=16]
  [2025/07/04 11:54:34.469 +08:00] [WARN] [advance.rs:431] ["check leader returns valid regions different from checking regions"] [checking_regions=52] [valid_regions=51] [thread_id=113]
  [2025/07/04 11:54:34.549 +08:00] [INFO] [endpoint.rs:609] ["the max gap of leader resolved-ts is large"] [last_resolve_attempt=None] [duration_to_last_update_safe_ts=60104ms] [min_memory_lock="Some((TimeStamp(459171764470284293), 7480000000000000FF785F728000000033FF6E948E0000000000FA))"] [txn_num=5] [lock_num=454] [min_lock="Some((TimeStamp(459171764457177089), TxnLocks { lock_count: 94, sample_lock: Some(7480000000000000785F728000000033655944) }))"] [applied_index=304436] [read_state="ReadState { idx: 282694, ts: 459171748728799240 }"] [gap=60180ms] [region_id=22] [thread_id=67]
  [2025/07/04 11:54:34.740 +08:00] [FATAL] [lib.rs:549] ["null pointer dereference occurred"] [backtrace="   0: backtrace::backtrace::libunwind::trace\n             at ~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/backtrace-0.3.61/src/backtrace/libunwind.rs:90:5\n      backtrace::backtrace::trace_unsynchronized\n             at ~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/backtrace-0.3.61/src/backtrace/mod.rs:66:5\n   1: backtrace::backtrace::trace\n             at ~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/backtrace-0.3.61/src/backtrace/mod.rs:53:14\n   2: backtrace::capture::Backtrace::create\n             at ~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/backtrace-0.3.61/src/capture.rs:176:9\n   3: backtrace::capture::Backtrace::new\n             at ~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/backtrace-0.3.61/src/capture.rs:140:22\n   4: tikv_util::set_panic_hook::{{closure}}\n             at ~/WorkSpace/forked_tikv/components/tikv_util/src/lib.rs:546:18\n   5: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call\n             at ~/.rustup/toolchains/nightly-2025-02-28-aarch64-apple-darwin/lib/rustlib/src/rust/library/alloc/src/boxed.rs:1986:9\n   6: std::panicking::rust_panic_with_hook\n             at ~/.rustup/toolchains/nightly-2025-02-28-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/panicking.rs:839:13\n   7: std::panicking::begin_panic_handler::{{closure}}\n             at ~/.rustup/toolchains/nightly-2025-02-28-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/panicking.rs:697:13\n   8: std::sys::backtrace::__rust_end_short_backtrace\n             at ~/.rustup/toolchains/nightly-2025-02-28-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/sys/backtrace.rs:168:18\n   9: rust_begin_unwind\n             at ~/.rustup/toolchains/nightly-2025-02-28-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/panicking.rs:695:5\n  10: core::panicking::panic_nounwind_fmt::runtime\n             at ~/.rustup/toolchains/nightly-2025-02-28-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/panicking.rs:117:22\n  11: core::panicking::panic_nounwind_fmt\n             at ~/.rustup/toolchains/nightly-2025-02-28-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/intrinsics/mod.rs:3089:9\n  12: core::panicking::panic_null_pointer_dereference\n             at ~/.rustup/toolchains/nightly-2025-02-28-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/panicking.rs:304:5\n  13: std::sys::sync::once_box::OnceBox<T>::get_unchecked\n             at ~/.rustup/toolchains/nightly-2025-02-28-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/sys/sync/once_box.rs:43:37\n  14: std::sys::sync::mutex::pthread::Mutex::unlock\n             at ~/.rustup/toolchains/nightly-2025-02-28-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/sys/sync/mutex/pthread.rs:41:18\n  15: <std::sync::poison::mutex::MutexGuard<T> as core::ops::drop::Drop>::drop\n             at ~/.rustup/toolchains/nightly-2025-02-28-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/sync/poison/mutex.rs:674:13\n  16: core::ptr::drop_in_place<std::sync::poison::mutex::MutexGuard<()>>\n             at ~/.rustup/toolchains/nightly-2025-02-28-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:523:1\n  17: core::ptr::drop_in_place<tikv_util::range_latch::RangeLatchGuard>\n             at ~/.rustup/toolchains/nightly-2025-02-28-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:523:1\n  18: core::ptr::drop_in_place<core::option::Option<tikv_util::range_latch::RangeLatchGuard>>\n             at ~/.rustup/toolchains/nightly-2025-02-28-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:523:1\n  19: tikv::server::gc_worker::compaction_filter::WriteCompactionFilter::flush_pending_writes_if_need\n             at ~/WorkSpace/forked_tikv/src/server/gc_worker/compaction_filter.rs:618:17\n  20: <tikv::server::gc_worker::compaction_filter::WriteCompactionFilter as core::ops::drop::Drop>::drop\n             at ~/WorkSpace/forked_tikv/src/server/gc_worker/compaction_filter.rs:728:25\n  21: core::ptr::drop_in_place<tikv::server::gc_worker::compaction_filter::WriteCompactionFilter>\n             at ~/.rustup/toolchains/nightly-2025-02-28-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:523:1\n  22: core::ptr::drop_in_place<rocksdb::compaction_filter::CompactionFilterProxy<tikv::server::gc_worker::compaction_filter::WriteCompactionFilter>>\n             at ~/.rustup/toolchains/nightly-2025-02-28-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:523:1\n  23: core::ptr::drop_in_place<alloc::boxed::Box<rocksdb::compaction_filter::CompactionFilterProxy<tikv::server::gc_worker::compaction_filter::WriteCompactionFilter>>>\n             at ~/.rustup/toolchains/nightly-2025-02-28-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:523:1\n  24: rocksdb::compaction_filter::destructor\n             at ~/.cargo/git/checkouts/rust-rocksdb-882d3d9019f8b391/755d152/src/compaction_filter.rs:102:71\n  25: _ZN27crocksdb_compactionfilter_tD2Ev\n             at ~/.cargo/git/checkouts/rust-rocksdb-882d3d9019f8b391/755d152/librocksdb_sys/crocksdb/c.cc:454:44\n  26: _ZN27crocksdb_compactionfilter_tD1Ev\n             at ~/.cargo/git/checkouts/rust-rocksdb-882d3d9019f8b391/755d152/librocksdb_sys/crocksdb/c.cc:454:42\n  27: _ZN27crocksdb_compactionfilter_tD0Ev\n             at ~/.cargo/git/checkouts/rust-rocksdb-882d3d9019f8b391/755d152/librocksdb_sys/crocksdb/c.cc:454:42\n  28: <unknown>\n             at /Library/Developer/CommandLineTools/SDKs/MacOSX15.5.sdk/usr/include/c++/v1/__memory/unique_ptr.h:81:5\n  29: <unknown>\n             at /Library/Developer/CommandLineTools/SDKs/MacOSX15.5.sdk/usr/include/c++/v1/__memory/unique_ptr.h:293:7\n  30: <unknown>\n             at /Library/Developer/CommandLineTools/SDKs/MacOSX15.5.sdk/usr/include/c++/v1/__memory/unique_ptr.h:262:71\n  31: <unknown>\n             at /Library/Developer/CommandLineTools/SDKs/MacOSX15.5.sdk/usr/include/c++/v1/__memory/unique_ptr.h:262:69\n  32: __ZN7rocksdb7titandb21TitanCompactionFilterD2Ev\n  33: __ZN7rocksdb7titandb21TitanCompactionFilterD1Ev\n  34: __ZN7rocksdb7titandb21TitanCompactionFilterD0Ev\n  35: <unknown>\n             at /Library/Developer/CommandLineTools/SDKs/MacOSX15.5.sdk/usr/include/c++/v1/__memory/unique_ptr.h:81:5\n  36: <unknown>\n             at /Library/Developer/CommandLineTools/SDKs/MacOSX15.5.sdk/usr/include/c++/v1/__memory/unique_ptr.h:293:7\n  37: <unknown>\n             at /Library/Developer/CommandLineTools/SDKs/MacOSX15.5.sdk/usr/include/c++/v1/__memory/unique_ptr.h:262:71\n  38: <unknown>\n             at /Library/Developer/CommandLineTools/SDKs/MacOSX15.5.sdk/usr/include/c++/v1/__memory/unique_ptr.h:262:69\n  39: <unknown>\n             at ~/.cargo/git/checkouts/rust-rocksdb-882d3d9019f8b391/755d152/librocksdb_sys/rocksdb/db/compaction/compaction_job.cc:1492:1\n  40: <unknown>\n             at /Library/Developer/CommandLineTools/SDKs/MacOSX15.5.sdk/usr/include/c++/v1/__type_traits/invoke.h:117:25\n  41: <unknown>\n             at /Library/Developer/CommandLineTools/SDKs/MacOSX15.5.sdk/usr/include/c++/v1/__thread/thread.h:198:3\n  42: <unknown>\n             at /Library/Developer/CommandLineTools/SDKs/MacOSX15.5.sdk/usr/include/c++/v1/__thread/thread.h:207:3\n  43: __pthread_cond_wait\n"] [location=~/.rustup/toolchains/nightly-2025-02-28-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/sys/sync/once_box.rs:43] [thread_name=<unnamed>] [thread_id=209]
  ...
  check detail log from: ~/.tiup/data/Upwu85a/tikv-2/tikv.log
  tikv quit: exit status 1
  0FA value:skipped assertion:None, Put key:7480000000000000FF785F728000000033FF5EA66D0000000000FA value:skipped assertion:None, Put key:7480000000000000FF785F728000000033FF5EAA550000000000FA value:skipped assertion:None, Put key:7480000000000000FF785F728000000033FF5EAE3D0000000000FA value:skipped assertion:None, Put key:7480000000000000FF785F728000000033FF5EB2250000000000FA value:skipped assertion:None, Put key:7480000000000000FF785F728000000033FF5EB60D0000000000FA value:skipped assertion:None, Put key:7480000000000000FF785F728000000033FF5EB9F50000000000FA value:skipped assertion:None, Put key:7480000000000000FF785F728000000033FF5EBDDD0000000000FA value:skipped assertion:None, Put key:7480000000000000FF785F728000000033FF5EC1C50000000000FA value:skipped assertion:None, Put key:7480000000000000FF785F728000000033FF5EC5AD0000000000FA value:skipped assertion:None, Put key:7480000000000000FF785F728000000033FF5EC9950000000000FA value:skipped assertion:None, Put key:7480000000000000FF785F728000000033FF5ECD7D0000000000FA value:skipped assertion:None, Put key:7480000000000000FF785F728000000033FF5ED1650000000000FA value:skipped assertion:None, Put key:7480000000000000FF785F728000000033FF5ED54D0000000000FA value:skipped assertion:None, Put key:7480000000000000FF785F728000000033FF5ED9350000000000FA value:skipped assertion:None, Put key:7480000000000000FF785F728000000033FF5EDD1D0000000000FA value:skipped assertion:None]) primary(7480000000000000785F7280000000335EA285) secondary_len(Some(93))@ 459171764562034689 3000 false 94 459171764562034690 459171765086322689 false Fast | region_id: 22 region_epoch { conf_ver: 5 version: 91 } peer { id: 179 store_id: 1 } max_execution_duration_ms: 20000 resource_group_tag: 0A20B94F08B8DD60DAAA2AA8E27CD49B738A0BAFCC1D63580B2E7138B69A4DC7A93E18012078 is_retry_request: true request_source: \"external_Insert_lightning\" resource_control_context { resource_group_name: \"default\" penalty {} override_priority: 8 } keyspace_id: 4294967295 source_stmt { connection_id: 4194306906 } cluster_id: 7523065782240116017"] [err="Error(Request(message: \"stale command\"))"] [cid=1012] [thread_id=43]
  [2025/07/04 11:54:50.462 +08:00] [INFO] [pd.rs:1848] ["succeed to update max timestamp"] [region_id=22] [thread_id=30]
  [2025/07/04 11:54:50.489 +08:00] [FATAL] [lib.rs:549] ["null pointer dereference occurred"] [backtrace="   0: backtrace::backtrace::libunwind::trace\n             at ~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/backtrace-0.3.61/src/backtrace/libunwind.rs:90:5\n      backtrace::backtrace::trace_unsynchronized\n             at ~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/backtrace-0.3.61/src/backtrace/mod.rs:66:5\n   1: backtrace::backtrace::trace\n             at ~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/backtrace-0.3.61/src/backtrace/mod.rs:53:14\n   2: backtrace::capture::Backtrace::create\n             at ~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/backtrace-0.3.61/src/capture.rs:176:9\n   3: backtrace::capture::Backtrace::new\n             at ~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/backtrace-0.3.61/src/capture.rs:140:22\n   4: tikv_util::set_panic_hook::{{closure}}\n             at ~/WorkSpace/forked_tikv/components/tikv_util/src/lib.rs:546:18\n   5: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call\n             at ~/.rustup/toolchains/nightly-2025-02-28-aarch64-apple-darwin/lib/rustlib/src/rust/library/alloc/src/boxed.rs:1986:9\n   6: std::panicking::rust_panic_with_hook\n             at ~/.rustup/toolchains/nightly-2025-02-28-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/panicking.rs:839:13\n   7: std::panicking::begin_panic_handler::{{closure}}\n             at ~/.rustup/toolchains/nightly-2025-02-28-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/panicking.rs:697:13\n   8: std::sys::backtrace::__rust_end_short_backtrace\n             at ~/.rustup/toolchains/nightly-2025-02-28-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/sys/backtrace.rs:168:18\n   9: rust_begin_unwind\n             at ~/.rustup/toolchains/nightly-2025-02-28-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/panicking.rs:695:5\n  10: core::panicking::panic_nounwind_fmt::runtime\n             at ~/.rustup/toolchains/nightly-2025-02-28-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/panicking.rs:117:22\n  11: core::panicking::panic_nounwind_fmt\n             at ~/.rustup/toolchains/nightly-2025-02-28-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/intrinsics/mod.rs:3089:9\n  12: core::panicking::panic_null_pointer_dereference\n             at ~/.rustup/toolchains/nightly-2025-02-28-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/panicking.rs:304:5\n  13: std::sys::sync::once_box::OnceBox<T>::get_unchecked\n             at ~/.rustup/toolchains/nightly-2025-02-28-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/sys/sync/once_box.rs:43:37\n  14: std::sys::sync::mutex::pthread::Mutex::unlock\n             at ~/.rustup/toolchains/nightly-2025-02-28-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/sys/sync/mutex/pthread.rs:41:18\n  15: <std::sync::poison::mutex::MutexGuard<T> as core::ops::drop::Drop>::drop\n             at ~/.rustup/toolchains/nightly-2025-02-28-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/sync/poison/mutex.rs:674:13\n  16: core::ptr::drop_in_place<std::sync::poison::mutex::MutexGuard<()>>\n             at ~/.rustup/toolchains/nightly-2025-02-28-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:523:1\n  17: core::ptr::drop_in_place<tikv_util::range_latch::RangeLatchGuard>\n             at ~/.rustup/toolchains/nightly-2025-02-28-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:523:1\n  18: core::ptr::drop_in_place<core::option::Option<tikv_util::range_latch::RangeLatchGuard>>\n             at ~/.rustup/toolchains/nightly-2025-02-28-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:523:1\n  19: tikv::server::gc_worker::compaction_filter::WriteCompactionFilter::flush_pending_writes_if_need\n             at ~/WorkSpace/forked_tikv/src/server/gc_worker/compaction_filter.rs:618:17\n  20: <tikv::server::gc_worker::compaction_filter::WriteCompactionFilter as core::ops::drop::Drop>::drop\n             at ~/WorkSpace/forked_tikv/src/server/gc_worker/compaction_filter.rs:728:25\n  21: core::ptr::drop_in_place<tikv::server::gc_worker::compaction_filter::WriteCompactionFilter>\n             at ~/.rustup/toolchains/nightly-2025-02-28-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:523:1\n  22: core::ptr::drop_in_place<rocksdb::compaction_filter::CompactionFilterProxy<tikv::server::gc_worker::compaction_filter::WriteCompactionFilter>>\n             at ~/.rustup/toolchains/nightly-2025-02-28-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:523:1\n  23: core::ptr::drop_in_place<alloc::boxed::Box<rocksdb::compaction_filter::CompactionFilterProxy<tikv::server::gc_worker::compaction_filter::WriteCompactionFilter>>>\n             at ~/.rustup/toolchains/nightly-2025-02-28-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:523:1\n  24: rocksdb::compaction_filter::destructor\n             at ~/.cargo/git/checkouts/rust-rocksdb-882d3d9019f8b391/755d152/src/compaction_filter.rs:102:71\n  25: _ZN27crocksdb_compactionfilter_tD2Ev\n             at ~/.cargo/git/checkouts/rust-rocksdb-882d3d9019f8b391/755d152/librocksdb_sys/crocksdb/c.cc:454:44\n  26: _ZN27crocksdb_compactionfilter_tD1Ev\n             at ~/.cargo/git/checkouts/rust-rocksdb-882d3d9019f8b391/755d152/librocksdb_sys/crocksdb/c.cc:454:42\n  27: _ZN27crocksdb_compactionfilter_tD0Ev\n             at ~/.cargo/git/checkouts/rust-rocksdb-882d3d9019f8b391/755d152/librocksdb_sys/crocksdb/c.cc:454:42\n  28: <unknown>\n             at /Library/Developer/CommandLineTools/SDKs/MacOSX15.5.sdk/usr/include/c++/v1/__memory/unique_ptr.h:81:5\n  29: <unknown>\n             at /Library/Developer/CommandLineTools/SDKs/MacOSX15.5.sdk/usr/include/c++/v1/__memory/unique_ptr.h:293:7\n  30: <unknown>\n             at /Library/Developer/CommandLineTools/SDKs/MacOSX15.5.sdk/usr/include/c++/v1/__memory/unique_ptr.h:262:71\n  31: <unknown>\n             at /Library/Developer/CommandLineTools/SDKs/MacOSX15.5.sdk/usr/include/c++/v1/__memory/unique_ptr.h:262:69\n  32: __ZN7rocksdb7titandb21TitanCompactionFilterD2Ev\n  33: __ZN7rocksdb7titandb21TitanCompactionFilterD1Ev\n  34: __ZN7rocksdb7titandb21TitanCompactionFilterD0Ev\n  35: <unknown>\n             at /Library/Developer/CommandLineTools/SDKs/MacOSX15.5.sdk/usr/include/c++/v1/__memory/unique_ptr.h:81:5\n  36: <unknown>\n             at /Library/Developer/CommandLineTools/SDKs/MacOSX15.5.sdk/usr/include/c++/v1/__memory/unique_ptr.h:293:7\n  37: <unknown>\n             at /Library/Developer/CommandLineTools/SDKs/MacOSX15.5.sdk/usr/include/c++/v1/__memory/unique_ptr.h:262:71\n  38: <unknown>\n             at /Library/Developer/CommandLineTools/SDKs/MacOSX15.5.sdk/usr/include/c++/v1/__memory/unique_ptr.h:262:69\n  39: <unknown>\n             at ~/.cargo/git/checkouts/rust-rocksdb-882d3d9019f8b391/755d152/librocksdb_sys/rocksdb/db/compaction/compaction_job.cc:1492:1\n  40: <unknown>\n             at /Library/Developer/CommandLineTools/SDKs/MacOSX15.5.sdk/usr/include/c++/v1/__type_traits/invoke.h:117:25\n  41: <unknown>\n             at /Library/Developer/CommandLineTools/SDKs/MacOSX15.5.sdk/usr/include/c++/v1/__thread/thread.h:198:3\n  42: <unknown>\n             at /Library/Developer/CommandLineTools/SDKs/MacOSX15.5.sdk/usr/include/c++/v1/__thread/thread.h:207:3\n  43: __pthread_cond_wait\n"] [location=~/.rustup/toolchains/nightly-2025-02-28-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/sys/sync/once_box.rs:43] [thread_name=<unnamed>] [thread_id=210]
  ...
  check detail log from: ~/.tiup/data/Upwu85a/tikv-1/tikv.log
  tikv quit: exit status 1
  FA, 7480000000000000FF785F728000000033FF5E313D0000000000FA, 7480000000000000FF785F728000000033FF5E35250000000000FA, 7480000000000000FF785F728000000033FF5E390D0000000000FA, 7480000000000000FF785F728000000033FF5E3CF50000000000FA, 7480000000000000FF785F728000000033FF5E40DD0000000000FA, 7480000000000000FF785F728000000033FF5E44C50000000000FA, 7480000000000000FF785F728000000033FF5E48AD0000000000FA, 7480000000000000FF785F728000000033FF5E4C950000000000FA, 7480000000000000FF785F728000000033FF5E507D0000000000FA, 7480000000000000FF785F728000000033FF5E54650000000000FA, 7480000000000000FF785F728000000033FF5E584D0000000000FA, 7480000000000000FF785F728000000033FF5E5C350000000000FA, 7480000000000000FF785F728000000033FF5E601D0000000000FA, 7480000000000000FF785F728000000033FF5E64050000000000FA, 7480000000000000FF785F728000000033FF5E67ED0000000000FA, 7480000000000000FF785F728000000033FF5E6BD50000000000FA, 7480000000000000FF785F728000000033FF5E6FBD0000000000FA, 7480000000000000FF785F728000000033FF5E73A50000000000FA, 7480000000000000FF785F728000000033FF5E778D0000000000FA, 7480000000000000FF785F728000000033FF5E7B750000000000FA, 7480000000000000FF785F728000000033FF5E7F5D0000000000FA, 7480000000000000FF785F728000000033FF5E83450000000000FA, 7480000000000000FF785F728000000033FF5E872D0000000000FA, 7480000000000000FF785F728000000033FF5E8B150000000000FA, 7480000000000000FF785F728000000033FF5E8EFD0000000000FA, 7480000000000000FF785F728000000033FF5E92E50000000000FA, 7480000000000000FF785F728000000033FF5E96CD0000000000FA, 7480000000000000FF785F728000000033FF5E9AB50000000000FA] 459171764509868034 -> 459171764522713090 | region_id: 22 region_epoch { conf_ver: 5 version: 91 } peer { id: 23 store_id: 2 } max_execution_duration_ms: 20000 resource_group_tag: 0A20B94F08B8DD60DAAA2AA8E27CD49B738A0BAFCC1D63580B2E7138B69A4DC7A93E18012078 is_retry_request: true request_source: \"external_Insert_lightning\" resource_control_context { resource_group_name: \"default\" penalty {} override_priority: 8 } keyspace_id: 4294967295 cluster_id: 7523065782240116017 heap_size: 5546"] [err="Error(Request(message: \"peer is not leader for region 22, leader may Some(id: 179 store_id: 1)\" not_leader { region_id: 22 leader { id: 179 store_id: 1 } }))"] [cid=72457] [thread_id=44]
  [2025/07/04 11:54:51.170 +08:00] [FATAL] [lib.rs:549] ["null pointer dereference occurred"] [backtrace="   0: backtrace::backtrace::libunwind::trace\n             at ~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/backtrace-0.3.61/src/backtrace/libunwind.rs:90:5\n      backtrace::backtrace::trace_unsynchronized\n             at ~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/backtrace-0.3.61/src/backtrace/mod.rs:66:5\n   1: backtrace::backtrace::trace\n             at ~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/backtrace-0.3.61/src/backtrace/mod.rs:53:14\n   2: backtrace::capture::Backtrace::create\n             at ~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/backtrace-0.3.61/src/capture.rs:176:9\n   3: backtrace::capture::Backtrace::new\n             at ~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/backtrace-0.3.61/src/capture.rs:140:22\n   4: tikv_util::set_panic_hook::{{closure}}\n             at ~/WorkSpace/forked_tikv/components/tikv_util/src/lib.rs:546:18\n   5: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call\n             at ~/.rustup/toolchains/nightly-2025-02-28-aarch64-apple-darwin/lib/rustlib/src/rust/library/alloc/src/boxed.rs:1986:9\n   6: std::panicking::rust_panic_with_hook\n             at ~/.rustup/toolchains/nightly-2025-02-28-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/panicking.rs:839:13\n   7: std::panicking::begin_panic_handler::{{closure}}\n             at ~/.rustup/toolchains/nightly-2025-02-28-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/panicking.rs:697:13\n   8: std::sys::backtrace::__rust_end_short_backtrace\n             at ~/.rustup/toolchains/nightly-2025-02-28-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/sys/backtrace.rs:168:18\n   9: rust_begin_unwind\n             at ~/.rustup/toolchains/nightly-2025-02-28-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/panicking.rs:695:5\n  10: core::panicking::panic_nounwind_fmt::runtime\n             at ~/.rustup/toolchains/nightly-2025-02-28-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/panicking.rs:117:22\n  11: core::panicking::panic_nounwind_fmt\n             at ~/.rustup/toolchains/nightly-2025-02-28-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/intrinsics/mod.rs:3089:9\n  12: core::panicking::panic_null_pointer_dereference\n             at ~/.rustup/toolchains/nightly-2025-02-28-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/panicking.rs:304:5\n  13: std::sys::sync::once_box::OnceBox<T>::get_unchecked\n             at ~/.rustup/toolchains/nightly-2025-02-28-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/sys/sync/once_box.rs:43:37\n  14: std::sys::sync::mutex::pthread::Mutex::unlock\n             at ~/.rustup/toolchains/nightly-2025-02-28-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/sys/sync/mutex/pthread.rs:41:18\n  15: <std::sync::poison::mutex::MutexGuard<T> as core::ops::drop::Drop>::drop\n             at ~/.rustup/toolchains/nightly-2025-02-28-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/sync/poison/mutex.rs:674:13\n  16: core::ptr::drop_in_place<std::sync::poison::mutex::MutexGuard<()>>\n             at ~/.rustup/toolchains/nightly-2025-02-28-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:523:1\n  17: core::ptr::drop_in_place<tikv_util::range_latch::RangeLatchGuard>\n             at ~/.rustup/toolchains/nightly-2025-02-28-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:523:1\n  18: core::ptr::drop_in_place<core::option::Option<tikv_util::range_latch::RangeLatchGuard>>\n             at ~/.rustup/toolchains/nightly-2025-02-28-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:523:1\n  19: tikv::server::gc_worker::compaction_filter::WriteCompactionFilter::flush_pending_writes_if_need\n             at ~/WorkSpace/forked_tikv/src/server/gc_worker/compaction_filter.rs:618:17\n  20: <tikv::server::gc_worker::compaction_filter::WriteCompactionFilter as core::ops::drop::Drop>::drop\n             at ~/WorkSpace/forked_tikv/src/server/gc_worker/compaction_filter.rs:728:25\n  21: core::ptr::drop_in_place<tikv::server::gc_worker::compaction_filter::WriteCompactionFilter>\n             at ~/.rustup/toolchains/nightly-2025-02-28-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:523:1\n  22: core::ptr::drop_in_place<rocksdb::compaction_filter::CompactionFilterProxy<tikv::server::gc_worker::compaction_filter::WriteCompactionFilter>>\n             at ~/.rustup/toolchains/nightly-2025-02-28-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:523:1\n  23: core::ptr::drop_in_place<alloc::boxed::Box<rocksdb::compaction_filter::CompactionFilterProxy<tikv::server::gc_worker::compaction_filter::WriteCompactionFilter>>>\n             at ~/.rustup/toolchains/nightly-2025-02-28-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:523:1\n  24: rocksdb::compaction_filter::destructor\n             at ~/.cargo/git/checkouts/rust-rocksdb-882d3d9019f8b391/755d152/src/compaction_filter.rs:102:71\n  25: _ZN27crocksdb_compactionfilter_tD2Ev\n             at ~/.cargo/git/checkouts/rust-rocksdb-882d3d9019f8b391/755d152/librocksdb_sys/crocksdb/c.cc:454:44\n  26: _ZN27crocksdb_compactionfilter_tD1Ev\n             at ~/.cargo/git/checkouts/rust-rocksdb-882d3d9019f8b391/755d152/librocksdb_sys/crocksdb/c.cc:454:42\n  27: _ZN27crocksdb_compactionfilter_tD0Ev\n             at ~/.cargo/git/checkouts/rust-rocksdb-882d3d9019f8b391/755d152/librocksdb_sys/crocksdb/c.cc:454:42\n  28: <unknown>\n             at /Library/Developer/CommandLineTools/SDKs/MacOSX15.5.sdk/usr/include/c++/v1/__memory/unique_ptr.h:81:5\n  29: <unknown>\n             at /Library/Developer/CommandLineTools/SDKs/MacOSX15.5.sdk/usr/include/c++/v1/__memory/unique_ptr.h:293:7\n  30: <unknown>\n             at /Library/Developer/CommandLineTools/SDKs/MacOSX15.5.sdk/usr/include/c++/v1/__memory/unique_ptr.h:262:71\n  31: <unknown>\n             at /Library/Developer/CommandLineTools/SDKs/MacOSX15.5.sdk/usr/include/c++/v1/__memory/unique_ptr.h:262:69\n  32: __ZN7rocksdb7titandb21TitanCompactionFilterD2Ev\n  33: __ZN7rocksdb7titandb21TitanCompactionFilterD1Ev\n  34: __ZN7rocksdb7titandb21TitanCompactionFilterD0Ev\n  35: <unknown>\n             at /Library/Developer/CommandLineTools/SDKs/MacOSX15.5.sdk/usr/include/c++/v1/__memory/unique_ptr.h:81:5\n  36: <unknown>\n             at /Library/Developer/CommandLineTools/SDKs/MacOSX15.5.sdk/usr/include/c++/v1/__memory/unique_ptr.h:293:7\n  37: <unknown>\n             at /Library/Developer/CommandLineTools/SDKs/MacOSX15.5.sdk/usr/include/c++/v1/__memory/unique_ptr.h:262:71\n  38: <unknown>\n             at /Library/Developer/CommandLineTools/SDKs/MacOSX15.5.sdk/usr/include/c++/v1/__memory/unique_ptr.h:262:69\n  39: <unknown>\n             at ~/.cargo/git/checkouts/rust-rocksdb-882d3d9019f8b391/755d152/librocksdb_sys/rocksdb/db/compaction/compaction_job.cc:1492:1\n  40: <unknown>\n             at /Library/Developer/CommandLineTools/SDKs/MacOSX15.5.sdk/usr/include/c++/v1/__type_traits/invoke.h:117:25\n  41: <unknown>\n             at /Library/Developer/CommandLineTools/SDKs/MacOSX15.5.sdk/usr/include/c++/v1/__thread/thread.h:198:3\n  42: <unknown>\n             at /Library/Developer/CommandLineTools/SDKs/MacOSX15.5.sdk/usr/include/c++/v1/__thread/thread.h:207:3\n  43: __pthread_cond_wait\n"] [location=~/.rustup/toolchains/nightly-2025-02-28-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/sys/sync/once_box.rs:43] [thread_name=<unnamed>] [thread_id=210]
  ...
  check detail log from: ~/.tiup/data/Upwu85a/tikv-0/tikv.log
```

detail log:
```
  - [2025/07/04 11:54:50.489 +08:00] [FATAL] [lib.rs:549] ["null pointer dereference occurred"] [backtrace="   0: backtrace::backtrace::libunwind::trace\n             at ~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/backtrace-0.3.61/src/backtrace/libunwind.rs:90:5\n      backtrace::backtrace::trace_unsynchronized\n             at ~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/backtrace-0.3.61/src/backtrace/mod.rs:66:5\n   1: backtrace::backtrace::trace\n             at ~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/backtrace-0.3.61/src/backtrace/mod.rs:53:14\n   2: backtrace::capture::Backtrace::create\n             at ~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/backtrace-0.3.61/src/capture.rs:176:9\n   3: backtrace::capture::Backtrace::new\n             at ~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/backtrace-0.3.61/src/capture.rs:140:22\n   4: tikv_util::set_panic_hook::{{closure}}\n             at ~/WorkSpace/forked_tikv/components/tikv_util/src/lib.rs:546:18\n   5: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call\n             at ~/.rustup/toolchains/nightly-2025-02-28-aarch64-apple-darwin/lib/rustlib/src/rust/library/alloc/src/boxed.rs:1986:9\n   6: std::panicking::rust_panic_with_hook\n             at ~/.rustup/toolchains/nightly-2025-02-28-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/panicking.rs:839:13\n   7: std::panicking::begin_panic_handler::{{closure}}\n             at ~/.rustup/toolchains/nightly-2025-02-28-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/panicking.rs:697:13\n   8: std::sys::backtrace::__rust_end_short_backtrace\n             at ~/.rustup/toolchains/nightly-2025-02-28-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/sys/backtrace.rs:168:18\n   9: rust_begin_unwind\n             at ~/.rustup/toolchains/nightly-2025-02-28-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/panicking.rs:695:5\n  10: core::panicking::panic_nounwind_fmt::runtime\n             at ~/.rustup/toolchains/nightly-2025-02-28-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/panicking.rs:117:22\n  11: core::panicking::panic_nounwind_fmt\n             at ~/.rustup/toolchains/nightly-2025-02-28-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/intrinsics/mod.rs:3089:9\n  12: core::panicking::panic_null_pointer_dereference\n             at ~/.rustup/toolchains/nightly-2025-02-28-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/panicking.rs:304:5\n  13: std::sys::sync::once_box::OnceBox<T>::get_unchecked\n             at ~/.rustup/toolchains/nightly-2025-02-28-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/sys/sync/once_box.rs:43:37\n  14: std::sys::sync::mutex::pthread::Mutex::unlock\n             at ~/.rustup/toolchains/nightly-2025-02-28-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/sys/sync/mutex/pthread.rs:41:18\n  15: <std::sync::poison::mutex::MutexGuard<T> as core::ops::drop::Drop>::drop\n             at ~/.rustup/toolchains/nightly-2025-02-28-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/sync/poison/mutex.rs:674:13\n  16: core::ptr::drop_in_place<std::sync::poison::mutex::MutexGuard<()>>\n             at ~/.rustup/toolchains/nightly-2025-02-28-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:523:1\n  17: core::ptr::drop_in_place<tikv_util::range_latch::RangeLatchGuard>\n             at ~/.rustup/toolchains/nightly-2025-02-28-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:523:1\n  18: core::ptr::drop_in_place<core::option::Option<tikv_util::range_latch::RangeLatchGuard>>\n             at ~/.rustup/toolchains/nightly-2025-02-28-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:523:1\n  19: tikv::server::gc_worker::compaction_filter::WriteCompactionFilter::flush_pending_writes_if_need\n             at ~/WorkSpace/forked_tikv/src/server/gc_worker/compaction_filter.rs:618:17\n  20: <tikv::server::gc_worker::compaction_filter::WriteCompactionFilter as core::ops::drop::Drop>::drop\n             at ~/WorkSpace/forked_tikv/src/server/gc_worker/compaction_filter.rs:728:25\n  21: core::ptr::drop_in_place<tikv::server::gc_worker::compaction_filter::WriteCompactionFilter>\n             at ~/.rustup/toolchains/nightly-2025-02-28-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:523:1\n  22: core::ptr::drop_in_place<rocksdb::compaction_filter::CompactionFilterProxy<tikv::server::gc_worker::compaction_filter::WriteCompactionFilter>>\n             at ~/.rustup/toolchains/nightly-2025-02-28-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:523:1\n  23: core::ptr::drop_in_place<alloc::boxed::Box<rocksdb::compaction_filter::CompactionFilterProxy<tikv::server::gc_worker::compaction_filter::WriteCompactionFilter>>>\n             at ~/.rustup/toolchains/nightly-2025-02-28-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:523:1\n  24: rocksdb::compaction_filter::destructor\n             at ~/.cargo/git/checkouts/rust-rocksdb-882d3d9019f8b391/755d152/src/compaction_filter.rs:102:71\n  25: _ZN27crocksdb_compactionfilter_tD2Ev\n             at ~/.cargo/git/checkouts/rust-rocksdb-882d3d9019f8b391/755d152/librocksdb_sys/crocksdb/c.cc:454:44\n  26: _ZN27crocksdb_compactionfilter_tD1Ev\n             at ~/.cargo/git/checkouts/rust-rocksdb-882d3d9019f8b391/755d152/librocksdb_sys/crocksdb/c.cc:454:42\n  27: _ZN27crocksdb_compactionfilter_tD0Ev\n             at ~/.cargo/git/checkouts/rust-rocksdb-882d3d9019f8b391/755d152/librocksdb_sys/crocksdb/c.cc:454:42\n  28: <unknown>\n             at /Library/Developer/CommandLineTools/SDKs/MacOSX15.5.sdk/usr/include/c++/v1/__memory/unique_ptr.h:81:5\n  29: <unknown>\n             at /Library/Developer/CommandLineTools/SDKs/MacOSX15.5.sdk/usr/include/c++/v1/__memory/unique_ptr.h:293:7\n  30: <unknown>\n             at /Library/Developer/CommandLineTools/SDKs/MacOSX15.5.sdk/usr/include/c++/v1/__memory/unique_ptr.h:262:71\n  31: <unknown>\n             at /Library/Developer/CommandLineTools/SDKs/MacOSX15.5.sdk/usr/include/c++/v1/__memory/unique_ptr.h:262:69\n  32: __ZN7rocksdb7titandb21TitanCompactionFilterD2Ev\n  33: __ZN7rocksdb7titandb21TitanCompactionFilterD1Ev\n  34: __ZN7rocksdb7titandb21TitanCompactionFilterD0Ev\n  35: <unknown>\n             at /Library/Developer/CommandLineTools/SDKs/MacOSX15.5.sdk/usr/include/c++/v1/__memory/unique_ptr.h:81:5\n  36: <unknown>\n             at /Library/Developer/CommandLineTools/SDKs/MacOSX15.5.sdk/usr/include/c++/v1/__memory/unique_ptr.h:293:7\n  37: <unknown>\n             at /Library/Developer/CommandLineTools/SDKs/MacOSX15.5.sdk/usr/include/c++/v1/__memory/unique_ptr.h:262:71\n  38: <unknown>\n             at /Library/Developer/CommandLineTools/SDKs/MacOSX15.5.sdk/usr/include/c++/v1/__memory/unique_ptr.h:262:69\n  39: <unknown>\n             at ~/.cargo/git/checkouts/rust-rocksdb-882d3d9019f8b391/755d152/librocksdb_sys/rocksdb/db/compaction/compaction_job.cc:1492:1\n  40: <unknown>\n             at /Library/Developer/CommandLineTools/SDKs/MacOSX15.5.sdk/usr/include/c++/v1/__type_traits/invoke.h:117:25\n  41: <unknown>\n             at /Library/Developer/CommandLineTools/SDKs/MacOSX15.5.sdk/usr/include/c++/v1/__thread/thread.h:198:3\n  42: <unknown>\n             at /Library/Developer/CommandLineTools/SDKs/MacOSX15.5.sdk/usr/include/c++/v1/__thread/thread.h:207:3\n  43: __pthread_cond_wait\n"] [location=~/.rustup/toolchains/nightly-2025-02-28-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/sys/sync/once_box.rs:43] [thread_name=<unnamed>] [thread_id=210]
```
The probability of occurrence is 1/5 ~ 2/5
maybe only occurs in v9.0.x, 
after testing, no reproduce in v8.5.2.

### LINKED ISSUE #18756: tikv memory fault in test_compaction_filter_blocked_by_clean_overlap_
## Bug Report
A low-probablity random failure:
```
(lldb) bt
* thread #113, name = 'region-worker::test_compaction_filter_blocked_by_clean_overlap_', stop reason = EXC_BAD_ACCESS (code=1, address=0xd)
  * frame #0: 0x00000001878058b0 libsystem_pthread.dylib`pthread_mutex_unlock + 12
    frame #1: 0x00000001051e145c failpoints-82c0c2b744de936d`_$LT$std..sync..poison..mutex..MutexGuard$LT$T$GT$$u20$as$u20$core..ops..drop..Drop$GT$::drop::h57c50fdae54a6bf6 + 56
    frame #2: 0x00000001051ab06c failpoints-82c0c2b744de936d`core::ptr::drop_in_place$LT$std..sync..poison..mutex..MutexGuard$LT$$LP$$RP$$GT$$GT$::hd863acc306193875 + 12
    frame #3: 0x00000001049e4098 failpoints-82c0c2b744de936d`core::ptr::drop_in_place$LT$tikv_util..range_latch..RangeLatchGuard$GT$::h89f35907d4c0e6cc + 108
    frame #4: 0x00000001049e4cfc failpoints-82c0c2b744de936d`core::ptr::drop_in_place$LT$core..option..Option$LT$tikv_util..range_latch..RangeLatchGuard$GT$$GT$::hac15ba0060781a6e + 60
    frame #5: 0x0000000104a0a96c failpoints-82c0c2b744de936d`engine_rocks::import::_$LT$impl$u20$engine_traits..import..ImportExt$u20$for$u20$engine_rocks..engine..RocksEngine$GT$::ingest_external_file_cf::h6a04738e2235dadf + 1092
    frame #6: 0x0000000104a0aee4 failpoints-82c0c2b744de936d`engine_rocks::misc::_$LT$impl$u20$engine_rocks..engine..RocksEngine$GT$::delete_all_in_range_cf_by_ingest::h5c8d3c1b5a66a4cb + 1140
    frame #7: 0x0000000104a0d0a4 failpoints-82c0c2b744de936d`engine_rocks::misc::_$LT$impl$u20$engine_traits..misc..MiscExt$u20$for$u20$engine_rocks..engine..RocksEngine$GT$::delete_ranges_cf::h39764cfc68ef1810 + 488
```

### What version of TiKV are you using?
v9.0.x

### What operating system and CPU are you using?
MacOS

### Steps to reproduce
Try running tests many times

### What did you expect?
Test passes.

### What did happened?
Test failure with memory fault

### PR DESCRIPTION
**Pull request by Dog-Du**
### What is changed and how it works?

Issue Number: Close #18756 

Close #18671

What's Changed:

```commit-message

fix dangling pointer.

make sure `_mutex_guard` released earlier than `Arc<Mutex<()>>`.

```

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [ ] Need to cherry-pick to the release branch

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note

```release-note
None
```

### CODE REVIEW

File: components/tikv_util/src/range_latch.rs [hunk 1]
```diff
@@ -126,15 +128,19 @@ pub struct RangeLatchGuard<'a> {
...
     /// Holds a reference to RangeLatch to release the latch when the guard is
     /// dropped.
     handle: &'a RangeLatch,
 }
 
 impl Drop for RangeLatchGuard<'_> {
     fn drop(&mut self) {
+        // Safety: we call `ManuallyDrop::drop` to drop the mutex guard once and only once.
+        // So `_mutex_guard` will be released earlier than the `Arc<Mutex<()>>`.
+        unsafe { ManuallyDrop::drop(&mut self._mutex_guard) };
```
Comment (v01dstar) [inline components/tikv_util/src/range_latch.rs:150]: The comment of `_mutex_guard` still implies it rely on declaration order for correctness, should we update it as well? BTW, can you add an explanation, in the PR description, why the "dropping order depends on declaration order" no longer holds?

Comment (Dog-Du) [reply components/tikv_util/src/range_latch.rs:150]: done

**Review by v01dstar — APPROVED** [review]

File: components/tikv_util/src/range_latch.rs [hunk 2]
```diff
@@ -96,15 +97,17 @@ impl RangeLatch {
 
                 // Now acquire the latch after releasing the write guard
                 let mutex_guard = mutex.lock().unwrap();
-                // Safety: `_mutex_guard` is declared before `handle` in `KeyHandleGuard`.
-                // So the mutex guard will be released earlier than the `Arc<KeyHandle>`.
+                // Safety: `transmute` just change the lifetime, do not change the type.
+                // `_mutex_guard` points to the `Mutex<()>`, we need to make sure it will be dropped before the `Arc<Mutex<()>>` and the `RangeLatch` while `drop`.
```
Comment (overvenus) [inline components/tikv_util/src/range_latch.rs]: Nit: please wrap the long line.

Comment (Dog-Du) [reply components/tikv_util/src/range_latch.rs]: ok~

**Comment by hhwyt** [comment]
LGTM. Good job!

**Review by hhwyt — APPROVED** [review]
