### PR TITLE
storage/txn: Add txn_status_cache module

### LINKED ISSUE #11187: Stale non-pessimistic lock may be incompatible with CDC and possibly affect data correctness
### What version of TiKV are you using?

v4.0.11
### Steps to reproduce

Pessimistic transactions may contain keys that don't need pessimistic locks. These locks are prewritten without any contraint checks.

So, there is a possible case. After a pessimistic transaction is committed, a non-pessimistic lock of the same transaction can  be also prewritten successfully. The lock TS of such a lock is smaller than the commit TS of the latest write record.

This breaks the assumption of the `DeltaScanner`. When a lock is encountered, it needs to find latest write record as the old value. It asserts that the commit TS of the record must be smaller than the lock TS. https://github.com/tikv/tikv/blob/v4.0.11/src/storage/mvcc/reader/scanner/mod.rs#L389-L392

This is probably the cause of the panic below.

### What did you expect?

CDC can still work in this case.

### What did happened?

TiKV panics.

```
stack backtrace:
   0: tikv_util::set_panic_hook::{{closure}}
             at components/tikv_util/src/lib.rs:481
   1: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:475
   2: rust_begin_unwind
             at src/libstd/panicking.rs:375
   3: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:326
   4: tikv::storage::mvcc::reader::scanner::seek_for_valid_write
             at /home/jenkins/agent/workspace/build_tikv_multi_branch_v4.0.11/tikv/<::std::macros::panic macros>:9
      tikv::storage::mvcc::reader::scanner::seek_for_valid_value
             at /home/jenkins/agent/workspace/build_tikv_multi_branch_v4.0.11/tikv/src/storage/mvcc/reader/scanner/mod.rs:418
   5: <tikv::storage::mvcc::reader::scanner::forward::DeltaEntryPolicy as tikv::storage::mvcc::reader::scanner::forward::ScanPolicy<S>>::handle_lock
             at /home/jenkins/agent/workspace/build_tikv_multi_branch_v4.0.11/tikv/src/storage/mvcc/reader/scanner/forward.rs:609
      tikv::storage::mvcc::reader::scanner::forward::ForwardScanner<S,P>::read_next
             at /home/jenkins/agent/workspace/build_tikv_multi_branch_v4.0.11/tikv/src/storage/mvcc/reader/scanner/forward.rs:258
      <tikv::storage::mvcc::reader::scanner::forward::ForwardScanner<S,P> as tikv::storage::txn::store::TxnEntryScanner>::next_entry
             at /home/jenkins/agent/workspace/build_tikv_multi_branch_v4.0.11/tikv/src/storage/mvcc/reader/scanner/forward.rs:744
      cdc::endpoint::Initializer::scan_batch
             at components/cdc/src/endpoint.rs:876
   6: cdc::endpoint::Endpoint<T>::on_register::{{closure}}
             at components/cdc/src/endpoint.rs:827
      <futures::future::then::Then<A,B,F> as futures::future::Future>::poll::{{closure}}
             at /rust/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/future/then.rs:33
      futures::future::chain::Chain<A,B,C>::poll
             at /rust/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/future/chain.rs:39
      <futures::future::then::Then<A,B,F> as futures::future::Future>::poll
             at /rust/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/future/then.rs:32
   7: <alloc::boxed::Box<F> as futures::future::Future>::poll
             at /rust/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/future/mod.rs:113
      futures::task_impl::Spawn<T>::poll_future_notify::{{closure}}
             at /rust/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/task_impl/mod.rs:329
      futures::task_impl::Spawn<T>::enter::{{closure}}
             at /rust/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/task_impl/mod.rs:399
      futures::task_impl::std::set
             at /rust/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/task_impl/std/mod.rs:83
      futures::task_impl::Spawn<T>::enter
             at /rust/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/task_impl/mod.rs:399
      futures::task_impl::Spawn<T>::poll_fn_notify
             at /rust/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/task_impl/mod.rs:291
      futures::task_impl::Spawn<T>::poll_future_notify
             at /rust/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/task_impl/mod.rs:329
      tokio_threadpool::task::Task::run::{{closure}}
             at /rust/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.16/src/task/mod.rs:145
      core::ops::function::FnOnce::call_once
             at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libcore/ops/function.rs:232
      <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/panic.rs:318
      std::panicking::try::do_call
             at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/panicking.rs:292
      std::panicking::try
             at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8//src/libpanic_unwind/lib.rs:78
      std::panic::catch_unwind
             at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/panic.rs:394
      tokio_threadpool::task::Task::run
             at /rust/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.16/src/task/mod.rs:130
      tokio_threadpool::worker::Worker::run_task2
             at /rust/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.16/src/worker/mod.rs:567
      tokio_threadpool::worker::Worker::run_task
             at /rust/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.16/src/worker/mod.rs:459
   8: tokio_threadpool::worker::Worker::try_run_owned_task
             at /rust/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.16/src/worker/mod.rs:390
      tokio_threadpool::worker::Worker::try_run_task
             at /rust/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.16/src/worker/mod.rs:297
      tokio_threadpool::worker::Worker::run
             at /rust/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.16/src/worker/mod.rs:241
   9: tokio_threadpool::worker::Worker::do_run::{{closure}}::{{closure}}
             at /rust/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.16/src/worker/mod.rs:129
      tokio_executor::global::with_default::{{closure}}
             at /rust/registry/src/github.com-1ecc6299db9ec823/tokio-executor-0.1.8/src/global.rs:209
      std::thread::local::LocalKey<T>::try_with
             at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/thread/local.rs:262
      std::thread::local::LocalKey<T>::with
             at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/thread/local.rs:239
      tokio_executor::global::with_default
             at /rust/registry/src/github.com-1ecc6299db9ec823/tokio-executor-0.1.8/src/global.rs:178
      tokio_threadpool::worker::Worker::do_run::{{closure}}
             at /rust/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.16/src/worker/mod.rs:125
      std::thread::local::LocalKey<T>::try_with
             at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/thread/local.rs:262
      std::thread::local::LocalKey<T>::with
             at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/thread/local.rs:239
      tokio_threadpool::worker::Worker::do_run
             at /rust/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.16/src/worker/mod.rs:116
      tokio_threadpool::pool::Pool::spawn_thread::{{closure}}
             at /rust/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.16/src/pool/mod.rs:345
      std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/sys_common/backtrace.rs:136
  10: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}
             at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/thread/mod.rs:469
      <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/panic.rs:318
      std::panicking::try::do_call
             at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/panicking.rs:292
      std::panicking::try
             at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8//src/libpanic_unwind/lib.rs:78
      std::panic::catch_unwind
             at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/panic.rs:394
      std::thread::Builder::spawn_unchecked::{{closure}}
             at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/thread/mod.rs:468
      core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libcore/ops/function.rs:232
  11: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/liballoc/boxed.rs:1022
  12: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/liballoc/boxed.rs:1022
      std::sys_common::thread::start_thread
             at src/libstd/sys_common/thread.rs:13
      std::sys::unix::thread::Thread::new::thread_start
             at src/libstd/sys/unix/thread.rs:80
  13: start_thread
  14: __clone
```

### PR DESCRIPTION
**Pull request by MyonKeminta**
### What is changed and how it works?

Issue Number: Ref #11187

What's Changed:

Most part of this PR is test and benchmark code.

```commit-message
This PR adds a module named txn_status_cache. It provides the type `TxnStatusCache`, which will be then put into scheduler to cache start_ts->commit_ts information of recently-committed transactions. This is part of fixing issue #11187 and will also be used for possible future optimizations such as checking txn status locally.
```

### Related changes

- Requires:
  - https://github.com/tikv/tikv/pull/15747

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by zyguan — APPROVED** [review]

File: src/storage/txn/txn_status_cache.rs [hunk 1]
```diff
@@ -0,0 +1,962 @@
...
+    /// field `simulated_system_time`.
+    #[inline]
+    #[cfg(test)]
+    fn now(&self) -> SystemTime {
+        // Always get the system time to simulate the latency.
+        let now = SystemTime::now();
+        if let Some(pseudo_system_time) = &self.simulated_system_time {
+            UNIX_EPOCH
+                + std::time::Duration::from_millis(
+                    pseudo_system_time.load(std::sync::atomic::Ordering::Acquire),
```
Comment (cfzjywxk) [inline src/storage/txn/txn_status_cache.rs:177]: It seems `Relaxed` is enough here for the atomic opereation? Though it would not be used in product.

File: src/storage/txn/txn_status_cache.rs [hunk 2]
```diff
@@ -0,0 +1,962 @@
...
+    /// multiple items is being inserted.
+    ///
+    /// If the transaction's information is already in the cache, it will
+    /// **NOT** be promoted to the most-recent place of the internal LRU.
+    pub fn insert(&self, start_ts: TimeStamp, commit_ts: TimeStamp, now: SystemTime) {
+        if !self.is_enabled {
+            return;
+        }
+
+        let insert_time = now.duration_since(UNIX_EPOCH).unwrap().as_millis() as u64;
```
Comment (cfzjywxk) [inline src/storage/txn/txn_status_cache.rs:333]: How much is its overhead compared with the `now_coarse` like functions?

File: src/storage/txn/txn_status_cache.rs [hunk 3]
```diff
@@ -0,0 +1,962 @@
...
+            .add(size as i64 - previous_size as i64);
+        SCHED_TXN_STATUS_CACHE_SIZE
+            .allocated
+            .add(allocated as i64 - previous_allocated as i64);
+    }
+
+    /// Try to get an item from the cache, without promoting the item (if
+    /// exists) to the most recent place.
+    pub fn get_no_promote(&self, start_ts: TimeStamp) -> Option<TimeStamp> {
+        if !self.is_enabled {
```
Comment (ekexium) [inline src/storage/txn/txn_status_cache.rs:359]: Returning None could mean either key does not exist or cache is disabled. I'm wondering the meaning of is_enabled here. Where is it supposed to be used?

File: src/storage/txn/txn_status_cache.rs (hunk 1 above)
Comment (MyonKeminta) [reply src/storage/txn/txn_status_cache.rs:177]: I'm afraid that `Relaxed` would cause strange instruction reordering here. I want to ensure that later accesses will always get the latest value that was just updated.

File: src/storage/txn/txn_status_cache.rs (hunk 3 above)
Comment (MyonKeminta) [reply src/storage/txn/txn_status_cache.rs:359]: Disabling means the capacity is 0, so nothing would be inserted here. So returning `None` when getting looks semantically correct, then the caller can behave like encountering a cache miss.
I think currently it's not necessary to distinguish being disabled or nothing found. After all, the cache can't guarantee to keep the not-expired entries *perfectly*.

I added this explicit flag to mark it disabled, because the internal `LruCache` doesn't support 0 capacity.

File: src/storage/txn/txn_status_cache.rs (hunk 2 above)
Comment (MyonKeminta) [reply src/storage/txn/txn_status_cache.rs:333]: This line is actually to calculate the integer timestamp from the `SystemTime` type, and it didn't acquire any time from system. The variable `now` is passed from outside the function.
As for the time cost, I have such benchmark results in my environment: (the last one `bench_system_time_since_unix_epoch` is the calculation in the line you commented)

```
bench_instant_now                               ... bench:          19 ns/iter (+/- 1)
bench_instant_now_coarse                        ... bench:           9 ns/iter (+/- 0)
bench_system_time_now                           ... bench:          19 ns/iter (+/- 0)
bench_system_time_since_unix_epoch              ... bench:           5 ns/iter (+/- 0)
```

File: src/storage/txn/txn_status_cache.rs (hunk 1 above)
Comment (cfzjywxk) [reply src/storage/txn/txn_status_cache.rs:176]: It seems the atomic variable is only set in the test, a little bit weird the interfaces does not use both `acquire` and `release` together. It's just a matter of personal habit, and it's okay. I just asked casually.

File: src/storage/txn/txn_status_cache.rs (hunk 2 above)
Comment (cfzjywxk) [reply src/storage/txn/txn_status_cache.rs:332]: Got, it looks good not to acuiqre system time.

File: src/storage/txn/txn_status_cache.rs (hunk 1 above)
Comment (MyonKeminta) [reply src/storage/txn/txn_status_cache.rs:176]: 🤔Release is used when setting it in the test code below

File: src/storage/txn/txn_status_cache.rs (hunk 2 above)
Comment (MyonKeminta) [reply src/storage/txn/txn_status_cache.rs:332]: Sorry but you may need to notice that the `should_evict` function called by the `insert` function  still need to acquire the system time, and I failed to avoid it without making the code too ugly...

**Review by ekexium — APPROVED** [review]

**Comment by MyonKeminta** [comment]
@cfzjywxk @ekexium PTAL when you have time. Thanks!

**Review by cfzjywxk — APPROVED** [review]
