### PR TITLE
cdc: remove assertion on the seek_for_valid_write

### LINKED ISSUE #19404: cdc assertion failed on the seek_for_valid_write
### What version of TiKV are you using?

v6.5
### Steps to reproduce

ref https://github.com/tikv/tikv/issues/11187
### What did you expect?
None
### What did happened?
https://github.com/tikv/tikv/issues/11187#issuecomment-962986671
If there is both data and index range in a region, CDC scanned the index range by mistake, causing panic

### PR DESCRIPTION
**Pull request by wk989898**
### What is changed and how it works?

Issue Number: ref https://github.com/tikv/tikv/issues/11187 close #19404

What's Changed:

```commit-message
Use warn instead of assertion on the seek_for_valid_write.
https://github.com/tikv/tikv/pull/16252 should fix the panic by specifying ranges, but it only fixes versions above v8.0.
```

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [x] Need to cherry-pick to the release branch

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note

```release-note
remove assertion on the non-pessimistic lock to avoid TiKV panic
```

### CODE REVIEW

File: src/storage/mvcc/reader/scanner/mod.rs [hunk 1]
```diff
@@ -496,10 +496,20 @@ where
...
+                // a non-pessimistic lock of the same transaction can be also prewritten
+                // successfully. The lock TS of such a lock is smaller than the commit TS of the
+                // latest write record.
+                // See https://github.com/tikv/tikv/issues/11187
+                let latest_write_ts = Key::decode_ts_from(write_cursor.key(&mut statistics.write))?;
+                if after_ts < latest_write_ts {
+                    warn!("found the user key of which ts > after_ts. There may be exist an unexpected stale non-pessimistic lock";
+                        "user_key" => %user_key,
+                        "after_ts" => after_ts,
+                        "latest_write_ts" => latest_write_ts,
```
Comment (MyonKeminta) [inline src/storage/mvcc/reader/scanner/mod.rs]: This is the commit_ts of the write record. Consider also printing its  start ts, which can be retrived by `write_ref.start_ts`.

File: src/storage/mvcc/reader/scanner/mod.rs [hunk 2]
```diff
@@ -496,10 +496,20 @@ where
...
-                    Key::decode_ts_from(write_cursor.key(&mut statistics.write))?
-                );
+                // After a pessimistic transaction is committed,
+                // a non-pessimistic lock of the same transaction can be also prewritten
+                // successfully. The lock TS of such a lock is smaller than the commit TS of the
+                // latest write record.
+                // See https://github.com/tikv/tikv/issues/11187
+                let latest_write_ts = Key::decode_ts_from(write_cursor.key(&mut statistics.write))?;
+                if after_ts < latest_write_ts {
+                    warn!("found the user key of which ts > after_ts. There may be exist an unexpected stale non-pessimistic lock";
```
Comment (MyonKeminta) [inline src/storage/mvcc/reader/scanner/mod.rs]:
```suggestion
                    warn!("found the user key of which ts > after_ts. There may exist an unexpected stale non-pessimistic lock";
```

**Review by 3AceShowHand — APPROVED** [review]

**Comment by 3AceShowHand** [comment]
I think may be we can skip this lock, if it's lock_ts smaller than the commit-ts.

**Review by MyonKeminta — APPROVED** [review]
