### PR TITLE
raftstore: reset region approximate size/keys stats when it becomes leader

### LINKED ISSUE #19180: Region approximate_size/keys may be incorrect after leader transfer
## Bug Report

https://github.com/tikv/tikv/blob/04df27b806a8801d3c94ba45dc9b54138d1c2d78/components/raftstore/src/store/fsm/peer.rs#L2262-L2275

After a peer becoming leader, it will report a heartbeat to pd instantly. But it just reuse the old approximate_size/keys stats. 

When there are many leader transfer operations in a short time, e.g. evict leader, these outdates stats can cause abrupt store size change in pd and trigges unnecessary region balance.

### PR DESCRIPTION
**Pull request by glorv**
### What is changed and how it works?

Issue Number: Close #19180

What's Changed:

```commit-message
Reset region's approximate size/keys stats when peer becomes leader. This can avoid peer report outdated stats to pd and caused unnecessary balance scheduling.
```

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [ ] Need to cherry-pick to the release branch

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note

```release-note
Fix the bug that pd heartbeat may report wrong region size/keys statistics data after leader change.
```

### CODE REVIEW

File: tests/integrations/raftstore/test_region_heartbeat.rs [hunk 1]
```diff
@@ -201,3 +201,69 @@ fn test_region_heartbeat_term() {
...
+    cluster.must_transfer_leader(region_id, new_peer(1, 1));
+    sleep_ms(100);
+    // the first region heartbeat after leader transfer will report with 0 value.
+    // Real pd with ignore this 0 value while the current test pd-client just keep
+    // this 0 value.
+    let size = cluster
+        .pd_client
+        .get_region_approximate_size(region_id)
+        .unwrap_or_default();
+    assert_eq!(size, 0);
```
Comment (hbisheng) [inline tests/integrations/raftstore/test_region_heartbeat.rs]: It's technically possible to let the test pd-client ignore the 0 value as well, right? If we do that, we will be able to assert `size >= 2000` in the end. But we will need to ensure that the new leader has uploaded its heartbeat (possibily using a failpoint).

Comment (hhwyt) [reply tests/integrations/raftstore/test_region_heartbeat.rs]: +1. we can add an assertion for the final state (size >= 2000).

Comment (glorv) [reply tests/integrations/raftstore/test_region_heartbeat.rs]: Done.

**Comment by glorv** [comment]
@hbisheng PTAL again, thanks
