### PR TITLE
tests: stable test_stale_read_during_merging

### LINKED ISSUE #4246: cases::test_stale_read::test_stale_read_during_merging failed
## Bug Report

https://internal.pingcap.net/idc-jenkins/blue/rest/organizations/jenkins/pipelines/tikv_ghpr_test/runs/1607/nodes/109/steps/587/log/?start=0

### PR DESCRIPTION
**Pull request by overvenus**
## What have you changed? (mandatory)

Stable test_stale_read_during_merging by sleep an election timeout, so The new leader needs enough time to gether all followers progress, in cause the merge request is reject by log gap too large (min_progress == 0).

## What are the type of the changes? (mandatory)

- Misc (other changes)

## How has this PR been tested? (mandatory)

Unit tests.

## Does this PR affect documentation (docs) update? (mandatory)

No.

## Does this PR affect tidb-ansible update? (mandatory)

No.

## Refer to a related PR or issue link (optional)

Fixes #4246

### CODE REVIEW

File: tests/failpoints/cases/test_stale_read.rs [hunk 1]
```diff
@@ -273,11 +273,16 @@ fn test_stale_read_during_merging() {
     cluster.must_transfer_leader(region1000.get_id(), leader1000.clone());
     assert_ne!(leader1.get_store_id(), leader1000.get_store_id());
 
-    //             Merge into
-    // region1000 ------------> region1,
+    // Sleeps an election timeout. The new leader needs enough time to gether
```
Comment (Connor1996) [inline tests/failpoints/cases/test_stale_read.rs]:
```suggestion
    // Sleeps an election timeout. The new leader needs enough time to gather
```
