### PR TITLE
coprocessor: not return rows when there is no input for simple aggregation

### LINKED ISSUE #11735: wrong  `firstrow` aggregation result when there are regions returning empty result
## Bug Report

This is an alias for https://github.com/pingcap/tidb/issues/30923

### PR DESCRIPTION
**Pull request by windtalker**
### What is changed and how it works?

Close #11735, Close pingcap/tidb#30923 

What's Changed:
For `SimpleAggregation` does not return row if there is no input rows
### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- PR to update `pingcap/tidb-ansible`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Manual test (add detailed scripts or steps below)

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

```release-note
Fix wrong `any_value` result when there are regions returning empty result 
```

### CODE REVIEW

**Review by sticnarf — APPROVED** [review]
Aggregation implementations on TiKV are always a bit different from TiDB, for example, the output of `avg()`. I think it's OK to assume at this time that simple aggr will not be the final result and return zero row.

File: components/tidb_query_executors/src/simple_aggr_executor.rs [hunk 1]
```diff
@@ -203,7 +215,9 @@ impl<Src: BatchExecutor> AggregationExecutorImpl<Src> for SimpleAggregationImpl
         mut iteratee: impl FnMut(&mut Entities<Src>, &[Box<dyn AggrFunctionState>]) -> Result<()>,
     ) -> Result<Vec<LazyBatchColumn>> {
         assert!(src_is_drained);
-        iteratee(entities, &self.states)?;
+        if self.has_input_rows {
+            iteratee(entities, &self.states)?;
+        }
```
Comment (breeswish) [inline components/tidb_query_executors/src/simple_aggr_executor.rs:220]: Maybe you also need to change L207

**Review by breeswish — COMMENTED** [review]
BTW seems that TiKV is keeping this behavior since v2.0.0, so this might be a bug exists for a lot of versions. Better to check v3.0 and v2.1 as well.

File: components/tidb_query_executors/src/simple_aggr_executor.rs (hunk 1 above)
Comment (windtalker) [reply components/tidb_query_executors/src/simple_aggr_executor.rs:220]: This [comment](https://github.com/tikv/tikv/blob/a7e89a85bb5661f6ea211b319ea6253341a53197/components/tidb_query_executors/src/util/aggr_executor.rs#L65) indicates that `group_len` can be inaccurate since it is just a hint. But I've updated L207 as you suggested.

**Comment by windtalker** [comment]
> pingcap/tidb#30923

TiDB v3.1.2/v3.0.20/v2.1.19, all of them have the same issue.

**Comment by windtalker** [comment]
> BTW seems that TiKV is keeping this behavior since v2.0.0, so this might be a bug exists for a lot of versions. Better to check v3.0 and v2.1 as well.

Tested in TiDB v3.1.2/v3.0.20/v2.1.19, all of them have the same issue.

**Review by breeswish — APPROVED** [review]

**Comment by windtalker** [comment]
@breeswish can you help merge it?
