### PR TITLE
copr:  fix the wrong arguments type of json_unquote

### LINKED ISSUE #10176: json_unquote: Expect `Json`, received `Bytes`
### What version of TiKV are you using?
5.0

### What operating system and CPU are you using?
AMD Ryzen 5 PRO 4650U with Radeon Graphics

Ubuntu 18.04

### Steps to reproduce
This is a **coprocessor bug**. And should enable push down of `json_unquote`, which is not by default. But still need to fix it.

    drop table if exists t1;
    create table t1(c1 varchar(100));
    insert into t1 values('abc'), ('"abc"');
    select c1 from t1 where json_unquote(c1) = 'abc';

### What did you expect?
    mysql>     select c1 from t1 where json_unquote(c1) = 'abc';
    +-------+
    | c1    |
    +-------+
    | abc   |
    | "abc" |
    +-------+
    2 rows in set (0.00 sec)
### What did happened?

    mysql> select c1 from t1 where json_unquote(c1) = 'abc';
    ERROR 1105 (HY000): other error: [components/tidb_query_expr/src/types/expr_builder.rs:295]: Invalid json_unquote (sig = JsonUnquoteSig) signature: Evaluate error: [components/tidb_query_expr/src/types/function.rs:272]: Expect `Json`, received `Bytes`
    m

### PR DESCRIPTION
**Pull request by guo-shaoge**
Signed-off-by: guo-shaoge <shaoge1994@163.com>

### What problem does this PR solve?

Issue Number: close #10176 

Problem Summary: `json_unquote` implementation use `JsonRef` as argument type, which is not correct. It causes the following SQL report errors.

    drop table if exists t1;
    create table t1(c1 varchar(100));
    insert into t1 values('abc'), ('"abc"');
    select c1 from t1 where json_unquote(c1) = 'abc';

    mysql> select c1 from t1 where json_unquote(c1) = 'abc';
    ERROR 1105 (HY000): other error: [components/tidb_query_expr/src/types/expr_builder.rs:295]: Invalid json_unquote (sig = JsonUnquoteSig) signature: Evaluate error: [components/tidb_query_expr/src/types/function.rs:272]: Expect `Json`, received `Bytes`
    m

### What is changed and how it works?
What's Changed: change argument type from `JsonRef` to `BytesRef`.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

### Release note 
- copr: fix the wrong arguments type of json_unquote

### CODE REVIEW

**Comment by guo-shaoge** [comment]
@skyzh PTAL ~

File: components/tidb_query_expr/src/impl_json.rs [hunk 1]
```diff
@@ -226,6 +227,16 @@ fn valid_paths(expr: &tipb::Expr) -> Result<()> {
     Ok(())
 }
 
+fn unquote_string(s: &str) -> Result<String> {
```
Comment (skyzh) [inline components/tidb_query_expr/src/impl_json.rs:230]: Why do we add a dedicated function to do this? Can’t we reuse the original logic?

File: components/tidb_query_expr/src/impl_json.rs [hunk 2]
```diff
@@ -204,9 +204,10 @@ fn quote(bytes: BytesRef) -> Result<Option<Bytes>> {
 
 #[rpn_fn(nullable)]
 #[inline]
-fn json_unquote(arg: Option<JsonRef>) -> Result<Option<Bytes>> {
+fn json_unquote(arg: Option<BytesRef>) -> Result<Option<Bytes>> {
```
Comment (skyzh) [inline components/tidb_query_expr/src/impl_json.rs:207]: You may use non-nullable variant for this. Please remove nullable in rpn_fn macro and remove Option in both args and result, so that copr framework could automatically handle the case for null internally with better efficiency.

File: components/tidb_query_expr/src/impl_json.rs [hunk 3]
```diff
@@ -226,6 +227,16 @@ fn valid_paths(expr: &tipb::Expr) -> Result<()> {
     Ok(())
 }
 
+fn unquote_string(s: &str) -> Result<String> {
+    let first_char = s.chars().next();
+    let last_char = s.chars().nth(s.len() - 1);
```
Comment (skyzh) [inline components/tidb_query_expr/src/impl_json.rs:232]: This seems to be not correct. len returns how many bytes are there in str, while chars is an iterator on UTF-8 characters. Please also considering adding test cases on CJK characters. After all, I suggest reusing previous logic instead of extracting quotes by ourselves.

File: components/tidb_query_expr/src/impl_json.rs (hunk 1 above)
Comment (guo-shaoge) [reply components/tidb_query_expr/src/impl_json.rs:230]: The original `unquote_json` doesn't remove first and last double quote, which is not compatible with MySQL.

    mysql> select json_unquote('"abc"');
    +-----------------------+
    | json_unquote('"abc"') |
    +-----------------------+
    | abc                   |
    +-----------------------+

So I add this one to remove.

File: components/tidb_query_expr/src/impl_json.rs (hunk 3 above)
Comment (guo-shaoge) [reply components/tidb_query_expr/src/impl_json.rs:232]: Yeah. I didn't notice the sematics of `len()`.

File: components/tidb_query_expr/src/impl_json.rs (hunk 2 above)
Comment (guo-shaoge) [reply components/tidb_query_expr/src/impl_json.rs:207]: Looks like all others functions in this file all use `nullable`. Maybe we open a new PR to fix all of them.

Comment (skyzh) [reply components/tidb_query_expr/src/impl_json.rs:207]: As far as I could see, most functions in this file have non-nullable support, except for those accepting ScalarVlaueRef as parameter, which do not support non-nullable. Therefore, I suggest make this change in this PR.

**Comment by skyzh** [comment]
Also I found this logic might be inconsistent with MySQL if the JSON is invalid. Consider this case:

```
SELECT  json_unquote('""a""');
```

where `""a""` is an invalid JSON object, and `json_unquote` might yield `a` after all. I think this might be a bug that should be fixed in both TiDB and TiKV in the future.

File: components/tidb_query_datatype/src/codec/mysql/json/mod.rs [hunk 4]
```diff
@@ -74,7 +74,7 @@ mod json_merge;
 mod json_modify;
 mod json_remove;
 mod json_type;
-mod json_unquote;
+pub mod json_unquote;
```
Comment (Xuanwo) [inline components/tidb_query_datatype/src/codec/mysql/json/mod.rs:77]: Why do we need to make `json_unquote` pub here?

File: components/tidb_query_expr/src/impl_json.rs (hunk 2 above)
Comment (Xuanwo) [reply components/tidb_query_expr/src/impl_json.rs:207]: I agreed with @skyzh.

File: components/tidb_query_datatype/src/codec/mysql/json/mod.rs (hunk 4 above)
Comment (guo-shaoge) [reply components/tidb_query_datatype/src/codec/mysql/json/mod.rs:77]: So we can use json_unquote::unquote_string in tidb_query_expr.

File: components/tidb_query_expr/src/impl_json.rs (hunk 2 above)
Comment (guo-shaoge) [reply components/tidb_query_expr/src/impl_json.rs]: done~

**Review by skyzh — APPROVED** [review]

**Review by Xuanwo — APPROVED** [review]

File: components/tidb_query_expr/src/impl_json.rs [hunk 5]
```diff
@@ -202,12 +202,11 @@ fn quote(bytes: BytesRef) -> Result<Option<Bytes>> {
     Ok(Some(result))
 }
 
-#[rpn_fn(nullable)]
+#[rpn_fn()]
```
Comment (Xuanwo) [inline components/tidb_query_expr/src/impl_json.rs:205]:
```suggestion
#[rpn_fn]
```

Comment (guo-shaoge) [reply components/tidb_query_expr/src/impl_json.rs:205]: done
