### PR TITLE
scanner/forward: move to next key if accesses a lock with delete type

### LINKED ISSUE #11541: Unexpected panic when scan_next
### What version of TiKV are you using?

master (c04fd41029c28f54e934830f63424f0aa34e2654)

### What operating system and CPU are you using?

k8s

### Steps to reproduce

run tipocket bank2 or ledger on master branch.

### What did you expect?

tikv run normally during the test

### What did happened?

tikv panicked
```
   0: tikv_util::set_panic_hook::{{closure}}
             at home/jenkins/agent/workspace/build_tikv_multi_branch_master/tikv/components/tikv_util/src/lib.rs:464:18
   1: std::panicking::rust_panic_with_hook
             at rustc/2faabf579323f5252329264cc53ba9ff803429a3/library/std/src/panicking.rs:626:17
   2: std::panicking::begin_panic_handler::{{closure}}
             at rustc/2faabf579323f5252329264cc53ba9ff803429a3/library/std/src/panicking.rs:517:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at rustc/2faabf579323f5252329264cc53ba9ff803429a3/library/std/src/sys_common/backtrace.rs:141:18
   4: rust_begin_unwind
             at rustc/2faabf579323f5252329264cc53ba9ff803429a3/library/std/src/panicking.rs:515:5
   5: core::panicking::panic_fmt
             at rustc/2faabf579323f5252329264cc53ba9ff803429a3/library/core/src/panicking.rs:92:14
   6: core::panicking::panic
             at rustc/2faabf579323f5252329264cc53ba9ff803429a3/library/core/src/panicking.rs:50:5
   7: tikv::storage::mvcc::reader::scanner::forward::ForwardScanner<S,P>::move_write_cursor_to_ts
             at home/jenkins/agent/workspace/build_tikv_multi_branch_master/tikv/src/storage/mvcc/reader/scanner/forward.rs:298:9
      tikv::storage::mvcc::reader::scanner::forward::ForwardScanner<S,P>::read_next
             at home/jenkins/agent/workspace/build_tikv_multi_branch_master/tikv/src/storage/mvcc/reader/scanner/forward.rs:276:43
      <tikv::storage::mvcc::reader::scanner::Scanner<S> as tikv::storage::txn::store::Scanner>::next
             at home/jenkins/agent/workspace/build_tikv_multi_branch_master/tikv/src/storage/mvcc/reader/scanner/mod.rs:203:45
   8: <tikv::coprocessor::dag::storage_impl::TiKVStorage<S> as tidb_query_common::storage::Storage>::scan_next
             at home/jenkins/agent/workspace/build_tikv_multi_branch_master/tikv/src/coprocessor/dag/storage_impl.rs:72:18
   9: tidb_query_common::storage::scanner::RangesScanner<T>::next
             at home/jenkins/agent/workspace/build_tikv_multi_branch_master/tikv/components/tidb_query_common/src/storage/scanner.rs:88:21
  10: tidb_query_executors::util::scan_executor::ScanExecutor<S,I>::fill_column_vec
             at home/jenkins/agent/workspace/build_tikv_multi_branch_master/tikv/components/tidb_query_executors/src/util/scan_executor.rs:104:28
      <tidb_query_executors::util::scan_executor::ScanExecutor<S,I> as tidb_query_executors::interface::BatchExecutor>::next_batch
             at home/jenkins/agent/workspace/build_tikv_multi_branch_master/tikv/components/tidb_query_executors/src/util/scan_executor.rs:171:26
      <tidb_query_executors::index_scan_executor::BatchIndexScanExecutor<S> as tidb_query_executors::interface::BatchExecutor>::next_batch
             at home/jenkins/agent/workspace/build_tikv_multi_branch_master/tikv/components/tidb_query_executors/src/index_scan_executor.rs:144:9
      <tidb_query_common::execute_stats::WithSummaryCollector<C,T> as tidb_query_executors::interface::BatchExecutor>::next_batch
             at home/jenkins/agent/workspace/build_tikv_multi_branch_master/tikv/components/tidb_query_executors/src/interface.rs:108:22
  11: <alloc::boxed::Box<T> as tidb_query_executors::interface::BatchExecutor>::next_batch
             at home/jenkins/agent/workspace/build_tikv_multi_branch_master/tikv/components/tidb_query_executors/src/interface.rs:77:9
      tidb_query_executors::runner::BatchExecutorsRunner<SS>::internal_handle_request
             at home/jenkins/agent/workspace/build_tikv_multi_branch_master/tikv/components/tidb_query_executors/src/runner.rs:549:26
  12: tidb_query_executors::runner::BatchExecutorsRunner<SS>::handle_request::{{closure}}
             at home/jenkins/agent/workspace/build_tikv_multi_branch_master/tikv/components/tidb_query_executors/src/runner.rs:426:41
      <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at rustc/2faabf579323f5252329264cc53ba9ff803429a3/library/core/src/future/mod.rs:80:19
      <tikv::coprocessor::dag::BatchDAGHandler as tikv::coprocessor::RequestHandler>::handle_request::__handle_request::{{closure}}
             at home/jenkins/agent/workspace/build_tikv_multi_branch_master/tikv/src/coprocessor/dag/mod.rs:111:22
      <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at rustc/2faabf579323f5252329264cc53ba9ff803429a3/library/core/src/future/mod.rs:80:19
  13: <core::pin::Pin<P> as core::future::future::Future>::poll
             at rustc/2faabf579323f5252329264cc53ba9ff803429a3/library/core/src/future/future.rs:119:9
      <tikv::coprocessor::interceptors::deadline::DeadlineChecker<F> as core::future::future::Future>::poll
             at home/jenkins/agent/workspace/build_tikv_multi_branch_master/tikv/src/coprocessor/interceptors/deadline.rs:34:9
      <tikv::coprocessor::interceptors::tracker::Tracker<F> as core::future::future::Future>::poll
             at home/jenkins/agent/workspace/build_tikv_multi_branch_master/tikv/src/coprocessor/interceptors/tracker.rs:49:19
  14: <tikv::coprocessor::interceptors::concurrency_limiter::ConcurrencyLimiter<PF,F> as core::future::future::Future>::poll
             at home/jenkins/agent/workspace/build_tikv_multi_branch_master/tikv/src/coprocessor/interceptors/concurrency_limiter.rs:111:15
  15: tikv::coprocessor::endpoint::Endpoint<E>::handle_unary_request_impl::{{closure}}
             at home/jenkins/agent/workspace/build_tikv_multi_branch_master/tikv/src/coprocessor/endpoint.rs:392:13
      <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at rustc/2faabf579323f5252329264cc53ba9ff803429a3/library/core/src/future/mod.rs:80:19
      <resource_metering::InTags<T> as core::future::future::Future>::poll
             at home/jenkins/agent/workspace/build_tikv_multi_branch_master/tikv/components/resource_metering/src/lib.rs:159:9
      tikv::read_pool::ReadPoolHandle::spawn_handle::{{closure}}
             at home/jenkins/agent/workspace/build_tikv_multi_branch_master/tikv/src/read_pool.rs:145:27
      <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at rustc/2faabf579323f5252329264cc53ba9ff803429a3/library/core/src/future/mod.rs:80:19
  16: tikv::read_pool::ReadPoolHandle::spawn::{{closure}}
             at home/jenkins/agent/workspace/build_tikv_multi_branch_master/tikv/src/read_pool.rs:121:25
      <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at rustc/2faabf579323f5252329264cc53ba9ff803429a3/library/core/src/future/mod.rs:80:19
      yatp::task::future::RawTask<F>::poll
             at rust/git/checkouts/yatp-e704b73c3ee279b6/d564d19/src/task/future.rs:59:9
  17: yatp::task::future::TaskCell::poll
             at rust/git/checkouts/yatp-e704b73c3ee279b6/d564d19/src/task/future.rs:103:9
      <yatp::task::future::Runner as yatp::pool::runner::Runner>::handle
             at rust/git/checkouts/yatp-e704b73c3ee279b6/d564d19/src/task/future.rs:387:20
  18: <tikv_util::yatp_pool::YatpPoolRunner<T> as yatp::pool::runner::Runner>::handle
             at home/jenkins/agent/workspace/build_tikv_multi_branch_master/tikv/components/tikv_util/src/yatp_pool/mod.rs:104:24
      <yatp::queue::multilevel::MultilevelRunner<R> as yatp::pool::runner::Runner>::handle
             at rust/git/checkouts/yatp-e704b73c3ee279b6/d564d19/src/queue/multilevel.rs:245:19
      yatp::pool::worker::WorkerThread<T,R>::run
             at rust/git/checkouts/yatp-e704b73c3ee279b6/d564d19/src/pool/worker.rs:48:13
      yatp::pool::builder::LazyBuilder<T>::build::{{closure}}
             at rust/git/checkouts/yatp-e704b73c3ee279b6/d564d19/src/pool/builder.rs:91:25
      std::sys_common::backtrace::__rust_begin_short_backtrace
             at rustc/2faabf579323f5252329264cc53ba9ff803429a3/library/std/src/sys_common/backtrace.rs:125:18
  19: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}
             at rustc/2faabf579323f5252329264cc53ba9ff803429a3/library/std/src/thread/mod.rs:476:17
      <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at rustc/2faabf579323f5252329264cc53ba9ff803429a3/library/std/src/panic.rs:347:9
      std::panicking::try::do_call
             at rustc/2faabf579323f5252329264cc53ba9ff803429a3/library/std/src/panicking.rs:401:40
      std::panicking::try
             at rustc/2faabf579323f5252329264cc53ba9ff803429a3/library/std/src/panicking.rs:365:19
      std::panic::catch_unwind
             at rustc/2faabf579323f5252329264cc53ba9ff803429a3/library/std/src/panic.rs:434:14
      std::thread::Builder::spawn_unchecked::{{closure}}
             at rustc/2faabf579323f5252329264cc53ba9ff803429a3/library/std/src/thread/mod.rs:475:30
      core::ops::function::FnOnce::call_once{{vtable.shim}}
             at rustc/2faabf579323f5252329264cc53ba9ff803429a3/library/core/src/ops/function.rs:227:5
  20: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at rustc/2faabf579323f5252329264cc53ba9ff803429a3/library/alloc/src/boxed.rs:1572:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at rustc/2faabf579323f5252329264cc53ba9ff803429a3/library/alloc/src/boxed.rs:1572:9
      std::sys::unix::thread::Thread::new::thread_start
             at rustc/2faabf579323f5252329264cc53ba9ff803429a3/library/std/src/sys/unix/thread.rs:91:17
  21: <unknown>
  22: clone
```

### PR DESCRIPTION
**Pull request by youjiali1995**
Signed-off-by: youjiali1995 <zlwgx1023@gmail.com>

### What is changed and how it works?

Close #11541

What's Changed:

Forward scanner panics because it accesses a lock with delete type and the write cursor has moved to the next user key, but the forward scanner still handles the current write in `read_next()`, so move to next user key in this case to resolve it.

### Check List 

Tests 

- Unit test

Side effects

### Release note 

```release-note
None
```

### CODE REVIEW

File: src/storage/mvcc/reader/scanner/forward.rs [hunk 1]
```diff
@@ -270,6 +271,7 @@ impl<S: Snapshot, P: ScanPolicy<S>> ForwardScanner<S, P> {
                         return Ok(Some(output));
                     }
                     HandleRes::Skip(key) => key,
+                    HandleRes::MoveToNext(_) => continue,
```
Comment (cfzjywxk) [inline src/storage/mvcc/reader/scanner/forward.rs:274]: Do we need to handle the move next result for backford scanner?

**Review by cfzjywxk — APPROVED** [review]

File: src/storage/mvcc/reader/scanner/forward.rs (hunk 1 above)
Comment (youjiali1995) [reply src/storage/mvcc/reader/scanner/forward.rs:274]: No. The implementation of backward scanner is different from forward scanner which abstracts a trait for different scan policies. Backward scanner handles it and `test_scan_access_locks` covers it.

https://github.com/tikv/tikv/blob/c04fd41029c28f54e934830f63424f0aa34e2654/src/storage/mvcc/reader/scanner/backward.rs#L177

File: src/storage/mvcc/reader/scanner/forward.rs [hunk 2]
```diff
@@ -56,6 +56,7 @@ pub trait ScanPolicy<S: Snapshot> {
 pub enum HandleRes<T> {
     Return(T),
     Skip(Key),
+    MoveToNext(Key),
```
Comment (sticnarf) [inline src/storage/mvcc/reader/scanner/forward.rs:59]: Why not remove the `Key` inside because it seems unused?

**Review by sticnarf — COMMENTED** [review]
The rest lgtm

**Review by sticnarf — APPROVED** [review]
