### PR TITLE
encryption: fix key rotation issues

### LINKED ISSUE #7839: master_key::mem::tests::test_mem_backend_authenticate failed
master_key::mem::tests::test_mem_backend_authenticate

 Latest failed builds: 
https://internal.pingcap.net/idc-jenkins/job/tikv_ghpr_test/22711/consoleFull

### PR DESCRIPTION
**Pull request by yiwu-arbug**
### What problem does this PR solve?

Problem Summary: Fixes several issues with encryption key rotation:
1. #7410 changed to use GCM mode to encrypt key dictionary, and since then decrypting key dictionary can fail. The failure should be treated as `WrongMasterKey` for key rotation fallback to work.
2. When rotating a file type master key (the `previous-master-key`) with a KMS type master key (the current `master-key`), key manager first try to use the KMS key to decrypt key dictionary. It will fail since the KMS vendor field is missing in file meta. This failure should be treated as `WrongMasterKey`, to let key manager able to fallback to use the previous key for decryption.
3 fix flaky test_mem_backend_authenticate. Fixes #7839 

### What is changed and how it works?

What's Changed: See the above.

### Related changes

No

### Check List 

Tests 

- Added new unit tests.
- Also did manual test to verify.

### Release note 

* Encryption: fix master key not being able to rotate.

### CODE REVIEW

File: components/encryption/src/master_key/mem.rs [hunk 1]
```diff
@@ -53,7 +53,7 @@ impl MemAesGcmBackend {
                 ))
             })?;
         if method.as_slice() != MetadataMethod::Aes256Gcm.as_slice() {
-            return Err(Error::WrongMasterKey(box_err!(
+            return Err(Error::Other(box_err!(
```
Comment (overvenus) [inline components/encryption/src/master_key/mem.rs:56]: I'm confused, is there any rule to determining if we should return a `WrongMasterKey` error?

**Comment by hunterlxt** [comment]
it's better to leave comments to explain in TiKV encryption, unless it is clearly determined that the error is not `WrongMasterKey`, return `WrongMasterKey` as much as possible to let rotation work

File: components/encryption/src/master_key/mem.rs (hunk 1 above)
Comment (yiwu-arbug) [reply components/encryption/src/master_key/mem.rs:63]: The rule in my mind is return WrongMasterKey whenever the error is possibly caused by a wrong master key used, and other error otherwise. Here since only aes256-gcm is allowed currently, if we encounter a new method, the encrypted content could be generated by a future version of TiKV, where we cannot handle anyway even we fallback to a different master key. I added some comments to reason able the error handling.

**Comment by yiwu-arbug** [comment]
> it's better to leave comments to explain in TiKV encryption, unless it is clearly determined that the error is not `WrongMasterKey`, return `WrongMasterKey` as much as possible to let rotation work

I'm incline to avoid returning `WrongMasterKey`, whenever the error could not caused by using a wrong master key. But whenever that's possible, `WrongMasterKey` should be returned. I think the choice is case by case, and I've added more comments.
