### PR TITLE
raftstore: update apply state even if peer is removed

### LINKED ISSUE #16069: raftstore: linearibilizy is broken when follower read is used
## Bug Report

Reference https://github.com/pingcap/tidb/issues/48802.

### What version of TiKV are you using?

The master & release-7.5

### What operating system and CPU are you using?

It dos not matter

### Steps to reproduce

Run Jepsen test monotonic workload

### What did you expect?
It finishes ok.

### What did happened?
```
INFO [2023-11-21 07:34:08,613] jepsen test runner - jepsen.core {:perf
 {:latency-graph {:valid? true},
  :rate-graph {:valid? true},
  :valid? true},
 :workload
 {:cycle
  {:valid? false,
   :scc-count 1,
   :cycles
   ["Let:\n  T1 = {:type :ok, :f :read, :value {0 1889, 1 1875, 2 1892, 3 1814, 4 1794, 5 1912, 6 1909, 7 1719}, :process 69, :time 241358622457, :txn-info {:start_ts 445789485148667916}, :index 59501}\n  T2 = {:type :ok, :f :read, :value {0 1889, 1 1875, 2 1893, 3 1813, 4 1794, 5 1912, 6 1909, 7 1719}, :process 111, :time 241400793624, :txn-info {:start_ts 445789485135560758}, :index 59523}\n\nThen:\n  - T1 < T2, because T1 observed 2 = 1892, and T2 observed a higher value 1893.\n  - However, T2 < T1, because T2 observed 3 = 1813, and T1 observed a higher value 1814: a contradiction!"]},
  :timeline {:valid? true},
  :valid? false},
 :valid? false}


Analysis invalid! (ﾉಥ益ಥ）ﾉ ┻━┻
```

The cause of this issue is
```
When a peer is removed, its apply state is not updated. While a simultaneous snap request caused by follower read is processed in the same raft poller loop. An outdated apply state is used when checking the snapshot applied index version, will invalidate the coprocessor cache assumption and potentially lead to a violation of linearizability (returning stale cache).
```

### PR DESCRIPTION
**Pull request by overvenus**
### What is changed and how it works?

Issue Number: Close #16069

Also close pingcap/tidb#48802

What's Changed:

```commit-message
When a peer is removed, it is necessary to update its apply state because
this peer may be simultaneously taking a snapshot. An outdated apply state
will invalidate the coprocessor cache assumption and potentially lead to
a violation of linearizability (returning stale cache).
```

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

### Release note 

```release-note
Fix an issue that TiKV coprocessor may return stale data when a raft peer is removed
```

### CODE REVIEW

**Comment by tonyxuqqi** [comment]
@overvenus Is this a recent regression?

File: components/raftstore/src/store/fsm/apply.rs [hunk 1]
```diff
@@ -662,9 +662,7 @@ where
         results: VecDeque<ExecResult<EK::Snapshot>>,
     ) {
         if self.host.pre_persist(&delegate.region, true, None) {
```
Comment (cfzjywxk) [inline components/raftstore/src/store/fsm/apply.rs:664]: Is it possible that the apply state is not updated(`self.host.pre_persist` returns false) and later snap request is still processed, thus the linearizilibity is broken?

File: components/raftstore/src/store/fsm/apply.rs [hunk 2]
```diff
@@ -7656,6 +7677,124 @@ mod tests {
         system.shutdown();
     }
 
+    // When a peer is removed, it is necessary to update its apply state because
+    // this peer may be simultaneously taking a snapshot. An outdated apply state
+    // will invalidate the coprocessor cache assumption and potentially lead to
```
Comment (Connor1996) [inline components/raftstore/src/store/fsm/apply.rs:7682]: Could you elaborate on how it invalidates the coprocessor cache assumption?

File: components/raftstore/src/store/fsm/apply.rs (hunk 1 above)
Comment (overvenus) [reply components/raftstore/src/store/fsm/apply.rs:664]: It's currently not possible in TiKV because there is no such observer in TiKV code base, but it's possible for tiflash. cc @CalvinNeo

**Comment by overvenus** [comment]
> @overvenus Is this a recent regression?

It has existed for a long time, but recent releases (>7.0.0) are more likely to trigger the issue due to the default enabling of follower reads.

File: components/raftstore/src/store/fsm/apply.rs (hunk 1 above)
Comment (cfzjywxk) [reply components/raftstore/src/store/fsm/apply.rs:664]: So, would it be safer here to update the apply state to ensure the security of the coprocessor cache, but what side effects would this have on TiFlash?

**Review by Connor1996 — APPROVED** [review]
LGTM

File: components/raftstore/src/store/fsm/apply.rs (hunk 1 above)
Comment (CalvinNeo) [reply components/raftstore/src/store/fsm/apply.rs:664]: In current implementation of TiFlash, `pre_persist` is similar to `should_write_to_engine` with several differences:
1. We don't persist on ComputeHash, since we treat it as a empty write cmd
2. We don't persist on IngestSST, since it will make no mutation to the real data in KVEngine
3. We don't persist on DeleteRange, since we delete table when syncing DDL

IMO, I think `pre_persist` is safe to return true in TiFlash, since:
1. TiFlash does not support cop cache
