### PR TITLE
txn: make use of near_seek for write-cf

### LINKED ISSUE #8229: MvccTxn can't make use of near_seek
## Bug Report

`MvccTxn` always uses `seek` to find write records. The reason is `MvccReader` in it always creates a new write cursor:
https://github.com/tikv/tikv/blob/11cbf057ba8dec3a0833a9948b5ae9ec54d6113d/src/storage/mvcc/reader/reader.rs#L129-L145

It's better to use `next` to get older versions in some cases. For example, in https://github.com/tikv/tikv/issues/7024, you can see 578k seeks per second. Please be careful with prefix seek in rocksdb, it can't guarantee a total order of all keys, but only keys for the same prefix.

### PR DESCRIPTION
**Pull request by youjiali1995**
Signed-off-by: youjiali1995 <zlwgx1023@gmail.com>

### What problem does this PR solve?

Issue Number: close #8229  

Problem Summary:

`MvccTxn` doesn't make use of `near_seek`. It creates a write cursor for every seek which may cost a lot if many versions exist.

### What is changed and how it works?

What's Changed:

Add a single key mode for `MvccReader` which uses a single write cursor for each user key. When the current key is changed, a new write cursor is created to guarantee the total order of all keys due to prefix seek. This check involves a key comparison for every seek, but the cost is in a single-digit nanosecond.

### Check List 

Tests 

- Unit test
- Benchmark

```
test storage::mvcc_reader::bench_get_txn_commit_record_non_single_key_100 ... bench:     379,062 ns/iter (+/- 82,203)
test storage::mvcc_reader::bench_get_txn_commit_record_non_single_key_5   ... bench:      27,508 ns/iter (+/- 12,069)
test storage::mvcc_reader::bench_get_txn_commit_record_single_key_100     ... bench:      38,188 ns/iter (+/- 7,773)
test storage::mvcc_reader::bench_get_txn_commit_record_single_key_5       ... bench:      10,879 ns/iter (+/- 462)
```

### Release note 
* No release note.

### CODE REVIEW

File: src/storage/mvcc/reader/reader.rs [hunk 1]
```diff
@@ -77,6 +77,13 @@ pub struct MvccReader<S: Snapshot> {
     scan_mode: Option<ScanMode>,
     key_only: bool,
 
+    /// True means following operations are performed on keys with the same prefix, i.e.,
+    /// different versions of the same key. It can use prefix seek to speed up reads from write-cf.
+    /// The `scan_mode` is ignored if it's true.
+    single_key: bool,
```
Comment (sticnarf) [inline src/storage/mvcc/reader/reader.rs:83]: Can we assume we are using the `single_key` mode when `scan_mode` is `None`? Then maybe we don't need this field?

File: src/storage/mvcc/reader/reader.rs [hunk 2]
```diff
@@ -116,6 +126,10 @@ impl<S: Snapshot> MvccReader<S> {
         self.key_only = key_only;
     }
 
+    pub fn set_single_key(&mut self, single_key: bool) {
```
Comment (nrc) [inline src/storage/mvcc/reader/reader.rs:126]: This doesn't need to be a function, just make the field `pub`

File: src/storage/mvcc/reader/reader.rs (hunk 1 above)
Comment (youjiali1995) [reply src/storage/mvcc/reader/reader.rs:83]: OK. Only support `single_key` mode and scan mode.

Comment (MyonKeminta) [reply src/storage/mvcc/reader/reader.rs:83]: Is it confirmed that we can reuse the reader on different keys even if single_key is set to true?

**Review by sticnarf — APPROVED** [review]
LGTM. Except that I'm a bit worried about MvccReader's `write_cursor` being `pub`. The only usage now `check_extra_op` is ok to me. But it may be not safe that people who don't know the constraint misuse the write cursor.

**Review by MyonKeminta — APPROVED** [review]
LGTM.

**Review by ti-srebot — APPROVED** [review]
