### PR TITLE
calculate snap dir size by scan

### LINKED ISSUE #9896: Store used size changes a lot after restarting
### What version of TiKV are you using?

```
Release Version:   5.0.0-rc.x
Edition:           Community
Git Commit Hash:   34d72b137a3eeadbcb444613a32763e0cfa5c084
Git Commit Branch: heads/refs/tags/v5.0.0-nightly
UTC Build Time:    2021-03-17 03:10:24
Rust Version:      rustc 1.51.0-nightly (1d0d76f8d 2021-01-24)
Enable Features:   jemalloc mem-profiling portable sse protobuf-codec test-engines-rocksdb cloud-aws cloud-gcp
Profile:           dist_release
```

### What operating system and CPU are you using?

Not related 

### Steps to reproduce

Run some workload and the used size will increase infinitely. And do a restart, the used size will be normal again.

### What did you expect?
the store used size is close to store size

### What did happened?
截屏2021-03-25 下午7 55 10

From PD metrics, store used size changes a lot after restarting which is reported from TiKV side.
TiKV calculates store used size by adding snapshot total size and engine used size.

截屏2021-03-25 下午7 55 27

image

From metrics, we can know that store size(engine used size) and disk space util doesn't changes a lot, **so it must be something wrong with snpashot total size.**

### PR DESCRIPTION
**Pull request by hicqu**
Signed-off-by: qupeng <qupeng@pingcap.com>

### What problem does this PR solve?

Issue Number: close #9896 .

### What is changed and how it works?

Before the patch the snap directory size is tracked in memory. However it's hard to handle `mv *.sst.tmp *.sst` if the target path exists. Besides this maybe there are still other unknown bugs.

This PR calculates the snap directory size by scan. This operation is moved to the PD worker thread from raftstore threads. A benchmark in #9896 shows that the scan won't hurt performance too much.

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- PR to update `pingcap/tidb-ansible`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Manual test
  With the patch store-used-size is very close to engine-size:
  
图片

  Without the patch store-used-size becomes far from engine-size after about 6 hours:
图片

### Release note 
* No release note.

### CODE REVIEW

File: components/raftstore/src/store/worker/pd.rs [hunk 1]
```diff
@@ -670,8 +672,8 @@ where
         stats.set_capacity(capacity);
 
         // already include size of snapshot files
```
Comment (Connor1996) [inline components/raftstore/src/store/worker/pd.rs:674]: we can remove the comment now

File: components/raftstore/src/store/snap.rs [hunk 2]
```diff
@@ -1453,8 +1453,18 @@ impl SnapManagerCore {
     fn get_total_snap_size(&self) -> Result<u64> {
         let mut total_size = 0;
         for entry in fs::read_dir(&self.base)? {
-            let entry = entry?;
-            let metadata = entry.metadata()?;
+            macro_rules! ignore_not_found {
+                ($op:expr) => {
+                    match $op {
+                        Err(e) if e.kind() == ErrorKind::NotFound => continue,
```
Comment (Connor1996) [inline components/raftstore/src/store/snap.rs:1459]: what's the case that the entry is not found.

Comment (hicqu) [reply components/raftstore/src/store/snap.rs:1459]: `read_dir` and read entries is not atomic. It's possible that snapshots are deleted between them, in which case we can meet error `no such file or directory`.

**Review by Connor1996 — APPROVED** [review]
LGTM

File: components/raftstore/src/store/snap.rs [hunk 3]
```diff
@@ -1448,6 +1450,34 @@ impl SnapManager {
...
+                        Err(e) => return Err(Error::from(e)),
+                        Ok(x) => x,
+                    }
+                };
+            }
+
+            let entry = ignore_not_found!(entry);
```
Comment (BusyJay) [inline components/raftstore/src/store/snap.rs:1466]: How about
```
let res = entry.and_then(|e| (e, e.metadata()));
let (entry, metadata) = match res {
    ...
};
```

**Review by NingLin-P — COMMENTED** [review]
Rest LGTM

File: components/raftstore/src/store/snap.rs (hunk 3 above)
Comment (BusyJay) [reply components/raftstore/src/store/snap.rs:1466]: Or just put all body of the loop into a closure.

**Review by NingLin-P — APPROVED** [review]

**Comment by nolouch** [comment]
Does release 3.0 exist this problem?

**Comment by BusyJay** [comment]
Does it mean there is leak resource?
