### PR TITLE
raftstore: Fix too large slow log

### LINKED ISSUE #17294: Slow log is too large
## Bug Report

Introduced by https://github.com/tikv/tikv/pull/17164, slow log is recorded for handing peer messages. These messages include `RaftlogFetched` which would output the entries content in debug format. The content may be huge.

img_v3_02cq_b86d0293-90f4-48ef-bf84-3a4adc14210g

### PR DESCRIPTION
**Pull request by Connor1996**
### What is changed and how it works?

Issue Number: Close #17294 

What's Changed:

```commit-message
Fix too large slow log
```

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [ ] Need to cherry-pick to the release branch

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note

```release-note
None
```

### CODE REVIEW

File: components/raftstore/src/store/entry_storage.rs [hunk 1]
```diff
@@ -431,6 +431,19 @@ pub struct RaftlogFetchResult {
     pub term: u64,
 }
 
+impl Debug for RaftlogFetchResult {
```
Comment (LykxSassinator) [inline components/raftstore/src/store/entry_storage.rs:434]:
```suggestion
impl std::fmt::Debug for RaftlogFetchResult {
```

**Review by LykxSassinator — APPROVED** [review]
LGTM

**Review by glorv — APPROVED** [review]
