### PR TITLE
sst_import: keep import sst if the ingest apply index has not flush the rocksdb.

### LINKED ISSUE #14663: [Dynamic Regions] tikv panic repeatedly after one tikv failure for 10m and recover
### What version of TiKV are you using?
./tikv-server -V
 TiKV 
Release Version:   7.2.0-alpha
Edition:           Community
Git Commit Hash:   20b75dc4436dc19f1d41acadde9704041dbb7c0c
Git Commit Branch: heads/refs/tags/v7.2.0-alpha
UTC Build Time:    2023-04-21 11:39:36
Rust Version:      rustc 1.67.0-nightly (96ddd32c4 2022-11-14)
Enable Features:   pprof-fp jemalloc mem-profiling portable sse test-engine-kv-rocksdb test-engine-raft-raft-engine cloud-aws cloud-gcp cloud-azure
Profile:           dist_release
2023-04-25T22:09:40.726+0800	INFO	k8s/client.go:132

### What operating system and CPU are you using?
8c/32 g

### Steps to reproduce
inject one tikv failure last for 10m
http://perf.pingcap.net:3000/d/WOw1JWmVk/ha-test-case-detail?orgId=1&refresh=10s&var-case_id=3240157

### What did you expect?
tikv can worker after chaos recover

### What did happened?
tikv panic repeatedly
"[[lib.rs:497](http://lib.rs:497/)] [\"corrupted sst [error=EngineTraits(Engine(Status { code: IoError, sub_code: None, sev: NoError, state: \\\"IO error: No such file or directory: while stat a file for size: /var/lib/tikv/data/import/7bd33b5c-6a79-4e43-87f0-79d235300005_1174_23_274_write.sst: No such file or directory\\\" }))] [sst=uuid: 7BD33B5C6A794E4387F079D235300005 range { start: 7480000000000000FF625F720380000000FF0000372B03800000FF000000377A000000FC end: 7480000000000000FF625F720380000000FF0000372D03800000FF0000003FED000000FC } length: 486020 cf_name: \\\"write\\\" region_id: 1174 region_epoch { conf_ver: 23 version: 274 } cipher_iv: 9B84928F5DEBA6DCDEFCBFD2AB13160A] [peer_id=1175] [region_id=1174]\"] [backtrace=\"   0: tikv_util::set_panic_hook::{{closure}}\\n             at home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/components/tikv_util/src/lib.rs:496:18\\n](http://github.com/pingcap/tikv/components/tikv_util/src/lib.rs:496:18//n)   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call\\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/[boxed.rs:2032](http://boxed.rs:2032/):9\\n      std::panicking::rust_panic_with_hook\\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/[panicking.rs:692](http://panicking.rs:692/):13\\n   2: std::panicking::begin_panic_handler::{{closure}}\\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/[panicking.rs:579](http://panicking.rs:579/):13\\n   3: std::sys_common::backtrace::__rust_end_short_backtrace\\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/[backtrace.rs:137](http://backtrace.rs:137/):18\\n   4: rust_begin_unwind\\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/[panicking.rs:575](http://panicking.rs:575/):5\\n   5: core::panicking::panic_fmt\\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/[panicking.rs:65](http://panicking.rs:65/):14\\n   6: raftstore_v2::operation::command::write::ingest::<impl raftstore_v2::raft::apply::Apply<EK,R>>::apply_ingest\\n             at home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/components/raftstore-v2/src/operation/command/write/ingest.rs:108:21\\n](http://github.com/pingcap/tikv/components/raftstore-v2/src/operation/command/write/ingest.rs:108:21//n)      raftstore_v2::operation::command::<impl raftstore_v2::raft::apply::Apply<EK,R>>::apply_entry::{{closure}}\\n             at home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/components/raftstore-v2/src/operation/command/mod.rs:603:33\\n](http://github.com/pingcap/tikv/components/raftstore-v2/src/operation/command/mod.rs:603:33//n)   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll\\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/[mod.rs:91](http://mod.rs:91/):19\\n      raftstore_v2::operation::command::<impl raftstore_v2::raft::apply::Apply<EK,R>>::apply_committed_entries::{{closure}}\\n             at home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/components/raftstore-v2/src/operation/command/mod.rs:536:61\\n](http://github.com/pingcap/tikv/components/raftstore-v2/src/operation/command/mod.rs:536:61//n)      <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll\\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/[mod.rs:91](http://mod.rs:91/):19\\n      raftstore_v2::fsm::apply::ApplyFsm<EK,R>::handle_all_tasks::{{closure}}\\n             at home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/components/raftstore-v2/src/fsm/apply.rs:138:94\\n](http://github.com/pingcap/tikv/components/raftstore-v2/src/fsm/apply.rs:138:94//n)   8: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll\\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/[mod.rs:91](http://mod.rs:91/):19\\n      raftstore_v2::operation::command::<impl raftstore_v2::raft::peer::Peer<EK,ER>>::schedule_apply_fsm::{{closure}}\\n             at home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/components/raftstore-v2/src/operation/command/mod.rs:157:61\\n](http://github.com/pingcap/tikv/components/raftstore-v2/src/operation/command/mod.rs:157:61//n)      <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll\\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/[mod.rs:91](http://mod.rs:91/):19\\n      <tracker::tls::TrackedFuture<F> as core::future::future::Future>::poll::{{closure}}\\n             at home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/components/tracker/src/tls.rs:64:23\\n](http://github.com/pingcap/tikv/components/tracker/src/tls.rs:64:23//n)      std::thread::local::LocalKey<T>::try_with\\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/[local.rs:446](http://local.rs:446/):16\\n      std::thread::local::LocalKey<T>::with\\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/[local.rs:422](http://local.rs:422/):9\\n      <tracker::tls::TrackedFuture<F> as core::future::future::Future>::poll\\n             at home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/components/tracker/src/tls.rs:62:9\\n](http://github.com/pingcap/tikv/components/tracker/src/tls.rs:62:9//n)      tikv_util::yatp_pool::future_pool::PoolInner::spawn::{{closure}}\\n             at home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/components/tikv_util/src/yatp_pool/future_pool.rs:167:27\\n](http://github.com/pingcap/tikv/components/tikv_util/src/yatp_pool/future_pool.rs:167:27//n)      <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll\\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/[mod.rs:91](http://mod.rs:91/):19\\n      yatp::task::future::RawTask<F>::poll\\n             at rust/git/checkouts/yatp-e704b73c3ee279b6/5523a9a/src/task/[future.rs:59](http://future.rs:59/):9\\n   9: yatp::task::future::TaskCell::poll\\n             at rust/git/checkouts/yatp-e704b73c3ee279b6/5523a9a/src/task/[future.rs:103](http://future.rs:103/):9\\n      <yatp::task::future::Runner as yatp::pool::runner::Runner>::handle\\n             at rust/git/checkouts/yatp-e704b73c3ee279b6/5523a9a/src/task/[future.rs:387](http://future.rs:387/):20\\n  10: <tikv_util::yatp_pool::YatpPoolRunner<T> as yatp::pool::runner::Runner>::handle\\n             at home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/components/tikv_util/src/yatp_pool/mod.rs:193:24\\n](http://github.com/pingcap/tikv/components/tikv_util/src/yatp_pool/mod.rs:193:24//n)      yatp::pool::worker::WorkerThread<T,R>::run\\n             at rust/git/checkouts/yatp-e704b73c3ee279b6/5523a9a/src/pool/[worker.rs:48](http://worker.rs:48/):13\\n      yatp::pool::builder::LazyBuilder<T>::build::{{closure}}\\n             at rust/git/checkouts/yatp-e704b73c3ee279b6/5523a9a/src/pool/[builder.rs:114](http://builder.rs:114/):25\\n      std::sys_common::backtrace::__rust_begin_short_backtrace\\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/[backtrace.rs:121](http://backtrace.rs:121/):18\\n  11: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}\\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/[mod.rs:551](http://mod.rs:551/):17\\n      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once\\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panic/[unwind_safe.rs:271](http://unwind_safe.rs:271/):9\\n      std::panicking::try::do_call\\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/[panicking.rs:483](http://panicking.rs:483/):40\\n      std::panicking::try\\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/[panicking.rs:447](http://panicking.rs:447/):19\\n      std::panic::catch_unwind\\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/[panic.rs:137](http://panic.rs:137/):14\\n      std::thread::Builder::spawn_unchecked_::{{closure}}\\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/[mod.rs:550](http://mod.rs:550/):30\\n      core::ops::function::FnOnce::call_once{{vtable.shim}}\\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/[function.rs:513](http://function.rs:513/):5\\n  12: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once\\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/[boxed.rs:2000](http://boxed.rs:2000/):9\\n      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once\\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/[boxed.rs:2000](http://boxed.rs:2000/):9\\n      std::sys::unix::thread::Thread::new::thread_start\\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys/unix/[thread.rs:108](http://thread.rs:108/):17\\n  13: start_thread\\n  14: __GI___clone\\n\"] [location=/home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/components/raftstore-v2/src/operation/command/write/ingest.rs:108](http://github.com/pingcap/tikv/components/raftstore-v2/src/operation/command/write/ingest.rs:108)] [thread_name=apply-0]"

### PR DESCRIPTION
**Pull request by bufferflies**
### What is changed and how it works?

Issue Number: Close #14663

What's Changed:

```commit-message
record the sst apply index  and delete them when the flushed index is higher than the apply index.
```

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)

Side effects

### Release note 

```release-note
fix the bug that the sst file is deleted by wrong.
```

### CODE REVIEW

File: components/engine_traits/src/flush.rs [hunk 1]
```diff
@@ -54,6 +54,37 @@ struct FlushProgress {
     last_flushed: [u64; DATA_CFS_LEN],
 }
 
+/// A share state between raftstore and underlying engine.
+///
+/// raftstore will update state changes and corresponding sst apply index, when
+/// apply ingest sst request, it should ensure the sst can be deleted
+/// if the flushed index greater than it .
+#[derive(Debug)]
+pub struct SSTState {
```
Comment (tonyxuqqi) [inline components/engine_traits/src/flush.rs:63]: 1) I think sst_applied_index should be per CF, not shared among the CFs.
2) The name of SSTState is also a bit confusing.  Maybe can renamed as SSTApplyIndex

File: components/raftstore-v2/src/operation/command/write/ingest.rs [hunk 2]
```diff
@@ -73,6 +73,15 @@ impl<EK: KvEngine, ER: RaftEngine> Peer<EK, ER> {
         if stale_ssts.is_empty() {
             return;
         }
+        let sst_index = self.sst_state().sst_applied_index();
```
Comment (tonyxuqqi) [inline components/raftstore-v2/src/operation/command/write/ingest.rs:76]: I don't think this will work well.  It will likely unnecessarily delay the SST cleanup. 
self.sst_state() is Peer/Region level state. Imagining we have two import SSTs calls on the same region.
The first import is with apply index1 and the second is with apply index2.
Then after the second is called, the sst_state is updated with apply index2.  Let's assume apply index1 is flushed and apply index2 is not flushed.
Now when cleanup sst is called,  because  here "log_recovery.as_ref()[off] >= sst_index" will always return false (because sst_index is apply index2, which is not flushed) even for the first import's sstmeta.

File: components/engine_traits/src/flush.rs (hunk 1 above)
Comment (tonyxuqqi) [reply components/engine_traits/src/flush.rs:63]: In fact, I guess we may have to keep the map of SstMeta and its apply index to make it work.

File: components/raftstore-v2/src/operation/command/write/ingest.rs (hunk 2 above)
Comment (bufferflies) [reply components/raftstore-v2/src/operation/command/write/ingest.rs:76]: yes, good suggestion. I wiil record the relationship between the sst meta with the entry index.

File: components/raftstore-v2/src/operation/command/write/ingest.rs [hunk 3]
```diff
@@ -67,12 +67,32 @@ impl<EK: KvEngine, ER: RaftEngine> Peer<EK, ER> {
...
+            fail::fail_point!("on_cleanup_import_sst", |_| false);
+            true
+        })();
+        if skip {
+            let epoch = self.region().get_region_epoch();
+            stale_ssts.retain(|sst| util::is_epoch_stale(sst.get_region_epoch(), epoch));
+        }
+
+        // some sst needs to be kept if the log didn't flush the dish.
+        if let Some(log_recovery) = self.storage().apply_trace().log_recovery() {
```
Comment (SpadeA-Tang) [inline components/raftstore-v2/src/operation/command/write/ingest.rs:81]: apply_trace.data_cfs may be sufficient here? As for a specified cf, apply will be skipped if apply index is less than flushed index.

Comment (bufferflies) [reply components/raftstore-v2/src/operation/command/write/ingest.rs:80]: that sst will not record in the sst apply state.

**Review by SpadeA-Tang — APPROVED** [review]

File: components/raftstore-v2/src/operation/command/write/ingest.rs [hunk 4]
```diff
@@ -67,12 +67,31 @@ impl<EK: KvEngine, ER: RaftEngine> Peer<EK, ER> {
...
-        stale_ssts.retain(|sst| util::is_epoch_stale(sst.get_region_epoch(), epoch));
+        let check_epoch = (|| {
+            fail::fail_point!("on_cleanup_import_sst", |_| false);
+            true
+        })();
+        if check_epoch {
+            let epoch = self.region().get_region_epoch();
+            stale_ssts.retain(|sst| util::is_epoch_stale(sst.get_region_epoch(), epoch));
+        }
+        // some sst needs to be kept if the log didn't flush the dish.
```
Comment (overvenus) [inline components/raftstore-v2/src/operation/command/write/ingest.rs:79]: `dish`? typo?

File: components/raftstore-v2/src/operation/ready/apply_trace.rs [hunk 5]
```diff
@@ -302,6 +302,7 @@ impl ApplyTrace {
         for (off, pr) in self.data_cfs.iter().enumerate() {
             flushed_indexes[off] = pr.flushed;
         }
+        fail::fail_point!("on_cleanup_import_sst", |_| Some(Box::new(flushed_indexes)));
```
Comment (overvenus) [inline components/raftstore-v2/src/operation/ready/apply_trace.rs:305]: Better to name it `on_log_recovery`.

File: components/engine_traits/src/flush.rs [hunk 6]
```diff
@@ -54,6 +54,40 @@ struct FlushProgress {
...
+        let mut map = self.sst_map.write().unwrap();
+        for uuid in uuids {
+            map.insert(uuid, sst_applied_index);
+        }
+    }
+
+    /// Query the sst applied index.
+    #[inline]
+    pub fn sst_applied_index(&self, uuid: &Vec<u8>) -> Option<u64> {
+        self.sst_map.read().unwrap().get(uuid).copied()
```
Comment (overvenus) [inline components/engine_traits/src/flush.rs:87]: Do we need to GC `sst_map`?

File: components/raftstore-v2/src/operation/command/write/ingest.rs [hunk 7]
```diff
@@ -67,12 +67,31 @@ impl<EK: KvEngine, ER: RaftEngine> Peer<EK, ER> {
...
+                if let Some(index) = sst_index {
+                    return log_recovery.as_ref()[off] >= index;
+                }
+                true
+            });
+        }
         if stale_ssts.is_empty() {
             return;
         }
+        fail::fail_point!("sst_importer_delete_sst");
```
Comment (overvenus) [inline components/raftstore-v2/src/operation/command/write/ingest.rs:94]: How about `on_cleanup_import_sst_schedule`?

File: components/engine_traits/src/flush.rs (hunk 6 above)
Comment (bufferflies) [reply components/engine_traits/src/flush.rs:87]: yes, I will remove the uuid which needs to delete?

File: components/raftstore-v2/src/operation/command/write/ingest.rs (hunk 4 above)
Comment (bufferflies) [reply components/raftstore-v2/src/operation/command/write/ingest.rs]: fixed by disk

File: components/raftstore-v2/src/operation/ready/apply_trace.rs (hunk 5 above)
Comment (bufferflies) [reply components/raftstore-v2/src/operation/ready/apply_trace.rs]: done

File: components/raftstore-v2/src/operation/command/write/ingest.rs (hunk 7 above)
Comment (bufferflies) [reply components/raftstore-v2/src/operation/command/write/ingest.rs]: done

File: components/raftstore-v2/src/operation/command/write/ingest.rs [hunk 8]
```diff
@@ -67,12 +67,36 @@ impl<EK: KvEngine, ER: RaftEngine> Peer<EK, ER> {
...
-        let epoch = self.region().get_region_epoch();
         let mut stale_ssts = Vec::from(ssts);
-        stale_ssts.retain(|sst| util::is_epoch_stale(sst.get_region_epoch(), epoch));
+        let check_epoch = (|| {
+            fail::fail_point!("on_cleanup_import_sst", |_| false);
+            true
+        })();
+        if check_epoch {
+            let epoch = self.region().get_region_epoch();
+            stale_ssts.retain(|sst| util::is_epoch_stale(sst.get_region_epoch(), epoch));
```
Comment (overvenus) [inline components/raftstore-v2/src/operation/command/write/ingest.rs:77]:
```suggestion
            stale_ssts.retain(|sst| {
                        fail::fail_point!("on_cleanup_import_sst", |_| true);
                        util::is_epoch_stale(sst.get_region_epoch(), epoch)
            });
```

**Review by overvenus — APPROVED** [review]

File: components/raftstore-v2/src/operation/command/write/ingest.rs (hunk 8 above)
Comment (bufferflies) [reply components/raftstore-v2/src/operation/command/write/ingest.rs]: good suggestion

File: components/raftstore-v2/src/operation/command/write/ingest.rs [hunk 9]
```diff
@@ -75,17 +75,17 @@ impl<EK: KvEngine, ER: RaftEngine> Peer<EK, ER> {
...
-                let off = data_cf_offset(sst.get_cf_name());
-                let uuid = sst.get_uuid().to_vec();
-                let sst_index = self.sst_apply_state().sst_applied_index(&uuid);
-                if let Some(index) = sst_index {
-                    return log_recovery.as_ref()[off] >= index;
-                }
-                true
-            });
-        }
+        let flushed_indexes = self.storage().apply_trace().flushed_indexes();
```
Comment (overvenus) [inline components/raftstore-v2/src/operation/command/write/ingest.rs:78]: What does the commit fix? How about using `admin.flushed`?

Comment (bufferflies) [reply components/raftstore-v2/src/operation/command/write/ingest.rs:78]: the `admin.flushed_index` is not correct, it doesn't write the disk sometimes.
