### PR TITLE
Fix multipart S3 uploads, customizable log-backup multipart threshold

### LINKED ISSUE #19162: Log backup to S3 stuck because of multipart upload bug
## Bug Report

Under heavy write pressure, log backup would fail once 10000 * 5MiB upload threshold is crossed.
S3Uploader tries to upload the data, and received HTTP 400 response from S3 API, as only 10000
parts are allowed.

br output:

```
sh-5.1# var/lib/br-bin/br log status --pd=redacted:2379 --ca=redacted/ca.crt --cert=redacted/tls.crt --key=/redacted/tls.key --send-credentials-to-tikv=false
[ ... cut by Vlad ... ]
● Total 1 Tasks.
> #1 <
                           name: redacted
                         status: ○ ERROR
                          start: 2025-11-04 23:01:12.523 +0000
                            end: 2090-11-18 14:07:45.624 +0000
                        storage: s3://redacted/scheduled/log/log-2025-11-04t23-00-58
                    speed(est.): 0.00 ops/s
             checkpoint[global]: 2025-11-15 07:28:22.459 +0000; gap=87h45m52s
          error[store=30861887]: KV:LogBackup:Io
error-happen-at[store=30861887]: 2025-11-16 00:32:54.527 +0000; gap=70h41m20s
  error-message[store=30861887]: I/O Error: failed to put object aws-sdk error: ServiceError(ServiceError { source: Unhandled(Unhandled { source: ErrorMetadata { code: Some("InvalidArgument"), message: Some("Part number must be an integer between 1 and 10000, inclusive"), extras: Some({"aws_request_id": "redacted", "s3_
                                 extended_request_id": "redacted"}) }, meta: ErrorMetadata { code: Some("InvalidArgument"), message: Some("Part number must be an integer between 1 and 10000, inclusive"), extras: Some({"aws_request_id": "redacted", "s3_extended_request_id": "redacted"}) } }), raw: Response { status: StatusCode(400), headers: Headers { headers: {"x-amz-request-id": HeaderValue { _private: H0("D2VZ19H0M53HQYD8") }, "x-amz-i
                                 d-2": HeaderValue { _private: H0("redacted") }, "content-type": HeaderValue { _private: H0("application/xml") }, "transfer-encoding": HeaderValue { _private: H0("chunked") }, "date": HeaderValue { _private: H
                                 0("Sun, 16 Nov 2025 00:32:51 GMT") }, "connection": HeaderValue { _private: H0("close") }, "server": HeaderValue { _private: H0("AmazonS3") }} }, body: SdkBody { inner: Once(Some(b"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>InvalidArgument</Code><Message>Part number must be an inte
                                 ger between 1 and 10000, inclusive</Message><ArgumentName>partNumber</ArgumentName><ArgumentValue>10001</ArgumentValue><RequestId>redacted</RequestId><HostId>redacted</HostId></Error>")), retryable: t
                                 rue }, extensions: Extensions { extensions_02x: Extensions, extensions_1x: Extensions } } })

```   

### What version of TiKV are you using?

8.5.2

### What operating system and CPU are you using?

Linux

### Steps to reproduce

Tricky to repro, observed under following scenario: have a log backup running, ingest a hundreds GiB of data to a new table via lightning 

### What did you expect?

log backup to continue running (no expectation of lightning data in the backup)

### What did happened?

log backup is broken

### PR DESCRIPTION
**Pull request by vldmit**
### What is changed and how it works?

Make S3Uploader honor 10000 parts limit in multipart S3 uploads, by increasing the part size if necessary.
This prevents log backup blockage in the scenarios of high write pressure (e.g. during lightning ingestion).

Also, make the multipart upload threshold configurable for log backups (existing s3_multi_part_size
option only applies to snapshots now).

Issue Number: Close #19162

What's Changed:

```commit-message
- Make S3Uploader honor 10000 parts limit in multipart S3 uploads, by increasing the part size if necessary.
- Make the multipart upload threshold configurable for log backups

```

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [ ] Need to cherry-pick to the release branch

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note

```release-note
S3 multipart uploads honor number of parts limit
```

## Summary by CodeRabbit

* **New Features**
  * Added configurable S3 multi-part upload size parameter (default 5MB, maximum 5GB) for backup operations
  * Automatic intelligent adjustment of upload part sizes for large files to maintain S3 compatibility

* **Improvements**
  * Enhanced configuration validation to enforce safe upload size limits with helpful warnings

### CODE REVIEW

File: src/config/mod.rs [hunk 1]
```diff
@@ -3193,6 +3202,7 @@ impl Default for BackupStreamConfig {
             initial_scan_rate_limit: ReadableSize::mb(60),
             initial_scan_concurrency: 6,
             temp_file_memory_quota: cache_size,
+            s3_multi_part_size: ReadableSize::mb(5),
```
Comment (3pointer) [inline src/config/mod.rs:3209]: To maintain maximum compatibility with existing behavior, we can increase the default part_size to 256 MB, so that in most cases the upload will be handled by a single PUT request.

Comment (vldmit) [reply src/config/mod.rs:3209]: @3pointer I'm happy to make the change, just to clarify: existing behavior is to have 5MiB s3_multi_part_size for backup-stream:

- `BackendConfig::default()` sets `s3_multi_part_size` to 0
- `set_multi_part_size(0)` enforces `MINIMUM_PART_SIZE`, which is 5MiB

256MiB default would be a behavior change, I think. In this PR, we adjust the part size only if file size is above s3_multi_part_size*10000 (~48GiB with 5MiB default).

**Review by 3pointer — APPROVED** [review]

File: src/config/mod.rs (hunk 1 above)
Comment (3pointer) [reply src/config/mod.rs:3209]: Ok, LGTM

**Comment by mittalrishabh** [comment]
[zhangjinpeng87](https://github.com/zhangjinpeng87) please approve this

**Review by v01dstar — APPROVED** [review]

**Review by zhangjinpeng87 — APPROVED** [review]
LGTM
