### PR TITLE
raftstore-v2: fix non-deterministic region merge

### LINKED ISSUE #15682: [Dynamic Regions] panic with "region corrupted"
## Bug Report

Similar to issue #15242, even though PR #15625 resolves the problem in the
transfer leader scenario, there are still cases that result in a "region corrupted" error. 

The main cause of this issue is that commit merge and rollback merge are not
deterministic, meaning that any transient error during propose could lead to
the problem occurring again. E.g., proposal failure by following lines:

https://github.com/tikv/tikv/blob/b95f5cd0353506d728d0a50b7a898b503de072e1/components/raftstore-v2/src/operation/command/admin/mod.rs#L112-L122

To fix such issue, TiKV must only propose rollback merge when target region is
not found or epoch has increased.

### What version of TiKV are you using?

v7.3.0

### Steps to reproduce

```rust
#[test]
fn test_deterministic_commit_rollback_merge() {
    use test_raftstore_v2::*;
    let mut cluster = new_node_cluster(0, 3);
    configure_for_merge(&mut cluster.cfg);
    // Use a large election tick to stable test.
    configure_for_lease_read(&mut cluster.cfg, None, Some(1000));
    // Use 2 threads for polling peers, so that they can run concurrently.
    cluster.cfg.raft_store.store_batch_system.pool_size = 2;
    cluster.cfg.raft_store.store_batch_system.max_batch_size = Some(1);
    cluster.run();

    let pd_client = Arc::clone(&cluster.pd_client);
    let region = pd_client.get_region(b"k1").unwrap();
    cluster.must_split(&region, b"k2");

    let left = pd_client.get_region(b"k1").unwrap();
    let right = pd_client.get_region(b"k3").unwrap();
    let right_1 = find_peer(&right, 1).unwrap().clone();
    cluster.must_transfer_leader(right.get_id(), right_1);
    let left_2 = find_peer(&left, 2).unwrap().clone();
    cluster.must_transfer_leader(left.get_id(), left_2);

    cluster.must_put(b"k1", b"v1");
    cluster.must_put(b"k3", b"v3");
    for i in 0..3 {
        must_get_equal(&cluster.get_engine(i + 1), b"k1", b"v1");
        must_get_equal(&cluster.get_engine(i + 1), b"k3", b"v3");
    }

    // Delay 1003 apply by dropping append response, so that proposal will fail
    // due to applied_term != current_term.
    let target_region_id = left.get_id();
    cluster.add_recv_filter_on_node(
        1,
        Box::new(DropMessageFilter::new(Arc::new(move |m| {
            if m.get_region_id() == target_region_id {
                return m.get_message().get_msg_type() != MessageType::MsgAppendResponse;
            }
            true
        }))),
    );

    let left_1 = find_peer(&left, 1).unwrap().clone();
    cluster.must_transfer_leader(left.get_id(), left_1);

    // left(1000) <- right(1).
    let (tx1, rx1) = channel();
    let (tx2, rx2) = channel();
    let rx2_ = Mutex::new(rx2);
    fail::cfg_callback("on_propose_commit_merge_fail_store_1", move || {
        tx1.send(()).unwrap();
        rx2_.lock().unwrap().recv().unwrap();
    })
    .unwrap();
    cluster.merge_region(right.get_id(), left.get_id(), Callback::None);

    // Wait for target fails to propose commit merge.
    rx1.recv_timeout(Duration::from_secs(5)).unwrap();
    // Let target apply continue, and new AskCommitMerge messages will propose
    // commit merge successfully.
    cluster.clear_recv_filter_on_node(1);

    // Trigger a CheckMerge tick, so source will send a AskCommitMerge again.
    fail::cfg("ask_target_peer_to_commit_merge_store_1", "pause").unwrap();
    let router = cluster.get_router(1).unwrap();
    router
        .check_send(1, PeerMsg::Tick(PeerTick::CheckMerge))
        .unwrap();

    // Send RejectCommitMerge to source.
    tx2.send(()).unwrap();
    fail::remove("on_propose_commit_merge_fail_store_1");

    // Wait for target applies to current term.
    cluster.must_put(b"k1", b"v11");

    // By remove the failpoint, CheckMerge tick sends a AskCommitMerge again.
    fail::remove("ask_target_peer_to_commit_merge_store_1");
    // At this point, source region will propose rollback merge.

    // Wait for source handle RejectCommitMerge and commit rollback merge.
    let timer = Instant::now();
    loop {
        if left.get_region_epoch().get_version()
            == cluster.get_region_epoch(left.get_id()).get_version()
        {
            if timer.saturating_elapsed() > Duration::from_secs(5) {
                panic!("region {:?} is still not merged.", left);
            }
        } else {
            break;
        }
        sleep_ms(10);
    }

    // No matter commit merge or rollback merge, cluster must be available to
    // process requests
    cluster.must_put(b"k0", b"v0");
    cluster.must_put(b"k4", b"v4");
}
```

With new failpoints below: 

```diff
diff --git a/components/raftstore-v2/src/operation/command/admin/merge/commit.rs b/components/raftstore-v2/src/operation/command/admin/merge/commit.rs
index 8e55f89a7..6203183f7 100644
--- a/components/raftstore-v2/src/operation/command/admin/merge/commit.rs
+++ b/components/raftstore-v2/src/operation/command/admin/merge/commit.rs
@@ -177,6 +177,11 @@ impl<EK: KvEngine, ER: RaftEngine> Peer<EK, ER> {
             self.region_id() == 2,
             |_| {}
         );
+        fail::fail_point!(
+            "ask_target_peer_to_commit_merge_store_1",
+            store_ctx.store_id == 1,
+            |_| {}
+        );
         let state = self.applied_merge_state().unwrap();
         let target = state.get_target();
         let target_id = target.get_id();
@@ -345,6 +345,11 @@ impl<EK: KvEngine, ER: RaftEngine> Peer<EK, ER> {
                         return;
                     }
                 }
+                fail::fail_point!(
+                    "on_propose_commit_merge_fail_1",
+                    self.peer().get_store_id() == 1,
+                    |_| {}
+                );
                 let _ = store_ctx
                     .router
                     .force_send(source_id, PeerMsg::RejectCommitMerge { index });

```

### What did you expect?

No panic.

### What did happened?

Panic.

### PR DESCRIPTION
**Pull request by overvenus**
### What is changed and how it works?

Issue Number: Close #15682

What's Changed:

```commit-message
This commit addresses the issue where a "region corrupted" error still
occurs in certain scenarios despite PR #15625 resolving the problem in
the transfer leader scenario. The root cause of the issue is the
non-deterministic nature of commit merge and rollback merge, allowing
transient errors during propose to trigger the problem again.

To fix this issue, the proposed solution ensures that TiKV only
initiates rollback merge when either the target region is not found or
the epoch has increased.
```

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Integration test

### Release note 

```release-note
Fix an issue that may cause "region corrupted" panic during region merge.
```

### CODE REVIEW

File: components/raftstore-v2/src/operation/command/admin/merge/commit.rs [hunk 1]
```diff
@@ -306,63 +314,51 @@ impl<EK: KvEngine, ER: RaftEngine> Peer<EK, ER> {
...
+        );
+        assert!(
+            region_on_same_stores(source_region, region),
+            "{:?}, {:?}",
+            source_region,
+            region
+        );
+        assert!(!self.storage().has_dirty_data());
+        let (ch, res) = CmdResChannel::pair();
+        self.on_admin_command(store_ctx, req, ch);
```
Comment (tonyxuqqi) [inline components/raftstore-v2/src/operation/command/admin/merge/commit.rs:345]: should check is_leader()?

**Review by SpadeA-Tang — APPROVED** [review]

File: components/raftstore-v2/src/operation/command/admin/merge/commit.rs (hunk 1 above)
Comment (overvenus) [reply components/raftstore-v2/src/operation/command/admin/merge/commit.rs:345]: `on_admin_command` checks leader.

**Review by tonyxuqqi — APPROVED** [review]

**Review by tabokie — APPROVED** [review]
