### PR TITLE
gc_worker: fix deadlock when gc worker is busy

### LINKED ISSUE #18214: gc_worker: deadlock in gc_a_round
## Bug Report

when compaction-filter is disable, we will perform GC in a traditional way, and need to GC each region one by one
https://github.com/tikv/tikv/blob/25897b73e1f0e93f616c764dbe65ed7db02edd07/src/server/gc_worker/gc_manager.rs#L516-L528

and here we should notice that we hold the lock for `current_tasks` when we call `async_gc_next_region`, while in the `cb` function, we need the same lock too, which means, we should release the lock before run `cb`

however, when we gc a region with the function `async_gc_next_region` 

https://github.com/tikv/tikv/blob/caf82d2864d1501af733bf60c99a7732e105144b/src/server/gc_worker/gc_manager.rs#L581-L609 

 if we meet any error we will goto `hand_gc_task_schedule_error`
https://github.com/tikv/tikv/blob/25897b73e1f0e93f616c764dbe65ed7db02edd07/src/server/gc_worker/gc_worker.rs#L1139-L1153 

if it is a busy error,we will run the func `callback`

https://github.com/tikv/tikv/blob/caf82d2864d1501af733bf60c99a7732e105144b/src/server/gc_worker/gc_worker.rs#L1139-L1153

### What did you expect?

no deadlock
### What did happened?
GC blocks when meet error like `"failed to schedule gc task"] [err="channel is full"] `

### PR DESCRIPTION
**Pull request by zyguan**
### What is changed and how it works?

Issue Number: Close #18214

What's Changed:

```commit-message
Do not acquire lock in gc task callback when meeting GcWorkerTooBusy.
```

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [ ] Need to cherry-pick to the release branch

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note

```release-note
Fix the deadlock issue when gc worker is busy.
```

### CODE REVIEW

**Review by v01dstar — APPROVED** [review]
lgtm

File: src/server/gc_worker/gc_manager.rs [hunk 1]
```diff
@@ -514,14 +514,18 @@ impl<S: GcSafePointProvider, R: RegionInfoProvider + 'static, E: KvEngine> GcMan
...
-                AUTO_GC_PROCESSED_REGIONS_GAUGE_VEC
-                    .with_label_values(&[PROCESS_TYPE_GC])
-                    .inc();
+            let cb = Box::new(move |res| {
+                if let Err(Error(box ErrorInner::GcWorkerTooBusy)) = res {
+                    // the task is actually not scheduled, so no action here.
+                } else {
+                    let (lock, cvar) = &*controller;
+                    let mut current_tasks = lock.lock().unwrap();
+                    *current_tasks -= 1;
```
Comment (v01dstar) [inline src/server/gc_worker/gc_manager.rs:523]: In line 608 
https://github.com/zyguan/tikv/blob/9e0c123dd7f303c61c2b519d1169127e2069ed03/src/server/gc_worker/gc_manager.rs#L607-L611

It seems that, the counter incr by 1 no matter whether there is error or not. If we do not to acquire the lock and deal with counter here, then we probably also need to check the result there, and incr the counter conditionally.

**Comment by v01dstar** [comment]
Reading the code, it feels to me that, although, the **compile time** code stack has potential deadlock issue, but `channel is fully` won't really happen in runtime because of this [`may_be_wait()`](https://github.com/zyguan/tikv/blob/9e0c123dd7f303c61c2b519d1169127e2069ed03/src/server/gc_worker/gc_manager.rs#L530). I am fine with fixing the **compile time** error now, just want to clarify the real impact.

**Comment by zyguan** [comment]
> Reading the code, it feels to me that, although, the **compile time** code stack has potential deadlock issue, but `channel is fully` won't really happen in runtime because of this [`may_be_wait()`](https://github.com/zyguan/tikv/blob/9e0c123dd7f303c61c2b519d1169127e2069ed03/src/server/gc_worker/gc_manager.rs#L530). I am fine with fixing the **compile time** error now, just want to clarify the real impact.

This PR tries to fix #18214 which comes from ONCALL-7659 last week, you may refer the internal ONCALL issue for the real impact. IMO, `maybe_wait` doesn't prevent `ScheduleError::Full`, it only limits the rate of `GcTask::Gc`, but doesn't affect gc tasks of other types.

File: src/server/gc_worker/gc_manager.rs [hunk 2]
```diff
@@ -514,14 +514,18 @@ impl<S: GcSafePointProvider, R: RegionInfoProvider + 'static, E: KvEngine> GcMan
...
-                let (lock, cvar) = &*controller;
-                let mut current_tasks = lock.lock().unwrap();
-                *current_tasks -= 1;
-                cvar.notify_one();
-                AUTO_GC_PROCESSED_REGIONS_GAUGE_VEC
-                    .with_label_values(&[PROCESS_TYPE_GC])
-                    .inc();
+            let cb = Box::new(move |res| {
+                if let Err(Error(box ErrorInner::GcWorkerTooBusy)) = res {
+                    // the task is actually not scheduled, so no action here.
```
Comment (MyonKeminta) [inline src/server/gc_worker/gc_manager.rs:519]: It looks still not a nice-looking solution to me 🤔 Can we consider replacing it with some other synchronization methods instead of using mutex and condvar?

Comment (cfzjywxk) [reply src/server/gc_worker/gc_manager.rs:519]: The current approach is simpler and easier to pick for the LTS version. Alternatively, an atomic variable can be used to avoid mutex, with periodic checks in `gc_a_round`.

Further refactoring could be left as a TODO task for GC restructuring. We could leave a TODO here.

**Review by MyonKeminta — APPROVED** [review]
