### PR TITLE
cdc: notify pending tasks if associated regions change

### LINKED ISSUE #15910: Number of snapshots  increases tremendously and TiKV OOM when resuming changefeed with a ts 6 days before.
### What version of TiKV are you using?
Release Version:   6.5.5                                       
Edition:           Community                                   
Git Commit Hash:   7f026c027741ef98204959c37e10a7de62934480    

### What operating system and CPU are you using?
K8S
/ # cat /etc/*-release                           
3.14.6                                           
NAME="Alpine Linux"                              
ID=alpine                                        
VERSION_ID=3.14.6                                
PRETTY_NAME="Alpine Linux v3.14"                 
HOME_URL="https://alpinelinux.org/"              
BUG_REPORT_URL="https://bugs.alpinelinux.org/"   

### Steps to reproduce
- TiDB GC is stopped for several days. (MVCC about 2TB, from 2.6T to 4.6T)
- There is a cdc changefeed running
- TiKV configuration cdc.incremental-fetch-speed-limit set to 128MiB
- Resume CDC changefeed and overwirte checkpoint ts with a ts 6 days before

### What did you expect?
TiKV not OOM

### What did happened?
Numbers of Snapshot increase tremendously to million level, and TiKV OOM is seen.
After pause cdc changefeed, snapshot number decreased as well
image
image

### PR DESCRIPTION
**Pull request by hicqu**
### What is changed and how it works?

Issue Number: Close #15910 

The problem is introduced in #15865 .

What's Changed:

```commit-message
```

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test

### Release note 

```release-note
None
```

### CODE REVIEW

File: components/cdc/src/initializer.rs [hunk 1]
```diff
@@ -110,9 +109,11 @@ impl<E: KvEngine> Initializer<E> {
         &mut self,
         change_observer: ChangeObserver,
         cdc_handle: T,
+        concurrency_semaphore: Arc<Semaphore>,
         memory_quota: Arc<MemoryQuota>,
     ) -> Result<()> {
         fail_point!("cdc_before_initialize");
+        let _permit = concurrency_semaphore.acquire().await;
```
Comment (pingyu) [inline components/cdc/src/initializer.rs:116]: Do we need to check the `self.downstream_state` after the semaphore is acquired.

File: components/cdc/src/observer.rs [hunk 2]
```diff
@@ -177,20 +177,23 @@ impl RegionChangeObserver for CdcObserver {
...
-                let store_err = RaftStoreError::RegionNotFound(region_id);
-                let deregister = Deregister::Delegate {
-                    region_id,
-                    observe_id,
-                    err: CdcError::request(store_err.into()),
-                };
-                if let Err(e) = self.sched.schedule(Task::Deregister(deregister)) {
-                    error!("cdc schedule cdc task failed"; "error" => ?e);
+        match event {
+            RegionChangeEvent::Destroy | RegionChangeEvent::Update(_) => {
```
Comment (pingyu) [inline components/cdc/src/observer.rs:181]: It seems that not all region update but just `Split` & `CommitMerge` are required to deregister.

Besided, shall we handle the event of role change (i.e. become follower from leader).

And I think it would be better to return more proper error (e.g. `EpochNotMatch` when split or merge happen).

File: components/cdc/src/initializer.rs (hunk 1 above)
Comment (hicqu) [reply components/cdc/src/initializer.rs:116]: It's unnecessary becasue we can always get the notification from the Observer.

File: components/cdc/src/observer.rs (hunk 2 above)
Comment (hicqu) [reply components/cdc/src/observer.rs]: Role changes are already handled in `on_role_change`. And here we can't know the correct `EpochNotMatch` information, so we can replace it with a `RegionNotFound`. For both 2 errors TiCDCs will retry them.

File: components/cdc/tests/failpoints/test_endpoint.rs [hunk 3]
```diff
@@ -569,3 +569,29 @@ fn test_cdc_stream_multiplexing() {
     }
     assert!(request_2_ready);
 }
+
+// This case tests pending regions can still get region split/merge
+// notifications.
+#[test]
+fn test_cdc_notifiy_pending_regions() {
```
Comment (pingyu) [inline components/cdc/tests/failpoints/test_endpoint.rs:576]:
```suggestion
fn test_cdc_notify_pending_regions() {
```

**Review by pingyu — APPROVED** [review]
LGTM~

**Review by overvenus — APPROVED** [review]
