### PR TITLE
tests: try to stabilize test_server_auto_adjust_replica

### LINKED ISSUE #3162: Test test_server_auto_adjust_replica failed
Backtrace: 

```
test raftstore_cases::test_conf_change::test_server_auto_adjust_replica ... thread 'raftstore_cases::test_conf_change::test_server_auto_adjust_replica' panicked at 'replica count 5 still not meet 4 after 10 secs', tests/raftstore_cases/test_conf_change.rs:288:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:207
   3: std::panicking::default_hook
             at libstd/panicking.rs:223
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:402
   5: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:349
   6: integrations::raftstore_cases::test_conf_change::wait_till_reach_count
             at tests/raftstore_cases/test_conf_change.rs:288
   7: integrations::raftstore_cases::test_conf_change::test_auto_adjust_replica
             at tests/raftstore_cases/test_conf_change.rs:344
   8: integrations::raftstore_cases::test_conf_change::test_server_auto_adjust_replica
             at tests/raftstore_cases/test_conf_change.rs:362
   9: integrations::__test::TESTS::{{closure}}
             at tests/raftstore_cases/test_conf_change.rs:359
  10: core::ops::function::FnOnce::call_once
             at /checkout/src/libcore/ops/function.rs:223
  11: <F as alloc::boxed::FnBox<A>>::call_box
             at libtest/lib.rs:1453
             at /checkout/src/libcore/ops/function.rs:223
             at /checkout/src/liballoc/boxed.rs:635
  12: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
FAILED
```

Link:  https://circleci.com/gh/overvenus/tikv/523

### PR DESCRIPTION
**Pull request by 5kbpers**
Signed-off-by: 5kbpers <tangminghua@pingcap.com>

### What problem does this PR solve?

Issue Number: close #3162 

Problem Summary:
`test_server_auto_adjust_replica` is not stable because of the replica count check.

### What is changed and how it works?

What's Changed:
Relax the check condition.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test

### Release note 
* N/A

### CODE REVIEW

**Comment by 5kbpers** [comment]
It could also fix https://github.com/tikv/tikv/issues/8358

File: components/test_raftstore/src/pd.rs [hunk 1]
```diff
@@ -562,7 +562,7 @@ impl Cluster {
                         .all(|x| x.get_store_id() != *store_id)
                     {
                         let peer = Either::Left(new_peer(*store_id, self.alloc_id().unwrap()));
-                        let policy = SchedulePolicy::Repeat(1);
+                        let policy = SchedulePolicy::TillSuccess;
```
Comment (BusyJay) [inline components/test_raftstore/src/pd.rs:565]: Why?

Comment (5kbpers) [reply components/test_raftstore/src/pd.rs:565]: Generally it will always be retried until success.

Comment (5kbpers) [reply components/test_raftstore/src/pd.rs:565]: And every retry will allocate a new peer id, which will be rejected by conf change proposal check.

Comment (BusyJay) [reply components/test_raftstore/src/pd.rs:565]: What if it can never succeed? For example, an old operator adds a peer on the store and occupy the store id with a different peer id.

**Review by BusyJay — APPROVED** [review]

**Review by NingLin-P — APPROVED** [review]

**Review by ti-srebot — APPROVED** [review]

**Review by gengliqi — APPROVED** [review]
