### PR TITLE
In-memory engine: consider mvcc suffix in prop test

### LINKED ISSUE #17456: In-memory engine: prop test failed
## Bug Report

The following test is generated by prop test and failed:
```
#[test]
fn test_case1() {
    let de = |data| {
        hex::decode(data).unwrap()
    };
    let cf = CF_WRITE;
    let operations = [
        Operation::Put(de("E2"), de("38CC98E09D9CB1D1")),
        Operation::DeleteRange(de("43AC4C5F7A16505B33EE3F"), de("E2")),
        Operation::Scan(de("2C0F698A"), 3),
    ];
    test_rocksdb_skiplist_basic_operations(cf, operations.to_vec());
}
```

The failed case was found by https://do.pingcap.net/jenkins/blue/organizations/jenkins/tikv%2Ftikv%2Fpull_unit_test/detail/pull_unit_test/1421/pipeline

### PR DESCRIPTION
**Pull request by SpadeA-Tang**
### What is changed and how it works?

Issue Number: Close #17456

What's Changed:

```commit-message
consider mvcc suffix in prop test
```

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [ ] Need to cherry-pick to the release branch

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note

```release-note
None
```

### CODE REVIEW

File: components/range_cache_memory_engine/src/prop_test.rs [hunk 1]
```diff
@@ -158,15 +161,27 @@ fn test_rocksdb_skiplist_basic_operations(cf: CfName, operations: Vec<Operation>
         (handle, key, value, guard)
     };
 
+    // Use data_key prefix here to avoid the special consider of  edge case(empty
```
Comment (overvenus) [inline components/range_cache_memory_engine/src/prop_test.rs:164]:
```suggestion
    // Use data_key prefix here to avoid the special consider of edge case(empty
```

Comment (overvenus) [reply components/range_cache_memory_engine/src/prop_test.rs:164]: Forget to add the data_key prefix "z"?

**Review by overvenus — COMMENTED** [review]
Rest LGTM

**Review by LykxSassinator — APPROVED** [review]

File: components/range_cache_memory_engine/src/prop_test.rs [hunk 2]
```diff
@@ -9,13 +9,16 @@ use engine_traits::{
...
 use tikv_util::config::{ReadableSize, VersionTrack};
+use txn_types::{Key, TimeStamp};
 
 use super::engine::SkiplistHandle;
 use crate::{
     decode_key, engine::SkiplistEngine, keys::encode_key, memory_controller::MemoryController,
     InternalBytes, RangeCacheEngineConfig,
 };
 
+const MVCC_SUFFIX: u64 = 10;
```
Comment (LykxSassinator) [inline components/range_cache_memory_engine/src/prop_test.rs:20]: It's better to add some necessary annotations here.

**Review by overvenus — APPROVED** [review]
