### PR TITLE
engine: calculate table properties correctly for Titan

### LINKED ISSUE #16319: Some table properties are incorrect if titan is enabled
### What version of TiKV are you using?
Master branch.

### What did happened?

If Titan is enabled, `PROP_MIN_TS` and `PROP_MAX_TS` may be wrong. If Titan is enabled on CF_WRITE, it may cause TiCDC lose some events.

### PR DESCRIPTION
**Pull request by hicqu**
### What is changed and how it works?

Issue Number: Close #16319 

What's Changed:

Calculate table properties correctly for Titan.

```commit-message

```

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [ ] Need to cherry-pick to the release branch

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note

```release-note
None
```

### CODE REVIEW

File: components/engine_rocks/src/properties.rs [hunk 1]
```diff
@@ -408,7 +408,10 @@ impl TablePropertiesCollector for MvccPropertiesCollector {
         // TsFilter filters sst based on max_ts and min_ts during iterating.
         // To prevent seeing outdated (GC) records, we should consider
         // RocksDB delete entry type.
-        if entry_type != DBEntryType::Put && entry_type != DBEntryType::Delete {
+        if entry_type != DBEntryType::Put
```
Comment (tonyxuqqi) [inline components/engine_rocks/src/properties.rs:411]: components/engine_rocks/src/ttl_properties.rs
Does this file need similar change?

File: components/cdc/src/initializer.rs [hunk 2]
```diff
@@ -1081,4 +1088,59 @@ mod tests {
...
+        let mut cfg = DbConfig::default();
+        cfg.titan.enabled = Some(true);
+        cfg.defaultcf.titan.blob_run_mode = BlobRunMode::Normal;
+        cfg.defaultcf.titan.min_blob_size = ReadableSize(0);
+        cfg.writecf.titan.blob_run_mode = BlobRunMode::Normal;
+        cfg.writecf.titan.min_blob_size = ReadableSize(0);
+        cfg.lockcf.titan.blob_run_mode = BlobRunMode::Normal;
+        cfg.lockcf.titan.min_blob_size = ReadableSize(0);
+        let mut engine = TestEngineBuilder::new()
+            .build_with_cfg(&cfg, false)
```
Comment (Connor1996) [inline components/cdc/src/initializer.rs:1103]: why disable block cache

File: components/engine_rocks/src/ttl_properties.rs [hunk 3]
```diff
@@ -74,6 +74,7 @@ pub struct TtlPropertiesCollector<F: KvFormat> {
 
 impl<F: KvFormat> TablePropertiesCollector for TtlPropertiesCollector<F> {
     fn add(&mut self, key: &[u8], value: &[u8], entry_type: DBEntryType, _: u64, _: u64) {
+        // DBEntryType::BlobIndex will be skit because we can't parse the value.
```
Comment (tonyxuqqi) [inline components/engine_rocks/src/ttl_properties.rs:77]: typo: skipped

Comment (Connor1996) [inline components/engine_rocks/src/ttl_properties.rs:77]:
```suggestion
        // DBEntryType::BlobIndex will be skipped because we can't parse the value.
```
How about add a check in config validation that ttl can't enabled with titan at the same time.

File: src/storage/kv/test_engine_builder.rs [hunk 4]
```diff
@@ -72,8 +72,12 @@ impl TestEngineBuilder {
         self.do_build(&cfg_rocksdb, true)
     }
 
-    pub fn build_with_cfg(self, cfg_rocksdb: &crate::config::DbConfig) -> Result<RocksEngine> {
-        self.do_build(cfg_rocksdb, true)
+    pub fn build_with_cfg(
+        self,
+        cfg_rocksdb: &crate::config::DbConfig,
+        enable_block_cache: bool,
```
Comment (Connor1996) [inline src/storage/kv/test_engine_builder.rs:78]: no need to change it, it's always true

File: components/cdc/src/initializer.rs [hunk 5]
```diff
@@ -1081,4 +1088,59 @@ mod tests {
 
         worker.stop();
     }
+
+    #[test]
+    fn test_scanner() {
```
Comment (Connor1996) [inline components/cdc/src/initializer.rs:1093]:
```suggestion
    fn test_scanner_with_titan() {
```

**Review by Connor1996 — APPROVED** [review]
rest LGTM
