### PR TITLE
encryption: fix offset inconsistency between crypter and file

### LINKED ISSUE #15080: encryption: encryption may corrupt data when partial write
### What version of TiKV are you using?
Current Master.

### What operating system and CPU are you using?
Linux, x86_64.

### Steps to reproduce

Apply the following patch (based on `a5f1a26d3bb5121a845f644b5eebff3d6c041278`):
<details><summary>Patch Content</summary>

```diff
+++ b/components/encryption/src/io.rs
@@ -525,6 +525,18 @@ mod tests {
         key
     }
 
+    struct Throttle<W>(W);
+
+    impl<W: Write> Write for Throttle<W> {
+        fn write(&mut self, buf: &[u8]) -> IoResult<usize> {
+            self.0.write(&buf[..2.min(buf.len())])
+        }
+
+        fn flush(&mut self) -> IoResult<()> {
+            Ok(())
+        }
+    }
+
     #[test]
     fn test_decrypt_encrypted_text() {
         let methods = [
@@ -557,10 +569,10 @@ mod tests {
                 let mut plaintext = vec![0; 1024];
                 OsRng.fill_bytes(&mut plaintext);
                 let buf = Vec::with_capacity(1024);
-                let mut encrypter = EncrypterWriter::new(buf, method, &key, iv).unwrap();
+                let mut encrypter = EncrypterWriter::new(Throttle(buf), method, &key, iv).unwrap();
                 encrypter.write_all(&plaintext).unwrap();
 
-                let buf = encrypter.finalize().unwrap();
+                let buf = encrypter.finalize().unwrap().0;
                 // Make sure it's properly encrypted.
                 if method != EncryptionMethod::Plaintext {
                     assert_ne!(buf, plaintext);
```

</details> 

Then, run the test case `test_decrypt_encrypted_text`.

### What did you expect?
The case should pass.

### What did happened?
```
---- io::tests::test_decrypt_encrypted_text stdout ----
thread 'io::tests::test_decrypt_encrypted_text' panicked at 'assertion failed: `(left == right)`
  left: `[122, 11, 30, 119, 4]`,
 right: `[122, 11, 66, 84, 249]`', components/encryption/src/io.rs:589:21
```

### PR DESCRIPTION
**Pull request by tabokie**
### What is changed and how it works?

Issue Number: Close #15080

What's Changed:

```commit-message
Fix offset inconsistency between crypter and file that could cause data corruption when file I/O is interrupted.
```

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

### Release note 

```release-note
Fix offset inconsistency between crypter and file that could cause data corruption when file I/O is interrupted.
```

### CODE REVIEW

File: components/encryption/src/io.rs [hunk 1]
```diff
@@ -334,7 +340,10 @@ impl<W: Write> Write for CrypterWriter<W> {
         if let Some(crypter) = self.crypter.as_mut() {
             let crypted = crypter.do_crypter(buf)?;
             debug_assert!(crypted.len() == buf.len());
-            self.writer.write(crypted)
+            let r = self.writer.write(crypted);
+            let missing = buf.len() - r.as_ref().unwrap_or(&0);
+            crypter.lazy_reset_crypter(crypter.offset - missing as u64);
```
Comment (YuJuncen) [inline components/encryption/src/io.rs:345]: A note here: Will we suffer really bad performance when the whole stream is long and the underlying writer writes a little bytes in each write? 

If we encrypt the whole buffer here each time, we may need to run AES-256 in `O(n^2)` bytes (if the openssl implementation doesn't cache the keystream), or do XOR with these bytes, at least.

But anyway this won't make things worse, and I have no idea about how to improve this.

**Review by YuJuncen — APPROVED** [review]
LGTM

File: components/encryption/src/io.rs (hunk 1 above)
Comment (tabokie) [reply components/encryption/src/io.rs:345]: Sure, but it should be rare. This could be improved by calling `write_all` instead of `write`. But it would be a violation of `Write` interface, and if there's an non-interrupt error, it causes the underlying file to enter "uncertain offset" state but we have not way to alert the user through the outer `write` interface.

File: components/encryption/src/io.rs [hunk 2]
```diff
@@ -470,18 +496,20 @@ impl CrypterCore {
             buf[encrypted..target].copy_from_slice(&self.buffer[..crypter_count]);
             encrypted += crypter_count;
         }
+        self.offset += count as u64;
```
Comment (tonyxuqqi) [inline components/encryption/src/io.rs:499]: question: Should self.offset be updated within while loop so that it can be recent 'encrypted' instead of 0, when it returns Err.

Comment (tabokie) [reply components/encryption/src/io.rs:499]: The offset here is used to kept track of file writer offset, not the crypter internal offset. When file writer finishes writing a chunk of data, crypter must encrypt it atomically.

**Review by tonyxuqqi — APPROVED** [review]
