### PR TITLE
backup-stream: clean the `pause-guard-gc-safepoint` when unregister the log task

### LINKED ISSUE #17316: pitr: store level safepoint not cleaned
### What version of TiKV are you using?

n/a

### What operating system and CPU are you using?

n/a

### Steps to reproduce

1. run pitr log backup, but the log backup failed and the task falls into pause status
2. stop pitr task instead of resume pit task 

### What did you expect?
no pitr related safepoints left in pd

### What did happened?
store level safetpoint left, here is an example
`    {
      "service_id": "longrun-pitr-test-06-21-pause-guard",
      "expired_at": 1720548006,
      "safe_point": 451008561534992909
    }`

### PR DESCRIPTION
**Pull request by Leavrth**
### What is changed and how it works?

Issue Number: Close #17316

What's Changed:

```commit-message
clean `pause-guard-gc-safepoint` when unregister the log task
```

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [ ] Need to cherry-pick to the release branch

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)

fatal by some error:
```
$ tiup ctl:nightly pd -u 127.0.0.1:35863 service-gc-safepoint                                
Starting component ctl: /root/.tiup/components/ctl/v8.3.0-alpha-nightly/ctl pd -u 127.0.0.1:35863 service-gc-safepoint
{
  "service_gc_safe_points": [
    {
      "service_id": "gc_worker",
      "expired_at": 9223372036854775807,
      "safe_point": 451470694268010496
    },
    {
      "service_id": "backup-stream-pitr-1",    --> flush gc safepoint
      "expired_at": 1722231754,
      "safe_point": 451470794866032641
    },
    {
      "service_id": "backup-stream-pitr-4",
      "expired_at": 1722231755,
      "safe_point": 451470794866032641
    },
    {
      "service_id": "backup-stream-pitr-5",
      "expired_at": 1722231755,
      "safe_point": 451470794866032641
    },
    {
      "service_id": "br-3cde8853-fe32-43af-97dc-9476accb4da5",     --> log start gc safepoint
      "expired_at": 1722226206,
      "safe_point": 451470794866032641
    },
    {
      "service_id": "pitr-1-pause-guard",   --> fatal gc safepoint
      "expired_at": 1722311036,
      "safe_point": 451470833741987840
    },
    {
      "service_id": "pitr-4-pause-guard",
      "expired_at": 1722311036,
      "safe_point": 451470833741987840
    },
    {
      "service_id": "pitr-5-pause-guard",
      "expired_at": 1722311036,
      "safe_point": 451470833741987840
    }
  ],
  "min_service_gc_safe_point": 451470694268010496,
  "gc_safe_point": 0
}
```

after remove the task
```
$ tiup ctl:nightly pd -u 127.0.0.1:35863 service-gc-safepoint
Starting component ctl: /root/.tiup/components/ctl/v8.3.0-alpha-nightly/ctl pd -u 127.0.0.1:35863 service-gc-safepoint
{
  "service_gc_safe_points": [
    {
      "service_id": "gc_worker",
      "expired_at": 9223372036854775807,
      "safe_point": 451470694268010496
    },
    {
      "service_id": "backup-stream-pitr-1",
      "expired_at": 1722231754,
      "safe_point": 451470794866032641
    },
    {
      "service_id": "backup-stream-pitr-4",
      "expired_at": 1722231755,
      "safe_point": 451470794866032641
    },
    {
      "service_id": "backup-stream-pitr-5",
      "expired_at": 1722231755,
      "safe_point": 451470794866032641
    },
    {
      "service_id": "br-3cde8853-fe32-43af-97dc-9476accb4da5",
      "expired_at": 1722226206,
      "safe_point": 451470794866032641
    }
  ],
  "min_service_gc_safe_point": 451470694268010496,
  "gc_safe_point": 0
}
```

- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note

```release-note
clean `pause-guard-gc-safepoint` when unregister the log task
```

### CODE REVIEW

File: components/backup-stream/src/endpoint.rs [hunk 1]
```diff
@@ -742,6 +731,21 @@ where
         metrics::update_task_status(TaskStatus::Running, &task_name);
     }
 
+    // clean the safepoint created at pause(if there is)
+    fn clean_pause_guard_id_for_task(&self, task_name: &str) {
+        self.pool.spawn(root!("unregister_task";
```
Comment (3pointer) [inline components/backup-stream/src/endpoint.rs:736]: both load/unload_task will invoke this function. so consider another proper name for it?

Comment (Leavrth) [reply components/backup-stream/src/endpoint.rs:736]: `pause_task` also calls the function `unload_task`. I wonder if it should also remove the pause guard too? I think it is so that the new function `clean_pause_guard_id_for_task` can be called in `unload_task` instead of `unregister_task`.

Comment (Leavrth) [reply components/backup-stream/src/endpoint.rs:736]: set gcsafepoint need to handle the error `pd_client::Error::UnsafeServiceGcSafePoint` if gc safe point exceeds the task checkpoint.

Comment (Leavrth) [reply components/backup-stream/src/endpoint.rs:736]: Maybe we need to drop the gc safepoint in BR to remove the scaled-in TiKV gc safepoint.

**Review by YuJuncen — APPROVED** [review]

**Review by 3pointer — APPROVED** [review]
