### PR TITLE
test: enhance unstable test test_pool_available_deadline

### LINKED ISSUE #16442: flaky test:  storage::txn::scheduler::tests::test_pool_available_deadline – tikv
https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/42028/tests

Stacktrace
thread 'storage::txn::scheduler::tests::test_pool_available_deadline' panicked at 'assertion failed: matches!(block_on(f).unwrap(),\n    Err(StorageError(box StorageErrorInner :: DeadlineExceeded)))', src/storage/txn/scheduler.rs:2088:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/core/src/panicking.rs:65:14
   2: core::panicking::panic
             at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/core/src/panicking.rs:114:5
   3: tikv::storage::txn::scheduler::tests::test_pool_available_deadline
   4: tikv::storage::txn::scheduler::tests::test_pool_available_deadline::{{closure}}
   5: core::ops::function::FnOnce::call_once
   6: core::ops::function::FnOnce::call_once
             at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/core/src/ops/function.rs:513:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Standard Output
running 1 test
test storage::txn::scheduler::tests::test_pool_available_deadline ... FAILED
failures:
failures:
    storage::txn::scheduler::tests::test_pool_available_deadline
test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 490 filtered out; finished in 0.60s
Standard Error
thread 'storage::txn::scheduler::tests::test_pool_available_deadline' panicked at 'assertion failed: matches!(block_on(f).unwrap(),\n    Err(StorageError(box StorageErrorInner :: DeadlineExceeded)))', src/storage/txn/scheduler.rs:2088:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/core/src/panicking.rs:65:14
   2: core::panicking::panic
             at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/core/src/panicking.rs:114:5
   3: tikv::storage::txn::scheduler::tests::test_pool_available_deadline
   4: tikv::storage::txn::scheduler::tests::test_pool_available_deadline::{{closure}}
   5: core::ops::function::FnOnce::call_once
   6: core::ops::function::FnOnce::call_once
             at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/core/src/ops/function.rs:513:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

### PR DESCRIPTION
**Pull request by glorv**
### What is changed and how it works?

Issue Number: Close #16442

What's Changed:

```commit-message
Enhance unstable test test_pool_available_deadline.

The original logica has 2 factors that makes it not stable:
- Thread scheduling. If the 2nd cmd is scheduled 500ms later than the 1st cmd, then the 2nd task won't meet deadline error.
- Threadpool thread count. The yatp's active thread count is not always ensured, it only ensure that within finite duration, the active thread count will reach the target number. Thus if the 2nd thread is scheduled when there are more than 1 active threads, it won't meet deadline error.

I found there is no easy way to ensure that the active thread number is 1 so just let the cmd timeout before it is scheduled to always trigger the deadline error.
```

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [ ] Need to cherry-pick to the release branch

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note

```release-note
None
```

### CODE REVIEW

File: src/storage/txn/scheduler.rs [hunk 1]
```diff
@@ -2307,24 +2307,18 @@ mod tests {
...
-            })
-            .unwrap();
-
         let mut req = BatchRollbackRequest::default();
         req.mut_context().max_execution_duration_ms = 100;
         req.set_keys(vec![b"a".to_vec(), b"b".to_vec(), b"c".to_vec()].into());
-
         let cmd: TypedCommand<()> = req.into();
+
+        // wait to let the cmd timeout.
```
Comment (LykxSassinator) [inline src/storage/txn/scheduler.rs:2315]:
```suggestion
        // Wait enough time to let the cmd timeout.
```

File: src/storage/txn/scheduler.rs [hunk 2]
```diff
@@ -2307,24 +2307,18 @@ mod tests {
...
+        std::thread::sleep(Duration::from_millis(120));
+
         let (cb, f) = paired_future_callback();
         scheduler.run_cmd(cmd.cmd, StorageCallback::Boolean(cb));
 
-        // But the max execution duration is 100ms, so the deadline is exceeded.
+        // the max execution duration is 100ms, so the deadline is exceeded.
```
Comment (LykxSassinator) [inline src/storage/txn/scheduler.rs:2321]:
```suggestion
        // The max execution duration is 100ms, so the deadline is exceeded.
```

**Review by LykxSassinator — APPROVED** [review]
Rest LGTM

**Review by overvenus — APPROVED** [review]
