### PR TITLE
raftstore: warm up IME before transferring leadership

### LINKED ISSUE #17782: [In-memory-engine] qps and latency jitter amplitude is larger when enable IME due to transfer leader
### What version of TiKV are you using?
TiKV
Release Version: 8.5.0-alpha
Edition: Community
Git Commit Hash: https://github.com/tikv/tikv/commit/d01bd7483aab212a6de36b2c4a2fe60930a1aa00
Git Commit Branch: heads/refs/tags/v8.5.0-alpha
UTC Build Time: 2024-11-03 11:37:49
Rust Version: rustc 1.77.0-nightly (89e2160c4 2023-12-27)
Enable Features: memory-engine pprof-fp jemalloc mem-profiling portable sse test-engine-kv-rocksdb test-engine-raft-raft-engine trace-async-tasks openssl-vendored
Profile: dist_release

### What operating system and CPU are you using?
8c/32g

### Steps to reproduce
[in-memory-engine]
enable = true
gc-run-interval = "2m"
capacity = "12GB"
evict-threshold = "10GB"
stop-load-threshold = "9GB"
mvcc-amplification-threshold = 5
cross-check-interval = "30s"

1、run sysbench databricks
./prepare.sh -h tc-tidb.glh-knhqn -u root -r 4000 -t 64 -w 2000 -d 0 -j 10000 -m true
./many_delete_mvcc.sh -h tc-tidb.glh-knhqn -u root -r 4000 -t 64 -w 2000 -j 10000 -s 10 -e 7200

### What did happened?
bdcf14c3-fcba-4c89-aaff-98ae420c1f35

another phenomenon
1、run mvcc select only，latency jitter
--db-driver=mysql --mysql-db=jobs --mysql-port=4000 --threads=16 --number_workspaces=5000 --jobs_per_org=50000 --many_mvcc_select_percentage=100 --separate_read_write=false --read_only=true --time=0  --mysql-user=root --mysql-ignore-errors=all --report-interval=10  many_delete_mvcc.lua

Image

### PR DESCRIPTION
**Pull request by overvenus**
### What is changed and how it works?

Issue Number: Close #17782 

Touch #17433

What's Changed:

```commit-message
This PR introduces a coprocessor hook before leadership transfer
acknowledgement. Ensures followers have completely warmed up their IME
cache before accepting leadership.

Tests show the change significantly improves 99.9 percentile of 
TiDB Query Duration (from ~4s to ~0.7s) when the cache regions are 
transferred frequently.
```

### Related changes

- Need to cherry-pick to the release branch

### Check List

Tests 

- Integration test
- Manual test (add detailed scripts or steps below)

Left: This PR vs Right: Master
image

### Release note

```release-note
Warmup IME before leader transfer to improves 99.9 percentile of TiDB Query Duration
```

### CODE REVIEW

File: components/raftstore/src/store/fsm/peer.rs [hunk 1]
```diff
@@ -3109,9 +3109,6 @@ where
     }
 
     fn on_extra_message(&mut self, mut msg: RaftMessage) {
-        self.ctx
```
Comment (Connor1996) [inline components/raftstore/src/store/fsm/peer.rs:3112]: Why remove this

File: components/hybrid_engine/src/observer/load_eviction.rs [hunk 2]
```diff
@@ -242,18 +248,83 @@ impl AdminObserver for LoadEvictionObserver {
...
+
+        // Exclude loading states to make sure the region is active.
+        let active_only = true;
+        let has_cached = self.cache_engine.region_cached(r.region(), active_only);
+        if has_cached {
+            // Ready to ack.
+            return true;
+        }
+
+        self.cache_engine.load_region(r.region());
```
Comment (Connor1996) [inline components/hybrid_engine/src/observer/load_eviction.rs:326]: This triggers loading only when the ticker ticks, can we make it more actively?

File: components/hybrid_engine/src/observer/load_eviction.rs [hunk 3]
```diff
@@ -242,18 +248,83 @@ impl AdminObserver for LoadEvictionObserver {
...
+        }
+
+        let region = r.region();
+        let context = msg.get_context();
+        let ty = match get_value(context) {
+            Ok(Some(ty)) => ty,
+            other => {
+                // For compatibility, return ready if the context is not found
+                // or invalid.
+                info!("ime transfer leader context not found";
```
Comment (LykxSassinator) [inline components/hybrid_engine/src/observer/load_eviction.rs:297]:
```suggestion
                info!("ignored as ime transfer leader context not found";
```

**Review by LykxSassinator — COMMENTED** [review]
overall LGTM

File: components/hybrid_engine/src/observer/load_eviction.rs (hunk 2 above)
Comment (overvenus) [reply components/hybrid_engine/src/observer/load_eviction.rs:328]: The loading is initiated[^1] when a peer receives a MsgTransferLeader and a transferee checks the result on every tick.

[^1]: https://github.com/overvenus/tikv/blob/2009bf4dd16bbdd50a91f7ecf76bf827d79a437c/components/raftstore/src/store/peer.rs#L4834

**Review by glorv — APPROVED** [review]
