### PR TITLE
raftstore: gc abnormal snapshots and destroy peer if failed to apply snapshots.

### LINKED ISSUE #15292: tikv panic repeatedly after this tikv recover from io hang
### What version of TiKV are you using?
[2023/08/07 18:32:41.764 +08:00] [INFO] [lib.rs:88] ["Welcome to TiKV"]
[2023/08/07 18:32:41.765 +08:00] [INFO] [lib.rs:93] ["Release Version:   7.4.0-alpha"]
[2023/08/07 18:32:41.765 +08:00] [INFO] [lib.rs:93] ["Edition:           Community"]
[2023/08/07 18:32:41.765 +08:00] [INFO] [lib.rs:93] ["Git Commit Hash:   1e47e9a2a987127a2371457d2c1379d62a54de11"]
[2023/08/07 18:32:41.765 +08:00] [INFO] [lib.rs:93] ["Git Commit Branch: heads/refs/tags/v7.4.0-alpha"]
[2023/08/07 18:32:41.765 +08:00] [INFO] [lib.rs:93] ["UTC Build Time:    Unknown (env var does not exist when building)"]
[2023/08/07 18:32:41.765 +08:00] [INFO] [lib.rs:93] ["Rust Version:      rustc 1.67.0-nightly (96ddd32c4 2022-11-14)"]
[2023/08/07 18:32:41.765 +08:00] [INFO] [lib.rs:93] ["Enable Features:   pprof-fp jemallo

### What operating system and CPU are you using?
8c/32g

### Steps to reproduce
1、run tpcc with 1000 warehouse and 10 thread
2、inject one of tikv io hang last for 20m

### What did you expect?
no panic

### What did happened?
tikv panic repeatedly after this tikv recover from io hang

[2023/08/07 18:32:36.398 +08:00] [FATAL] [lib.rs:510] ["[region 11581] 11584 applying snapshot failed"] [backtrace="   0: tikv_util::set_panic_hook::{{closure}}\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/tikv_util/src/lib.rs:509:18\n   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2032:9\n      std::panicking::rust_panic_with_hook\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:692:13\n   2: std::panicking::begin_panic_handler::{{closure}}\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:579:13\n   3: std::sys_common::backtrace::__rust_end_short_backtrace\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:137:18\n   4: rust_begin_unwind\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:575:5\n   5: core::panicking::panic_fmt\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panicking.rs:65:14\n   6: raftstore::store::peer_storage::PeerStorage<EK,ER>::check_applying_snap\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/peer_storage.rs:797:21\n   7: raftstore::store::peer::Peer<EK,ER>::check_snap_status\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/peer.rs:2305:15\n      raftstore::store::peer::Peer<EK,ER>::handle_raft_ready_append\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/peer.rs:2425:13\n   8: raftstore::store::fsm::peer::PeerFsmDelegate<EK,ER,T>::collect_ready\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/fsm/peer.rs:1998:19\n      <raftstore::store::fsm::store::RaftPoller<EK,ER,T> as batch_system::batch::PollHandler<raftstore::store::fsm::peer::PeerFsm<EK,ER>,raftstore::store::fsm::store::StoreFsm<EK>>>::handle_normal\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/fsm/store.rs:1023:13\n   9: batch_system::batch::Poller<N,C,Handler>::poll\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/batch-system/src/batch.rs:380:27\n  10: batch_system::batch::BatchSystem<N,C>::start_poller::{{closure}}\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/batch-system/src/batch.rs:550:17\n      <std::thread::Builder as tikv_util::sys::thread::StdThreadBuildWrapper>::spawn_wrapper::{{closure}}\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/tikv_util/src/sys/thread.rs:438:13\n      std::sys_common::backtrace::__rust_begin_short_backtrace\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:121:18\n  11: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:551:17\n      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panic/unwind_safe.rs:271:9\n      std::panicking::try::do_call\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:483:40\n      std::panicking::try\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:447:19\n      std::panic::catch_unwind\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:137:14\n      std::thread::Builder::spawn_unchecked_::{{closure}}\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:550:30\n      core::ops::function::FnOnce::call_once{{vtable.shim}}\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:513:5\n  12: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2000:9\n      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2000:9\n      std::sys::unix::thread::Thread::new::thread_start\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys/unix/thread.rs:108:17\n  13: start_thread\n  14: __clone\n"] [location=/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/peer_storage.rs:797] [thread_name=raftstore-18-0]
[2023/08/07 18:32:41.764 +08:00] [INFO] [lib.rs:88] ["Welcome to TiKV"]

### PR DESCRIPTION
**Pull request by LykxSassinator**
### What is changed and how it works?

Issue Number: Close #15292

What's Changed:

Previously, there were pending tasks to address the scenario where TiKV would panic if applying snapshots failed due to abnormal conditions such as IO errors or unexpected issues.

This pull request resolves the issue by introducing additional traits `tombstone: bool` to `SnapshotApplied`, indicating whether the failure occurred due to abnormal snapshots.
Additionally, the region_id of the abnormal peer will be recorded into the newly added `StoreMeta::damaged_regions`, used to remove the associated peer.
Finally, this peer will be destroyed later through the StoreHeartbeat to PD, which will create a `remove peer` operator to remove the peer safely.

```commit-message
Replace `SnapshotApplied` with `SnapshotApplied { peer_id: u64, tombstone: bool}`. And if `tombstone` == true, the
relative peer will be automatically GCed.
```

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [ ] Need to cherry-pick to the release branch

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note

```release-note
None.
```

### CODE REVIEW

**Comment by glorv** [comment]
I have 2 questions about this PR:
1. Is it possible to directly retry applying the snapshot if the failure is caused by unexpected(maybe some IO layer) error?
2. Why need to tombstone the peer after applying snapshot failed? Why not just switch the peer status to normal and so the leader should start a new snapshot automatically.

**Comment by LykxSassinator** [comment]
> I have 2 questions about this PR:
> 
> 1. Is it possible to directly retry applying the snapshot if the failure is caused by unexpected(maybe some IO layer) error?
> 2. Why need to tombstone the peer after applying snapshot failed? Why not just switch the peer status to normal and so the leader should start a new snapshot automatically.

1. Nope, it's caused by loading abnormal blocks. According to the logs in the issue https://github.com/tikv/tikv/issues/15292 and https://github.com/tikv/tikv/issues/16958, it shows that the given snapshot has abnormal file blocks, causing the failure of the applying.
2. For safety. Tombstone the peer and destroy it will assure that this TiKV node do not have any other remains data / meta data about this peer.

**Comment by LykxSassinator** [comment]
By the way, as for the point 2, I agree what u mentioned before. But for safety, this pr takes current implementation.

> Why not just switch the peer status to normal and so the leader should start a new snapshot automatically.

I'll have a try for the `point 2` u mentioned and do some extra tests on it to make comparisons.

**Comment by overvenus** [comment]
I don't think we can directly mark it as `Tombstone` or `Normal`, because both options violate the current raft state machine protocol.
* `Tombstone` indicates that the peer has been fully removed, including its Raft membership and data. However, in this case, the peer remains a valid member.
* `Normal` means that the peer has all data up to its last commit index. But, in this case, it does not, as its last commit index has been updated to the snapshot index.

---

There are two ways to fix the panic:

1. Have PD remove this peer via a confchange, which I believe is the simplest solution.
2. Introduce a new RPC to instruct the leader to resend the snapshot, which may change lots of code.

**Comment by glorv** [comment]
> Introduce a new RPC to instruct the leader to resend the snapshot, which may change lots of code.

Why need this extra RPC? At the leader side, it will switch the peer's state to normal after finishing send the snapshot. At the follower side, when apply snapshot failed, it is also doable to restore the raft state to its previous state before this snapshot. Thus, If I understand correctly, the leader should start another snapshot without any extra operation?

**Comment by overvenus** [comment]
> At the follower side, when apply snapshot failed, it is also doable to restore the raft state to its previous state before this snapshot. 

Do you mean persist the previous state? So it can be restored even after restart TiKV?

That's doable (without a new RPC), but still it adds extra logical to raftstore.

**Comment by glorv** [comment]
> Do you mean persisting the previous state so it can be restored even after restarting TiKV?

Yes. But I think just update the peer's state to its previous status should be simpler that tombstone or let pd remove this peer and later add it back.

**Comment by LykxSassinator** [comment]
> > Do you mean persisting the previous state so it can be restored even after restarting TiKV?
> 
> Yes. But I think just update the peer's state to its previous status should be simpler than tombstone or let pd remove this peer and later add it back.

Correct me if I'm wrong, but I think that removing the peer and making PD add one fresh peer sounds valid ? As the peer, which panics due to loading the abnormal snapshot, has already advanced its `persisted_index` and `committed_index`, rolling back the persisted state of this peer will violate rules of raft protocol. Right ?

**Comment by glorv** [comment]
> Correct me if I'm wrong, but I think that removing the peer and making PD add one fresh peer sounds valid ? As the peer, which panics due to loading the abnormal snapshot, has already advanced its `persisted_index` and `committed_index`, rolling back the persisted state of this peer to a previous one will violate rules of raft protocol. Right ?

You are right, the raft state is reset to the snapshot's state when receives the snapshot msg, so it not easy to revert to the previous state. And makes the raft state revert may cause other side-effects. 

Thus, if it's doable, I prefer the current idea to just destroy the current peer and let newer raft message to trigger create it automatically.

**Comment by glorv** [comment]
@LykxSassinator  from https://github.com/tikv/tikv/blob/06eed732641ad47aec44dd58aa3d64e18c1c5ee8/components/raftstore/src/store/fsm/store.rs#L2114-L2130

It seems after tombstoning the peer, the region will drop all following raft messages, thus the peer won't be recovered automatically.

**Comment by LykxSassinator** [comment]
> @LykxSassinator from
> 
> https://github.com/tikv/tikv/blob/06eed732641ad47aec44dd58aa3d64e18c1c5ee8/components/raftstore/src/store/fsm/store.rs#L2114-L2130
> 
> It seems after tombstoning the peer, the region will drop all following raft messages, thus the peer won't be recovered automatically.

Yes, thank you for the reminder. It seems that we may need to utilize `ConfChange` for this task.
Anyway, I will investigate further, and this pull request will be put on hold until the necessary changes are implemented and ready for review.

File: components/raftstore/src/store/worker/region.rs [hunk 1]
```diff
@@ -535,18 +539,46 @@ where
...
+                false
             }
             Err(e) => {
-                error!(%e; "failed to apply snap!!!");
+                warn!("failed to apply snap!!!"; "region_id" => region_id, "err" => %e);
+                self.coprocessor_host
+                    .cancel_apply_snapshot(region_id, peer_id);
                 status.swap(JOB_STATUS_FAILED, Ordering::SeqCst);
                 SNAP_COUNTER.apply.fail.inc();
+                // As the snapshot failed, it should be cleared and the related peer should be
```
Comment (Connor1996) [inline components/raftstore/src/store/worker/region.rs:551]: Why not handle it when `JOB_STATUS_FAILED` in `check_applying_snap`

File: components/raftstore/src/store/fsm/peer.rs [hunk 2]
```diff
@@ -1259,9 +1259,18 @@ where
...
             }
-            CasualMessage::SnapshotApplied => {
+            CasualMessage::SnapshotApplied { peer_id, tombstone } => {
                 self.fsm.has_ready = true;
-                if self.fsm.peer.should_destroy_after_apply_snapshot() {
+                let apply_snap_failed =
+                    tombstone && self.fsm.peer.peer_id() == peer_id && !self.fsm.peer.is_leader();
+                if apply_snap_failed {
+                    // Send ConfChange to the leader to make the region tombstone the peer.
+                    self.fsm.peer.send_tombstone_peer_msg(self.ctx);
```
[the remark this answers is not in the document]
Comment (LykxSassinator) [reply components/raftstore/src/store/fsm/peer.rs:1268]: Make senses. The absence of messages can result in abnormal peer residue on this node.

Let me dive deeper in it.

**Comment by hbisheng** [comment]
Out of curiosity and just trying to learn, what are the typical scenarios where applying snapshots may fail? In those cases, would it help if we retry a few times? If we destroy the peer and add a new one, it's possible that the new peer may hit the same issue again, right?

**Comment by LykxSassinator** [comment]
> Out of curiosity and just trying to learn, what are the typical scenarios where applying snapshots may fail? In those cases, would it help if we retry a few times? If we destroy the peer and add a new one, it's possible that the new peer may hit the same issue again, right?

Yep. One typical case is that loading snapshots encounters IO errors. In this case, the issue can be attributed to physical errors on the disk or system errors.
And as for whether the retrying is success or not, it depends on the root cause of the IO error. If it's due to physical errors on the disk, retries may not always be successful. But if it's a system error, retries may have a higher chance of success.

File: components/raftstore/src/store/fsm/peer.rs [hunk 3]
```diff
@@ -3003,11 +3045,7 @@ where
                 self.on_voter_replicated_index_response(msg.get_extra_msg());
             }
             ExtraMessageType::MsgGcPeerRequest => {
```
Comment (overvenus) [inline components/raftstore/src/store/fsm/peer.rs:3047]: This message is only used by the 'CheckGcPeer' protocol in raftstorev2. I prefer not to mix them up, as raftstorev2 is not actively being developed and adding this would increase complexity.

Comment (LykxSassinator) [reply components/raftstore/src/store/fsm/peer.rs:3047]: Agree, it also troubles me a lot. 

Meanwhile, Implementing a retry mechanism seems necessary in case messages are unexpectedly lost

File: Cargo.toml [hunk 4]
```diff
@@ -244,6 +244,8 @@ procinfo = { git = "https://github.com/tikv/procinfo-rs", rev = "7693954bd1dd86e
 # After the PR to rust-rocksdb is merged, remember to comment this out and run `cargo update -p rocksdb`.
 # [patch.'https://github.com/tikv/rust-rocksdb']
 # rocksdb = { git = "https://github.com/your_github_id/rust-rocksdb", branch = "your_branch" }
+[patch.'https://github.com/pingcap/kvproto']
+kvproto = { git = "https://github.com/LykxSassinator/kvproto", branch = "tombstone_peer" }
```
Comment (LykxSassinator) [inline Cargo.toml:248]: Will be updated with latest if this pr is approved.

File: deny.toml [hunk 5]
```diff
@@ -99,3 +99,7 @@ exceptions = [
 unknown-git = "deny"
 unknown-registry = "deny"
 allow-org = { github = ["tikv", "pingcap", "rust-lang"] }
+# Allow list.
+allow-git = [
```
Comment (LykxSassinator) [inline deny.toml:103]: Will be cleared when this pr is approved.

File: components/raftstore/src/store/peer_storage.rs [hunk 6]
```diff
@@ -795,8 +795,9 @@ where
                 } else if s == JOB_STATUS_CANCELLED {
                     SnapState::ApplyAborted
                 } else if s == JOB_STATUS_FAILED {
-                    // TODO: cleanup region and treat it as tombstone.
-                    panic!("{} applying snapshot failed", self.tag,);
+                    // Cleanup region and treat it as tombstone.
+                    warn!("{} applying snapshot failed", self.tag,);
```
Comment (Connor1996) [inline components/raftstore/src/store/peer_storage.rs:799]:
```suggestion
                    warn!("{} applying snapshot failed", self.tag);
```

File: components/raftstore/src/store/fsm/peer.rs [hunk 7]
```diff
@@ -3009,6 +3051,9 @@ where
                     self.on_gc_peer_request(msg);
                 }
             }
+            ExtraMessageType::MsgTombstonePeerRequest => {
```
Comment (Connor1996) [inline components/raftstore/src/store/fsm/peer.rs:3054]: Tombstone is ambiguous, it actually does remove peer

File: components/raftstore/src/store/fsm/peer.rs [hunk 8]
```diff
@@ -1259,9 +1259,16 @@ where
                 let raft_msg = self.fsm.peer.build_raft_messages(self.ctx, vec![msg]);
                 self.fsm.peer.send_raft_messages(self.ctx, raft_msg);
             }
-            CasualMessage::SnapshotApplied => {
+            CasualMessage::SnapshotApplied { peer_id, tombstone } => {
                 self.fsm.has_ready = true;
+                // If failed on applying snapshot, it should tomebstone the peer.
+                self.fsm.peer.should_tombstone =
```
[the remark this answers is not in the document]
Comment (LykxSassinator) [reply components/raftstore/src/store/fsm/peer.rs:1265]: To prevent the loss of messages in case of sending failures due to unexpected issues.
The flag `should_tombstone` is used to ensure that the abnormal peer continues to send the TombStone message to the leader until it is removed from the raft group.

File: components/raftstore/src/store/fsm/peer.rs (hunk 7 above)
Comment (LykxSassinator) [reply components/raftstore/src/store/fsm/peer.rs:3054]: How about `MsgForcelyRemovePeerRequest` ?

Comment (Connor1996) [reply components/raftstore/src/store/fsm/peer.rs:3071]: lgtm

File: components/raftstore/src/store/fsm/peer.rs [hunk 9]
```diff
@@ -2255,6 +2262,11 @@ where
         // the pending conf change check because first index has been updated to
         // a value that is larger than last index.
         if self.fsm.peer.is_handling_snapshot() || self.fsm.peer.has_pending_snapshot() {
+            // If failed on applying snapshot, send ConfChange to the leader to make the
+            // region tombstone the peer.
+            if self.fsm.peer.should_tombstone {
+                self.fsm.peer.send_tombstone_peer_msg(self.ctx);
```
Comment (Connor1996) [inline components/raftstore/src/store/fsm/peer.rs:2268]: how to avoid sending too many msgs?

File: components/raftstore/src/store/fsm/peer.rs (hunk 8 above)
[the remark this answers is not in the document]
Comment (Connor1996) [reply components/raftstore/src/store/fsm/peer.rs:1265]: still can send it here

File: components/raftstore/src/store/fsm/peer.rs [hunk 10]
```diff
@@ -2830,11 +2842,24 @@ where
         self.fsm.hibernate_state.count_vote(from.get_id());
     }
 
-    fn on_availability_response(&mut self, from: &metapb::Peer, msg: &ExtraMessage) {
+    fn on_availability_response(&mut self, msg: RaftMessage) {
```
Comment (Connor1996) [inline components/raftstore/src/store/fsm/peer.rs:2845]: As it's only used by witness, I don't suggest to change it

Comment (LykxSassinator) [reply components/raftstore/src/store/fsm/peer.rs]: Yep, that's right. It was reverted.

Comment (LykxSassinator) [reply components/raftstore/src/store/fsm/peer.rs]: And the abnormal peer will be cleared by the responding message with the `RaftMessage::is_tombstone` == true.

File: components/raftstore/src/store/fsm/peer.rs (hunk 8 above)
[the remark this answers is not in the document]
Comment (LykxSassinator) [reply components/raftstore/src/store/fsm/peer.rs:1265]: FYI, the abnormal peer will stop sending messages once it is destroyed, which is triggered by receiving a `RaftMessage` with the flag `RaftMessage::is_tombstone` set to true.

**Comment by LykxSassinator** [comment]
This pr needs extra support from PD side to make the implementation more valid.

Hold until  https://github.com/tikv/pd/pull/8266 is merged.

**Review by Connor1996 — COMMENTED** [review]
Please remove this logic for backward compatibility as we can handle abnormal snapshots now
image

File: components/raftstore/src/store/fsm/peer.rs [hunk 11]
```diff
@@ -3906,6 +3916,7 @@ where
             );
         })();
         let mut meta = self.ctx.store_meta.lock().unwrap();
+        meta.damaged_regions.remove(&self.fsm.region_id());
```
Comment (overvenus) [inline components/raftstore/src/store/fsm/peer.rs:3919]: Please shrink its capacity to free memory.

File: tests/failpoints/cases/test_pending_peers.rs [hunk 12]
```diff
@@ -225,3 +225,37 @@ fn test_on_check_busy_on_apply_peers() {
...
+    pd_client.must_add_peer(region_id, new_peer(2, 2));
+
+    // To ensure peer 2 is not pending.
+    cluster.must_put(b"k1", b"v1");
+    must_get_equal(&cluster.get_engine(2), b"k1", b"v1");
+
+    // Mock applying snapshot failed on peer 3.
+    fail::cfg("region_apply_snap_io_err", "return").unwrap();
+    pd_client.must_add_peer(region_id, new_peer(3, 3));
+    sleep_ms(1000);
```
Comment (overvenus) [inline tests/failpoints/cases/test_pending_peers.rs:250]: Why sleep 1s? Will it be a flakey test?

**Review by overvenus — COMMENTED** [review]
Rest LGTM

File: tests/failpoints/cases/test_pending_peers.rs (hunk 12 above)
Comment (LykxSassinator) [reply tests/failpoints/cases/test_pending_peers.rs]: Just one store_heartbeat interval is enough to update meta.

File: tests/failpoints/cases/test_pending_peers.rs [hunk 13]
```diff
@@ -225,3 +225,37 @@ fn test_on_check_busy_on_apply_peers() {
...
+    pd_client.must_add_peer(region_id, new_peer(2, 2));
+
+    // To ensure peer 2 is not pending.
+    cluster.must_put(b"k1", b"v1");
+    must_get_equal(&cluster.get_engine(2), b"k1", b"v1");
+
+    // Mock applying snapshot failed on peer 3.
+    fail::cfg("region_apply_snap_io_err", "return").unwrap();
+    pd_client.must_add_peer(region_id, new_peer(3, 3));
+    sleep_ms(100);
```
Comment (glorv) [inline tests/failpoints/cases/test_pending_peers.rs:250]: Better replace this kind of sleep with `test_util::eventually` to avoid flaky cases.

**Review by glorv — COMMENTED** [review]
rest LGTM

File: tests/failpoints/cases/test_pending_peers.rs (hunk 13 above)
Comment (LykxSassinator) [reply tests/failpoints/cases/test_pending_peers.rs:250]: Not appropriate for this, it should wait one region_heartbeat for updating the meta.

File: tests/failpoints/cases/test_pending_peers.rs [hunk 14]
```diff
@@ -247,15 +247,22 @@ fn test_on_apply_snap_failed() {
...
+        let pending_peers = pd_client.get_pending_peers();
+        pending_peers[&3] == new_peer(3, 3)
+    });
     must_get_none(&cluster.get_engine(3), b"k1");
-    cluster.must_send_store_heartbeat(3);
-    sleep_ms(100);
     // Check that the region is marked as damaged.
-    let stats = cluster.pd_client.get_store_stats(3).unwrap();
+    test_util::eventually(Duration::from_millis(100), Duration::from_secs(1), || {
+        cluster.must_send_store_heartbeat(3);
```
Comment (glorv) [inline tests/failpoints/cases/test_pending_peers.rs]: move this line out of this block?

**Review by glorv — APPROVED** [review]
LGTM

**Review by overvenus — APPROVED** [review]
