### PR TITLE
txn: Do constraint check when handling repeated acqurie_pessimsitic_lock request

### LINKED ISSUE #14038: Do should_not_exist constraint check when handling repeated acquire_pessimistic_lock requests.
## Bug Report

See https://github.com/pingcap/tidb/issues/40114 for details of the bug.

A reasonable way to fix the problem is to do the `should_not_exist` check when handling `acquire_pessimistic_lock` requests sent to the keys that are already locked by the same transaction.

### PR DESCRIPTION
**Pull request by MyonKeminta**
### What is changed and how it works?

Issue Number: Close #14038 
Close https://github.com/pingcap/tidb/issues/40114

What's Changed:

```commit-message
Fixes the problem that when handling repeated acquire_pessimistic_lock requests is recevied, should_not_exist is ignored. 

TiKV provides idempotency for these RPC requests, but for acquire_pessimistic_lock, it ignored the possibility that the client may expect a pessimistic_rollback between two acquire_pessimistic_lock request on the same key. In this case the second request may come from another statement and carries `should_not_exist` that wasn't set in the previously finished pessimistic lock request. If the first request successfully acquired the lock and the pessimistic_rollback failed, TiKV may return a sucessful response, making the client believe that the key doesn't exist before. In some rare cases, this has risk to cause data inconsistency.
```

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

Side effects

- Performance regression
    - Consumes more CPU

### Release note 

```release-note
Fixed a problem that when a transaction in TiDB fails to execute a pessimistic DML and then executes another DML, if there are random network failures between TiDB and TiKV, it has risk to cause data inconsistency.
```

### CODE REVIEW

File: src/storage/txn/actions/acquire_pessimistic_lock.rs [hunk 1]
```diff
@@ -142,10 +142,20 @@ pub fn acquire_pessimistic_lock<S: Snapshot>(
...
-        if need_load_value {
-            val = reader.get(&key, for_update_ts)?;
-        } else if need_check_existence {
-            val = reader.get_write(&key, for_update_ts)?.map(|_| vec![]);
+        if need_load_value || need_check_existence || should_not_exist {
+            let write = reader.get_write_with_commit_ts(&key, for_update_ts)?;
+            if let Some((write, commit_ts)) = write {
+                // Here `get_write_with_commit_ts` returns only the latest PUT if it exists and
+                // is not deleted. It's still ok to pass it into `check_data_constraint`.
+                if locked_with_conflict_ts.is_none() {
```
Comment (sticnarf) [inline src/storage/txn/actions/acquire_pessimistic_lock.rs:150]: Can you add a comment about why `locked_with_conflict_ts` cases can be skipped? I cannot think of any problem but I also want to hear how you think about it.

Comment (cfzjywxk) [reply src/storage/txn/actions/acquire_pessimistic_lock.rs:150]: Would it be a problem for this case:
1. Raise an `Insert` pessimistic lock
2. Locking is successful with conflict and the constraint check is not done
3. Response of 2 is lost, the client retry
4. The `locked_with_conflict_ts` is `Some` and the constraint check is skipped unexpectedly

Comment (MyonKeminta) [reply src/storage/txn/actions/acquire_pessimistic_lock.rs:150]: It acquires the lock and lets the client (TiDB) retry the statement in this case. TiDB will find the key already exists when it retries the statement.
But actually I want to adjust this behavior later: When `should_not_exist` is set and the key exists and the latest version is newer than for_update_ts, return write conflict error even `allow_lock_with_conflict` is set. I think in most cases, when the statement retries, it's likely that it still want to insert the same key and it should still fail.

Comment (MyonKeminta) [reply src/storage/txn/actions/acquire_pessimistic_lock.rs:152]: > Would it be a problem for this case:
> 
> 1. Raise an `Insert` pessimistic lock
> 2. Locking is successful with conflict and the constraint check is not done
> 3. Response of 2 is lost, the client retry
> 4. The `locked_with_conflict_ts` is `Some` and the constraint check is skipped unexpectedly

 In the current implementation (which I'm planning to adjust later), the retried request in the 4th step will still produce a `locked_with_conflict` result, and TiDB will still retry. It will notice the key already exists when retrying the statement and abort the statement then, at which time the lock will be `pessimistic_rollback`-ed

Comment (cfzjywxk) [reply src/storage/txn/actions/acquire_pessimistic_lock.rs:152]: Got it. So the correctness depends on that the returned pessimistic lock result must contain "value existing" information, maybe we could add this in the comment too in case we forget to return the required information?

Comment (MyonKeminta) [reply src/storage/txn/actions/acquire_pessimistic_lock.rs:152]: The `Value` field is required in [`PessimisticLockKeyResult::LockedWithConflict`](https://github.com/tikv/tikv/blob/e1467c56a445d36a8fd8642f9467a0b18fbb8203/src/storage/types.rs#L174). I think it's just fine for locked_with_conflict cases? I'm actually not very sure where you prefer to add the comment you said

Comment (cfzjywxk) [reply src/storage/txn/actions/acquire_pessimistic_lock.rs:152]: Ok, it's fine.

**Review by sticnarf — APPROVED** [review]
LGTM

**Review by cfzjywxk — APPROVED** [review]

**Comment by MyonKeminta** [comment]
@sticnarf @cfzjywxk It seems that your approval doesn't take effect due to the bot was down yesterday night. Could you help try re-approving this PR?

**Review by sticnarf — APPROVED** [review]

**Review by cfzjywxk — APPROVED** [review]
