### PR TITLE
[apiv2] encode key range in raw_checksum interface

### LINKED ISSUE #12950: raw_checksum does not encode key for apiv2
### What version of TiKV are you using?
v6.1.0 & master

### Steps to reproduce
1. run with client-go and run checksum cmd.
2. key is not in region error occurs.

### What did you expect?

raw checksum cmd can succeed.

### What did happened?
`raw_checksum` does not encode key for apiv2

### PR DESCRIPTION
**Pull request by haojinming**
Signed-off-by: haojinming <jinming.hao@pingcap.com>

encode ranges in raw checksum apiv2

Signed-off-by: haojinming <jinming.hao@pingcap.com>

### What is changed and how it works?

Issue Number: Close #12950 

What's Changed:

encode key range in raw_checksum interface

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Manual test (add detailed scripts or steps below)

Side effects

### Release note 

```release-note
None
```

### CODE REVIEW

File: src/storage/mod.rs [hunk 1]
```diff
@@ -4559,6 +4576,25 @@ mod tests {
         let mut range = KeyRange::default();
         range.set_start_key(b"r\0a".to_vec());
         range.set_end_key(b"r\0z".to_vec());
+        assert_eq!(
+            (checksum, total_kvs, total_bytes),
+            block_on(storage.raw_checksum(ctx.clone(), ChecksumAlgorithm::Crc64Xor, vec![range]))
+                .unwrap(),
+        );
+
+        let mut range = KeyRange::default();
```
Comment (pingyu) [inline src/storage/mod.rs:4585]: The test case [here](https://github.com/tikv/tikv/blob/50e0cf4ee720a36ce62a2d80c341cf48533e2977/tests/integrations/storage/test_storage.rs#L1102) may also need to be changed.

Comment (haojinming) [reply src/storage/mod.rs:4585]: This case is ok, as it juse use the prefix to be the start key. The test case added is a negative case to prevent the encoded key as the input.

File: src/storage/mod.rs [hunk 2]
```diff
@@ -2463,6 +2463,20 @@ impl<E: Engine, L: LockManager, F: KvFormat> Storage<E, L, F> {
                         .map(|range| (Some(range.get_start_key()), Some(range.get_end_key()))),
                 )?;
 
+                let encoded_ranges: Vec<KeyRange> = ranges
+                    .iter()
+                    .map(|range| {
+                        let mut new_range = KeyRange::new();
+                        new_range.set_start_key(
+                            F::encode_raw_key(range.get_start_key(), None).into_encoded(),
```
[the remark this answers is not in the document]
Comment (haojinming) [reply src/storage/mod.rs]: Done, PTAL~

File: src/storage/mod.rs (hunk 1 above)
Comment (haojinming) [reply src/storage/mod.rs:4581]: The input range is left closed and right open interval. If changed to `b"r\0f"`, whatever the key is encoded or not, the entry `(b"r\0f", b"ff")` will not be included in checksum.

Comment (haojinming) [reply src/storage/mod.rs]: Changed the first key to `b"r\0a0"` to simplify the case.

**Review by pingyu — APPROVED** [review]
LGTM~

File: src/storage/mod.rs [hunk 3]
```diff
@@ -2462,6 +2461,17 @@ impl<E: Engine, L: LockManager, F: KvFormat> Storage<E, L, F> {
                         .iter()
                         .map(|range| (Some(range.get_start_key()), Some(range.get_end_key()))),
                 )?;
+                let mut encoded_ranges = Vec::with_capacity(ranges.len());
```
[the remark this answers is not in the document]
Comment (haojinming) [reply src/storage/mod.rs:2464]: great suggestion! Thanks.

[the remark this answers is not in the document]
Comment (haojinming) [reply src/storage/mod.rs]: PTAL~ @iosmanthus

**Review by iosmanthus — APPROVED** [review]
LGTM
