### PR TITLE
In-memory engine: encode key for lock cf without mvcc version in delete range

### LINKED ISSUE #17140: In-memory Engine: encoding keys for lock cf should not contain mvcc in delete range
## Bug Report

Encoding keys for lock cf should not contain mvcc in delete range.

### PR DESCRIPTION
**Pull request by SpadeA-Tang**
### What is changed and how it works?

Issue Number: Close #17140 Ref #16141

What's Changed:

```commit-message
encode key for lock cf without mvcc version in delete range
```

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [ ] Need to cherry-pick to the release branch

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by LykxSassinator — APPROVED** [review]
LGTM

**Review by overvenus — COMMENTED** [review]
Rest LGTM

File: components/region_cache_memory_engine/src/keys.rs [hunk 1]
```diff
@@ -216,12 +216,12 @@ pub fn encode_seek_for_prev_key(key: &[u8], seq: u64) -> InternalBytes {
 
 // range keys deos not contain mvcc version and sequence number
 #[inline]
-pub fn encode_key_for_eviction(range: &CacheRange) -> (InternalBytes, InternalBytes) {
+pub fn encode_key_for_boundary_with_mvcc(range: &CacheRange) -> (InternalBytes, InternalBytes) {
     // Both encoded_start and encoded_end should be the smallest key in the
-    // respective of user key, so that the eviction covers all versions of the range
-    // start and covers nothing of range end.
+    // respective of user key (with mvcc version), so that the iterations covers all
+    // versions of the range start and covers nothing of range end.
```
[the remark this answers is not in the document]
Comment (SpadeA-Tang) [reply components/region_cache_memory_engine/src/keys.rs:222]: If the encoded_end is the largest key with respect to its user key, then some versions of it may be deleted.

File: components/region_cache_memory_engine/src/keys.rs [hunk 2]
```diff
@@ -235,6 +235,19 @@ pub fn encode_key_for_eviction(range: &CacheRange) -> (InternalBytes, InternalBy
     (encoded_start, encoded_end)
 }
 
+#[inline]
+pub fn encode_key_for_boundary_without_mvcc(range: &CacheRange) -> (InternalBytes, InternalBytes) {
+    // Both encoded_start and encoded_end should be the smallest key in the
+    // respective of user key (without mvcc version), so that the iterations covers
```
Comment (afeinberg) [inline components/region_cache_memory_engine/src/keys.rs:241]: > "should be the smallest key in the respective of the user key".

could you clarify what you mean by this? smallest possible valid key prefix? smallest possible user key in that range?

Comment (afeinberg) [inline components/region_cache_memory_engine/src/keys.rs:241]: nit: iterations cover, or iteration covers.

**Review by afeinberg — APPROVED** [review]
LGTM

File: components/region_cache_memory_engine/src/keys.rs (hunk 2 above)
Comment (SpadeA-Tang) [reply components/region_cache_memory_engine/src/keys.rs:241]: Keys in kv engine are format of  user_key + mvcc_version + sequence number.
So the smallest key in the respective of user key is user_key + max mvcc version + max sequence number

**Review by overvenus — APPROVED** [review]
