### PR TITLE
Test/fix mac

### LINKED ISSUE #9411: Security check doesn't work in MacOS
### What version of TiKV are you using?

master

### What operating system and CPU are you using?

MacOS

### Steps to reproduce

```shell
make dev
```

### What did happened?

```
usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]
	[-e pattern] [-f file] [--binary-files=value] [--color=when]
	[--context[=num]] [--directories=action] [--label] [--line-buffered]
	[--null] [pattern] [file ...]
Security check passed.
```

Clearly the grep of the security check does not work in MacOS. And it correctly reports security check pass incorrectly as well.

### PR DESCRIPTION
**Pull request by gregwebs**
Fix Mac warnings.

Resolves #9411

### Release note 

None

### CODE REVIEW

File: components/test_util/src/lib.rs [hunk 1]
```diff
@@ -28,10 +28,6 @@ pub use crate::security::*;
 
 pub fn setup_for_ci() {
     if env::var("CI").is_ok() {
-        if env::var("LOG_FILE").is_ok() {
```
Comment (gregwebs) [inline components/test_util/src/lib.rs:31]: Clippy gave a collapsible if warning here previously.

File: scripts/check-redact-log [hunk 2]
```diff
@@ -1,9 +1,21 @@
...
+        echo "To print user data into info logs or error messages, use log_wrappers::Value() instead of hex::encode_upper. The former will respect \`security.redact-info-log\` config and filter out user data from info log if needed. Otherwise, use \`log_wrappers::hex_encode_upper\` to get around the lint error. See https://github.com/tikv/tikv/pull/9250 for more information." >&2
+}
+
+if command -v uname >/dev/null && [[ "$(uname)" == "Darwin" ]] ; then
+   if grep -r -n --color=always --include '*.rs' --exclude hex.rs --exclude-dir target 'encode_upper' . | grep -v log_wrappers ; then
+	error_msg
+	exit 1
+   fi
+else
+    if grep -r -n -P '(?<!hex_)encode_upper' -C 1 --color=always --include \*.rs --exclude hex.rs --exclude-dir target . ; then
```
Comment (gregwebs) [inline scripts/check-redact-log:15]: Should we look behind for l`og_wrappers` instead?

Comment (skyzh) [reply scripts/check-redact-log:15]: It is possible that some SQL functions relies on `log_wrappers::hex_encode_upper` in `tidb_query_vec_expr`. Therefore, I applied look behind regex for all files instead of only for `log_wrappers`.

**Review by skyzh — APPROVED** [review]

File: scripts/check-redact-log (hunk 2 above)
Comment (skyzh) [reply scripts/check-redact-log:15]: I think it's okay to look behind for `log_wrappers` instead of `hex_`.

File: scripts/check-redact-log [hunk 3]
```diff
@@ -1,9 +1,21 @@
...
+set -euo pipefail
 
-if grep -r -n -P '(?<!hex_)encode_upper' -C 1 --color=always --include \*.rs --exclude hex.rs --exclude-dir target . ; then
-    echo "To print user data into info logs or error messages, use log_wrappers::Value() instead of hex::encode_upper. The former will respect \`security.redact-info-log\` config and filter out user data from info log if needed. Otherwise, use \`log_wrappers::hex_encode_upper\` to get around the lint error. See https://github.com/tikv/tikv/pull/9250 for more information." 
-    exit 1
+function error_msg() {
+        echo "To print user data into info logs or error messages, use log_wrappers::Value() instead of hex::encode_upper. The former will respect \`security.redact-info-log\` config and filter out user data from info log if needed. Otherwise, use \`log_wrappers::hex_encode_upper\` to get around the lint error. See https://github.com/tikv/tikv/pull/9250 for more information." >&2
+}
+
+if command -v uname >/dev/null && [[ "$(uname)" == "Darwin" ]] ; then
```
Comment (BusyJay) [inline scripts/check-redact-log:9]: What's the purpose of `command -v uname`?

Comment (gregwebs) [reply scripts/check-redact-log:9]: I am used to checking for the existence of an executable. Probably not needed in this case so I am happy to remove it.

Comment (BusyJay) [reply scripts/check-redact-log:9]: Please keep it simple.

File: scripts/check-redact-log [hunk 4]
```diff
@@ -1,9 +1,21 @@
...
+   if grep -r -n --color=always --include '*.rs' --exclude hex.rs --exclude-dir target 'encode_upper' . | grep -v log_wrappers ; then
```
Comment (BusyJay) [inline scripts/check-redact-log:10]: Probably just using the same command is enough for all platforms.

**Comment by gregwebs** [comment]
@BusyJay PTAL

File: scripts/check-redact-log (hunk 4 above)
Comment (BusyJay) [reply scripts/check-redact-log:10]: Why is it marked resolved? I can see different commands are still used for different platforms.

Comment (skyzh) [reply scripts/check-redact-log:10]: On macOS, `grep` doesn't support look back pattern (`{except hex_}encode_upper`). If we use grep once and then `grep -v`, the output will lose context information `-C`, which shows adjacent lines around `encode_upper` and is friendly to developers. Therefore, to retain context information correctly, we need to use one grep with look back pattern, and have to use two separate commands for different platforms. The result is that, on macOS, no context information is shown, and on Linux, adjacent lines will be shown.

Comment (BusyJay) [reply scripts/check-redact-log:10]: Get it, thanks!

**Review by BusyJay — APPROVED** [review]

**Review by yiwu-arbug — APPROVED** [review]
LGTM
