### PR TITLE
Revert "In-memory Engine: do not evict range on applying snapshot

### LINKED ISSUE #17405: In-memory Engine: assert failed "left: Active != right: Pending" on RegionManager::split_region
## Bug Report

```log
[2024/08/20 09:26:12.595 +00:00] [FATAL] [lib.rs:478] ["assertion `left == right` failed
  left: Active
 right: Pending"] [backtrace="   0: tikv_util::set_panic_hook::{{closure}}
             at home/stn/tikv/components/tikv_util/src/lib.rs:477:18
   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at home/stn/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2029:9
      std::panicking::rust_panic_with_hook
             at home/stn/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:783:13
   2: std::panicking::begin_panic_handler::{{closure}}
             at home/stn/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:657:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at home/stn/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:171:18
   4: rust_begin_unwind
             at home/stn/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:645:5
   5: core::panicking::panic_fmt
             at home/stn/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panicking.rs:72:14
   6: core::panicking::assert_failed_inner
             at home/stn/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panicking.rs:342:17
   7: core::panicking::assert_failed
             at home/stn/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panicking.rs:297:5
   8: range_cache_memory_engine::range_manager::RegionManager::split_region
             at home/stn/tikv/components/range_cache_memory_engine/src/range_manager.rs:817:13
   9: <range_cache_memory_engine::engine::RangeCacheMemoryEngine as engine_traits::range_cache_engine::RangeCacheEngine>::on_region_event
             at home/stn/tikv/components/range_cache_memory_engine/src/engine.rs:490:17
  10: hybrid_engine::range_cache_engine::<impl engine_traits::range_cache_engine::RangeCacheEngineExt for hybrid_engine::engine::HybridEngine<EK,EC>>::on_region_event
             at home/stn/tikv/components/hybrid_engine/src/range_cache_engine.rs:14:9
  11: hybrid_engine::observer::eviction::EvictionObserver::on_flush_cmd
             at home/stn/tikv/components/hybrid_engine/src/observer/eviction.rs:120:13
  12: raftstore::coprocessor::dispatcher::CoprocessorHost<E>::on_flush_applied_cmd_batch
             at home/stn/tikv/components/raftstore/src/coprocessor/dispatcher.rs:872:13
  13: raftstore::store::fsm::apply::ApplyContext<EK>::write_to_db
             at home/stn/tikv/components/raftstore/src/store/fsm/apply.rs:662:9
  14: raftstore::store::fsm::apply::ApplyContext<EK>::flush
             at home/stn/tikv/components/raftstore/src/store/fsm/apply.rs:749:30
  15: <raftstore::store::fsm::apply::ApplyPoller<EK> as batch_system::batch::PollHandler<raftstore::store::fsm::apply::ApplyFsm<EK>,raftstore::store::fsm::apply::ControlFsm>>::end
             at home/stn/tikv/components/raftstore/src/store/fsm/apply.rs:4745:9
      batch_system::batch::Poller<N,C,Handler>::poll
             at home/stn/tikv/components/batch-system/src/batch.rs:440:13
  16: batch_system::batch::BatchSystem<N,C>::start_poller::{{closure}}
             at home/stn/tikv/components/batch-system/src/batch.rs:551:17
      <std::thread::Builder as tikv_util::sys::thread::StdThreadBuildWrapper>::spawn_wrapper::{{closure}}
             at home/stn/tikv/components/tikv_util/src/sys/thread.rs:438:13
      std::sys_common::backtrace::__rust_begin_short_backtrace
             at home/stn/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:155:18
  17: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
             at home/stn/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:529:17
      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at home/stn/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panic/unwind_safe.rs:272:9
      std::panicking::try::do_call
             at home/stn/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:552:40
      std::panicking::try
             at home/stn/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:516:19
      std::panic::catch_unwind
             at home/stn/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:142:14
      std::thread::Builder::spawn_unchecked_::{{closure}}
             at home/stn/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:528:30
      core::ops::function::FnOnce::call_once{{vtable.shim}}
             at home/stn/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5
  18: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at home/stn/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2015:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at home/stn/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2015:9
      std::sys::unix::thread::Thread::new::thread_start
             at home/stn/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys/unix/thread.rs:108:17
  19: start_thread
  20: __clone3
"] [location=components/range_cache_memory_engine/src/range_manager.rs:817] [thread_name=apply-1] [thread_id=112]
```

### What version of TiKV are you using?

Based on #17359 + #17296 
df8fdcf6a09de8cde9f11f84f245500c1c731298

### Steps to reproduce

Run sysbench workload, specifically https://github.com/PingCAP-QE/tidb-test/pull/2379

### What did you expect?

No assert failure.

### What did happened?

See above.

### PR DESCRIPTION
**Pull request by glorv**
…7237)"

This reverts commit fe7d5232447c5ab8958cccbc666878994230ac3f.

### What is changed and how it works?

Issue Number: Close #17405

What's Changed:

```commit-message
Revert #17237 because cache region can be loaded even when current peer is not leader so we should handle apply snapshot event.
```

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [ ] Need to cherry-pick to the release branch

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by overvenus — APPROVED** [review]

File: components/hybrid_engine/src/observer.rs [hunk 1]
```diff
@@ -44,14 +44,15 @@ impl Observer {
         coprocessor_host
             .registry
             .register_admin_observer(priority, BoxAdminObserver::new(self.clone()));
+        // Evict cache when a peer applies snapshot.
```
Comment (overvenus) [inline components/hybrid_engine/src/observer.rs:47]: BTW, please add some comments about why we have to evict region before applying snapshot.

Comment (glorv) [reply components/hybrid_engine/src/observer.rs:47]: Done

**Review by SpadeA-Tang — APPROVED** [review]
