### PR TITLE
raftstore & raftstore-v2:control grpc server according to slowness.

### LINKED ISSUE #15086: TiKV provides APIs to restart grpc service
When a TiKV node becomes unhealthy  (such as slow IO, network partition from certain nodes),  we usually want to fail fast existing requests and do leader transfer. 
However, we may not want to kill a tikv server when it's unhealthy because restarting the tikv is too expensive and it may impact performance (due to warmup cache). 
So there should be a way to do a soft restart that will only start/stop grpc services

### PR DESCRIPTION
**Pull request by LykxSassinator**
### What is changed and how it works?

Issue Number: Close #15086

What's Changed:

This pr refers to [pr:14991](https://github.com/tikv/tikv/pull/14991), and all the controlling implementation is based on it.
After [pr:14991](https://github.com/tikv/tikv/pull/14991) merged, this pr will merge it and polish redundant codes.
```commit-message
Make raftstore & raftstore-v2 able to control the grpc service, according to the slowness.
```

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

```release-note
Please add a release note.

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

If you don't think this PR needs a release note then fill it with None.
If this PR will be picked to release branch, then a release note is probably required.
```

### CODE REVIEW

**Comment by LykxSassinator** [comment]
The update on the private dependency in `Cargo.toml` is waiting for pr on kvrproto: https://github.com/pingcap/kvproto/pull/1150 to be merged.

**Comment by LykxSassinator** [comment]
And as https://github.com/tikv/tikv/pull/14991 has been closed, this pr will be the formal one.

**Comment by LykxSassinator** [comment]
/cc @tonyxuqqi 
PTAL, thx.

**Comment by LykxSassinator** [comment]
/cc @overvenus @tabokie 
PTAL, thx.

File: components/server/src/server.rs [hunk 1]
```diff
@@ -153,12 +155,37 @@ fn run_impl<CER: ConfiguredRaftEngine, F: KvFormat>(config: TikvConfig) {
...
+                Some(service_event_tx),
+            )
+        })
+    };
+    loop {
+        if let Ok(service_event) = service_event_rx.recv() {
+            match service_event {
+                ServiceEvent::PauseGrpc => {
+                    tikv.pause();
+                }
```
Comment (overvenus) [inline components/server/src/server.rs:177]: If we want abort requests ASAP, how about let them select a abort signal?

I think it's less error-prone, as it does not need to restart gRPC server.

For all gRPC requests,
``` rust
let (abort, notify) = tokio::sync::broadcast::channel(1);

if server is slow {
    drop(notify);
}

fn kv_requests(ctx, req) {
    ctx.spawn(async {
        select! {
          handle(req).await => { .. }
          abort.await => { .. }
        }
    })
}
```

Comment (tonyxuqqi) [reply components/server/src/server.rs:177]: We may try this approach later. For now let's stick to restarting gRPC server as the short term solution. 
The reason is that the approach above is essentially is "api level grpc restart",  it needs to handle not only current requests, but also prevent new requests reaching to this TiKV node. Also if we need to add a new error code, then it would need tikv-client's code change.  It's all do-able, but it requires more time to implement and test. 

As discussed, we will use restart grpc server as the first short term solution. And we can explore the suggested solution later once we have a workable baseline.

File: src/server/server.rs [hunk 2]
```diff
@@ -344,6 +396,35 @@ where
         Ok(())
     }
 
+    pub fn pause(&mut self) -> Result<()> {
```
Comment (tonyxuqqi) [inline src/server/server.rs:399]: is there any test case to cover pause and resume logic?

**Review by tonyxuqqi — COMMENTED** [review]
Overall LGTM, but need some integration test.

File: components/raftstore/src/store/worker/pd.rs [hunk 3]
```diff
@@ -1969,6 +1990,31 @@ where
...
+                }
+            }
+            pdpb::ControlGrpcEvent::Resume => {
+                if let Err(e) = self.grpc_service_manager.resume() {
+                    warn!("failed to send service event to RESUME grpc server";
+                            "err" => ?e);
+                } else {
+                    self.update_health_status(ServingStatus::Serving);
+                }
+            }
```
Comment (overvenus) [inline components/raftstore/src/store/worker/pd.rs:2015]: How much time do they take? Could you add to log?

File: tests/failpoints/cases/test_kv_service.rs [hunk 4]
```diff
@@ -100,4 +100,6 @@ fn test_undetermined_write_err() {
     .unwrap_err();
     assert_eq!(err.to_string(), "RpcFailure: 1-CANCELLED CANCELLED",);
     fail::remove("applied_cb_return_undetermined_err");
+    // The previous panic hasn't been captured.
+    assert!(std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| drop(cluster))).is_err());
```
Comment (overvenus) [inline tests/failpoints/cases/test_kv_service.rs:104]: Why does it panic?

File: src/server/server.rs [hunk 5]
```diff
@@ -344,6 +396,35 @@ where
...
+        // Prepare the builder for resume grpc server
+        // If the builder cannot be created, then pause will be skipped;
+        let builder = self.builder_factory.create_builder(self.env.clone())?;
+        let builder = Either::Left(builder);
+        if let Some(Either::Right(server)) = self.builder_or_server.take() {
+            drop(server);
+        }
+        self.health_service
+            .set_serving_status("", ServingStatus::NotServing);
+        self.builder_or_server = Some(builder);
```
Comment (overvenus) [inline src/server/server.rs:411]: Why not create builder on `resume()`?

File: src/server/server.rs (hunk 2 above)
Comment (LykxSassinator) [reply src/server/server.rs:399]: Supplied.

File: tests/failpoints/cases/test_kv_service.rs (hunk 4 above)
Comment (LykxSassinator) [reply tests/failpoints/cases/test_kv_service.rs:104]: The failpoint `applied_cb_return_undetermined_err` just return with `fatal` but not captured in previous work.

File: src/server/server.rs (hunk 5 above)
Comment (LykxSassinator) [reply src/server/server.rs:411]: As annotations marked in `pause()`, we wanna make the preparing work completed when successfully `pause`.

File: components/raftstore/src/store/worker/pd.rs (hunk 3 above)
Comment (LykxSassinator) [reply components/raftstore/src/store/worker/pd.rs:2015]: Maybe it's redundant? `pause` and `resume` just sends messages to the external receiver, and it's a light-weight operation.

File: components/service/src/service_manager.rs [hunk 6]
```diff
@@ -0,0 +1,80 @@
...
+    /// Send message to outer handler to notify PAUSE grpc server.
+    pub fn pause(&mut self) -> Result<(), SendError<ServiceEvent>> {
+        if self.is_paused() {
+            // Already in PAUSE.
+            return Ok(());
+        }
+        let result = self.service_router.send(ServiceEvent::PauseGrpc);
+        if result.is_ok() {
+            self.status
+                .store(GrpcServiceStatus::NotServing, Ordering::Relaxed);
```
Comment (tonyxuqqi) [inline components/service/src/service_manager.rs:52]: this status is really not very useful, as the real pause/resume status is not known at this layer at all. I think this can be removed and the check should be added where the actual pause/resume is done.

File: components/raftstore-v2/src/worker/pd/store.rs [hunk 7]
```diff
@@ -231,6 +231,8 @@ where
         stats.set_cpu_usages(self.store_stat.store_cpu_usages.clone().into());
         stats.set_read_io_rates(self.store_stat.store_read_io_rates.clone().into());
         stats.set_write_io_rates(self.store_stat.store_write_io_rates.clone().into());
+        // Update grpc server status
+        stats.set_is_grpc_paused(self.grpc_service_manager.is_paused());
```
Comment (tonyxuqqi) [inline components/raftstore-v2/src/worker/pd/store.rs:235]: How is this information (is_grpc_paused) used in PD?

File: src/server/server.rs [hunk 8]
```diff
@@ -344,6 +396,33 @@ where
...
+        Ok(())
+    }
+
+    pub fn resume(&mut self) -> Result<()> {
```
Comment (tonyxuqqi) [inline src/server/server.rs:413]: It's better to measure the duration in pause/resume as they seem pretty heavy.

File: components/raftstore-v2/src/worker/pd/store.rs (hunk 7 above)
Comment (LykxSassinator) [reply components/raftstore-v2/src/worker/pd/store.rs:235]: For:

By design, PD will notify the slow TiKV node to restart Grpc if necessary(). And this flag is a flag reflecting whether the Grpc server has been paused or not in the target node.

This strategy is not open until the detection on transient jitters has been merged.

File: src/server/server.rs (hunk 8 above)
Comment (LykxSassinator) [reply src/server/server.rs:414]: Got

File: components/raftstore/src/store/worker/pd.rs (hunk 3 above)
Comment (overvenus) [reply components/raftstore/src/store/worker/pd.rs:2015]: Oh, I see, is there any log after the actual pause and resume operation?

Comment (LykxSassinator) [reply components/raftstore/src/store/worker/pd.rs:2015]: > Oh, I see, is there any log after the actual pause and resume operation?

Yep, as @tonyxuqqi suggested, the loggings of PAUSE | RESUME operation (containing the time costs ) have been supplied in the latest commit.

File: src/server/server.rs [hunk 9]
```diff
@@ -344,6 +396,33 @@ where
...
+        // Prepare the builder for resume grpc server. And if the builder cannot be
+        // created, then pause will be skipped.
+        let builder = Either::Left(self.builder_factory.create_builder(self.env.clone())?);
+        if let Some(Either::Right(server)) = self.builder_or_server.take() {
+            drop(server);
+        }
+        self.health_service
+            .set_serving_status("", ServingStatus::NotServing);
+        self.builder_or_server = Some(builder);
+        info!("paused the grpc server"; "spent_time" => ?start.elapsed(),);
```
Comment (overvenus) [inline src/server/server.rs:410]:
```suggestion
        info!("paused the grpc server"; "takes" => ?start.elapsed(),);
```

Mostly, TiKV uses "takes" for slow operation duration.

File: src/server/server.rs [hunk 10]
```diff
@@ -344,6 +396,33 @@ where
...
+        Ok(())
+    }
+
+    pub fn resume(&mut self) -> Result<()> {
+        if let Some(builder) = self.builder_or_server.as_ref() {
+            let start = Instant::now();
+            assert!(builder.is_left());
+            self.build_and_bind()?;
```
Comment (overvenus) [inline src/server/server.rs:418]: Does caller retry if it fails to bind ports?

File: tests/integrations/server/server.rs [hunk 11]
```diff
@@ -0,0 +1,68 @@
...
+        config.log.file.filename = "".to_string();
+        config.storage.data_dir = dir.path().to_str().unwrap().to_string();
+        config.pd.endpoints = vec![format!("{}:{}", eps[0].0, eps[0].1)];
+        server::server::run_tikv(config, service_event_tx, service_event_rx);
+
+        pd_server.stop();
+    });
+
+    let env = Arc::new(Environment::new(1));
+    let channel = ChannelBuilder::new(env).connect("127.0.0.1:20160");
```
Comment (overvenus) [inline tests/integrations/server/server.rs:46]: Could you bind a random port `127.0.0.1:0`? So that test can success even if 20160 is not available.

File: tests/integrations/server/server.rs [hunk 12]
```diff
@@ -0,0 +1,68 @@
...
+    let req = HealthCheckRequest {
+        service: "".to_string(),
+        ..Default::default()
+    };
+    let max_retry = 30;
+    check_heath_api(max_retry, &client);
+    // PAUSE grpc service and validate.
+    sender.send(ServiceEvent::PauseGrpc).unwrap();
+    std::thread::sleep(Duration::from_secs(1));
+    let resp = client.check(&req);
```
Comment (overvenus) [inline tests/integrations/server/server.rs:57]: Better retry check, because pause grpc is executed asynchronously.

```rust
let start = Instant::now();
loop {
  if start.elapsed() > Duration::from_secs(5) { panic!(); }
  if client.check(&req).is_err() { break; }
}
```

File: src/server/server.rs (hunk 10 above)
Comment (LykxSassinator) [reply src/server/server.rs:418]: Yep, it will warn with `failed to resume the grpc server` logging if it fails. And the user can find it to repeat the operation again.

File: src/server/server.rs (hunk 9 above)
Comment (LykxSassinator) [reply src/server/server.rs:410]: Got, thx.

File: tests/integrations/server/server.rs (hunk 12 above)
Comment (LykxSassinator) [reply tests/integrations/server/server.rs]: thx.

**Review by overvenus — APPROVED** [review]
