### PR TITLE
resolved_ts: reduce retrying of registering observe region

### LINKED ISSUE #10163: resolved_ts: register region busy loop prints too many logs
### What version of TiKV are you using?

A recent master TiKV a52d25a2b4c53706046346c522b4dd653d9befc4

### Steps to reproduce

Keeps giving TiKV huge write load. I run with uniform workload in https://github.com/pingcap/tipocket/pull/410.

### What did happened?

There are lots of logs like this. And the region takes a long time (up to several minutes) to split so the client may receive `Region Unavailable`.

```
[2021/05/12 16:59:42.011 +08:00] [INFO] [endpoint.rs:223] ["register observe region"] [region="id: 21161 start_key: 7480000000000000FFA75F720136326562FF35396636FF2D6163FF39372D3465FF6639FF2D383538662DFF63FF65643634336638FFFF666366660000
0000FFFB00000000000000F8 end_key: 7480000000000000FFA75F720136383266FF65303232FF2D3936FF65342D3464FF3162FF2D616464322DFF35FF63353532386231FFFF3638636400000000FFFB00000000000000F8 region_epoch { conf_ver: 5 version: 779 } peers { id: 211
62 store_id: 1 } peers { id: 21163 store_id: 4 } peers { id: 21164 store_id: 5 }"] ["store id"=Some(5)]
[2021/05/12 16:59:42.011 +08:00] [WARN] [scanner.rs:83] ["resolved_ts scan get snapshot failed"] [err="Request(message: \"read index not ready, reason can not read index due to split, region 21161\" read_index_not_ready { reason: \"can
not read index due to split\" region_id: 21161 })"]
[2021/05/12 16:59:42.011 +08:00] [INFO] [endpoint.rs:347] ["region met error, try to register again"] [error="message: \"read index not ready, reason can not read index due to split, region 21161\" read_index_not_ready { reason: \"can n
ot read index due to split\" region_id: 21161 }"] [region_id=21161]
[2021/05/12 16:59:42.011 +08:00] [INFO] [endpoint.rs:295] ["deregister observe region"] [observe_id=ObserveID(3781060)] [region_id=21161] [store_id=Some(5)]
[2021/05/12 16:59:42.011 +08:00] [INFO] [endpoint.rs:223] ["register observe region"] [region="id: 21161 start_key: 7480000000000000FFA75F720136326562FF35396636FF2D6163FF39372D3465FF6639FF2D383538662DFF63FF65643634336638FFFF666366660000
0000FFFB00000000000000F8 end_key: 7480000000000000FFA75F720136383266FF65303232FF2D3936FF65342D3464FF3162FF2D616464322DFF35FF63353532386231FFFF3638636400000000FFFB00000000000000F8 region_epoch { conf_ver: 5 version: 779 } peers { id: 211
62 store_id: 1 } peers { id: 21163 store_id: 4 } peers { id: 21164 store_id: 5 }"] ["store id"=Some(5)]
[2021/05/12 16:59:42.011 +08:00] [WARN] [scanner.rs:83] ["resolved_ts scan get snapshot failed"] [err="Request(message: \"read index not ready, reason can not read index due to split, region 21161\" read_index_not_ready { reason: \"can
not read index due to split\" region_id: 21161 })"]
[2021/05/12 16:59:42.011 +08:00] [INFO] [endpoint.rs:347] ["region met error, try to register again"] [error="message: \"read index not ready, reason can not read index due to split, region 21161\" read_index_not_ready { reason: \"can n
ot read index due to split\" region_id: 21161 }"] [region_id=21161]
[2021/05/12 16:59:42.011 +08:00] [INFO] [endpoint.rs:295] ["deregister observe region"] [observe_id=ObserveID(3781061)] [region_id=21161] [store_id=Some(5)]
[2021/05/12 16:59:42.011 +08:00] [INFO] [endpoint.rs:223] ["register observe region"] [region="id: 21161 start_key: 7480000000000000FFA75F720136326562FF35396636FF2D6163FF39372D3465FF6639FF2D383538662DFF63FF65643634336638FFFF666366660000
0000FFFB00000000000000F8 end_key: 7480000000000000FFA75F720136383266FF65303232FF2D3936FF65342D3464FF3162FF2D616464322DFF35FF63353532386231FFFF3638636400000000FFFB00000000000000F8 region_epoch { conf_ver: 5 version: 779 } peers { id: 211
62 store_id: 1 } peers { id: 21163 store_id: 4 } peers { id: 21164 store_id: 5 }"] ["store id"=Some(5)]
```

~~I'm afrait frequent calling of `SignificantMsg::CaptureChange` also prevent the region from splitting and keeps making the condition worse.~~

### PR DESCRIPTION
**Pull request by NingLin-P**
### What problem does this PR solve?

Issue Number: close #10163 

Problem Summary:

After the new leader elected, it will try to register observe region immediately. To register observe region, the leader needs to first handle a quorum read request to ensure it has the most update-to-date data, the request usually fail because the leader hasn't apply any log on its term or it is splitting or merging, and the leader will retry the request immediately without backoff, and result in busy loop of retrying.

### What is changed and how it works?

What's Changed:

Use `applied_on_current_term` replace `on_role_change` to trigger register observe region, so the request won't fail because the leader hasn't apply any log on its term.

Add backoff before retrying if the request still fails for some resion

Tests 

- Integration test

### Release note 
- No release note

### CODE REVIEW

File: components/raftstore/src/coprocessor/dispatcher.rs [hunk 1]
```diff
@@ -680,6 +690,7 @@ mod tests {
         fn on_flush_apply(&self, _: PanicEngine) {
             self.called.fetch_add(13, Ordering::SeqCst);
         }
+        fn on_applied_current_term(&self, _: StateRole, _: &Region) {}
```
Comment (BusyJay) [inline components/raftstore/src/coprocessor/dispatcher.rs:693]: Seems unnecessary.

File: components/resolved_ts/src/observer.rs [hunk 2]
```diff
@@ -110,10 +110,28 @@ impl<E: KvEngine> CmdObserver<E> for Observer<E> {
...
+        }
+    }
 }
 
 impl<E: KvEngine> RoleObserver for Observer<E> {
     fn on_role_change(&self, ctx: &mut ObserverContext<'_>, role: StateRole) {
+        // Delay the leader's `RegionRoleChanged` event util the leader has applied on its term
+        // so that registering observe region won't be failed because the leader not apply on its
+        // term
+        if role == StateRole::Leader {
```
Comment (BusyJay) [inline components/resolved_ts/src/observer.rs:132]: The change can affect all role observers. How about adding a new event `ApplyToCurrentTerm` instead of reusing `RoleChange`?

Comment (NingLin-P) [reply components/resolved_ts/src/observer.rs:132]: This change only affects the `resolved-ts`'s `Observer`, we can add a new event `ApplyToCurrentTerm` to observe new leader but still need `RoleChange` to observe step down leader

Comment (nolouch) [reply components/resolved_ts/src/observer.rs:132]: How about a state flag instead of skipping in here?

Comment (NingLin-P) [reply components/resolved_ts/src/observer.rs]: I split the `RoleChange` task into `RegisterRegion` and `DeRegisterRegion` task, PTAL again.

**Review by nolouch — COMMENTED** [review]
/lgtm

File: components/resolved_ts/src/scanner.rs [hunk 3]
```diff
@@ -170,27 +174,43 @@ impl<T: 'static + RaftStoreRouter<E>, E: KvEngine> ScannerPool<T, E> {
...
+                if err.has_epoch_not_match() || err.get_message().contains("satle observe id") {
+                    return Err(Error::request(err));
+                }
+                last_err = Some(err)
+            } else {
+                return Ok(resp.snapshot.unwrap());
+            }
         }
-        Ok(resp.snapshot.unwrap())
+        Err(Error::request(last_err.unwrap()))
```
Comment (Yisaer) [inline components/resolved_ts/src/scanner.rs:213]: I think the error here should also include `backoff timeout`

**Review by Yisaer — COMMENTED** [review]
Rest LGTM

**Review by Yisaer — APPROVED** [review]

**Review by 5kbpers — COMMENTED** [review]
Could you add some tests?

File: components/cdc/src/observer.rs [hunk 4]
```diff
@@ -143,6 +143,8 @@ impl<E: KvEngine> CmdObserver<E> for CdcObserver {
             }
         }
     }
+
+    fn on_applied_current_term(&self, _: StateRole, _: &Region) {}
```
[the remark this answers is not in the document]
Comment (nolouch) [reply components/cdc/src/observer.rs:147]: cc @NingLin-P
