### PR TITLE
raftstore: check stale peer on leader missing

### LINKED ISSUE #11847: resolved_ts: max resolved ts gap exceed 1 hours  while inject network chaos during run stale read
### What version of TiKV are you using?

/ # /tikv-server -V
TiKV
Release Version:   5.4.0-alpha
Edition:           Community
Git Commit Hash:   3f769418ef0f4ab853aad466a40371c6afdc44c8
Git Commit Branch: heads/refs/tags/v5.4.0-nightly
UTC Build Time:    2022-01-11 05:13:56
Rust Version:      rustc 1.56.0-nightly (2faabf579 2021-07-27)
Enable Features:   jemalloc mem-profiling portable sse test-engines-rocksdb cloud-aws cloud-gcp cloud-azure
Profile:           dist_release

### Steps to reproduce

run oltp_stale_read_rel_001, inject one tikv network down error while run stale read.

### What did you expect?
Max 
### What did happened?
image

### LINKED ISSUE #15520: resolved_ts doesn't push forward, it's stuck, which will cause ebs backup failed
### Steps to reproduce
1. create cluster
2. do volumebackup

### What did you expect?
1. volumebackup success

### What did happened?
1. volumebackup failed, 
img_v2_b6cecace-1769-4f2d-9424-c4180ec68b3g
[2023/06/15 02:57:43.947 +00:00] [INFO] [[raft.rs:384](http://raft.rs:384/)] [newRaft] [peers="Configuration { incoming: Configuration { voters: {} }, outgoing: Configuration { voters: {} } }"] ["last term"=0] ["last index"=0] [applied=0] [commit=0] [term=0] [raft_id=426644] [region_id=242469]
[2023/06/15 02:57:43.947 +00:00] [INFO] [[raw_node.rs:315](http://raw_node.rs:315/)] ["RawNode created with id 426644."] [id=426644] [raft_id=426644] [region_id=242469]
[2023/06/15 02:57:43.947 +00:00] [INFO] [[raft.rs:1364](http://raft.rs:1364/)] ["received a message with higher term from 415815"] ["msg type"=MsgHeartbeat] [message_term=18] [term=0] [from=415815] [raft_id=426644] [region_id=242469]
[2023/06/15 02:57:43.947 +00:00] [INFO] [[raft.rs:1120](http://raft.rs:1120/)] ["became follower at term 18"] [term=18] [raft_id=426644] [region_id=242469]
[2023/06/15 05:17:43.969 +00:00] [WARN] [[peer.rs:6108](http://peer.rs:6108/)] ["leader missing longer than max_leader_missing_duration. To check with pd and other peers whether it's still valid"] [expect=2h] [peer_id=426644] [region_id=242469]
img_v2_336b9719-95ca-4c2a-bac8-9aac6a02fd1g
img_v2_64d62082-afe0-400d-a239-92511e89bb8g

### PR DESCRIPTION
**Pull request by overvenus**
### What is changed and how it works?

Issue Number: Close #15520 Close #11847 Close pingcap/tidb#39130

What's Changed:

```commit-message
Stale peers can impede TiKV store resolved ts and impact RTO for essential
functions. Default 2-hour interval for stale peer check is insufficient
for stale reads, flashbacks, and ebs backup.

To mitigate this, we speed up stale read check by allowing TiKV to check for
stale peers every 10 minutes in the event that a leader is missing.
```

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Integration test

### Release note 

```release-note
Fix an issue that resolved ts may be blocked for 2 hours.
```

### CODE REVIEW

File: components/raftstore/src/store/metrics.rs [hunk 1]
```diff
@@ -659,6 +659,11 @@ lazy_static! {
             "Total number of leader missed region."
         ).unwrap();
 
+    pub static ref CHECK_STALE_PEER_COUNTER: IntCounter = register_int_counter!(
```
Comment (tonyxuqqi) [inline components/raftstore/src/store/metrics.rs:662]: It's better to update the tikv_detail metrics file as well.

**Review by tonyxuqqi — APPROVED** [review]

**Review by YuJuncen — APPROVED** [review]
