### PR TITLE
txn: Add batch-resumed mode for acquire_pessimistic_lock storage command 

### LINKED ISSUE #13298: Enhanced queueing for conflicting pessimistic transactions
## Background

Currently, we are adopting a simple but rough implementation for pessimistic lock waiting and waking up. It works just fine in most normal cases, however, there will be problems under workloads that has frequent lock conflicts. When there are many requests trying to acquire the lock on a single key in TiKV:

* The order that the transactions successfully get the lock has too much randomness
* When a pessimistic lock request is woken up after waiting a while in TiKV, it always returns `WriteConflict` to TiDB so that TiDB will retry the statement.
* When many pessimistic lock requests are waiting on the same key in TiKV and the current lock is released, one of the requests will be woken up, and the others will be woken up too after delaying for `wake-up-delay-duration` (which is a configurable value that defaults to 10ms). If the first awakened transaction's retrying request arrives late, the key might already have been locked by another transaction.

This may lead to some problems:

* The latency to acquire the lock might be very unstable, causing high tail latency.
* There might be too many statement-retries that are useless but wastes resources.
* When the problem is severe, it's also possible to cause errors like lock wait timeout and statement retry limit exceeded.

By carefully adjusting `wake-up-delay-duration`, we are actually able to try to make it work well in most scenarios. However, it's very hard to adjust it since it's difficult to predict the effect of changing it. It's even harder if a user who don't understand the internal implementation of TiKV want to tune it. Besides, its a store level config, which means, if a user have more than one workloads that has different characteristics in a single cluster, it's impossible to use different `wake-up-delay-duration` for different workloads.

We expects it would be better to make transactions in such kind of scenarios to execute sequentially, avoiding too much useless statement retries and high tail latency. However, this will be very complicated to implement in our current architecture, especially considering that we needs to guarantee the backward compatibility. We have a complicated design for this problem and it took us much efforts to trying to demonstrate it. We've confirmed that the complicated design is helpful for solving the problem stated above in those kinds of scenarios. However, the stronger queueing behavior in lock waiting introduces higher average latency, or to say, lower QPS. We do have ideas to optimize it further, however, it would make the design much more complicated.

Now we are going to productize the idea. As the first step, we will first implement a subset of the original design: we will enhance the queueing behavior for pessimistic lock requests that involves only one key. This will be helpful for many cases that has frequent lock conflicts on some single rows. And since there's possibly QPS regression, the new behavior will be optional and disabled by default. A user will need to choose to get lower tail latency at the expense of higher average latency if the user needs.

<details>
<summary>Demo branches</summary>

The draft branches for demo can be found at:

* https://github.com/pingcap/tidb/pull/35588
* https://github.com/tikv/client-go
* https://github.com/tikv/tikv/pull/12749

Most part of the final implementation can be ported from these branches, but there will also be some differences.

</details>

## Tasks

- [ ] The RFC / design document
  - RFC for TiKV: https://github.com/tikv/rfcs/pull/100
  - Design doc for TiDB: https://github.com/pingcap/tidb/pull/37518
- [ ] The spec document

- kvproto
    - [x] Protocol change (kvproto) https://github.com/pingcap/kvproto/pull/872
- TiKV
    - [x] Lock waiting queue implementation
        - Each key will have its own waiting queue. In the demo branch, it's put in `Latch`, but later we found hard to store it with an efficient and simple data structure. We will consider store it in the lock table of `ConcurrencyManager` or another separated concurrent hash map.
        - https://github.com/tikv/tikv/pull/13486
        - https://github.com/tikv/tikv/pull/13560
    - [x] Waiter manager & deadlock detector adaption
        - `WaiterManager` no longer have the responsibility to wake up lock requests after the lock is released. Instead, we will need it to be able to index requests by unique tokens. Therefore both its interface and inner data structure need to be updated.
        - https://github.com/tikv/tikv/pull/13447
    - [x] New implementation of storage command `AcquirePessimisticLock`
        - For requests that contains only one key, it can choose to use the new locking behavior: it's allowed to force lock the key even when there's write conflict. It will use the new protocol to return the actual locked ts (the actual lower bound of `for_update_ts`) to the client (TiDB).
        - https://github.com/tikv/tikv/pull/13687
    - [x] Resuming of pessimistic lock requests
        - For pessimistic lock requests that choose to use the new locking behavior, after waiting for another lock, we allow it to continue acquiring the lock after being woken up, instead of returning `WriteConflict` to the client to request a retry.
        - https://github.com/tikv/tikv/pull/13833
        - https://github.com/tikv/tikv/pull/13826
    - [x] Lock wait info update for queueing requests
        - When many requests are queued waiting the same key, and one of them is granted the lock after the previous lock being released, then for the other queueing requests, the transaction they are waiting for is changed. In this case, we need some update operations so that it can perform correct deadlock detection and provide diagnostic information about lock waiting.
- client-go
    - [x] Support aggressive locking behavior
      - https://github.com/tikv/client-go/pull/528
- TiDB
    - [x] Support aggressive locking behavior which can be enabled by system variable
      - https://github.com/pingcap/tidb/pull/35588
- Misc tasks and issues
  - [x] https://github.com/tikv/tikv/pull/13865
  - [x] Telemetry
  - [ ] Confirm compatibility with lazy constraint check in TiDB's pessimistic transaction
  - [ ] Find a proper behavior for the case where insert (should_not_exist) constraint check failure and write conflict occurs together https://github.com/tikv/tikv/issues/14293
  - [ ] In some rare corner cases, for_update_ts collision may cause unexpected pessimistic-rollback https://github.com/pingcap/tidb/issues/41792
  - [ ] In some rare corner cases, replayed pessimistic lock request on a key that lost its pessimistic lock may affect transaction correctness https://github.com/tikv/tikv/issues/14311
- Optional optimizations
    - [ ] Region level waking up after region change (leader or epoch change)
    - [ ] Batch re-detect deadlocks after updating lock wait info
    - [ ] Replace the implementation of `Key` from `Vec<u8>` to something like `Arc<Vec<u8>>` or `Arc<[u8]>` to reduce overhead of cloning keys (it needs to be tested whether it helps)
- Integration tests

### PR DESCRIPTION
**Pull request by MyonKeminta**
### What is changed and how it works?

Issue Number: Ref #13298 

Requires: https://github.com/tikv/tikv/pull/13680

What's Changed:

```commit-message
Add batch-resumed mode for acquire_pessimistic_lock storage command.

Now the storage command `AcquirePessimisticLock` contains an enum to determine whether it's executing a normal request or it's a batch of requests resumed after waiting for another lock.
```

……but I doubt that whether it would be better if I add a new command instead of making `AcquirePessimisticLock` an enum inside

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- It will be covered by tests after another PR that makes use of it.

Side effects

- Performance regression
    - Consumes more CPU

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by sticnarf** [comment]
> ……but I doubt that whether it would be better if I add a new command instead of making `AcquirePessimisticLock` an enum inside

I think it looks better to add a new command. Is there any difficulty doing this way?

**Comment by MyonKeminta** [comment]
> > ……but I doubt that whether it would be better if I add a new command instead of making `AcquirePessimisticLock` an enum inside
> 
> I think it looks better to add a new command. Is there any difficulty doing this way?

No. At first I was trying to reuse most of the code, but finally it looks totally different. I'll split it into two commands.

File: src/storage/txn/commands/acquire_pessimistic_lock.rs [hunk 1]
```diff
@@ -46,9 +46,9 @@ command! {
             /// later read in the same transaction.
             return_values: bool,
             min_commit_ts: TimeStamp,
-            old_values: OldValues,
```
Comment (TonsnakeLin) [inline src/storage/txn/commands/acquire_pessimistic_lock.rs:49]: Why removed the field `old_values`? Do we still support this feature of `old_value`?
um..., I know little about `old_value`.

File: src/storage/txn/commands/acquire_pessimistic_lock.rs [hunk 2]
```diff
@@ -69,27 +69,28 @@ impl CommandExt for AcquirePessimisticLock {
...
-        )))))) => info,
-        _ => panic!("unexpected mvcc error"),
-    }
-}
-
 impl<S: Snapshot, L: LockManager> WriteCommand<S, L> for AcquirePessimisticLock {
-    fn process_write(mut self, snapshot: S, context: WriteContext<'_, L>) -> Result<WriteResult> {
+    fn process_write(self, snapshot: S, context: WriteContext<'_, L>) -> Result<WriteResult> {
+        if self.allow_lock_with_conflict && self.keys.len() > 1 {
+            // Currently multiple keys with `allow_lock_with_conflict` set is not supported.
```
Comment (TonsnakeLin) [inline src/storage/txn/commands/acquire_pessimistic_lock.rs:75]: Do we support a single request which has multiple keys and `allow_lock_with_conflict` set finally ?

Comment (MyonKeminta) [reply src/storage/txn/commands/acquire_pessimistic_lock.rs:75]: Maybe we'll supported it in the future. It depends.

File: src/storage/txn/commands/acquire_pessimistic_lock.rs (hunk 1 above)
Comment (MyonKeminta) [reply src/storage/txn/commands/acquire_pessimistic_lock.rs:49]: It seems that the old_value is never assigned as any valid value outside the command, and its only purpose is to hold the results produced during the pessimistic lock command and return it after finishing the command, which seems can be done by a local variable.

File: src/storage/txn/commands/acquire_pessimistic_lock.rs [hunk 3]
```diff
@@ -104,101 +105,96 @@ impl<S: Snapshot, L: LockManager> WriteCommand<S, L> for AcquirePessimisticLock
...
+                        start_ts,
+                        lock_ttl: self.lock_ttl,
+                        for_update_ts: self.for_update_ts,
+                        wait_timeout: self.wait_timeout,
+                        return_values: self.return_values,
+                        min_commit_ts: self.min_commit_ts,
+                        check_existence: self.check_existence,
+                        is_first_lock: self.is_first_lock,
+                        lock_only_if_exists: self.lock_only_if_exists,
+                        allow_lock_with_conflict: false,
```
Comment (TonsnakeLin) [inline src/storage/txn/commands/acquire_pessimistic_lock.rs:133]: Always Set `allow_lock_with_conflict` to false instead of self.allow_lock_with_conflict?

Comment (MyonKeminta) [reply src/storage/txn/commands/acquire_pessimistic_lock.rs:133]: Sorry, it's a mistake.

File: src/storage/txn/commands/mod.rs [hunk 4]
```diff
@@ -389,7 +392,7 @@ pub struct WriteResult {
     pub to_be_write: WriteData,
     pub rows: usize,
     pub pr: ProcessResult,
-    pub lock_info: Option<WriteResultLockInfo>,
+    pub lock_info: Vec<WriteResultLockInfo>,
```
Comment (sticnarf) [inline src/storage/txn/commands/mod.rs:395]: What will be the behavior when we encounter multiple locks in the future?

File: src/storage/txn/commands/macros.rs [hunk 5]
```diff
@@ -183,6 +183,13 @@ macro_rules! gen_lock {
             crate::storage::txn::latch::Lock::new(keys)
         }
     };
+    ($field: ident: enum_match { $( $arm: pat => $expr: expr ), * }) => {
+        fn gen_lock(&self) -> crate::storage::txn::latch::Lock {
+            match &self.$field {
+                $( $arm => crate::storage::txn::latch::Lock::new($expr) ),*
+            }
+        }
+    }
```
Comment (sticnarf) [inline src/storage/txn/commands/macros.rs:192]: Where is this rule used?

File: src/storage/txn/commands/acquire_pessimistic_lock_resumed.rs [hunk 6]
```diff
@@ -0,0 +1,211 @@
...
+            {
+                if let Some(txn) = txn {
+                    if !txn.is_empty() {
+                        modifies.extend(txn.into_modifies());
+                    }
+                }
+                txn = Some(MvccTxn::new(
+                    params.start_ts,
+                    context.concurrency_manager.clone(),
+                ));
```
Comment (sticnarf) [inline src/storage/txn/commands/acquire_pessimistic_lock_resumed.rs:97]:
```suggestion
                if let Some(txn) = txn.replace(MvccTxn::new(...)) {
                    if !txn.is_empty() {
                        modifies.extend(txn.into_modifies());
                    }
                }
```

Comment (sticnarf) [reply src/storage/txn/commands/acquire_pessimistic_lock_resumed.rs:97]: `replace` is a bit simpler. Same for the `reader` below.

Comment (sticnarf) [reply src/storage/txn/commands/acquire_pessimistic_lock_resumed.rs:97]: Is `!txn.is_empty()` necessary? IMO the code will look a bit simpler if removing the `if`.

File: src/storage/txn/commands/acquire_pessimistic_lock_resumed.rs [hunk 7]
```diff
@@ -0,0 +1,211 @@
...
+            ) {
+                Ok((key_res, old_value)) => {
+                    res.push(key_res);
+                    new_locked_keys.push((params.start_ts, key.clone()));
+                    if old_value.resolved() {
+                        let key = key.append_ts(txn.start_ts);
+                        // MutationType is unknown in AcquirePessimisticLock stage.
+                        let mutation_type = None;
+                        old_values.insert(key, (old_value, mutation_type));
+                    }
```
Comment (sticnarf) [inline src/storage/txn/commands/acquire_pessimistic_lock_resumed.rs:135]: Seems we can extract this common code from acquire_pessimistic_lock, acquire_pessimistic_lock_resumed and prewrite.

File: src/storage/txn/commands/macros.rs (hunk 5 above)
Comment (MyonKeminta) [reply src/storage/txn/commands/macros.rs:192]: Ah sorry. This is not used now and I forgot to delete it.

**Comment by sticnarf** [comment]
Please fix the conflict.

**Comment by MyonKeminta** [comment]
I'll fix conflicts after https://github.com/tikv/tikv/pull/13777 is merged.

**Review by sticnarf — APPROVED** [review]

**Review by TonsnakeLin — APPROVED** [review]

File: src/storage/mod.rs [hunk 8]
```diff
@@ -1452,6 +1452,18 @@ impl<E: Engine, L: LockManager, F: KvFormat> Storage<E, L, F> {
                 )?;
                 check_key_size!(keys, self.max_key_size, callback);
             }
+            Command::AcquirePessimisticLockResumed(AcquirePessimisticLockResumed {
```
Comment (cfzjywxk) [inline src/storage/mod.rs:1455]: Should we make the command name consistent with the "wakeup mode" in kv proto in the later pr?

File: src/storage/txn/commands/acquire_pessimistic_lock_resumed.rs [hunk 9]
```diff
@@ -0,0 +1,414 @@
...
+                ResumedPessimisticLockItem {
+                    key: item.key,
+                    should_not_exist: item.should_not_exist,
+                    params: item.parameters,
+                    lock_wait_token: item.lock_wait_token,
+                }
+            })
+            .collect();
+
+        assert!(!items.is_empty());
```
Comment (cfzjywxk) [inline src/storage/txn/commands/acquire_pessimistic_lock_resumed.rs:192]: By now should we use `assert_eq(items.len(), 1)`?

**Review by cfzjywxk — APPROVED** [review]
LGTM

File: src/storage/mod.rs (hunk 8 above)
Comment (MyonKeminta) [reply src/storage/mod.rs:1455]: Sorry but I didn't quite understand. What's your suggested name of this command?

Comment (cfzjywxk) [reply src/storage/mod.rs:1455]: Since it seems we're not going to use the "resume" here(https://github.com/pingcap/kvproto/pull/872/files), should we change the name here to "Force" too?

Comment (MyonKeminta) [reply src/storage/mod.rs:1455]: This command is not used at first. When a request arrives TiKV, it's handled in `AcquirePessimisticLock` firstly; if it's blocked by lock, after waiting and woken up, this new command will be used. Therefore I think `resumed` is a proper word for it, but the behavior described by the word `Force` (which I think means the same thing as allow_lock_with_conflict) exists in both `AcquirePessimisticLock` and this new command.
