### PR TITLE
config: Make labels' format constaint consistent with PD

### LINKED ISSUE #9699: label format is inconsistent with PD
### What version of TiKV are you using?

v4.0.10

### What operating system and CPU are you using?

N/A

### Steps to reproduce

1. prepare to deploy a new cluster with tiup
1. set PD labels as 
image
1. make tikv consistent with PD
image
1. deploy it with tiup

### What did you expect?
Successfully deploy the cluster.

### What did happened?
image

### PR DESCRIPTION
**Pull request by MyonKeminta**
Signed-off-by: MyonKeminta <MyonKeminta@users.noreply.github.com>

### What problem does this PR solve?

Issue Number: close #9699 

Problem Summary: Labels can be specified via TiKV's config file and it will be then reported to PD. However the format constraint of labels is not consistent between TiKV and PD. This PR changes TiKV's format constraint so that more formats are allowed, so that it's now consistent with PD.

### What is changed and how it works?

What's Changed: Updated format constraint of labels in TiKV's config file.

### Related changes

- Need to cherry-pick to the release branch
  - It depends

### Check List 

Tests 

- Unit test

Side effects

-

### Release note 

* Make the format constraint of labels consistent with PD's.

### CODE REVIEW

File: src/server/config.rs [hunk 1]
```diff
@@ -284,35 +288,32 @@ impl Config {
     }
 }
 
-fn validate_label(s: &str, tp: &str) -> Result<()> {
+fn validate_label_key(s: &str) -> Result<()> {
+    let report_err = || box_err!("store label key: {:?} not match {}", s, LABEL_KEY_FORMAT);
+    let format = Regex::new(LABEL_KEY_FORMAT).unwrap();
```
Comment (BusyJay) [inline src/server/config.rs:293]: How about making it static?

File: src/server/config.rs [hunk 2]
```diff
@@ -284,35 +288,32 @@ impl Config {
     }
 }
 
-fn validate_label(s: &str, tp: &str) -> Result<()> {
+fn validate_label_key(s: &str) -> Result<()> {
+    let report_err = || box_err!("store label key: {:?} not match {}", s, LABEL_KEY_FORMAT);
```
Comment (BusyJay) [inline src/server/config.rs:292]: You can move it to L298 without closure.

**Review by BusyJay — APPROVED** [review]

**Review by nolouch — APPROVED** [review]
