### PR TITLE
txn: collect mvcc for error `CommitTsExpired`

### LINKED ISSUE #18441: collect mvcc info for error `CommitTsExpired` when secondary commit
## Development Task

See: https://github.com/tikv/client-go/issues/1631

The min_commit_ts can be pushed to a larger value before committing the primary. 

When committing the secondary, the commit_ts must be determined and always greater than the min_commit_ts. If not, it is an unexpected case and may be a bug. We should collect mvcc info for this case to provide more info in log for debugging.

### PR DESCRIPTION
**Pull request by lcwangchao**
### What is changed and how it works?

Issue Number: Close #18441

What's Changed:

```commit-message
When the secondary commit failed with error `CommitTsExpired`, collect the MVCC info for debugging.
```

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [ ] Need to cherry-pick to the release branch

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by v01dstar — APPROVED** [review]

File: src/storage/errors.rs [hunk 1]
```diff
@@ -364,6 +364,30 @@ pub fn extract_committed(err: &Error) -> Option<TimeStamp> {
...
+        // remove the values in default CF to reduce the size of the response.
+        mvcc.values.clear();
+        // set mvcc info to debug_info
+        let mut mvcc_debug_info = kvrpcpb::MvccDebugInfo::default();
+        mvcc_debug_info.set_key(key.to_owned());
+        mvcc_debug_info.set_mvcc(mvcc.into_proto());
+        debug_info.mvcc_info.push(mvcc_debug_info);
+    }
+}
+
```
Comment (cfzjywxk) [inline src/storage/errors.rs:390]: How about
```suggestion
fn add_debug_mvcc_for_key_error(
    err: mut kvrpcpb::KeyError,
    key: &[u8],
    mvcc_info: Option<types::MvccInfo>,
) -> kvrpcpb::KeyError{
    if let Some(mut mvcc) = mvcc_info {
        let debug_info = err.debug_info.get_or_insert_default();
        // remove the values in default CF to reduce the size of the response.
        mvcc.values.clear();
        // set mvcc info to debug_info
        let mut mvcc_debug_info = kvrpcpb::MvccDebugInfo::default();
        mvcc_debug_info.set_key(key.to_owned());
        mvcc_debug_info.set_mvcc(mvcc.into_proto());
        debug_info.mvcc_info.push(mvcc_debug_info);
    }
    err
}
```

Comment (lcwangchao) [reply src/storage/errors.rs:390]: `SingularPtrField` seems do not support `get_or_insert_default`

**Review by cfzjywxk — APPROVED** [review]
