### PR TITLE
raftstore: destroy uninitialized peer can make it possible to recreate old peer

### LINKED ISSUE #10533: destroy uninitialized peer can make it possible to recreate old peer
### What version of TiKV are you using?
v5.0.3

### What operating system and CPU are you using?
Linux

### Steps to reproduce
Supposing there are 4 stores 1, 2, 3, 4. And we schedule a region to add peer a, b, c on store 1, 2, 3 respectively. Since then a is isolated, b is leader. b decides to remove c and add d on store 4. It can succeed as quorum remains connected during the whole time. After that, 2 adds a new learner e on store 3, but remove it immediately before sending any snapshot to it. So e is uninitialized. After 2 hours, e will ask PD and find itself deleted, so will mark itself as tombstone with an **empty region**. If a is recovered and send vote requests to c, the messages can pass the peer id check and epoch check as region is uninitialized. So c will be recreated as an uninitialized peer and vote for a. Then a will become leader. There will be two leaders a and b for the region.

### What did you expect?
Only one leader at a term and the cluster work correctly.

### What did happened?
Correctness is broken.

### PR DESCRIPTION
**Pull request by PatrickNicholas**
Signed-off-by: p4tr1ck <patricknicholas@foxmail.com>

### What problem does this PR solve?

Issue Number: close #10533  

Problem Summary:

For an uninitialized peer, both epoch and peer list are empty, so a message target to a staled peer which override by an uninitialized peer will be create again. 

### What is changed and how it works?

What's Changed:

This PR will save the current peer into peer list if this region is uninitialized.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Integration test

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

```release-note
Fix the problem that destroying an uninitialized replica may cause a stalled replica be created again.
```

### CODE REVIEW

**Comment by PatrickNicholas** [comment]
@BusyJay @NingLin-P 
PTAL, feel free to let me know if you have any other questions.

**Comment by BusyJay** [comment]
Can you explain how this is fixed in the PR description?

File: components/keys/src/lib.rs [hunk 1]
```diff
@@ -56,6 +60,9 @@ pub const SNAPSHOT_RAFT_STATE_SUFFIX: u8 = 0x04;
 // For region meta
 pub const REGION_STATE_SUFFIX: u8 = 0x01;
 
+// For peer meta
+pub const PEER_STATE_SUFFIX: u8 = 0x01;
```
Comment (BusyJay) [inline components/keys/src/lib.rs:64]: I don't think it's a good idea to add a new state just for one corner case, especially when it can be fixed by no extra states.

Comment (PatrickNicholas) [reply components/keys/src/lib.rs:64]: I think this is not a corner case. On the contrary, it is the correct way to give each removed peer a separate key to record its status.

Comment (PatrickNicholas) [reply components/keys/src/lib.rs:64]: >  especially when it can be fixed by no extra states.

@BusyJay Could you roughly describe the solution?

Comment (BusyJay) [reply components/keys/src/lib.rs:64]: It's quoted in the original issue that "adding the current peer into peer list when writing tombstone".

Comment (PatrickNicholas) [reply components/keys/src/lib.rs:64]: > It's quoted in the original issue that "adding the current peer into peer list when writing tombstone".

This is to introduce a new concept just to solve a corner case, and only part of the problem can be solved. You also need to introduce some other mechanisms to resolve other case. For example, merge a region need the region info in the RegionLocalState to continue ticking for overlapped, so I need save both tombstone state and region info.

The most intuitive and easy to understand way is to record state and region info on the state of the peer, not on the state of the region. In this way, any related problems can be solved once and for all.

Comment (BusyJay) [reply components/keys/src/lib.rs:64]: > ...introduce a new concept just to solve a corner case...

What's the new concept? Using epoch and peer list to check for existence is existing flow.

> For example, merge a region need the region info in the RegionLocalState to continue ticking for overlapped, so I need save both tombstone state and region info.

Can you explain more? I don't see how adding the current peer into peer list can break this.

Comment (PatrickNicholas) [reply components/keys/src/lib.rs:64]: > Using epoch and peer list to check for existence is existing flow.
Maybe I misunderstood what you said "add current peer into peer list", do you mean add the current peer into the region in RegionLocalState if it is uninitialized?

Comment (BusyJay) [reply components/keys/src/lib.rs:64]: Yes. More precisely, if a peer is about to be destroyed, and it's uninitialized, then add the peer to the region peer list without changing epoch. So when a stale heartbeat arrives, it will find the local state in tombstone with epoch set to 0. So it will check the peer list to find if there is a peer with larger or equal ID, then hit the added peer and return.

Comment (PatrickNicholas) [reply components/keys/src/lib.rs:64]: Make sense, I will try to modify this PR.

**Comment by PatrickNicholas** [comment]
@BusyJay I have modified the code according to the comments, PTAL.

File: tests/failpoints/cases/test_stale_peer.rs [hunk 2]
```diff
@@ -211,3 +212,99 @@ fn test_stale_peer_destroy_when_apply_snapshot() {
...
+    // must_get_equal(&cluster.get_engine(4), b"k10", b"v1");
+
+    pd_client.must_add_peer(r1, new_peer(4, 4));
+    pd_client.must_remove_peer(r1, new_peer(3, 3));
+
+    for i in 11..20 {
+        cluster.must_put(format!("k{}", i).as_bytes(), b"v1");
+    }
+
+    // Add learner on store 5
```
Comment (BusyJay) [inline tests/failpoints/cases/test_stale_peer.rs:267]: You mean store 3?

File: tests/failpoints/cases/test_stale_peer.rs [hunk 3]
```diff
@@ -211,3 +212,99 @@ fn test_stale_peer_destroy_when_apply_snapshot() {
...
+    pd_client.must_add_peer(r1, new_learner_peer(3, 5));
+
+    // Ensure 5 drops all snapshot
+    let (notify_tx, _notify_rx) = mpsc::channel();
+    cluster
```
Comment (BusyJay) [inline tests/failpoints/cases/test_stale_peer.rs:272]: Should probably add filter before doing the conf change.

File: tests/failpoints/cases/test_stale_peer.rs [hunk 4]
```diff
@@ -211,3 +212,99 @@ fn test_stale_peer_destroy_when_apply_snapshot() {
...
+    }
+
+    // Remove 3 and add 4
+    pd_client.must_add_peer(r1, new_learner_peer(4, 4));
+    // must_get_equal(&cluster.get_engine(4), b"k10", b"v1");
+
+    pd_client.must_add_peer(r1, new_peer(4, 4));
+    pd_client.must_remove_peer(r1, new_peer(3, 3));
+
+    for i in 11..20 {
```
Comment (BusyJay) [inline tests/failpoints/cases/test_stale_peer.rs:263]: What's the purpose?

File: tests/failpoints/cases/test_stale_peer.rs [hunk 5]
```diff
@@ -211,3 +212,99 @@ fn test_stale_peer_destroy_when_apply_snapshot() {
...
+        .add_recv_filter(3, Box::new(DropSnapshotFilter::new(notify_tx)));
+
+    for i in 21..30 {
+        cluster.must_put(format!("k{}", i).as_bytes(), b"v1");
+    }
+
+    // Remove and destroy the uninitialized 5
+    let peer_5 = new_learner_peer(3, 5);
+    pd_client.must_remove_peer(r1, peer_5.clone());
+    cluster.must_destroy_peer(r1, 3, peer_5.clone());
```
Comment (BusyJay) [inline tests/failpoints/cases/test_stale_peer.rs:284]: You can use `configure_for_merge` to make stale peer check quicker without destroying the peer explicitly.

File: tests/failpoints/cases/test_stale_peer.rs [hunk 6]
```diff
@@ -211,3 +212,99 @@ fn test_stale_peer_destroy_when_apply_snapshot() {
...
+    cluster
+        .sim
+        .wl()
+        .add_recv_filter(2, Box::new(PartitionFilter::new(vec![1, 3])));
+    cluster
+        .sim
+        .wl()
+        .add_recv_filter(4, Box::new(PartitionFilter::new(vec![1, 3])));
+
+    cluster.sim.wl().clear_send_filters(1);
```
Comment (BusyJay) [inline tests/failpoints/cases/test_stale_peer.rs:299]: Why not just 
```
cluster.clear_send_filters();
cluster.partition(vec![1, 3], vec![2, 4]);
```
?

File: tests/failpoints/cases/test_stale_peer.rs [hunk 7]
```diff
@@ -211,3 +212,99 @@ fn test_stale_peer_destroy_when_apply_snapshot() {
...
+
+    // Add learner on store 5
+    pd_client.must_add_peer(r1, new_learner_peer(3, 5));
+
+    // Ensure 5 drops all snapshot
+    let (notify_tx, _notify_rx) = mpsc::channel();
+    cluster
+        .sim
+        .wl()
+        .add_recv_filter(3, Box::new(DropSnapshotFilter::new(notify_tx)));
```
Comment (BusyJay) [inline tests/failpoints/cases/test_stale_peer.rs:275]: Or you can use send filter like `RegionPacketFilter`, so in the end explicit clean can be avoided.

File: tests/failpoints/cases/test_stale_peer.rs [hunk 8]
```diff
@@ -211,3 +212,99 @@ fn test_stale_peer_destroy_when_apply_snapshot() {
...
+        .sim
+        .wl()
+        .add_recv_filter(4, Box::new(PartitionFilter::new(vec![1, 3])));
+
+    cluster.sim.wl().clear_send_filters(1);
+    cluster.sim.wl().clear_send_filters(3);
+    cluster.sim.wl().clear_recv_filters(3);
+
+    sleep_ms(
+        6u64 * cluster.cfg.raft_store.raft_election_timeout_ticks as u64
```
Comment (BusyJay) [inline tests/failpoints/cases/test_stale_peer.rs:304]: What is `6`?

File: tests/failpoints/cases/test_stale_peer.rs (hunk 6 above)
Comment (PatrickNicholas) [reply tests/failpoints/cases/test_stale_peer.rs:299]: This is not an atomic operation, maybe some messages are send from 1 to 2 before  `cluster.partition`, after `cluster.clear_send_filters`.

Comment (BusyJay) [reply tests/failpoints/cases/test_stale_peer.rs:299]: Yes, but it's simple and too fast to meet race.

File: tests/failpoints/cases/test_stale_peer.rs (hunk 8 above)
Comment (PatrickNicholas) [reply tests/failpoints/cases/test_stale_peer.rs:304]: Randomly selected, just ensure enough intervals so that peer 1 would trigger a election.

File: tests/failpoints/cases/test_stale_peer.rs (hunk 4 above)
Comment (BusyJay) [reply tests/failpoints/cases/test_stale_peer.rs:263]: Then a single write should be sufficient.

File: tests/failpoints/cases/test_stale_peer.rs (hunk 8 above)
Comment (BusyJay) [reply tests/failpoints/cases/test_stale_peer.rs:304]: Shouldn't `3` be enough? The default election timeout is 250ms in test, 6 times means 1.5 seconds.

File: tests/integrations/raftstore/test_conf_change.rs [hunk 9]
```diff
@@ -79,8 +79,8 @@ fn test_simple_conf_change<T: Simulator>(cluster: &mut Cluster<T>) {
     // peer 3 must exist
     must_get_equal(&engine_3, b"k3", b"v3");
 
-    // add peer 2 then remove it again.
-    pd_client.must_add_peer(r1, new_peer(2, 2));
+    // add peer 22 then remove it again.
```
Comment (BusyJay) [inline tests/integrations/raftstore/test_conf_change.rs:82]: Why change this?

File: tests/failpoints/cases/test_stale_peer.rs (hunk 5 above)
Comment (PatrickNicholas) [reply tests/failpoints/cases/test_stale_peer.rs]: I think it would be easier to understand if you explicitly destroying the peer?

File: tests/integrations/raftstore/test_conf_change.rs (hunk 9 above)
Comment (PatrickNicholas) [reply tests/integrations/raftstore/test_conf_change.rs]: Please ignore, this is cherry-picked from the previous changes, I have deleted it.

File: tests/failpoints/cases/test_stale_peer.rs (hunk 8 above)
Comment (PatrickNicholas) [reply tests/failpoints/cases/test_stale_peer.rs:302]: Ok, I will change to 3. Would it be better to add a helper to unify this logic?

Comment (BusyJay) [reply tests/failpoints/cases/test_stale_peer.rs:302]: Yes. Perhaps you can add a send filter to capture `VoteResponse` from store 3, which should collect nothing and always timeout.

File: tests/failpoints/cases/test_stale_peer.rs (hunk 5 above)
Comment (BusyJay) [reply tests/failpoints/cases/test_stale_peer.rs]: Yes, I don't have strong opinion on this. Stale peer check is the real code path that can trigger problem.

**Review by BusyJay — COMMENTED** [review]
The case can pass even without the fix.

File: components/test_raftstore/src/cluster.rs [hunk 10]
```diff
@@ -1570,6 +1572,38 @@ impl<T: Simulator> Cluster<T> {
             sleep_ms(20);
         }
     }
+
+    pub fn destroy_peer(
```
[the remark this answers is not in the document]
Comment (PatrickNicholas) [reply components/test_raftstore/src/cluster.rs]: I have renamed this function to gc_peer, PTAL.

**Comment by BusyJay** [comment]
> The case can pass even without the fix.

Any updates? You can verify it by running
```
env EXTRA_CARGO_ARGS=test_destroy_uninitialized_peer_when_there_exists_old_peer make test
```

**Comment by PatrickNicholas** [comment]
> > The case can pass even without the fix.
> 
> Any updates? You can verify it by running
> 
> ```
> env EXTRA_CARGO_ARGS=test_destroy_uninitialized_peer_when_there_exists_old_peer make test
> ```

Do you mean `test_destroy_uninitialized_peer_when_there_exists_old_peer` would pass even without saving current peer into RegionLocalState? I have verified by:

```
git checkout c73c5512d1bcadec784fb6f82f886db8901e6b7a
cargo test -p tests --test failpoints -- test_destroy_uninitialized_peer_when_there_exists_old_peer
```

The result is :

```
failures:
    cases::test_stale_peer::test_destroy_uninitialized_peer_when_there_exists_old_peer

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 167 filtered out; finished in 2.78s

error: test failed, to rerun pass '-p tests --test failpoints'
```

Now it is the latest change, please give a some sugession if you have any question.

**Comment by BusyJay** [comment]
I test it with:
```
git checkout master -- components/raftstore
cargo test -p tests --test failpoints -- test_destroy_uninitialized_peer_when_there_exists_old_peer
```
.

And no failure is reported.

I guess the latest change break the test case.

**Comment by PatrickNicholas** [comment]
> I guess the latest change break the test case.

Yes, I have fixed.

**Review by BusyJay — APPROVED** [review]

**Comment by BusyJay** [comment]
Remember to add release note for the fix.

**Review by NingLin-P — APPROVED** [review]
