### PR TITLE
raftstore: spawn the whole autosplit task in event loop

### LINKED ISSUE #8574: 09-01 Performance regression on wide table
## Bug Report

```
Version:
tidb: 1cab3d59471a536b5d3d8dca7b07b209f9e8e363(master) 2020-09-01 13:58:35
tikv: 1c61d3903cd42348e036317124704fc7f60dff55(master) 2020-09-01 08:15:06
pd: 68767909a740e0a58cd75bf7b5aa06574a0480e2(master) 2020-09-01 08:24:39

Compare:
tidb: https://github.com/pingcap/tidb/compare/1cab3d5...1cab3d5
tikv: https://github.com/tikv/tikv/compare/fe3280b...1c61d39
pd: https://github.com/pingcap/pd/compare/6876790...6876790

workload: <wide_point_select>

tidb_max_cpu: 9.67, delta: -52.67%
tikv_max_cpu: 0.01, delta: -99.91%
tidb_max_memory: 171.24 MiB, delta: -7.42%

tps : 17849.15 ± 0.0000% (std=0.00) delta: -62.66%
qps : 17849.15 ± 0.0000% (std=0.00) delta: -62.66%
lat_avg : 14.34 ± 0.0000% (std=0.00) delta: 168.04%
lat_99th : 15.00 ± 0.0000% (std=0.00) delta: 1.83%

workload: <wide_range_select>

tidb_max_cpu: 10.76, delta: -47.23%
tikv_max_cpu: 7.74, delta: -45.38%
tidb_max_memory: 201.93 MiB, delta: 2.19%

tps : 3455.48 ± 0.0000% (std=0.00) delta: -56.19%
qps : 3455.48 ± 0.0000% (std=0.00) delta: -56.19%
lat_avg : 73.95 ± 0.0000% (std=0.00) delta: 127.89%
lat_99th : 123.28 ± 0.0000% (std=0.00) delta: 9.42%
```

## What version of TiKV are you using?

1c61d3903cd42348e036317124704fc7f60dff55

### PR DESCRIPTION
**Pull request by hunterlxt**
Signed-off-by: Xintao <hunterlxt@live.com>

### What problem does this PR solve?

Issue Number: close #8574

Problem Summary: 
tikv will crash when execute `LocalPool` executor from within another executor. Runnable do jobs in `LocalSet` executor, but when we try to use `futures::executor::block_on`, it actually do the job in `LocalPool`. Two executors conflict with each other.

Solution:
1. We can pass the handle of `LocalSet` and use its method `block_on`. 
2. Another way is to use `await` and spawn the task to the event loop. This PR choose the latter

### What is changed and how it works?

What's Changed:
spawn the whole autosplit task in event loop so we can await pd operation to switch to another task.

### Release note 
- Spawn the whole `autosplit` task in event loop.

### CODE REVIEW

File: components/raftstore/src/store/worker/pd.rs [hunk 1]
```diff
@@ -1023,20 +1025,30 @@ where
...
+                                split_info.peer,
+                                true,
+                                Callback::None,
+                                String::from("auto_split"),
+                            );
+                        }
                     }
-                }
+                };
+                spawn_local(f);
```
Comment (BusyJay) [inline components/raftstore/src/store/worker/pd.rs:1051]: So will it be executed immediately? I think it introduces race between tasks if it's executed later.

Comment (gengliqi) [reply components/raftstore/src/store/worker/pd.rs:1051]: I think it behaves the same as before because the `handle_ask_batch_split` also needs to wait for the response from PD.

Comment (BusyJay) [reply components/raftstore/src/store/worker/pd.rs:1051]: I don't get it. How is it related to make `get_region_by_id` async?

Comment (hunterlxt) [reply components/raftstore/src/store/worker/pd.rs:1051]: @BusyJay Can you describe an example which race exists between tasks for this PR?

**Comment by gengliqi** [comment]
By the way, TiKV crashes in the previous code which means the unit tests do not cover this case i.e. `Task::AutoSplit`. I find it is added from https://github.com/tikv/tikv/pull/6663 @lhy1024  Maybe we should add test(s)?

File: components/raftstore/src/store/worker/pd.rs (hunk 1 above)
Comment (BusyJay) [reply components/raftstore/src/store/worker/pd.rs:1051]: For example, `Task::AutoSplit` and `Task::AskSplit` can arrive almost the same time. In the past, they will be executed one by one. Now auto split can be delay and `AskSplit` is handled first. It's just one of the situations that changes, and perhaps no harm. No sure if there are any other cases that can cause problems.

Comment (hunterlxt) [reply components/raftstore/src/store/worker/pd.rs:1051]: Yes, spawn means we don't care about the sequence. Maybe the original author can end this issue /cc @lhy1024

File: components/raftstore/src/store/worker/pd.rs [hunk 2]
```diff
@@ -528,8 +527,12 @@ where
         spawn_local(f);
     }
 
+    // Note: The parameter doesn't contain `self` because this function may
+    // be called in an asynchronous context.
     fn handle_ask_batch_split(
-        &self,
+        router: RaftRouter<EK, ER>,
```
Comment (BusyJay) [inline components/raftstore/src/store/worker/pd.rs:533]: Why change it into a function?

File: components/raftstore/src/store/worker/pd.rs (hunk 1 above)
Comment (lhy1024) [reply components/raftstore/src/store/worker/pd.rs:1051]: i think we may not care about the change of sequence

**Review by lhy1024 — COMMENTED** [review]
> By the way, TiKV crashes in the previous code which means the unit tests do not cover this case i.e. `Task::AutoSplit`. I find it is added from #6663 @lhy1024 Maybe we should add test(s)?

yep, you are right, I will do it later

File: components/raftstore/src/store/worker/pd.rs (hunk 2 above)
Comment (hunterlxt) [reply components/raftstore/src/store/worker/pd.rs:533]: This avoids using self inside the async context.

Comment (BusyJay) [reply components/raftstore/src/store/worker/pd.rs:533]: It's not an async function.

**Review by lhy1024 — APPROVED** [review]

File: components/raftstore/src/store/worker/pd.rs (hunk 2 above)
Comment (hunterlxt) [reply components/raftstore/src/store/worker/pd.rs:533]: but it may be called in other async context

Comment (hunterlxt) [reply components/raftstore/src/store/worker/pd.rs:533]: rust cannot infer lifetime for `Runner`

**Review by ti-srebot — APPROVED** [review]
