### PR TITLE
raftstore: invalidate follower read cache when region is destroyed

### LINKED ISSUE #18570: Jepsen monotonic fails due to snapshot after peer is destroyed
### What version of TiKV are you using?

[`72760df16e6ccd931eb91eb6d530b225f3583767`](https://github.com/tikv/tikv/commit/72760df16e6ccd931eb91eb6d530b225f3583767)
### What operating system and CPU are you using?

x64

### Steps to reproduce

Run Jepsen with follower read and some nemesis, see the command.

```
"--nemesis=schedules,kill,stop",
"--txn-mode=optimistic",
"--use-index",
"--workload=monotonic"
```

### What did you expect?

The monotonic test passes.

### What did happened?

```
458750803976650767 = 2025-06-15T13:50:37.533Z
T70 = {:type :ok, :f :read, :value {0 467, 1 437, 2 437, 3 422, 4 433, 5 432, 6 444, 7 433}, :process 5, :time 26564587360, :txn-info {:txn_scope \"global\", :start_ts 458750803976650767, :commit_ts 0, :txn_commit_mode \"\", :async_commit_fallback false, :one_pc_fallback false, :pipelined false, :flush_wait_ms 0}, :index 13794}

458750804028817509 = 2025-06-15T13:50:37.732Z
T71 = {:type :ok, :f :read, :value {0 470, 1 -1, 2 442, 3 423, 4 439, 5 436, 6 444, 7 437}, :process 0, :time 28168159258, :txn-info {:txn_scope \"global\", :start_ts 458750804028817509, :commit_ts 0, :txn_commit_mode \"\", :async_commit_fallback false, :one_pc_fallback false, :pipelined false, :flush_wait_ms 0}, :index 14616}

458750797850345486 = 2025-06-15T13:50:14.163Z
T72 = {:type :ok, :f :read, :value {0 -1, 1 0, 2 -1, 3 2, 4 1, 5 0, 6 1, 7 -1}, :process 0, :time 3767442452, :txn-info {:txn_scope \"global\", :start_ts 458750797850345486, :commit_ts 0, :txn_commit_mode \"\", :async_commit_fallback false, :one_pc_fallback false, :pipelined false, :flush_wait_ms 0}, :index 162}
```

T71(458750804028817509) should not see empty result set in register 1.

From TiDB's slowlog, it takes 1.38s to get the snapshot `scan_detail: {total_keys: 1, get_snapshot_time: 1.38s ...}`, and from the coprocessor's slow log, we can infer the snapshot is returned about `13:50:39`.

```log
[2025/06/15 13:50:39.152 +00:00] [INFO] [coprocessor.go:1515] ["[TIME_COP_WAIT] resp_time:1.383065034s txnStartTS:458750804028817509 region_id:696 store_addr:node-0.node-peer.jepsen-tps-7871563-1-252:20160 stats:Cop:{num_rpc:1, total_time:1.38s} kv_process_ms:1 kv_wait_ms:1381 kv_read_ms:1 processed_versions:0 total_versions:1 rocksdb_delete_skipped_count:1296 rocksdb_key_skipped_count:1503 rocksdb_cache_hit_count:0 rocksdb_read_count:0 rocksdb_read_byte:0"] [conn=4162846728] [session_alias=]
```

The strange region id is 696, and tikv is node-0.

node-0's log shows that region 696's peer is destroyed before `13:50:37.821` on this store.

```
[2025/06/15 13:50:37.820 +00:00] [INFO] [apply.rs:2533] ["conf change successfully"] [current_region="id: 696 start_key: 7480000000000000FF7C5F698000000000FF0000010380000000FF0000000003800000FF000000000C038000FF0000000000000000FD end_key: 7800000000000000FB region_epoch { conf_ver: 29 version: 154 } peers { id: 698 store_id: 8 } peers { id: 1171 store_id: 7 } peers { id: 6070 store_id: 2 }"] [original_region="id: 696 start_key: 7480000000000000FF7C5F698000000000FF0000010380000000FF0000000003800000FF000000000C038000FF0000000000000000FD end_key: 7800000000000000FB region_epoch { conf_ver: 28 version: 154 } peers { id: 698 store_id: 8 } peers { id: 701 store_id: 17 role: Learner } peers { id: 1171 store_id: 7 } peers { id: 6070 store_id: 2 }"] [changes="[change_type: RemoveNode peer { id: 701 store_id: 17 role: Learner }]"] [peer_id=701] [region_id=696] [thread_id=147]
[2025/06/15 13:50:37.820 +00:00] [INFO] [router.rs:283] ["shutdown mailbox"] [region_id=696] [thread_id=147]
[2025/06/15 13:50:37.820 +00:00] [INFO] [raft.rs:2706] ["switched to configuration"] [config="Configuration { voters: Configuration { incoming: Configuration { voters: {1171, 698, 6070} }, outgoing: Configuration { voters: {} } }, learners: {}, learners_next: {}, auto_leave: false }"] [raft_id=701] [region_id=696] [thread_id=143]
[2025/06/15 13:50:37.820 +00:00] [INFO] [peer.rs:4060] ["delays destroy"] [reason=UnFlushLogGc] [merged_by_target=false] [peer_id=701] [region_id=696] [thread_id=143]
[2025/06/15 13:50:37.820 +00:00] [INFO] [peer.rs:4115] ["starts destroy"] [is_latest_initialized=true] [is_peer_initialized=true] [merged_by_target=false] [peer_id=701] [region_id=696] [thread_id=144]
[2025/06/15 13:50:37.820 +00:00] [INFO] [peer.rs:1405] ["begin to destroy"] [peer_id=701] [region_id=696] [thread_id=144]
[2025/06/15 13:50:37.820 +00:00] [INFO] [pd.rs:1732] ["remove peer statistic record in pd"] [region_id=696] [thread_id=37]
[2025/06/15 13:50:37.820 +00:00] [INFO] [peer_storage.rs:1120] ["finish clear peer meta"] [takes=5.447µs] [raft_key=1] [apply_key=1] [meta_key=1] [region_id=696] [thread_id=144]
[2025/06/15 13:50:37.821 +00:00] [INFO] [peer.rs:1517] ["peer destroy itself"] [keep_data=false] [clean=true] [takes=370.213µs] [peer_id=701] [region_id=696] [thread_id=144]
[2025/06/15 13:50:37.821 +00:00] [INFO] [region.rs:514] ["register deleting data in range"] [end_key=7A7800000000000000FB] [start_key=7A7480000000000000FF7C5F698000000000FF0000010380000000FF0000000003800000FF000000000C038000FF0000000000000000FD] [region_id=696] [thread_id=138]
[2025/06/15 13:50:37.821 +00:00] [INFO] [router.rs:283] ["shutdown mailbox"] [region_id=696] [thread_id=144]
[2025/06/15 13:50:37.821 +00:00] [INFO] [region.rs:553] ["delete data in range because of stale"] [end_key=7A7800000000000000FB] [start_key=7A7480000000000000FF7C5F698000000000FF0000010380000000FF0000000003800000FF000000000C038000FF0000000000000000FD] [region_id=696] [thread_id=138]
```

Since the peer is already destroyed in that time, a region error should be raised instead of a snapshot.

### PR DESCRIPTION
**Pull request by you06**
### What is changed and how it works?

Issue Number: close #18570

What's Changed:

```commit-message
Set `read_index_safe_ts` to 0 when `RegionReadProgress` is paused to prevent unsafe follower read.
```

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [ ] Need to cherry-pick to the release branch

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note

```release-note
Fix the issue that follower read may get wrong result through follower read cache.
```

### CODE REVIEW

File: components/raftstore/src/store/util.rs [hunk 1]
```diff
@@ -1524,11 +1524,12 @@ impl RegionReadProgress {
             find_store_id(&core.leader_info.peers, core.leader_info.leader_id)
     }
 
-    /// Reset `safe_ts` to 0 and stop updating it
+    /// Reset `safe_ts` and `read_index_safe_ts` to 0 and stop updating them
     pub fn pause(&self) {
         let mut core = self.core.lock().unwrap();
         core.pause = true;
         self.safe_ts.store(0, AtomicOrdering::Release);
+        self.read_index_safe_ts.store(0, AtomicOrdering::Release);
```
Comment (cfzjywxk) [inline components/raftstore/src/store/util.rs:1538]: Perhaps we should also reset it in `disacrd` function, and check if there are other missing operations.

Comment (mittalrishabh) [reply components/raftstore/src/store/util.rs:1532]: we should check for core.pause and any other invarant in check_stale_read_safe() too. It is a consolidated place to see if safe_ts or read_index_safe_ts is valid or not.

Comment (mittalrishabh) [reply components/raftstore/src/store/util.rs:1538]: +1

Comment (you06) [reply components/raftstore/src/store/util.rs:1538]: With a fast check, I think it won't affect follower read cache because `discard` is invoked in leader only after `PrepareMerge` is committed.

But we may not handle the `read_index_safe_ts` well when the region is merged  (see merging `safe_ts` below).

https://github.com/tikv/tikv/blob/4d704035f878f5ac2fe027e383b6d2297e8e6712/components/raftstore/src/store/util.rs#L1700

Without the correction like `safe_ts`, the source region may inherit from target's larger `read_index_safe_ts` after region merge.

I'll introduce a test for this case which will also cover the `discard` code path.

**Comment by you06** [comment]
/hold
Need to add more test cases.

**Review by cfzjywxk — APPROVED** [review]
LGTM

File: tests/failpoints/cases/test_replica_read.rs [hunk 2]
```diff
@@ -902,16 +918,491 @@ fn test_read_index_cache() {
...
+        new_peer(1, 1),
         r1.clone(),
         b"k1",
         Some(2),
         Duration::from_millis(2000),
     );
 }
+
+#[test_case(test_raftstore::new_server_cluster)]
+fn test_read_index_cache_in_destroied_peer() {
```
Comment (mittalrishabh) [inline tests/failpoints/cases/test_replica_read.rs]: change it to test_read_index_cache_in_destroyed_peer

File: components/raftstore/src/store/util.rs [hunk 3]
```diff
@@ -1545,20 +1550,28 @@ impl RegionReadProgress {
...
             .store(core.read_state.ts, AtomicOrdering::Release);
+        self.read_index_safe_ts.store(0, AtomicOrdering::Release);
     }
 
     pub fn safe_ts(&self) -> u64 {
         self.safe_ts.load(AtomicOrdering::Acquire)
     }
 
     pub fn update_read_index_safe_ts(&self, start_ts: u64) {
+        if start_ts == u64::MAX {
```
Comment (mittalrishabh) [inline components/raftstore/src/store/util.rs:1564]: what is the scenario where we can get u64::MAX in start_ts

File: components/raftstore/src/store/util.rs [hunk 4]
```diff
@@ -1524,18 +1527,20 @@ impl RegionReadProgress {
             find_store_id(&core.leader_info.peers, core.leader_info.leader_id)
     }
 
-    /// Reset `safe_ts` to 0 and stop updating it
+    /// Reset `safe_ts` and `read_index_safe_ts` to 0 and stop updating them
     pub fn pause(&self) {
         let mut core = self.core.lock().unwrap();
         core.pause = true;
         self.safe_ts.store(0, AtomicOrdering::Release);
+        self.read_index_safe_ts.store(0, AtomicOrdering::Release);
```
Comment (mittalrishabh) [inline components/raftstore/src/store/util.rs:1538]: can we move safe_ts and read_index_safe_ts to one function to reset it. They are read in the same function too(check_stale_read_safe).

File: components/raftstore/src/store/util.rs [hunk 5]
```diff
@@ -1524,18 +1527,20 @@ impl RegionReadProgress {
...
     }
 
     /// Discard incoming `read_state` item and stop updating `safe_ts`
     pub fn discard(&self) {
         let mut core = self.core.lock().unwrap();
         core.pause = true;
         core.discard = true;
+        self.read_index_safe_ts.store(0, AtomicOrdering::Release);
```
Comment (mittalrishabh) [inline components/raftstore/src/store/util.rs:1546]: why are we only reseting read_index_safe_ts and not the safe_ts here.

File: components/raftstore/src/store/util.rs [hunk 6]
```diff
@@ -1545,20 +1550,28 @@ impl RegionReadProgress {
...
 
     pub fn safe_ts(&self) -> u64 {
         self.safe_ts.load(AtomicOrdering::Acquire)
     }
 
     pub fn update_read_index_safe_ts(&self, start_ts: u64) {
+        if start_ts == u64::MAX {
+            return;
+        }
+        let core = self.core.lock().unwrap();
```
Comment (mittalrishabh) [inline components/raftstore/src/store/util.rs:1564]: why do we want to check for core.pause or discard here. I think its an overkill to take lock in io path.

File: tests/failpoints/cases/test_replica_read.rs [hunk 7]
```diff
@@ -902,16 +918,491 @@ fn test_read_index_cache() {
...
+    let cluster = Arc::new(Mutex::new(new_cluster(0, 4)));
+    let pd_client = cluster.lock().unwrap().pd_client.clone();
+
+    fn async_snapshot(
```
Comment (mittalrishabh) [inline tests/failpoints/cases/test_replica_read.rs:940]: we already have `async_get_snapshot` used in the test case above. Can't we use the same one.

File: components/raftstore/src/store/util.rs [hunk 8]
```diff
@@ -1545,20 +1550,28 @@ impl RegionReadProgress {
...
+        if core.pause || core.discard {
+            return;
+        }
```
Comment (mittalrishabh) [inline components/raftstore/src/store/util.rs:1570]: this check made me think what happen if we return the response of read_index message after region is destroyed. What happen in this scenario
1. send read_index message
2. region destroyed
3. read index message came
4. snapshot read happen

File: components/raftstore/src/store/util.rs (hunk 3 above)
Comment (you06) [reply components/raftstore/src/store/util.rs:1564]: u64::MAX start_ts can be used in auto-commit point get, but should never be updated to max-ts or read-index-safe-ts.

`start_ts == u64::MAX` here is unreachable, just a sanity check.

Comment (mittalrishabh) [reply components/raftstore/src/store/util.rs:1564]: its already been taken care in https://github.com/tikv/tikv/blob/31f529e914a589680a42b3598d6f839ebd39a34b/src/server/raftkv/mod.rs#L873 .

File: tests/failpoints/cases/test_replica_read.rs (hunk 7 above)
Comment (you06) [reply tests/failpoints/cases/test_replica_read.rs:940]: For 2 reasons, `async_get_snapshot` is not a good option:

- It needs a mutable borrow, which cannot run in another thread.
- The response doesn't contain the snapshot so it's unable to check the read result.

File: components/raftstore/src/store/util.rs (hunk 8 above)
Comment (you06) [reply components/raftstore/src/store/util.rs:1570]: The read index after region is destroyed will be dropped by term mismatch.

https://github.com/tikv/tikv/blob/81055e47dc3fc41184067b2fa5cc4ee525df0651/components/raftstore/src/store/peer.rs#L3687-L3693

Comment (mittalrishabh) [reply components/raftstore/src/store/util.rs:1570]: I think we should add this check here too 
https://github.com/tikv/tikv/blob/81055e47dc3fc41184067b2fa5cc4ee525df0651/components/raftstore/src/store/peer.rs#L3656

Comment (mittalrishabh) [reply components/raftstore/src/store/util.rs:1570]: update_read_index_safe_ts() is updated only through raft. I am not sure if we need to have this check if we add the above suggested check.

Comment (you06) [reply components/raftstore/src/store/util.rs:1570]: Good catch, looks dropped read request can update the `read_index_safe_ts`.

Comment (you06) [reply components/raftstore/src/store/util.rs:1570]: > The read index after region is destroyed will be dropped by term mismatch.

A read-index in destroyed peer is not dropped here, it's controlled by `pending_remove`

https://github.com/tikv/tikv/blob/ed504baa35c36fa2f05ee1e5bb8f5e3f60da46d6/components/raftstore/src/store/peer.rs#L743-L748

> 1. send read_index message
> 2. region destroyed
> 3. read index message came
> 4. snapshot read happen

So the step3's read-index message will be rejected in this case.

File: components/raftstore/src/store/util.rs (hunk 3 above)
Comment (you06) [reply components/raftstore/src/store/util.rs:1564]: This check won't hurt anything and will prevent misuses by other developers.

File: components/raftstore/src/store/util.rs (hunk 4 above)
Comment (you06) [reply components/raftstore/src/store/util.rs:1538]: We treat read_index_safe_ts and safe_ts in different ways. The safe_ts is usually lagged much more because it's also used by ticdc to confirm the transactions which are ready to be synced.

The condition `future_commit_ts > safe_ts` holds true, but future_commit_ts > read_index_safe_ts doesn't.

Since `read_index_safe_ts` typically advances at a faster pace, we simply choose to reset it when there are changes to region meta or status. That's why I didn't introduce a function to manage both `safe_ts` and `read_index_safe_ts`.

File: components/raftstore/src/store/util.rs (hunk 5 above)
Comment (you06) [reply components/raftstore/src/store/util.rs:1546]: There is no known issue caused by skipping resetting `read_index_safe_ts` here, this reset is just for the rule "we simply choose to reset it when there are changes to region meta or status".

File: components/raftstore/src/store/util.rs [hunk 9]
```diff
@@ -1545,20 +1550,28 @@ impl RegionReadProgress {
...
         let current_ts: u64 = self.read_index_safe_ts();
         if start_ts > current_ts {
             let compare_exchange = self.read_index_safe_ts.compare_exchange(
                 current_ts,
                 start_ts,
-                AtomicOrdering::SeqCst,
-                AtomicOrdering::Relaxed,
+                AtomicOrdering::AcqRel,
+                AtomicOrdering::Acquire,
```
Comment (ekexium) [inline components/raftstore/src/store/util.rs:1577]: Any comment to explain the change in Ordering?

File: components/test_raftstore/src/util.rs [hunk 10]
```diff
@@ -1897,3 +1897,13 @@ pub fn wait_down_peers<T: Simulator>(cluster: &Cluster<T>, count: u64, peer: Opt
         peers, count, peer
     );
 }
+
+pub fn get_region_read_index_safe_ts<T: Simulator>(
```
Comment (ekexium) [inline components/test_raftstore/src/util.rs:1901]: If it cannot be `cfg(test)`, maybe we should leave a comment stating it's only for tests.

**Review by ekexium — COMMENTED** [review]
Generally LGTM.
I'm considering a minor refactoring, such as extracting an on_region_change method, to better express the rationale.

File: components/raftstore/src/store/util.rs (hunk 9 above)
Comment (you06) [reply components/raftstore/src/store/util.rs:1577]: The memory order change is to fix the `read_index_safe_ts`'s usage of `Relaxed`, which is not guaranteed to read the update of `SeqCst`.

Since I change the read order into `Acquire`, and replace the other atomic order with `AcqRel` just like `safe_ts`.

I'll add some comments in the struct definition.

File: components/test_raftstore/src/util.rs (hunk 10 above)
Comment (you06) [reply components/test_raftstore/src/util.rs:1901]: It's under the `test_raftstore` component. I don't think we need to worry about it being used outside of tests. Also, all functions in this crate aren't marked with `cfg(test)`.
