### PR TITLE
raftstore: avoid early hibernate if pending on applying logs when restart

### LINKED ISSUE #18233: Raft peers may get stuck in busy apply state post TiKV startup
## Bug Report

We observed that after a TiKV instance restarted, some peers got stuck in the "busy apply" state for 2 minutes while there was no Raft log lag. As a result, the server reported the "Server is busy" error and prevented PD from transferring leaders to the TiKV instance.

Image

Image

During this time, Raftstore had no operations, indicating that the peers were not performing any actions.

Image

One potential cause is that the peers went into hibernation before successfully exiting the "busy apply" state.

Image

### What version of TiKV are you using?
v8.5.1

### PR DESCRIPTION
**Pull request by LykxSassinator**
### What is changed and how it works?

Issue Number: Close #18233

What's Changed:

In previous work #16239, we introduced the `busy_on_apply` state to indicate
whether a `Peer` is pending the application of pending Raft logs upon restart.

However, this approach misses a corner case: if the `Peer` quickly enters the
`hibernate` state after restarting, the `busy_on_apply` state may not be updated
in a timely manner. This results in the Node failed to update the count of pending
applying regions, continuously reporting an incorrect `is_busy == true` state to PD. 
Consequently, this can slow down the rolling-restart progress more than expected.

Therefore, this PR addresses this issue by updating the applied state in `on_apply_res`.

```commit-message
Fix the bug where some hibernated peers, marked with `busy_on_apply == true`, 
cannot be reset with normal even thought the `applied_index == committed_index`.
```

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [ ] Need to cherry-pick to the release branch

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note

```release-note
Fix the bug where some hibernated peers, marked with `busy_on_apply == true`, 
cannot be reset with normal even thought the `applied_index == committed_index`.
```

### CODE REVIEW

File: components/raftstore/src/store/peer.rs [hunk 1]
```diff
@@ -1609,6 +1609,8 @@ where
                 && !self.is_leader()
                 // Keep ticking if it's waiting for snapshot.
                 && !self.wait_data
+                // Keep ticking if it still has some pending and unapplied raft logs.
```
Comment (overvenus) [inline components/raftstore/src/store/peer.rs:1612]: How about check and update `busy_on_apply` on `on_apply_res`? Keeping tick might wake up hibernated peers.

Comment (LykxSassinator) [reply components/raftstore/src/store/peer.rs:1612]: I've also considered this solution but not adapt it.

IMO, since restarting a single node will wake up all hibernated regions on that node, applying this change will not introduce higher pressure than the peak load during this period. Therefore, simply ticking until the unapplied state has been updated is acceptable.

Comment (hbisheng) [reply components/raftstore/src/store/peer.rs:1612]: I'm fine with the current approach as well. I agree that the `on_apply_res` approach will allow peers to go into hibernation earlier, saving some ticks. But the difference might not matter a lot because the code change only affects the first few minutes after a TiKV restart, when the server is still in the busy apply stage. During this time, the server has no leaders and some extra ticks likely won't be a significant issue.

**Review by hbisheng — APPROVED** [review]

File: components/raftstore/src/store/peer.rs (hunk 1 above)
Comment (overvenus) [reply components/raftstore/src/store/peer.rs:1612]: Besides saving ticks, I am also considering maintainability. Since the Hibernate region-related code is already complex, it's better to leave it unchanged. To me, it seems more intuitive to check and update the `busy_on_apply` field in `on_apply_res` rather than in `on_raft_base_tick`.

Also, why was it originally checked in `on_raft_base_tick`? Is there a reason I'm missing?

Comment (LykxSassinator) [reply components/raftstore/src/store/peer.rs]: To safely unify the initialization of the check mechanism for the `busy_on_apply` state, the following cases will be covered, specifically after the peers are restarted and their roles (either "follower" or "leader") have been confirmed:
1. Peers with `applied_index` == `committed_index` will be checked only once.
2. Peers with `applied_index` <= `committed_index` can be updated using the Raft base tick.


> Besides saving ticks, I am also considering maintainability. Since the Hibernate region-related code is already complex, it's better to leave it unchanged.

Accepted. This point is reasonable and acceptable, as it avoids increasing the complexity of the Hibernate mechanism.

**Review by hbisheng — APPROVED** [review]

**Review by overvenus — APPROVED** [review]
