### PR TITLE
raftstore: remove ts for bucket keys

### LINKED ISSUE #12549: raftstore: bucket keys should not contain TS information
### What version of TiKV are you using?

6.1-alpha

### What operating system and CPU are you using?
centos 8

### Steps to reproduce
enable dynamic region and enable region buckets.
run sysbench and dump region information in pd-ctl

### What did you expect?
the bucket keys in region should not contain timestamp
### What did happened?
the bucket keys in region contains timestamp
"buckets": [
        "7480000000000011FF4C5F728000000000FF0761680000000000FA",
        "7480000000000011FF4C5F728000000000FF0F6FAA0000000000FAF9FD362468E3FFFD",
        "7480000000000011FF4C5F728000000000FF17BA130000000000FAF9FD35EC7257FFFA",
        "7480000000000011FF4C5F728000000000FF204A1F0000000000FAF9FD35BA0043FFFB",
        "7480000000000011FF4C5F728000000000FF2894890000000000FAF9FD358A432BFFF7",
        "7480000000000011FF4C5F728000000000FF3117330000000000FAF9FD3551B2B3FFFA",
        "7480000000000011FF4C5F728000000000FF3995380000000000FAF9FD34E333FBFFF8",
        "7480000000000011FF4C5F728000000000FF41DE860000000000FAF9FD34CC3543FFF1",
        "7480000000000011FF4C5F728000000000FF4A31D80000000000FAF9FD348931CBFFFB",
        "7480000000000011FF4C5F728000000000FF52BF210000000000FAF9FD34360EFBFFFE",
        "7480000000000011FF4C5F728000000000FF5B098A0000000000FAF9FD339FF78FFFF8",
        "7480000000000011FF4C5F728000000000FF63483C0000000000FAF9FD3297531FFFFB",
        "7480000000000011FF4C5F728000000000FF6BBA550000000000FAF9FD32933AABFFFB",
        "7480000000000011FF4C5F728000000000FF7401F40000000000FAF9FD3161F95BFFFB",
        "7480000000000011FF4C5F728000000000FF7C345B0000000000FAF9FD31055BFBFFF4",
        "7480000000000011FF4C5F728000000000FF84A35E0000000000FAF9FD3100FD3FFFF7",
        "7480000000000011FF4C5F728000000000FF8CE3510000000000FAF9FD30FD603FFFF9",
        "7480000000000011FF4C5F728000000000FF955A640000000000FA"
      ]

### PR DESCRIPTION
**Pull request by tonyxuqqi**
Signed-off-by: qi.xu <tonxuqi@outlook.com>

### What is changed and how it works?
Issue Number: Close #12549

What's Changed:

```commit-message
remove ts from bucket keys
```

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

### Release note 

```release-note
None
```

### CODE REVIEW

File: components/raftstore/src/coprocessor/split_check/mod.rs [hunk 1]
```diff
@@ -99,12 +102,16 @@ impl<'a, E> Host<'a, E> {
...
                 .approximate_split_keys(region, engine)
-                .map(|keys| Bucket {
-                    keys: keys
+                .map(|keys| {
+                    let mut bucket_keys: Vec<Vec<u8>> = keys
                         .into_iter()
-                        .map(|k| ::keys::origin_key(&k).to_vec())
-                        .collect(),
-                    size: region_size,
+                        .map(|k| strip_timestamp_if_exists(::keys::origin_key(&k).to_vec()))
```
Comment (bufferflies) [inline components/raftstore/src/coprocessor/split_check/mod.rs:108]:
```suggestion
                        .map(|k| strip_timestamp_if_exists(::keys::origin_key(&k).to_vec())).dedup()
```

Comment (tonyxuqqi) [reply components/raftstore/src/coprocessor/split_check/mod.rs:108]: 你确定这个能编译吗？你上面dedup()的对象不是Vec<Vec<u8>>吧。

**Review by BusyJay — COMMENTED** [review]
Can it be done by observer like `split_obsever`? For example, before buckets are taking effects, put them go through observers and strip timestamp.

**Comment by tonyxuqqi** [comment]
> Can it be done by observer like `split_obsever`? For example, before buckets are taking effects, put them go through observers and strip timestamp.

Probably not. There's no pre_propose like hook for buckets.

File: components/raftstore/src/store/worker/split_check.rs [hunk 2]
```diff
@@ -234,20 +238,68 @@ where
...
+                    let mut bucket_region = region.clone();
+                    bucket_region.set_start_key(bucket_range.0.clone());
+                    bucket_region.set_end_key(bucket_range.1.clone());
+                    if is_valid_split_key(&key, i, &bucket_region) {
+                        Some(key)
+                    } else {
+                        None
+                    }
+                })
+                .coalesce(|prev, curr| {
```
Comment (BusyJay) [inline components/raftstore/src/store/worker/split_check.rs:267]: This is almost the same as split check, why not reuse the code?

File: components/raftstore/src/store/worker/split_check.rs [hunk 3]
```diff
@@ -234,20 +238,68 @@ where
...
+                            "skip invalid split key: key should not be larger than the previous.";
+                            "region_id" => region.id,
+                            "key" => log_wrappers::Value::key(&curr),
+                            "previous" => log_wrappers::Value::key(&prev),
+                        );
+                        Ok(prev)
+                    }
+                })
+                .collect::<Vec<_>>();
+            bucket.keys = adjusted_keys;
```
Comment (BusyJay) [inline components/raftstore/src/store/worker/split_check.rs:282]: What if the key is beyond the region range?

File: components/raftstore/src/store/worker/split_check.rs (hunk 2 above)
Comment (tonyxuqqi) [reply components/raftstore/src/store/worker/split_check.rs:267]: As discussed, the parameter for is_valid_split_key is different--here it's per bucket range, not per region range.

File: components/raftstore/src/store/worker/split_check.rs (hunk 3 above)
Comment (tonyxuqqi) [reply components/raftstore/src/store/worker/split_check.rs:282]: Theoretically it should not happen because bucket region is always within region range. But I can add an assert here.

**Review by BusyJay — APPROVED** [review]

**Review by 5kbpers — APPROVED** [review]
