### PR TITLE
cdc: skip seek old value for Put if cache returns None

### LINKED ISSUE #10036: CDC old value cache does not work effectively for caching Put commands
## Bug Report

CDC old value cache does not work effectively for Put commands without previous writes (old value), because it does not add Oldvalue::None to cache when there is no old value. It causes 100% cache miss and results in a higher CPU usage for CDC endpoint thread. 

image

### What version of TiKV are you using?

5.0.0

### Steps to reproduce

```
go-ycsb load mysql -p workload=core -p mysql.host=172.16.5.33 -p mysql.port=47904 -p mysql.user=root -p recordcount=6000000 -p fieldcount=10 -p fieldlength=16 -p threadcount=8 -p table=usertable1 && \
sleep 60 && go-ycsb run mysql -p workload=core -p mysql.host=172.16.5.33 -p mysql.port=47904 -p mysql.user=root -p recordcount=6000000 -p fieldcount=10 -p fieldlength=16 -p threadcount=8 -p table=usertable1 -p operationcount=30000000 -p updateproportion=1 -p requestdistribution=uniform
```

This issue relates to #9996.

### PR DESCRIPTION
**Pull request by overvenus**
### What problem does this PR solve?

CDC old value cache does not work effectively for Put commands without previous writes (old value), because it does not add Oldvalue::None to cache when there is no old value. It causes 100% cache miss and results in a higher CPU usage for CDC endpoint thread. 

Close #10036.
This issue is found during investigating #9996.

### What is changed and how it works?

Add a new variant `Unkown` to OldValue to support distinguishing Unknown from None for OldValue.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)

```
go-ycsb load mysql -p workload=core -p mysql.host=172.16.5.33 -p mysql.port=47904 -p mysql.user=root -p recordcount=6000000 -p fieldcount=10 -p fieldlength=16 -p threadcount=8 -p table=usertable1 && \
sleep 60 && go-ycsb run mysql -p workload=core -p mysql.host=172.16.5.33 -p mysql.port=47904 -p mysql.user=root -p recordcount=6000000 -p fieldcount=10 -p fieldlength=16 -p threadcount=8 -p table=usertable1 -p operationcount=30000000 -p updateproportion=1 -p requestdistribution=uniform
```

Before this PR
image

This PR
image

### Release note 

- Fix a potential OOM issue by avoiding unnecessary read for getting CDC old values.

### CODE REVIEW

File: components/txn_types/src/types.rs [hunk 1]
```diff
@@ -340,6 +329,8 @@ pub enum OldValue {
     },
     /// `None` means we don't found a previous value
     None,
+    /// `Unknown` means we don't sure if there is a previous value
+    Unknown,
```
Comment (5kbpers) [inline components/txn_types/src/types.rs:333]: Why not use `Unspecified`?

File: src/storage/txn/actions/prewrite.rs [hunk 2]
```diff
@@ -75,10 +75,18 @@ pub fn prewrite<S: Snapshot>(
...
     }
 
-    let old_value = if txn_props.need_old_value && mutation.mutation_type.may_have_old_value() {
-        if let Some(w) = prev_write {
-            reader.get_old_value(w)?
+    let old_value = if txn_props.need_old_value {
+        if mutation.mutation_type == MutationType::Insert {
+            // The previous write of an Insert is guaranteed to be None.
+            OldValue::None
+        } else if mutation.skip_constraint_check() {
```
Comment (5kbpers) [inline src/storage/txn/actions/prewrite.rs:82]: Could you add a comment to explain the case for pessimistic transaction?

File: src/storage/txn/actions/prewrite.rs [hunk 3]
```diff
@@ -75,8 +75,15 @@ pub fn prewrite<S: Snapshot>(
         return Ok((min_commit_ts, OldValue::Unspecified));
     }
 
-    let old_value = if txn_props.need_old_value && mutation.mutation_type.may_have_old_value() {
-        if let Some(w) = prev_write {
+    let old_value = if txn_props.need_old_value {
```
Comment (MyonKeminta) [inline src/storage/txn/actions/prewrite.rs:78]: Seems you removed the `may_have_old_value` condition. I'm afraid it's not a good idea, since it makes `MutationType::Lock` also loads the old value.

File: src/storage/txn/actions/prewrite.rs [hunk 4]
```diff
@@ -1095,7 +1122,100 @@ pub mod tests {
...
+    fn test_prewrite_old_value_rollback_and_lock() {
+        let engine_rollback = crate::storage::TestEngineBuilder::new().build().unwrap();
+
+        must_prewrite_put(&engine_rollback, b"k1", b"v1", b"k1", 10);
+        must_commit(&engine_rollback, b"k1", 10, 30);
+
+        must_prewrite_put(&engine_rollback, b"k1", b"v2", b"k1", 40);
+        must_rollback(&engine_rollback, b"k1", 40, false);
+
+        let engine_lock = crate::storage::TestEngineBuilder::new().build().unwrap();
```
Comment (MyonKeminta) [inline src/storage/txn/actions/prewrite.rs:1150]: It's ok though, actually, you can write on different keys on one engine

**Review by MyonKeminta — COMMENTED** [review]
LGTM

**Review by MyonKeminta — APPROVED** [review]
