### PR TITLE
cmd: make lock files accessible to all users.

### LINKED ISSUE #12399: File locks for working around port conflict are sometimes inaccessible
### What version of TiKV are you using?
master

### What operating system and CPU are you using?
unix

### Steps to reproduce
1. run tikv-server in root mode
2. run tikv-server in user mode

### What did you expect?
nornal startup

### What did happened?
`[FATAL] [[server.rs:894](http://server.rs:894/)] ["failed to create lock at /tmp/1001_TIKV_LOCK_FILES/0.0.0.0_20160: Permission denied (os error 13)"]`

### PR DESCRIPTION
**Pull request by hunterlxt**
Signed-off-by: Xintao <hunterlxt@live.com>

### What is changed and how it works?

Issue Number: Close #12399

What's Changed:

```commit-message
Make lock files accessible to all users.
```

### Related changes

- None

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

```release-note
Fix the bug where sometimes tikv-server would not start because it didn't have access to lock files.
```

### CODE REVIEW

File: components/server/src/server.rs [hunk 1]
```diff
@@ -1504,6 +1507,18 @@ fn get_lock_dir() -> String {
     "TIKV_LOCK_FILES".to_owned()
 }
 
+// Make the lock files be accessed by all users. Only support in unix platform.
+#[cfg(unix)]
+fn set_path_all_permission<P: AsRef<Path>>(path: P) {
+    use std::fs::{set_permissions, Permissions};
+    use std::os::unix::fs::PermissionsExt;
+    // this may failed when setting a file created by root.
+    let _ = set_permissions(path, Permissions::from_mode(0o777));
```
Comment (5kbpers) [inline components/server/src/server.rs:1516]: Should we log this error?

**Review by 5kbpers — APPROVED** [review]
rest LGTM

File: components/server/src/server.rs (hunk 1 above)
Comment (hunterlxt) [reply components/server/src/server.rs:1516]: If tikv-server started by root, it will return error when starting by normal user. I don't think this behavior is a error?

**Review by sticnarf — APPROVED** [review]
LGTM

File: components/server/src/server.rs (hunk 1 above)
Comment (5kbpers) [reply components/server/src/server.rs:1516]: Got it.
