### PR TITLE
snapshot_backup: enhanced prepare stage

### LINKED ISSUE #15739: TiKV panic due to catch up logs during ebs restore
## Bug Report

TiKV panic with following backtrace

<details><summary> [lib.rs:509] ["unstable.slice[28051, 28055] out of bound[28051, 28051], raft_id: 2010234007, region_id: 2010234004"] </summary>
<p>

```
[lib.rs:509] ["unstable.slice[28051, 28055] out of bound[28051, 28051], raft_id: 2010234007, region_id: 2010234004"] [backtrace="
   0: tikv_util::set_panic_hook::{{closure}}
             at tikv/components/tikv_util/src/lib.rs:508:18
   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at root/.rustup/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2032:9
      std::panicking::rust_panic_with_hook
             at root/.rustup/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:692:13
   2: std::panicking::begin_panic_handler::{{closure}}
             at root/.rustup/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:579:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at root/.rustup/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:137:18
   4: rust_begin_unwind
             at root/.rustup/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:575:5
   5: core::panicking::panic_fmt
             at root/.rustup/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panicking.rs:65:14
   6: raft::log_unstable::Unstable::must_check_outofbounds
             at root/.cargo/git/checkouts/raft-rs-42b8049ef2e3af07/2357cb2/src/log_unstable.rs:201:13
   7: raft::log_unstable::Unstable::truncate_and_append
             at root/.cargo/git/checkouts/raft-rs-42b8049ef2e3af07/2357cb2/src/log_unstable.rs:169:13
   8: raft::raft_log::RaftLog<T>::append
             at root/.cargo/git/checkouts/raft-rs-42b8049ef2e3af07/2357cb2/src/raft_log.rs:377:9
   9: raft::raft_log::RaftLog<T>::maybe_append
             at root/.cargo/git/checkouts/raft-rs-42b8049ef2e3af07/2357cb2/src/raft_log.rs:268:17
  10: raftstore::store::peer::Peer<EK,ER>::maybe_append_merge_entries
             at tikv/components/raftstore/src/store/peer.rs:1369:9
      raftstore::store::fsm::peer::PeerFsmDelegate<EK,ER,T>::on_catch_up_logs_for_merge
             at tikv/components/raftstore/src/store/fsm/peer.rs:4466:15
      raftstore::store::fsm::peer::PeerFsmDelegate<EK,ER,T>::on_significant_msg
             at tikv/components/raftstore/src/store/fsm/peer.rs:1403:17
  11: raftstore::store::fsm::peer::PeerFsmDelegate<EK,ER,T>::handle_msgs
             at tikv/components/raftstore/src/store/fsm/peer.rs:666:49
  12: <raftstore::store::fsm::store::RaftPoller<EK,ER,T> as batch_system::batch::PollHandler<raftstore::store::fsm::peer::PeerFsm<EK,ER>,raftstore::store::fsm::store::StoreFsm<EK>>>::handle_normal
             at tikv/components/raftstore/src/store/fsm/store.rs:971:9
  13: batch_system::batch::Poller<N,C,Handler>::poll
             at tikv/components/batch-system/src/batch.rs:430:27
  14: batch_system::batch::BatchSystem<N,C>::start_poller::{{closure}}
             at tikv/components/batch-system/src/batch.rs:600:17
      <std::thread::Builder as tikv_util::sys::thread::StdThreadBuildWrapper>::spawn_wrapper::{{closure}}
             at tikv/components/tikv_util/src/sys/thread.rs:415:23
      std::sys_common::backtrace::__rust_begin_short_backtrace
             at root/.rustup/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:121:18
  15: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
             at root/.rustup/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:551:17
      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at root/.rustup/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panic/unwind_safe.rs:271:9
      std::panicking::try::do_call
             at root/.rustup/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:483:40
      std::panicking::try
             at root/.rustup/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:447:19
      std::panic::catch_unwind
             at root/.rustup/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:137:14
      std::thread::Builder::spawn_unchecked_::{{closure}}
             at root/.rustup/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:550:30
      core::ops::function::FnOnce::call_once{{vtable.shim}}
             at root/.rustup/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:513:5
  16: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at root/.rustup/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2000:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at root/.rustup/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2000:9
      std::sys::unix::thread::Thread::new::thread_start
             at root/.rustup/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys/unix/thread.rs:108:17
  17: start_thread
  18: __clone3"] [location=/root/.cargo/git/checkouts/raft-rs-42b8049ef2e3af07/2357cb2/src/log_unstable.rs:201] [thread_name=raftstore-1942158-0]

```

</p>
</details> 

The panic is caused by ebs backup breaks region merge assumption: when proposing commit merge, all source peers must have raft log that is large than or equal to prepare merge min index. But in ebs backup, the snapshot of panic tikv is taken before merge (does not have enough raft logs), and the snapshot of other tikvs is taken after merge. So the target region leader sends CommitMerge raft log to panic tikv, but the source region leader doesn't send the following raft log (because it is merged), which causes the source region panic when handling CatchUpLogs from target region.

Cc #13554 which has the same panic backtrace but without ebs.

### What version of TiKV are you using?

v6.5.4

### What did you expect?

No panic.

### What did happened?

Panic.

### PR DESCRIPTION
**Pull request by YuJuncen**
### What is changed and how it works?

Issue Number: Close #15739

What's Changed:
This PR added the implementation of an enhanced version of preparing, which allows us to make a safer backup. 

```commit-message
It contains:
- A coprocessor that can fully reject all admin and ingest commands.
- A new region-leveled wait apply implementation, which allow us to wait all pending commands to be applied.
```

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Integration test
- Manual test (add detailed scripts or steps below)

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM

### Release note 

```release-note
None
```

### CODE REVIEW

File: components/backup/src/disk_snap.rs [hunk 1]
```diff
@@ -0,0 +1,309 @@
+//! This module contains things about disk snapshot.
```
Comment (overvenus) [inline components/backup/src/disk_snap.rs:1]: License header.

File: components/backup/src/service.rs [hunk 2]
```diff
@@ -56,33 +61,31 @@ where
...
-                .map(|res: Result<()>| match res {
-                    Ok(_) => {
-                        info!("check admin closed");
-                    }
-                    Err(e) => {
-                        error!("check admin canceled"; "error" => ?e);
-                    }
-                });
-                ctx.spawn(send_task);
+        if let Err(err) = self.snap_br_env.handle.broadcast_check_pending_admin(tx) {
```
Comment (overvenus) [inline components/backup/src/service.rs:64]: How long does it take? If it's too long, it might cause keep alive timeout.

File: components/raftstore/src/store/fsm/peer.rs [hunk 3]
```diff
@@ -949,24 +948,34 @@ where
...
-            syncer.abort();
+            req.syncer.abort(AbortReason::Duplicated);
             return;
         }
 
         let target_index = self.fsm.peer.raft_group.raft.raft_log.last_index();
+        let term = self.fsm.peer.raft_group.raft.term;
+        if let Some(e) = &req.expected_epoch {
+            if let Err(err) = compare_region_epoch(e, self.region(), true, true, true) {
+                warn!("epoch not match for wait apply, aborting."; "err" => %err);
```
Comment (overvenus) [inline components/raftstore/src/store/fsm/peer.rs:967]: Please add peer_id, region_id.

File: tests/integrations/backup/disk_snap.rs [hunk 4]
```diff
@@ -0,0 +1,112 @@
...
+    println!("{:?}", resp.response.get_header().get_error());
+    must_contains_error(
+        &resp.response,
+        "rejecting proposing admin commands while preparing snapshot backup",
+    );
+}
+
+#[test]
+
+fn test_wait_apply() {
```
Comment (overvenus) [inline tests/integrations/backup/disk_snap.rs:27]:
```suggestion
#[test]
fn test_wait_apply() {
```

File: components/backup/src/service.rs (hunk 2 above)
Comment (YuJuncen) [reply components/backup/src/service.rs:64]: This will send a message to every region in the store. I guess that will be fast if there isn't a region blocking.

File: components/raftstore/src/store/metrics.rs [hunk 5]
```diff
@@ -260,6 +260,33 @@ make_static_metric! {
         unable_to_split_cpu_top,
     }
 
+    pub label_enum SnapshotBrWaitApplyEventType {
+        sent,
+
```
Comment (Connor1996) [inline components/raftstore/src/store/metrics.rs:265]: why blank

File: components/backup/src/service.rs [hunk 6]
```diff
@@ -2,52 +2,57 @@
...
-    router: Option<RaftRouter<EK, ER>>,
+    snap_br_env: disk_snap::Env<H>,
 }
 
-impl<EK, ER> Service<EK, ER>
-where
-    EK: KvEngine,
-    ER: RaftEngine,
-{
+impl<H: SnapshotBrHandle> Clone for Service<H> {
```
[the remark this answers is not in the document]
Comment (YuJuncen) [reply components/backup/src/service.rs:20]: Rustc will complain this:

```
This will send a message to every region in the store. I guess that will be fast if there isn't a region blocking.

error[E0277]: the trait bound `service::Service<UnimplementedHandle>: Clone` is not satisfied
   --> components/backup/src/service.rs:179:76
    |
179 |             ServerBuilder::new(env.clone()).register_service(create_backup(backup_service));
    |                                                              ------------- ^^^^^^^^^^^^^^ the trait `Clone` is not implemented for `service::Service<UnimplementedHandle>`
    |                                                              |
    |                                                              required by a bound introduced by this call
    |
rustcClick for full compiler diagnostic
service.rs(179, 62): required by a bound introduced by this call
service.rs(15, 10): required for `service::Service<UnimplementedHandle>` to implement `Clone`
brpb_grpc.rs(144, 41): required by a bound in `kvproto::brpb::create_backup`
service.rs(179, 76): consider borrowing here: `&`
```

File: tests/integrations/backup/mod.rs [hunk 7]
```diff
@@ -17,6 +17,8 @@ use tikv::coprocessor::checksum_crc64_xor;
 use tikv_util::HandyRwLock;
 use txn_types::TimeStamp;
 
+pub mod disk_snap;
```
Comment (overvenus) [inline tests/integrations/backup/mod.rs:20]:
```suggestion
mod disk_snap;
```

File: tests/integrations/raftstore/test_snap_recovery.rs [hunk 8]
```diff
@@ -94,31 +97,38 @@ fn test_snap_wait_apply() {
...
-            SnapshotRecoveryWaitApplySyncer::new(1, tx.clone()),
+        PeerMsg::SignificantMsg(SignificantMsg::SnapshotBrWaitApply(
+            SnapshotBrWaitApplyRequest::relaxed(syncer.clone()),
         ))
     });
 
     // we expect recv timeout because the leader peer on store 1 cannot finished the
     // apply. so the wait apply will timeout.
-    rx.recv_timeout(Duration::from_secs(1)).unwrap_err();
+    block_on(
```
Comment (overvenus) [inline tests/integrations/raftstore/test_snap_recovery.rs:110]: How about `tikv_util::future::block_on_timeout`?

File: tests/integrations/backup/disk_snap.rs [hunk 9]
```diff
@@ -0,0 +1,111 @@
...
+}
+
+#[test]
+fn test_wait_apply() {
+    test_util::init_log_for_test();
+    let mut suite = Suite::new(3);
+    for key in 'a'..'k' {
+        suite.split(&[key as u8]);
+    }
+    let rc = suite.cluster.get_region(b"ca");
```
Comment (overvenus) [inline tests/integrations/backup/disk_snap.rs:32]: Should we wait for splitting before `get_region`?

File: tests/integrations/backup/disk_snap.rs [hunk 10]
```diff
@@ -0,0 +1,111 @@
...
+                Some(Box::new({
+                    let tx = tx.clone();
+                    move || drop(tx)
+                })),
+                None,
+            ),
+        )
+        .unwrap();
+    }
+    // Hacking: assume all leaders are in one store.
```
Comment (overvenus) [inline tests/integrations/backup/disk_snap.rs:78]: You can set a large election tick to stable leadership.

File: tests/integrations/backup/disk_snap.rs [hunk 11]
```diff
@@ -0,0 +1,111 @@
...
+use test_raftstore::{must_contains_error, Direction, RegionPacketFilter, Simulator};
+use tikv_util::HandyRwLock;
+
+#[test]
+fn test_basic() {
+    let mut suite = Suite::new(1);
+    let mut call = suite.prepare_backup(1);
+    call.prepare(60);
+    let resp = suite.try_split(b"k");
+    println!("{:?}", resp.response.get_header().get_error());
```
Comment (overvenus) [inline tests/integrations/backup/disk_snap.rs:18]:
```suggestion
    debug!("{:?}", resp.response.get_header().get_error());
```

File: components/snap_recovery/src/services.rs [hunk 12]
```diff
@@ -413,11 +412,11 @@ impl<ER: RaftEngine> RecoverData for RecoveryService<ER> {
             // FIXME: this function will exit once the first region finished apply.
             // BUT for the flashback resolve KV implementation, that is fine because the
             // raft log stats is consistent.
-            let (tx, rx) = sync_channel(1);
-            RecoveryService::wait_apply_last(router, tx.clone());
-            match rx.recv() {
+            let (tx, rx) = oneshot::channel();
+            RecoveryService::wait_apply_last(router, tx);
```
Comment (overvenus) [inline components/snap_recovery/src/services.rs:416]: The blocking operation should not spawn into grpc threads.

File: components/backup/src/disk_snap.rs [hunk 13]
```diff
@@ -0,0 +1,310 @@
...
+                    self.0.send((resp, WriteFlags::default())).await?;
+                }
+            },
+        }
+        Ok(self)
+    }
+}
+
+impl Error {
+    fn how_to_handle(self) -> HandleErr {
```
Comment (overvenus) [inline components/backup/src/disk_snap.rs:84]:
```suggestion
    fn into_handle_error(self) -> HandleErr {
```

Or impl `core::convert::Into`.

It's better to use rust idioms.

File: components/backup/src/disk_snap.rs [hunk 14]
```diff
@@ -0,0 +1,310 @@
...
+    SnapshotBrWaitApplySyncer,
+};
+use tikv_util::warn;
+use tokio::sync::oneshot;
+use tokio_stream::Stream;
+
+type Result<T> = std::result::Result<T, Error>;
+
+enum Error {
+    NotInitialized,
```
Comment (overvenus) [inline components/backup/src/disk_snap.rs:38]:
```suggestion
    Uninitialized,
```

File: components/backup/src/disk_snap.rs [hunk 15]
```diff
@@ -0,0 +1,310 @@
...
+
+impl<SR: SnapshotBrHandle + 'static> StreamHandleLoop<SR> {
+    pub fn new(env: Env<SR>) -> Self {
+        Self {
+            env,
+            pending_regions: vec![],
+        }
+    }
+
+    fn async_wait_apply(&mut self, region: &Region) -> BoxFuture<'static, (Region, Result<()>)> {
```
Comment (overvenus) [inline components/backup/src/disk_snap.rs:195]:
```suggestion
    async fn wait_apply(&mut self, region: &Region) -> (Region, Result<()>) {
```

File: components/backup/src/service.rs [hunk 16]
```diff
@@ -137,13 +147,35 @@ where
...
+        &mut self,
+        ctx: grpcio::RpcContext<'_>,
+        stream: grpcio::RequestStream<PrepareSnapshotBackupRequest>,
+        sink: grpcio::DuplexSink<PrepareSnapshotBackupResponse>,
+    ) {
+        let l = StreamHandleLoop::new(self.snap_br_env.clone());
+        ctx.spawn(async move {
+            if let Err(err) = l.run(stream, sink.into()).await {
+                warn!("stream closed; perhaps a problem cannot be retried happens"; "reason" => ?err);
+            }
```
Comment (overvenus) [inline components/backup/src/service.rs:170]: It's better to offload complex event loop to a future runtime, in case grpc threads are blocked by the event loop accidently.

Comment (YuJuncen) [reply components/backup/src/service.rs:170]: Done, I will make it share with the IO pool of backing up.

File: tests/failpoints/cases/test_disk_snap_br.rs [hunk 17]
```diff
@@ -0,0 +1,31 @@
+use std::time::Duration;
```
Comment (overvenus) [inline tests/failpoints/cases/test_disk_snap_br.rs:1]: License header?

File: components/backup/src/service.rs (hunk 6 above)
[the remark this answers is not in the document]
Comment (Connor1996) [reply components/backup/src/service.rs:20]: make `SnapshotBrHandle: Sync + Send + Clone`

File: components/raftstore/src/store/snapshot_backup.rs [hunk 18]
```diff
@@ -0,0 +1,383 @@
...
+        )))
+    }
+}
+
+pub struct RejectIngestAndAdmin {
+    until: AtomicU64,
+    initialized: AtomicBool,
+}
+
+impl Default for RejectIngestAndAdmin {
```
Comment (Connor1996) [inline components/raftstore/src/store/snapshot_backup.rs:129]: derive(Default)

File: components/raftstore/src/store/snapshot_backup.rs [hunk 19]
```diff
@@ -0,0 +1,383 @@
...
+        tx: UnboundedSender<CheckAdminResponse>,
+    ) -> crate::Result<()> {
+        self.lock().unwrap().broadcast_normal(|| {
+            PeerMsg::SignificantMsg(SignificantMsg::CheckPendingAdmin(tx.clone()))
+        });
+        Ok(())
+    }
+}
+
+pub struct UnimplementedHandle {
```
Comment (Connor1996) [inline components/raftstore/src/store/snapshot_backup.rs:94]: that should be in raftstore v2?

File: components/backup/src/service.rs (hunk 6 above)
[the remark this answers is not in the document]
Comment (YuJuncen) [reply components/backup/src/service.rs:20]: The `SnapshotBrHandle` doesn't need to be `Clone` because it is `Arc`ed in the field. But somehow I agree that allow the `Handle` to implement `Clone` will be better.

File: components/raftstore/src/store/snapshot_backup.rs [hunk 20]
```diff
@@ -0,0 +1,345 @@
...
+                    v = new_val;
+                    expired = v < epoch_second_coarse();
+                }
+            }
+        }
+
+        expired
+    }
+
+    pub fn connected(&self) -> bool {
```
Comment (Connor1996) [inline components/raftstore/src/store/snapshot_backup.rs:140]: initialized?

File: components/backup/src/disk_snap.rs [hunk 21]
```diff
@@ -0,0 +1,340 @@
...
+
+    pub async fn run(
+        mut self,
+        mut input: impl Stream<Item = grpcio::Result<PReq>> + Unpin,
+        mut sink: ResultSink,
+    ) -> grpcio::Result<()> {
+        loop {
+            match self.next_event(&mut input).await {
+                StreamHandleEvent::Req(req) => match req.get_ty() {
+                    PReqT::UpdateLease => {
```
Comment (Connor1996) [inline components/backup/src/disk_snap.rs:292]: Could you explain somewhere what's problem that lease is to solve

File: components/raftstore/src/store/snapshot_backup.rs [hunk 22]
```diff
@@ -0,0 +1,345 @@
...
+    }
+
+    /// Extend the lease.
+    ///
+    /// # Returns
+    ///
+    /// Whether previously there is a lease.
+    pub fn heartbeat(&self, lease: Duration) -> bool {
+        let mut v = self.until.load(Ordering::SeqCst);
+        let now = epoch_second_coarse();
```
Comment (Connor1996) [inline components/raftstore/src/store/snapshot_backup.rs:151]: Instant::now_coarse?

File: components/raftstore/src/store/snapshot_backup.rs [hunk 23]
```diff
@@ -0,0 +1,345 @@
...
+        self.initialized.load(Ordering::Acquire)
+    }
+
+    /// Extend the lease.
+    ///
+    /// # Returns
+    ///
+    /// Whether previously there is a lease.
+    pub fn heartbeat(&self, lease: Duration) -> bool {
+        let mut v = self.until.load(Ordering::SeqCst);
```
Comment (Connor1996) [inline components/raftstore/src/store/snapshot_backup.rs:150]: call it `before`

File: components/raftstore/src/store/snapshot_backup.rs [hunk 24]
```diff
@@ -0,0 +1,345 @@
...
+    pub fn connected(&self) -> bool {
+        self.initialized.load(Ordering::Acquire)
+    }
+
+    /// Extend the lease.
+    ///
+    /// # Returns
+    ///
+    /// Whether previously there is a lease.
+    pub fn heartbeat(&self, lease: Duration) -> bool {
```
Comment (Connor1996) [inline components/raftstore/src/store/snapshot_backup.rs:149]: How about calling it `update_lease``

File: components/raftstore/src/store/snapshot_backup.rs [hunk 25]
```diff
@@ -0,0 +1,345 @@
...
+        let mut v = self.until.load(Ordering::SeqCst);
+        let now = epoch_second_coarse();
+        let new_lease = now + lease.as_secs();
+        let last_lease_valid = v > now;
+        loop {
+            match self
+                .until
+                .compare_exchange(v, new_lease, Ordering::SeqCst, Ordering::SeqCst)
```
Comment (Connor1996) [inline components/raftstore/src/store/snapshot_backup.rs:157]: use `fetch_update`?

File: components/backup/src/disk_snap.rs [hunk 26]
```diff
@@ -0,0 +1,340 @@
...
+            rejector,
+            active_stream: Arc::new(AtomicU64::new(0)),
+            runtime: Either::Right(Self::default_runtime()),
+        }
+    }
+
+    pub fn with_rejector_and_runtime(
+        handle: SR,
+        rejector: Arc<RejectIngestAndAdmin>,
+        runtime: Handle,
```
Comment (Connor1996) [inline components/backup/src/disk_snap.rs:156]: How about renaming to `new`, and accept `Option<Handle>`

File: components/backup/src/disk_snap.rs [hunk 27]
```diff
@@ -0,0 +1,340 @@
...
+        let region = region.clone();
+        let epoch = region.get_region_epoch().clone();
+        let id = region.get_id();
+        let send_res = handle
+            .send_wait_apply(id, SnapshotBrWaitApplyRequest::strict(syncer, epoch))
+            .map_err(Error::RaftStore);
+        Box::pin(
+            async move {
+                send_res?;
+                rx.await.map_err(|_| Error::WaitApplyAborted).map(|_| ())
```
Comment (Connor1996) [inline components/backup/src/disk_snap.rs:242]: Why not remove the reigon id from `pending_peers` here? Then you don't need to write `wait_applies` logic in `next_event`

Comment (YuJuncen) [reply components/backup/src/disk_snap.rs:242]: I think concurrency access to the same variable may make things more complex. Also I think it would be harder to be notified once some wait apply finished (perhaps we have to poll the status of `pending_peers`). 🤔

File: components/raftstore/src/store/snapshot_backup.rs (hunk 22 above)
Comment (YuJuncen) [reply components/raftstore/src/store/snapshot_backup.rs:151]: We need to store it as an atomic variable, I think it might be more convenient if we store it as an `uint64` instead of an `Instant`.

File: components/backup/src/disk_snap.rs (hunk 21 above)
Comment (YuJuncen) [reply components/backup/src/disk_snap.rs:292]: I guess perhaps we can write this to kvproto...?

File: components/backup/src/disk_snap.rs [hunk 28]
```diff
@@ -0,0 +1,331 @@
...
+        }
+
+        let (tx, rx) = oneshot::channel();
+        let syncer = SnapshotBrWaitApplySyncer::new(region.id, tx);
+        let handle = self.env.handle.clone();
+        let region = region.clone();
+        let epoch = region.get_region_epoch().clone();
+        let id = region.get_id();
+        let send_res = handle
+            .send_wait_apply(id, SnapshotBrWaitApplyRequest::strict(syncer, epoch))
```
Comment (Connor1996) [inline components/backup/src/disk_snap.rs:228]: why not use syncer to wait all regions finish applied

File: components/raftstore/src/store/snapshot_backup.rs [hunk 29]
```diff
@@ -0,0 +1,345 @@
...
+        self.lock().unwrap().broadcast_normal(|| {
+            PeerMsg::SignificantMsg(SignificantMsg::CheckPendingAdmin(tx.clone()))
+        });
+        Ok(())
+    }
+}
+
+#[derive(Default)]
+pub struct RejectIngestAndAdmin {
+    before: AtomicU64,
```
Comment (Connor1996) [inline components/raftstore/src/store/snapshot_backup.rs:97]: give it a meaningful name

File: components/raftstore/src/store/fsm/peer.rs [hunk 30]
```diff
@@ -993,10 +1004,12 @@ where
                 "applied_index" => self.fsm.peer.raft_group.raft.raft_log.applied,
             );
         }
+        SNAP_BR_WAIT_APPLY_EVENT.accepted.inc();
 
-        self.fsm.peer.snapshot_recovery_state = Some(SnapshotRecoveryState::WaitLogApplyToLast {
+        self.fsm.peer.snapshot_recovery_state = Some(SnapshotBrState::WaitLogApplyToLast {
             target_index,
-            syncer,
+            valid_for_term: Some(term),
```
Comment (Connor1996) [inline components/raftstore/src/store/fsm/peer.rs:1011]: seems always some?

File: components/backup/src/disk_snap.rs [hunk 31]
```diff
@@ -0,0 +1,331 @@
...
+    }
+
+    pub fn handle(&self) -> &Handle {
+        match &self.runtime {
+            Either::Left(h) => h,
+            Either::Right(rt) => rt.handle(),
+        }
+    }
+
+    pub fn new(handle: SR, rejector: Arc<RejectIngestAndAdmin>, runtime: Option<Handle>) -> Self {
```
Comment (Connor1996) [inline components/backup/src/disk_snap.rs:144]: move it to the first line of impl as convention

File: components/backup/src/service.rs [hunk 32]
```diff
@@ -2,87 +2,78 @@
...
-    pub fn new(scheduler: Scheduler<Task>) -> Self {
-        Service {
-            scheduler,
-            router: None,
-        }
-    }
-
     // Create a new backup service with router, this used for raftstore v1.
-    pub fn with_router(scheduler: Scheduler<Task>, router: RaftRouter<EK, ER>) -> Self {
+    pub fn with_env(scheduler: Scheduler<Task>, env: disk_snap::Env<H>) -> Self {
```
Comment (Connor1996) [inline components/backup/src/service.rs:26]: simply call it `new`

File: components/backup/src/service.rs [hunk 33]
```diff
@@ -2,87 +2,78 @@
...
-    // Create a new backup service without router, this used for raftstore v2.
-    // because we don't have RaftStoreRouter any more.
-    pub fn new(scheduler: Scheduler<Task>) -> Self {
-        Service {
-            scheduler,
-            router: None,
-        }
-    }
-
     // Create a new backup service with router, this used for raftstore v1.
```
Comment (Connor1996) [inline components/backup/src/service.rs:25]: update comment

File: components/raftstore-v2/src/operation/disk_snapshot_backup.rs [hunk 34]
```diff
@@ -0,0 +1,37 @@
+// Copyright 2023 TiKV Project Authors. Licensed under Apache-2.0.
+
+use futures::channel::mpsc::UnboundedSender;
+use kvproto::brpb::CheckAdminResponse;
+use raftstore::store::snapshot_backup::{SnapshotBrHandle, SnapshotBrWaitApplyRequest};
```
Comment (Connor1996) [inline components/raftstore-v2/src/operation/disk_snapshot_backup.rs:5]: shouldn't have dependencys on v1

File: components/raftstore/src/store/snapshot_backup.rs [hunk 35]
```diff
@@ -0,0 +1,345 @@
...
+    report_id: u64,
+}
+
+impl Drop for SnapshotBrWaitApplySyncer {
+    fn drop(&mut self) {
+        let chan = self
+            .channel
+            .take()
+            .expect("channel taken, maybe dropped twice");
+        if let Ok(ch) = Arc::try_unwrap(chan) {
```
Comment (Connor1996) [inline components/raftstore/src/store/snapshot_backup.rs:291]: why `try_unwrap`

Comment (YuJuncen) [reply components/raftstore/src/store/snapshot_backup.rs:291]: This is a way to check whether this is the last one... I'm going to somehow refactor this code. You may review this part of code later.

File: components/backup/src/disk_snap.rs (hunk 28 above)
Comment (YuJuncen) [reply components/backup/src/disk_snap.rs:228]: We may need to fetch back some error information region by region.

File: components/raftstore/src/store/snapshot_backup.rs (hunk 29 above)
Comment (YuJuncen) [reply components/raftstore/src/store/snapshot_backup.rs:97]: Do you have some good ideas? Perhaps `PrepareDiskSnapObserver`?

File: components/raftstore/src/store/fsm/peer.rs (hunk 30 above)
Comment (YuJuncen) [reply components/raftstore/src/store/fsm/peer.rs:1011]: Oops, nice catch.

File: components/raftstore/src/store/snapshot_backup.rs [hunk 36]
```diff
@@ -320,14 +362,20 @@ impl SnapshotBrWaitApplySyncer {
             }
             AbortReason::Duplicated => metrics::SNAP_BR_WAIT_APPLY_EVENT.duplicated.inc(),
         }
-        self.channel.as_ref().unwrap().lock().unwrap().take();
+        if !core.aborted() {
```
Comment (Connor1996) [inline components/raftstore/src/store/snapshot_backup.rs:365]: always calling `abort`, and if the channel is none, do nothing innerly

File: Cargo.toml [hunk 37]
```diff
@@ -217,8 +217,8 @@ procinfo = { git = "https://github.com/tikv/procinfo-rs", rev = "7693954bd1dd86e
 # When you modify TiKV cooperatively with kvproto, this will be useful to submit the PR to TiKV and the PR to
 # kvproto at the same time.
 # After the PR to kvproto is merged, remember to comment this out and run `cargo update -p kvproto`.
-# [patch.'https://github.com/pingcap/kvproto']
-# kvproto = { git = "https://github.com/your_github_id/kvproto", branch = "your_branch" }
+[patch.'https://github.com/pingcap/kvproto']
+kvproto = { git = "https://github.com/yujuncen/kvproto", branch = "advanced-prepare" }
```
Comment (Connor1996) [inline Cargo.toml:221]: don't forget to update

**Review by Connor1996 — APPROVED** [review]
LGTM

File: Cargo.toml (hunk 37 above)
Comment (YuJuncen) [reply Cargo.toml:221]: I think we can change this after this PR is LGT2.

File: components/raftstore/src/store/snapshot_backup.rs [hunk 38]
```diff
@@ -0,0 +1,388 @@
...
+            // We disable `CompactLog` here because if the log get truncated, 
+            // we may take a long time to send snapshots during restoring.
+            AdminCmdType::CompactLog |
+            // We will allow `Commit/RollbackMerge` here because the 
+            // `wait_pending_admin` will wait until the merge get finished.
+            // If we reject them, they won't be able to see the merge get finished.
+            // And will finally time out.
+            AdminCmdType::PrepareMerge |
+            AdminCmdType::ChangePeer |
+            AdminCmdType::ChangePeerV2
```
Comment (overvenus) [inline components/raftstore/src/store/snapshot_backup.rs:249]: How about `BatchSwitchWitness`?

File: components/raftstore/src/store/snapshot_backup.rs [hunk 39]
```diff
@@ -0,0 +1,388 @@
...
+
+impl SyncerCore {
+    fn new(report_id: u64, feedback: oneshot::Sender<SyncReport>) -> Self {
+        Self {
+            report_id,
+            feedback: Some(feedback),
+        }
+    }
+
+    fn aborted(&self) -> bool {
```
Comment (overvenus) [inline components/raftstore/src/store/snapshot_backup.rs:294]: A method/function that returns a boolean should be named as a question, eg., `is_aborted`?

File: components/raftstore/src/store/snapshot_backup.rs [hunk 40]
```diff
@@ -0,0 +1,388 @@
...
+        self.before
+            .load(Ordering::Acquire)
+            .saturating_sub(epoch_second_coarse())
+    }
+
+    fn reject(&self) -> CopError {
+        CopError::RequireDelay {
+            after: Duration::from_secs(self.remained_secs()),
+            reason:
+                "[Suspended] Preparing disk snapshot backup, ingests and some of admin commands are suspended."
```
Comment (overvenus) [inline components/raftstore/src/store/snapshot_backup.rs:119]: What does the `[Suspended]` refer to? If no, how about `[snapshot_backup]`? as it belongs to the feature `snapshot_backup`.

File: components/test_raftstore/src/transport_simulate.rs [hunk 41]
```diff
@@ -273,6 +273,12 @@ pub trait FilterFactory {
     fn generate(&self, node_id: u64) -> Vec<Box<dyn Filter>>;
 }
 
+impl<F: Fn(u64) -> Fl, Fl: Filter + 'static> FilterFactory for F {
```
[the remark this answers is not in the document]
Comment (YuJuncen) [reply components/test_raftstore/src/transport_simulate.rs:276]: Here uses this:
https://github.com/tikv/tikv/pull/15946/files/50652324d022c77ef000889faf21c1c0380afef4#diff-96f1c5ec1b8bab5d6d8c06672c3ac23bf006dc1312b80b4007a3f5b9c42985fdR117-R121

File: components/raftstore/src/store/snapshot_backup.rs (hunk 40 above)
Comment (YuJuncen) [reply components/raftstore/src/store/snapshot_backup.rs:119]: It is just a keyword for retrying, perhaps we can remove it after check with some clients' implementation (specially `tidb-lightning`.)

File: components/raftstore/src/coprocessor/error.rs [hunk 42]
```diff
@@ -1,12 +1,14 @@
...
-use std::{error::Error as StdError, result::Result as StdResult};
+use std::{error::Error as StdError, result::Result as StdResult, time::Duration};
 
 use error_code::{self, ErrorCode, ErrorCodeExt};
 use thiserror::Error;
 
 #[derive(Debug, Error)]
 pub enum Error {
+    #[error("required retry after {after:?}, hint: {reason:?}")]
+    RequireDelay { after: Duration, reason: String },
```
[the remark this answers is not in the document]
Comment (YuJuncen) [reply components/raftstore/src/coprocessor/error.rs:11]: The client. Generally we will generate a `ServerIsBusy` with retry backoff of `RequireDelay.after` and the `reason` is used for debugging.

File: components/raftstore/src/store/snapshot_backup.rs (hunk 38 above)
Comment (YuJuncen) [reply components/raftstore/src/store/snapshot_backup.rs:249]: I think they won't make things worse. However we can still add it since rejecting it won't be harmful anyway.

File: components/raftstore/src/store/snapshot_backup.rs [hunk 43]
```diff
@@ -0,0 +1,388 @@
...
+            AbortReason::Duplicated => metrics::SNAP_BR_WAIT_APPLY_EVENT.duplicated.inc(),
+        }
+        core.abort(reason);
+    }
+}
+
+#[derive(Debug, PartialEq)]
+pub enum AbortReason {
+    EpochNotMatch(kvproto::errorpb::EpochNotMatch),
+    TermMismatch {
```
[the remark this answers is not in the document]
Comment (YuJuncen) [reply components/raftstore/src/store/snapshot_backup.rs]: Done, now it will return a `StaleCommand`. The term info and region id has been kept for debug usage.

**Review by overvenus — APPROVED** [review]
