### PR TITLE
log_backup: Adapt for log backup encrypting

### LINKED ISSUE #15083: log-backup: support encrypting the temporary files
## Development Task
As title, for now, temporary files are plain text. Which isn't good enough and may be leaked when TiKV exits unexpectedly.

### PR DESCRIPTION
**Pull request by YuJuncen**
### What is changed and how it works?

Issue Number: Close #15083

What's Changed:

```commit-message
Allows log backup to read the encryption config and use it to encrypt the local files.
```

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [ ] Need to cherry-pick to the release branch

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note

```release-note
Now, temporary files generated by log backup will be encrypted if encryption enabled.
```

### CODE REVIEW

**Review by Leavrth — APPROVED** [review]

**Review by 3pointer — APPROVED** [review]

File: components/backup-stream/tests/failpoints/mod.rs [hunk 1]
```diff
@@ -400,6 +404,67 @@ mod all {
...
+            .into_iter()
+            .filter_map(|file| file.ok().filter(|f| f.file_type().is_file()))
+            .collect::<Vec<_>>();
+        assert!(!files.is_empty());
+        for dir in files {
+            let data = std::fs::read(dir.path()).unwrap();
+            // assert it contains data...
+            assert_ne!(data.len(), 0);
+            // ... and is plain zstd compression.
+            assert_ne!(
```
Comment (zhangjinpeng87) [inline components/backup-stream/tests/failpoints/mod.rs:450]: This is just a not equal assertion, can't prove the data is encrypt as planned.

Comment (YuJuncen) [reply components/backup-stream/tests/failpoints/mod.rs:450]: Yes, it only makes sure that the content was probably encrypted. Because the CTR mode have a random initial vector, it is a little bit harder to verify by an equal check.

File: components/backup-stream/src/tempfiles.rs [hunk 2]
```diff
@@ -505,6 +505,9 @@ impl FileCore {
     }
 
     fn should_swap_out(&self, new_data_size: usize) -> bool {
+        fail::fail_point!("log_backup::FileCore::should_swap_out::return_true", |_| {
```
Comment (overvenus) [inline components/backup-stream/src/tempfiles.rs:508]: In TiKV, we prefer failpoint name matches "[a-z][a-z0-9_]+".

**Review by overvenus — APPROVED** [review]

File: components/backup-stream/tests/failpoints/mod.rs (hunk 1 above)
Comment (YuJuncen) [reply components/backup-stream/tests/failpoints/mod.rs:446]: (I have added more assertions to make sure there isn't values presented in plain text.)

**Review by Leavrth — APPROVED** [review]
