### PR TITLE
degrade TiKV Error log level for false alarm

### LINKED ISSUE #16018: tikv report "cleanup import sst failed" during import into command
### What version of TiKV are you using?
v7.5.0
076b79c54b9e7656f9119865d4ed75bec3bd58d6

### Steps to reproduce
MySQL [test]> IMPORT INTO test.item_core  FROM "ks3://qe-testing/xxx/10T-copy/data*/data*/test.item_core.*.csv?access-key=xxx" with thread=30,detached;

### What did you expect?
import into  successfully

### What did happened?
```
found "cleanup import sst failed" ERROR in log
2023-11-17 21:46:36 (UTC+08:00)TiKV [tc-tikv-14.tc](http://tc-tikv-14.tc/)-tikv-peer.sql-global-sort-and-mvindex-testing-tps-3720033-1-803.svc:20160[[store.rs:2881](http://store.rs:2881/)] ["cleanup import sst failed"] [err_code=KV:Raftstore:Unknown] [err="Other(\"[components/raftstore/src/store/fsm/[store.rs:2763](http://store.rs:2763/)]: No such file or directory (os error 2)\")"] [store_id=25] [thread_id=0x5]
2023-11-17 21:48:19 (UTC+08:00)TiKV [tc-tikv-2.tc](http://tc-tikv-2.tc/)-tikv-peer.sql-global-sort-and-mvindex-testing-tps-3720033-1-803.svc:20160[[store.rs:2881](http://store.rs:2881/)] ["cleanup import sst failed"] [err_code=KV:Raftstore:Unknown] [err="Other(\"[components/raftstore/src/store/fsm/[store.rs:2763](http://store.rs:2763/)]: No such file or directory (os error 2)\")"] [store_id=6] [thread_id=0x5]
2023-11-17 21:56:36 (UTC+08:00)TiKV [tc-tikv-14.tc](http://tc-tikv-14.tc/)-tikv-peer.sql-global-sort-and-mvindex-testing-tps-3720033-1-803.svc:20160[[store.rs:2881](http://store.rs:2881/)] ["cleanup import sst failed"] [err_code=KV:Raftstore:Unknown] [err="Other(\"[components/raftstore/src/store/fsm/[store.rs:2763](http://store.rs:2763/)]: No such file or directory (os error 2)\")"] [store_id=25] [thread_id=0x5]
```

### LINKED ISSUE #18745: degrade TiKV Error log level for false alarms

### PR DESCRIPTION
**Pull request by exit-code-1**
### What is changed and how it works?

Issue Number:  Close #16018 , Close #18745 

What's Changed:

```commit-message
degrade TiKV Error log level for false alarm
```

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [ ] Need to cherry-pick to the release branch

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [x] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note

```release-note
Downgrades the severity level of certain misleading logs to reduce false alarms in monitoring systems.
```

### CODE REVIEW

**Review by LykxSassinator — APPROVED** [review]

File: components/raftstore/src/store/fsm/store.rs [hunk 1]
```diff
@@ -2278,7 +2280,7 @@ impl<EK: KvEngine, ER: RaftEngine, T: Transport> StoreFsmDelegate<'_, EK, ER, T>
         }
 
         if !msg.has_region_epoch() {
-            error!(
+            info!(
```
Comment (overvenus) [inline components/raftstore/src/store/fsm/store.rs]: Let's warning it.

File: components/raftstore/src/store/worker/cleanup_snapshot.rs [hunk 2]
```diff
@@ -148,7 +148,10 @@ where
 
                 let msg = StoreMsg::GcSnapshotFinish;
                 if let Err(e) = StoreRouter::send(&self.router, msg) {
-                    error!(%e; "send StoreMsg::GcSnapshotFinish failed");
+                    warn!(
```
Comment (overvenus) [inline components/raftstore/src/store/worker/cleanup_snapshot.rs:151]: Let's keep it as an error, because `StoreTick::SnapGc` no longer ticks if it fails to send `StoreMsg::GcSnapshotFinish`.

File: components/raftstore/src/store/entry_storage.rs [hunk 3]
```diff
@@ -1187,7 +1187,7 @@ impl<EK: KvEngine, ER: RaftEngine> EntryStorage<EK, ER> {
                         // FIXME: the assertion below doesn't hold.
                         // assert!(is_valid, "the warmup range should still be valid");
                         if !is_valid {
-                            error!(
+                            warn!(
```
Comment (overvenus) [inline components/raftstore/src/store/entry_storage.rs:1190]: It looks like an error.

File: src/server/raftkv/mod.rs [hunk 4]
```diff
@@ -246,7 +246,7 @@ pub fn async_write_callback_dropped_err() -> errorpb::Error {
 
 pub fn drop_on_applied_callback() -> WriteResponse {
     let bt = backtrace::Backtrace::new();
-    error!("async write on_applied callback is dropped"; "backtrace" => ?bt);
+    warn!("async write on_applied callback is dropped"; "backtrace" => ?bt);
```
Comment (overvenus) [inline src/server/raftkv/mod.rs]: It is an error, TiKV does not allow dropping a callback without invoking it.

File: src/server/raftkv/raft_extension.rs [hunk 5]
```diff
@@ -95,8 +95,9 @@ where
             .router
             .report_snapshot_status(region_id, to_peer_id, status)
         {
-            error!(?e;
+            warn!(
                 "report snapshot to peer failes";
```
Comment (overvenus) [inline src/server/raftkv/raft_extension.rs]:
```suggestion
                "report snapshot to peer fails";
```

BTW, please correct the typo.

File: src/server/raft_client.rs [hunk 6]
```diff
@@ -593,7 +593,7 @@ where
         }
 
         let (sink_err, recv_err) = (res.0.err(), res.1.err());
-        error!("connection aborted"; "store_id" => self.store_id, "sink_error" => ?sink_err, "receiver_err" => ?recv_err, "addr" => %self.sender.addr);
+        warn!("connection aborted"; "store_id" => self.store_id, "sink_error" => ?sink_err, "receiver_err" => ?recv_err, "addr" => %self.sender.addr);
```
Comment (overvenus) [inline src/server/raft_client.rs]:
```suggestion
        warn!(
            "connection aborted";
            "store_id" => self.store_id,
            "sink_error" => ?sink_err,
            "receiver_err" => ?recv_err,
            "addr" => %self.sender.addr
        );
```

File: components/raftstore/src/store/fsm/store.rs (hunk 1 above)
Comment (exit-code-1) [reply components/raftstore/src/store/fsm/store.rs]: Agreed.

File: components/raftstore/src/store/worker/cleanup_snapshot.rs (hunk 2 above)
Comment (exit-code-1) [reply components/raftstore/src/store/worker/cleanup_snapshot.rs:151]: We should downgrade it to `warn!` to handle false alarm during node shutdown.

File: components/raftstore/src/store/entry_storage.rs (hunk 3 above)
Comment (exit-code-1) [reply components/raftstore/src/store/entry_storage.rs:1190]: Resolved (use `warn!`).

File: src/server/raftkv/mod.rs (hunk 4 above)
Comment (exit-code-1) [reply src/server/raftkv/mod.rs]: Agree！

File: src/server/raftkv/raft_extension.rs (hunk 5 above)
Comment (exit-code-1) [reply src/server/raftkv/raft_extension.rs]: Done！

File: src/server/raft_client.rs (hunk 6 above)
Comment (exit-code-1) [reply src/server/raft_client.rs]: Done!
