### PR TITLE
tidb_query_expr: fix incorrect intdiv for decimal type

### LINKED ISSUE #16024: intdiv for decimal is not handle correctly
### What version of TiKV are you using?

master

Need to port https://github.com/pingcap/tidb/pull/11804 from TiDB to TiKV

### PR DESCRIPTION
**Pull request by wjhuang2016**
### What is changed and how it works?

Issue Number: Close #16024

What's Changed:

```
fix incorrect intdiv for decimal type
```

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

Side effects

### Release note 

```release-note
None
```

### CODE REVIEW

File: components/tidb_query_expr/src/impl_arithmetic.rs [hunk 1]
```diff
@@ -452,16 +452,33 @@ fn int_divide_decimal(ctx: &mut EvalContext, lhs: &Decimal, rhs: &Decimal) -> Re
...
-                )
-                .map(Some)?
-        })
+        if result.is_truncated() {
+            return Ok(Some(result.unwrap()));
+        }
+        Err(Error::overflow("BIGINT", format!("({} / {})", lhs, rhs)).into())
+    } else {
+        Ok(None)
+    }
```
Comment (LykxSassinator) [inline components/tidb_query_expr/src/impl_arithmetic.rs:461]:
```suggestion
        return if result.is_truncated() {
            Ok(Some(result.unwrap()))
        } else {
            Err(Error::overflow("BIGINT", format!("({} / {})", lhs, rhs)).into())
        };
    }
    Ok(None)
```

File: components/tidb_query_expr/src/impl_arithmetic.rs [hunk 2]
```diff
@@ -452,16 +452,33 @@ fn int_divide_decimal(ctx: &mut EvalContext, lhs: &Decimal, rhs: &Decimal) -> Re
...
+            let signed_result = result.as_i64();
+            if signed_result.unwrap() == 0 && signed_result.is_truncated() {
+                return Ok(Some(0));
+            }
+            return Err(Error::overflow("BIGINT UNSIGNED", format!("({} / {})", lhs, rhs)).into());
+        }
+        Ok(Some(unsigned_result.unwrap() as i64))
     } else {
         Ok(None)
     }
```
Comment (LykxSassinator) [inline components/tidb_query_expr/src/impl_arithmetic.rs:484]:
```suggestion
    if let Some(result) = result {
        let unsigned_result = result.as_u64();
        if unsigned_result.is_overflow() {
            let signed_result = result.as_i64();
            return if signed_result.unwrap() == 0 && signed_result.is_truncated() {
                Ok(Some(0))
            } else {
                Err(Error::overflow("BIGINT UNSIGNED", format!("({} / {})", lhs, rhs)).into())
            };
        }
        Ok(Some(unsigned_result.unwrap() as i64))
    }
    Ok(None)
```

**Review by iosmanthus — APPROVED** [review]
