### PR TITLE
encryption: fix key collision issue in tablet snapshot

### LINKED ISSUE #15059: [Dynamic Region] raft log lag more and more after inject one tikv network partition for 50m and recover
### What version of TiKV are you using?
./tikv-server -V
 TiKV 
Release Version:   7.3.0-alpha
Edition:           Community
Git Commit Hash:   425f6f262f577425612cf1663ea6cceada72c724
Git Commit Branch: heads/refs/tags/v7.3.0-alpha
UTC Build Time:    2023-06-30 11:15:31
Rust Version:      rustc 1.67.0-nightly (96ddd32c4 2022-11-14)
Enable Features:   pprof-fp jemalloc mem-profiling portable sse test-engine-kv-rocksdb test-engine-raft-raft-engine cloud-aws cloud-gcp cloud-azure
Profile:           dist_release
2023-07-03T09:59:28.474+0800

### What operating system and CPU are you using?
8c/32g

### Steps to reproduce
1、run tpcc
2、inject one tikv network partition for 50m and recover

### What did you expect?
raft log lag can catch up within some time

### What did happened?
raft log lag more and more after inject one tikv network partition for 50m and recover
9f12f8e1-48e0-431b-80b2-b89c02a19250

### PR DESCRIPTION
**Pull request by tabokie**
### What is changed and how it works?

Issue Number: Close #15059

What's Changed:

```commit-message
- Properly clean up encryption keys when cleaning up snapshot cache file.
- Allow overwriting stale encryption keys when importing remote keys.
```

### Check List 

Tests 

- Unit test

### Release note 

```release-note
None
```

### CODE REVIEW

File: src/server/tablet_snap.rs [hunk 1]
```diff
@@ -314,6 +314,9 @@ async fn cleanup_cache(
             }
         }
         fs::remove_file(entry.path())?;
+        if let Some(m) = key_manager {
+            m.delete_file(entry.path().to_str().unwrap())?;
+        }
```
Comment (overvenus) [inline src/server/tablet_snap.rs:319]: Is there any `EncryptedFilesystem`? Maybe we can wrap these two remove-file in `EncryptedFilesystem::remove_file`?

**Review by overvenus — APPROVED** [review]

File: src/server/tablet_snap.rs (hunk 1 above)
Comment (tabokie) [reply src/server/tablet_snap.rs:319]: Maybe in another PR, file_system is a drop-in replacement for std::fs, but `remove_encrypted_file` requires additional parameter, and it can't be placed in file_system crate due to cyclic dependency.

**Review by tonyxuqqi — APPROVED** [review]
