### PR TITLE
raftstore: continue GC  snapshot files when it encounters a corrupted snapshot

### LINKED ISSUE #10813: corrupted snapshot can prevent snapshot files gc
### What version of TiKV are you using?
v3.0.8

### What operating system and CPU are you using?
Doesn't matter.

### Steps to reproduce
Some of snapshot files get deleted after received, so the snapshot is corrupted. And the peer is deleted before applying snapshot.

### What did you expect?
Corrupted snapshot will be deleted in the end.

### What did happened?
Store fails to delete the corrupted snapshot files. And all other stale snapshot files are not gc anymore.

The problem is it returns early here:

https://github.com/tikv/tikv/blob/master/components/raftstore/src/store/fsm/store.rs#L2129.

### PR DESCRIPTION
**Pull request by tonyxuqqi**
### What problem does this PR solve?

Issue Number: close #10813 

Problem Summary:

### What is changed and how it works?
When snapshot GC runs into problem (such as file corrupted), today it stopped processing other GC-able snapshot files.
This PR will make it continue processing rest of the snapshot files.

### Related changes

Tests 
- Unit test

Side effects
No.

### Release note 

```release-note
RaftStore Snapshot GC fix: fix the issue that snapshot GC missed GC snapshot files when there's one snapshot file failed to be GC-ed. 
```
/cc @BusyJay

### CODE REVIEW

File: tests/failpoints/cases/test_snap.rs [hunk 1]
```diff
@@ -467,3 +470,73 @@ fn test_cancel_snapshot_generating() {
...
+    loop {
+        let snap_keys = cluster.get_snap_mgr(3).list_idle_snap().unwrap();
+        if snap_keys.is_empty() {
+            panic!("no snapshot file is found");
+        }
+
+        let mut found_unexpected_file = false;
+        let mut found_expected_file = false;
+        for (snap_key, _is_sending) in snap_keys {
+            if snap_key.region_id == 2 && snap_key.idx == 1 {
```
Comment (hicqu) [inline tests/failpoints/cases/test_snap.rs:518]: It's so strange that the case can pass. I thought `run_conf_change` creates a region with ID 1 instead of 2.

**Comment by hicqu** [comment]
Rest LGTM.

**Review by hicqu — APPROVED** [review]

**Review by hicqu — APPROVED** [review]

File: tests/failpoints/cases/test_snap.rs (hunk 1 above)
Comment (tonyxuqqi) [reply tests/failpoints/cases/test_snap.rs:518]: The reason to have region_id 2 is because we want to make "match self.ctx.router.send(region_id, gc_snap)" fail. And the way to make it fail is to have a non-exist region_id. That's why we have region_id 2 here instead of 1.

**Review by BusyJay — APPROVED** [review]
