### PR TITLE
log-backup: fix early return

### LINKED ISSUE #13281: data inconsistency after br PiTR restore
### What version of TiKV are you using?
/ # /tikv-server -V                                                                                            
TiKV                                                                                                           
Release Version:   6.2.0-alpha
Edition:           Community                                                                                   
Git Commit Hash:   7824699f4e05feb3eb37b12265ecc1e26511a4d7                                                    
Git Commit Branch: heads/refs/tags/v6.2.0                                                                      
UTC Build Time:    2022-08-11 13:49:18                                                                         
Rust Version:      rustc 1.62.0-nightly (7c4b47696 2022-04-30)                                                 
Enable Features:   pprof-fp jemalloc mem-profiling portable sse test-engine-kv-rocksdb test-engine-raft-raft-en
gine cloud-aws cloud-gcp cloud-azure                                                                           
Profile:           dist_release                                                                                

### What operating system and CPU are you using?
K8S, 8C 16G

### Steps to reproduce
1. Start log backup
2. Do full backup
3. Start workload with 1000 tables for 10 min
```
sysbench --db-driver=mysql --mysql-host=upstream-tidb.brie-acceptance-pitr-robust-tps-1083099-1-452 --mysql-port=4000 --mysql-user=root --mysql-db=sbtest1000 --tables=1000 --table-size=10000 --create_secondary=off --time=60 --threads=20 oltp_insert prepare
sysbench --db-driver=mysql --mysql-host=upstream-tidb.brie-acceptance-pitr-robust-tps-1083099-1-452 --mysql-port=4000 --mysql-user=root --mysql-db=sbtest1000 --tables=1000 --table-size=10000 --create_secondary=off --time=600 --threads=20 oltp_insert run
```
4. Wait checkpoint move forward
```
● Total 1 Tasks.
> #1 <
              name: task1
            status: ● NORMAL
             start: 2022-08-13 02:28:36.516 +0000
               end: 2090-11-18 14:07:45.624 +0000
           storage: s3://tmp/br-log-backup84ed324a-894c-4f13-84fa-44675095787d/Log
       speed(est.): 0.00 ops/s
checkpoint[global]: 2022-08-13 02:43:07.216 +0000; gap=4m59s
[2022/08/13 10:48:06.135 +08:00] [INFO] [br.go:518] ["Current log backup checkpoint: 2022-08-13 02:43:07 +0000 UTC, expect it is larger than: 2022-08-13 02:41:05.816 +0000 UTC"]

```
  5. Do a PiTR restore, and check data consistency
```
/br  restore  point "--storage" "s3://tmp/br-log-backup84ed324a-894c-4f13-84fa-44675095787d/Log" "--pd" "http://downstream-pd.brie-acceptance-pitr-robust-tps-1083099-1-452:2379" "--full-backup-storage" "s3://tmp/br-log-backup84ed324a-894c-4f13-84fa-44675095787d/Full"
```
    
### What did you expect?
Data should be consistent after PiTR restore

### What did happened?
PiTR Restore was successful, but data consistency check failed via sync_diff_inspector.

origin_img_v2_0ef751b7-af01-4067-a24a-1b40bf07f7cg

### PR DESCRIPTION
**Pull request by YuJuncen**
### What is changed and how it works?

Issue Number: Close #13281 

What's Changed:
This PR fixed a bug that may cause data loss with the satisfaction of these conditions:
- In the initial scanning stage, if...
  - There are more than 1,024 adjacent keys are prewritten but not committed. 
  - The values of these keys are all short enough to be inlined in the `write` CF.
("adjacent" means, the initial scanning cannot get any commit entries interleaving them, the `DeltaScanner` emits a batch with 1,024 `Prewrite`s).
- If there are some keys committed BEFORE the initial scanning but NOT YET have been observed, those key would be lost. (For a detailed case, check the integration test `split_txn`).

```commit-message
Fixed a bug that may cause data loss in log backup.
```

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Integration test
- Manual test (add detailed scripts or steps below)
We have tested this with 1,000 tables in `sysbench` `oltp_write_only` prepare phase.
  - with this PR, no data loss observed.
  - without this PR, there would always be data loss for some tables.

### Release note 

```release-note
Fixed a bug that may cause PiTR losing some data when there are too many adjacent short row putting.
```

### CODE REVIEW

File: components/backup-stream/tests/mod.rs [hunk 1]
```diff
@@ -650,6 +665,45 @@ mod test {
         suite.cluster.shutdown();
     }
 
+    /// This test tests whether we can handle some weird transactions and their
```
Comment (overvenus) [inline components/backup-stream/tests/mod.rs:668]: How the "weird transactions" looks like? Could you add some comments?

**Review by overvenus — APPROVED** [review]

**Review by 3pointer — APPROVED** [review]
LGTM
