### PR TITLE
test: fix unstable test test_node_merge_write_data_to_source_region_after_merging

### LINKED ISSUE #7909: cases::test_merge::test_node_merge_write_data_to_source_region_after_merging failed
cases::test_merge::test_node_merge_write_data_to_source_region_after_merging

 Latest failed builds: 
https://internal.pingcap.net/idc-jenkins/job/tikv_master_test_coverage/1268/consoleFull

### PR DESCRIPTION
**Pull request by NingLin-P**
Signed-off-by: linning <linningde25@gmail.com>

### What problem does this PR solve?

Issue Number: close #7909

Problem Summary:

Although #7909 previous fixed at #8558, it is still quite unstable (especially on release-4.0), the log shows that the test panic while exiting the test because a new split region failed to send `PeerMsg::Start` while the raftstore is shutting down

### What is changed and how it works?

What's Changed:

Make sure the region finish split before trigger the `pause` fail point

### Check List 

Tests 

- Unit test

### Release note 
- No release note

### CODE REVIEW

File: tests/failpoints/cases/test_merge.rs [hunk 1]
```diff
@@ -994,6 +994,11 @@ fn test_node_merge_write_data_to_source_region_after_merging() {
 
     let right_peer_2 = find_peer(&right, 2).cloned().unwrap();
     assert_eq!(right_peer_2.get_id(), 2);
+    {
+        // Make sure peer 2 finish split before pause
+        cluster.must_put(b"k2pause", b"vpause");
+        must_get_equal(&cluster.get_engine(2), b"k2pause", b"vpause");
+    }
```
Comment (gengliqi) [inline tests/failpoints/cases/test_merge.rs:1001]: Hmmm. I think we don't need the brace?

**Review by gengliqi — APPROVED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]
