### PR TITLE
raftstore: fix a panic in read index queue

### LINKED ISSUE #6607: tikv panic about replica reads
### What version of TiKV are you using?
commit: `5fd2239d508a1bd437d2f838c71b1d12fe61ad92`

### What did happened?
```
2020/02/13 06:18:52.154 +00:00] [FATAL] [lib.rs:503] ["called `Option::unwrap()` on a `None` value"] [backtrace="stack backtrace:
   0: tikv_util::set_panic_hook::{{closure}}
             at components/tikv_util/src/lib.rs:502
   1: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:475
   2: rust_begin_unwind
             at src/libstd/panicking.rs:375
   3: core::panicking::panic_fmt
             at src/libcore/panicking.rs:84
   4: core::panicking::panic
             at src/libcore/panicking.rs:51
   5: core::option::Option<T>::unwrap
             at rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libcore/macros/mod.rs:15
      tikv::raftstore::store::read_queue::ReadIndexQueue::advance_replica_reads
             at root/tikv/src/raftstore/store/read_queue.rs:182
      tikv::raftstore::store::peer::Peer::apply_reads
             at root/tikv/src/raftstore/store/peer.rs:1423
      tikv::raftstore::store::peer::Peer::handle_raft_ready_apply
             at root/tikv/src/raftstore/store/peer.rs:1348
      tikv::raftstore::store::fsm::peer::PeerFsmDelegate<T,C>::post_raft_ready_append
             at root/tikv/src/raftstore/store/fsm/peer.rs:659
   6: tikv::raftstore::store::fsm::store::RaftPoller<T,C>::handle_raft_ready
             at root/tikv/src/raftstore/store/fsm/store.rs:550
      <tikv::raftstore::store::fsm::store::RaftPoller<T,C> as batch_system::batch::PollHandler<tikv::raftstore::store::fsm::peer::PeerFsm,tikv::raftstore::store::fsm::store::StoreFsm>>::end
             at root/tikv/src/raftstore/store/fsm/store.rs:693
      batch_system::batch::Poller<N,C,Handler>::poll
             at root/tikv/components/batch-system/src/batch.rs:329
   7: batch_system::batch::BatchSystem<N,C>::spawn::{{closure}}
             at root/tikv/components/batch-system/src/batch.rs:392
      std::sys_common::backtrace::__rust_begin_short_backtrace
             at rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/sys_common/backtrace.rs:136
   8: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}
             at rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/thread/mod.rs:469
      <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/panic.rs:318
      std::panicking::try::do_call
             at rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/panicking.rs:292
      std::panicking::try
             at rustc/0de96d37fbcc54978458c18f5067cd9817669bc8//src/libpanic_unwind/lib.rs:78
      std::panic::catch_unwind
             at rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/panic.rs:394
      std::thread::Builder::spawn_unchecked::{{closure}}
             at rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/thread/mod.rs:468
      core::ops::function::FnOnce::call_once{{vtable.shim}}
             at rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libcore/ops/function.rs:232
   9: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/liballoc/boxed.rs:1022
  10: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/liballoc/boxed.rs:1022
      std::sys_common::thread::start_thread
             at src/libstd/sys_common/thread.rs:13
      std::sys::unix::thread::Thread::new::thread_start
             at src/libstd/sys/unix/thread.rs:80
  11: <unknown>
  12: __clone
"] [location=/rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libcore/macros/mod.rs:15]
```

### PR DESCRIPTION
**Pull request by hicqu**
Signed-off-by: qupeng <qupeng@pingcap.com>

###  What have you changed?
Fix a bug in read index queue during role changes.
Close #6607 .

When role changes, `clear_uncommitted` will be called after `advance_for_leader`. After these 2 method are called, `ReadQueue::context` could still contain some `uuid`s, which can't be cleared unless the peer is removed. When the peer becomes follower again, and receives a duplicated `ReadIndexResp` for old requests already committed, the `uuid` could be poped from `ReadQueue::contexts` with a stale offset, so panic occurs.

###  What is the type of the changes?
Bugfix (a change which fixes an issue)

###  How is the PR tested?
Unit test

###  Any examples? (optional)

### CODE REVIEW

**Comment by youjiali1995** [comment]
@hicqu Will it be merged into v3.1.0-beta.2?

File: src/raftstore/store/read_queue.rs [hunk 1]
```diff
@@ -123,7 +123,7 @@ impl ReadIndexQueue {
         self.handled_cnt = 0;
     }
 
-    pub fn clear_uncommitted(&mut self, term: u64) {
+    pub fn clear_uncommitted_on_role_change(&mut self, term: u64) {
         let mut removed = 0;
         for mut read in self.reads.drain(self.ready_cnt..) {
             self.contexts.remove(&read.id);
```
Comment (5kbpers) [inline src/raftstore/store/read_queue.rs]: I think this operation is not necessary anymore since the map is cleared at the next step.

**Comment by BusyJay** [comment]
Can you talk more about it? Like what leads to panic and why choose the fix.
