### PR TITLE
tikv_util: Clippy fix

### LINKED ISSUE #8336: Fix Clippy warnings
`make clippy` results in one Clippy warning (not sure how this made it past CI) in components/tidb_query_codegen, which seems easy to fix. 

When running `make clippy` we disable a lot of warnings, when running `cargo clippy` we get the default set of lints and we see a lot of Clippy warnings. Some of those really should be ignored, but some could be easily fixed. You can see even more things that could be fixed with `-Wrust-2018-idioms` (cc #4301)

It would be great to fix a bunch of those, and perhaps re-enable the lints if appropriate.

If you have any questions about whether a warning should be fixed or not, please ask me here or in Slack.

### PR DESCRIPTION
**Pull request by TszKitLo40**
Signed-off-by: Zijie Lu <wslzj40@gmail.com>

### What problem does this PR solve?

Issue Number: #8336 

Problem Summary:

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:
Clippy fix for `tikv_uitl`
### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- PR to update `pingcap/tidb-ansible`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 
- No release note

### CODE REVIEW

File: components/tikv_util/src/metrics/threads_dummy.rs [hunk 1]
```diff
@@ -36,3 +36,9 @@ impl ThreadInfoStatistics {
         HashMap::default()
     }
 }
+
+impl Default for ThreadInfoStatistics {
```
Comment (BusyJay) [inline components/tikv_util/src/metrics/threads_dummy.rs:40]: We allow clippy::new_without_default explictly.

Comment (TszKitLo40) [reply components/tikv_util/src/metrics/threads_dummy.rs:40]: OK, so we can remove all the Default method is this pr?

Comment (TszKitLo40) [reply components/tikv_util/src/metrics/threads_dummy.rs:40]: Are there any command to allow clippy::new_without_default in clippy?

Comment (BusyJay) [reply components/tikv_util/src/metrics/threads_dummy.rs]: It's at https://github.com/tikv/tikv/blob/master/scripts/clippy#L20

Comment (TszKitLo40) [reply components/tikv_util/src/metrics/threads_dummy.rs]: So all the lints in this script is allowed?

Comment (BusyJay) [reply components/tikv_util/src/metrics/threads_dummy.rs]: `unnecessary_wraps` and `needless_range_loop` can be removed, they are not checked probably due to too many changes need to be taken.

Comment (TszKitLo40) [reply components/tikv_util/src/metrics/threads_dummy.rs]: I think it may be better to fix the clippy errors by package. And I have fixed the errors in the `tikv_util` package.

**Review by BusyJay — APPROVED** [review]

**Review by youjiali1995 — APPROVED** [review]
