### PR TITLE
raftstore: fix lost request vote messages during split

### LINKED ISSUE #8456: Request vote messages are lost during split
## Bug Report

Request vote messages are lost during split. 99.999% latency is up to 15s.

https://github.com/tikv/tikv/blob/ae7a6ecee6e3367da016df0293a9ffe9cc2b5705/components/raftstore/src/store/fsm/store.rs#L1567-L1571

### What version of TiKV are you using?

master branch.

### Steps to reproduce

sysbench oltp_write.

### PR DESCRIPTION
**Pull request by overvenus**
### What problem does this PR solve?

Fix #8456, request vote messages are lost during split.

This PR improve TiDB 99.999% Txn duration from 15s to 1s.

image

image

### What is changed and how it works?

Cache vote message into pending votes, so that new peer can response ASAP.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Integration test

### Release note 

* Fix lost request vote messages during split.

### CODE REVIEW

File: components/raftstore/src/store/fsm/store.rs [hunk 1]
```diff
@@ -1334,7 +1334,7 @@ pub fn create_raft_batch_system<EK: KvEngine, ER: KvEngine>(
 #[derive(Debug, PartialEq)]
 enum CheckMsgStatus {
     // The peer already exist
-    PeerExist,
+    PeerExist { force_send: bool },
```
Comment (NingLin-P) [inline components/raftstore/src/store/fsm/store.rs:1337]: Seem `force_send` will always be `true`.

**Comment by NingLin-P** [comment]
LGTM

File: components/raftstore/src/store/fsm/store.rs (hunk 1 above)
Comment (overvenus) [reply components/raftstore/src/store/fsm/store.rs:1337]: Yes, it's always true in the current implementation. I think it would be clear if we explicitly state the message need to be force sent.

**Comment by zhangjinpeng1987** [comment]
Better to open an individual issue to describe the bug.

File: components/raftstore/src/store/fsm/store.rs [hunk 2]
```diff
@@ -1525,19 +1514,43 @@ impl<'a, EK: KvEngine, ER: KvEngine, T: Transport, C: PdClient> StoreFsmDelegate
...
                     check_msg_status == CheckMsgStatus::NewPeerFirst,
                 )? {
-                    return Ok(());
+                    if !is_first_vote {
+                        // Can not create peer from the message and it's not the
+                        // first request vote message.
+                        return Ok(());
+                    }
                 }
+                is_first_vote
```
Comment (gengliqi) [inline components/raftstore/src/store/fsm/store.rs:1533]:
```suggestion
                    }
                    is_first_vote
                }
                false
```

File: components/raftstore/src/store/fsm/store.rs [hunk 3]
```diff
@@ -1525,19 +1518,44 @@ impl<'a, EK: KvEngine, ER: KvEngine, T: Transport, C: PdClient> StoreFsmDelegate
...
             CheckMsgStatus::NewPeer | CheckMsgStatus::NewPeerFirst => {
                 if !self.maybe_create_peer(
                     region_id,
                     &msg,
                     check_msg_status == CheckMsgStatus::NewPeerFirst,
                 )? {
-                    return Ok(());
+                    if !util::is_first_vote_msg(msg.get_message()) {
+                        // Can not create peer from the message and it's not the
+                        // first request vote message.
```
Comment (gengliqi) [inline components/raftstore/src/store/fsm/store.rs:1532]: Maybe we should add `self.ctx.raft_metrics.message_dropped.region_nonexistent += 1;` to this line and L1546?

Comment (overvenus) [reply components/raftstore/src/store/fsm/store.rs:1532]: In fact, this message is not dropped. 🤔
