### PR TITLE
config: simplify handling of nullable configurations (#12133)

### LINKED ISSUE #13467: Support configuring RocksDB write-stall settings smaller than flow control
## Bug Report

Related to #11424

Support using smaller config for RocksDB so that compaction can be triggered more often.

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #12133 to release-5.4
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tikv repo:
git pr https://github.com/tikv/tikv/pull/12738
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tikv.git pr/12738:release-5.4-8954a76e2b87
```

---

Signed-off-by: tabokie <xy.tao@outlook.com>

### What is changed and how it works?

Issue Number: Close #13467, Ref #11424

What's Changed:

Support deriving `OnlineConfig` on any `Option<T>`. One caveat is such `T` must implement `Default`.

This change is made for #12127.

### Check List 

Tests
- Unit test

### Release note 

```release-note
None
```

### CODE REVIEW

File: src/config.rs [hunk 1]
```diff
@@ -2961,9 +2954,15 @@ impl TiKvConfig {
...
         let cache_cfg = &mut self.storage.block_cache;
+<<<<<<< HEAD
         if cache_cfg.shared && cache_cfg.capacity.0.is_none() {
             cache_cfg.capacity.0 = Some(ReadableSize {
                 0: self.rocksdb.defaultcf.block_cache_size.0
+=======
+        if cache_cfg.shared && cache_cfg.capacity.is_none() {
+            cache_cfg.capacity = Some(ReadableSize(
+                self.rocksdb.defaultcf.block_cache_size.0
+>>>>>>> 8954a76e2... config: simplify handling of nullable configurations (#12133)
```
Comment (tabokie) [inline src/config.rs:2965]:
```suggestion
        if cache_cfg.shared && cache_cfg.capacity.is_none() {
            cache_cfg.capacity = Some(ReadableSize(
                self.rocksdb.defaultcf.block_cache_size.0
```

**Review by tabokie — APPROVED** [review]

**Review by glorv — APPROVED** [review]
