### PR TITLE
cdc: limit pending scan tasks (#16048)

### LINKED ISSUE #16035: TiKV OOM during CDC initial scan
### What version of TiKV are you using?
/ # /tikv-server -V
TiKV
Release Version:   6.5.3
Edition:           Enterprise
Git Commit Hash:   5165943fbffce298b61698a59620f415df239420
Git Commit Branch: heads/refs/tags/v6.5.3-20231116-5165943

### What operating system and CPU are you using?
K8S

### Steps to reproduce
1. TiDB cluster with 6 TiKV (16c 40g), 2 TiCDC 
2. Create cdc changefeed and pause it
3. Run workload to generate 1TB data for CDC to sync.
4. Resume cdc changefeed

### What did you expect?
TiKV should not OOM

### What did happened?
TiKV OOM

image
image

### PR DESCRIPTION
**Pull request by overvenus**
### What is changed and how it works?

Issue Number: Close #16035

What's Changed:

```commit-message
When TiCDC starts changefeed, it may send numerous requests leading to
the creation of numerous scan tasks. However, the initial surge of scan
tasks may cause OOM.

This commit aims to resolve the issue by implementing a mechanism that
allows TiKV to reject requests when the number of pending tasks reaches
a certain limit.
```

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

### Release note 

```release-note
Fix an issue that TiCDC captures large table may cause TiKV OOM
```

### CODE REVIEW

File: components/cdc/src/endpoint.rs [hunk 1]
```diff
@@ -659,6 +665,27 @@ impl<T: 'static + RaftStoreRouter<E>, E: KvEngine> Endpoint<T, E> {
             return;
         }
 
+        let scan_task_counter = self.scan_task_counter.clone();
+        let scan_task_count = scan_task_counter.fetch_add(1, Ordering::Relaxed);
+        let release_scan_task_counter = tikv_util::DeferContext::new(move || {
+            scan_task_counter.fetch_sub(1, Ordering::Relaxed);
+        });
+        if scan_task_count + 1 > self.config.incremental_scan_concurrency_limit as isize {
+            warn!("cdc rejects registration, too many scan tasks";
```
Comment (overvenus) [inline components/cdc/src/endpoint.rs:674]:
```suggestion
            debug!("cdc rejects registration, too many scan tasks";
```

**Review by Connor1996 — APPROVED** [review]
LGTM

**Review by LykxSassinator — APPROVED** [review]
