### PR TITLE
coprocessor:  request key needs to encode for `tls_collect_read_flow`

### LINKED ISSUE #14998: [Dynamic Regions]: the statistics of region buckets can't work well for coprocessor request
### What version of TiKV are you using?

master
### What operating system and CPU are you using?

amd
### Steps to reproduce

run sysbench table scan 
### What did you expect?
the statistics of region buckets work well
### What did happened?
the statistics of region buckets  is zero

### PR DESCRIPTION
**Pull request by bufferflies**
### What is changed and how it works?

Issue Number: Close #14998

What's Changed:

```commit-message
the request key needs to encode. If not , the bucket's key range has no intersection for the request's key range
```

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Manual test (add detailed scripts or steps below)
before
```
request key
start-key: 116, 128, 0, 0, 0, 0, 0, 0, 184, 95, 114, 128, 0, 0, 0, 0, 0, 70, 67
end-key:  116, 128, 0, 0, 0, 0, 0, 0, 184, 95, 114, 128, 0, 0, 0, 0, 0, 70, 167

buckets:
start-key:  116, 128, 0, 0, 0, 0, 0, 0, 255, 179, 95, 114, 128, 0, 0, 0, 0, 255, 0, 175, 155, 0, 0, 0, 0, 0, 250
decode-key:  116, 128, 0, 0, 0, 0, 0, 0, 179, 95, 114, 128, 0, 0, 0, 0, 0, 175, 155
end-key:   116, 128, 0, 255, 255, 255, 255, 255, 255, 254, 0, 0, 0, 0, 0, 0, 0, 248
```

after:
```
request key
start-key:  116, 128, 0, 0, 0, 0, 0, 0, 255, 184, 95, 114, 128, 0, 0, 0, 0, 255, 0, 49, 125, 0, 0, 0, 0, 0, 250
end-key:   116, 128, 0, 0, 0, 0, 0, 0, 255, 184, 95, 114, 128, 0, 0, 0, 0, 255, 0, 49, 225, 0, 0, 0, 0, 0, 250

buckets:
start-key:  116, 128, 0, 0, 0, 0, 0, 0, 255, 184, 95, 114, 128, 0, 0, 0, 0, 255, 0, 49, 225, 0, 0, 0, 0, 0, 250
end-key:   116, 128, 0, 255, 255, 255, 255, 255, 255, 254, 0, 0, 0, 0, 0, 0, 0, 248
```

Side effects

### Release note 

```release-note
the statistics of region buckets can't work well for coprocessor request 
```

### CODE REVIEW

File: src/coprocessor/tracker.rs [hunk 1]
```diff
@@ -353,14 +353,14 @@ impl<E: Engine> Tracker<E> {
...
-            Key::from_raw(end_key).as_encoded(),
+            start_key.as_encoded(),
+            end_key.as_encoded(),
             reverse_scan,
         );
         tls_collect_read_flow(
             self.req_ctx.context.get_region_id(),
-            Some(start_key),
-            Some(end_key),
+            Some(start_key.as_encoded()),
```
Comment (lhy1024) [inline src/coprocessor/tracker.rs:362]: Is it introduced by #12080? We also need to pick  it to other release

Comment (lhy1024) [reply src/coprocessor/tracker.rs:362]: Do we need to add any tests about it?

**Review by lhy1024 — APPROVED** [review]

File: src/coprocessor/tracker.rs (hunk 1 above)
Comment (nolouch) [reply src/coprocessor/tracker.rs:362]: Does it affect the hot-region schedule?

Comment (lhy1024) [reply src/coprocessor/tracker.rs:362]: > Does it affect the hot-region schedule?

I think it will only effect bucket bound, not hot-region-scheduler flow statistic or load-base-split key.

Comment (bufferflies) [reply src/coprocessor/tracker.rs:362]: > Do we need to add any tests about it?



> Does it affect the hot-region schedule?
yes，it cause that the bucket's statistics is zero. some big hot region can't splitted if it can't find the hot buckets.

Comment (bufferflies) [reply src/coprocessor/tracker.rs:362]: > Do we need to add any tests about it?

yes， I will add IT for it

**Review by pingyu — APPROVED** [review]
LGTM~
