### PR TITLE
raftstore-v2: fix destroy blocked by apply progress

### LINKED ISSUE #14215: [Dynamic Regions] Scale-in is blocked because one region's cannot promt learner to voter
### What version of TiKV are you using?

release 6.6 + tablet leak fix
### Steps to reproduce

1 Sysbench prepare about 150GB per TiKV
2) Run Sysbench read-write workload 
3) During the workload, scale-out a new TiKV node
4) During the workload, scale-in the new tikv node
### What did you expect?
The new tikv node can be scaled in and become timbstone. 
### What did happened?
The new tikv node is stuck in pending offline. And there's one region cannot be moved out because its learner role in another TiKV cannot be promoted to voter.  
The error is "[2023/02/14 07:13:08.485 +08:00] [WARN] [raft.rs:1553] ["cannot campaign at term 25 since there are still 2 pending configuration changes to apply"] [pending_changes=2] [term=25] [raft_id=39709568] [peer_id=39709568] [region_id=1834]
"
[region_1834_tikv.log](https://github.com/tikv/tikv/files/10727086/region_1834_tikv.log)
Screen Shot 2023-02-13 at 12 11 46 PM

### PR DESCRIPTION
**Pull request by BusyJay**
### What is changed and how it works?
Issue Number: Close #14215

What's Changed:

```commit-message
If a peer is marked for destroy, it will skip all apply result, which
will make it never apply to committed index. This PR relaxes the check
to last_applying_index and always process apply result.

It also fixes a bug that new peer created by large ID may not survive
restart.
```

### Check List 

Tests 

- Unit test
- Integration test

### Release note 

```release-note
None
```

### CODE REVIEW

File: components/raftstore-v2/src/operation/life.rs [hunk 1]
```diff
@@ -570,12 +570,13 @@ impl<EK: KvEngine, ER: RaftEngine> Peer<EK, ER> {
     /// tablet.
     #[inline]
     pub fn postponed_destroy(&self) -> bool {
+        let last_applying_index = self.compact_log_context().last_applying_index();
         let entry_storage = self.storage().entry_storage();
         // If it's marked as tombstone, then it must be changed by conf change. In
         // this case, all following entries are skipped so applied_index never equals
         // to commit_index.
```
Comment (tonyxuqqi) [inline components/raftstore-v2/src/operation/life.rs:577]: The comment should be changed to match the change.

Also could you elaborate the difference of entry_storage.commit_index() and last_applying_index?
So the compact_log_context's last_applying_index comes from committed_entries. So it's kind of observed commit index, which should be <= entry_storage.commit_index().
But I still don't get why this change is needed.

File: components/raftstore-v2/src/operation/life.rs [hunk 2]
```diff
@@ -570,12 +570,13 @@ impl<EK: KvEngine, ER: RaftEngine> Peer<EK, ER> {
...
         (self.storage().region_state().get_state() != PeerState::Tombstone
-           && entry_storage.applied_index() != entry_storage.commit_index())
+            && entry_storage.applied_index() != last_applying_index)
```
Comment (tonyxuqqi) [inline components/raftstore-v2/src/operation/life.rs:579]: The comment should be changed to match the change.

Also could you elaborate the difference of entry_storage.commit_index() and last_applying_index?
So the compact_log_context's last_applying_index comes from committed_entries. So it's kind of observed commit index, which should be <= entry_storage.commit_index().
But I still don't get why this change is needed.

File: components/raftstore-v2/src/operation/command/mod.rs [hunk 3]
```diff
@@ -320,11 +320,10 @@ impl<EK: KvEngine, ER: RaftEngine> Peer<EK, ER> {
     }
 
     pub fn on_apply_res<T>(&mut self, ctx: &mut StoreContext<EK, ER, T>, apply_res: ApplyRes) {
-        if !self.serving() {
-            return;
+        if !self.serving() || !apply_res.admin_result.is_empty() {
+            // TODO: remove following log once stable.
+            info!(self.logger, "on_apply_res"; "apply_res" => ?apply_res, "apply_trace" => ?self.storage().apply_trace());
```
Comment (tonyxuqqi) [inline components/raftstore-v2/src/operation/command/mod.rs:325]: Maybe the log information can be tuned to better reflect what it means.

File: components/raftstore-v2/src/operation/command/mod.rs [hunk 4]
```diff
@@ -320,11 +320,10 @@ impl<EK: KvEngine, ER: RaftEngine> Peer<EK, ER> {
     }
 
     pub fn on_apply_res<T>(&mut self, ctx: &mut StoreContext<EK, ER, T>, apply_res: ApplyRes) {
-        if !self.serving() {
-            return;
+        if !self.serving() || !apply_res.admin_result.is_empty() {
```
Comment (tonyxuqqi) [inline components/raftstore-v2/src/operation/command/mod.rs:323]: So what if it's self.serving() && apply_res.admin_result.is_empty(). Should it return immediately?

File: components/raftstore-v2/src/operation/ready/mod.rs [hunk 5]
```diff
@@ -939,6 +940,18 @@ impl<EK: KvEngine, ER: RaftEngine> Storage<EK, ER> {
         }
         // If snapshot initializes the peer, we don't need to write apply trace again.
         if !self.ever_persisted() {
+            let region_id = self.region().get_id();
```
Comment (tonyxuqqi) [inline components/raftstore-v2/src/operation/ready/mod.rs:943]: Could you please add the comment here why it's needed?

File: components/raftstore-v2/src/operation/life.rs (hunk 2 above)
Comment (BusyJay) [reply components/raftstore-v2/src/operation/life.rs:579]: Because last_applying_index is the largest index of entries sent to apply thread, so applied_index always <= last_applying_index. And applied_index may never equals commit_index.

File: components/raftstore-v2/src/operation/command/mod.rs (hunk 3 above)
Comment (BusyJay) [reply components/raftstore-v2/src/operation/command/mod.rs:325]: The log is a debug log to show the API is called.

File: components/raftstore-v2/src/operation/command/mod.rs (hunk 4 above)
Comment (BusyJay) [reply components/raftstore-v2/src/operation/command/mod.rs:323]: No, it should keep processing. I returned early in the past to reduce processing, but now it seems keep processing can get more benefits.

**Review by tabokie — APPROVED** [review]

File: components/raftstore-v2/src/operation/command/mod.rs (hunk 3 above)
Comment (tonyxuqqi) [reply components/raftstore-v2/src/operation/command/mod.rs:325]: > The log is a debug log to show the API is called.

But now it's not printed each time on_apply_res is called. It will only print when  !self.serving() || !apply_res.admin_result.is_empty(). But the log content seems that it printed whenever on_apply_res is called.

**Review by tonyxuqqi — APPROVED** [review]

File: components/raftstore-v2/src/operation/command/mod.rs (hunk 3 above)
Comment (BusyJay) [reply components/raftstore-v2/src/operation/command/mod.rs:325]: The condition is just to reduce frequency. What's your suggestion?
