### PR TITLE
raftstore: offloading I/O Operations from pd_worker to bg_worker.

### LINKED ISSUE #17679: Slow score fails to update during IO hang
### What version of TiKV are you using?

v8.4.0

### What operating system and CPU are you using?

8c/32g

### Steps to reproduce

1、run tpcc with 64 threads
2、inject one of tikv io hang

### What did you expect?
The slow score of IO-hanging TiKV node rapidly increase to 100.

### What did happened?
The slow score is low, while the pending tasks on pd_worker rapidly increase.

img_v3_02fn_1c270cbd-e8a3-4796-b006-42f9ddecb29g
img_v3_02fn_6fe5eb07-3b4e-4f91-97c9-3d29ae87b66g
img_v3_02fn_087d2fcb-8691-4565-9aa4-cf17076def9g
img_v3_02fn_bb1b565e-1505-4782-a983-ee9e072139eg

### PR DESCRIPTION
**Pull request by LykxSassinator**
### What is changed and how it works?

Issue Number: Close https://github.com/tikv/tikv/issues/17939, close #17679

What's Changed:

This PR is used to shift I/O operations from the `pd_worker` to mitigate the risk of it becoming blocked on I/O tasks.
This change is necessary to prevent scenarios where TiKV is unable to send commands or receive responses from PD due to `pd_worker` being stuck on I/O operations.

Meanwhile, previously, `collect_engine_size` didn't account for `placeholder_size` and `separated_raft_mount_path` in the used_size calculation. This PR fixes that by consolidating similar logic into `DiskUsageChecker::inspect`.

```commit-message
This PR is used to shift I/O operations from the `pd_worker` to mitigate the risk of it becoming blocked on I/O tasks.
```

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [ ] Need to cherry-pick to the release branch

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note

```release-note
This PR is used to shift I/O operations from the `pd_worker` to mitigate the risk of it becoming blocked on I/O tasks.
```

### CODE REVIEW

File: components/raftstore/src/store/worker/pd.rs [hunk 1]
```diff
@@ -2497,51 +2468,16 @@ fn collect_report_read_peer_stats(
...
-    let kv_size = store_info
-        .kv_engine
-        .get_engine_used_size()
-        .expect("kv engine used size");
-
-    STORE_SIZE_EVENT_INT_VEC.raft_size.set(raft_size as i64);
-    STORE_SIZE_EVENT_INT_VEC.snap_size.set(snap_mgr_size as i64);
-    STORE_SIZE_EVENT_INT_VEC.kv_size.set(kv_size as i64);
-
-    let used_size = snap_mgr_size + kv_size + raft_size;
```
Comment (hbisheng) [inline components/raftstore/src/store/worker/pd.rs:2539]: Previously, `collect_engine_size` didn't account for `placeholder_size` and `separated_raft_mount_path` in the `used_size` calculation. This PR fixes that by consolidating similar logic into `DiskUsageChecker::inspect`, which is a good improvement.

**Review by hbisheng — COMMENTED** [review]
overall LGTM

File: components/raftstore-v2/tests/integrations/cluster.rs [hunk 2]
```diff
@@ -339,6 +340,28 @@ impl RunningState {
...
+                let snap_size = snap_mgr.total_snap_size().unwrap();
+                let mut kv_size = 0;
+                tablet_registry.for_each_opened_tablet(|_, cached| {
+                    if let Some(tablet) = cached.latest() {
+                        kv_size += tablet.get_engine_used_size().unwrap_or(0);
+                    }
+                    true
+                });
+                let used_size = snap_size + kv_size;
+                let (capacity, available) = disk::get_disk_space_stats(&data_dir).unwrap();
```
Comment (hhwyt) [inline components/raftstore-v2/tests/integrations/cluster.rs:358]: Do we need add error handling to disk::get_disk_space_stats instead of using unwrap to prevent TiKV from panicking?

**Comment by hhwyt** [comment]
rest LGTM.

File: components/raftstore-v2/tests/integrations/cluster.rs (hunk 2 above)
Comment (LykxSassinator) [reply components/raftstore-v2/tests/integrations/cluster.rs:358]: Since this code is intended for testing purposes and not for formal use, it's not necessary to supply the check.

Comment (hhwyt) [reply components/raftstore-v2/tests/integrations/cluster.rs:358]: Get. It's "v2" :)

**Comment by hhwyt** [comment]
LGTM

File: components/raftstore-v2/tests/integrations/cluster.rs [hunk 3]
```diff
@@ -339,6 +340,28 @@ impl RunningState {
 
         let background = Worker::new("background");
         let pd_worker = LazyWorker::new("pd-worker");
+        // Spawn a task to update the disk status periodically.
+        {
+            let tablet_registry = registry.clone();
+            let data_dir = PathBuf::from(tablet_registry.tablet_root());
+            let snap_mgr = snap_mgr.clone();
+            background.spawn_interval_task(std::time::Duration::from_millis(100), move || {
```
Comment (glorv) [inline components/raftstore-v2/tests/integrations/cluster.rs:348]: Does it need to be this offen? I think maybe 10s interval is enough

**Review by hbisheng — APPROVED** [review]
Would it be possible to avoid changing v2-related code? The PR will be much smaller that way.

**Review by Connor1996 — APPROVED** [review]
LGTM

**Comment by glorv** [comment]
@LykxSassinator Seems the changes break some test cases.
