### PR TITLE
raftstore-v2: fix MergedRecords not being cleaned up

### LINKED ISSUE #15644: [Dynamic Regions] `merged_records` will never be cleaned up
## Bug Report

After commit merge, the merged_records of target merge will never be cleaned up,
because followers never report GcPeerResponse if they finish commit merge
normally.
TiKV must reports GcPeerResponse for merged source peers in `on_gc_peer_request`.
https://github.com/tikv/tikv/blob/ec4a9002f153f86c609e902ba685eee7a1224e6c/components/raftstore-v2/src/operation/life.rs#L647-L665

This issue may bloat `RegionLocalState`.

### What version of TiKV are you using?

v7.3.0

### Steps to reproduce

Merge two regions.

### What did you expect?

merged_records are cleaned up eventually.

### What did happened?

As title.

### PR DESCRIPTION
**Pull request by overvenus**
### What is changed and how it works?

Issue Number: Close #15644

What's Changed:

```commit-message
MergedRecords were not being properly cleaned up, causing unnecessary
bloating of RegionLocalState and continuous sending of GcPeerRequest by
raftstore.
This commit addresses the issue by enhancing the handling of
GcPeerRequests, ensuring that target region followers forward
GcPeerRequests to the source peer. The source peer or store then reports
GcPeerResponse accordingly.
```

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Integration test

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by tonyxuqqi — APPROVED** [review]

File: tests/integrations/raftstore/test_merge.rs [hunk 1]
```diff
@@ -1792,23 +1792,150 @@ fn test_gc_peer_after_merge() {
...
+    assert!(
+        !region_state.get_removed_records().is_empty(),
+        "{:?}",
+        region_state
+    );
+
+    // So cluster becomes
+    //  left region: merged
+    // right region: 1(leader) 2 | 3 (destroyed but not yet cleaned in removed
+    // records) | means isolation.
```
Comment (SpadeA-Tang) [inline tests/integrations/raftstore/test_merge.rs:1932]:
```suggestion
    // records)
    // | means isolation.
```

**Review by SpadeA-Tang — APPROVED** [review]

File: tests/integrations/raftstore/test_merge.rs (hunk 1 above)
Comment (overvenus) [reply tests/integrations/raftstore/test_merge.rs]: Thanks!
