### PR TITLE
*: Reduce frequency of store size reporting

### LINKED ISSUE #18955: Overly frequent storage stats reporting causing high tail latency when dataset is large
## Bug Report
TiKV reports store size every 1 second, since it requires reading SST properties with RocksDB DB-wide mutex held, serving tail latency got impacted significantly when single-instance dataset is huge.

### What did you expect?
Background activities have limited impact on online traffic.

### What did happened?
Tail latency increase, QPS drop

### PR DESCRIPTION
**Pull request by v01dstar**
### What is changed and how it works?

Issue Number: Close #18955

What's Changed:

```commit-message
Reduce frequency of store size reporting
```

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [ ] Need to cherry-pick to the release branch

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [x] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note

```release-note
None
```

### CODE REVIEW

File: components/server/src/server.rs [hunk 1]
```diff
@@ -242,7 +242,7 @@ pub fn run_tikv(
 
 const DEFAULT_METRICS_FLUSH_INTERVAL: Duration = Duration::from_millis(10_000);
 const DEFAULT_MEMTRACE_FLUSH_INTERVAL: Duration = Duration::from_millis(1_000);
-const DEFAULT_STORAGE_STATS_INTERVAL: Duration = Duration::from_secs(1);
+const DEFAULT_STORAGE_STATS_INTERVAL: Duration = Duration::from_secs(60);
```
Comment (Connor1996) [inline components/server/src/server.rs:247]: Please add a comment here

**Review by Connor1996 — APPROVED** [review]
LGTM

**Review by overvenus — APPROVED** [review]
