### PR TITLE
cop: Fixed issue #6690 Coprocessor Cache is unsound

### LINKED ISSUE #6690: Coprocessor Cache is unsound
## Bug Report

The Coprocessor cache works as follows, similar to HTTP cache:

1. TiDB sends a request to TiKV
2. TiKV returns the response, with current apply index.
3. TiDB caches the request, response, apply index.
4. Next time, before TiDB sending the same request, TiDB checks whether this request is cached.
  - If request exists in TiDB local cache, TiDB sends request to TiKV, carry with last apply_index.
  - If request not exists in TiDB local cache, TiDB sends request normally.
5. If TiKV receives a request with apply_index, TiKV checks whether latest apply_index matches the provided apply_index.
  - If apply_index is unchanged, it means the response in TiDB is valid, so TiKV returns empty response (with cache hit = true flag)
  - If apply_index is changed, TiKV returns normal response with current apply index.
6. If TiDB receives a response, with cache hit = true flag, TiDB fills the response from the local cache.

The "same request" concept is determined by the request payload without Timestamp, which means, sending request with different Timestamp but identical process payload is the same request. This is to make sure that in most cases the cache can work (since we almost never provide the same timestamp).

This process has a bug. If we send request use a old TS, cached response **may** not be safely used for a new TS. If old TS cannot scan **latest** data, then the response must not be cached.

The proposed change is as follows:

1. Add a field to Coprocessor response, indicating whether this response can be safely cached by TiDB.
2. When scanning data in MVCC, currently we skip (seek) directly to `${key}{start_ts}`. We can change to skip to `${key}{max_ts}`. If scanned key ts > start_ts, it means we found data newer than TS, so that this response must not be cached.
3. When we received locks, we also need to check the lock ts.

### PR DESCRIPTION
**Pull request by innerr**
###  What have you changed?
- This PR is trying to fix #6690, the issue is comprehensive, so I skipped the details here.
- Get enabled-cache-flag from rpc-request, past it through `DagHandlerBuilder`->`TiKVStorage`->`SnapshotStore`+`Scanner`, implement `can_be_cached()` in these modules and `Executor`, then put the can-be-cached flag into response (with updated kvproto)
- Add method `can_be_cached()` to trait `Executor`, and let all executors pass this flag from bottom Executor to the top one (this looks not good, I discussed it with WenXuan and got no improvement solution)
 - Modify the implement of PointGetter and BackwardScanner and ForwardScanner, to provide can_be_cached() feature, it cost a extra `seek` on `write cf` in some situation, `near_seek` is used when it is possible to make it not slower too much than before.

###  What is the type of the changes?

- Bugfix (a change which fixes an issue)

###  How is the PR tested?

- Unit test
- Integration test

###  Does this PR affect documentation (docs) or should it be mentioned in the release notes?

  - No

###  Does this PR affect `tidb-ansible`?

  - No

###  Refer to a related PR or issue link (optional)
  - Origin issue #6690
  - Related PRs should be merged in the same time:
      - TiDB: https://github.com/pingcap/tidb/pull/15499 
      - kvproto: https://github.com/pingcap/kvproto/pull/580

###  Benchmark result if necessary (optional)
  - TODO: should be tested to prove no regression

### CODE REVIEW

File: src/coprocessor/dag/mod.rs [hunk 1]
```diff
@@ -178,6 +188,7 @@ fn handle_qe_response(
         Ok(sel_resp) => {
             let mut resp = Response::default();
             resp.set_data(box_try!(sel_resp.write_to_bytes()));
+            resp.set_can_be_cached(can_be_cached);
```
Comment (sticnarf) [inline src/coprocessor/dag/mod.rs]: Currently this field does not exist in `Response`. Is there a proto update?

Comment (innerr) [reply src/coprocessor/dag/mod.rs]: Yes, the proto change is in https://github.com/innerr/kvproto/tree/issue-6690, just added this field and no other changes.

File: src/storage/mvcc/reader/point_getter.rs [hunk 2]
```diff
@@ -213,10 +218,14 @@ impl<S: Snapshot> PointGetter<S> {
                     }
                     match write.short_value {
                         Some(value) => {
+                            let current_key = self.write_cursor.key(&mut self.statistics.write);
```
Comment (innerr) [inline src/storage/mvcc/reader/point_getter.rs]: Here it cost a extra read, I am not sure if I sure pass down a flag `check_can_be_cached` so when the flag is false that I could avoid the extra read.

File: src/storage/mvcc/reader/point_getter.rs [hunk 3]
```diff
@@ -186,7 +191,7 @@ impl<S: Snapshot> PointGetter<S> {
     ///
     /// First, a correct version info in the Write CF will be sought. Then, value will be loaded
     /// from Default CF if necessary.
-    fn load_data(&mut self, user_key: &Key) -> Result<Option<Value>> {
+    fn load_data(&mut self, user_key: &Key, can_be_cached: &mut bool) -> Result<Option<Value>> {
         if !self.write_cursor.seek(
             &user_key.clone().append_ts(self.ts),
```
Comment (sticnarf) [inline src/storage/mvcc/reader/point_getter.rs]: Here we directly seek to `self.ts`, then it's impossible to see the higher versions.

Comment (innerr) [reply src/storage/mvcc/reader/point_getter.rs]: Fixed.
My rust code is horrible, thanks a lot for helping

File: src/storage/mvcc/reader/point_getter.rs [hunk 4]
```diff
@@ -151,14 +155,24 @@ impl<S: Snapshot> PointGetter<S> {
             }
         }
 
+        let mut can_be_cached_by_lock = true;
```
Comment (innerr) [inline src/storage/mvcc/reader/point_getter.rs]: It's ugly, need help...

Comment (sticnarf) [reply src/storage/mvcc/reader/point_getter.rs]: Here it's also not performant... If we want to check cacheability, we seek twice...

File: src/storage/txn/store.rs [hunk 5]
```diff
@@ -425,7 +444,14 @@ impl Store for FixtureStore {
     }
 
     #[inline]
```
[the remark this answers is not in the document]
Comment (innerr) [reply src/storage/txn/store.rs]: It doesn't contain Mvcc info, so I think yes

File: src/storage/txn/store.rs [hunk 6]
```diff
@@ -190,6 +197,8 @@ pub struct SnapshotStore<S: Snapshot> {
     bypass_locks: TsSet,
 
     point_getter_cache: Option<PointGetter<S>>,
+
+    check_can_be_cached: bool,
```
[the remark this answers is not in the document]
Comment (innerr) [reply src/storage/txn/store.rs]: Addressed, at first I want this flag to affect both `get` and `scan`

File: src/storage/mvcc/reader/point_getter.rs (hunk 4 above)
Comment (innerr) [reply src/storage/mvcc/reader/point_getter.rs]: We have to seek twice, I think.
near_seek might help a little.

File: components/tidb_query/src/batch/executors/util/mock_executor.rs [hunk 7]
```diff
@@ -47,4 +47,8 @@ impl BatchExecutor for MockExecutor {
         // Do nothing
         unreachable!()
     }
+
+    fn can_be_cached(&mut self) -> bool {
+        return false;
```
[the remark this answers is not in the document]
Comment (innerr) [reply components/tidb_query/src/batch/executors/util/mock_executor.rs]: Addressed

**Comment by innerr** [comment]
@sticnarf @breeswish PTAL

File: src/storage/mvcc/reader/point_getter.rs [hunk 8]
```diff
@@ -151,15 +155,27 @@ impl<S: Snapshot> PointGetter<S> {
...
         match self.isolation_level {
             IsolationLevel::Si => {
                 // Check for locks that signal concurrent writes in Si.
-                self.load_and_check_lock(user_key)?;
+                self.load_and_check_lock(user_key, Some(&mut can_be_cached_by_lock))?;
```
Comment (breeswish) [inline src/storage/mvcc/reader/point_getter.rs:162]: If there is a lock, it will return early because of `?` operator. Then if the lock cannot be cached (after ts), `can_be_cached` loses update.

File: src/storage/mvcc/reader/point_getter.rs [hunk 9]
```diff
@@ -151,15 +155,27 @@ impl<S: Snapshot> PointGetter<S> {
...
             }
             IsolationLevel::Rc => {}
         }
 
-        self.load_data(user_key)
+        let mut use_near_seek = false;
+        if let Some(can_be_cached) = can_be_cached {
```
Comment (breeswish) [inline src/storage/mvcc/reader/point_getter.rs:168]: Maybe we can use `if let Some(true) = can_be_cached {`?

Comment (breeswish) [reply src/storage/mvcc/reader/point_getter.rs:168]: If we know that there is a lock after ts, maybe no need to pre-seek anymore?

File: src/storage/mvcc/reader/scanner/backward.rs [hunk 10]
```diff
@@ -227,15 +240,39 @@ impl<S: Snapshot> BackwardKvScanner<S> {
         }
         assert!(ts > last_checked_commit_ts);
```
Comment (breeswish) [inline src/storage/mvcc/reader/scanner/backward.rs:241]: What if the data looks like:

```
k1v13, k1v12, k1v11, k1v10
```

And we seek for ts=12, REVERSE_SEEK_BOUND = 3.

1. i=0, `k1v13, k1v12, k1v11, [k1v10]` (`[]` denotes the key that cursor is pointing to)
2. i=1, `k1v13, k1v12, [k1v11], k1v10`
3. i=2, `k1v13, [k1v12], k1v11, k1v10`
4. i=3, break loop.

Now we hit L230 and the function is returned without discovering `k1v13`.

File: src/storage/mvcc/reader/scanner/backward.rs [hunk 11]
```diff
@@ -227,15 +240,39 @@ impl<S: Snapshot> BackwardKvScanner<S> {
...
+                user_key.as_encoded().as_slice()
+            ));
+            let max_ts = Key::decode_ts_from(current_key)?;
+            if max_ts > ts {
+                self.can_be_cached = false
+            }
+        }
+
         // After several `prev()`, we still not get the latest version for the specified ts,
         // use seek to locate the latest version.
```
Comment (breeswish) [inline src/storage/mvcc/reader/scanner/backward.rs:263]: maybe we should put these comments before L243.

File: src/storage/mvcc/reader/scanner/forward.rs [hunk 12]
```diff
@@ -239,6 +246,13 @@ impl<S: Snapshot, P: ScanPolicy<S>> ForwardScanner<S, P> {
             };
 
             if has_lock {
+                if self.cfg.check_can_be_cached && self.can_be_cached {
+                    let lock_value = self.cursors.lock.value(&mut self.statistics.lock);
+                    let lock = Lock::parse(lock_value)?;
```
Comment (breeswish) [inline src/storage/mvcc/reader/scanner/forward.rs:251]: Lock is parsed twice.. @sticnarf Do you have ideas to reduce the extra parsing?

File: src/storage/mvcc/reader/scanner/forward.rs [hunk 13]
```diff
@@ -296,15 +310,23 @@ impl<S: Snapshot, P: ScanPolicy<S>> ForwardScanner<S, P> {
...
         // If we have not found `${user_key}_${ts}` in a few `next()`, directly `seek()`.
         if needs_seek {
             // `user_key` must have reserved space here, so its clone has reserved space too. So no
             // reallocation happens in `append_ts`.
+            let seek_ts = if self.cfg.check_can_be_cached && self.can_be_cached {
+                // TODO: use "write.seek(ts) + write.prev()" to check newer data maybe faster?
+                TimeStamp::max()
+            } else {
+                self.cfg.ts
+            };
```
Comment (breeswish) [inline src/storage/mvcc/reader/scanner/forward.rs:327]: I guess (not sure) we even don't need to check it here. If we hit `needs_seek`, it means that we must have found some `ts > specified ts`, otherwise the seek bound will not exceed.

File: src/storage/mvcc/reader/point_getter.rs (hunk 8 above)
Comment (innerr) [reply src/storage/mvcc/reader/point_getter.rs]: Addressed

File: components/tidb_query/src/executor/runner.rs [hunk 14]
```diff
@@ -318,4 +318,8 @@ impl<SS: 'static> ExecutorsRunner<SS> {
         // return SelectResponse in `handle_request`.
         self.executor.collect_storage_stats(dest);
     }
+
+    pub fn can_be_cached(&mut self) -> bool {
```
[the remark this answers is not in the document]
Comment (innerr) [reply components/tidb_query/src/executor/runner.rs:324]: Addressed

File: src/storage/mvcc/reader/point_getter.rs (hunk 9 above)
Comment (innerr) [reply src/storage/mvcc/reader/point_getter.rs]: Addressed

File: src/storage/mvcc/reader/scanner/backward.rs (hunk 11 above)
Comment (innerr) [reply src/storage/mvcc/reader/scanner/backward.rs]: Addressed

File: src/storage/mvcc/reader/scanner/forward.rs (hunk 13 above)
Comment (innerr) [reply src/storage/mvcc/reader/scanner/forward.rs:327]: Good cache! the seeking for check_can_be_cached will not executed on this code

Comment (innerr) [reply src/storage/mvcc/reader/scanner/forward.rs]: Addressed, remove the seeking code

File: src/storage/mvcc/reader/scanner/backward.rs (hunk 10 above)
Comment (innerr) [reply src/storage/mvcc/reader/scanner/backward.rs]: Good cache, it's a corner case.

Comment (innerr) [reply src/storage/mvcc/reader/scanner/backward.rs:248]: Addressed

File: src/storage/mvcc/reader/point_getter.rs [hunk 15]
```diff
@@ -151,15 +155,35 @@ impl<S: Snapshot> PointGetter<S> {
...
+        let mut can_be_cached_by_lock = true;
         match self.isolation_level {
             IsolationLevel::Si => {
                 // Check for locks that signal concurrent writes in Si.
-                self.load_and_check_lock(user_key)?;
+                let check_lock_res =
+                    self.load_and_check_lock(user_key, Some(&mut can_be_cached_by_lock));
+                if let Err(e) = check_lock_res {
+                    *can_be_cached.unwrap() = can_be_cached_by_lock;
+                    return Err(e);
```
Comment (sticnarf) [inline src/storage/mvcc/reader/point_getter.rs:166]: Only a conflict lock error can be cached. Other errors like getting snapshot error shouldn't be cached.

File: src/storage/mvcc/reader/point_getter.rs [hunk 16]
```diff
@@ -151,15 +155,35 @@ impl<S: Snapshot> PointGetter<S> {
...
-        self.load_data(user_key)
+        let mut use_near_seek = false;
+        if can_be_cached_by_lock {
+            if let Some(true) = can_be_cached {
+                self.write_cursor.seek(
+                    &user_key.clone().append_ts(TimeStamp::max()),
+                    &mut self.statistics.write,
+                )?;
+                let current_key = self.write_cursor.key(&mut self.statistics.write);
+                *can_be_cached.unwrap() =
```
Comment (sticnarf) [inline src/storage/mvcc/reader/point_getter.rs:180]: I think we should compare `current_key` with `user_key` first. If they are different, we don't continue.

File: src/storage/mvcc/reader/scanner/forward.rs (hunk 12 above)
Comment (sticnarf) [reply src/storage/mvcc/reader/scanner/forward.rs:252]: I don't have a good idea... But instead of pass `lock_value` in, I prefer to pass `can_be_cached` in...

File: src/storage/mvcc/reader/point_getter.rs [hunk 17]
```diff
@@ -151,15 +155,35 @@ impl<S: Snapshot> PointGetter<S> {
             }
         }
 
+        let mut can_be_cached_by_lock = true;
         match self.isolation_level {
             IsolationLevel::Si => {
                 // Check for locks that signal concurrent writes in Si.
-                self.load_and_check_lock(user_key)?;
+                let check_lock_res =
+                    self.load_and_check_lock(user_key, Some(&mut can_be_cached_by_lock));
```
Comment (breeswish) [inline src/storage/mvcc/reader/point_getter.rs:163]: Maybe better to use:

```rust
let check_lock_res = self.load_and_check_lock(
    user_key, 
    can_be_cached.as_ref().map(|_| &mut can_be_cached_by_lock)
);
```

so that `load_and_check_lock()` receives `load_and_check_lock(.., None)` when `get()` receives `get(..., None)`.

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=ce34cc3b4925da7e012560445b7bb858

File: src/storage/mvcc/reader/point_getter.rs [hunk 18]
```diff
@@ -151,15 +155,35 @@ impl<S: Snapshot> PointGetter<S> {
...
+                if let Err(e) = check_lock_res {
+                    *can_be_cached.unwrap() = can_be_cached_by_lock;
```
Comment (breeswish) [inline src/storage/mvcc/reader/point_getter.rs:165]: `can_be_cached` can be `None`. Maybe:

```rust
if !can_be_cached_by_lock {
    *can_be_checked.unwrap() = false;   // the unwrap here is fine, since `can_be_cached_by_lock` can only be changed when `can_be_cached` is Some due to my previous comment
}
check_lock_res?;
```

File: src/storage/mvcc/reader/point_getter.rs [hunk 19]
```diff
@@ -151,15 +155,35 @@ impl<S: Snapshot> PointGetter<S> {
...
+                    return Err(e);
+                }
             }
             IsolationLevel::Rc => {}
         }
 
-        self.load_data(user_key)
+        let mut use_near_seek = false;
+        if can_be_cached_by_lock {
```
Comment (breeswish) [inline src/storage/mvcc/reader/point_getter.rs:173]: if my comment over L165 is applied then this line can be removed (since `can_be_cached_by_lock` are always synced to `can_be_cached`, we only need to check `can_be_cached`).

File: src/storage/mvcc/reader/point_getter.rs [hunk 20]
```diff
@@ -151,15 +155,35 @@ impl<S: Snapshot> PointGetter<S> {
...
+                if let Err(e) = check_lock_res {
+                    *can_be_cached.unwrap() = can_be_cached_by_lock;
+                    return Err(e);
+                }
             }
             IsolationLevel::Rc => {}
         }
 
-        self.load_data(user_key)
+        let mut use_near_seek = false;
```
Comment (breeswish) [inline src/storage/mvcc/reader/point_getter.rs:172]: prefer to move logic in `load_data()`

File: src/storage/mvcc/reader/point_getter.rs (hunk 16 above)
Comment (breeswish) [reply src/storage/mvcc/reader/point_getter.rs:180]: +1

File: src/storage/mvcc/reader/scanner/backward.rs [hunk 21]
```diff
@@ -223,19 +236,52 @@ impl<S: Snapshot> BackwardKvScanner<S> {
         // At this time, we must have current commit_ts <= ts. If commit_ts == ts,
         // we don't need to seek any more and we can just utilize `last_version`.
         if last_checked_commit_ts == ts {
+            self.write_cursor.prev(&mut self.statistics.write);
+            if let Ok(true) = self.write_cursor.valid() {
+                let current_key = self.write_cursor.key(&mut self.statistics.write);
+                self.can_be_cached =
+                    !Key::is_user_key_eq(current_key, user_key.as_encoded().as_slice());
+            }
+            self.write_cursor.next(&mut self.statistics.write);
```
Comment (breeswish) [inline src/storage/mvcc/reader/scanner/backward.rs:245]: maybe need to put behind `if self.cfg.check_can_be_cached && self.can_be_cached { .. }`

Comment (breeswish) [inline src/storage/mvcc/reader/scanner/backward.rs:245]: there is no need to move cursor back in L245, since `handle_last_version` will not consider current write cursor any more.

File: src/storage/mvcc/reader/scanner/backward.rs [hunk 22]
```diff
@@ -223,19 +236,52 @@ impl<S: Snapshot> BackwardKvScanner<S> {
         // At this time, we must have current commit_ts <= ts. If commit_ts == ts,
         // we don't need to seek any more and we can just utilize `last_version`.
         if last_checked_commit_ts == ts {
+            self.write_cursor.prev(&mut self.statistics.write);
+            if let Ok(true) = self.write_cursor.valid() {
```
Comment (breeswish) [inline src/storage/mvcc/reader/scanner/backward.rs:240]: I think errors should be thrown to outside:

```rust
if self.write_cursor.valid()? {
```

File: src/storage/mvcc/reader/scanner/backward.rs [hunk 23]
```diff
@@ -223,19 +236,52 @@ impl<S: Snapshot> BackwardKvScanner<S> {
...
+                let current_key = self.write_cursor.key(&mut self.statistics.write);
+                self.can_be_cached =
+                    !Key::is_user_key_eq(current_key, user_key.as_encoded().as_slice());
```
Comment (breeswish) [inline src/storage/mvcc/reader/scanner/backward.rs:243]: maybe better to `if ... { self.can_be_cached = false }` in order to totally avoid the possibility that `can_be_cached` may be changed back to `true` when it is already `false`.

Comment (innerr) [reply src/storage/mvcc/reader/scanner/backward.rs]: Addressed

File: src/storage/mvcc/reader/scanner/backward.rs (hunk 22 above)
Comment (innerr) [reply src/storage/mvcc/reader/scanner/backward.rs]: Addressed

Comment (innerr) [reply src/storage/mvcc/reader/scanner/backward.rs]: When the prev write_cursor is not valid，I think we should not thrown because the current (not prev) data at write_cursor is good.
When the prev write_cursor is not valid，It means no newer data of this user-key, aka, cache_able

File: src/storage/mvcc/reader/scanner/backward.rs (hunk 21 above)
Comment (innerr) [reply src/storage/mvcc/reader/scanner/backward.rs]: Addressed

Comment (innerr) [reply src/storage/mvcc/reader/scanner/backward.rs]: Addressed

File: src/storage/mvcc/reader/point_getter.rs (hunk 15 above)
Comment (innerr) [reply src/storage/mvcc/reader/point_getter.rs:166]: Can be cached or not is decided by load_and_check_lock and return in can_be_cached_by_lock,
the code here is not deciding cache_able, just assigning can_be_cached before return.
(Ugly, though)

File: Cargo.toml [hunk 24]
```diff
@@ -90,7 +90,7 @@ openssl = "0.10"
 tokio-openssl = "0.2"
 hyper = { version = "0.12", default-features = false, features = ["runtime"] }
 keys = { path = "components/keys" }
-kvproto = { git = "https://github.com/pingcap/kvproto.git", default-features = false }
+kvproto = { git = "https://github.com/innerr/kvproto.git", default-features = false, branch = "issue-6690" }
```
Comment (youjiali1995) [inline Cargo.toml:93]: You can replace it with [patch](https://doc.rust-lang.org/edition-guide/rust-2018/cargo-and-crates-io/replacing-dependencies-with-patch.html#replacing-dependencies-with-patch) in the root `Cargo.toml` only.

File: src/storage/mvcc/reader/scanner/forward.rs [hunk 25]
```diff
@@ -239,6 +252,14 @@ impl<S: Snapshot, P: ScanPolicy<S>> ForwardScanner<S, P> {
             };
 
             if has_lock {
+                // TODO: here we parse lock_value twice, maybe we could pass `lock_value` to `handle_lock`?
```
Comment (youjiali1995) [inline src/storage/mvcc/reader/scanner/forward.rs:255]: Needn't parse it. It's uncacheable.

File: src/storage/mvcc/reader/scanner/mod.rs [hunk 26]
```diff
@@ -211,13 +233,14 @@ impl<S: Snapshot> ScannerConfig<S> {
...
             bypass_locks: Default::default(),
+            check_has_newer_ts_data: false,
         }
     }
 
     #[inline]
     fn scan_mode(&self) -> ScanMode {
         if self.desc {
-            ScanMode::Backward
+            ScanMode::Mixed
```
Comment (youjiali1995) [inline src/storage/mvcc/reader/scanner/mod.rs:243]: Why change it?

File: Cargo.toml (hunk 24 above)
Comment (innerr) [reply Cargo.toml:93]: Yes I did use patch locally at first. The purpose here is for pass CI.
We could check all things are OK, then merge related PR in kvproto, then reverse this dependency, then finally merge this PR

File: src/storage/mvcc/reader/scanner/mod.rs (hunk 26 above)
Comment (innerr) [reply src/storage/mvcc/reader/scanner/mod.rs:243]: The purpose here is to use near_seek later(we seek twice on one key, the first time is for checking can_be_cached, the second time is for getting the result, we want to use near_seek on the second time), If scan_mode is Backward, we can't call near_seek

File: src/storage/mvcc/reader/scanner/backward.rs [hunk 27]
```diff
@@ -223,19 +244,58 @@ impl<S: Snapshot> BackwardKvScanner<S> {
         // At this time, we must have current commit_ts <= ts. If commit_ts == ts,
         // we don't need to seek any more and we can just utilize `last_version`.
         if last_checked_commit_ts == ts {
```
[the remark this answers is not in the document]
Comment (breeswish) [reply src/storage/mvcc/reader/scanner/backward.rs:246]: When moving cursor backward, there could be a chance that ts of `pointing key == ts && REVERSE_SEEK_BOUND is hit`. Before this PR, it returns directly since a suitable ts is already found. In this PR however, before returning data, we need to move backward again to see if there are larger ts available to invalidate the cache.

File: src/storage/mvcc/reader/point_getter.rs [hunk 28]
```diff
@@ -175,6 +200,9 @@ impl<S: Snapshot> PointGetter<S> {
         if let Some(ref lock_value) = lock_value {
             self.statistics.lock.processed += 1;
             let lock = Lock::parse(lock_value)?;
+            if lock.ts > self.ts && self.met_newer_ts_data == NewerTsCheckState::NotMetYet {
```
[the remark this answers is not in the document]
Comment (innerr) [reply src/storage/mvcc/reader/point_getter.rs]: Addressed

File: src/storage/mvcc/reader/scanner/backward.rs [hunk 29]
```diff
@@ -136,6 +149,11 @@ impl<S: Snapshot> BackwardKvScanner<S> {
                             let lock_value = self.lock_cursor.value(&mut self.statistics.lock);
                             Lock::parse(lock_value)?
                         };
+                        if lock.ts > self.cfg.ts
```
[the remark this answers is not in the document]
Comment (innerr) [reply src/storage/mvcc/reader/scanner/backward.rs:152]: Addressed, but I am not sure handling it right when it's `IsolationLevel::Rc`

**Comment by innerr** [comment]
Waiting for VerKV solve the building problem

File: src/storage/mvcc/reader/scanner/backward.rs (hunk 29 above)
[the remark this answers is not in the document]
Comment (youjiali1995) [reply src/storage/mvcc/reader/scanner/backward.rs]: We don't care about `IsolationLevel::Rc` in TiKV.

File: src/storage/mvcc/reader/scanner/forward.rs (hunk 25 above)
Comment (innerr) [reply src/storage/mvcc/reader/scanner/forward.rs]: Addressed

**Comment by innerr** [comment]
I will do more benchmarks manually later
