### PR TITLE
raftstore: fix meta inconsistency issue

### LINKED ISSUE #13311: TiKV panicked due to corrupted meta
### What version of TiKV are you using?

master

### What operating system and CPU are you using?

kubernetes

### Steps to reproduce

run jepsen with the following options
```edn
{:auto-retry-limit :default,
 :ssh-private-key "jepsen.pem",
 :isolation :repeatable-read,
 :concurrency 15,
 :predicate-read false,
 :tarball-url
 "http://minio.pingcap.net:9000/tp-team/tests/jepsen/tidb-master-linux-amd64.tar.gz",
 :txn-mode "optimistic",
 :force-reinstall true,
 :update-in-place false,
 :ssh
 {:username "root",
  :password "root",
  :strict-host-key-checking false,
  :private-key-path "jepsen.pem"},
 :nemesis-long-recovery false,
 :follower-read true,
 :nemesis
 {:interval 10,
  :schedules true,
  :partition-pd-leader true,
  :partition-half true,
  :partition-ring true},
 :nodes
 ["node-0.node-peer.jepsen-tps-1170516-1-921"
  "node-1.node-peer.jepsen-tps-1170516-1-921"
  "node-2.node-peer.jepsen-tps-1170516-1-921"
  "node-3.node-peer.jepsen-tps-1170516-1-921"
  "node-4.node-peer.jepsen-tps-1170516-1-921"],
 :test-count 1,
 :read-lock nil,
 :use-index false,
 :table-cache false,
 :os #object[tidb.core.Image 0x604d28c6 "tidb.core.Image@604d28c6"],
 :time-limit 600,
 :recovery-time 10,
 :version "master",
 :auto-retry :default,
 :workload :bank-multitable,
 :init-txn-sql
 ("set @@tidb_enable_async_commit = 0, @@tidb_enable_1pc = 0"
  "set @@tidb_enable_async_commit = 1, @@tidb_enable_1pc = 0"
  "set @@tidb_enable_async_commit = 1, @@tidb_enable_1pc = 1"),
 :init-sql
 ("set @@tidb_enable_mutation_checker=1, @@tidb_txn_assertion_level=strict")}
```

### What did you expect?

The test passed.

### What did happened?

TiKV panicked. ([full logs](http://minio.pingcap.net:9000/test-infra/2022-08-15/plan-exec-1170516/plan-exec-1170516-359813707/archive.tgz))
```
[2022/08/15 19:53:49.673 +00:00] [FATAL] [lib.rs:494] ["meta corrupted: no region for 3312 7A6D44423A32000000FF00FB000000000000FF00685461626C653AFF3638FF0000000000FF000000F700000000FB when creating 3307 region_id: 3307 from_peer { id: 3309 store_id: 1 } to_peer { id: 3558 store_id: 6 role: Learner } message { msg_type: MsgHeartbeat to: 3558 from: 3309 term: 7 } region_epoch { conf_ver: 152 version: 196 } start_key: 6D44423A31000000FF00FB000000000000FF00685461626C653AFF3600FE0000000000FA end_key: 6D44423A31000000FF00FB000000000000FF00685461626C653AFF3634FF0000000000FF000000F700000000FB"] [backtrace="   0: tikv_util::set_panic_hook::{{closure}}\n             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/tikv_util/src/lib.rs:493:18\n   1: std::panicking::rust_panic_with_hook\n             at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:702:17\n   2: std::panicking::begin_panic_handler::{{closure}}\n             at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:588:13\n   3: std::sys_common::backtrace::__rust_end_short_backtrace\n             at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:138:18\n   4: rust_begin_unwind\n             at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:584:5\n   5: core::panicking::panic_fmt\n             at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panicking.rs:142:14\n   6: raftstore::store::fsm::store::StoreFsmDelegate<EK,ER,T>::maybe_create_peer_internal\n             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/fsm/store.rs:2081:25\n      raftstore::store::fsm::store::StoreFsmDelegate<EK,ER,T>::maybe_create_peer\n             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/fsm/store.rs:2006:19\n   7: raftstore::store::fsm::store::StoreFsmDelegate<EK,ER,T>::on_raft_message\n             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/fsm/store.rs:1936:20\n      raftstore::store::fsm::store::StoreFsmDelegate<EK,ER,T>::handle_msgs\n             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/fsm/store.rs:709:37\n   8: <raftstore::store::fsm::store::RaftPoller<EK,ER,T> as batch_system::batch::PollHandler<raftstore::store::fsm::peer::PeerFsm<EK,ER>,raftstore::store::fsm::store::StoreFsm<EK>>>::handle_control\n             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/fsm/store.rs:858:9\n      batch_system::batch::Poller<N,C,Handler>::poll\n             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/batch-system/src/batch.rs:419:27\n   9: raftstore::store::worker::refresh_config::PoolController<N,C,H>::increase_by::{{closure}}\n             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/worker/refresh_config.rs:78:21\n      <std::thread::Builder as tikv_util::sys::thread::StdThreadBuildWrapper>::spawn_wrapper::{{closure}}\n             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/tikv_util/src/sys/thread.rs:415:23\n      std::sys_common::backtrace::__rust_begin_short_backtrace\n             at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:122:18\n  10: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}\n             at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:505:17\n      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once\n             at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panic/unwind_safe.rs:271:9\n      std::panicking::try::do_call\n             at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:492:40\n      std::panicking::try\n             at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:456:19\n      std::panic::catch_unwind\n             at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:137:14\n      std::thread::Builder::spawn_unchecked_::{{closure}}\n             at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:504:30\n      core::ops::function::FnOnce::call_once{{vtable.shim}}\n             at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:248:5\n  11: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once\n             at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:1935:9\n      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once\n             at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:1935:9\n      std::sys::unix::thread::Thread::new::thread_start\n             at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys/unix/thread.rs:108:17\n  12: start_thread\n  13: clone\n"] [location=/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/fsm/store.rs:2081] [thread_name=raftstore-6-1]
   0: tikv_util::set_panic_hook::{{closure}}
             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/tikv_util/src/lib.rs:493:18
   1: std::panicking::rust_panic_with_hook
             at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:702:17
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:588:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:138:18
   4: rust_begin_unwind
             at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:584:5
   5: core::panicking::panic_fmt
             at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panicking.rs:142:14
   6: raftstore::store::fsm::store::StoreFsmDelegate<EK,ER,T>::maybe_create_peer_internal
             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/fsm/store.rs:2081:25
      raftstore::store::fsm::store::StoreFsmDelegate<EK,ER,T>::maybe_create_peer
             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/fsm/store.rs:2006:19
   7: raftstore::store::fsm::store::StoreFsmDelegate<EK,ER,T>::on_raft_message
             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/fsm/store.rs:1936:20
      raftstore::store::fsm::store::StoreFsmDelegate<EK,ER,T>::handle_msgs
             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/fsm/store.rs:709:37
   8: <raftstore::store::fsm::store::RaftPoller<EK,ER,T> as batch_system::batch::PollHandler<raftstore::store::fsm::peer::PeerFsm<EK,ER>,raftstore::store::fsm::store::StoreFsm<EK>>>::handle_control
             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/fsm/store.rs:858:9
      batch_system::batch::Poller<N,C,Handler>::poll
             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/batch-system/src/batch.rs:419:27
   9: raftstore::store::worker::refresh_config::PoolController<N,C,H>::increase_by::{{closure}}
             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/worker/refresh_config.rs:78:21
      <std::thread::Builder as tikv_util::sys::thread::StdThreadBuildWrapper>::spawn_wrapper::{{closure}}
             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/tikv_util/src/sys/thread.rs:415:23
      std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:122:18
  10: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
             at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:505:17
      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panic/unwind_safe.rs:271:9
      std::panicking::try::do_call
             at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:492:40
      std::panicking::try
             at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:456:19
      std::panic::catch_unwind
             at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:137:14
      std::thread::Builder::spawn_unchecked_::{{closure}}
             at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:504:30
      core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:248:5
  11: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:1935:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:1935:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys/unix/thread.rs:108:17
  12: start_thread
  13: clone
```

### PR DESCRIPTION
**Pull request by cfzjywxk**
### What is changed and how it works?

Issue Number: Close #13311 

What's Changed:
When a replicated uninitialized peer is destroyed when its related new region is also being created by region split at the same time, the region meta information could be inconsistent thus causing tikv panic.

Try to check the meta information when destroying an uninitialized peer, if it's initialized in the meta information delete related information to keep consistency.

```commit-message
Fix the possible meta inconsistency issue.
```

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

Side effects

### Release note 

```release-note
Fix the tikv panic caused by inconsistent region meta information.
```

### CODE REVIEW

File: components/raftstore/src/store/fsm/peer.rs [hunk 1]
```diff
@@ -3764,15 +3763,24 @@ where
...
+            } else if is_latest_initialized {
+                let latest_region_info = meta.regions.get(&region_id).unwrap();
+                Some(enc_end_key(latest_region_info))
+            } else {
+                None
+            };
+
+            if let Some(delete_key) = key {
+                if meta.region_ranges.remove(&delete_key).is_none() {
+                    panic!("{} meta corruption detected", self.fsm.peer.tag);
```
Comment (tonyxuqqi) [inline components/raftstore/src/store/fsm/peer.rs:3779]: Could panic happen when key is Some(enc_end_key(latest_region_info))?
If not, maybe this panic code can be moved to if is_peer_initialized block.

**Review by tonyxuqqi — APPROVED** [review]

File: components/raftstore/src/store/fsm/peer.rs (hunk 1 above)
Comment (cfzjywxk) [reply components/raftstore/src/store/fsm/peer.rs:3779]: I haven't seen this panic by now, it checks another kind of consistency between the `region_id` and `end_key`,  maybe it's okay to keep the check here.

File: components/raftstore/src/store/fsm/peer.rs [hunk 2]
```diff
@@ -3688,26 +3684,29 @@ where
...
+        (|| {
+            fail_point!(
+                "before_destroy_peer_on_peer_1003",
+                self.fsm.peer.peer_id() == 1003,
+                |_| {}
             );
-        }
+        })();
+        let mut meta = self.ctx.store_meta.lock().unwrap();
+        let is_latest_initialized = {
```
Comment (Connor1996) [inline components/raftstore/src/store/fsm/peer.rs:3695]: if it's already initialized now, seems we can't call `meta.readers.remove(&region_id)` and others as well, otherwise the new split region's item is removed

Comment (cfzjywxk) [reply components/raftstore/src/store/fsm/peer.rs:3695]: In the situation that `destroy_peer` is called by an uninitialized peer while it's already initialized in the region `meta`, I only find the case where the uninitialized peer is destroyed by a larger peer message during the splitting region happens in another thread by now. In this case, the newly inserted region or peer would be finally destroyed by the larger peer id message.

Skipping destroying the uninitialized peer seems to be an option too, maybe it's safer?

File: tests/failpoints/cases/test_split_region.rs [hunk 3]
```diff
@@ -42,6 +43,7 @@ use txn_types::{Key, LastChange, PessimisticLock, TimeStamp};
 
 #[test]
 fn test_meta_inconsistency() {
+    init_log_for_test();
```
[the remark this answers is not in the document]
Comment (cfzjywxk) [reply tests/failpoints/cases/test_split_region.rs]: Debug information is cleared, PTAL

**Review by Connor1996 — APPROVED** [review]
LGTM
