### PR TITLE
handle MVCC delete marks quickly

### LINKED ISSUE #8861: potential endless loop in compaction_filter
### What version of TiKV are you using?

master

### Steps to reproduce

none

### What did happened?
https://github.com/tikv/tikv/blob/cac226a6a00fcb54dc320894e5bab24e9edd6b0c/src/server/gc_worker/compaction_filter.rs#L167-L172

potential endless loop when `match Key::split_on_ts_for(key)` return error

### PR DESCRIPTION
**Pull request by hicqu**
### What problem does this PR solve?
Handles MVCC delete marsk quickly.
Close #8861 .

### What is changed and how it works?

Without this patch MVCC delete marks can only be handled at L6, which means GC can be too slow to reduce performance. This patch allows MVCC delete marks to be handled at all levels, to make GC faster.

We have tested it with workload `oltp_update_index`. The result shows that GC speed is faster, but compaction needs more resources.

### Check List 

Tests 
- Unit tests
- Performanace tests
企业微信截图_6397e688-421e-4f30-9f03-5d882823a2c6
企业微信截图_63807d83-3946-4aa1-9ca6-ee12c24e7285
企业微信截图_499030b7-e33f-4242-8eef-d8dcc32ce21a
企业微信截图_20750e3d-bbcc-4706-a1a6-9b0204d194b2
企业微信截图_2745e4e3-45f3-4426-a64d-940e29d6f182
企业微信截图_c430f135-0207-412a-84c6-6bf7984c5616

We can see
* with the patch gc speed is more smooth
* however compaction is slower with the patch

Side effects

### Release note 
* No release note

### CODE REVIEW

**Comment by Little-Wallace** [comment]
It seems that `near_seek` cost a log of CPU resource....

**Comment by hicqu** [comment]
@Little-Wallace replace `near_seek` with `seek` will utility more CPU resource.

File: src/server/gc_worker/compaction_filter.rs [hunk 1]
```diff
@@ -279,10 +297,8 @@ impl CompactionFilter for WriteCompactionFilter {
                 WriteType::Put => self.remove_older = true,
                 WriteType::Delete => {
                     self.remove_older = true;
-                    if self.bottommost_level {
-                        filtered = true;
-                        self.gc_before_delete_mark(key, key_prefix);
-                    }
+                    filtered = true;
+                    self.gc_before_delete_mark(key, key_prefix);
```
Comment (yiwu-arbug) [inline src/server/gc_worker/compaction_filter.rs:301]: not related to this PR, but here we trigger gc_before_delete_mark once we hit a deletion marker. Can we trigger it only when we pass the oldest version of the current key in the current compaction?

**Review by Little-Wallace — APPROVED** [review]
LGTM

File: src/server/gc_worker/compaction_filter.rs [hunk 2]
```diff
@@ -247,50 +303,39 @@ impl CompactionFilter for WriteCompactionFilter {
...
                 WriteType::Rollback | WriteType::Lock => filtered = true,
                 WriteType::Put => self.remove_older = true,
                 WriteType::Delete => {
                     self.remove_older = true;
-                    if self.bottommost_level {
-                        filtered = true;
-                        self.gc_before_delete_mark(key, key_prefix);
-                    }
+                    filtered = true;
+                    self.deleting.0 = key_prefix.to_vec();
```
Comment (yiwu-arbug) [inline src/server/gc_worker/compaction_filter.rs:330]: What's the rational to actively remove stale versions after Delete but not Put?

Comment (yiwu-arbug) [inline src/server/gc_worker/compaction_filter.rs:330]: since `self.deleting.0` is just `self.key_prefix`, can we have `deleting` being an `Option<VecDeque>`? And adjust the changes around line 317.

File: src/server/gc_worker/compaction_filter.rs [hunk 3]
```diff
@@ -229,12 +280,17 @@ impl Drop for WriteCompactionFilter {
         }
 
         self.switch_key_metrics();
-        debug!(
-            "WriteCompactionFilter has filtered all key/value pairs";
-            "bottommost_level" => self.bottommost_level,
-            "versions" => self.total_versions,
-            "deleted" => self.total_deleted,
-        );
+        VERSIONS_AND_DELETES.with(|x| {
```
Comment (yiwu-arbug) [inline src/server/gc_worker/compaction_filter.rs:283]: shall we export the metrics to grafana instead of in info log?

File: src/server/gc_worker/compaction_filter.rs [hunk 4]
```diff
@@ -160,33 +163,75 @@ impl WriteCompactionFilter {
...
+        let mut write_iter = self.write_iter.take().unwrap();
         while valid {
-            let (key, value) = (iter.key(), iter.value());
-            let key_prefix = match Key::split_on_ts_for(key) {
-                Ok((key, _)) => key,
-                Err(_) => continue,
-            };
-            if key_prefix != prefix {
+            let (key, value) = (write_iter.key(), write_iter.value());
+            if truncate_ts(key) > self.deleting.0.as_slice() {
```
Comment (yiwu-arbug) [inline src/server/gc_worker/compaction_filter.rs:175]: nit: do `!=` just to be safe?

File: src/server/gc_worker/compaction_filter.rs [hunk 5]
```diff
@@ -160,33 +163,75 @@ impl WriteCompactionFilter {
...
                 break;
             }
-            let write = WriteRef::parse(value).unwrap();
-            if write.short_value.is_none() && write.write_type == WriteType::Put {
-                let def_key = Key::from_encoded_slice(key_prefix).append_ts(write.start_ts);
-                self.delete_default_key(def_key.as_encoded());
+
+            let (mut drain_pos, mut found) = (0, false);
+            while drain_pos < self.deleting.1.len() {
+                match write_iter.key().cmp(self.deleting.1[drain_pos].as_slice()) {
```
Comment (yiwu-arbug) [inline src/server/gc_worker/compaction_filter.rs:183]: I thin we can assume both write_iter and `deleting.1` are ordered, and remember `drain_pos` to avoid searching over again for the next key version?

**Review by yiwu-arbug — COMMENTED** [review]
We get more CPU usage for this PR. How about compare it to without compaction filter?

File: src/server/gc_worker/compaction_filter.rs (hunk 2 above)
Comment (hicqu) [reply src/server/gc_worker/compaction_filter.rs:330]: For MVCC delete marks, it's necessary to delete all stale versions (maybe not involved in the compaction) older than them because the marks themselves are not kept.

File: src/server/gc_worker/compaction_filter.rs (hunk 3 above)
Comment (hicqu) [reply src/server/gc_worker/compaction_filter.rs:283]: metrics are updated in `switch_key_metrics`.

File: src/server/gc_worker/compaction_filter.rs (hunk 5 above)
Comment (hicqu) [reply src/server/gc_worker/compaction_filter.rs:183]: `deleting` is drained after every search so there won't be any redundant searches.

**Review by yiwu-arbug — APPROVED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]
