### PR TITLE
cdc: re-design delegate and downstream to support partial region subscription better

### LINKED ISSUE #16526: other tikv panic when inject one of tikv failure with ticdc changfeed running
### What version of TiKV are you using?
./tikv-server -V
 TiKV 
Release Version:   8.0.0-alpha
Edition:           Community
Git Commit Hash:   55c572a564c2826498135e71dc2713594647c33b
Git Commit Branch: heads/refs/tags/v8.0.0-alpha
UTC Build Time:    2024-02-10 11:56:41
Rust Version:      rustc 1.77.0-nightly (89e2160c4 2023-12-27)
Enable Features:   pprof-fp jemalloc mem-profiling portable sse test-engine-kv-rocksdb test-engine-raft-raft-engine cloud-aws cloud-gcp cloud-azure trace-async-tasks openssl-vendored
Profile:           dist_release
2024-02-13T21:21:47.678+0800

### What operating system and CPU are you using?
8c/32g

### Steps to reproduce
1、run ticdc changfeed
2、run workload
3、inject one of tikv failure

### What did you expect?
no panic

### What did happened?
other tikv panic when inject one of tikv failure with ticdc changfeed running

{"container":"tikv","log":"[[lib.rs:477](http://lib.rs:477/)] [\"region 33816 commit_ts: TimeStamp(447697680388849796), resolved_ts: TimeStamp(447697683350290435)\"] [backtrace=\"   0: tikv_util::set_panic_hook::{{closure}}\\n             at home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/components/tikv_util/src/lib.rs:476:18\\n](http://github.com/pingcap/tikv/components/tikv_util/src/lib.rs:476:18//n)   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call\\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/[boxed.rs:2029](http://boxed.rs:2029/):9\\n      std::panicking::rust_panic_with_hook\\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/[panicking.rs:783](http://panicking.rs:783/):13\\n   2: std::panicking::begin_panic_handler::{{closure}}\\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/[panicking.rs:657](http://panicking.rs:657/):13\\n   3: std::sys_common::backtrace::__rust_end_short_backtrace\\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/[backtrace.rs:171](http://backtrace.rs:171/):18\\n   4: rust_begin_unwind\\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/[panicking.rs:645](http://panicking.rs:645/):5\\n   5: core::panicking::panic_fmt\\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/[panicking.rs:72](http://panicking.rs:72/):14\\n   6: cdc::delegate::Delegate::sink_txn_put\\n             at home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/components/cdc/src/delegate.rs:878:21\\n](http://github.com/pingcap/tikv/components/cdc/src/delegate.rs:878:21//n)      cdc::delegate::Delegate::sink_put\\n             at home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/components/cdc/src/delegate.rs:837:13\\n](http://github.com/pingcap/tikv/components/cdc/src/delegate.rs:837:13//n)      cdc::delegate::Delegate::sink_data\\n             at home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/components/cdc/src/delegate.rs:696:33\\n](http://github.com/pingcap/tikv/components/cdc/src/delegate.rs:696:33//n)      cdc::delegate::Delegate::on_batch\\n             at home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/components/cdc/src/delegate.rs:558:17\\n](http://github.com/pingcap/tikv/components/cdc/src/delegate.rs:558:17//n)   7: cdc::endpoint::Endpoint<T,E,S>::on_multi_batch\\n             at home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/components/cdc/src/endpoint.rs:886:33\\n](http://github.com/pingcap/tikv/components/cdc/src/endpoint.rs:886:33//n)      <cdc::endpoint::Endpoint<T,E,S> as tikv_util::worker::pool::Runnable>::run\\n             at home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/components/cdc/src/endpoint.rs:1275:18\\n](http://github.com/pingcap/tikv/components/cdc/src/endpoint.rs:1275:18//n)   8: tikv_util::worker::pool::Worker::start_with_timer_impl::{{closure}}\\n             at home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/components/tikv_util/src/worker/pool.rs:517:25\\n](http://github.com/pingcap/tikv/components/tikv_util/src/worker/pool.rs:517:25//n)      <tracker::tls::TrackedFuture<F> as core::future::future::Future>::poll::{{closure}}\\n             at home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/components/tracker/src/tls.rs:64:23\\n](http://github.com/pingcap/tikv/components/tracker/src/tls.rs:64:23//n)      std::thread::local::LocalKey<T>::try_with\\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/[local.rs:270](http://local.rs:270/):16\\n      std::thread::local::LocalKey<T>::with\\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/[local.rs:246](http://local.rs:246/):9\\n      <tracker::tls::TrackedFuture<F> as core::future::future::Future>::poll\\n             at home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/components/tracker/src/tls.rs:62:27\\n](http://github.com/pingcap/tikv/components/tracker/src/tls.rs:62:27//n)      tikv_util::yatp_pool::future_pool::PoolInner::spawn::{{closure}}\\n             at home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/components/tikv_util/src/yatp_pool/future_pool.rs:220:28\\n](http://github.com/pingcap/tikv/components/tikv_util/src/yatp_pool/future_pool.rs:220:28//n)      yatp::task::future::RawTask<F>::poll\\n             at rust/git/checkouts/yatp-e704b73c3ee279b6/793be4d/src/task/[future.rs:59](http://future.rs:59/):9\\n   9: yatp::task::future::TaskCell::poll\\n             at rust/git/checkouts/yatp-e704b73c3ee279b6/793be4d/src/task/[future.rs:103](http://future.rs:103/):9\\n      <yatp::task::future::Runner as yatp::pool::runner::Runner>::handle\\n             at rust/git/checkouts/yatp-e704b73c3ee279b6/793be4d/src/task/[future.rs:387](http://future.rs:387/):20\\n  10: <tikv_util::yatp_pool::YatpPoolRunner<T> as yatp::pool::runner::Runner>::handle\\n             at home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/components/tikv_util/src/yatp_pool/mod.rs:198:24\\n](http://github.com/pingcap/tikv/components/tikv_util/src/yatp_pool/mod.rs:198:24//n)      yatp::pool::worker::WorkerThread<T,R>::run\\n             at rust/git/checkouts/yatp-e704b73c3ee279b6/793be4d/src/pool/[worker.rs:48](http://worker.rs:48/):13\\n      yatp::pool::builder::LazyBuilder<T>::build::{{closure}}\\n             at rust/git/checkouts/yatp-e704b73c3ee279b6/793be4d/src/pool/[builder.rs:114](http://builder.rs:114/):25\\n      std::sys_common::backtrace::__rust_begin_short_backtrace\\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/[backtrace.rs:155](http://backtrace.rs:155/):18\\n  11: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}\\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/[mod.rs:529](http://mod.rs:529/):17\\n      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once\\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panic/[unwind_safe.rs:272](http://unwind_safe.rs:272/):9\\n      std::panicking::try::do_call\\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/[panicking.rs:552](http://panicking.rs:552/):40\\n      std::panicking::try\\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/[panicking.rs:516](http://panicking.rs:516/):19\\n      std::panic::catch_unwind\\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/[panic.rs:142](http://panic.rs:142/):14\\n      std::thread::Builder::spawn_unchecked_::{{closure}}\\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/[mod.rs:528](http://mod.rs:528/):30\\n      core::ops::function::FnOnce::call_once{{vtable.shim}}\\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/[function.rs:250](http://function.rs:250/):5\\n  12: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once\\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/[boxed.rs:2015](http://boxed.rs:2015/):9\\n      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once\\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/[boxed.rs:2015](http://boxed.rs:2015/):9\\n      std::sys::unix::thread::Thread::new::thread_start\\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys/unix/[thread.rs:108](http://thread.rs:108/):17\\n  13: start_thread\\n  14: clone\\n\"] [location=components/cdc/src/[delegate.rs:878](http://delegate.rs:878/)] [thread_name=cdc-0] [thread_id=30]","level":"FATAL","namespace":"endless-ha-test-ticdc-tps-6541512-1-295","pod":"tc-tikv-1"}

### PR DESCRIPTION
**Pull request by hicqu**
### What is changed and how it works?

Issue Number: Close #16526

What's Changed:

* Refactor `Delegate` and `Downstream` to support partial subscription better:
  * incremental scan can be performed on the subscribed range instead of the whole region;
  * if there is a lock in the subscribed region but not in the subscribed range, resolved-ts won't be blocked any more.

```commit-message

```

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [ ] Need to cherry-pick to the release branch

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note

```release-note
None
```

### CODE REVIEW

File: components/txn_types/src/types.rs [hunk 1]
```diff
@@ -247,6 +247,11 @@ impl Key {
     pub fn len(&self) -> usize {
         self.0.len()
     }
+
+    #[inline]
+    pub fn transumte_encoded(encoded_key: &Vec<u8>) -> &Self {
```
Comment (3AceShowHand) [inline components/txn_types/src/types.rs:252]: do you mean `transmute` ?

`transumte` -> `transmute`

File: components/cdc/src/endpoint.rs [hunk 2]
```diff
@@ -350,14 +349,103 @@ impl ResolvedRegionHeap {
...
+}
 
-    fn clear(&mut self) {
-        self.heap.clear();
-    }
+#[derive(Default, Debug)]
+pub(crate) struct Advance {
+    // multiplexing means one region can be subscribed multiple times in one `Conn`,
+    // in which case progresses are grouped by (ConnId, request_id).
+    pub(crate) multiplexing: HashMap<(ConnId, u64), ResolvedRegionHeap>,
```
Comment (3AceShowHand) [inline components/cdc/src/endpoint.rs:358]: can we declare a new data type `RequestID` to replace the `u64`

File: components/cdc/src/endpoint.rs [hunk 3]
```diff
@@ -350,14 +349,103 @@ impl ResolvedRegionHeap {
...
+
+    // exclusive means one region can only be subscribed one time in one `Conn`,
+    // in which case progresses are grouped by ConnId.
+    pub(crate) exclusive: HashMap<ConnId, ResolvedRegionHeap>,
+
+    // To be compatible with old TiCDC client before v4.0.8.
+    // TODO(qupeng): we can deprecate support for too old TiCDC clients.
```
Comment (3AceShowHand) [inline components/cdc/src/endpoint.rs:365]: Is there any plan to deprecate support too old TiCDC clients? 

What condition satisfied can we do this ?

File: components/cdc/src/endpoint.rs [hunk 4]
```diff
@@ -350,14 +349,103 @@ impl ResolvedRegionHeap {
...
+    pub(crate) blocked_on_locks: usize,
+}
+
+impl Advance {
+    fn emit_resolved_ts(&mut self, connections: &HashMap<ConnId, Conn>) -> (u64, TimeStamp) {
+        let handle_send_result = |conn: &Conn, res: std::result::Result<(), SendError>| -> bool {
+            match res {
+                Ok(_) => return true,
+                Err(SendError::Disconnected) => {
+                    debug!("cdc send event failed, disconnected";
```
Comment (3AceShowHand) [inline components/cdc/src/endpoint.rs:382]: will this output too much logs? It looks that `disconnected` may happens more frequently than `full` and `congested`, since the latter two log level is set to info, but this one set to debug.

File: components/cdc/src/delegate.rs [hunk 5]
```diff
@@ -1036,6 +1111,33 @@ impl Delegate {
     }
 }
 
+#[derive(Default)]
+struct RowsBuilder {
+    // map[Key]->(row, has_value, lock_count_modify)
```
Comment (pingyu) [inline components/cdc/src/delegate.rs:1116]: Nit: make `(row, has_value, lock_count_modify)` a struct for more readable.

File: components/cdc/src/delegate.rs [hunk 6]
```diff
@@ -1225,8 +1328,23 @@ impl ObservedRange {
         entries.retain(|e| self.is_key_in_range(&self.start_key_raw, &self.end_key_raw, &e.key));
         entries
     }
+
+    fn to_range(&self) -> (Bound<&Key>, Bound<&Key>) {
+        unsafe {
+            let start = Bound::Included(std::mem::transmute(&self.start_key_encoded));
```
Comment (pingyu) [inline components/cdc/src/delegate.rs:1334]: Need to add `#[repr(transparent)]` to `Key` ?

File: components/cdc/src/delegate.rs [hunk 7]
```diff
@@ -549,19 +708,17 @@ impl Delegate {
             } = cmd;
             if response.get_header().has_error() {
                 let err_header = response.mut_header().take_error();
-                self.mark_failed();
```
Comment (pingyu) [inline components/cdc/src/delegate.rs:552]: Why we can remove the `mark_failed`s ?

File: components/cdc/src/endpoint.rs [hunk 8]
```diff
@@ -2331,6 +2266,7 @@ mod tests {
                 other => panic!("unknown event {:?}", other),
             }
         } else {
+            println!("event: {:?}", cdc_event.0);
```
Comment (pingyu) [inline components/cdc/src/endpoint.rs:2269]:
```suggestion
```

File: components/txn_types/src/types.rs [hunk 9]
```diff
@@ -247,6 +247,11 @@ impl Key {
     pub fn len(&self) -> usize {
         self.0.len()
     }
+
+    #[inline]
```
Comment (pingyu) [inline components/txn_types/src/types.rs:251]: I don't find where it's used. For `ObservedRange.to_range()` ?

File: components/cdc/src/delegate.rs [hunk 10]
```diff
@@ -216,107 +237,72 @@ impl Downstream {
...
-        self.req_id
-    }
 }
 
-struct Pending {
-    downstreams: Vec<Downstream>,
-    locks: Vec<PendingLock>,
-    pending_bytes: usize,
-    memory_quota: Arc<MemoryQuota>,
+// In `PendingLock`,  `key` is raw format instead of encoded.
```
Comment (pingyu) [inline components/cdc/src/delegate.rs:245]: They seems to be encoded ?

**Review by pingyu — COMMENTED** [review]
The PR is a little too big. Suggest to split to some smaller PRs.

File: components/cdc/src/endpoint.rs (hunk 2 above)
Comment (hicqu) [reply components/cdc/src/endpoint.rs:358]: Many lines will be changed by this replacing. I prefer to do it in another PR.

File: components/cdc/src/endpoint.rs (hunk 3 above)
Comment (hicqu) [reply components/cdc/src/endpoint.rs:365]: We can do it right now. In the latest TiCDC, upstream cluster version should be greater than 6.1.

File: components/cdc/src/endpoint.rs (hunk 4 above)
Comment (hicqu) [reply components/cdc/src/endpoint.rs:382]: By default `info` will be called 1 time in 1 second for every connection. I think it's OK. We need this log to debug.

File: components/cdc/src/delegate.rs [hunk 11]
```diff
@@ -326,45 +312,192 @@ impl HeapSize for PendingLock {
...
+        for delta_lock in delta_locks {
+            let bytes = delta_lock.approximate_heap_size();
+            self.memory_quota.free(bytes);
+            CDC_PENDING_BYTES_GAUGE.sub(bytes as _);
+            match delta_lock {
+                PendingLock::Track { key, start_ts } => match locks.entry(key) {
+                    BTreeMapEntry::Vacant(x) => {
+                        x.insert(start_ts);
+                    }
+                    BTreeMapEntry::Occupied(x) => {
```
[the remark this answers is not in the document]
Comment (hicqu) [reply components/cdc/src/delegate.rs:421]: For the new pipelined DML protocol.

File: components/cdc/src/delegate.rs (hunk 7 above)
Comment (hicqu) [reply components/cdc/src/delegate.rs:552]: `mark_failed` will be called in the function which calls `on_batch`.

File: components/txn_types/src/types.rs (hunk 9 above)
Comment (hicqu) [reply components/txn_types/src/types.rs:251]: Yes.

File: components/cdc/src/delegate.rs (hunk 10 above)
Comment (hicqu) [reply components/cdc/src/delegate.rs:245]: Yes!

File: components/cdc/src/delegate.rs [hunk 12]
```diff
@@ -1166,11 +1287,11 @@ fn decode_default(value: Vec<u8>, row: &mut EventRow, has_value: &mut bool) {
...
 pub struct ObservedRange {
-    start_key_encoded: Vec<u8>,
-    end_key_encoded: Vec<u8>,
-    start_key_raw: Vec<u8>,
-    end_key_raw: Vec<u8>,
-    pub(crate) all_key_covered: bool,
+    pub start_key_encoded: Vec<u8>,
+    pub end_key_encoded: Vec<u8>,
+    pub start_key_raw: Vec<u8>,
+    pub end_key_raw: Vec<u8>,
```
Comment (overvenus) [inline components/cdc/src/delegate.rs:1293]: How about changing types to `Key`? So we don't need unsafe `transmute_encoded`.

File: components/cdc/src/delegate.rs [hunk 13]
```diff
@@ -1106,28 +1230,25 @@ fn decode_write(
...
+
     row.start_ts = lock.ts.into_inner();
     row.key = key.into_raw().unwrap();
     row.op_type = op_type as _;
-    // used for filter out the event. see `txn_source` field for more detail.
     row.txn_source = lock.txn_source;
     set_event_row_type(row, EventLogType::Prewrite);
     if let Some(value) = lock.short_value {
-        row.value = value;
+        assert!(!*has_value);
```
Comment (overvenus) [inline components/cdc/src/delegate.rs:1249]: How about printing some debugging info? Such as ts or hexed key.

File: components/cdc/src/delegate.rs [hunk 14]
```diff
@@ -120,22 +125,33 @@ impl DownstreamState {
...
-    peer: String,
-    region_epoch: RegionEpoch,
+    pub id: DownstreamId,
+    pub peer: String,
+    pub region_epoch: RegionEpoch,
+    pub req_id: u64,
+    pub conn_id: ConnId,
+    pub kv_api: ChangeDataRequestKvApi,
+    pub filter_loop: bool,
+    pub observed_range: ObservedRange,
```
Comment (overvenus) [inline components/cdc/src/delegate.rs:136]: Please keep comments.

File: components/cdc/src/delegate.rs [hunk 15]
```diff
@@ -216,107 +237,72 @@ impl Downstream {
...
-                "num_locks" => num_locks,
-                "memory_quota_in_use" => self.memory_quota.in_use(),
-                "memory_quota_capacity" => self.memory_quota.capacity(),
-            );
+impl fmt::Debug for LockTracker {
+    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
+        match self {
+            LockTracker::Pending => write!(f, "LockTracker::Pending"),
+            LockTracker::Preparing(..) => write!(f, "LockTracker::Preparing"),
+            LockTracker::Prepared { .. } => write!(f, "LockTracker::Prepared"),
```
Comment (overvenus) [inline components/cdc/src/delegate.rs:275]: How about printing the number of locks?

File: components/cdc/src/delegate.rs [hunk 16]
```diff
@@ -326,45 +312,195 @@ impl HeapSize for PendingLock {
...
+impl Drop for Delegate {
+    fn drop(&mut self) {
+        match &self.lock_tracker {
+            LockTracker::Pending => {}
+            LockTracker::Preparing(locks) => {
+                for lock in locks {
+                    let bytes = lock.approximate_heap_size();
+                    self.memory_quota.free(bytes);
+                    CDC_PENDING_BYTES_GAUGE.sub(bytes as _);
+                }
```
Comment (overvenus) [inline components/cdc/src/delegate.rs:337]:
```suggestion
                let mut free_bytes = 0;
                for lock in locks {
                    let bytes = lock.approximate_heap_size();
                    self.memory_quota.free(bytes);
                    free_bytes += bytes;
                }
                CDC_PENDING_BYTES_GAUGE.sub(free_bytes as _);
```

File: components/cdc/src/delegate.rs [hunk 17]
```diff
@@ -675,287 +834,216 @@ impl Delegate {
...
-                        "region_id" => self.region_id,
-                        "command" => ?req,
-                    );
-                    Ok(())
+            match req.get_cmd_type() {
+                CmdType::Put => {
+                    self.sink_put(req.take_put(), &mut rows_builder, &mut read_old_value)?
                 }
+                CmdType::Delete => self.sink_delete(req.take_delete(), &mut rows_builder)?,
+                _ => debug!("skip other command"; "region_id" => self.region_id, "command" => ?req),
```
Comment (overvenus) [inline components/cdc/src/delegate.rs:859]:
```suggestion
                _ => debug!("cdc skip other command";
                        "region_id" => self.region_id,
                        "command" => ?req),
```

**Review by overvenus — COMMENTED** [review]
Will do another round review.

File: components/txn_types/src/types.rs [hunk 18]
```diff
@@ -45,7 +45,8 @@ pub type KvPair = (Vec<u8>, Value);
 /// Orthogonal to binary representation, keys may or may not embed a timestamp,
 /// but this information is transparent to this type, the caller must use it
 /// consistently.
-#[derive(Eq, PartialEq, Ord, PartialOrd, Hash)]
+#[derive(Eq, PartialEq, Ord, PartialOrd, Hash, Default)]
+#[repr(transparent)]
```
Comment (overvenus) [inline components/txn_types/src/types.rs:49]:
```suggestion
#[derive(Eq, PartialEq, Ord, PartialOrd, Hash)]
```

File: components/cdc/tests/failpoints/test_memory_quota.rs [hunk 19]
```diff
@@ -146,6 +134,7 @@ fn test_pending_on_region_ready_memory_quota_exceeded() {
         }
         other => panic!("unknown event {:?}", other),
     }
+    println!("gets an error");
```
Comment (overvenus) [inline components/cdc/tests/failpoints/test_memory_quota.rs:137]:
```suggestion
```

File: components/cdc/src/initializer.rs [hunk 20]
```diff
@@ -413,40 +468,25 @@ impl<E: KvEngine> Initializer<E> {
...
             CDC_SCAN_DISK_READ_BYTES.inc_by(bytes as _);
             self.scan_speed_limiter.consume(bytes).await;
         }
-        CDC_SCAN_BYTES.inc_by(emit as _);
-        self.fetch_speed_limiter.consume(emit as _).await;
-
-        if let Some(resolver) = resolver {
-            // Track the locks.
-            for entry in entries.iter().flatten() {
-                if let KvEntry::TxnEntry(TxnEntry::Prewrite { ref lock, .. }) = entry {
```
[the remark this answers is not in the document]
Comment (hicqu) [reply components/cdc/src/initializer.rs:437]: Because locks are already retrieved and handled in the `MvccReader` above.

**Review by pingyu — APPROVED** [review]
LGTM～
