### PR TITLE
test: fix error when Linux kernel doesn't contain epollex engine

### LINKED ISSUE #1965: tikv does not build on ppc64le
1. What version of Rust are you using (`rustc --version`)?
Beta 1.19 and Nightly 1.20 downloaded from - https://static.rust-lang.org/dist/rust-beta-powerpc64le-unknown-linux-gnu.tar.gz

2. What operating system and processor architecture are you using?
ppc64le, RedHat 7.3

3. What did you do?
Build tikv using make / make static_release
The build fails with the following error
error[E0432]: unresolved import `types::os::arch::c95::*`
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/libc-0.1.12/rust/src/liblibc/lib.rs:100:9
    |
100 | pub use types::os::arch::c95::*;
    |         ^^^^^^^^^^^^^^^^^^^^^^^^ Could not find `arch` in `os`
... ...

4. Analysis so far:
Initially, I was suspecting that the libc crate is not ported for ppc64le, however, after interacting with the rust community, I found that support for ppc64le is available in the latest version of the libc crate.
https://github.com/rust-lang/rust/issues/42858

They suggest upgrading utime, nix and other tikv dependencies to the latest version for better platform compatibility. 

I am currently trying to understand what all might need to be updated- any pointers/thoughts on this would be of great help - thanks in advance!!

Regards,
Priya

### PR DESCRIPTION
**Pull request by Hijiao**
Signed-off-by: Max <xiahaijiao@hotmail.com>

## What have you changed? (mandatory)
Fix #1965 

## What are the type of the changes? (mandatory)

- Bug fix (non-breaking change which fixes an issue)

## How has this PR been tested? (mandatory)
No
## Does this PR affect documentation (docs) update? (mandatory)

No

## Does this PR affect tidb-ansible update? (mandatory)
No

### CODE REVIEW

**Comment by Hijiao** [comment]
@BusyJay  @overvenus  PTAL

File: components/test_util/src/lib.rs [hunk 1]
```diff
@@ -34,19 +34,28 @@ pub use macros::*;
...
+        if env::var("LOG_FILE").is_ok() {
+            logging::init_log_for_test();
+        }
+
+        // HACK! Use `epollex` as the polling engine for gRPC when running CI tests on
+        // Linux and it hasn't been set before.
+        // See more: https://github.com/grpc/grpc/blob/v1.17.2/src/core/lib/iomgr/ev_posix.cc#L124
+        // See more: https://grpc.io/grpc/core/md_doc_core_grpc-polling-engines.html
+        #[cfg(target_os = "linux")]
+        {
```
Comment (BusyJay) [inline components/test_util/src/lib.rs]: Are the brackets necessary?

Comment (Hijiao) [reply components/test_util/src/lib.rs]: Yes, `if` expression is not supported.
