### PR TITLE
In-memory Engine: optimize auto evict to reduce latency spike

### LINKED ISSUE #18093: In-memory Engine: regions periodically evict and load which may lead to latency jitter
### What version of TiKV are you using?
./tikv-server -V
 TiKV 
Release Version:   8.5.0
Edition:           Community
Git Commit Hash:   a2c58c94f89cbb410e66d8f85c236308d6fc64f0
Git Commit Branch: HEAD
UTC Build Time:    2024-12-18 03:28:49
Rust Version:      rustc 1.77.0-nightly (89e2160c4 2023-12-27)
Enable Features:   memory-engine pprof-fp jemalloc mem-profiling portable sse test-engine-kv-rocksdb test-engine-raft-raft-engine trace-async-tasks openssl-vendored
Profile:           dist_release
2025-01-04T11:04:00.159+0800

### What operating system and CPU are you using?
30c/100GB

### Steps to reproduce
1、enable IME
2、pause scheduler
3、run mvcc select

### What did you expect?
qps and  latency can keep stability

### What did happened?
Regions periodically evict and load which lead to latency jitter

Image
Image

### PR DESCRIPTION
**Pull request by overvenus**
### What is changed and how it works?

Issue Number: Close #18093

What's Changed:

Tested with read-only workload.

Left: This PR
Right: nightly 2025-01-13

image

```commit-message
Optimize auto evict to minimize coprocessor request latency by avoiding
periodic eviction and loading of regions with high MVCC amplification.

* Do not evict cached regions when memory has not reached the
  `stop-load-threshold`.
* Replace MVCC amplification-based auto evict strategy with a simple
  moving average of coprocessor requests. This is because
  `RegionWriteCfCopDetail` only reflects MVCC amplification in IME,
  not in RocksDB, making low MVCC amplification a poor indicator for eviction.
```

### Related changes

- Need to cherry-pick to the release branch

### Check List

Tests 

- [ ] Unit test

### Release note

```release-note
Optimize auto evict to minimize coprocessor request latency by avoiding periodic eviction and loading of regions with high MVCC amplification.
```

### CODE REVIEW

File: components/in_memory_engine/src/region_stats.rs [hunk 1]
```diff
@@ -269,68 +215,96 @@ impl RegionStatsManager {
...
+                // NB: When a region is cached, its RegionWriteCfCopDetail only
+                // reflects the MVCC amplification in IME not in RocksDB. So
+                // low MVCC amplification is not a good indicator for eviction.
+                //
+                // Instead, we assume workload patterns remain consistent after
+                // caching and evict based on request frequency.
+                let is_cop_requests_low = crs.sma_cop_requests_avg
+                    <= avg_cop_requests / SMA_COP_REQUEST_AVG_FILTER_FACTOR;
+
+                let is_cop_requests_reliable =
```
Comment (glorv) [inline components/in_memory_engine/src/region_stats.rs:252]: Does this mean if a region has no reuqest, it can be evicted at all?

File: components/in_memory_engine/src/region_stats.rs [hunk 2]
```diff
@@ -457,6 +411,57 @@ impl RegionStatsManager {
...
+        crss.push(CachedRegionStat {
+            iterated_count: stat.cop_detail.iterated_count(),
+            region,
+            stat,
+            sma_cop_requests_avg: cop_requests_avg,
+            sma_cop_requests_count: cop_requests_count,
+        });
+    }
+
+    crss.sort_by(|a, b| {
```
Comment (glorv) [inline components/in_memory_engine/src/region_stats.rs:453]: Ideally, we should cache regions which to most `reqeusts * (avg_kv_per_req_before_cache - avg_kv_per_req_after_cache)`, this can largely reflect the resource usage save after load. Thus, I think QPS or request_count is an even poorer metrics here.

File: components/in_memory_engine/src/region_manager.rs [hunk 3]
```diff
@@ -261,6 +286,7 @@ impl CacheRegionMeta {
             in_gc: AtomicBool::new(source_meta.in_gc.load(Ordering::Relaxed)),
             is_written: AtomicBool::new(source_meta.is_written.load(Ordering::Relaxed)),
             evict_info: None,
+            average_cop_requests: Arc::new(Mutex::new(Default::default())),
```
Comment (glorv) [inline components/in_memory_engine/src/region_manager.rs:289]: So after region split, all child region's stats will be reset. Better derive the stats data from parent region.

File: components/in_memory_engine/src/region_manager.rs [hunk 4]
```diff
@@ -109,7 +109,16 @@ impl SnapshotList {
     }
 }
 
-#[derive(Debug)]
+/// Estimates the smoothed coprocessor request rate over the last hour using a
+/// simple moving average.
+pub(crate) type CopRequestsSMA = Smoother<f64, COP_REQUEST_SMA_RECORD_COUNT, ONE_HOUR_IN_SECS, 0>;
```
Comment (glorv) [inline components/in_memory_engine/src/region_manager.rs:114]:
```suggestion
pub(crate) type CopRequestsSma = Smoother<f64, COP_REQUEST_SMA_RECORD_COUNT, ONE_HOUR_IN_SECS, 0>;
```
Follow the rust naming convension

**Review by glorv — COMMENTED** [review]
most LGTM, but I think `request count only` is a very poor metrics for region eviction.

File: components/in_memory_engine/src/region_stats.rs [hunk 5]
```diff
@@ -269,68 +215,96 @@ impl RegionStatsManager {
...
+                let is_cop_requests_low = crs.sma_cop_requests_avg
+                    <= avg_cop_requests / SMA_COP_REQUEST_AVG_FILTER_FACTOR;
+
+                let is_cop_requests_reliable =
+                    crs.sma_cop_requests_count > SMA_COP_REQUEST_COUNT_FILTER;
+
+                let is_iterated_count_low = crs.stat.cop_detail.iterated_count()
+                    <= avg_next_prev / ITERATED_COUNT_FILTER_FACTOR;
+
+                is_memory_low
```
Comment (LykxSassinator) [inline components/in_memory_engine/src/region_stats.rs:258]: Does it should be `!is_memory_low` to represent that although the memory_usage is low, it should also evict some cached_regions which are not frequently accessed ?

**Review by LykxSassinator — COMMENTED** [review]
Overall LGTM

File: components/in_memory_engine/src/region_stats.rs (hunk 5 above)
Comment (overvenus) [reply components/in_memory_engine/src/region_stats.rs:258]: The variable name is misleading, it actually means the remain memory capacity for IME is low. Will revise the name.

File: components/in_memory_engine/src/region_stats.rs (hunk 2 above)
Comment (overvenus) [reply components/in_memory_engine/src/region_stats.rs:453]: We can iterative improve the eviction algorithm, after all the master implementation is inaccurate, and this PR can reduce spike as tests show.

File: components/in_memory_engine/src/region_stats.rs (hunk 1 above)
Comment (overvenus) [reply components/in_memory_engine/src/region_stats.rs:252]: `is_cop_requests_low` means if a region has a few requests, then it will be an eviction candidate.
`is_cop_requests_reliable` means an eviction candidate can only be evicted if IME has sampled it three times (by default 30 minutes)

Comment (LykxSassinator) [reply components/in_memory_engine/src/region_stats.rs:254]: Could you update the annotations with the above comments or incorporate them into the annotations? This would make the strategy for choosing eviction candidates clearer and easier to understand.

**Review by glorv — APPROVED** [review]

File: components/in_memory_engine/src/region_stats.rs (hunk 1 above)
Comment (overvenus) [reply components/in_memory_engine/src/region_stats.rs:254]: Comments are added in f263f5e07f98da24d1fc65a9f694693ac5835f30

**Review by LykxSassinator — APPROVED** [review]

**Comment by glorv** [comment]
@overvenus this is a lint error
