### PR TITLE
In-memory engine: fix concurrency issue between delete range and write to memory

### LINKED ISSUE #17104: In-memory Engine: race condition among delete range and write to memory engine
## Bug Report

When deleting ranges as well as write to memory enigne, we will free the lock to avoid blocking other operations. However, we are missing mechanism to handle the concurrency between these two operations, which results in dirty data when loading a range.

### What version of TiKV are you using?

built on [bbc4af3](https://github.com/tikv/tikv/pull/16868/commits/bbc4af3404a21ed418a088a4edc35eaefedf7441)

### PR DESCRIPTION
**Pull request by SpadeA-Tang**
### What is changed and how it works?

Issue Number: Close #17104

What's Changed:

```commit-message
fix concurrency issue between delete range and write to memory
```
Range delete and range write may be exectued concurrently which causes data in the range may not be cleared completely, so that dirty data exists which cause data inconsistency. 
This PR fixes it by making a dedicated worker perform delete range task (no other places can perform delete range), and before actually delete the data, check whether the range is being written. If the range is being written, the delete task will be delayed. It ensures that when the range is being deleted, no more data will be inserted in the engine.

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [ ] Need to cherry-pick to the release branch

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note

```release-note
None
```

### CODE REVIEW

File: components/region_cache_memory_engine/src/background.rs [hunk 1]
```diff
@@ -549,27 +584,32 @@ impl BackgroundRunnerCore {
...
-                    for r in ranges_to_delete {
-                        engine_wr.engine().delete_range(&r);
-                        if r.overlaps(range) {
-                            evicted_range = true;
-                        }
-                    }
+                    ranges_to_delete.append(&mut ranges);
                 }
             }
             if evicted_range {
```
Comment (SpadeA-Tang) [inline components/region_cache_memory_engine/src/background.rs:603]: I see the previous code shows that this bool is true when `evict_range` returns true. I am not sure what it means: `evict_range` returninig true means there's no ongoing snapshot so that the range can be deleted immediately. So what exactly does the parameter in `handle_range_evicted` means, is it just be evicted or ready to be deleted? @afeinberg

File: components/region_cache_memory_engine/src/write_batch.rs [hunk 2]
```diff
@@ -40,6 +40,7 @@ const AMOUNT_TO_CLEAN_TOMBSTONE: u64 = ReadableSize::mb(16).0;
 // delegate. It sets `range_cache_status` which is used to determine whether the
 // writes of this peer should be buffered.
 pub struct RangeCacheWriteBatch {
+    id: u64,
```
Comment (overvenus) [inline components/region_cache_memory_engine/src/write_batch.rs:43]: Please add some comment about the ID.

File: components/region_cache_memory_engine/src/engine.rs [hunk 3]
```diff
@@ -270,6 +273,8 @@ pub struct RangeCacheMemoryEngine {
     // When reaching to the threshold, a CleanLockTombstone task will be scheduled to clean lock cf
     // tombstones.
     pub(crate) lock_modification_bytes: Arc<AtomicU64>,
+
+    write_batch_id_allocator: Arc<AtomicU64>,
```
Comment (overvenus) [inline components/region_cache_memory_engine/src/engine.rs:277]: Please add comments.

File: components/region_cache_memory_engine/src/background.rs [hunk 4]
```diff
@@ -895,24 +941,22 @@ impl Runnable for BackgroundRunner {
...
                 } else {
                     self.core.memory_controller.set_memory_checking(false);
                 }
             }
-            BackgroundTask::DeleteRange(ranges) => {
-                let mut core = self.core.clone();
-                let f = async move { core.delete_ranges(&ranges) };
-                self.delete_range_remote.spawn(f);
-            }
+            BackgroundTask::DeleteRange(_) => unreachable!(),
```
Comment (overvenus) [inline components/region_cache_memory_engine/src/background.rs:955]: Please add some comments about the `unreachable`.

File: components/region_cache_memory_engine/src/background.rs [hunk 5]
```diff
@@ -1027,6 +1071,84 @@ impl RunnableWithTimer for BackgroundRunner {
...
+        for r in ranges {
+            println!("delete range {:?}", r);
+            skiplist_engine.delete_range(r);
+        }
+        self.engine
+            .write()
+            .mut_range_manager()
+            .on_delete_ranges(ranges);
+        #[cfg(test)]
+        flush_epoch();
```
Comment (overvenus) [inline components/region_cache_memory_engine/src/background.rs:1102]: I'm curious why do we have to flush_epoch here?

File: components/region_cache_memory_engine/src/background.rs [hunk 6]
```diff
@@ -1027,6 +1071,84 @@ impl RunnableWithTimer for BackgroundRunner {
...
+                        {
+                            ranges_to_delay.push(r);
+                        } else {
+                            ranges_to_delete.push(r);
+                        }
+                    }
+                    (ranges_to_delay, ranges_to_delete)
+                };
+                self.delay_ranges.append(&mut ranges_to_delay);
+                self.delete_ranges(&ranges_to_delete);
```
Comment (overvenus) [inline components/region_cache_memory_engine/src/background.rs:1130]: Can it prevent ABA problems? E.g., delete_range `[a, c)` is somehow delayed, and `[a, c)` is reloaded.

Comment (SpadeA-Tang) [reply components/region_cache_memory_engine/src/background.rs:1130]: After [a, c) is evicted and before it completes the deletion, it is in the ranges_being_deleted which prevents any range overlapped with it being loaded.

File: components/region_cache_memory_engine/src/engine.rs (hunk 3 above)
Comment (SpadeA-Tang) [reply components/region_cache_memory_engine/src/engine.rs:278]: Done

File: components/region_cache_memory_engine/src/background.rs (hunk 5 above)
Comment (SpadeA-Tang) [reply components/region_cache_memory_engine/src/background.rs:1104]: In crossbeam skiplist, after delete, the memory free is not performed immedietly, it is buffered and delayed until it is guaranteed that no other threads will read the memory. The flush here is to accelerate this process.

File: components/region_cache_memory_engine/src/range_manager.rs [hunk 7]
```diff
@@ -147,6 +148,19 @@ pub struct RangeManager {
...
+    // It is used to avoid the conccurency issue between delete range and write to memory: after
+    // the range is evicted or failed to load, the range is recorded in `ranges_being_deleted`
+    // which means no further write of it is allowed, and a DeleteRange task of the range will be
+    // scheduled to cleanup the dirty data. However, it is possible that the apply thread is
+    // writting data for this range. Therefore, we have to delay the DeleteRange task until the
+    // range leaves the `ranges_being_written`.
+    //
+    // `u64` means write batch id, we record the ranges of a specific write batch together so when
+    // the write batch is consumed by the in-memory engine, all ranges of it are cleared from
+    // `ranges_being_written`.
```
Comment (LykxSassinator) [inline components/region_cache_memory_engine/src/range_manager.rs:162]:
```suggestion
    // The key in this map is the id of the write batch, and the value is a collection
    // the ranges of this batch. So, when the write batch is consumed by the in-memory engine,
    // all ranges of it are cleared from `ranges_being_written`.
```

File: components/region_cache_memory_engine/src/range_manager.rs [hunk 8]
```diff
@@ -411,6 +425,32 @@ impl RangeManager {
...
 
+    pub(crate) fn range_overlapped_with_ranges_being_written(&self, range: &CacheRange) -> bool {
+        self.ranges_being_written.iter().any(|(_, ranges)| {
+            ranges
+                .iter()
+                .any(|range_being_written| range_being_written.overlaps(range))
+        })
+    }
+
+    pub(crate) fn set_range_in_being_written(&mut self, write_batch_id: u64, range: &CacheRange) {
```
Comment (LykxSassinator) [inline components/region_cache_memory_engine/src/range_manager.rs:436]:
```suggestion
    pub(crate) fn record_in_ranges_being_written(&mut self, write_batch_id: u64, range: &CacheRange) {
```

File: components/region_cache_memory_engine/src/range_manager.rs [hunk 9]
```diff
@@ -411,6 +425,32 @@ impl RangeManager {
         self.ranges_in_gc = ranges_in_gc;
     }
 
+    pub(crate) fn range_overlapped_with_ranges_being_written(&self, range: &CacheRange) -> bool {
```
Comment (LykxSassinator) [inline components/region_cache_memory_engine/src/range_manager.rs:428]:
```suggestion
    pub(crate) fn is_overlapped_with_ranges_being_written(&self, range: &CacheRange) -> bool {
```

File: components/region_cache_memory_engine/src/background.rs [hunk 10]
```diff
@@ -540,36 +569,43 @@ impl BackgroundRunnerCore {
...
+
+        let mut ranges_to_delete = vec![];
         // TODO (afeinberg): approximate size may differ from size in in-memory cache,
         // consider taking the actual size into account.
         for (range, approx_size) in &ranges_to_evict {
             if remaining == 0 {
                 break;
             }
-            let mut evicted_range = false;
+            let evicted_range;
```
Comment (LykxSassinator) [inline components/region_cache_memory_engine/src/background.rs:580]: How about:
```
    let evicted_range = {
        ...
        true
    };
```

File: components/region_cache_memory_engine/src/background.rs [hunk 11]
```diff
@@ -596,20 +632,25 @@ impl BackgroundRunnerCore {
...
+                    "range_to_evict" => ?&evict_range,
+                    "ranges_evicted" => ?ranges
+                );
+                ranges_to_delete.append(&mut ranges);
             }
         }
+        if !ranges_to_delete.is_empty() {
+            delete_range_scheduler
+                .schedule_force(BackgroundTask::DeleteRange(ranges_to_delete))
+                .unwrap();
```
Comment (LykxSassinator) [inline components/region_cache_memory_engine/src/background.rs:652]: Should not we check the error ?

File: components/region_cache_memory_engine/src/background.rs (hunk 10 above)
Comment (SpadeA-Tang) [reply components/region_cache_memory_engine/src/background.rs]: done

File: components/region_cache_memory_engine/src/background.rs (hunk 11 above)
Comment (SpadeA-Tang) [reply components/region_cache_memory_engine/src/background.rs]: modified

**Review by overvenus — APPROVED** [review]

**Review by LykxSassinator — APPROVED** [review]
