### PR TITLE
raftstore: set availability_context

### LINKED ISSUE #15151: [Dynamic Regions] tikv crash for assertion failed: resp.has_availability_context() with tiflash
### What version of TiKV are you using?

TiKV
Release Version:   7.3.0-alpha
Edition:           Community
Git Commit Hash:   c27b43018ca83bd4103abf627c50293b841396bd
Git Commit Branch: heads/refs/tags/v7.3.0-alpha
UTC Build Time:    2023-07-17 11:11:24
Rust Version:      rustc 1.67.0-nightly (96ddd32c4 2022-11-14)
Enable Features:   pprof-fp jemalloc mem-profiling portable sse test-engine-kv-rocksdb test-engine-raft-raft-engine cloud-aws cloud-gcp cloud-azure
Profile:           dist_release
### Steps to reproduce

htap workload with tiflash
### What did you expect?
tikv crash
```
/var/lib/tikv/log/tikv-2023-07-18T16-13-37.895.log:[2023/07/18 16:08:22.551 +08:00] [FATAL] [[lib.rs:510](http://lib.rs:510/)] ["assertion failed: resp.has_availability_context()"] [backtrace="   0: tikv_util::set_panic_hook::{{closure}}\n             at home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/components/tikv_util/src/lib.rs:509:18\n](http://github.com/pingcap/tikv/components/tikv_util/src/lib.rs:509:18/n)   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/[boxed.rs:2032](http://boxed.rs:2032/):9\n      std::panicking::rust_panic_with_hook\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/[panicking.rs:692](http://panicking.rs:692/):13\n   2: std::panicking::begin_panic_handler::{{closure}}\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/[panicking.rs:577](http://panicking.rs:577/):13\n   3: std::sys_common::backtrace::__rust_end_short_backtrace\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/[backtrace.rs:137](http://backtrace.rs:137/):18\n   4: rust_begin_unwind\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/[panicking.rs:575](http://panicking.rs:575/):5\n   5: core::panicking::panic_fmt\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/[panicking.rs:65](http://panicking.rs:65/):14\n   6: core::panicking::panic\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/[panicking.rs:114](http://panicking.rs:114/):5\n   7: raftstore_v2::operation::command::admin::merge::prepare::<impl raftstore_v2::raft::peer::Peer<EK,ER>>::merge_on_availability_response\n             at home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/components/raftstore-v2/src/operation/command/admin/merge/prepare.rs:371:13\n](http://github.com/pingcap/tikv/components/raftstore-v2/src/operation/command/admin/merge/prepare.rs:371:13/n)   8: raftstore_v2::operation::life::<impl raftstore_v2::raft::peer::Peer<EK,ER>>::on_availability_response\n             at home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/components/raftstore-v2/src/operation/life.rs:533:9\n](http://github.com/pingcap/tikv/components/raftstore-v2/src/operation/life.rs:533:9/n)      raftstore_v2::operation::ready::<impl raftstore_v2::raft::peer::Peer<EK,ER>>::on_raft_message\n             at home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/components/raftstore-v2/src/operation/ready/mod.rs:330:21\n](http://github.com/pingcap/tikv/components/raftstore-v2/src/operation/ready/mod.rs:330:21/n)      raftstore_v2::fsm::peer::PeerFsmDelegate<EK,ER,T>::on_msgs\n             at home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/components/raftstore-v2/src/fsm/peer.rs:243:21\n](http://github.com/pingcap/tikv/components/raftstore-v2/src/fsm/peer.rs:243:21/n)   9: <raftstore_v2::batch::store::StorePoller<EK,ER,T> as batch_system::batch::PollHandler<raftstore_v2::fsm::peer::PeerFsm<EK,ER>,raftstore_v2::fsm::store::StoreFsm>>::handle_normal\n             at home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/components/raftstore-v2/src/batch/store.rs:282:9\n](http://github.com/pingcap/tikv/components/raftstore-v2/src/batch/store.rs:282:9/n)      batch_system::batch::Poller<N,C,Handler>::poll\n             at home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/components/batch-system/src/batch.rs:380:27\n](http://github.com/pingcap/tikv/components/batch-system/src/batch.rs:380:27/n)  10: raftstore_v2::worker::refresh_config::PoolController<N,C,H>::increase_by::{{closure}}\n             at home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/components/raftstore-v2/src/worker/refresh_config.rs:75:21\n](http://github.com/pingcap/tikv/components/raftstore-v2/src/worker/refresh_config.rs:75:21/n)      <std::thread::Builder as tikv_util::sys::thread::StdThreadBuildWrapper>::spawn_wrapper::{{closure}}\n             at home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/components/tikv_util/src/sys/thread.rs:438:13\n](http://github.com/pingcap/tikv/components/tikv_util/src/sys/thread.rs:438:13/n)      std::sys_common::backtrace::__rust_begin_short_backtrace\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/[backtrace.rs:121](http://backtrace.rs:121/):18\n  11: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/[mod.rs:551](http://mod.rs:551/):17\n      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panic/[unwind_safe.rs:271](http://unwind_safe.rs:271/):9\n      std::panicking::try::do_call\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/[panicking.rs:483](http://panicking.rs:483/):40\n      std::panicking::try\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/[panicking.rs:447](http://panicking.rs:447/):19\n      std::panic::catch_unwind\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/[panic.rs:137](http://panic.rs:137/):14\n      std::thread::Builder::spawn_unchecked_::{{closure}}\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/[mod.rs:550](http://mod.rs:550/):30\n      core::ops::function::FnOnce::call_once{{vtable.shim}}\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/[function.rs:513](http://function.rs:513/):5\n  12: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/[boxed.rs:2000](http://boxed.rs:2000/):9\n      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/[boxed.rs:2000](http://boxed.rs:2000/):9\n      std::sys::unix::thread::Thread::new::thread_start\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys/unix/[thread.rs:108](http://thread.rs:108/):17\n  13: start_thread\n  14: __clone\n"] [location=/home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/components/raftstore-v2/src/operation/command/admin/merge/prepare.rs:371](http://github.com/pingcap/tikv/components/raftstore-v2/src/operation/command/admin/merge/prepare.rs:371)] [thread_name=rs-177-0]
```
### What did happened?
normally

### PR DESCRIPTION
**Pull request by CalvinNeo**
### What is changed and how it works?

Issue Number: Close #15151

What's Changed:

```commit-message
Set availability_context in raftstore v1
```

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

```release-note
None
```

### CODE REVIEW

File: components/raftstore/src/store/fsm/peer.rs [hunk 1]
```diff
@@ -2681,9 +2681,13 @@ where
         if self.fsm.peer.is_leader() {
             return;
         }
-        let mut resp = ExtraMessage::default();
+        let mut resp: ExtraMessage = ExtraMessage::default();
         resp.set_type(ExtraMessageType::MsgAvailabilityResponse);
         resp.wait_data = self.fsm.peer.wait_data;
+        let report = resp.mut_availability_context();
```
Comment (tonyxuqqi) [inline components/raftstore/src/store/fsm/peer.rs:2687]: Can you add comments on how is the information used in TiFlash

**Review by tonyxuqqi — APPROVED** [review]

File: components/raftstore/src/store/fsm/peer.rs (hunk 1 above)
Comment (CalvinNeo) [reply components/raftstore/src/store/fsm/peer.rs:2687]: This information is used by v2. https://github.com/tikv/tikv/blob/c16cab2c29ba36af51826e9b7d4e8bd950e0c15e/components/raftstore-v2/src/operation/command/admin/merge/prepare.rs#L371

**Review by overvenus — APPROVED** [review]

File: components/raftstore/src/store/fsm/peer.rs [hunk 2]
```diff
@@ -2681,9 +2681,13 @@ where
         if self.fsm.peer.is_leader() {
             return;
         }
-        let mut resp = ExtraMessage::default();
+        let mut resp: ExtraMessage = ExtraMessage::default();
```
Comment (overvenus) [inline components/raftstore/src/store/fsm/peer.rs:2684]:
```suggestion
        let mut resp = ExtraMessage::default();
```
