### PR TITLE
storage: fix wrong commit_ts in Get/TableScan when latest write is Op_Lock

### LINKED ISSUE #19312: active active support
ref TiDB https://github.com/pingcap/tidb/issues/64281

### LINKED ISSUE #19393: The TiKV may return wrong `_tidb_commit_ts` for point-get and reverse-scan
See #19374 

This issue does not introduce any release bugs actually, because `_tidb_commit_ts` is used in feature branch only.

Problem Summary:

When `load_commit_ts=true` and a key has newer committed `Op_Lock` versions on top of the visible `Op_Put`, TiKV may return the lock commit_ts instead of the put commit_ts.

### PR DESCRIPTION
**Pull request by lcwangchao**
### What is changed and how it works?

Issue Number: Close #19312, Close #19393

What's Changed:

```commit-message
storage: fix wrong commit_ts in Get/TableScan when latest write is Op_Lock

Problem Summary:
- When `load_commit_ts=true` and a key has newer committed `Op_Lock` versions on top of the visible `Op_Put`, TiKV may return the lock commit_ts instead of the put commit_ts.

What changed:
- Fix `PointGetter` to return the commit_ts of the actual write version loaded by `last_change` shortcut, instead of the current cursor version.
- Fix backward scanner to only update `loaded_commit_ts` when selecting a `Put` version, avoiding ts overwrite from `Lock/Rollback` versions.

Tests:
- Add `test_point_get_load_commit_ts_with_top_lock_versions` in `point_getter.rs`.
- Add `test_load_commit_ts_with_top_lock_versions` in `scanner/backward.rs`.
- Verify existing related tests:
  - `test_point_get_load_commit_ts`
  - `test_scan_with_load_commit_ts`
```

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [ ] Need to cherry-pick to the release branch

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note

```release-note
Fix wrong commit_ts returned by Get and TableScan when `load_commit_ts` is enabled and newer `Op_Lock` versions exist above the latest `Op_Put`.
```

### CODE REVIEW

File: src/storage/mvcc/reader/scanner/backward.rs [hunk 1]
```diff
@@ -370,9 +370,6 @@ impl<S: Snapshot> BackwardKvScanner<S> {
                 ));
                 Key::decode_ts_from(current_key)?
             };
-            if self.cfg.load_commit_ts {
-                loaded_commit_ts = Some(current_ts);
-            }
             if current_ts <= last_checked_commit_ts {
                 // We reach the last handled key
                 return self.handle_last_version(last_version, user_key, loaded_commit_ts);
```
Comment (Connor1996) [inline src/storage/mvcc/reader/scanner/backward.rs:375]: What if it hits this branch, the `loaded_commit_ts` is not updated

Comment (lcwangchao) [reply src/storage/mvcc/reader/scanner/backward.rs:375]: Good question. In this branch we return `last_version` (captured during the initial `prev()` loop), not the `write` at `current_ts`. `loaded_commit_ts` is updated together with `last_version` (only for PUT/DELETE), so it already matches what we return here. Not updating it for LOCK/ROLLBACK is intentional to avoid the original bug where commit_ts could be taken from a newer LOCK. Added `test_load_commit_ts_with_top_lock_versions` to cover the case (many committed LOCKs on top of a visible PUT) and it asserts the returned commit_ts comes from the PUT.

**Review by cfzjywxk — APPROVED** [review]
