### PR TITLE
raftstore: respond gc peer immediately if region state not found

### LINKED ISSUE #15074: [Dynamic Region] TiFlash proxy crash for failed to get regions state
## Bug Report

Mirrors https://github.com/pingcap/tiflash/issues/7727

### PR DESCRIPTION
**Pull request by overvenus**
### What is changed and how it works?

Issue Number: close #15074
ref pingcap/tiflash#7727

What's Changed:

```commit-message
A peer may never be created if its parent peer skips split by applying a new snapshot.
```
So tikv should respond gc peer immediately if region state not found.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Integration test
TODO

### Release note 

```release-note
None
```
No need release note for TiKV.

Release note for TiFlash:

```
Fix an issue that TiFlash may panic if removing a peer that has not being created.
```

### CODE REVIEW

File: components/raftstore/src/store/fsm/life.rs [hunk 1]
```diff
@@ -68,12 +69,17 @@ pub fn handle_tombstone_message_on_learner<EK: KvEngine>(
...
-            e
-        ),
+        e => {
+            warn!(
+                "[store {}] failed to get regions state of {:?}: {:?}",
+                store_id,
+                msg.get_region_id(),
+                e
+            );
+            // A peer may never be created if its parent peer skips split by
```
Comment (tonyxuqqi) [inline components/raftstore/src/store/fsm/life.rs:79]: > // A peer may never be created if its parent peer skips split by

Do you mean the peer has not applied the snapshot and thus no region_state_key.  But the peer object itself is created otherwise it won't go to this path.

**Review by tonyxuqqi — APPROVED** [review]

File: components/raftstore/src/store/fsm/life.rs (hunk 1 above)
Comment (SpadeA-Tang) [reply components/raftstore/src/store/fsm/life.rs:79]: This is not the path of PeerFsmDelegate but StoreFsmDelegate.

File: tests/integrations/raftstore/test_life.rs [hunk 2]
```diff
@@ -124,3 +139,98 @@ fn test_gc_peer_tiflash_engine() {
...
+    check_peer.set_check_peer(new_learner_peer(2, 4));
+    check_peer.set_check_region_epoch(epoch.clone());
+
+    cluster.sim.wl().send_raft_msg(msg).unwrap();
+    let gc_resp = rx.recv_timeout(Duration::from_secs(5)).unwrap();
+    assert_eq!(gc_resp.get_region_id(), region_id);
+    assert_eq!(*gc_resp.get_from_peer(), new_learner_peer(2, 4));
+
+    // GC a peer that has been removed before creation.
+    let mut msg = RaftMessage::default();
```
Comment (SpadeA-Tang) [inline tests/integrations/raftstore/test_life.rs:218]: Is line218-line235 duplicate with line165-line182.

**Review by SpadeA-Tang — APPROVED** [review]
REST LGTM.

**Comment by nkg-** [comment]
Can this be cherrypicked to release6.5. https://github.com/tikv/tikv/pull/16505/files has a dependency on it. Particularly wait_peer_state function, added in the unit test.
