### PR TITLE
raftstore: Do not print error log for "region not exist but not tombstone"

### LINKED ISSUE #13002: Do not print log in error level for "region not exist but not tombstone"
## Development Task

Sometimes when add-peer runs slowly occasionally after a region split, a message from leader may arrive before finishing adding peer. In this case, an error complaining about "region not exist but not tombstone" will be produced:

https://github.com/tikv/tikv/blob/5c941586f5163ca9dbb82a0d14e7f02b09732181/components/raftstore/src/store/fsm/store.rs#L1743-L1747

And then it will cause an error log here:

https://github.com/tikv/tikv/blob/5c941586f5163ca9dbb82a0d14e7f02b09732181/components/raftstore/src/store/fsm/store.rs#L698-L701

However, this case is usually considered normal, and the logs in error level looks like something went wrong and may confuse the user (especially considering that some user may want to put the error log to their alert system).

It would be better if we can avoid printing error log for this kind of error. Looks like we'd better avoid using `box_err` here and define a specific kind of error for it.

### PR DESCRIPTION
**Pull request by MyonKeminta**
Signed-off-by: MyonKeminta <MyonKeminta@users.noreply.github.com>

### What is changed and how it works?

Issue Number: Close #13002 

What's Changed:

```commit-message
Avoid printing the log about "region not exist but not tombstone" in error level since it may happen in normal cases and confuse users.
```

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

\-

Side effects

\-

### Release note 

```release-note
None
```

### CODE REVIEW

File: components/raftstore/src/store/fsm/store.rs [hunk 1]
```diff
@@ -708,10 +708,20 @@ impl<'a, EK: KvEngine + 'static, ER: RaftEngine + 'static, T: Transport>
...
                     if let Err(e) = self.on_raft_message(msg) {
-                        error!(?e;
-                            "handle raft message failed";
-                            "store_id" => self.fsm.store.id,
-                        );
+                        if matches!(&e, Error::RegionNotRegistered { .. }) {
+                            // This may happen in normal cases when add-peer runs slowly
+                            // occasionally after a region split. Avoid printing error
+                            // log here, which may confuse users.
+                            warn!("handle raft message failed";
```
Comment (BusyJay) [inline components/raftstore/src/store/fsm/store.rs:715]: How about changing it to `info`?

Comment (MyonKeminta) [reply components/raftstore/src/store/fsm/store.rs:715]: ok

**Review by gengliqi — APPROVED** [review]

**Review by BusyJay — APPROVED** [review]
