### PR TITLE
sst_import: implement regional import mode for raftstore v2

### LINKED ISSUE #14916: [Dynamic Regions] Fast DDL generates lots of L0 files in MultiRocksDB
### What version of TiKV are you using?

nightly
### Steps to reproduce

With partitioned-raft-kv enabled, Use Fast DDL to create an new index and import data
### What did you expect?
The speed should be faster than default engine. 
### What did happened?
SST ingest failed because of too many L0 files leading to TiKV ServerBusy.
Below is the SST ingestion picked level in partitioned-raft-kv. All the L0 files are generated by SST ingestion. 
Screen Shot 2023-06-09 at 3 06 34 PM

There're 3 rounds of SST ingestion. Within each round, SST key range are non-overlapping. Between rounds, there's overlap. 
So in the first round, all SSTs are ingested to L6, which is expected. However, in second round, most of them are ingested to L5 and L0. 
Here's the example RocksDB instance's log.
[2780.txt](https://github.com/tikv/tikv/files/11710471/2780.txt)
Below is the example of a unexpected ingestion to L0.  As the log shows, when a L0 file is ingested, there's no other SST files except L6. So it should ingest to non L0 instead. 

> [2023/06/09 17:04:03.071 +00:00][5][INFO] [2780_112][db/external_sst_file_ingestion_job.cc:491] [AddFile] External SST file /var/lib/tikv/data/import/.clone/2935deae-09af-48d6-8b1d-51088ada353e_2780_959_173_write.sst was ingested in L0 with path /var/lib/tikv/data/tablets/2780_112/000624.sst (global_seqno=230)
> [2023/06/09 17:04:03.072 +00:00][5][INFO] [2780_112]EVENT_LOG_v1 {"time_micros": 1686330243071902, "event": "ingest_finished", "files_ingested": ["file", "/var/lib/tikv/data/tablets/2780_112/000624.sst", "level", 0], "lsm_state": [1, 0, 0, 0, 0, 0, 7]}

And from this log, we can know the base level is 6.
> [2023/06/09 17:09:04.913 +00:00][5][INFO] [2780_112](Original Log Time 2023/06/09-17:09:04.913248) [db/compaction/compaction_job.cc:965] [write] compacted to: base level 6 level multiplier 10.00 max bytes base 536870912 files[5 0 0 0 0 0 9] max score 1.25, MB/sec: 10.3 rd, 10.4 wr, level 6, files in(1, 2) out(1 +0 blob) MB in(0.8, 6.7 +0.0 blob) out(7.5 +0.0 blob), read-write-amplify(19.6) write-amplify(9.8) OK, records in: 29705, records dropped: 0 output_compression: ZSTD

Below is the SST ingestion picked level in raft-kv
Screen Shot 2023-06-09 at 3 20 23 PM

### PR DESCRIPTION
**Pull request by SpadeA-Tang**
### What is changed and how it works?

Issue Number: Close #14916 

What's Changed:

```commit-message
implement regional import mode for raftstore-v2.
```

### Related changes

https://github.com/pingcap/kvproto/pull/1138

### Check List 

Tests 

- Unit test
- Integration test

### Release note 

```release-note
None
```

### CODE REVIEW

File: src/import/sst_service.rs [hunk 1]
```diff
@@ -671,17 +706,40 @@ impl<E: Engine> ImportSst for ImportSstService<E> {
...
-            if let LocalTablets::Singleton(tablet) = &self.tablets {
-                match req.get_mode() {
+            match &self.tablets {
+                LocalTablets::Singleton(tablet) => match req.get_mode() {
                     SwitchMode::Normal => self.importer.enter_normal_mode(tablet.clone(), mf),
                     SwitchMode::Import => self.importer.enter_import_mode(tablet.clone(), mf),
+                },
+                LocalTablets::Registry(_) => {
+                    if req.get_mode() == SwitchMode::Import {
+                        if !self.importer.region_import_mode() {
```
Comment (tonyxuqqi) [inline src/import/sst_service.rs:716]: We should support client to call multiple enter import model with different key ranges.  So here when region_import_mode is true, it should continue to update the import mode regions by the key ranges.

File: src/import/sst_service.rs [hunk 2]
```diff
@@ -671,17 +706,40 @@ impl<E: Engine> ImportSst for ImportSstService<E> {
...
+                            let mut covered_regions = HashSet::new();
```
Comment (tonyxuqqi) [inline src/import/sst_service.rs:717]: should re-use the existing one in self.importer

File: components/sst_importer/src/import_mode.rs [hunk 3]
```diff
@@ -120,6 +131,29 @@ impl ImportModeSwitcher {
...
+    pub fn set_import_mode_regions(&self, import_mode_regions: HashSet<u64>) {
+        self.inner.lock().unwrap().import_mode_regions = Some(import_mode_regions);
+    }
+
+    pub fn clear_import_mode_regions(&self) {
+        self.inner.lock().unwrap().import_mode_regions.take();
+    }
+
+    // Should only be used in v2.
+    pub fn region_in_import_mode(&self, region_id: u64) -> bool {
```
Comment (tonyxuqqi) [inline components/sst_importer/src/import_mode.rs:149]: Check the self.ctx.importer.get_mode() in raftstore v1 and there're some logic may be ported to v2. 
For example, on_split_region_check_tick, it will skip if the region is under import mode. 
And for on_cleanup_import_sst, it's also used. We may need it in v2 as well.

File: components/raftstore-v2/src/operation/command/write/ingest.rs [hunk 4]
```diff
@@ -39,7 +39,7 @@ impl Store {
         ctx: &mut StoreContext<EK, ER, T>,
     ) -> Result<()> {
         let ssts = box_try!(ctx.sst_importer.list_ssts());
-        if ssts.is_empty() {
+        if ssts.is_empty() || ctx.sst_importer.regional_import_mode() {
```
Comment (tonyxuqqi) [inline components/raftstore-v2/src/operation/command/write/ingest.rs:42]: We should not block cleaning up SST of region A when region B is in import mode.

File: components/sst_importer/src/import_mode2.rs [hunk 5]
```diff
@@ -0,0 +1,302 @@
...
+        inner.next_check.insert(range, next_check);
+    }
+
+    pub fn clear_import_mode_regions_in_range(&self, range: KeyRange) {
+        let mut inner = self.inner.lock().unwrap();
+        let range = Range::from(range);
+        inner.clear_import_mode_regions_in_range(range);
+    }
+
+    pub fn regional_import_mode(&self) -> bool {
```
Comment (tonyxuqqi) [inline components/sst_importer/src/import_mode2.rs:147]: I think we should have region_id as the parameter to precisely know if the region is in import mode or not.

File: components/raftstore/src/store/fsm/peer.rs [hunk 6]
```diff
@@ -5724,7 +5724,9 @@ where
         // When Lightning or BR is importing data to TiKV, their ingest-request may fail
         // because of region-epoch not matched. So we hope TiKV do not check region size
         // and split region during importing.
-        if self.ctx.importer.get_mode() == SwitchMode::Import {
+        if self.ctx.importer.get_mode() == SwitchMode::Import
+            || self.ctx.importer.regional_import_mode()
```
Comment (tonyxuqqi) [inline components/raftstore/src/store/fsm/peer.rs:5728]: We should use region_in_import_mode instead.

File: components/raftstore-v2/src/operation/command/write/ingest.rs (hunk 4 above)
Comment (SpadeA-Tang) [reply components/raftstore-v2/src/operation/command/write/ingest.rs:42]: 1. region infos in sst_importer may not be update to date.
2. the regions may be created soon but now in this store now, but the ssts are uploaded in advance.
3. there's a background worker to check timeout and all regions will not be import mode eventually at some time.

File: components/raftstore/src/store/fsm/peer.rs (hunk 6 above)
Comment (SpadeA-Tang) [reply components/raftstore/src/store/fsm/peer.rs:5728]: The reason why I use this is the same as the reply above.

File: components/raftstore-v2/src/operation/command/write/ingest.rs (hunk 4 above)
Comment (tonyxuqqi) [reply components/raftstore-v2/src/operation/command/write/ingest.rs:42]: Then I think we need to use region's key range to check if the region should be in import mode or not. So it does not matter the region split/merge.

**Review by lance6716 — COMMENTED** [review]
rest lgtm

File: components/raftstore-v2/src/operation/command/write/ingest.rs [hunk 7]
```diff
@@ -42,18 +43,30 @@ impl Store {
...
+
         let mut region_ssts: HashMap<_, Vec<_>> = HashMap::default();
         for sst in ssts {
             region_ssts
                 .entry(sst.get_region_id())
                 .or_default()
                 .push(sst);
         }
+
+        let ranges = ctx.sst_importer.ranges_in_import();
```
[the remark this answers is not in the document]
Comment (SpadeA-Tang) [reply components/raftstore-v2/src/operation/command/write/ingest.rs:55]: It's already the logic of v1 where clean up is not performed for regions unexisted if the current mode is import.
The reason for it is sometimes sst may be uploaded to a store even before the region is transfered to the store, this piece of code avoid deleting these ssts.

File: components/sst_importer/src/sst_importer.rs [hunk 8]
```diff
@@ -171,8 +174,13 @@ impl SstImporter {
         root: P,
         key_manager: Option<Arc<DataKeyManager>>,
         api_version: ApiVersion,
+        multi_rocksdb: bool,
```
Comment (overvenus) [inline components/sst_importer/src/sst_importer.rs:177]:
```suggestion
        raft_kv_v2: bool,
```

File: src/import/sst_service.rs [hunk 9]
```diff
@@ -672,17 +716,37 @@ impl<E: Engine> ImportSst for ImportSstService<E> {
...
+                    if req.get_mode() == SwitchMode::Import {
+                        if req.has_range() {
+                            let range = req.take_range();
+                            self.importer.range_enter_import_mode(range);
+                            Ok(true)
+                        } else {
+                            Err(sst_importer::Error::Engine(
+                                "partitioned-raft-kv only support switch mode with range set"
+                                    .into(),
+                            ))
```
[the remark this answers is not in the document]
Comment (SpadeA-Tang) [reply src/import/sst_service.rs:734]: Before this PR, v2 does not support import mode, so it does not support old lightning before.

File: Cargo.toml [hunk 10]
```diff
@@ -200,8 +200,8 @@ procinfo = { git = "https://github.com/tikv/procinfo-rs", rev = "6599eb9dca74229
 # When you modify TiKV cooperatively with kvproto, this will be useful to submit the PR to TiKV and the PR to
 # kvproto at the same time.
 # After the PR to kvproto is merged, remember to comment this out and run `cargo update -p kvproto`.
-# [patch.'https://github.com/pingcap/kvproto']
-# kvproto = { git = "https://github.com/your_github_id/kvproto", branch = "your_branch" }
+[patch.'https://github.com/pingcap/kvproto']
+kvproto = { git = "https://github.com/SpadeA-Tang/kvproto", branch = "import-sst" }
```
[the remark this answers is not in the document]
Comment (SpadeA-Tang) [reply Cargo.toml:204]: ok

File: components/sst_importer/src/import_mode2.rs [hunk 11]
```diff
@@ -0,0 +1,262 @@
...
+
+fn region_overlap_with_range(range: &HashRange, region: &Region) -> bool {
+    (region.end_key.is_empty() || range.start_key < region.end_key)
+        && (range.end_key.is_empty() || region.start_key < range.end_key)
+}
+
+pub fn range_overlaps(range1: &HashRange, range2: &Range) -> bool {
+    (range2.end.is_empty() || range1.start_key < range2.end)
+        && (range1.end_key.is_empty() || range2.start < range1.end_key)
+}
```
[the remark this answers is not in the document]
Comment (SpadeA-Tang) [reply components/sst_importer/src/import_mode2.rs:147]: Fine.

File: src/import/sst_service.rs (hunk 9 above)
[the remark this answers is not in the document]
Comment (tonyxuqqi) [reply src/import/sst_service.rs:734]: I think it's better to fail the request. Otherwise a client mistake (not specify a key range) will make import mode applied in all regions.

**Review by tonyxuqqi — APPROVED** [review]

**Review by overvenus — COMMENTED** [review]
Rest LGTM

File: components/raftstore-v2/src/operation/command/write/ingest.rs [hunk 12]
```diff
@@ -42,18 +43,30 @@ impl Store {
...
         for (region_id, ssts) in region_ssts {
             if let Err(TrySendError::Disconnected(msg)) = ctx.router.send(region_id, PeerMsg::CleanupImportSst(ssts.into()))
                 && !ctx.router.is_shutdown() {
-                let PeerMsg::CleanupImportSst(ssts) = msg else { unreachable!() };
-                let _ = ctx.schedulers.tablet.schedule(tablet::Task::CleanupImportSst(ssts));
+                let PeerMsg::CleanupImportSst( ssts) = msg else { unreachable!() };
+                let mut ssts = ssts.into_vec();
+                ssts.retain(|sst| {
+                    for range in &ranges {
```
[the remark this answers is not in the document]
Comment (SpadeA-Tang) [reply components/raftstore-v2/src/operation/command/write/ingest.rs:62]: I think it may be fine as it only does this for region not existed in the store.

**Review by overvenus — APPROVED** [review]

File: src/import/sst_service.rs (hunk 9 above)
[the remark this answers is not in the document]
Comment (benmaoer) [reply src/import/sst_service.rs:734]: It's not a breaking change. After discussion, the conclusion:
1.  Lightning (prior to v7.3) does not support to import data to Partitioned Raft KV engine. 
2.  Lightning (v7.3 and above) supports import data to both Partitioned Raft KV engine and Single RocksDB engines.  Add a new parameter to defined the key range of the table that user are importing data.  The key range is prefix by table_id. If importing multiple tables, multiple key range parameters can be passed.
3. TiKV supports both interfaces with and without the key range parameter.
