### PR TITLE
resolved_ts: re-register region if memory quota exceeded 

### LINKED ISSUE #14864: Resolved ts in stale read may cause TiKV OOM
## Bug Report

Stale read is enabled by default, and it maintains resolved ts(a btree map) for tracking every lock written by leaders.
If there is a large txn, the map may cause TiKV OOM.

To prevent OOM, we can use a memory quota to keep the total memory consumption under control. If a region is tracking too many locks and exceeds the quota, we can deregister its delegate in the stale read component, free its memory, and then register it again after a certain backoff period.

### What version of TiKV are you using?

\> 5.1.0

### Steps to reproduce

Run a large txn that is much greater than TiKV memory size.

### What did you expect?

No OOM.

### What did happened?

OOM.

### PR DESCRIPTION
**Pull request by overvenus**
### What is changed and how it works?

Issue Number: Close #14864

What's Changed:

```commit-message
Fix resolved ts OOM caused by Resolver tracking large txns. `ObserveRegion` is
deregistered if it exceeds memory quota. It may cause higher CPU usage because
of scanning locks, but it's better than OOM.
```

Running a transaction that updates 100,000,000 lines.
Left: master branch, right: this PR.

image

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Integration test

Side effects

- Performance regression
    - Consumes more CPU

### Release note 

```release-note
Fix an OOM issue that is caused by stale read tracking large transactions. 
```

### CODE REVIEW

File: components/resolved_ts/src/resolver.rs [hunk 1]
```diff
@@ -142,7 +172,7 @@ impl Resolver {
             start_ts,
             self.region_id
         );
-        let bytes = key.as_slice().heap_size();
+        let bytes = self.lock_heap_size(&key);
```
Comment (3pointer) [inline components/resolved_ts/src/resolver.rs:175]: shall we calculate douple size here since `approximate_heap_bytes` has calculate both `locks_by_key` and `lock_ts_heap`?

**Review by tonyxuqqi — APPROVED** [review]

File: components/resolved_ts/src/resolver.rs [hunk 2]
```diff
@@ -103,9 +113,23 @@ impl Resolver {
...
+            return 0;
+        }
+
+        const SAMPLE_COUNT: usize = 32;
+        let mut key_count = 0;
+        let mut key_bytes = 0;
+        for key in self.locks_by_key.keys() {
+            key_count += 1;
+            key_bytes += key.len();
+            if key_count >= SAMPLE_COUNT {
```
[the remark this answers is not in the document]
Comment (overvenus) [reply components/resolved_ts/src/resolver.rs:128]: Good suggestion!

File: components/resolved_ts/src/resolver.rs (hunk 1 above)
Comment (overvenus) [reply components/resolved_ts/src/resolver.rs:175]: The majority of memory is consumed by keys, `locks_by_key` and `lock_ts_heap` shares the same `Arc<[u8]>`, so I think `lock_ts_heap` is negligible. Also, it's hard to track accurate memory use of `lock_ts_heap` as it's a `BTreeMap<TimeStamp, HashSet<Arc<[u8]>>>`, a timestamp may have many keys.

**Review by 3pointer — APPROVED** [review]
