### PR TITLE
import: write RPC will check region epoch before continue

### LINKED ISSUE #15003: tikv panic when tikv exit the import mode but import process is still not stopped during "import into" command is cancelled
### What version of TiKV are you using?
master

### Steps to reproduce
1. set global tidb_enable_dist_task=off;
2. IMPORT INTO big.items  FROM "s3://tmp/9T-csv/big.items.*.csv?access-key=minioadmin&secret-access-key=minioadmin&endpoint=http%3a%2f%2f10.2.12.100%3a32762&force-path-style=true" with thread=16,detached;
3. cancel this job 
4. clear table of big.items
5. set global tidb_enable_dist_task=on;
6. execute import into command again

### What did you expect?
import job can be successfully
### What did happened?
```
[2023/06/26 03:25:03.580 +00:00] [FATAL] [[lib.rs:497](http://lib.rs:497/)] ["[region 15563512] 15563513 ingest uuid: 5ACC4E816AC84B9682AA3E6985C3B924 range { start: 7480000000000000FF665F698000000000FF000008014A6C3179FF6F616362FF456879FF7555526174FF517AFF7667316B5654FF64FF6646714B633253FFFF44397650414D446DFFFF436D7635466E55FF66FF32636C364249FF5775FF5042516472FF386642FF38555145FF57317630FF594A58FF56346D6146FF5738FF3536436B4D61FF53FF326E4568465470FFFF64726C6C564F4949FFFF354C3239316F54FF36FF73314B345246FF344AFF64704D7045FF376A52FF3252396CFF556F4A5AFF69646FFF4E76575546FF6979FF6F507A5A4C37FF33FF71724451683566FFFF5749795373574B48FFFF77566E6B35474BFF68FF33396E494875FF3958FF625A6B4769FF386955FF664B676AFF666D5875FF525049FF536261477AFF7773FF637A39506C63FF4AFF4B6D396C554143FFFF4955587951713571FFFF6A516D485A5557FF4AFF767230674865FF7243FF4767573468FF687234FF687A324CFF31776C47FF555471FF4C43436D30FF304BFF465379454878FF67FF3961674E486D68FFFF4C415A7633645749FFFF63524D6E464343FF66FF6C6567304536FF5856FF763853786DFF377134FF32586A54FF76446171FF655964FF4D48746D78FF314AFF53437857547AFF56FF6944776D654737FFFF6847485166333231FFFF76346B33494D68FF55FF3651726D3346FF6457FF3248587442FF4F6A6BFF784C6457FF77796D46FF704C36FF63714F4476FF7177FF645772693275FF31FF4D5A4967746F36FFFF516B70676A637445FFFF7144446C6C4149FF33FF72584E67434CFF7438FF3251504632FF745437FF63386A41FF6158434DFF4D6E69FF4935307259FF6236FF645970573658FF31FF75697A7A427352FFFF47315453755A3757FFFF6D334A30615934FF6CFF45646466455AFF4972FF6661324C48FF62526FFF4B357438FF54666145FF59396AFF5444774A35FF7233FF68654B556E78FF57FF514D30664D6664FFFF6B4F39446B435774FFFF4765796968356EFF4EFF79466D5A446CFF567AFF6575564A44FF4A556EFF5854544CFF546E4C4FFF667143FF4644535849FF3167FF746C357A754BFF4CFF707A3468715837FFFF6731526368445273FFFF6B7870524E3137FF65FF4E5041333547FF6D38FF5A7272494FFF516D66FF32646C6AFF49446D71FF554C75FF4E43756775FF5739FF61425568586AFF58FF567773364A5143FFFF6477513754594E4EFFFF574B7551657947FF42FF75784D5A4D42FF5579FF3647683356FF327867FF71335468FF41303168FF6F6337FF7945486974FF4B75FF327847396F45FF34FF39543550693257FFFF52687A314A484C31FFFF667332524B544AFF6AFF5A51766A4E44FF7441FF396577466BFF787968FF6A493875FF66385241FF386342FF4432516167FF6A75FF353474734838FF62FF36433856474559FFFF0000000000000000FFF7016E6F64653054FF3234FF497350516FFF4F556CFF4E305059FF61795973FF637578FF524F6E4E79FF4F73FF616273776353FF56FF354356346B6D53FFFF3668536551596743FFFF7171677464744BFF6EFF4D5346703047FF695AFF4948735672FF715536FF4443524FFF72494F4EFF673248FF38324C5A70FF5747FF446B76334F55FF39FF776F3571636242FFFF4247336974667332FFFF306F6561745056FF56FF5A7A344B7569FF3130FF4453704435FF4A6C6DFF4D553642FF37644D6FFF6D737AFF5468674F61FF5754FF55506A326264FF79FF3034674D536C57FFFF7272304279374E46FFFF35514D46523666FF64FF775641466A64FF4E4DFF7172434A5AFF627165FF616F3247FF5A343871FF676A45FF4473564F66FF4C00FF000000000000F800FE end: 7480000000000000FF665F698000000000FF000008014A6E4D66FF34574B4EFF746E4AFF3078783263FF4850FF6A416778786CFF47FF426E456A527279FFFF3034353743715247FFFF71555438506E59FF49FF576736306B77FF574FFF6A61796959FF555236FF426F4643FF664C4875FF6E434FFF6D62794878FF304BFF544442704B67FF4BFF4C70504A69645AFFFF51636E6E414D5746FFFF3152587454694CFF6BFF69757341344FFF5036FF3245497665FF33366BFF6F4E5072FF336A5668FF7A7745FF7150556B66FF4579FF784F71496458FF4EFF613979546A7A4DFFFF454662456E394B30FFFF73736272447439FF4AFF786E3771556DFF7246FF3877325744FF4A326FFF4C415943FF6478566DFF327867FF4A38723378FF5367FF64497230624FFF49FF6637484C554863FFFF5A78594A57434843FFFF70395050686F4AFF6EFF74656D417971FF3850FF526D6E6F7AFF425258FF6E545331FF59706542FF487356FF3344555967FF4B62FF57644B7A496EFF30FF6372714C53354CFFFF6851515A5A796B6AFFFF78486C4D6F5A51FF57FF685A5870486DFF594DFF50585A5A62FF325346FF6F59496AFF73714F48FF634267FF56496E5347FF4546FF684B514E5144FF47FF4C424930614A72FFFF5A674C6D7136416EFFFF506F6444346935FF68FF334C79786E4AFF3365FF5342525551FF335379FF39495479FF566A5856FF386C48FF3350445365FF7A50FF43726D4C576BFF4DFF4B6B7067305778FFFF6D6A6C7534634856FFFF3976675051464BFF43FF34354C616B30FF5148FF776B436E45FF47546FFF61427432FF6B6B4342FF59714CFF4E7A4A736DFF514DFF50726D6E7432FF32FF325754776A5A6CFFFF4C4531596B6B4B6CFFFF4E616
```

### PR DESCRIPTION
**Pull request by lance6716**
### What is changed and how it works?

Issue Number: Close #15003

What's Changed:

```commit-message
```

see https://github.com/tikv/tikv/issues/15003#issuecomment-1606957339

server side (this PR): 
- for import sst service, write RPC will only continue when the local region epoch is same as the epoch in request
- for cleanup logic, when the region is not found or region epoch is changed, we can delete the sst file

client side (will open it in TiDB repo):
- for write RPC, retry from write for the error message "please retry write later", and retry from rescan region for the error message "please rescan region later"

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test

in lightning (import client), manually increase the epoch version and check the log

```
[2023/10/16 16:41:42.557 +08:00] [WARN] [local.go:1429] ["meet retryable error when writing to TiKV"] [error="peer 370, store 2, region 369, epoch conf_ver:5 version:66 : rpc error: code = Unknown desc = Engine(\"request region 369 is ahead of local region, local epoch conf_ver: 5 version: 65, request epoch conf_ver: 5 version: 66, please retry write later\")"] ["job stage"=regionScanned]
```

manuall decrease the epoch version and check the log

```
[2023/10/16 16:52:12.086 +08:00] [WARN] [local.go:1429] ["meet retryable error when writing to TiKV"] [error="peer 385, store 1, region 384, epoch conf_ver:5 version:64 , when close write stream: rpc error: code = Unknown desc = Engine(\"request region 384 is staler than local region, local epoch conf_ver: 5 version: 65, request epoch conf_ver: 5 version: 64, please rescan region later\")"] ["job stage"=regionScanned]
```

Side effects

- Performance regression
    - client will wait the slowest peer in a raft group
- Breaking backward compatibility
    - client should adjust the protocol about handle error message

### Release note 

```release-note
None
```

### CODE REVIEW

File: src/import/sst_service.rs [hunk 1]
```diff
@@ -582,6 +587,75 @@ impl<E: Engine> ImportSstService<E> {
...
+    epoch: &RegionEpoch,
+    region_info_accessor: Arc<dyn RegionInfoProvider>,
+) -> Result<()> {
+    let (tx2, rx2) = crossbeam::channel::bounded(1);
+    region_info_accessor
+        .find_region_by_id(
+            region_id,
+            Box::new(move |item| {
+                tx2.send(item)
+                    .expect("BUG: failed to send to newly created channel.");
```
Comment (Connor1996) [inline src/import/sst_service.rs:601]:
```suggestion
                    .unwrap();
```

**Review by Connor1996 — APPROVED** [review]
LGTM

**Comment by lance6716** [comment]
/hold

seems we can make use of "remove peer" logic to delete SST

**Comment by lance6716** [comment]
close due to we found another way to fix. We should be able to delete stale SST files when destroy region. The new way does not require any change at client side (lightning).

https://github.com/tikv/tikv/issues/15053

File: components/raftstore/src/store/worker/cleanup_sst.rs [hunk 2]
```diff
@@ -31,10 +27,10 @@ where
     EK: KvEngine,
     S: StoreRouter<EK>,
 {
-    store_id: u64,
-    store_router: S,
+    _store_id: u64,
+    _store_router: S,
```
Comment (overvenus) [inline components/raftstore/src/store/worker/cleanup_sst.rs:31]: Why not just remove them?

File: src/import/sst_service.rs [hunk 3]
```diff
@@ -618,6 +623,74 @@ impl<E: Engine> ImportSstService<E> {
     }
 }
 
+fn check_local_region_stale(
+    region_id: u64,
+    epoch: &RegionEpoch,
+    region_info_accessor: Arc<dyn RegionInfoProvider>,
+) -> Result<()> {
+    let (tx2, rx2) = crossbeam::channel::bounded(1);
```
Comment (overvenus) [inline src/import/sst_service.rs:631]: You can use `paired_future_callback` to make the function async, it can improve performance I think.

File: src/import/sst_service.rs [hunk 4]
```diff
@@ -618,6 +623,74 @@ impl<E: Engine> ImportSstService<E> {
...
+        )
+    })?;
+    match result {
+        Some(local_region_info) => {
+            let local_region_epoch = local_region_info.region.region_epoch.unwrap();
+
+            // TODO(lance6717): we should only need to check conf_ver because we require all
+            // peers have SST on the disk, and does not care about which one is
+            // leader. But since check_sst_for_ingestion also checks epoch version,
+            // we just keep it here for now.
```
Comment (overvenus) [inline src/import/sst_service.rs:659]: I think it must check version too, because region split does not change conf_version.

File: src/import/sst_service.rs [hunk 5]
```diff
@@ -656,7 +730,15 @@ macro_rules! impl_write {
                         }
                         _ => return Err(Error::InvalidChunk),
                     };
+                    // wait the region epoch on this TiKV to catch up with the epoch
+                    // in request, which comes from PD and represents the majority
+                    // peers' status.
```
Comment (overvenus) [inline src/import/sst_service.rs:735]: What if a peer is more up-to-date than the request (peer.region_epoch > request.region_epoch)?

File: src/import/sst_service.rs (hunk 4 above)
Comment (lance6716) [reply src/import/sst_service.rs:659]: The function is_epoch_stale also checked epoch.version.

File: components/raftstore/src/store/fsm/store.rs [hunk 6]
```diff
@@ -2806,8 +2765,10 @@ impl<'a, EK: KvEngine, ER: RaftEngine, T: Transport> StoreFsmDelegate<'a, EK, ER
                         delete_ssts.push(sst);
                     }
                 } else {
-                    // If the peer doesn't exist, we need to validate the SST through PD.
-                    validate_ssts.push(sst);
+                    // The write RPC of import sst service have make sure the region do exist at the
+                    // write time, and now the region is not found, sst can be
+                    // deleted because it won't be used by ingest in future.
```
Comment (tonyxuqqi) [inline components/raftstore/src/store/fsm/store.rs:2770]: How about the upgrade scenario when the SST is uploaded without this change, and then the TiKV is upgraded to this version.

**Comment by tonyxuqqi** [comment]
Except the upgrade scenario,  others are LGTM.

File: components/raftstore/src/store/fsm/store.rs (hunk 6 above)
Comment (lance6716) [reply components/raftstore/src/store/fsm/store.rs:2770]: Currently I don't know how to solve it 😂 For non-technical solution, it should be OK to forbid importing when upgrading. I'll think about it later.

Comment (tonyxuqqi) [reply components/raftstore/src/store/fsm/store.rs:2770]: We may need to do some mark in this PR for SSTs uploaded with this change.
And if there's no mark for that file, it means the file is uploaded before this change.

File: components/sst_importer/src/import_file.rs [hunk 7]
```diff
@@ -458,20 +458,33 @@ impl ImportDir {
...
+pub const API_VERSION_2: i32 = 2;
+
+/// sst_meta_to_path will encode the filepath with default api version (current
+/// is 2). So when the SstMeta is created in old version of TiKV and filepath
+/// will not correspond to the real file, in the deletion logic we can't remove
+/// these files.
 pub fn sst_meta_to_path(meta: &SstMeta) -> Result<PathBuf> {
     Ok(PathBuf::from(format!(
-        "{}_{}_{}_{}_{}{}",
+        "{}_{}_{}_{}_{}_{}{}",
```
Comment (tonyxuqqi) [inline components/sst_importer/src/import_file.rs:471]: Does it mean this SST cannot be parsed by older version. 
It's fine to me, but need to document somewhere later that it's not compatible with older version.

**Review by tonyxuqqi — APPROVED** [review]

File: components/sst_importer/src/import_file.rs (hunk 7 above)
Comment (lance6716) [reply components/sst_importer/src/import_file.rs:471]: In the old version of `parse_meta_from_path`, it will only use the first 5 fields after split the string with `_`, so the new version should be able to be ignored.
