### PR TITLE
raftstore-v2: support flashback region

### LINKED ISSUE #14684: [Dynamic Regions] flashback is not working in raftstore v2
## Bug Report

Flashback is not working in raftstore v2

### What version of TiKV are you using?

v7.0.0

### Steps to reproduce

Enable raftstore v2 and run stale raed SQL in tidb.

### What did you expect?

Stale read success.

### What did happened?

Stale read fails.

### PR DESCRIPTION
**Pull request by overvenus**
### What is changed and how it works?

Issue Number: Close #14684

What's Changed:

```commit-message
raftstore-v2: support flashback region
```

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test

### Release note 

```release-note
None
```

### CODE REVIEW

File: components/raftstore-v2/src/raft/peer.rs [hunk 1]
```diff
@@ -261,11 +261,12 @@ impl<EK: KvEngine, ER: RaftEngine> Peer<EK, ER> {
             self.leader_lease.expire_remote_lease();
         }
 
-        let mut region_state = RegionLocalState::default();
-        region_state.set_region(region.clone());
-        region_state.set_tablet_index(tablet_index);
-        region_state.set_state(self.storage().region_state().get_state());
-        self.storage_mut().set_region_state(region_state);
+        self.storage_mut()
```
Comment (overvenus) [inline components/raftstore-v2/src/raft/peer.rs:264]: This is a bug fix, I will add tests in a later PR.

Comment (overvenus) [reply components/raftstore-v2/src/raft/peer.rs:264]: It's fixed by https://github.com/tikv/tikv/pull/14690

File: components/raftstore-v2/src/operation/command/admin/flashback.rs [hunk 2]
```diff
@@ -0,0 +1,100 @@
...
+                res.region_state.get_tablet_index(),
+            );
+        }
+
+        self.state_changes_mut()
+            .put_region_state(region_id, res.index, &res.region_state)
+            .unwrap();
+        self.set_has_extra_write();
+        // Let the leader lease to None to ensure that local reads are not
+        // executed. self.leader_lease_mut().expire_remote_lease();
```
Comment (JmPotato) [inline components/raftstore-v2/src/operation/command/admin/flashback.rs:98]:
```suggestion
        // executed.
        self.leader_lease_mut().expire_remote_lease();
```

Comment (overvenus) [reply components/raftstore-v2/src/operation/command/admin/flashback.rs:98]: Forget cleanup, in v2, only local reader can serve read requests, we can not expire lease.

File: components/raftstore-v2/src/operation/command/admin/flashback.rs [hunk 3]
```diff
@@ -0,0 +1,100 @@
...
+
+use super::AdminCmdResult;
+use crate::{
+    batch::StoreContext,
+    fsm::ApplyResReporter,
+    raft::{Apply, Peer},
+};
+
+#[derive(Debug)]
+pub struct SetFlashbackState {
```
Comment (tonyxuqqi) [inline components/raftstore-v2/src/operation/command/admin/flashback.rs:20]: Minor: struct name typically should not start with a Verb, can be renamed as FlashbackSetState. To be FlashbackState seems better.

File: components/raftstore-v2/src/operation/command/admin/flashback.rs [hunk 4]
```diff
@@ -0,0 +1,100 @@
...
+    }
+}
+
+impl<EK: KvEngine, R: ApplyResReporter> Apply<EK, R> {
+    pub fn apply_flashback(
+        &mut self,
+        index: u64,
+        req: &AdminRequest,
+    ) -> Result<(AdminResponse, AdminCmdResult)> {
+        let is_in_flashback = req.get_cmd_type() == AdminCmdType::PrepareFlashback;
```
Comment (tonyxuqqi) [inline components/raftstore-v2/src/operation/command/admin/flashback.rs:42]: Since the fn is apply_flashback,  req.get_cmd_type() must be AdminCmdType::PrepareFlashback. 
It can use an assert to assure it.

File: components/raftstore-v2/src/operation/command/admin/flashback.rs (hunk 2 above)
Comment (tonyxuqqi) [reply components/raftstore-v2/src/operation/command/admin/flashback.rs:98]: > Forget cleanup, in v2, only local reader can serve read requests, we can not expire lease.

We still can expire lease in v2. Otherwise the read may return incorrect data after tablet split

**Review by tonyxuqqi — COMMENTED** [review]
Overall LGTM, except the one around lease expire.

File: components/raftstore-v2/src/operation/command/admin/flashback.rs [hunk 5]
```diff
@@ -0,0 +1,100 @@
...
+        // Modify the region meta in memory.
+        let region = self.region_state_mut().mut_region();
+        region.set_is_in_flashback(is_in_flashback);
+        region.set_flashback_start_ts(req.get_prepare_flashback().get_start_ts());
```
Comment (JmPotato) [inline components/raftstore-v2/src/operation/command/admin/flashback.rs:46]: Do we need to only set it when it's in the flashback?

**Review by JmPotato — APPROVED** [review]
The rest LGTM.

File: components/raftstore-v2/src/operation/command/admin/flashback.rs (hunk 5 above)
Comment (overvenus) [reply components/raftstore-v2/src/operation/command/admin/flashback.rs:46]: Yes, that's clearer. I will address your comment.

File: components/raftstore-v2/src/operation/command/admin/mod.rs [hunk 6]
```diff
@@ -264,7 +267,10 @@ impl<EK: KvEngine, ER: RaftEngine> Peer<EK, ER> {
                 }
                 AdminCmdType::PrepareMerge => self.propose_prepare_merge(ctx, req),
                 AdminCmdType::CommitMerge => self.propose_commit_merge(ctx, req),
-                _ => unimplemented!(),
+                AdminCmdType::PrepareFlashback | AdminCmdType::FinishFlashback => {
+                    self.propose_flashback(ctx, req)
```
Comment (HuSharp) [inline components/raftstore-v2/src/operation/command/admin/mod.rs:271]: Maybe can make the `UpdateGcPeer` propose behavior consistently with here?

**Review by HuSharp — APPROVED** [review]
rest LGTM!

File: components/raftstore-v2/src/operation/command/admin/flashback.rs [hunk 7]
```diff
@@ -0,0 +1,108 @@
...
+
+        match req.get_cmd_type() {
+            AdminCmdType::PrepareFlashback => {
+                PEER_ADMIN_CMD_COUNTER.prepare_flashback.success.inc();
+            }
+            AdminCmdType::FinishFlashback => {
+                PEER_ADMIN_CMD_COUNTER.finish_flashback.success.inc();
+            }
+            _ => unreachable!(),
+        }
```
Comment (tonyxuqqi) [inline components/raftstore-v2/src/operation/command/admin/flashback.rs:60]: The code can be polished by using match req.get_cmd_type() to organizing the whole logic. 
Now it's using req.get_cmd_type() == AdminCmdType::PrepareFlashback initially and then have a match later.

Comment (tonyxuqqi) [reply components/raftstore-v2/src/operation/command/admin/flashback.rs:60]:
```suggestion
        let region = self.region_state_mut().mut_region();
         match req.get_cmd_type() {
            AdminCmdType::PrepareFlashback => {
                PEER_ADMIN_CMD_COUNTER.prepare_flashback.success.inc();
                region.set_is_in_flashback(true);
                region.set_flashback_start_ts(req.get_prepare_flashback().get_start_ts());
            }
            AdminCmdType::FinishFlashback => {
                PEER_ADMIN_CMD_COUNTER.finish_flashback.success.inc();
                region.set_is_in_flashback(false);
                region.clear_flashback_start_ts();
            }
            _ => unreachable!(),
        }
```

File: src/server/raftkv2/mod.rs [hunk 8]
```diff
@@ -313,4 +317,51 @@ impl<EK: KvEngine, ER: RaftEngine> tikv_kv::Engine for RaftKv2<EK, ER> {
...
     }
+
+    fn start_flashback(
+        &self,
+        ctx: &Context,
+        start_ts: u64,
+    ) -> BoxFuture<'static, tikv_kv::Result<()>> {
+        // Send an `AdminCmdType::PrepareFlashback` to prepare the raftstore for the
+        // later flashback. Once invoked, we will update the persistent region meta and
+        // the memory state of the flashback in Peer FSM to reject all read, write
```
Comment (tonyxuqqi) [inline src/server/raftkv2/mod.rs:328]: > "reject all read"

Can local read still work? If yes, then will it be a problem? As from user perspective, local read and raftstore read (not exist in v2, but exist in v1) make no difference.

File: components/raftstore-v2/src/operation/command/mod.rs [hunk 9]
```diff
@@ -193,6 +194,32 @@ impl<EK: KvEngine, ER: RaftEngine> Peer<EK, ER> {
...
+            header,
+            admin_type,
+            self.region_id(),
+            true,
+        ) {
+            match e {
+                Error::FlashbackInProgress(..) => {
+                    metrics.invalid_proposal.flashback_in_progress.inc()
+                }
+                Error::FlashbackNotPrepared(_) => {
```
Comment (tonyxuqqi) [inline components/raftstore-v2/src/operation/command/mod.rs:216]: This should be unreachable as skip_not_prepared is true.

File: components/raftstore-v2/src/operation/command/admin/flashback.rs [hunk 10]
```diff
@@ -0,0 +1,108 @@
...
+}
+
+impl<EK: KvEngine, R: ApplyResReporter> Apply<EK, R> {
+    pub fn apply_flashback(
+        &mut self,
+        index: u64,
+        req: &AdminRequest,
+    ) -> Result<(AdminResponse, AdminCmdResult)> {
+        let is_in_flashback = req.get_cmd_type() == AdminCmdType::PrepareFlashback;
+        // Modify the region meta in memory.
```
[the remark this answers is not in the document]
Comment (overvenus) [reply components/raftstore-v2/src/operation/command/admin/flashback.rs:43]: It's okay, because it replays committed logs before serve any request.

File: src/server/raftkv2/mod.rs (hunk 8 above)
Comment (overvenus) [reply src/server/raftkv2/mod.rs:328]: Local read only works for special read requests that have FLASHBACK flag.
It won't be a problem, because it behaves like raftstore v1.

**Review by tonyxuqqi — APPROVED** [review]

**Comment by JmPotato** [comment]
It seems that there is a flashback-related test case failure.

**Comment by overvenus** [comment]
The test `test_mvcc_flashback_unprepared` is flaky in raftstore v2. Read gets an error, rejected by flashback (which the test assumes it should not), because flashback state is set asynchronously.
