### PR TITLE
In-memory Engine: sequence number should be increased for each key

### LINKED ISSUE #17114: In-memory Engine: cache engine's sequence number may differ from rocksdb
## Bug Report

https://github.com/tikv/tikv/blob/454faa2e16ac2178078c725d8900ecba6f045955/components/region_cache_memory_engine/src/write_batch.rs#L107-L125

RocksDB assigns a unique sequence number for every modification, whereas the cache engine reuses the same sequence number. This may result in a Put operation being overshadowed by a Delete if they are in the same write batch. If this happens on the lock column family, it can lead to issues like #17074.

### What version of TiKV are you using?

Nightly, 2024-06-06

### Steps to reproduce

No need.

### PR DESCRIPTION
**Pull request by SpadeA-Tang**
### What is changed and how it works?

Issue Number: Close #17114 Ref #16141

What's Changed:

```commit-message
sequence number should be increased for each key
```

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [ ] Need to cherry-pick to the release branch

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note

```release-note
None
```

### CODE REVIEW

File: components/region_cache_memory_engine/src/write_batch.rs [hunk 1]
```diff
@@ -104,11 +104,13 @@ impl RangeCacheWriteBatch {
         Ok(())
     }
 
-    fn write_impl(&mut self, seq: u64) -> Result<()> {
+    // `seq`` is the sequence number of the first key in this write batch. Seq is
+    // incremented for each key so that all keys have unique sequence numbers.
```
Comment (LykxSassinator) [inline components/region_cache_memory_engine/src/write_batch.rs:108]:
```suggestion
    // Do write coincident with Rocksdb does.
    // Attention, `seq` is the sequence number of the first key in this write batch, 
    // which will be incremented automatically for each key, so that all keys have
    // unique sequence numbers. 
```

File: components/hybrid_engine/tests/failpoints/test_write_batch.rs [hunk 2]
```diff
@@ -0,0 +1,94 @@
...
+        fail::cfg("on_snapshot_load_finished", "pause").unwrap();
+        tx.send(true).unwrap();
+    })
+    .unwrap();
+
+    let engine = hybrid_engine.region_cache_engine().clone();
+    let r = CacheRange::new(b"k".to_vec(), b"k5".to_vec());
+    engine.new_range(r.clone());
+
+    // mock that we have a loading range, and there are some keys written in it
```
Comment (LykxSassinator) [inline components/hybrid_engine/tests/failpoints/test_write_batch.rs:26]:
```suggestion
    // Mock that we have a loading range, and there are some keys written in it
```

**Review by LykxSassinator — COMMENTED** [review]
Rest LGTM

**Review by overvenus — APPROVED** [review]

**Review by LykxSassinator — APPROVED** [review]
LGTM
