### PR TITLE
storage: refactor flashback to use the MVCC overwriting

### LINKED ISSUE #13448: change gc_life_time from 12h to 10 minutes after flashback, report [errors.rs:409] ["txn aborts"] [err_code=KV:Storage:DefaultNotFound]
### What version of TiKV are you using?
[root@10 bin]# ./tikv-server -V
TiKV 
Release Version:   6.2.0-alpha
Edition:           Community
Git Commit Hash:   b55ef7215572e675fd6e30ad10e97e7024c3c469
Git Commit Branch: master
UTC Build Time:    2022-09-02 09:11:10
Rust Version:      rustc 1.64.0-nightly (0f4bcadb4 2022-07-30)
Enable Features:   pprof-fp jemalloc mem-profiling portable sse test-engine-kv-rocksdb test-engine-raft-raft-engine cloud-aws cloud-gcp cloud-azure
Profile:           release
[root@10 bin]# 

### Steps to reproduce
1. set tidb_gc_life_time =12h
2. tikv config:
  tikv:
    storage.scheduler-pending-write-threshold: 2GB
    raft-engine.enable: true
    raftstore.store-io-pool-size: 1
    storage.io-rate-limit.max-bytes-per-sec: 838860800
    rocksdb.titan.enabled: true
    rocksdb.titan.disable-gc: true
    rocksdb.defaultcf.titan.level-merge: true
3. init flashback data with game_blob_update
4. record time A
5. run update for 2 hours, then flashback to A
6. change GC to 10 minutes
7. run update workload for 2 hours

### What did you expect?
after flashback, data is consistent. workload will run normally

### What did happened?
2022-09-10 17:21:44 (GMT+8)TiKV [10.2.12.15:2360](http://10.2.12.15:2360/)[[errors.rs:409](http://errors.rs:409/)] ["txn aborts"] [err_code=KV:Storage:DefaultNotFound] [err="Error(Txn(Error(Mvcc(Error(DefaultNotFound { key: [116, 128, 0, 0, 0, 0, 0, 0, 144, 95, 114, 128, 0, 0, 0, 0, 8, 146, 164] })))))"]
2022-09-10 17:29:15 (GMT+8)TiKV [10.2.12.14:2360](http://10.2.12.14:2360/)[[errors.rs:409](http://errors.rs:409/)] ["txn aborts"] [err_code=KV:Storage:DefaultNotFound] [err="Error(Txn(Error(Mvcc(Error(DefaultNotFound { key: [116, 128, 0, 0, 0, 0, 0, 0, 132, 95, 114, 128, 0, 0, 0, 0, 6, 162, 19] })))))"]

### PR DESCRIPTION
**Pull request by JmPotato**
Signed-off-by: JmPotato <ghzpotato@gmail.com>

### What is changed and how it works?

Issue Number: Close #13448, ref #13303. Should merge after https://github.com/pingcap/kvproto/pull/986.

What's Changed:

```commit-message
Since deleting the old MVCC keys directly will cause the GC Compaction Filter to mishandle the deletion entry,
this PR refactors the `FlashbackToVersionReadPhase` and `FlashbackToVersion` commands to use the MVCC
overwriting to achieve the flashback.
```

### Check List 

Tests 

- Unit test
- Integration test

### Release note 

```release-note
None.
```

### CODE REVIEW

File: src/storage/txn/commands/flashback_to_version_read_phase.rs [hunk 1]
```diff
@@ -59,41 +77,63 @@ impl<S: Snapshot> ReadCommand<S> for FlashbackToVersionReadPhase {
...
+            let key_writes;
             (key_writes, has_remain_writes) = key_writes_result?;
+            for (key, _) in key_writes {
+                if key.decode_ts()? >= self.commit_ts {
+                    return Err(Error::from(ErrorInner::InvalidTxnTso {
+                        start_ts: self.start_ts,
+                        commit_ts: self.commit_ts,
+                    }));
+                }
+                keys.push(key.truncate_ts()?);
```
Comment (Connor1996) [inline src/storage/txn/commands/flashback_to_version_read_phase.rs:115]: if the latest write of one key precedes `self.version`, no need to write it again

File: src/storage/txn/commands/flashback_to_version.rs [hunk 2]
```diff
@@ -84,29 +83,43 @@ impl<S: Snapshot, L: LockManager> WriteCommand<S, L> for FlashbackToVersion {
...
             }
-            let encoded_key = key.clone().truncate_ts()?;
-            let commit_ts = key.decode_ts()?;
-            txn.delete_write(encoded_key.clone(), commit_ts);
-            rows += 1;
-            // If the short value is none and it's a `WriteType::Put`, we should delete the
-            // corresponding key from `CF_DEFAULT` as well.
-            if write.short_value.is_none() && write.write_type == WriteType::Put {
-                txn.delete_value(encoded_key, write.start_ts);
+            let old_write = reader.seek_write(&key, self.version)?;
```
Comment (Connor1996) [inline src/storage/txn/commands/flashback_to_version.rs:99]: it's wasteful, why not just collect the old write in read phase

File: src/storage/txn/commands/flashback_to_version_read_phase.rs [hunk 3]
```diff
@@ -59,41 +77,72 @@ impl<S: Snapshot> ReadCommand<S> for FlashbackToVersionReadPhase {
...
+                        if commit_ts <= self.version {
+                            return false;
+                        }
+                    }
+                    // Only scan the latest version for each key, i.e, the first version we meet
+                    // for each key.
+                    if let Ok(truncated_key) = key.clone().truncate_ts() {
+                        let mut cur_key_rc = cur_key.borrow_mut();
+                        if cur_key_rc.is_some() && truncated_key == *cur_key_rc.as_ref().unwrap() {
+                            return false;
```
Comment (you06) [inline src/storage/txn/commands/flashback_to_version_read_phase.rs:103]: If the two versions of the same key are read in different batches, `cur_key` checking would miss it.

File: src/storage/txn/commands/flashback_to_version.rs [hunk 4]
```diff
@@ -84,29 +83,43 @@ impl<S: Snapshot, L: LockManager> WriteCommand<S, L> for FlashbackToVersion {
...
+            // If it's not a short value and it's a `WriteType::Put`, we should put the old
+            // value in `CF_DEFAULT` with `self.start_ts` as well.
+            if old_write.short_value.is_none() && old_write.write_type == WriteType::Put {
+                if let Some(old_value) = reader.get(&key, self.version)? {
+                    txn.put_value(key.clone(), self.start_ts, old_value);
+                    rows += 1;
+                }
+            }
+            let new_write = Write::new(old_write.write_type, self.start_ts, old_write.short_value);
+            txn.put_write(key.clone(), self.commit_ts, new_write.as_ref().to_bytes());
```
Comment (you06) [inline src/storage/txn/commands/flashback_to_version.rs:118]: When read meets write record with `WriteType::Lock` or `WriteType::Rollback`, it'll continue to next value. In this case, you should find the latest visible value and write it unless a `WriteType::Lock` or `WriteType::Rollback` will fallback to the wrong result.

File: src/storage/mvcc/reader/reader.rs [hunk 5]
```diff
@@ -531,24 +530,27 @@ impl<S: EngineSnapshot> MvccReader<S> {
...
+    ///   - `has_remain` indicates whether there MAY be remaining writes that
+    ///     can be scanned.
     ///
-    /// The return type is `(writes, has_remain)`. `has_remain` indicates
-    /// whether there MAY be remaining writes that can be scanned.
-    pub fn scan_writes<F>(
+    /// This function is used by `txn::commands::FlashbackToVersionReadPhase`
+    /// and `txn::commands::FlashbackToVersion` to achieve the MVCC
+    /// overwriting.
+    pub fn scan_old_writes(
```
Comment (JmPotato) [inline src/storage/mvcc/reader/reader.rs:546]: cc @you06 @Connor1996 I implemented this function to get the old MVCC records for all keys, it will handle the `WriteType::Lock` and `WriteType::Rollback` as well in this function. PTAL, thx a lot!

Comment (Connor1996) [inline src/storage/mvcc/reader/reader.rs:546]: maybe call it `scan_writes` and make `version` to be `Option<Timestamp>`

Comment (JmPotato) [reply src/storage/mvcc/reader/reader.rs:546]: Okay, let's make it more generic.

File: src/storage/mvcc/reader/reader.rs [hunk 6]
```diff
@@ -557,29 +559,65 @@ impl<S: EngineSnapshot> MvccReader<S> {
...
-                    return Ok((writes, true));
+            let commit_ts = key.decode_ts()?;
+            let truncated_key = key.truncate_ts()?;
+            // 1. To make sure we only check each unique key once.
+            // 2. No need to find an old version for the key if its latest `commit_ts` is
+            // smaller than or equal to the version.
+            if cur_key.is_some() && cur_key.clone().unwrap() == truncated_key
+                || cur_key.is_none() && commit_ts <= version
+            {
+                cursor.next(&mut self.statistics.lock);
```
Comment (you06) [inline src/storage/mvcc/reader/reader.rs:579]:
```suggestion
                cursor.next(&mut self.statistics.write);
```

File: src/storage/mvcc/reader/reader.rs [hunk 7]
```diff
@@ -557,29 +559,65 @@ impl<S: EngineSnapshot> MvccReader<S> {
...
+                && Key::is_user_key_eq(
+                    cursor.key(&mut self.statistics.write),
+                    truncated_key.as_encoded(),
+                )
+            {
+                while cursor.valid()? {
+                    old_write =
+                        Some(WriteRef::parse(cursor.value(&mut self.statistics.write))?.to_owned());
+                    // Move to the next key.
+                    cursor.next(&mut self.statistics.lock);
```
Comment (you06) [inline src/storage/mvcc/reader/reader.rs:597]:
```suggestion
                    cursor.next(&mut self.statistics.write);
```

File: src/storage/mvcc/reader/reader.rs [hunk 8]
```diff
@@ -557,29 +559,65 @@ impl<S: EngineSnapshot> MvccReader<S> {
...
+                    match old_write.as_ref().unwrap().write_type {
+                        WriteType::Put | WriteType::Delete => {
+                            break;
+                        }
+                        WriteType::Lock | WriteType::Rollback => {
+                            // We should find the latest visible version after it.
+                            let key =
+                                Key::from_encoded_slice(cursor.key(&mut self.statistics.write));
+                            if key.truncate_ts()? != truncated_key {
+                                break;
```
Comment (you06) [inline src/storage/mvcc/reader/reader.rs:607]: Need to set `old_write` and `cur_key` to `None` when the key is mismatch? 
`cur_key` is never reset to `None` in this function, I'm think the test coverage is not enough,

File: src/storage/mvcc/reader/reader.rs [hunk 9]
```diff
@@ -1673,17 +1711,17 @@ pub mod tests {
...
+            .prefix("_test_storage_mvcc_reader_scan_old_writes")
             .tempdir()
             .unwrap();
         let path = path.path().to_str().unwrap();
         let region = make_region(1, vec![], vec![]);
         let db = open_db(path, true);
         let mut engine = RegionEngine::new(&db, &region);
 
-        // Put some writes to the db.
+        // Prewrite and commit k1.
```
Comment (you06) [inline src/storage/mvcc/reader/reader.rs:1724]: Adding a put record of `k0` with large commit ts breaks the test.

File: src/storage/mvcc/reader/reader.rs (hunk 8 above)
Comment (JmPotato) [reply src/storage/mvcc/reader/reader.rs:607]: Nice catch.

**Review by you06 — APPROVED** [review]

File: src/storage/txn/commands/flashback_to_version.rs [hunk 10]
```diff
@@ -84,29 +87,42 @@ impl<S: Snapshot, L: LockManager> WriteCommand<S, L> for FlashbackToVersion {
...
-            let commit_ts = key.decode_ts()?;
-            txn.delete_write(encoded_key.clone(), commit_ts);
-            rows += 1;
-            // If the short value is none and it's a `WriteType::Put`, we should delete the
-            // corresponding key from `CF_DEFAULT` as well.
-            if write.short_value.is_none() && write.write_type == WriteType::Put {
-                txn.delete_value(encoded_key, write.start_ts);
+            // If the old write doesn't exist, we should put a `WriteType::Delete` record to
+            // delete the current key.
+            if old_write.is_none() {
```
Comment (Connor1996) [inline src/storage/txn/commands/flashback_to_version.rs:105]: if let (write) = old_write {
    ...
} else {
    ...
}

File: src/storage/mvcc/reader/reader.rs [hunk 11]
```diff
@@ -557,29 +566,68 @@ impl<S: EngineSnapshot> MvccReader<S> {
...
-
-            if filter(&key) {
-                writes.push((
-                    key,
-                    WriteRef::parse(cursor.value(&mut self.statistics.write))?.to_owned(),
-                ));
-                if limit > 0 && writes.len() == limit {
-                    return Ok((writes, true));
+            let commit_ts = key.decode_ts()?;
+            let truncated_key = key.clone().truncate_ts()?;
```
Comment (Connor1996) [inline src/storage/mvcc/reader/reader.rs:581]: usually, we can it user_key

File: src/storage/mvcc/reader/reader.rs [hunk 12]
```diff
@@ -557,29 +566,68 @@ impl<S: EngineSnapshot> MvccReader<S> {
...
+                                break;
+                            }
+                        }
+                    }
                 }
             }
-            cursor.next(&mut self.statistics.lock);
+            key_writes.push((truncated_key, commit_ts, write));
+            if limit > 0 && key_writes.len() == limit {
+                return Ok((key_writes, true));
```
Comment (Connor1996) [inline src/storage/mvcc/reader/reader.rs:625]: metrics is not updated due to early return

File: src/storage/mvcc/reader/reader.rs [hunk 13]
```diff
@@ -557,29 +566,68 @@ impl<S: EngineSnapshot> MvccReader<S> {
...
+        // Use the latest version as the default value if the version is not given.
+        let version = version.unwrap_or_else(TimeStamp::max);
+        let mut cur_key = None;
+        let mut key_writes = Vec::with_capacity(limit);
         while cursor.valid()? {
             let key = Key::from_encoded_slice(cursor.key(&mut self.statistics.write));
             if let Some(end) = end {
                 if key >= *end {
-                    return Ok((writes, false));
+                    return Ok((key_writes, false));
```
Comment (Connor1996) [inline src/storage/mvcc/reader/reader.rs:577]: ditto

File: src/storage/txn/commands/flashback_to_version.rs [hunk 14]
```diff
@@ -84,29 +87,41 @@ impl<S: Snapshot, L: LockManager> WriteCommand<S, L> for FlashbackToVersion {
...
+                        rows += 1;
+                    }
+                }
+                let new_write =
+                    Write::new(old_write.write_type, self.start_ts, old_write.short_value);
+                txn.put_write(key.clone(), self.commit_ts, new_write.as_ref().to_bytes());
+            } else {
+                // If the old write doesn't exist, we should put a `WriteType::Delete` record to
+                // delete the current key.
+                let new_write = Write::new(WriteType::Delete, self.start_ts, None);
```
Comment (kevin-xianliu) [inline src/storage/txn/commands/flashback_to_version.rs:118]: None ----(flashback target time) --- Put ---- Delete --- Flashback operation time
In above case, is it possible that a WriteType:Delete record been put twice?   Does it matter?

File: src/storage/txn/commands/flashback_to_version.rs [hunk 15]
```diff
@@ -100,25 +100,24 @@ impl<S: Snapshot, L: LockManager> WriteCommand<S, L> for FlashbackToVersion {
...
+                // value in `CF_DEFAULT` with `self.start_ts` as well.
+                if old_write.short_value.is_none() && old_write.write_type == WriteType::Put {
+                    if let Some(old_value) = reader.get(&key, self.version)? {
+                        txn.put_value(key.clone(), self.start_ts, old_value);
+                        rows += 1;
+                    }
+                }
+                let new_write =
+                    Write::new(old_write.write_type, self.start_ts, old_write.short_value);
+                txn.put_write(key.clone(), self.commit_ts, new_write.as_ref().to_bytes());
```
Comment (Connor1996) [inline src/storage/txn/commands/flashback_to_version.rs:114]:
```rust
let new_write = if let Some(old_write) = old_write {
 ...
} else {
 ...
};
txn.put_write(...);
```

File: src/storage/txn/commands/flashback_to_version_read_phase.rs [hunk 16]
```diff
@@ -39,11 +41,26 @@ impl CommandExt for FlashbackToVersionReadPhase {
...
 impl<S: Snapshot> ReadCommand<S> for FlashbackToVersionReadPhase {
     fn process_read(self, snapshot: S, statistics: &mut Statistics) -> Result<ProcessResult> {
+        if self.commit_ts <= self.start_ts {
+            return Err(Error::from(ErrorInner::InvalidTxnTso {
+                start_ts: self.start_ts,
+                commit_ts: self.commit_ts,
+            }));
+        }
         let mut reader = MvccReader::new_with_ctx(snapshot, Some(ScanMode::Forward), &self.ctx);
+        // TODO: maybe we should resolve all locks before starting a flashback.
```
Comment (Connor1996) [inline src/storage/txn/commands/flashback_to_version_read_phase.rs:63]: I think we should. Or delete all the versions between [min-resolve-ts, latest-ts) to provide a transaction conisistency.

Comment (Defined2014) [reply src/storage/txn/commands/flashback_to_version_read_phase.rs:63]: It's hard to make transaction conisistency during flashback cluster. Because the commit-ts for each region is different and we can't rollback flashbacked region when other region meets error during flashback.

Maybe in TiDB we could ban snapshot read with [min-resolve-ts, flashback-end-ts) time range.

File: src/storage/txn/actions/flashback_to_version.rs [hunk 17]
```diff
@@ -0,0 +1,300 @@
+// Copyright 2021 TiKV Project Authors. Licensed under Apache-2.0.
```
Comment (Connor1996) [inline src/storage/txn/actions/flashback_to_version.rs:1]:
```suggestion
// Copyright 2022 TiKV Project Authors. Licensed under Apache-2.0.
```

File: src/storage/txn/actions/flashback_to_version.rs [hunk 18]
```diff
@@ -0,0 +1,300 @@
...
+
+// #[PerformanceCriticalPath]
```
Comment (Connor1996) [inline src/storage/txn/actions/flashback_to_version.rs:3]:
```suggestion
```

**Review by Connor1996 — APPROVED** [review]
rest LGTM

File: src/storage/txn/commands/flashback_to_version.rs (hunk 14 above)
Comment (JmPotato) [reply src/storage/txn/commands/flashback_to_version.rs]: I think it is better to avoid this situation and I added a corresponding check and related tests.
