### PR TITLE
raftstore: use SplitReason in SplitCheckerHost

### LINKED ISSUE #19220: load base split can not work when scan table
### What did you do?
1、create a small table 
2、run oltp_write_only
3、table full scan

### What did you expect to see?
region can be splited

### What did you see instead?
region can not be splited

### What version of PD are you using (`pd-server -V`)?
./pd-server -V
 Release Version: v9.0.0-beta.2.pre-223-gaef91a5
Edition: Community
Kernel Type: Classic
Git Commit Hash: aef91a5ee6d6747b611f78f3874babd06af2d67d
Git Branch: HEAD
UTC Build Time:  2025-12-11 01:57:48
2025-12-11T22:42:01.516+0800	INFO	k8s/client.go:141	it should be noted that a long-running command will not be interrupted even the use case has ended. For more information, please refer to https://github.com/pingcap/test-infra/discussions/129

### PR DESCRIPTION
**Pull request by HunDunDM**
### What is changed and how it works?

Issue Number: Close #19220

What's Changed:

```commit-message
raftstore: use SplitReason in SplitCheckerHost
```

In #19013, both `SplitReason::Load` and `SplitReason::Size` were treated as `auto_split` in `SplitCheckerHost`. This contradicts the expected behavior of `SplitCheckerHost`, which should only treat `SplitReason::Size` as `auto_split`. To avoid ambiguity, `SplitReason` was used to replace `auto_split` in `SplitCheckerHost`.

test report is https://github.com/tikv/tikv/issues/19220#issuecomment-3669304240

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [x] Need to cherry-pick to the release branch

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note

```release-note
None
```

### CODE REVIEW

File: components/raftstore/src/coprocessor/split_check/half.rs [hunk 1]
```diff
@@ -86,7 +89,7 @@ where
         _: &E,
         policy: CheckPolicy,
     ) {
-        if host.auto_split() {
+        if host.split_reason() == SplitReason::Size {
```
Comment (lhy1024) [inline components/raftstore/src/coprocessor/split_check/half.rs:92]: We need a new unit test for it

**Comment by lhy1024** [comment]
test report is https://github.com/tikv/tikv/issues/19220#issuecomment-3669304240

**Review by lhy1024 — APPROVED** [review]

**Review by LykxSassinator — APPROVED** [review]

**Comment by lhy1024** [comment]
/needs-cherry-pick-release-8.5
