### PR TITLE
raftstore-v2: consider None when getting mailbox

### LINKED ISSUE #14347: [Dynamic Regions] multiple rocksdb tikv panic
### What version of TiKV are you using?

[2023/03/05 18:59:20.132 +00:00] [INFO] [[lib.rs:85](http://lib.rs:85/)] ["Welcome to TiKV"]
[2023/03/05 18:59:20.132 +00:00] [INFO] [[lib.rs:90](http://lib.rs:90/)] ["Release Version:   6.7.0-alpha"]
[2023/03/05 18:59:20.132 +00:00] [INFO] [[lib.rs:90](http://lib.rs:90/)] ["Edition:           Community"]
[2023/03/05 18:59:20.132 +00:00] [INFO] [[lib.rs:90](http://lib.rs:90/)] ["Git Commit Hash:   d74fd1325280999b367424ee332c49e11bbf80b0"]
[2023/03/05 18:59:20.132 +00:00] [INFO] [[lib.rs:90](http://lib.rs:90/)] ["Git Commit Branch: heads/refs/tags/v6.7.0-alpha"]
[2023/03/05 18:59:20.132 +00:00] [INFO] [[lib.rs:90](http://lib.rs:90/)] ["UTC Build Time:    Unknown (env var does not exist when building)"]
### Steps to reproduce

```
[2023/03/05 19:01:11.887 +00:00] [FATAL] [[lib.rs:497](http://lib.rs:497/)] ["called `Option::unwrap()` on a `None` value"] [backtrace="   0: tikv_util::set_panic_hook::{{closure}}\n             at /home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/components/tikv_util/src/lib.rs:496:18\n](http://github.com/pingcap/tikv/components/tikv_util/src/lib.rs:496:18/n)   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call\n             at /rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/[boxed.rs:2032](http://boxed.rs:2032/):9\n      std::panicking::rust_panic_with_hook\n             at /rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/[panicking.rs:692](http://panicking.rs:692/):13\n   2: std::panicking::begin_panic_handler::{{closure}}\n             at /rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/[panicking.rs:577](http://panicking.rs:577/):13\n   3: std::sys_common::backtrace::__rust_end_short_backtrace\n             at /rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/[backtrace.rs:137](http://backtrace.rs:137/):18\n   4: rust_begin_unwind\n             at /rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/[panicking.rs:575](http://panicking.rs:575/):5\n   5: core::panicking::panic_fmt\n             at /rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/[panicking.rs:65](http://panicking.rs:65/):14\n   6: core::panicking::panic\n             at /rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/[panicking.rs:114](http://panicking.rs:114/):5\n   7: raftstore_v2::operation::command::admin::split::<impl raftstore_v2::raft::peer::Peer<EK,ER>>::on_apply_res_split\n      raftstore_v2::operation::command::<impl raftstore_v2::raft::peer::Peer<EK,ER>>::on_apply_res\n             at /home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/components/raftstore-v2/src/operation/command/mod.rs:356:21\n](http://github.com/pingcap/tikv/components/raftstore-v2/src/operation/command/mod.rs:356:21/n)   8: raftstore_v2::fsm::peer::PeerFsmDelegate<EK,ER,T>::on_msgs\n             at /home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/components/raftstore-v2/src/fsm/peer.rs:266:43\n](http://github.com/pingcap/tikv/components/raftstore-v2/src/fsm/peer.rs:266:43/n)   9: <raftstore_v2::batch::store::StorePoller<EK,ER,T> as batch_system::batch::PollHandler<raftstore_v2::fsm::peer::PeerFsm<EK,ER>,raftstore_v2::fsm::store::StoreFsm>>::handle_normal\n             at /home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/components/raftstore-v2/src/batch/store.rs:230:9\n](http://github.com/pingcap/tikv/components/raftstore-v2/src/batch/store.rs:230:9/n)      batch_system::batch::Poller<N,C,Handler>::poll\n             at /home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/components/batch-system/src/batch.rs:422:27\n](http://github.com/pingcap/tikv/components/batch-system/src/batch.rs:422:27/n)  10: batch_system::batch::BatchSystem<N,C>::start_poller::{{closure}}\n             at /home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/components/batch-system/src/batch.rs:550:17\n](http://github.com/pingcap/tikv/components/batch-system/src/batch.rs:550:17/n)      <std::thread::Builder as tikv_util::sys::thread::StdThreadBuildWrapper>::spawn_wrapper::{{closure}}\n             at /home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/components/tikv_util/src/sys/thread.rs:427:23\n](http://github.com/pingcap/tikv/components/tikv_util/src/sys/thread.rs:427:23/n)      std::sys_common::backtrace::__rust_begin_short_backtrace\n             at /rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/[backtrace.rs:121](http://backtrace.rs:121/):18\n  11: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}\n             at /rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/[mod.rs:551](http://mod.rs:551/):17\n      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once\n             at /rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panic/[unwind_safe.rs:271](http://unwind_safe.rs:271/):9\n      std::panicking::try::do_call\n             at /rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/[panicking.rs:483](http://panicking.rs:483/):40\n      std::panicking::try\n             at /rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/[panicking.rs:447](http://panicking.rs:447/):19\n      std::panic::catch_unwind\n             at /rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/[panic.rs:137](http://panic.rs:137/):14\n      std::thread::Builder::spawn_unchecked_::{{closure}}\n             at /rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/[mod.rs:550](http://mod.rs:550/):30\n      core::ops::function::FnOnce::call_once{{vtable.shim}}\n             at /rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/[function.rs:513](http://function.rs:513/):5\n  12: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once\n             at /rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/[boxed.rs:2000](http://boxed.rs:2000/):9\n      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once\n             at /rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/[boxed.rs:2000](http://boxed.rs:2000/):9\n      std::sys::unix::thread::Thread::new::thread_start\n             at /rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys/unix/[thread.rs:108](http://thread.rs:108/):17\n  13: start_thread\n  14: clone\n"] [location=/home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/components/raftstore-v2/src/operation/command/admin/split.rs:606](http://github.com/pingcap/tikv/components/raftstore-v2/src/operation/command/admin/split.rs:606)] [thread_name=rs-3-0]
```

### PR DESCRIPTION
**Pull request by SpadeA-Tang**
### What is changed and how it works?

Issue Number: Close #14347

What's Changed:

```commit-message
consider None when getting mailbox
```
When the cluster is stopped, mailboxes will be cleared.  However, on_apply_res_split may be executed concurrently, which means we cannot unwrap on `mailbox(xxx)`.

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

### Release note 

```release-note
None
```

### CODE REVIEW

File: components/raftstore-v2/src/operation/command/admin/split.rs [hunk 1]
```diff
@@ -603,7 +603,17 @@ impl<EK: KvEngine, ER: RaftEngine> Peer<EK, ER> {
             self.add_pending_tick(PeerTick::SplitRegionCheck);
         }
         self.storage_mut().set_has_dirty_data(true);
-        let mailbox = store_ctx.router.mailbox(self.region_id()).unwrap();
+        let mailbox = {
+            match store_ctx.router.mailbox(self.region_id()) {
+                Some(mailbox) => mailbox,
+                None => {
```
Comment (BusyJay) [inline components/raftstore-v2/src/operation/command/admin/split.rs:609]: Not enough, it can still panic in the following lines within the function.

File: components/raftstore-v2/src/operation/command/admin/split.rs [hunk 2]
```diff
@@ -603,7 +603,17 @@ impl<EK: KvEngine, ER: RaftEngine> Peer<EK, ER> {
...
+                    // None means the node is shutdown concurrently and thus the
+                    // mailboxes in router have been cleared
+                    assert!(store_ctx.router.is_shutdown());
```
Comment (BusyJay) [inline components/raftstore-v2/src/operation/command/admin/split.rs:612]: Should include logger.

Comment (SpadeA-Tang) [reply components/raftstore-v2/src/operation/command/admin/split.rs]: Done

File: components/raftstore-v2/src/operation/command/admin/split.rs [hunk 3]
```diff
@@ -641,16 +657,21 @@ impl<EK: KvEngine, ER: RaftEngine> Peer<EK, ER> {
...
-                    store_ctx
+                    fail_point!("before_cluster_shutdown2", |_| {});
+                    if let Err(e) = store_ctx
                         .router
                         .force_send_control(StoreMsg::SplitInit(msg))
-                        .unwrap_or_else(|e| {
+                    {
+                        if store_ctx.router.is_shutdown() {
+                            return;
+                        } else {
```
Comment (BusyJay) [inline components/raftstore-v2/src/operation/command/admin/split.rs:667]: Useless else.

**Review by BusyJay — APPROVED** [review]

**Review by tabokie — APPROVED** [review]
