### PR TITLE
collation: fix wrong compare result for unicode collate

### LINKED ISSUE #18784: Result wrong with utf8mb4_unicode_ci
### What version of TiKV are you using?

master

### What operating system and CPU are you using?

none related

### Steps to reproduce

See https://github.com/pingcap/tidb/issues/62808

### What did you expect?
See https://github.com/pingcap/tidb/issues/62808

### PR DESCRIPTION
**Pull request by Defined2014**
### What is changed and how it works?

Issue Number: Close #18784

What's Changed:

```commit-message
Follow tidb code, see https://github.com/pingcap/tidb/blob/2a522358ceb60095eea898503682595dd3612492/pkg/util/collate/ucaimpl/unicode_ci.go.tpl#L50 to get more informations.
```

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [ ] Need to cherry-pick to the release branch

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note

```release-note
None
```

### CODE REVIEW

File: components/tidb_query_datatype/src/codec/collation/collator/utf8mb4_uca/mod.rs [hunk 1]
```diff
@@ -67,7 +67,7 @@ impl<T: UnicodeVersion> Collator for CollatorUca<T> {
         let mut an = 0;
         let mut bn = 0;
 
-        while !sa.is_empty() || !sb.is_empty() {
+        loop {
```
Comment (Defined2014) [inline components/tidb_query_datatype/src/codec/collation/collator/utf8mb4_uca/mod.rs:70]: Follow https://github.com/pingcap/tidb/blob/2a522358ceb60095eea898503682595dd3612492/pkg/util/collate/ucaimpl/unicode_ci.go.tpl#L50

**Review by breezewish — APPROVED** [review]
