### PR TITLE
raftstore: reject follower read request on disk-full follower

### LINKED ISSUE #19201: follower read request can be stuck forever when disk is full
## Bug Report

In one production env, 1 tikv's read pool pending increased to the limit in a very short time and caused it reject all following read requests. And these pending tasks are all in waiting for snapshot state and never finish. This happened when this store's disk usage increased to NearFull state(due to a big compaction in rocksdb). 

I found the snapshot pending was due to follower read. Because when disk is near full, raft append is stopped and all follower on this store's raft applied index will fall behind. So the async_snapshot requests with readIndex can never return because raft apply is stopped while leader's committed index is still increasing. 

So in this case, I think when propose readIndex request on follower peer, if current store's disk is full, it should directly return an errror to the caller to let the caller try other replica instead of waiting forever.

### PR DESCRIPTION
**Pull request by glorv**
### What is changed and how it works?

Issue Number: Close #19201

What's Changed:

```commit-message
Reject read request(e.g. snapshot request) on follower when the disk is full. To can avoid letting the readIndex request stuck forever as the follower's applied index can not catchup with leader's committed index.
```

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [ ] Need to cherry-pick to the release branch

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note

```release-note
Reject read request if the raft follower store's disk is full to avoid stucking the read request for too long.
```

### CODE REVIEW

File: components/raftstore/src/store/peer.rs [hunk 1]
```diff
@@ -4320,6 +4320,17 @@ where
             }
         } else {
             fail_point!("propose_readindex_from_follower");
+            let request = req.get_requests();
+            let is_read_index_request =
+                request.len() == 1 && request[0].get_cmd_type() == CmdType::ReadIndex;
```
Comment (hbisheng) [inline components/raftstore/src/store/peer.rs]: will there be multiple read index cmds in one `request`?

File: tests/failpoints/cases/test_disk_full.rs [hunk 2]
```diff
@@ -333,6 +333,7 @@ fn test_majority_disk_full() {
     opts.disk_full_opt = DiskFullOpt::AllowedOnAlmostFull;
     let ch = cluster.async_request_with_opts(put, opts).unwrap();
     let resp = block_on_timeout(ch, Duration::from_secs(10)).unwrap();
+    println!("{:?}", resp);
```
Comment (hbisheng) [inline tests/failpoints/cases/test_disk_full.rs]: should be removed

File: components/raftstore/src/store/peer.rs (hunk 1 above)
Comment (glorv) [reply components/raftstore/src/store/peer.rs]: This logic is the same as following in `pre_propose_raft_command`:
 https://github.com/tikv/tikv/blob/147cacc5e3f783348797a099c7be7fe9e01eb013/components/raftstore/src/store/fsm/peer.rs#L5924-L5932

File: tests/failpoints/cases/test_disk_full.rs [hunk 3]
```diff
@@ -591,3 +591,34 @@ fn test_down_node_when_disk_full() {
         fail::remove(get_fp(DiskUsage::AlmostFull, i));
     }
 }
+
+#[test]
+fn test_reject_follower_read_index_when_disk_ful() {
```
Comment (hhwyt) [inline tests/failpoints/cases/test_disk_full.rs]:
```suggestion
fn test_reject_follower_read_index_when_disk_full() {
```

File: components/raftstore/src/store/peer.rs [hunk 4]
```diff
@@ -4320,6 +4320,17 @@ where
...
+            // reject read request(e.g. snapshot) on follower when the disk is full.
+            // allow readIndex request here because it can be used in other functions.
```
Comment (hhwyt) [inline components/raftstore/src/store/peer.rs]: what do you mean by "in other funcations"?

File: components/raftstore/src/store/peer.rs [hunk 5]
```diff
@@ -4320,6 +4320,17 @@ where
             }
         } else {
             fail_point!("propose_readindex_from_follower");
+            let request = req.get_requests();
+            let is_read_index_request =
+                request.len() == 1 && request[0].get_cmd_type() == CmdType::ReadIndex;
+            // reject read request(e.g. snapshot) on follower when the disk is full.
```
Comment (hhwyt) [inline components/raftstore/src/store/peer.rs]: More precisely, it is near full.

File: components/raftstore/src/store/peer.rs [hunk 6]
```diff
@@ -4320,6 +4320,17 @@ where
...
+            // allow readIndex request here because it can be used in other functions.
+            if !is_read_index_request && poll_ctx.self_disk_usage != DiskUsage::Normal {
```
Comment (hhwyt) [inline components/raftstore/src/store/peer.rs]: How about:
```
 matches!(
          poll_ctx.self_disk_usage,
          DiskUsage::AlmostFull | DiskUsage::AlreadyFull
      )
```

Comment (hbisheng) [reply components/raftstore/src/store/peer.rs]: @glorv Should we also add `req.get_header().get_replica_read()` to the conditions to ensure it's a replica read request? Can it replace the `!is_read_index_request` condition?

Comment (glorv) [reply components/raftstore/src/store/peer.rs]: Yeah, using `req.get_header().get_replica_read()` directly should be a better condition.

**Comment by mittalrishabh** [comment]
what is the status of this PR

**Comment by glorv** [comment]
@hhwyt @hbisheng @Connor1996 PTAL again, thanks

**Comment by glorv** [comment]
> what is the status of this PR

@mittalrishabh still under review, I will try to let it merge in the next week.
