### PR TITLE
tikv-ctl: add tikv-ctl fork-readonly-tikv

### LINKED ISSUE #14357: shadow server on read-only TiKV cluster remains
## Enhancement

Please consider this case:
* data centers can fail and won't recover; all remains are some disks;
* those disks **can only be mounted in `read-only`** mode;
* fortunately there is a backup cluster based on TiCDC;
* however some committed transactions haven't been replicated to the downstream cluster;

So before switching to the downstream backup cluster, we need to fetch all committed transactions from the **read-only** upstream cluster, and dispatch them to the downstream backup cluster.

To resolve the requirement: 
* We can copy the whole old cluster data into a new read-write place;
* Or we can **symlink as more as possible files to a new read-write place, and copy others**.

And then start the cluster on the new read-write place.

Obviously, the second ways can save much disk space and reduce much recovery time.

### PR DESCRIPTION
**Pull request by hicqu**
### What is changed and how it works?

Issue Number: Close #14357 

What's Changed:

```commit-message
tikv-ctl: add tikv-ctl reuse-readonly-remains
```

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Manual test (add detailed scripts or steps below)

Side effects

### Release note 

```release-note
None
```

### CODE REVIEW

File: cmd/tikv-ctl/src/main.rs [hunk 1]
```diff
@@ -235,6 +241,75 @@ fn main() {
...
+                    println!("cluster-id: {}", id);
+                    process::exit(0);
+                }
+                Err(e) => {
+                    eprintln!("read cluster ID fail: {}", e);
+                    process::exit(-1);
+                }
+            }
+        }
+        Cmd::ReuseReadonlyRemains {
```
Comment (3pointer) [inline cmd/tikv-ctl/src/main.rs:272]: shall we set `raftstore::store::config::snap_apply_copy_symlink` to true by default?

**Review by 3pointer — COMMENTED** [review]
rest LGTM

File: cmd/tikv-ctl/src/main.rs (hunk 1 above)
Comment (hicqu) [reply cmd/tikv-ctl/src/main.rs:272]: Generally snapshot files are generated by TiKV, so they should be regular files instead of symlinks. So it's ok to set `snap_apply_copy_symlink` to `false` in general cases.
By design, only TiKV instances created by `reuse-readonly-remains` need to set the flag.

File: cmd/tikv-ctl/src/main.rs [hunk 2]
```diff
@@ -235,6 +241,75 @@ fn main() {
...
+            data_dir,
+            agent_dir,
+            snaps,
+            rocksdb_files,
+        } => {
+            if opt.config.is_none() {
+                eprintln!("tikv-ctl parameter config must be specified");
+                process::exit(-1);
```
Comment (overvenus) [inline cmd/tikv-ctl/src/main.rs:280]:
```suggestion
                clap::Error {
                    message: String::from("(--config) must be specified"),
                    kind: ErrorKind::MissingRequiredArgument,
                    info: None,
                }
                .exit();
```

**Review by overvenus — COMMENTED** [review]
nits: Could you use `clap::Error::exit()`?

File: cmd/tikv-ctl/src/main.rs [hunk 3]
```diff
@@ -235,6 +241,101 @@ fn main() {
...
+                clap::Error {
+                    message: String::from(
+                        "raft-engine.recovery-mode can only be tolerate-tail-corruption",
+                    ),
+                    kind: ErrorKind::InvalidValue,
+                    info: None,
+                }
+                .exit();
+            }
+            if snaps != "symlink" && snaps != "copy" {
```
Comment (tonyxuqqi) [inline cmd/tikv-ctl/src/main.rs:321]: use a const instead of "copy" directly. 
Same for "symlink"

**Comment by tonyxuqqi** [comment]
The code LGTM. Except, the name of the cmd reuse-readonly-remains seems a bit odd to and hard to understand. 
To me it seems better to use fork-readonly-tikv

**Review by tonyxuqqi — APPROVED** [review]

**Review by 3pointer — APPROVED** [review]

File: cmd/tikv-ctl/src/cmd.rs [hunk 4]
```diff
@@ -565,6 +565,41 @@ pub enum Cmd {
...
+    },
+    /// Usage: tikv-ctl fork-readonly-tikv
+    ///
+    /// fork-readonly-tikv is for creating a tikv-server agent based on a
+    /// read-only TiKV remains. The agent can be used for recovery because
+    /// all committed transactions can be accessed correctly, without any
+    /// modifications on the remained TiKV.
+    ///
+    /// NOTE: The remained TiKV can't run concurrently with the agent.
+    ReuseReadonlyRemains {
```
Comment (HuSharp) [inline cmd/tikv-ctl/src/cmd.rs:582]: Is it `reuse-readonly-remains` or `fork-readonly-tikv`?
