### PR TITLE
In-memory engine: mvcc keys with different sequence number should only be handled once in GC

### LINKED ISSUE #17060: In-memory engine: default not found in long tpcc run
### What did happened?
[2024/05/24 00:55:49.491 +00:00] [INFO] [cmd.go:31] ["[2024-05-24 00:55:49] execute run failed, err exec SELECT c_balance, c_first, c_middle, c_id FROM customer WHERE c_w_id = ? AND c_d_id = ? AND c_last = ? ORDER BY c_first failed Error 1105: other error: default not found: key:74800000000000E5FF065F720380000000FF0000002403800000FF0000000008038000FF00000000081D0000FDF9C160F026F7FF96, maybe read truncated/dropped table data?"]

### PR DESCRIPTION
**Pull request by SpadeA-Tang**
### What is changed and how it works?

Issue Number: Close #17060 Ref #16141

What's Changed:

```commit-message
mvcc keys with different sequen number should only be handled once in GC
```
Without the patch, the default not found can occur:
If one key in write cf is overwritten, GC can delete the default cf incorrectly, e.g.
safe-point is 10, and there is only one k1 with commit ts less than 10, ex: k1_5_100 (5 is the commit ts, 100 is the seqno)
Now the overwrite happens, k1_5_200.
So now it's k1_5_200, k1_5_100.

The GC will leave the latest put under the safe-point
Here, k1_5_100 was mistakenly GC'd, and the corresponding default cf was deleted where key of this default cf is also the one pointed to by k1_5_200.

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [ ] Need to cherry-pick to the release branch

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note

```release-note
None
```

### CODE REVIEW

File: components/region_cache_memory_engine/tests/failpoints/test_gc.rs [hunk 1]
```diff
@@ -0,0 +1,118 @@
...
+
+    let guard = &epoch::pin();
+    for &ts in &[commit_ts1, commit_ts2, commit_ts3] {
+        let key = Key::from_raw(b"k");
+        let key = encoding_for_filter(key.as_encoded(), TimeStamp::new(ts));
+
+        assert!(key_exist(&write, &key, guard));
+    }
+
+    std::thread::sleep(Duration::from_secs_f32(1.5));
```
Comment (overvenus) [inline components/region_cache_memory_engine/tests/failpoints/test_gc.rs:107]: Why sleep?

File: components/region_cache_memory_engine/src/background.rs [hunk 2]
```diff
@@ -481,6 +488,9 @@ pub struct BackgroundRunner {
 
     gc_range_remote: Remote<yatp::task::future::TaskCell>,
     gc_range_worker: Worker,
+
+    // RocksEngine is used to get the oldest snapshot no.
```
Comment (overvenus) [inline components/region_cache_memory_engine/src/background.rs:492]:
```suggestion
    // RocksEngine is used to get the oldest snapshot sequence number.
```

File: components/region_cache_memory_engine/src/background.rs [hunk 3]
```diff
@@ -531,17 +542,41 @@ impl Runnable for BackgroundRunner {
 
     fn run(&mut self, task: Self::Task) {
         match task {
+            BackgroundTask::SetRocksEngine(rocks_engine) => {
+                self.rocks_engine = Some(rocks_engine);
+            }
             BackgroundTask::Gc(t) => {
+                let seqno = (|| {
+                    fail::fail_point!("oldest_seqno_ingest", |t| {
```
Comment (overvenus) [inline components/region_cache_memory_engine/src/background.rs:550]:
```suggestion
                    fail::fail_point!("in_memry_engine_gc_oldest_seqno", |t| {
```

File: components/region_cache_memory_engine/tests/failpoints/test_gc.rs (hunk 1 above)
Comment (SpadeA-Tang) [reply components/region_cache_memory_engine/tests/failpoints/test_gc.rs:107]: GC interval is 1 second.

Comment (overvenus) [reply components/region_cache_memory_engine/tests/failpoints/test_gc.rs:107]: It may become a flakey test. How about using a `fail::cfg_callback` to wait GC?

**Review by overvenus — COMMENTED** [review]
Rest LGTM

**Review by overvenus — APPROVED** [review]

File: components/region_cache_memory_engine/src/test_util.rs [hunk 4]
```diff
@@ -0,0 +1,126 @@
...
+        None,
+        short_value,
+        default_cf,
+        write_cf,
+        mem_controller,
+    )
+}
+
+// Put data with write cf and related start cf and overwrite the write cf with
+// sequence number `seq_num2` which also points to the prevous default cf
```
Comment (LykxSassinator) [inline components/region_cache_memory_engine/src/test_util.rs:42]:
```suggestion
// sequence number `seq_num2` which also points to the previous default cf.
```

**Review by LykxSassinator — COMMENTED** [review]
Rest LGTM

**Review by LykxSassinator — APPROVED** [review]
