### PR TITLE
snapshot-v2: delete idle snapshot file

### LINKED ISSUE #14581: [Dynamic Regions] tablet_snap takes 1.4TB and TiKV running out of space
### What version of TiKV are you using?

nightly

### What operating system and CPU are you using?

x86
### Steps to reproduce

run the social network simulation for two days

### What did you expect?
no  running out of space
### What did happened?
running out of space, tablets directory takes 1.4 TB
```
[root@tc-tikv-0 data]# pwd
/var/lib/tikv/data
[root@tc-tikv-0 data]# df -h .
Filesystem      Size  Used Avail Use% Mounted on
/dev/nvme4n1    3.6T  3.5T     0 100% /var/lib/tikv
[root@tc-tikv-0 data]# du -sh * | sort -n
0       LOCK
0       raftdb.info
1.4T    tablet_snap
2.1T    tablets
12K     import
20K     last_tikv.toml
29M     rocksdb.info
45G     raft-engine
```

### PR DESCRIPTION
**Pull request by bufferflies**
### What is changed and how it works?

Issue Number: Close #14581

What's Changed:

```commit-message
1. change `delete_snapshot` to delete some snapshot directory those has same region_id and to_peer_id
2. the delete_snapshot will be happened in peer destory or send_snapshot finished.
```

### Check List 

Tests 

- Unit test
- Integration test

Side effects

### Release note 

```release-note
Please add a release note.

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

If you don't think this PR needs a release note then fill it with None.
If this PR will be picked to release branch, then a release note is probably required.
```

### CODE REVIEW

File: components/raftstore/src/store/snap.rs [hunk 1]
```diff
@@ -2094,18 +2094,29 @@ impl TabletSnapManager {
...
+            }
+            let os_name = entry.file_name();
+            let name = os_name.to_str().unwrap().to_string();
+
+            let parts = name
+                .split('_')
+                .skip(1)
+                .map(|s| s.parse().unwrap())
+                .collect::<Vec<u64>>();
+            if parts.len() < 4 {
```
Comment (SpadeA-Tang) [inline components/raftstore/src/store/snap.rs:2112]: In which cases it will be less than 4?

File: src/server/tablet_snap.rs [hunk 2]
```diff
@@ -805,6 +804,17 @@ where
             }
             Task::Send { addr, msg, cb } => {
                 let region_id = msg.get_region_id();
+                let to_peer_id = msg.get_to_peer().get_id();
+                defer!({
+                    if let Err(e) = self.snap_mgr.delete_snapshot(region_id, to_peer_id) {
```
Comment (SpadeA-Tang) [inline src/server/tablet_snap.rs:809]: If the node shutdowns after generating snapshot but before this line, the snapshot may still not be cleared? Or do we have some checks and actions on node start?

File: components/raftstore/src/store/snap.rs (hunk 1 above)
Comment (bufferflies) [reply components/raftstore/src/store/snap.rs:2112]: none, but user may create dir in this directory.

File: src/server/tablet_snap.rs (hunk 2 above)
Comment (bufferflies) [reply src/server/tablet_snap.rs:809]: It will resent snapshot again after this node restart. So the old snapshot will be deleted .

Comment (SpadeA-Tang) [reply src/server/tablet_snap.rs:809]: If it's not a leader after restart?

Comment (bufferflies) [reply src/server/tablet_snap.rs:809]: Good catch , I will remove all `gen_x_x_x_x` file  after restart.

File: components/file_system/src/lib.rs [hunk 3]
```diff
@@ -464,14 +464,12 @@ pub fn trash_dir_all(path: impl AsRef<Path>) -> io::Result<()> {
     remove_dir_all(trash_path)
 }
 
-/// When using `trash_dir_all`, it's possible the directory is marked as trash
-/// but not being actually deleted after a restart. This function can be used
-/// to resume all those removal in the given directory.
+// remove all file exclude prefix.
 #[inline]
-pub fn clean_up_trash(path: impl AsRef<Path>) -> io::Result<()> {
```
Comment (BusyJay) [inline components/file_system/src/lib.rs:471]: This method is supposed to be used paired with `trash_dir_all`.

File: components/raftstore/src/store/snap.rs [hunk 4]
```diff
@@ -2013,7 +2013,7 @@ impl TabletSnapManager {
                 format!("{} should be a directory", path.display()),
             ));
         }
-        file_system::clean_up_trash(&path)?;
+        file_system::clean_up_exclude_prefix(&path, SNAP_REV_PREFIX)?;
```
Comment (BusyJay) [inline components/raftstore/src/store/snap.rs:2016]: It's safer to use allowlist instead of blocklist.

File: src/server/tablet_snap.rs [hunk 5]
```diff
@@ -805,6 +804,17 @@ where
             }
             Task::Send { addr, msg, cb } => {
                 let region_id = msg.get_region_id();
+                let to_peer_id = msg.get_to_peer().get_id();
+                defer!({
+                    if let Err(e) = self.snap_mgr.delete_snapshot(region_id, Some(to_peer_id)) {
```
Comment (BusyJay) [inline src/server/tablet_snap.rs:809]: It's wrong to delete snapshot here while the sending task is being processed in the background.

File: components/raftstore-v2/src/worker/tablet_gc.rs [hunk 6]
```diff
@@ -295,6 +315,9 @@ impl<EK: KvEngine> Runner<EK> {
                             "path" => path.display(),
                         )
                     });
+                if success.is_ok() &&let Err(e) = mgr.delete_snapshot(region_id, None){
```
Comment (BusyJay) [inline components/raftstore-v2/src/worker/tablet_gc.rs:318]: Destroying a tablet doesn't mean the snapshot is outdated.

**Review by BusyJay — COMMENTED** [review]
You only need to delete snapshots after sending is finished or after restart.

File: components/file_system/src/lib.rs (hunk 3 above)
Comment (bufferflies) [reply components/file_system/src/lib.rs:471]: yes fixed it with one parameter `prefix`

File: components/raftstore/src/store/snap.rs (hunk 4 above)
Comment (bufferflies) [reply components/raftstore/src/store/snap.rs]: fixed

File: src/server/tablet_snap.rs (hunk 5 above)
Comment (bufferflies) [reply src/server/tablet_snap.rs]: yes,  it should add in the limit and add defer in send_snap.

File: components/raftstore-v2/src/worker/tablet_gc.rs (hunk 6 above)
Comment (bufferflies) [reply components/raftstore-v2/src/worker/tablet_gc.rs]: removed

File: src/server/tablet_snap.rs [hunk 7]
```diff
@@ -662,7 +662,6 @@ pub fn send_snap(
         send_timer.observe_duration();
         drop(client);
         drop(deregister);
-        mgr.delete_snapshot(&key);
```
Comment (BusyJay) [inline src/server/tablet_snap.rs:665]: Maybe you can add this line to `deregister` explicitly.

File: components/file_system/src/lib.rs (hunk 3 above)
Comment (BusyJay) [reply components/file_system/src/lib.rs:471]: You should keep this method and introduce a new method instead. You may make this method call the new method.

File: components/raftstore/src/store/snap.rs [hunk 8]
```diff
@@ -2061,6 +2061,8 @@ impl TabletSnapManager {
                 stat.set_total_duration_sec(start.saturating_elapsed().as_secs());
                 stat.set_region_id(region_id);
             });
+
+        self.delete_snapshot(region_id, Some(key.to_peer));
```
Comment (BusyJay) [inline components/raftstore/src/store/snap.rs]: This is an unexpected side affect.

Comment (bufferflies) [reply components/raftstore/src/store/snap.rs]: fixed, move it in deregister.

File: components/file_system/src/lib.rs [hunk 9]
```diff
@@ -469,9 +469,13 @@ pub fn trash_dir_all(path: impl AsRef<Path>) -> io::Result<()> {
 /// to resume all those removal in the given directory.
 #[inline]
 pub fn clean_up_trash(path: impl AsRef<Path>) -> io::Result<()> {
+    clean_up_dir(path, TRASH_PREFIX)
+}
+
+pub fn clean_up_dir(path: impl AsRef<Path>, prefix: &str) -> io::Result<()> {
```
Comment (BusyJay) [inline components/file_system/src/lib.rs:475]: Should add comment.

File: components/raftstore/src/store/snap.rs [hunk 10]
```diff
@@ -2046,6 +2047,7 @@ impl TabletSnapManager {
             ));
         }
         file_system::clean_up_trash(&self.base)?;
+        file_system::clean_up_dir(&self.base, SNAP_GEN_PREFIX)?;
```
Comment (BusyJay) [inline components/raftstore/src/store/snap.rs:2050]: Can `init` be deleted as `new` does the same thing as `init`?

File: components/raftstore/src/store/snap.rs [hunk 11]
```diff
@@ -2019,6 +2019,7 @@ impl TabletSnapManager {
             ));
         }
         file_system::clean_up_trash(&path)?;
+        file_system::clean_up_dir(&path, SNAP_GEN_PREFIX)?;
```
Comment (BusyJay) [inline components/raftstore/src/store/snap.rs:2022]: Maybe clean `SNAP_GEN_PREFIX` first.

File: components/raftstore/src/store/snap.rs [hunk 12]
```diff
@@ -2099,18 +2101,31 @@ impl TabletSnapManager {
...
-        if path.exists() && let Err(e) = file_system::trash_dir_all(&path) {
-            error!(
-                "delete snapshot failed";
-                "path" => %path.display(),
-                "err" => ?e,
-            );
-            false
-        } else {
-            true
+    pub fn delete_snapshot(&self, region_id: u64, to_peer: Option<u64>) -> Result<()> {
```
Comment (BusyJay) [inline components/raftstore/src/store/snap.rs:2104]: Doesn't need to change.

File: components/raftstore/src/store/snap.rs (hunk 10 above)
Comment (bufferflies) [reply components/raftstore/src/store/snap.rs:2050]: But some caller using `new_without_init` to create `TabletSnapshotManager`.

File: components/raftstore/src/store/snap.rs (hunk 12 above)
Comment (bufferflies) [reply components/raftstore/src/store/snap.rs:2104]: What's your means that the parameter also using `TabletSnapKey`?  But it will skip if the concurrency is more than the limit.

File: components/raftstore/src/store/snap.rs (hunk 10 above)
Comment (BusyJay) [reply components/raftstore/src/store/snap.rs:2050]: Like what case?

File: components/raftstore/src/store/snap.rs (hunk 12 above)
Comment (BusyJay) [reply components/raftstore/src/store/snap.rs:2104]: The key can still be built in this case.

File: components/raftstore/src/store/snap.rs (hunk 10 above)
Comment (BusyJay) [reply components/raftstore/src/store/snap.rs:2050]: I don't see why it's not initialized here. It's almost initialized immediately after being built.

Comment (bufferflies) [reply components/raftstore/src/store/snap.rs:2050]: The reason is that some called maybe using `""` to create `SnapshotManagerCore`. I think `TabletSnapManager` should redefine `new` and `init`, I think they do the same things .

File: components/file_system/src/lib.rs (hunk 9 above)
Comment (bufferflies) [reply components/file_system/src/lib.rs:477]: fixed

File: components/raftstore/src/store/snap.rs (hunk 11 above)
Comment (bufferflies) [reply components/raftstore/src/store/snap.rs]: fixed

File: components/raftstore/src/store/snap.rs (hunk 10 above)
Comment (BusyJay) [reply components/raftstore/src/store/snap.rs:2039]: `new_without_init` is introduced yesterday, how come those test cases pass in the past?

File: components/raftstore/src/store/snap.rs [hunk 13]
```diff
@@ -2099,18 +2091,28 @@ impl TabletSnapManager {
...
-            error!(
-                "delete snapshot failed";
-                "path" => %path.display(),
-                "err" => ?e,
-            );
-            false
-        } else {
-            true
+    pub fn delete_snapshot(&self, key: TabletSnapKey) -> Result<()> {
+        for f in file_system::read_dir(&self.base)? {
```
Comment (BusyJay) [inline components/raftstore/src/store/snap.rs:2095]: Why still need to iterate the directory?

Comment (bufferflies) [reply components/raftstore/src/store/snap.rs:2095]: `new_without_init` only is only used as `SnapshotManagerCore` receive the v2 snapshot. And these test cases does not need to create the real dir, so it can pass. But if using `new` to create it, it will failed because the path is wrong.

Comment (bufferflies) [reply components/raftstore/src/store/snap.rs:2095]: yes, it doesn't needs to iterate the directory. The backlogged snapshot task will be delete after the tikv restart.

Comment (BusyJay) [reply components/raftstore/src/store/snap.rs]: > new_without_init only is only used as SnapshotManagerCore receive the v2 snapshot. And these test cases does not need to create the real dir, so it can pass. But if using new to create it, it will failed because the path is wrong.

As explained before: If "" is meant to disable tablet snapshot, then tablet snapshot manager should be defined as an Option.

Comment (bufferflies) [reply components/raftstore/src/store/snap.rs]: OK, I will remove the constructed function in later pr.

File: components/file_system/src/lib.rs (hunk 9 above)
Comment (BusyJay) [reply components/file_system/src/lib.rs:475]: No, comment is still messing.

File: components/raftstore/src/store/snap.rs (hunk 13 above)
Comment (BusyJay) [reply components/raftstore/src/store/snap.rs]: Why not just do it in this PR?

Comment (bufferflies) [reply components/raftstore/src/store/snap.rs]: done, have remove `init` and `new_without_init` functions .

Comment (SpadeA-Tang) [reply components/raftstore/src/store/snap.rs]: > > new_without_init only is only used as SnapshotManagerCore receive the v2 snapshot. And these test cases does not need to create the real dir, so it can pass. But if using new to create it, it will failed because the path is wrong.
> 
> As explained before: If "" is meant to disable tablet snapshot, then tablet snapshot manager should be defined as an Option.

Passing "" is not meant to disable tablet snap mgr. Some tests does not want to use snap manager but want to use struct that has the field of snap manager, so it pass "" to create the snap manager but never uses it. For snap manager, as it lazily create the dir, so it's fine. Now, we add tablet snap manager as a field of snap manager, creating dir based on "" may cause problem.

Comment (SpadeA-Tang) [reply components/raftstore/src/store/snap.rs]: I suggest to adjust these tests (very few), and add an assert that the path is not "" in the `SnapManagerBuilder::build`.

File: components/raftstore/src/store/snap.rs [hunk 14]
```diff
@@ -2099,8 +2076,8 @@ impl TabletSnapManager {
         PathBuf::from(&self.base).join(prefix)
     }
 
-    pub fn delete_snapshot(&self, key: &TabletSnapKey) -> bool {
-        let path = self.tablet_gen_path(key);
+    pub fn delete_snapshot(&self, key: TabletSnapKey) -> bool {
```
Comment (SpadeA-Tang) [inline components/raftstore/src/store/snap.rs:2079]: why remove &?

File: components/raftstore/src/store/snap.rs [hunk 15]
```diff
@@ -1409,7 +1409,6 @@ impl SnapManager {
 
     pub fn init(&self) -> io::Result<()> {
         self.init_core()?;
```
Comment (SpadeA-Tang) [inline components/raftstore/src/store/snap.rs:1411]: now, we can remove this `init` and change the name of `init_core` to `init`

File: components/raftstore/src/store/snap.rs (hunk 13 above)
Comment (BusyJay) [reply components/raftstore/src/store/snap.rs]: > Some tests does not want to use snap manager but want to use struct that has the field of snap manager

What are those cases?

Comment (BusyJay) [reply components/raftstore/src/store/snap.rs]: I don't see `tablet_snap_manager` is used in the case. Can you show it in details?

Comment (SpadeA-Tang) [reply components/raftstore/src/store/snap.rs]: `TabletSnapManager` is a field of `SnapManager`
```
pub struct SnapManager {
    core: SnapManagerCore,
    max_total_size: Arc<AtomicU64>,

    // only used to receive snapshot from v2
    tablet_snap_manager: TabletSnapManager,
}
```

Comment (BusyJay) [reply components/raftstore/src/store/snap.rs]: So what's the problem when `tablet_snap_manager` is defined as `Option<TabletSnapManager>` and become `None` when it's not used?

File: components/raftstore/src/store/snap.rs (hunk 14 above)
Comment (bufferflies) [reply components/raftstore/src/store/snap.rs]: revert

File: components/file_system/src/lib.rs (hunk 9 above)
Comment (bufferflies) [reply components/file_system/src/lib.rs:476]: really fixed

File: components/raftstore/src/store/snap.rs (hunk 13 above)
Comment (SpadeA-Tang) [reply components/raftstore/src/store/snap.rs]: There's no problem for tablet_snap_manager to be defined as Option<TabletSnapManager>, but whether it is None or Some should not be determined by `path == ""` but by whether it's a tiflash engine.

**Review by BusyJay — APPROVED** [review]

**Review by SpadeA-Tang — APPROVED** [review]
