### PR TITLE
test_raftstore: error handling of call_command_on_leader

### LINKED ISSUE #2649: test_server_leader_change_with_uncommitted_log fails with stale command
```
test raftstore_cases::test_multi::test_server_leader_change_with_uncommitted_log ... thread 'raftstore_cases::test_multi::test_server_leader_change_with_uncommitted_log' panicked at 'header {error {message: "stale command" stale_command {}} current_term: 10}', tests/raftstore_cases/test_multi.rs:405:4
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:380
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:396
   4: tikv::util::panic_hook::track_hook::{{closure}}
             at src/util/panic_hook.rs:61
   5: <std::thread::local::LocalKey<T>>::try_with
             at /checkout/src/libstd/thread/local.rs:362
   6: <std::thread::local::LocalKey<T>>::with
             at /checkout/src/libstd/thread/local.rs:276
   7: tikv::util::panic_hook::track_hook
             at src/util/panic_hook.rs:55
   8: core::ops::function::Fn::call
             at /checkout/src/libcore/ops/function.rs:48
   9: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:611
  10: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:571
  11: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:521
  12: integrations::raftstore_cases::test_multi::test_leader_change_with_uncommitted_log
             at tests/raftstore_cases/test_multi.rs:405
  13: integrations::raftstore_cases::test_multi::test_server_leader_change_with_uncommitted_log
             at tests/raftstore_cases/test_multi.rs:422
  14: <F as test::FnBox<T>>::call_box
             at /checkout/src/libtest/lib.rs:1477
             at /checkout/src/libcore/ops/function.rs:143
             at /checkout/src/libtest/lib.rs:138
  15: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:98
FAILED
```

### LINKED ISSUE #3262: test test_server_remove_leader_with_uncommitted_log failed
test_server_remove_leader_with_uncommitted_log failed with prevote.

Backtrace:
```
test raftstore_cases::test_multi::test_server_remove_leader_with_uncommitted_log ... thread 'raftstore_cases::test_multi::test_server_remove_leader_with_uncommitted_log' panicked at 'called `Result::unwrap()` on an `Err` value: Other(StringError("[tests/raftstore/cluster.rs:263]: can\'t get leader of region 1"))', libcore/result.rs:945:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:511
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:426
   6: rust_begin_unwind
             at libstd/panicking.rs:337
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:92
   8: core::result::unwrap_failed
             at /checkout/src/libcore/macros.rs:26
   9: <core::result::Result<T, E>>::unwrap
             at /checkout/src/libcore/result.rs:782
  10: <integrations::raftstore::cluster::Cluster<T>>::request
             at tests/raftstore/cluster.rs:565
  11: <integrations::raftstore::cluster::Cluster<T>>::must_put_cf
             at tests/raftstore/cluster.rs:653
  12: <integrations::raftstore::cluster::Cluster<T>>::must_put
             at tests/raftstore/cluster.rs:649
  13: integrations::raftstore_cases::test_multi::test_remove_leader_with_uncommitted_log
             at tests/raftstore_cases/test_multi.rs:618
  14: integrations::raftstore_cases::test_multi::test_server_remove_leader_with_uncommitted_log
             at tests/raftstore_cases/test_multi.rs:671
  15: integrations::__test::TESTS::{{closure}}
             at tests/raftstore_cases/test_multi.rs:669
  16: core::ops::function::FnOnce::call_once
             at /checkout/src/libcore/ops/function.rs:223
  17: <F as alloc::boxed::FnBox<A>>::call_box
             at libtest/lib.rs:1451
             at /checkout/src/libcore/ops/function.rs:223
             at /checkout/src/liballoc/boxed.rs:640
  18: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
FAILED
```

Log at https://circleci.com/gh/pingcap/tikv/11391

### PR DESCRIPTION
**Pull request by 5kbpers**
Signed-off-by: 5kbpers <tangminghua@pingcap.com>

### What problem does this PR solve?

Issue Number: 
close #3262 

Problem Summary:
Sometimes leader could be elected slowly and also could be changed during CI running.

### What is changed and how it works?

What's Changed:

Better error handling of `call_command_on_leader` to reduce the possibility of test fail.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test

### Release note 
* Not available

### CODE REVIEW

**Review by NingLin-P — APPROVED** [review]
LGTM

File: components/test_raftstore/src/cluster.rs [hunk 1]
```diff
@@ -395,7 +395,7 @@ impl<T: Simulator> Cluster<T> {
         let region_id = request.get_header().get_region_id();
         loop {
             let leader = match self.leader_of_region(region_id) {
-                None => return Err(box_err!("can't get leader of region {}", region_id)),
+                None => return Err(Error::NotLeader(region_id, None)),
```
Comment (BusyJay) [inline components/test_raftstore/src/cluster.rs:398]: But `leader_of_region` already tries for 5 seconds.

Comment (5kbpers) [reply components/test_raftstore/src/cluster.rs:398]: I think the timeout should be controlled by `request`.

**Comment by BusyJay** [comment]
#2649 calls `call_command` instead of `request`, seems not related to this PR.

**Comment by 5kbpers** [comment]
> #2649 calls `call_command` instead of `request`, seems not related to this PR.

Checkout to v2.1.0, it fails on https://github.com/tikv/tikv/blob/v2.1.0/tests/raftstore_cases/test_multi.rs#L422

**Comment by BusyJay** [comment]
You probably look at the wrong version. The stack said it panicked in function `test_leader_change_with_uncommitted_log` instead of `must_transfer_leader`.

**Comment by 5kbpers** [comment]
> You probably look at the wrong version. The stack said it panicked in function `test_leader_change_with_uncommitted_log` instead of `must_transfer_leader`.

@BusyJay Do the archaeological survey again, already removed it.

**Review by BusyJay — APPROVED** [review]

**Review by ti-srebot — APPROVED** [review]
