### PR TITLE
txn: prevent 1pc locks from being skipped when reading with max-ts

### LINKED ISSUE #18117: Reads with max-ts may not see previous writes when async-apply-prewrite is enabled
### What version of TiKV are you using?

master

### Steps to reproduce

ref https://github.com/pingcap/tidb/issues/58677

### What did you expect?

No anomaly detected by jepsen.

### What did happened?

The jepsen test failed.

### PR DESCRIPTION
**Pull request by zyguan**
### What is changed and how it works?

Issue Number: Close #18117 

What's Changed:

```commit-message
Introduce a new field `use_one_pc` to the `Lock` struct to indicate whether the txn uses 1pc, and use it to prevent locks from being skipped when reading with max-ts.
```

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [x] Need to cherry-pick to the release branch

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note

```release-note
Fix an issue that reads cannot see previous writes when `tidb_enable_async_commit = 0`, `tidb_enable_1pc = 1` and `storage.enable-async-apply-prewrite = true`.
```

### CODE REVIEW

File: src/storage/txn/actions/prewrite.rs [hunk 1]
```diff
@@ -618,6 +618,12 @@ impl<'a> PrewriteMutation<'a> {
         if let Some(secondary_keys) = self.secondary_keys {
             lock.use_async_commit = true;
             lock.secondaries = secondary_keys.to_owned();
+        } else if try_one_pc && lock.primary == self.key.to_raw()? {
+            // Set use_async_commit to true when try_one_pc and the key is primary. If
+            // use_async_commit is false and async-prewrite-apply is enabled, there is a
+            // chance that reads with max_ts cannot see the previous writes because the mem
+            // lock can be skipped and the data hasn't been applied yet.
+            lock.use_async_commit = true;
```
Comment (cfzjywxk) [inline src/storage/txn/actions/prewrite.rs:626]: How about wrapping the logic into the `Lock::use_async_commit` function?

Comment (zyguan) [reply src/storage/txn/actions/prewrite.rs:626]: Do you mean to wrap the condition logic? I see `Lock::use_async_commit` is used in decoding a lock from bytes, where there is no txn context (`try_one_pc` & `mutation.key`).

Comment (cfzjywxk) [reply src/storage/txn/actions/prewrite.rs:626]: Yes so the `lock.use_async_commit = true;` is wrapped into one place, but this does indeed require additional input parameters for the wrapped function.

Comment (zyguan) [reply src/storage/txn/actions/prewrite.rs:626]: But `Lock::use_async_commit` is currently used to construct a lock from raw bytes (instead of a prewrite mutation), thus "additional input parameters" are unavailable when constructing from bytes.

Comment (MyonKeminta) [inline src/storage/txn/actions/prewrite.rs:626]: Consider renaming the field to something like ` use_async_commit_or_1pc`?

**Comment by ekexium** [comment]
Seems this is changing the semantics of the variable.
Have we verified that none of the existing usages of use_async_commit depend on its implicit meaning of "not using 1pc"?

**Comment by zyguan** [comment]
> Seems this is changing the semantics of the variable. Have we verified that none of the existing usages of `use_async_commit` depend on its implicit meaning of "not using 1pc"?

Not fully verified, especially when 1pc fallback to 2pc. It seems the current solution is not a good idea. I'm thinking about introducing an another field to the `Lock` struct to indicate that the lock uses 1pc.

**Comment by cfzjywxk** [comment]
Adding a new variable is a safer way, it seems to be fine if the fix is not going to be picked to the release branch.

File: components/txn_types/src/lock.rs [hunk 2]
```diff
@@ -84,6 +84,10 @@ pub struct Lock {
     pub txn_size: u64,
     pub min_commit_ts: TimeStamp,
     pub use_async_commit: bool,
+    // This field is only valid for in-memory locks and does not need to be persisted because:
+    //   1. the lock should be converted to a write directly when 1pc succeeds.
+    //   2. the field should be reverted to false (default value) when 1pc fails.
```
Comment (cfzjywxk) [inline components/txn_types/src/lock.rs:89]: Perhaps we need to reset the flag to false in `fallback_1pc_locks` .

Comment (zyguan) [reply components/txn_types/src/lock.rs:89]: Since the field is not persisted, it just like the flag automatically gets reverted when calling `lock.to_bytes` (fallback_1pc_locks -> txn.put_lock -> lock.to_bytes). Maybe just add a comment to `fallback_1pc_locks`?

Comment (cfzjywxk) [reply components/txn_types/src/lock.rs:89]: That approach is fine as well. We need a mechanism to inform code maintainers about this, minimizing deeply implicit dependencies or constraints.

Comment (MyonKeminta) [reply components/txn_types/src/lock.rs:89]: Personally I prefer setting it to false explicitly, in which way I think the semantics of the code can be more clear

File: src/storage/txn/actions/prewrite.rs [hunk 3]
```diff
@@ -619,11 +619,9 @@ impl<'a> PrewriteMutation<'a> {
...
             lock.secondaries = secondary_keys.to_owned();
         } else if try_one_pc && lock.primary == self.key.to_raw()? {
-            // Set use_async_commit to true when try_one_pc and the key is primary. If
-            // use_async_commit is false and async-prewrite-apply is enabled, there is a
-            // chance that reads with max_ts cannot see the previous writes because the mem
-            // lock can be skipped and the data hasn't been applied yet.
-            lock.use_async_commit = true;
+            // Set `use_one_pc` to true when the key is primary. It's used to prevent the
+            // in-memory lock from being skipped when reading with max_ts.
+            lock.use_one_pc = true;
```
Comment (MyonKeminta) [inline src/storage/txn/actions/prewrite.rs:624]: Do we need to only set it for primary? Perhaps setting it to all locks is better?
...btw I just noticed that `lock.secondaries` seems can be set for no matter primary or secondaries... not sure if it's expected

File: components/txn_types/src/lock.rs (hunk 2 above)
Comment (zyguan) [reply components/txn_types/src/lock.rs:89]: OK, I will update it later.

File: src/storage/txn/actions/prewrite.rs (hunk 3 above)
Comment (zyguan) [reply src/storage/txn/actions/prewrite.rs:624]: > Perhaps setting it to all locks is better?

Hmm... sounds reasonable.

**Review by cfzjywxk — APPROVED** [review]
LGTM

**Review by ekexium — APPROVED** [review]
