### PR TITLE
sst_importer: fix external storage cache block

### LINKED ISSUE #18999: the sst_importer::CacheMap may stuck if there are too many requests and slowing s3 client creation with small runtime threads
## Bug Report
The reproduction unit test if the number of runtime worker threads are less than 11. The async task who hold the `DashMap` mutex is scheduled out because the async `Pending` while every worker thread running the async task trying to lock the `DashMap` mutex. Therefore the deadlock occurs.
```
components/sst_import/src/caching/cache_map.rs
mod tests {
    ...


    #[derive(Clone, Default)]
    struct AsyncCacheChecker(std::sync::Arc<AtomicBool>);
    impl MakeCache for AsyncCacheChecker {
        type Cached = ();
        type Error = Infallible;

        fn make_cache(&self) -> std::result::Result<Self::Cached, Self::Error> {
            self.0.store(true, Ordering::SeqCst);
            futures::executor::block_on(async {
                tokio::time::sleep(std::time::Duration::from_secs(10)).await;
            });
            Ok(())
        }
    }

    #[tokio::test]
    async fn test_deadlock() {
        let rt = tokio::runtime::Builder::new_multi_thread().worker_threads(4).enable_all().build().unwrap();
        let cached = CacheMap::default();

        let mut joins = Vec::new();
        for _ in 0..10 {
            let cached_cloned = cached.clone();
            let j = rt.spawn(async move {
                let c = AsyncCacheChecker::default();
                cached_cloned.cached_or_create("hello", &c).unwrap();
            });
            joins.push(j);
        }
        for j in joins {
            j.await.unwrap();
        }
    }
}
```

### PR DESCRIPTION
**Pull request by Leavrth**
### What is changed and how it works?

Issue Number: Close #18999

What's Changed:

```commit-message
fix external storage cache block
```

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [ ] Need to cherry-pick to the release branch

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note

```release-note
None
```

### CODE REVIEW

File: components/sst_importer/src/sst_importer.rs [hunk 1]
```diff
@@ -487,6 +487,14 @@ impl<E: KvEngine> SstImporter<E> {
         &self,
         backend: &StorageBackend,
         cache_id: &str,
+    ) -> Result<Arc<dyn ExternalStorage>> {
+        tokio::task::block_in_place(|| self.external_storage_or_cache_internal(backend, cache_id))
```
Comment (3pointer) [inline components/sst_importer/src/sst_importer.rs:495]: you can add some comments here, or copy from origin comment

**Review by 3pointer — APPROVED** [review]
rest LGTM

File: components/sst_importer/src/sst_importer.rs (hunk 1 above)
Comment (Leavrth) [reply components/sst_importer/src/sst_importer.rs:495]: done

**Review by 3pointer — APPROVED** [review]

**Review by LykxSassinator — APPROVED** [review]
