### PR TITLE
raftstore: do not override min_matched index with min_committed index

### LINKED ISSUE #18129: TiKV panic with "unstable.slice[1026, 1093] out of bound[1026, 1026]" at src/log_unstable.rs:201
## Bug Report

```
/opt/tidb/kv.log:[2025/01/15 23:14:46.296 +00:00] [FATAL] [lib.rs:480] ["unstable.slice[1026, 1093] out of bound[1026, 1026], raft_id: 29, region_id: 26"] [backtrace="   0: tikv_util::set_panic_hook::{{closure}}
             at /home/stn/tikv/components/tikv_util/src/lib.rs:479:18
   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /home/stn/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2029:9
      std::panicking::rust_panic_with_hook
             at /home/stn/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:783:13
   2: std::panicking::begin_panic_handler::{{closure}}
             at /home/stn/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:657:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /home/stn/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:171:18
   4: rust_begin_unwind
             at /home/stn/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:645:5
   5: core::panicking::panic_fmt
             at /home/stn/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panicking.rs:72:14
   6: raft::log_unstable::Unstable::must_check_outofbounds
             at /home/stn/.cargo/git/checkouts/raft-rs-42b8049ef2e3af07/a76fb6e/src/log_unstable.rs:201:13
   7: raft::log_unstable::Unstable::truncate_and_append
             at /home/stn/.cargo/git/checkouts/raft-rs-42b8049ef2e3af07/a76fb6e/src/log_unstable.rs:169:13
   8: raft::raft_log::RaftLog<T>::append
             at /home/stn/.cargo/git/checkouts/raft-rs-42b8049ef2e3af07/a76fb6e/src/raft_log.rs:395:9
   9: raft::raft_log::RaftLog<T>::maybe_append
             at /home/stn/.cargo/git/checkouts/raft-rs-42b8049ef2e3af07/a76fb6e/src/raft_log.rs:280:17
  10: raftstore::store::peer::Peer<EK,ER>::maybe_append_merge_entries
             at /home/stn/tikv/components/raftstore/src/store/peer.rs:1296:9
  11: raftstore::store::fsm::peer::PeerFsmDelegate<EK,ER,T>::on_catch_up_logs_for_merge
             at /home/stn/tikv/components/raftstore/src/store/fsm/peer.rs:5117:15
      raftstore::store::fsm::peer::PeerFsmDelegate<EK,ER,T>::on_significant_msg
             at /home/stn/tikv/components/raftstore/src/store/fsm/peer.rs:1616:17
  12: raftstore::store::fsm::peer::PeerFsmDelegate<EK,ER,T>::handle_msgs
             at /home/stn/tikv/components/raftstore/src/store/fsm/peer.rs:760:49
  13: <raftstore::store::fsm::store::RaftPoller<EK,ER,T> as batch_system::batch::PollHandler<raftstore::store::fsm::peer::PeerFsm<EK,ER>,raftstore::store::fsm::store::StoreFsm<EK>>>::handle_normal
             at /home/stn/tikv/components/raftstore/src/store/fsm/store.rs:1116:9
      batch_system::batch::Poller<N,C,Handler>::poll
             at /home/stn/tikv/components/batch-system/src/batch.rs:458:27
  14: batch_system::batch::BatchSystem<N,C>::start_poller::{{closure}}
             at /home/stn/tikv/components/batch-system/src/batch.rs:589:17
      <std::thread::Builder as tikv_util::sys::thread::StdThreadBuildWrapper>::spawn_wrapper::{{closure}}
             at /home/stn/tikv/components/tikv_util/src/sys/thread.rs:438:13
      std::sys_common::backtrace::__rust_begin_short_backtrace
             at /home/stn/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:155:18
  15: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
             at /home/stn/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:529:17
      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /home/stn/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panic/unwind_safe.rs:272:9
      std::panicking::try::do_call
             at /home/stn/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:552:40
      std::panicking::try
             at /home/stn/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:516:19
      std::panic::catch_unwind
             at /home/stn/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:142:14
      std::thread::Builder::spawn_unchecked_::{{closure}}
             at /home/stn/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:528:30
      core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /home/stn/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5
  16: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /home/stn/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2015:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /home/stn/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2015:9
      std::sys::unix::thread::Thread::new::thread_start
             at /home/stn/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys/unix/thread.rs:108:17
  17: start_thread
  18: clone
"] [location=/home/stn/.cargo/git/checkouts/raft-rs-42b8049ef2e3af07/a76fb6e/src/log_unstable.rs:201] [thread_name=raftstore-5-1] [thread_id=146]
```

https://tcms.pingcap.net/dashboard/executions/case/13319846

### What version of TiKV are you using?

Nightly 2024-12-27
https://github.com/tikv/tikv/commit/fb67400e73c831fdae6d170c8a934f3a28f0d770

### Steps to reproduce

Run random jepsen tests.

### PR DESCRIPTION
**Pull request by glorv**
### What is changed and how it works?

Issue Number: Close #18129

What's Changed:

```commit-message
During region merge, the CacheUpLogs phase is used to ensure all peers can replicate all the raft logs even if leader is already merged. The original low bound of these logs is calculated by the min matched index of all peers. But in #9982, the bound is replaced with the min committed index, but this is not correct because committed index can not ensure raft state can be recovered from the CatchUpLogs message when the current leader is restarted after proposing PrepareMerge.
```

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [ ] Need to cherry-pick to the release branch

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by LykxSassinator — APPROVED** [review]

File: tests/failpoints/cases/test_merge.rs [hunk 1]
```diff
@@ -2338,3 +2338,75 @@ fn test_raft_log_gc_after_merge() {
...
+
+// This case tests following scenario:
+// When `max_apply_unpersisted_log_limit > 0`, raft leader's applied_index can
+// be higher than committed_index. When the leader propose a merge, in the
+// CatchUpLogs phase, it should ensure the all peers can be recovered from the
+// log even if any peer is restarted in which case it can lose some unpersisted
+// logs. For more details, see: https://github.com/tikv/tikv/issues/18129
+#[test]
+fn test_node_merge_with_apply_ahead_of_persist() {
+    test_util::init_log_for_test();
```
[the remark this answers is not in the document]
Comment (glorv) [reply tests/failpoints/cases/test_merge.rs]: Done

File: components/raftstore/src/store/peer.rs [hunk 2]
```diff
@@ -4301,19 +4301,20 @@ where
...
                 "region_id" => self.region_id,
                 "peer_id" => self.peer.get_id(),
                 "min_matched" => min_m,
                 "min_committed" => min_c,
             );
-            // Reset `min_matched` to `min_committed`, since the raft log at `min_committed`
-            // is known to be committed in all peers, all of the peers should also have
-            // replicated it
-            min_m = min_c;
+            // Do NOT override `min_matched` to `min_committed` here because
```
Comment (overvenus) [inline components/raftstore/src/store/peer.rs:4313]: Can we reject proposing `PrepareMerge` when `min_m < min_c` or even disable early apply completely during region merge?

AFAIK, the region merge (at least part of it) is built on the assumption `min_m >= min_c`[^1].

Also, there is a minor issue: the entry size check might be wrong, now it should account the size of entries from `min_m`[^2]. 

[^1]: https://github.com/tikv/tikv/pull/9982#discussion_r610990186
[^2]: https://github.com/tikv/tikv/blob/55993bf0a6766bd65680b72f5e5ab3b84d3815c2/components/raftstore/src/store/peer.rs#L4365-L4408

Comment (LykxSassinator) [reply components/raftstore/src/store/peer.rs:4313]: > even disable early apply completely during region merge?

FYI, according to the current implementation #16626 -> https://github.com/tikv/tikv/pull/16626/files#diff-78aa13bfc4a34ffc7f594cd5e4b11ed46e2267b3fc650d43bb7371cbb1d76ee1R3781-R3783, it has diabled the early apply feature when the leader pre-proposes `PrepareMerge` request.

Comment (glorv) [reply components/raftstore/src/store/peer.rs:4313]: > Can we reject proposing PrepareMerge when min_m < min_c or even disable early apply completely during region merge?

I'm not sure, but if we reject PrepareMerge when `min_m < min_c`, then it's possible that the region will not be merged forever if `min_m < min_c` is always true due to persistent new writing. Not sure if this has other side effect.

> AFAIK, the region merge (at least part of it) is built on the assumption min_m >= min_c

I don't see why two phase merge depends on this prerequisite.  Actually, the committed_index in leader and follower has different meanings: for follower, it means quorum + self persisted index, but for leader, it only request quorum persisted index but **NOT** self persist. Thus, at least for region leader, requires matched index >= committed index is not reasonable.

File: tests/failpoints/cases/test_merge.rs [hunk 3]
```diff
@@ -2338,3 +2338,73 @@ fn test_raft_log_gc_after_merge() {
     let resp = rx.recv().unwrap();
     assert!(resp.response.get_header().has_error());
 }
+
+// This case tests following scenario:
+// When `max_apply_unpersisted_log_limit > 0`, raft leader's applied_index can
+// be higher than committed_index. When the leader propose a merge, in the
```
Comment (hbisheng) [inline tests/failpoints/cases/test_merge.rs:2344]: > raft leader's applied_index can be higher than committed_index

Would you mind explaining how `applied_index` is related to the problem being solved? From the fix above, it looks like only match_index and committed_index are related. 

In other words, I'd like to understand why this issue didn't happen when "apply before persistence" was turned off. Thx!

Comment (glorv) [reply tests/failpoints/cases/test_merge.rs]: Fixed.

**Comment by glorv** [comment]
@overvenus After discussing with @hbisheng , I found the original issue is not related to `max_apply_unpersisted_log_limit`, and in the new test case, even if I set `max_apply_unpersisted_log_limit = 0` the panic can still occur.
I think the root case is that using committed index as the lower bound is incorrect in the first place.

**Comment by LykxSassinator** [comment]
Seems that the ut `raftstore::test_merge::test_node_merge_prerequisites_check::test_raftstore_new_node_cluster` is failed.

**Review by Connor1996 — APPROVED** [review]
LGTM
