### PR TITLE
raftstore: fix store_heartbeat incorrectly reporting store.is_busy == true.

### LINKED ISSUE #16491: leader and region are not balanced during br restore data and losts of miss-peer region after restore finished
### What version of TiKV are you using?
./tikv-server -V
 TiKV 
Release Version:   8.0.0-alpha
Edition:           Community
Git Commit Hash:   00a2518938f6328a305f70215d60355bfd2a3a9e
Git Commit Branch: heads/refs/tags/v8.0.0-alpha
UTC Build Time:    2024-02-02 11:42:35
Rust Version:      rustc 1.77.0-nightly (89e2160c4 2023-12-27)
Enable Features:   pprof-fp jemalloc mem-profiling portable sse test-engine-kv-rocksdb test-engine-raft-raft-engine cloud-aws cloud-gcp cloud-azure trace-async-tasks openssl-vendored
Profile:           dist_release
2024-02-03T17:24:45.309+0800	

### What operating system and CPU are you using?
8c/32g

### Steps to reproduce
1、br restore data
/br restore db --db tpcc20000 --pd tc-pd.endless-ha-test-with-some-feature-tps-6540279-1-119:2379 --storage \"s3://qe-testing/benchmark/tpcc20000?access-key=xxx&secret-access-key=xxx&endpoint=http%3a%2f%2fks3-cn-beijing-internal.ksyuncs.com&force-path-style=false&region=Beijing&provider=ks\" --send-credentials-to-tikv=true --check-requirements=false

### What did you expect?
leader and region are balanced during br restore data

### What did happened?
leader and region are not balanced during br restore data
img_v3_027o_c6803f2c-70c7-4d0c-a115-4f3d4ed2554g
image
img_v3_027o_bfeaebea-b08a-4c41-b9bc-0c7c0234202g

### PR DESCRIPTION
**Pull request by LykxSassinator**
### What is changed and how it works?

Issue Number: Close #16491

What's Changed:

This pr is used to fix the issue when starting from no regions (new node from empty), store_heartbeat incorrectly reports `store.is_busy == true`.
Meanwhile, the related codes when reporting `store.is_busy` has been polished.

```commit-message

In this pr, `completed_apply_peers_count` is replaced with `Option<u64>` from `u64`.

When initializing, `completed_apply_peers_count` will be set with `Some(0)`. If the check finds
that the store already finishes its `busy_on_apply` check  with `false` or starting from empty regions, this value
will be reset with `None` to mark the check is finished and no need to keep the check anymore next time.
```

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [ ] Need to cherry-pick to the release branch

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

After bugfix:
image

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note

```release-note
None.
```

### CODE REVIEW

**Review by Connor1996 — APPROVED** [review]
LGTM

File: components/raftstore/src/store/fsm/store.rs [hunk 1]
```diff
@@ -2725,8 +2727,15 @@ impl<'a, EK: KvEngine, ER: RaftEngine, T: Transport> StoreFsmDelegate<'a, EK, ER
...
         region_count: u64,
         busy_apply_peers_count: u64,
-        completed_apply_peers_count: u64,
+        completed_apply_peers_count: Option<u64>,
     ) -> bool {
+        // No need to check busy status if there are no regions.
+        if completed_apply_peers_count.is_none() || region_count == 0 {
+            return false;
+        }
+        assert!(completed_apply_peers_count.is_some());
```
Comment (bufferflies) [inline components/raftstore/src/store/fsm/store.rs:2736]: unless assert, remove this.

**Review by bufferflies — APPROVED** [review]
