### PR TITLE
raftstore: move get_region_approximate_size to split check worker

### LINKED ISSUE #9024: PD worker is blocked by `get_region_approximate_size`
## Bug Report

PD worker is blocked by `get_region_approximate_size` for a long time if there are some huge regions. We have met a cluster with a few huge regions (around 50~60 GB), the cluster is not functioning normally to PD schedule (add peers/transfer leader) due to PD worker is blocked.

### What version of TiKV are you using?

v4.0.7

Flamegraph

https://gist.github.com/overvenus/87185107dc291d397021706b013d5ad4

### PR DESCRIPTION
**Pull request by gozssky**
### What problem does this PR solve?

When peer's approximate size or keys is none，region heartbeat need to directly read rocksdb to get size and keys. It will affect other region's heartbeat. This PR move `get_region_approximate_size` and `get_region_approximate_keys`  to split worker's thread so that most regions' heartbeat will go smoothly.

### What is changed and how it works?

What's Changed:

Add a new task type `GetRegionApproximateSizeAndKeys`  to split checker.  For this task, split check worker will read rocksdb to get size and keys, and execute an callback. 

### Check List 

Tests 

- Unit test
- Integration test

### Release note 

- No release note.

### CODE REVIEW

File: components/raftstore/src/store/worker/split_check.rs [hunk 1]
```diff
@@ -335,6 +345,13 @@ where
             Task::ChangeConfig(c) => self.change_cfg(c),
             #[cfg(any(test, feature = "testexport"))]
             Task::Validate(f) => f(&self.cfg),
+            Task::GetRegionApproximateSize { region, cb } => {
+                let keys =
+                    get_region_approximate_keys(&self.engine, &region, 0).unwrap_or_default();
+                let size =
+                    get_region_approximate_size(&self.engine, &region, 0).unwrap_or_default();
+                cb(keys, size);
```
Comment (Little-Wallace) [inline components/raftstore/src/store/worker/split_check.rs:353]: Please also send it back to raftstore.

Comment (gozssky) [reply components/raftstore/src/store/worker/split_check.rs:361]: Done.

File: components/raftstore/src/store/worker/pd.rs [hunk 2]
```diff
@@ -1096,23 +1093,12 @@ where
...
-                let approximate_size = approximate_size.unwrap_or_else(|| {
-                    get_region_approximate_size(&self.db, &region, 0).unwrap_or_default()
+            Task::Heartbeat(hb_task) => {
+                let approximate_size = hb_task.approximate_size.unwrap_or_else(|| {
+                    get_region_approximate_size(&self.db, &hb_task.region, 0).unwrap_or_default()
                 });
-                let approximate_keys = approximate_keys.unwrap_or_else(|| {
-                    get_region_approximate_keys(&self.db, &region, 0).unwrap_or_default()
+                let approximate_keys = hb_task.approximate_keys.unwrap_or_else(|| {
+                    get_region_approximate_keys(&self.db, &hb_task.region, 0).unwrap_or_default()
```
Comment (Little-Wallace) [inline components/raftstore/src/store/worker/pd.rs:1101]: `get_region_approximate_size` is unnecessary here. We do not need to read rocksdb here,

File: components/raftstore/src/store/worker/pd.rs [hunk 3]
```diff
@@ -75,6 +75,19 @@ where
...
+pub struct HeartbeatTask {
+    pub term: u64,
+    pub region: metapb::Region,
+    pub peer: metapb::Peer,
+    pub down_peers: Vec<pdpb::PeerStats>,
+    pub pending_peers: Vec<metapb::Peer>,
+    pub written_bytes: u64,
+    pub written_keys: u64,
+    pub approximate_size: Option<u64>,
+    pub approximate_keys: Option<u64>,
```
Comment (Little-Wallace) [inline components/raftstore/src/store/worker/pd.rs:87]: Please change it to `u64` instead of `Option<u64>`

File: components/raftstore/src/store/worker/pd.rs (hunk 2 above)
Comment (Little-Wallace) [reply components/raftstore/src/store/worker/pd.rs:1101]: Please remove it.

File: components/raftstore/src/store/worker/pd.rs (hunk 3 above)
Comment (gozssky) [reply components/raftstore/src/store/worker/pd.rs]: Done.

File: components/raftstore/src/store/worker/pd.rs (hunk 2 above)
Comment (gozssky) [reply components/raftstore/src/store/worker/pd.rs]: Done.

**Review by Little-Wallace — APPROVED** [review]
LGTM

File: components/raftstore/src/store/worker/split_check.rs [hunk 4]
```diff
@@ -335,6 +348,28 @@ where
             Task::ChangeConfig(c) => self.change_cfg(c),
             #[cfg(any(test, feature = "testexport"))]
             Task::Validate(f) => f(&self.cfg),
+            Task::GetRegionApproximateSizeAndKeys {
+                region,
+                pending_tasks,
+                cb,
+            } => {
+                if pending_tasks.fetch_sub(1, AtomicOrdering::SeqCst) > 1 {
```
Comment (Connor1996) [inline components/raftstore/src/store/worker/split_check.rs:356]: one region may be starving by this always be true

Comment (gozssky) [reply components/raftstore/src/store/worker/split_check.rs:356]: This condition is before io operations. Starving can happen only if  task producing rate is greater than split checker processing(without io) rate. If heartbeat tick is 10 minutes，this will be hard to happen.

File: components/raftstore/src/store/fsm/peer.rs [hunk 5]
```diff
@@ -2219,6 +2245,28 @@ where
...
             new_peer.has_ready |= campaigned;
 
+            // We roughly estimate the size and keys for new region to avoid blocking heartbeat.
+            // But the value may be far from the real value. So we let split checker to update
+            // it immediately.
+            if !self.fsm.peer.is_region_size_or_keys_none() {
+                new_peer.peer.approximate_size =
+                    Some(self.fsm.peer.approximate_size.unwrap() / new_region_count);
+                new_peer.peer.approximate_keys =
+                    Some(self.fsm.peer.approximate_keys.unwrap() / new_region_count);
```
Comment (Little-Wallace) [inline components/raftstore/src/store/fsm/peer.rs:2255]: you have refresh it. So do not need to divide again.

Comment (gozssky) [reply components/raftstore/src/store/fsm/peer.rs]: Oh no，that's really a bug. I have fixed it.

**Review by Little-Wallace — APPROVED** [review]
LGTM

File: components/raftstore/src/store/worker/split_check.rs (hunk 4 above)
Comment (gozssky) [reply components/raftstore/src/store/worker/split_check.rs:356]: @Connor1996  Do you have any suggestions?

File: components/raftstore/src/store/fsm/peer.rs [hunk 6]
```diff
@@ -2125,9 +2127,28 @@ where
...
             panic!("{} original region should exists", self.fsm.peer.tag);
         }
-        // It's not correct anymore, so set it to None to let split checker update it.
-        self.fsm.peer.approximate_size = None;
         let last_region_id = regions.last().unwrap().get_id();
+
+        let new_region_count = regions.len() as u64;
+        // Roughly estimate the size and keys and then let split checker to update it.
+        self.fsm.peer.approximate_size =
+            self.fsm.peer.approximate_size.map(|x| x / new_region_count);
```
Comment (Connor1996) [inline components/raftstore/src/store/fsm/peer.rs:2135]: When Region [a,e) size exceeds `region_max_size`, it will be split into several Regions [a,b), [b,c), [c,d), [d,e) and the size of [a,b), [b,c), [c,d) will be `region_split_size` (or a little larger)

Let's make the this peer's approximate_size to be `x - (region_split_size * (n -1))` and new region peer's to be `region_split_size`

File: components/raftstore/src/store/worker/split_check.rs (hunk 4 above)
Comment (Connor1996) [reply components/raftstore/src/store/worker/split_check.rs:356]: I think `pending_pd_heartbeat_tasks > 2` check in `heartbeat_pd` is enough, and a log there?

File: components/raftstore/src/store/fsm/peer.rs (hunk 6 above)
Comment (gozssky) [reply components/raftstore/src/store/fsm/peer.rs:2135]: It seems this way is more reasonable. And what about the keys calculation?

File: components/raftstore/src/store/worker/split_check.rs (hunk 4 above)
Comment (gozssky) [reply components/raftstore/src/store/worker/split_check.rs:356]: If there are two heartbeats，skip the first can reduce one IO without any side effects. Maybe it is not a bad choice?

Comment (Connor1996) [reply components/raftstore/src/store/worker/split_check.rs:356]: Oh, it's a counter for every peer. I misunderstood the code.

**Review by Connor1996 — APPROVED** [review]
LGTM

**Review by Little-Wallace — COMMENTED** [review]
LGTM

File: components/raftstore/src/store/fsm/peer.rs (hunk 6 above)
Comment (gozssky) [reply components/raftstore/src/store/fsm/peer.rs:2135]: I found it's hard to access `region_split_size` from current peer's member variables. Since the keys and size will be updated by split checker very soon, finally I keep the original implementation.

File: components/raftstore/src/store/fsm/peer.rs [hunk 7]
```diff
@@ -2218,6 +2239,8 @@ where
             new_peer.peer.peer_stat = self.fsm.peer.peer_stat.clone();
             let campaigned = new_peer.peer.maybe_campaign(is_leader);
             new_peer.has_ready |= campaigned;
+            new_peer.peer.approximate_size = self.fsm.peer.approximate_size;
+            new_peer.peer.approximate_keys = self.fsm.peer.approximate_keys;
```
Comment (Little-Wallace) [inline components/raftstore/src/store/fsm/peer.rs:2243]: We only need to change it when it is a leader. So you can do in in next statement.
```
if is_leader {
}
```

File: components/raftstore/src/store/fsm/peer.rs [hunk 8]
```diff
@@ -2255,6 +2278,22 @@ where
...
+                    pending_tasks: Arc::new(AtomicU64::new(1)),
+                    cb: Box::new(move |_, _| {}),
+                },
+            ) {
+                error!(
+                    "failed to schedule split check task";
+                    "region_id" => new_region_id,
+                    "err" => ?e,
+                );
+            }
```
Comment (Little-Wallace) [inline components/raftstore/src/store/fsm/peer.rs:2296]: Judge whether `is_leader`

File: components/raftstore/src/store/fsm/peer.rs (hunk 7 above)
Comment (gozssky) [reply components/raftstore/src/store/fsm/peer.rs]: Done.

File: components/raftstore/src/store/fsm/peer.rs (hunk 8 above)
Comment (gozssky) [reply components/raftstore/src/store/fsm/peer.rs:2298]: Done.

File: components/raftstore/src/store/fsm/peer.rs [hunk 9]
```diff
@@ -2125,9 +2127,28 @@ where
...
+                cb: Box::new(move |_, _| {}),
+            },
+        ) {
+            error!(
+                "failed to schedule split check task";
+                "region_id" => self.fsm.region_id(),
+                "peer_id" => self.fsm.peer_id(),
+                "err" => ?e,
+            );
+        }
```
Comment (gengliqi) [inline components/raftstore/src/store/fsm/peer.rs:2151]: If it's not leader, this task is very wasteful and the `approximate_size` & `approximate_key` are no need to be updated.

Comment (gengliqi) [reply components/raftstore/src/store/fsm/peer.rs:2151]: And I think `self.fsm.peer.heartbeat_pd` should be called here if it's a leader.

Comment (gozssky) [reply components/raftstore/src/store/fsm/peer.rs:2151]: > If it's not leader, this task is very wasteful and the `approximate_size` & `approximate_key` are no need to be updated.

Oh, I didn't notice here in the last update. I will add some check later.

> And I think self.fsm.peer.heartbeat_pd should be called here if it's a leader.

`heartbeat_pd` is called a few lines before here.

Comment (gozssky) [reply components/raftstore/src/store/fsm/peer.rs]: @gengliqi I have updated. PTAL.

Comment (gengliqi) [reply components/raftstore/src/store/fsm/peer.rs]: I think we can move these codes to the upper `if is_leader`.

Comment (gozssky) [reply components/raftstore/src/store/fsm/peer.rs]: I have updated again. Please have a look.

File: components/raftstore/src/store/fsm/peer.rs [hunk 10]
```diff
@@ -2096,8 +2098,18 @@ where
         let region_id = derived.get_id();
         meta.set_region(&self.ctx.coprocessor_host, derived, &mut self.fsm.peer);
         self.fsm.peer.post_split();
+        // It's not correct anymore, so set it to None to let split checker update it.
+        self.fsm.peer.approximate_size = None;
```
Comment (gengliqi) [inline components/raftstore/src/store/fsm/peer.rs:2102]: Hmmm, I think we should remove these lines?

Comment (gozssky) [reply components/raftstore/src/store/fsm/peer.rs:2102]: This is for non-leader peers. As the previous comment says, the size is not correct anymore.

Comment (gozssky) [reply components/raftstore/src/store/fsm/peer.rs:2102]: If we use the estimated size for non-leader peers but not to update it size immediately, I don't know whether there are 
potential risks?

File: components/raftstore/src/store/worker/split_check.rs [hunk 11]
```diff
@@ -335,6 +348,28 @@ where
...
+                let keys =
+                    get_region_approximate_keys(&self.engine, &region, 0).unwrap_or_default();
+                let _ = self.router.send(
+                    region.get_id(),
+                    CasualMessage::RegionApproximateSize { size },
+                );
+                let _ = self.router.send(
+                    region.get_id(),
+                    CasualMessage::RegionApproximateKeys { keys },
+                );
```
Comment (gengliqi) [inline components/raftstore/src/store/worker/split_check.rs:370]: These data may be sent to a different peer instead of the expected one in rare circumstances. I find it is the same as the original code of `RegionApproximateSize/Keys`, which also has this problem. It seems that the side effect is little but it's risky. I will file an issue for that.

File: components/raftstore/src/store/fsm/peer.rs (hunk 10 above)
Comment (gengliqi) [reply components/raftstore/src/store/fsm/peer.rs:2102]: If `self.fsm.peer.approximate_size` is none, the latter `estimated_size` is always none.

Comment (gengliqi) [reply components/raftstore/src/store/fsm/peer.rs:2102]: There is no potential risk because the `approximate_size` and `approximate_keys` are meaningful only on the leader.

Comment (gozssky) [reply components/raftstore/src/store/fsm/peer.rs:2102]: Should it be meaningful if a follower becomes a leader?

> If self.fsm.peer.approximate_size is none, the latter estimated_size is always none.

Sorry, I make a mistake here.

File: components/raftstore/src/store/worker/split_check.rs (hunk 11 above)
Comment (gozssky) [reply components/raftstore/src/store/worker/split_check.rs:370]: Sounds like a potential risk. Please let me know what caused it to happen when you are free.

**Review by gengliqi — APPROVED** [review]

**Review by ti-srebot — APPROVED** [review]
