### PR TITLE
ctl: remove success flashback in retry loop

### LINKED ISSUE #15107: [dr-autosync] tikv flashback hung more than 12h
### What version of TiKV are you using?

6.5.3

### Steps to reproduce

Try to recover tidb cluster after switching from sync_recovery mode to backup dc, after do online recovery succeeded, do flashback to backup to min resolved ts.

### What did you expect?
flashback return and succeeded.

### What did happened?
460d52d8-0137-45ea-a4bb-fa0c5885de2b

### PR DESCRIPTION
**Pull request by HuSharp**
### What is changed and how it works?

Issue Number: Close #15107

What's Changed:

### Problem
- [master/src/server/debug.rs#L1082-L1084](https://github.com/tikv/tikv/blob/master/src/server/debug.rs?rgh-link-date=2023-07-13T07%3A05%3A08Z#L1082-L1084) At finish flashback state, if any future returns an error halfway.
Through the [master/cmd/tikv-ctl/src/main.rs#L941-L947](https://github.com/tikv/tikv/blob/master/cmd/tikv-ctl/src/main.rs?rgh-link-date=2023-07-13T07%3A05%3A08Z#L941-L947) execution, it will continue and retry.
And then since the previous region has already executed the finish flashback, it will always return not in flashback state, and then continue triggering the retry continue, so introduce a dead loop.

### Change summary
- For the `flashback_whole_cluster` function, first get the debug_executor associated with the store
- Attempts to send prepareFlashback req by key range, creating a map called `key_range_to_prepare` to record preparations for flashbacks.
- Create a map called `key_range_to_prepare` to record the key ranges that need to be completed for the flashback.
- When prepareFlashback meet fails, both `key_range_to_prepare` and `key_range_to_finish` need to be updated.
- After all `prepare`s have succeeded, send `finish_flashback`.
- Update `load_key_range` to get "(region_id, leader's store id)" instead of redundant mapping relation
- Add server integration test

```commit-message
```

### Check List 

Tests 

- Integration test
- Manual test (add detailed scripts or steps below)
- No code

Side effects

### Release note 

```release-note
None.
```

### CODE REVIEW

File: cmd/tikv-ctl/src/main.rs [hunk 1]
```diff
@@ -822,41 +822,62 @@ fn flashback_whole_cluster(
     block_on(runtime.spawn(async move {
         // Prepare all regions for flashback.
         let start_ts = pd_client.get_tso().await.unwrap();
-        let mut stores_leader = load_leaders_to_each_store(&pd_client, start_key, end_key);
+        let prepare_stores_leader = Arc::new(RwLock::new(load_leaders_to_each_store(
```
Comment (JmPotato) [inline cmd/tikv-ctl/src/main.rs:825]: Since `try_join_all` will poll all futures one by one, it seems that the lock is unnecessary here?

File: cmd/tikv-ctl/src/main.rs [hunk 2]
```diff
@@ -897,39 +920,56 @@ fn flashback_whole_cluster(
...
+                                key_range.clone(),
+                                start_ts.into_inner(),
+                                commit_ts.into_inner(),
+                            ) {
+                                Ok(_) => {
+                                    need_finish_stores_leader
+                                        .write()
+                                        .unwrap()
+                                        .get_mut(&store_id)
+                                        .unwrap()
```
Comment (JmPotato) [inline cmd/tikv-ctl/src/main.rs:958]: Suggest better not do unwrapping here.

**Review by JmPotato — COMMENTED** [review]
Do we have any test on this case?

File: cmd/tikv-ctl/src/main.rs [hunk 3]
```diff
@@ -822,41 +822,60 @@ fn flashback_whole_cluster(
...
+                                new_debug_executor(&cfg_inner, None, Some(&addr), mgr);
+                            match debug_executor.flashback_to_version(
+                                version,
+                                region_id,
+                                key_range.clone(),
+                                start_ts.into_inner(),
+                                0,
+                            ) {
+                                Ok(_) => {
+                                    prepare_stores_leader
```
Comment (JmPotato) [inline cmd/tikv-ctl/src/main.rs:861]: You just cloned `prepare_stores_leader` at line 843, so this seems meaningless since it won't affect the real `prepare_stores_leader` at all.

File: cmd/tikv-ctl/src/main.rs [hunk 4]
```diff
@@ -899,37 +919,51 @@ fn flashback_whole_cluster(
...
+                                new_debug_executor(&cfg_inner, None, Some(&addr), mgr);
+                            match debug_executor.flashback_to_version(
+                                version,
+                                region_id,
+                                key_range.clone(),
+                                start_ts.into_inner(),
+                                commit_ts.into_inner(),
+                            ) {
+                                Ok(_) => {
+                                    need_finish_stores_leader
```
Comment (JmPotato) [inline cmd/tikv-ctl/src/main.rs:950]: Ditto.

File: cmd/tikv-ctl/src/main.rs (hunk 3 above)
Comment (HuSharp) [reply cmd/tikv-ctl/src/main.rs:861]: fixed. now catch ref.

File: cmd/tikv-ctl/src/main.rs [hunk 5]
```diff
@@ -868,18 +891,14 @@ fn flashback_whole_cluster(
...
-                        for (store_id, leaders) in retry_stores_leader {
-                            let regions = stores_leader
-                                .entry(store_id)
-                                .or_insert_with(HashMap::default);
-                            regions.extend(leaders);
-                        }
+                        let key_range = load_key_range(&pd_client, key_range.start_key.clone(), key_range.end_key.clone());
+                        key_range.into_iter().for_each(|((start_key, end_key), (region_id, store_id))| {
+                            // Need to update `prepare_key_range` to replace stale key range.
+                            let mut check = prepare_key_range.write().unwrap();
```
Comment (JmPotato) [inline cmd/tikv-ctl/src/main.rs:897]: Do we need to lock it inside the `for_each`? Could we just lock it once outside the loop?

File: cmd/tikv-ctl/src/main.rs [hunk 6]
```diff
@@ -868,18 +891,14 @@ fn flashback_whole_cluster(
...
+                            check.insert((start_key.clone(), end_key.clone()), (region_id, store_id));
```
Comment (JmPotato) [inline cmd/tikv-ctl/src/main.rs:898]: Should also delete the old key range.

Comment (HuSharp) [reply cmd/tikv-ctl/src/main.rs:898]: ops, my fault!

**Comment by HuSharp** [comment]
@Connor1996 PTAL, thx!

File: cmd/tikv-ctl/src/main.rs [hunk 7]
```diff
@@ -831,43 +835,68 @@ fn flashback_whole_cluster(
         .unwrap();
 
     block_on(runtime.spawn(async move {
-        // Prepare all regions for flashback.
+        // Get all stores related debug executor.
```
Comment (JmPotato) [inline cmd/tikv-ctl/src/main.rs:838]:
```suggestion
        // Pre-create the debug executors for all stores.
```

File: cmd/tikv-ctl/src/main.rs [hunk 8]
```diff
@@ -831,43 +835,68 @@ fn flashback_whole_cluster(
...
+            .map(|s| {
+                let addr = pd_client.get_store(s.get_id()).unwrap().address;
+                let cfg_inner = cfg.clone();
+                let mgr = Arc::clone(&mgr);
+                let debug_executor = new_debug_executor(&cfg_inner, None, Some(&addr), mgr);
+                (s.get_id(), debug_executor)
+            } )
+            .collect::<HashMap<_, _>>());
+        // Prepare flashback.
         let start_ts = pd_client.get_tso().await.unwrap();
```
Comment (JmPotato) [inline cmd/tikv-ctl/src/main.rs:857]: Better add a TODO here to indicate we could manually pass the `start_ts` and `commit_ts` later.

File: cmd/tikv-ctl/src/main.rs [hunk 9]
```diff
@@ -831,43 +835,68 @@ fn flashback_whole_cluster(
...
-        let mut stores_leader = load_leaders_to_each_store(&pd_client, start_key, end_key);
-        // Need to retry if all regions are not finish prepare.
+        let prepare_key_range = RwLock::new(load_key_range(&pd_client, start_key, end_key));
+        // Need to retry if all regions are not finish.
+        let mut need_finish_key_range = prepare_key_range.read().unwrap().clone();
```
Comment (JmPotato) [inline cmd/tikv-ctl/src/main.rs:860]:
```suggestion
        let mut key_range_to_finish = prepare_key_range.read().unwrap().clone();
```

File: cmd/tikv-ctl/src/main.rs [hunk 10]
```diff
@@ -831,43 +835,68 @@ fn flashback_whole_cluster(
...
+                let mgr = Arc::clone(&mgr);
+                let debug_executor = new_debug_executor(&cfg_inner, None, Some(&addr), mgr);
+                (s.get_id(), debug_executor)
+            } )
+            .collect::<HashMap<_, _>>());
+        // Prepare flashback.
         let start_ts = pd_client.get_tso().await.unwrap();
-        let mut stores_leader = load_leaders_to_each_store(&pd_client, start_key, end_key);
-        // Need to retry if all regions are not finish prepare.
+        let prepare_key_range = RwLock::new(load_key_range(&pd_client, start_key, end_key));
```
Comment (JmPotato) [inline cmd/tikv-ctl/src/main.rs:858]:
```suggestion
        let key_range_to_prepare = RwLock::new(load_key_range(&pd_client, start_key, end_key));
```

File: cmd/tikv-ctl/src/main.rs [hunk 11]
```diff
@@ -971,29 +1006,25 @@ fn flashback_whole_cluster(
...
 }
 
-fn load_leaders_to_each_store(
+// Load (region_id, leader's store id) in the cluster with key ranges.
+fn load_key_range(
     pd_client: &RpcClient,
     start_key: Vec<u8>,
     end_key: Vec<u8>,
-) -> HashMap<u64, HashMap<(Vec<u8>, Vec<u8>), u64>> {
+) -> HashMap<(Vec<u8>, Vec<u8>), (u64, u64)> {
```
Comment (JmPotato) [inline cmd/tikv-ctl/src/main.rs:1014]: Why not just make it return `Vec<metapb::Region>` here? It contains all info we need and does not need to introduce a map with such a redundant structure.

**Review by JmPotato — COMMENTED** [review]
The rest LGTM.

**Comment by HuSharp** [comment]
@Connor1996 @v01dstar PTAL, thx!

File: cmd/tikv-ctl/src/main.rs (hunk 11 above)
Comment (HuSharp) [reply cmd/tikv-ctl/src/main.rs:1014]: - This map is as (key_range, info) to make sure that the unit is keyRange, if we don't map it here, we also need to construct a mapping inside the function.
- Since I only need store_id and region_id, I want to minimize redundant info when the number of regions is large.

File: cmd/tikv-ctl/src/main.rs (hunk 8 above)
Comment (HuSharp) [reply cmd/tikv-ctl/src/main.rs:857]: If specified `ts` manually there seems to be no guarantee that it will always be the maximum and that no other written, which will destroy https://github.com/tikv/tikv/blob/master/src/storage/txn/actions/flashback_to_version.rs#L45 assert.

**Review by JmPotato — APPROVED** [review]

**Review by bufferflies — APPROVED** [review]

**Review by Connor1996 — APPROVED** [review]
LGTM
