### PR TITLE
compact_log_backup: fix compact meta edit filter

### LINKED ISSUE #18843: backup-compact: compact duplicated metadata
### What version of TiKV are you using?

nightly
### Steps to reproduce

compact
### What did you expect?
compacted data won't be compacted
### What did happened?
compacted data will be compacted again

### PR DESCRIPTION
**Pull request by Leavrth**
### What is changed and how it works?

Issue Number: Close #18843

What's Changed:

```commit-message
Merge the same meta edit from different migrations instead of replacing.
```

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [ ] Need to cherry-pick to the release branch

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note

```release-note
None
```

### CODE REVIEW

File: components/compact-log-backup/src/storage.rs [hunk 1]
```diff
@@ -651,6 +658,34 @@ impl MetaEditFilter {
         this
     }
 
+    fn merge_from_meta_edit(&mut self, mut em: MetaEdit) {
+        self.destructed_self = self.destructed_self || em.destruct_self;
+        self.all_data_files_compacted =
+            self.all_data_files_compacted || em.all_data_files_compacted;
+        if self.destructed_self || self.all_data_files_compacted {
```
Comment (3pointer) [inline components/compact-log-backup/src/storage.rs:665]: if `self.all_data_files_compacted` is true while `self.destructed_self` is false.

should we clear the segments here?

**Review by 3pointer — APPROVED** [review]
