### PR TITLE
In-memory engine: consider range overlaps when eviction

### LINKED ISSUE #17131: In-memory Engine: `range` to evict may contain multiple cached range
## Bug Report

Now, the implementation of `evict_range` assumes the range to be evicted is just overlapped(including contain and be contained) with at most one range. However, if delete_range occurs as well as merge, the range may contain multiple cached  ranges.

### PR DESCRIPTION
**Pull request by SpadeA-Tang**
### What is changed and how it works?

Issue Number: Close #17131  Ref #16141

What's Changed:

```commit-message
consider range overlaps when eviction
```

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [ ] Need to cherry-pick to the release branch

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note

```release-note
None
```

### CODE REVIEW

File: components/engine_traits/src/range_cache_engine.rs [hunk 1]
```diff
@@ -203,4 +204,32 @@ mod tests {
...
+        let r1 = CacheRange::new(b"k1".to_vec(), b"k6".to_vec());
+        let r2 = CacheRange::new(b"k2".to_vec(), b"k6".to_vec());
+        assert!(r1.overlaps(&r2));
+        assert!(r2.overlaps(&r1));
+
+        let r1 = CacheRange::new(b"k1".to_vec(), b"k6".to_vec());
+        let r2 = CacheRange::new(b"k1".to_vec(), b"k6".to_vec());
+        assert!(r1.overlaps(&r2));
+        assert!(r2.overlaps(&r1));
+    }
```
Comment (overvenus) [inline components/engine_traits/src/range_cache_engine.rs:234]: Please also tests non overlap cases?

"[k1, k2)" vs "[k2, k3)", "[k1, k2)" vs "[k3, k4)",

File: components/region_cache_memory_engine/src/range_manager.rs [hunk 2]
```diff
@@ -298,30 +298,68 @@ impl RangeManager {
...
+    // There are two cases based on the relationship between `evict_range` and
+    // cached ranges:
+    // 1. `evict_range` is contained(including equals) by a cached range (only one
+    //    due to non-overlapping in cached ranges)
+    // 2. `evict_range` is overlapped with (including contain but not be contained)
+    //    one or more cached ranges
+    //
+    // For 1, if the `evict_range` is a proper subset of the cached_range, we will
+    // split the cached_range so that only the `evict_range` part will be evicted
+    // and deleted.
```
Comment (overvenus) [inline components/region_cache_memory_engine/src/range_manager.rs:311]: Should we adjust tags and ranges of the partially evicted range? Because region split creates new region id and key ranges.

**Review by overvenus — COMMENTED** [review]
Rest LGTM

File: components/region_cache_memory_engine/src/range_manager.rs (hunk 2 above)
Comment (SpadeA-Tang) [reply components/region_cache_memory_engine/src/range_manager.rs:311]: tag is just used for print

**Review by overvenus — APPROVED** [review]

File: components/region_cache_memory_engine/src/range_manager.rs [hunk 3]
```diff
@@ -298,30 +298,66 @@ impl RangeManager {
...
+    //    one due to non-overlapping in cached ranges)
+    // 2. `evict_range` is overlapped with (including contains but not be contained)
+    //    one or more cached ranges
+    //
+    // For 1, if the `evict_range` is a proper subset of the cached_range, we will
+    // split the cached_range so that only the `evict_range` part will be evicted
+    // and deleted.
+    //
+    // For 2, this is caused by some special operations such as merge and delete
+    // range. So, conservertively, we evict all ranges overlap with it.
```
Comment (LykxSassinator) [inline components/region_cache_memory_engine/src/range_manager.rs:314]:
```suggestion
    // range. So, conservatively, we evict all ranges overlap with it.
```

File: components/engine_traits/src/range_cache_engine.rs [hunk 4]
```diff
@@ -136,6 +136,7 @@ impl CacheRange {
         self.start.as_slice() <= key && key < self.end.as_slice()
     }
 
+    // note: overlaps also includes contain
```
Comment (LykxSassinator) [inline components/engine_traits/src/range_cache_engine.rs:139]:
```suggestion
    // Note: overlaps also includes "contain"
```

**Review by LykxSassinator — COMMENTED** [review]
Rest LGTM

File: components/region_cache_memory_engine/src/range_manager.rs (hunk 2 above)
Comment (afeinberg) [reply components/region_cache_memory_engine/src/range_manager.rs:311]: May be clarify and document that tag is not to be used for identification purposes, only for debugging.

File: components/engine_traits/src/range_cache_engine.rs (hunk 4 above)
Comment (afeinberg) [reply components/engine_traits/src/range_cache_engine.rs:139]: nit: "contain" should be "contains" (tenses should agree.)

File: components/region_cache_memory_engine/src/engine.rs [hunk 5]
```diff
@@ -296,12 +296,13 @@ impl RangeCacheMemoryEngine {
...
         let mut core = self.core.write();
-        if core.range_manager.evict_range(range) {
+        let ranges_to_delete = core.range_manager.evict_range(range);
+        if !ranges_to_delete.is_empty() {
             drop(core);
             // The range can be deleted directly.
             if let Err(e) = self
                 .bg_worker_manager()
-                .schedule_task(BackgroundTask::DeleteRange(vec![range.clone()]))
+                .schedule_task(BackgroundTask::DeleteRange(ranges_to_delete))
```
Comment (afeinberg) [inline components/region_cache_memory_engine/src/engine.rs:305]: is this in any way inconsistent with some of the logic I added for eviction in the most change?

File: components/region_cache_memory_engine/src/write_batch.rs [hunk 6]
```diff
@@ -547,12 +548,18 @@ impl Mutable for RangeCacheWriteBatch {
         Ok(())
     }
 
-    fn delete_range(&mut self, _: &[u8], _: &[u8]) -> Result<()> {
-        unimplemented!()
+    // rather than delete the keys in the range, we evict ranges overlap with them
```
Comment (afeinberg) [inline components/region_cache_memory_engine/src/write_batch.rs:551]:
```suggestion
    // rather than delete the keys in the range, we evict ranges that overlap with them
```

**Review by afeinberg — APPROVED** [review]

File: components/region_cache_memory_engine/src/engine.rs (hunk 5 above)
Comment (SpadeA-Tang) [reply components/region_cache_memory_engine/src/engine.rs:305]: The inconsistent may exist on my another PR https://github.com/tikv/tikv/pull/17149. I will check it there.

**Review by LykxSassinator — APPROVED** [review]
