### PR TITLE
In-memory Engine: evict range on ingest sst

### LINKED ISSUE #17182: In-memory Engine: range should be evicted after sst ingestion
## Bug Report

Both Lightning import and BR restore will read ingest data for checksum verification. However, TiKV currently does not load SST files immediately after ingestion. This delay causes checksum mismatches, leading to failures in Lightning and BR.

### What version of TiKV are you using?

Nightly, 2024-06-23

### Steps to reproduce

Just run BR restore.

### PR DESCRIPTION
**Pull request by overvenus**
### What is changed and how it works?

Issue Number: Close #17182

What's Changed:

```commit-message
Both Lightning import and BR restore will read ingest data for checksum
verification. However, TiKV currently does not load SST files immediately
after ingestion. This delay causes checksum mismatches, leading to
failures in Lightning and BR.

This commit workaround such issue by evict ranges that are ingested sst.
```

### Check List

Tests 

- [x] Unit test
- [x] Integration test

### Release note

```release-note
None
```

### CODE REVIEW

**Review by zhangjinpeng87 — APPROVED** [review]
LGTM, it is a great job to gather all kinds of eviction into one place.

File: components/hybrid_engine/src/observer.rs [hunk 1]
```diff
@@ -0,0 +1,259 @@
...
+        if !self.cache_engine.range_cache_engine_enabled() {
+            return;
+        }
+        // Evict caches for successfully executed ingest commands and admin
+        // commands that change region range.
+        if apply.pending_handle_ssts.is_some()
+            || (state.modified_region.is_some()
+                && matches!(
+                    cmd.request.get_admin_request().get_cmd_type(),
+                    AdminCmdType::BatchSplit
```
Comment (SpadeA-Tang) [inline components/hybrid_engine/src/observer.rs:69]: The range can still servce requests after batch split (it still has complete data view), so it should not evict.

**Review by SpadeA-Tang — APPROVED** [review]
