### PR TITLE
resource_control: fix virtual time overflow

### LINKED ISSUE #14507: resource_control: virtual time overflow after update_min_virtual_time
### What version of TiKV are you using?

nightly

### Steps to reproduce

Create a  resource group rg1 with ru_per_sec = 1 and several resource group with random ru rate and then run some workload on all the resource groups.

### What did you expect?
The virtual time will be reset periodically

### What did happened?
In some case, the virtual time is reset very often anormally.

### PR DESCRIPTION
**Pull request by glorv**
### What is changed and how it works?

Issue Number: Close #14507

What's Changed:
- Add a lock to ensure `update_min_virtual_time` is always called by a single thread
- remove the call of `(vt - max_vt)/2` because at that time vt might increase and is bigger that the former `max_vt` and this can cause overflow.

```
Fix virtual time overflow by avoiding substracting bigger value than self.
```

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

Side effects

- Performance regression

### Release note 

```release-note
None
```

### CODE REVIEW

File: components/resource_control/src/resource_group.rs [hunk 1]
```diff
@@ -267,15 +281,19 @@ impl ResourceController {
                 // but it should be ok as this operation should be extremely rare
                 // and the impact is not big.
                 if near_overflow {
-                    tracker.decrease_vt(RESET_VT_THRESHOLD - (max_vt - vt) / 2);
+                    tracker.decrease_vt(RESET_VT_THRESHOLD);
```
Comment (nolouch) [inline components/resource_control/src/resource_group.rs:284]: I think the essential problem is  the growth rate of `vt` be very fast, especially for relatively `hot group`, then the `update_min_virtual_time` cannot catch up it to avoid the overflow rate. maybe we can try to decrease the weight factor with some normalization methods?

Comment (glorv) [reply components/resource_control/src/resource_group.rs:284]: The maximum weight is MaxInt32 when the ru_per_sec = 1, in this case if a resource_group is overflow in 1s, the resource consumation should be 2^60/2/2^31 = 2^28 that is about 268M. This is not a very big number as our cpu time is managed in microseconds, so in the extreme case, if a resource group consumes more than 268 seconds cpu or write more than 268M bytes within 1s, the `update_min_virtual_time` is not fast enough to handle.  
In my test, with ru_per_sec = 1 and 8c tikv server, it takes a read workload about 1min to trigger this overflow.

BTW, the PR here is to fix the bug that because the `vt` is load after `max_vt`, in my test with 128 groups, the duration is about 10us, so it is possible some resource group's `vt` has grown bigger than the `max_vt`, thus `max-vt` is negatively overflow and  cause `RESET_VT_THRESHOLD - (max_vt - vt) / 2` to be about `u64::MAX/2`.

I original thought this overflow is not triggered very often because it has some side effect that can impact the task lantency because of task priority's disorder. Maybe we can rollback to the old algorithm to use a dynamic task wight formula and special handle the default weight if it is the default maximum value.

File: components/resource_control/src/resource_group.rs [hunk 2]
```diff
@@ -267,15 +281,19 @@ impl ResourceController {
...
                 } else if vt < max_vt {
                     // TODO: is increase by half is a good choice.
                     tracker.increase_vt((max_vt - vt) / 2);
                 }
             });
         if near_overflow {
-            info!("all reset groups' virtual time are near overflow, do reset");
+            let end = Instant::now_coarse();
+            info!("all resource groups' virtual time are near overflow, do reset";
```
[the remark this answers is not in the document]
Comment (glorv) [reply components/resource_control/src/resource_group.rs:292]: In the normal case, the overflow should not be very often, we expect the reset duration should be more than 1 day, so a metrics here seems not very helpfully, the log is used for potential debug convenience.

**Review by nolouch — APPROVED** [review]
lgtm

File: components/resource_control/src/resource_group.rs [hunk 3]
```diff
@@ -240,6 +244,14 @@ impl ResourceController {
     }
 
     pub fn update_min_virtual_time(&self) {
+        let mut guard = match self.lock.try_lock() {
+            Ok(g) => g,
+            Err(_) => {
+                // another thread is still processing, just return.
```
Comment (Connor1996) [inline components/resource_control/src/resource_group.rs:250]: I think it won't have another thread as there is a lock in `advance_min_virtual_time`

Comment (glorv) [reply components/resource_control/src/resource_group.rs]: done, removed.

**Review by Connor1996 — APPROVED** [review]
LGTM
