### PR TITLE
*: ignore tombstone stores

### LINKED ISSUE #4221: TiKV/Importer should ignore tombstoned stores
## Bug Report

Currently TiKV/Importer gets all stores via the `get_all_stores` API. Its result includes tombstoned stores. TiKV/Importer should ignore them, otherwise there will be unexpected behaviors, eg, try to connect to an invalid address https://github.com/pingcap/tidb/issues/9269 .

### PR DESCRIPTION
**Pull request by overvenus**
## What have you changed? (mandatory)

Ignore tombstone stores.

## What are the type of the changes? (mandatory)

- Bug fix (non-breaking change which fixes an issue)

## How has this PR been tested? (mandatory)

Unit tests.

## Does this PR affect documentation (docs) update? (mandatory)

No

## Does this PR affect tidb-ansible update? (mandatory)

No.

## Refer to a related PR or issue link (optional)

Fixes #4221 
Cc https://github.com/pingcap/tidb/issues/9269

### CODE REVIEW

File: src/pd/client.rs [hunk 1]
```diff
@@ -210,10 +210,15 @@ impl PdClient for RpcClient {
         })?;
         check_resp_header(resp.get_header())?;
 
-        Ok(resp.take_store())
+        let store = resp.take_store();
+        if store.get_state() != metapb::StoreState::Tombstone {
+            Ok(store)
+        } else {
+            Err(Error::StoreTombstone(format!("{:?}", store)))
```
Comment (zhangjinpeng1987) [inline src/pd/client.rs]: Why return error when the store is `Tombstone`?

File: src/pd/util.rs [hunk 2]
```diff
@@ -473,16 +473,18 @@ pub fn try_connect_leader(
...
     }
-    // TODO: translate more error types
     let err = header.get_error();
     match err.get_field_type() {
         ErrorType::ALREADY_BOOTSTRAPPED => Err(Error::ClusterBootstrapped(header.get_cluster_id())),
         ErrorType::NOT_BOOTSTRAPPED => Err(Error::ClusterNotBootstrapped(header.get_cluster_id())),
         ErrorType::INCOMPATIBLE_VERSION => Err(Error::Incompatible),
-        _ => Err(box_err!(err.get_message())),
+        ErrorType::STORE_TOMBSTONE => Err(Error::StoreTombstone(err.get_message().to_owned())),
+        ErrorType::UNKNOWN => Err(box_err!(err.get_message())),
```
Comment (zhangjinpeng1987) [inline src/pd/util.rs]: When the UNKNOWN error type will be returned?

Comment (overvenus) [reply src/pd/util.rs]: It depends on PD.

File: src/pd/client.rs (hunk 1 above)
Comment (overvenus) [reply src/pd/client.rs]: Tombstone stores are no longer belongs to the cluster, other TiKVs should ignore such stores. See more pingcap/tidb#9269

File: src/pd/client.rs [hunk 3]
```diff
@@ -226,7 +231,15 @@ impl PdClient for RpcClient {
...
         check_resp_header(resp.get_header())?;
 
-        Ok(resp.take_stores().to_vec())
+        let mut stores = resp.take_stores().to_vec();
+        if !include_tombstone {
+            for i in (0..stores.len()).rev() {
+                if stores[i].get_state() == metapb::StoreState::Tombstone {
+                    stores.swap_remove(i);
+                }
+            }
```
Comment (kennytm) [inline src/pd/client.rs]: If we are allowed to use nightly APIs this could be simplified as

```rust
#![feature(drain_filter)]

stores.drain_filter(|s| s.get_state() == metapb::StoreState::Tombstone);
```

However according to rust-lang/rust#43244 there isn't a consensus on the exact behavior, so it would likely stay unstable for quite a long time.

File: src/pd/client.rs [hunk 4]
```diff
@@ -210,10 +210,15 @@ impl PdClient for RpcClient {
...
+        let store = resp.take_store();
+        if store.get_state() != metapb::StoreState::Tombstone {
+            Ok(store)
+        } else {
+            Err(Error::StoreTombstone(format!("{:?}", store)))
+        }
     }
 
-    fn get_all_stores(&self) -> Result<Vec<metapb::Store>> {
+    fn get_all_stores(&self, include_tombstone: bool) -> Result<Vec<metapb::Store>> {
```
Comment (zhangjinpeng1987) [inline src/pd/client.rs]: I think PD support such API is more elegant. BTW, how lightning interact with this API?

Comment (kennytm) [reply src/pd/client.rs]: Lightning doesn't interact with TiKV stores directly, Importer does (`src/import/import.rs` in this PR). 

Importer uses this API to get all TiKV nodes to forward the "switch to import mode" or "compact cluster" command. It doesn't affect SST ingestion.

Comment (kennytm) [reply src/pd/client.rs]: Lightning doesn't interact with TiKV stores directly, Importer does (`src/import/import.rs` in this PR). 

Importer uses this API to get all TiKV nodes to forward the "switch to import mode" or "compact cluster" command. It doesn't affect SST ingestion.

Comment (zhangjinpeng1987) [reply src/pd/client.rs]: Got it.

File: src/pd/client.rs (hunk 1 above)
Comment (siddontang) [reply src/pd/client.rs]: seem we don't need to use a string for the StoreTombstone. maybe integer is enough.

Comment (overvenus) [reply src/pd/client.rs]: PD may return StoreTombston error too, but it does not contain a store id, so I choose string for simplicity.

File: src/pd/client.rs (hunk 3 above)
Comment (overvenus) [reply src/pd/client.rs]: I think `swap_remove` is fine. :thinking:

File: src/pd/client.rs (hunk 4 above)
Comment (overvenus) [reply src/pd/client.rs]: Cc @nolouch What do you think? Is it ok to support this feature in PD side?

File: src/import/client.rs [hunk 5]
```diff
@@ -107,7 +107,8 @@ impl Client {
 
     pub fn switch_cluster(&self, req: &SwitchModeRequest) -> Result<()> {
         let mut futures = Vec::new();
-        for store in self.pd.get_all_stores()? {
+        // do not include tombstone stores.
```
Comment (Connor1996) [inline src/import/client.rs]: use capital word at the beginning.

File: src/pd/client.rs (hunk 4 above)
Comment (nolouch) [reply src/pd/client.rs]: I think it's ok to do that.

**Comment by overvenus** [comment]
PTAL
/run-all-tests

**Comment by overvenus** [comment]
@huachaohuang PTAL, thanks!

**Comment by huachaohuang** [comment]
When I first added this `get_all_stores` API, I didn't expect PD to return tombstone stores at all (yes, I implemented that API in PD too, sorry :joy:). IMO, it's more elegant to fix this in PD, and we can add an option like `include_tombstones` in the request if we really need that in the future.

**Comment by overvenus** [comment]
> IMO, it's more elegant to fix this in PD, and we can add an option like `include_tombstones` in the request if we really need that in the future.

Yes, but it does not with to this PR, they all have the same API. Some users already met this bug, so I think we should merge this PR ASAP.

**Comment by huachaohuang** [comment]
@overvenus how about just fixing this in PD?
https://github.com/pingcap/pd/pull/1440

**Comment by kennytm** [comment]
Could we have a solution that can be easily cherry-picked to 2.1?

**Comment by overvenus** [comment]
PTAL, thanks!
