### PR TITLE
copr: Improve `BitVec` perf

### LINKED ISSUE #8504: copr: optimize ChunkedVecSized performance
## Development Task

https://github.com/tikv/tikv/pull/8503 adds benchmark for structures modified in Chunk-based Computing RFC. The result shows that `ChunkedVecSized<T>` is 2x slower than original `Vec<Option<T>>`. We should figure out what caused such regression, and optimize performance of `ChunkedVecSized`.

image

### PR DESCRIPTION
**Pull request by vn-ki**
Signed-off-by: Vishnunarayan K I <appukuttancr@gmail.com>

### What problem does this PR solve?

Issue Number: close #8504 

Problem Summary:

### What is changed and how it works?

What's Changed:
- [x] use `u64` instead of `u8`
- [x] maunually inline usage of `BitVec::replace` in `BitVec::push` because
  the assert seems to be not inlined (ref: https://rust.godbolt.org/z/Y5bb8d)
 
The perf measurements on my system shows improvements but it is fluctuating too much to be of any use. Opening PR to macro bench the changes.

### Check List 

Tests 

- [x] Unit test
- Integration test
- [ ] Manual test (add detailed scripts or steps below)

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### CODE REVIEW

File: components/tidb_query_datatype/src/codec/data_type/bit_vec.rs [hunk 1]
```diff
@@ -1,17 +1,17 @@
 // Copyright 2020 TiKV Project Authors. Licensed under Apache-2.0.
 
-/// A boolean vector, which consolidates 8 booleans into 1 u8 to save space.
+/// A boolean vector, which consolidates 8 booleans into 1 u64 to save space.
```
Comment (skyzh) [inline components/tidb_query_datatype/src/codec/data_type/bit_vec.rs:3]: should be 64 booleans

**Review by skyzh — APPROVED** [review]
rest LGTM

**Comment by skyzh** [comment]
Please merge latest master so as to solve the build issue.

File: components/tidb_query_datatype/src/codec/data_type/bit_vec.rs [hunk 2]
```diff
@@ -1,17 +1,17 @@
 // Copyright 2020 TiKV Project Authors. Licensed under Apache-2.0.
 
-/// A boolean vector, which consolidates 8 booleans into 1 u8 to save space.
+/// A boolean vector, which consolidates 64 booleans into 1 u64 to save space.
 ///
 /// `BitVec` is mainly used to implement bitmap in ChunkedVec.
 #[derive(Debug, PartialEq, Clone)]
 pub struct BitVec {
```
Comment (BusyJay) [inline components/tidb_query_datatype/src/codec/data_type/bit_vec.rs:7]: Why not use https://docs.rs/bitvec/0.19.2/bitvec/vec/struct.BitVec.html?

Comment (skyzh) [reply components/tidb_query_datatype/src/codec/data_type/bit_vec.rs:7]: When evaluating vectorized functions, we need to apply bitwise and on several BitVec. This can be done efficiently by bitwise and a whole u8 or u64. When I was prototyping the original version of BitVec, it seems that bitvec crate doesn't provide such functionality.

Comment (skyzh) [reply components/tidb_query_datatype/src/codec/data_type/bit_vec.rs:7]: Seems that there is a [bitwise and function](https://docs.rs/bitvec/0.19.2/bitvec/vec/struct.BitVec.html#method.bitand) for bitvec crate. Maybe we could migrate to `bitvec` and do some benchmark.

Comment (vn-ki) [reply components/tidb_query_datatype/src/codec/data_type/bit_vec.rs:7]: I ran the micro benchmarks of `ChunkedVecSized` by removing the `push` into `BitVec` and what I found from the results on my machine is that `BitVec` is not the biggest contributor to overhead. Do you think it's still worth exploring `bitvec` crate?

Comment (skyzh) [reply components/tidb_query_datatype/src/codec/data_type/bit_vec.rs:7]: From my benchmark result https://github.com/tikv/tikv/issues/8504 it seems that BitVec push takes 1.5x time of vec push, that's why I suggest optimize bitvec performance. I may run the micro benchmark later to verify the result.

**Comment by vn-ki** [comment]
On master
```
running 2 tests
test codec::data_type::chunked_vec_sized::benches::bench_append                           ... bench:      44,518 ns/iter (+/- 6,718)
test codec::data_type::chunked_vec_sized::benches::bench_append_option_vec                ... bench:      24,067 ns/iter (+/- 5,985)
```

With this patch
```
running 2 tests
test codec::data_type::chunked_vec_sized::benches::bench_append                           ... bench:      30,713 ns/iter (+/- 4,102)
test codec::data_type::chunked_vec_sized::benches::bench_append_option_vec                ... bench:      24,949 ns/iter (+/- 3,722)
```

```rust
    #[bench]
    fn bench_append(b: &mut test::Bencher) {
        b.iter(|| {
            let mut chunked_vec_int = ChunkedVecSized::with_capacity(10000);
            for _i in 0..5000 {
                chunked_vec_int.push(Some(233));
                chunked_vec_int.push(None);
            }
        });
    }

    #[bench]
    fn bench_append_option_vec(b: &mut test::Bencher) {
        b.iter(|| {
            let mut vec: Vec<Option<i32>> = Vec::with_capacity(10000);
            for _i in 0..5000 {
                vec.push(Some(233));
                vec.push(None);
            }
        });
    }
```

**Comment by vn-ki** [comment]
One more optimisation that can be done is that when pushing a null, we don't have to set the mask.

That change makes bitvec push practically free. But that also means that additional logic has to be introduced in `BitVec::truncate` for correctness. Therefore I'm not very sure about whether it is worth it. (I also haven't done extensive testing, maybe it may have unforeseen consequences).

```
running 2 tests
test codec::data_type::chunked_vec_sized::benches::bench_append                           ... bench:      25,864 ns/iter (+/- 460)
test codec::data_type::chunked_vec_sized::benches::bench_append_option_vec                ... bench:      24,675 ns/iter (+/- 655)
```

```diff
diff --git a/components/tidb_query_datatype/src/codec/data_type/bit_vec.rs b/components/tidb_query_datatype/src/codec/data_type/bit_vec.rs
index d72116273..1bf8ae6ef 100644
--- a/components/tidb_query_datatype/src/codec/data_type/bit_vec.rs
+++ b/components/tidb_query_datatype/src/codec/data_type/bit_vec.rs
@@ -32,8 +32,6 @@ impl BitVec {
         self.length += 1;
         if value {
             self.data[idx] |= mask;
-        } else {
-            self.data[idx] &= !mask;
         }
     }
 
@@ -59,7 +57,17 @@ impl BitVec {
     pub fn truncate(&mut self, len: usize) {
         if len < self.length {
             self.length = len;
-            self.data.truncate(Self::upper_bound(len));
+            let idx = Self::upper_bound(len);
+            self.data.truncate(idx);
+            if idx != 0 {
+                let rem = self.length % BITS;
+                let mask: u64 = if rem == 0 {
+                    0
+                } else {
+                    0xffffffffffffffff << rem
+                };
+                self.data[idx-1] &= !mask;
+            }
         }
     }
```

**Comment by skyzh** [comment]
You can open another PR to add this optimization it after this PR gets merged. Thanks for your work!

**Comment by breeswish** [comment]
@skyzh Is this PR ready to merge?

**Comment by skyzh** [comment]
> @skyzh Is this PR ready to merge?

Yes

**Review by breeswish — APPROVED** [review]
Thanks!

**Review by ti-srebot — APPROVED** [review]
