### PR TITLE
pd_client:  fix the kvproto compatibility for global config

### LINKED ISSUE #14042: fix kvproto
## Development Task

Due to operation error, the kvproto was updated in advance https://github.com/pingcap/kvproto/pull/1035
so this pr  is just for make sure compatibility
No one is currently using this interface and there is already a corresponding pr https://github.com/tikv/tikv/pull/14022

### PR DESCRIPTION
**Pull request by HuSharp**
Signed-off-by: husharp <jinhao.hu@pingcap.com>

### What is changed and how it works?

Issue Number: close #14042 

What's Changed:

```commit-message
Due to operation error, the kvproto was updated in advance https://github.com/pingcap/kvproto/pull/1035
so this pr  is just for make sure compatibility
No one is currently using this interface and there is already a corresponding pr https://github.com/tikv/tikv/pull/14022
```

### Check List 

Tests 

- Unit test

```release-note
None
```

### CODE REVIEW

**Review by JmPotato — APPROVED** [review]

**Review by ekexium — APPROVED** [review]

File: components/pd_client/src/lib.rs [hunk 1]
```diff
@@ -209,7 +209,7 @@ pub const INVALID_ID: u64 = 0;
 /// all the time.
 pub trait PdClient: Send + Sync {
     /// Load a list of GlobalConfig
-    fn load_global_config(&self, _list: Vec<String>) -> PdFuture<HashMap<String, String>> {
+    fn load_global_config(&self, _config_path: String) -> PdFuture<HashMap<String, String>> {
```
Comment (Connor1996) [inline components/pd_client/src/lib.rs:212]: the change is breaking, please make sure no one is using it, otherwise adding a new interface instead

**Review by Connor1996 — APPROVED** [review]
