### PR TITLE
raftstore: ignore stale read states

### LINKED ISSUE #12046: RaftStore panicked with out of bounds access error
### What version of TiKV are you using?

master @ cbcaab6ce56cdc0a503a5f9171470bff3c0b53da

### What operating system and CPU are you using?

kubernetes

### Steps to reproduce

Run jepsen monotonic test.

### What did you expect?

No unexpected panic of tikv during test.

### What did happened?

RaftStore panicked as the following log shown
```
[2022/02/27 10:11:04.211 +00:00] [FATAL] [lib.rs:466] ["Out of bounds access"] [backtrace="   0: tikv_util::set_panic_hook::{{closure}}\n             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/tikv_util/src/lib.rs:465:18\n   1: std::panicking::rust_panic_with_hook\n             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/panicking.rs:702:17\n   2: std::panicking::begin_panic_handler::{{closure}}\n             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/panicking.rs:588:13\n   3: std::sys_common::backtrace::__rust_end_short_backtrace\n             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/sys_common/backtrace.rs:138:18\n   4: rust_begin_unwind\n             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/panicking.rs:584:5\n   5: core::panicking::panic_fmt\n             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/core/src/panicking.rs:143:14\n   6: core::panicking::panic_display\n             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/core/src/panicking.rs:73:5\n   7: core::panicking::panic_str\n             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/core/src/panicking.rs:56:5\n   8: core::option::expect_failed\n             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/core/src/option.rs:1852:5\n   9: core::option::Option<T>::expect\n             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/core/src/option.rs:715:21\n      <alloc::collections::vec_deque::VecDeque<T,A> as core::ops::index::Index<usize>>::index\n             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/alloc/src/collections/vec_deque/mod.rs:2853:9\n      raftstore::store::read_queue::ReadIndexQueue<S>::advance_leader_reads\n             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/read_queue.rs:238:30\n      raftstore::store::peer::Peer<EK,ER>::apply_reads\n             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/peer.rs:2694:13\n      raftstore::store::peer::Peer<EK,ER>::handle_raft_ready_append\n             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/peer.rs:2092:9\n  10: raftstore::store::fsm::peer::PeerFsmDelegate<EK,ER,T>::collect_ready\n             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/fsm/peer.rs:1307:19\n      <raftstore::store::fsm::store::RaftPoller<EK,ER,T> as batch_system::batch::PollHandler<raftstore::store::fsm::peer::PeerFsm<EK,ER>,raftstore::store::fsm::store::StoreFsm<EK>>>::handle_normal\n             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/fsm/store.rs:791:13\n  11: batch_system::batch::Poller<N,C,Handler>::poll\n             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/batch-system/src/batch.rs:446:27\n  12: raftstore::store::worker::refresh_config::PoolController<N,C,H>::increase_by::{{closure}}\n             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/worker/refresh_config.rs:71:21\n      std::sys_common::backtrace::__rust_begin_short_backtrace\n             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/sys_common/backtrace.rs:122:18\n  13: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}\n             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/thread/mod.rs:498:17\n      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once\n             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/core/src/panic/unwind_safe.rs:271:9\n      std::panicking::try::do_call\n             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/panicking.rs:492:40\n      std::panicking::try\n             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/panicking.rs:456:19\n      std::panic::catch_unwind\n             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/panic.rs:137:14\n      std::thread::Builder::spawn_unchecked_::{{closure}}\n             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/thread/mod.rs:497:30\n      core::ops::function::FnOnce::call_once{{vtable.shim}}\n             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/core/src/ops/function.rs:227:5\n  14: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once\n             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/alloc/src/boxed.rs:1854:9\n      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once\n             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/alloc/src/boxed.rs:1854:9\n      std::sys::unix::thread::Thread::new::thread_start\n             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/sys/unix/thread.rs:108:17\n  15: start_thread\n  16: clone\n"] [location=/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/read_queue.rs:238] [thread_name=raftstore-7-0]
   0: tikv_util::set_panic_hook::{{closure}}
             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/tikv_util/src/lib.rs:465:18
   1: std::panicking::rust_panic_with_hook
             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/panicking.rs:702:17
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/panicking.rs:588:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/sys_common/backtrace.rs:138:18
   4: rust_begin_unwind
             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/panicking.rs:584:5
   5: core::panicking::panic_fmt
             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/core/src/panicking.rs:143:14
   6: core::panicking::panic_display
             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/core/src/panicking.rs:73:5
   7: core::panicking::panic_str
             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/core/src/panicking.rs:56:5
   8: core::option::expect_failed
             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/core/src/option.rs:1852:5
   9: core::option::Option<T>::expect
             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/core/src/option.rs:715:21
      <alloc::collections::vec_deque::VecDeque<T,A> as core::ops::index::Index<usize>>::index
             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/alloc/src/collections/vec_deque/mod.rs:2853:9
      raftstore::store::read_queue::ReadIndexQueue<S>::advance_leader_reads
             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/read_queue.rs:238:30
      raftstore::store::peer::Peer<EK,ER>::apply_reads
             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/peer.rs:2694:13
      raftstore::store::peer::Peer<EK,ER>::handle_raft_ready_append
             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/peer.rs:2092:9
  10: raftstore::store::fsm::peer::PeerFsmDelegate<EK,ER,T>::collect_ready
             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/fsm/peer.rs:1307:19
      <raftstore::store::fsm::store::RaftPoller<EK,ER,T> as batch_system::batch::PollHandler<raftstore::store::fsm::peer::PeerFsm<EK,ER>,raftstore::store::fsm::store::StoreFsm<EK>>>::handle_normal
             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/fsm/store.rs:791:13
  11: batch_system::batch::Poller<N,C,Handler>::poll
             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/batch-system/src/batch.rs:446:27
  12: raftstore::store::worker::refresh_config::PoolController<N,C,H>::increase_by::{{closure}}
             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/worker/refresh_config.rs:71:21
      std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/sys_common/backtrace.rs:122:18
  13: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/thread/mod.rs:498:17
      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/core/src/panic/unwind_safe.rs:271:9
      std::panicking::try::do_call
             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/panicking.rs:492:40
      std::panicking::try
             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/panicking.rs:456:19
      std::panic::catch_unwind
             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/panic.rs:137:14
      std::thread::Builder::spawn_unchecked_::{{closure}}
             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/thread/mod.rs:497:30
      core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/core/src/ops/function.rs:227:5
  14: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/alloc/src/boxed.rs:1854:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/alloc/src/boxed.rs:1854:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/sys/unix/thread.rs:108:17
  15: start_thread
  16: clone
```
The full log can be accessed [here](http://minio.pingcap.net:9000/test-infra/2022-02-26/plan-exec-634870/plan-exec-634870-1335848004/archive.tgz).

### PR DESCRIPTION
**Pull request by BusyJay**
### What is changed and how it works?

Issue Number: Close #12046

What's Changed:

```commit-message
If a read index request travel too long in the network, a leader may receive the
request it sent when it's still follower and break the strict order pending read
assumption.

This PR solves the problem by ignoring invalid read states. It also adds a defense
check to ignore all ReadIndex messages when it's sent by current leader.
```

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test

### Release note 

```release-note
Fix panicking when replica read is enabled and there is a long time network condition
```

### CODE REVIEW

File: components/raftstore/src/store/read_queue.rs [hunk 1]
```diff
@@ -230,14 +216,47 @@ where
...
+                debug!(
+                    "cannot find corresponding read from pending reads";
+                    "uuid" => ?uuid, "read-index" => index, "tag" => tag
+                );
+                continue;
+            }
+
+            error!("{} unexpected uuid detected", tag; "current_id" => ?invalid_id);
+            let mut expect_id_track = vec![];
+            for i in (0..self.ready_cnt).rev().take(10).rev() {
```
Comment (5kbpers) [inline components/raftstore/src/store/read_queue.rs:245]: Why is there `10` and `20`?

**Review by 5kbpers — COMMENTED** [review]
rest LGTM

File: components/raftstore/src/store/fsm/peer.rs [hunk 2]
```diff
@@ -1868,6 +1874,16 @@ where
             self.on_transfer_leader_msg(msg.get_message(), peer_disk_usage);
             Ok(())
         } else {
+            // This can be a message that sent when it's still a follower. Nevertheleast,
+            // it's meaningless to continue to handle the request as callbacks are cleared.
+            if msg.get_message().get_msg_type() == MessageType::MsgReadIndex
+                && self.fsm.peer.is_leader()
+                && (msg.get_message().get_from() == 0
```
Comment (tonyxuqqi) [inline components/raftstore/src/store/fsm/peer.rs:1881]: question: when get_from() == 0? is 0 a special meaning id?

File: components/raftstore/src/store/read_queue.rs [hunk 3]
```diff
@@ -230,14 +216,47 @@ where
...
+    pub fn advance_leader_reads<T>(&mut self, tag: &str, states: T)
     where
         T: IntoIterator<Item = (Uuid, Option<LockInfo>, u64)>,
     {
-        for (uuid, _, index) in states {
-            assert_eq!(uuid, self.reads[self.ready_cnt].id);
-            self.reads[self.ready_cnt].read_index = Some(index);
-            self.ready_cnt += 1;
+        let mut states_iter = states.into_iter();
+        while let Some((uuid, info, index)) = states_iter.next() {
```
Comment (tonyxuqqi) [inline components/raftstore/src/store/read_queue.rs:224]: with the message filter above, is this block still necessary? or it's just for potential debug purpose?

File: components/raftstore/src/store/read_queue.rs (hunk 1 above)
Comment (BusyJay) [reply components/raftstore/src/store/read_queue.rs:245]: It can be any number. `10` and `20` are just the safe number that I believe can find the overlap sequences.

File: components/raftstore/src/store/fsm/peer.rs (hunk 2 above)
Comment (BusyJay) [reply components/raftstore/src/store/fsm/peer.rs:1881]: 0 is the same as `self.id()`. raft-rs will treat it as if the request is issue locally.

File: components/raftstore/src/store/read_queue.rs [hunk 4]
```diff
@@ -230,14 +216,47 @@ where
...
+                Some(r) if r.id == uuid => {
+                    r.read_index = Some(index);
+                    self.ready_cnt += 1;
+                    continue;
+                }
+                Some(r) => Some((r.id, r.propose_time)),
+                None => None,
+            };
+
+            if !self.contexts.contains_key(&uuid) {
```
Comment (NingLin-P) [inline components/raftstore/src/store/read_queue.rs:235]: Only non-leader requests will be put into `self.context`, so leader can always skip panic due to this check :
https://github.com/tikv/tikv/blob/356774c4a9e6d75f6cd589694b982130e017428b/components/raftstore/src/store/read_queue.rs#L209-L213

File: components/raftstore/src/store/read_queue.rs (hunk 3 above)
Comment (BusyJay) [reply components/raftstore/src/store/read_queue.rs:224]: Yes, it's a defense.

File: components/raftstore/src/store/read_queue.rs (hunk 4 above)
Comment (BusyJay) [reply components/raftstore/src/store/read_queue.rs]: I deleted the block. As there is a message filter before stepping, the block will not be triggered for any known cases.

File: components/raftstore/src/store/fsm/peer.rs (hunk 2 above)
Comment (NingLin-P) [reply components/raftstore/src/store/fsm/peer.rs:1881]: How about using `raft::INVALID_ID` instead.

File: tests/integrations/raftstore/test_replica_read.rs [hunk 5]
```diff
@@ -507,3 +509,64 @@ fn test_read_local_after_snapshpot_replace_peer() {
...
+    cluster.cfg.raft_store.raft_log_gc_threshold = 12;
+    cluster.cfg.raft_store.raft_log_gc_count_limit = 12;
+    cluster.cfg.raft_store.hibernate_regions = true;
+    cluster.cfg.raft_store.check_leader_lease_interval = ReadableDuration::hours(10);
+    let pd_client = Arc::clone(&cluster.pd_client);
+    pd_client.disable_default_operator();
+
+    let region_id = cluster.run_conf_change();
+    pd_client.must_add_peer(region_id, new_peer(2, 2));
+    pd_client.must_add_peer(region_id, new_peer(3, 3));
```
Comment (NingLin-P) [inline tests/integrations/raftstore/test_replica_read.rs:527]: How about just `cluster.run()`

**Review by NingLin-P — COMMENTED** [review]
Rest LGTM

File: tests/integrations/raftstore/test_replica_read.rs (hunk 5 above)
Comment (BusyJay) [reply tests/integrations/raftstore/test_replica_read.rs:527]: Using `run_conf_change` is on purpose to speed up initialization. The lease is increased, so the election timeout will be long when there are multiple peers.

**Review by NingLin-P — APPROVED** [review]

**Review by 5kbpers — APPROVED** [review]
