### PR TITLE
import: write RPC will check region epoch before continue

### LINKED ISSUE #15003: tikv panic when tikv exit the import mode but import process is still not stopped during "import into" command is cancelled
### What version of TiKV are you using?
master

### Steps to reproduce
1. set global tidb_enable_dist_task=off;
2. IMPORT INTO big.items  FROM "s3://tmp/9T-csv/big.items.*.csv?access-key=minioadmin&secret-access-key=minioadmin&endpoint=http%3a%2f%2f10.2.12.100%3a32762&force-path-style=true" with thread=16,detached;
3. cancel this job 
4. clear table of big.items
5. set global tidb_enable_dist_task=on;
6. execute import into command again

### What did you expect?
import job can be successfully
### What did happened?
```
[2023/06/26 03:25:03.580 +00:00] [FATAL] [[lib.rs:497](http://lib.rs:497/)] ["[region 15563512] 15563513 ingest uuid: 5ACC4E816AC84B9682AA3E6985C3B924 range { start: 7480000000000000FF665F698000000000FF000008014A6C3179FF6F616362FF456879FF7555526174FF517AFF7667316B5654FF64FF6646714B633253FFFF44397650414D446DFFFF436D7635466E55FF66FF32636C364249FF5775FF5042516472FF386642FF38555145FF57317630FF594A58FF56346D6146FF5738FF3536436B4D61FF53FF326E4568465470FFFF64726C6C564F4949FFFF354C3239316F54FF36FF73314B345246FF344AFF64704D7045FF376A52FF3252396CFF556F4A5AFF69646FFF4E76575546FF6979FF6F507A5A4C37FF33FF71724451683566FFFF5749795373574B48FFFF77566E6B35474BFF68FF33396E494875FF3958FF625A6B4769FF386955FF664B676AFF666D5875FF525049FF536261477AFF7773FF637A39506C63FF4AFF4B6D396C554143FFFF4955587951713571FFFF6A516D485A5557FF4AFF767230674865FF7243FF4767573468FF687234FF687A324CFF31776C47FF555471FF4C43436D30FF304BFF465379454878FF67FF3961674E486D68FFFF4C415A7633645749FFFF63524D6E464343FF66FF6C6567304536FF5856FF763853786DFF377134FF32586A54FF76446171FF655964FF4D48746D78FF314AFF53437857547AFF56FF6944776D654737FFFF6847485166333231FFFF76346B33494D68FF55FF3651726D3346FF6457FF3248587442FF4F6A6BFF784C6457FF77796D46FF704C36FF63714F4476FF7177FF645772693275FF31FF4D5A4967746F36FFFF516B70676A637445FFFF7144446C6C4149FF33FF72584E67434CFF7438FF3251504632FF745437FF63386A41FF6158434DFF4D6E69FF4935307259FF6236FF645970573658FF31FF75697A7A427352FFFF47315453755A3757FFFF6D334A30615934FF6CFF45646466455AFF4972FF6661324C48FF62526FFF4B357438FF54666145FF59396AFF5444774A35FF7233FF68654B556E78FF57FF514D30664D6664FFFF6B4F39446B435774FFFF4765796968356EFF4EFF79466D5A446CFF567AFF6575564A44FF4A556EFF5854544CFF546E4C4FFF667143FF4644535849FF3167FF746C357A754BFF4CFF707A3468715837FFFF6731526368445273FFFF6B7870524E3137FF65FF4E5041333547FF6D38FF5A7272494FFF516D66FF32646C6AFF49446D71FF554C75FF4E43756775FF5739FF61425568586AFF58FF567773364A5143FFFF6477513754594E4EFFFF574B7551657947FF42FF75784D5A4D42FF5579FF3647683356FF327867FF71335468FF41303168FF6F6337FF7945486974FF4B75FF327847396F45FF34FF39543550693257FFFF52687A314A484C31FFFF667332524B544AFF6AFF5A51766A4E44FF7441FF396577466BFF787968FF6A493875FF66385241FF386342FF4432516167FF6A75FF353474734838FF62FF36433856474559FFFF0000000000000000FFF7016E6F64653054FF3234FF497350516FFF4F556CFF4E305059FF61795973FF637578FF524F6E4E79FF4F73FF616273776353FF56FF354356346B6D53FFFF3668536551596743FFFF7171677464744BFF6EFF4D5346703047FF695AFF4948735672FF715536FF4443524FFF72494F4EFF673248FF38324C5A70FF5747FF446B76334F55FF39FF776F3571636242FFFF4247336974667332FFFF306F6561745056FF56FF5A7A344B7569FF3130FF4453704435FF4A6C6DFF4D553642FF37644D6FFF6D737AFF5468674F61FF5754FF55506A326264FF79FF3034674D536C57FFFF7272304279374E46FFFF35514D46523666FF64FF775641466A64FF4E4DFF7172434A5AFF627165FF616F3247FF5A343871FF676A45FF4473564F66FF4C00FF000000000000F800FE end: 7480000000000000FF665F698000000000FF000008014A6E4D66FF34574B4EFF746E4AFF3078783263FF4850FF6A416778786CFF47FF426E456A527279FFFF3034353743715247FFFF71555438506E59FF49FF576736306B77FF574FFF6A61796959FF555236FF426F4643FF664C4875FF6E434FFF6D62794878FF304BFF544442704B67FF4BFF4C70504A69645AFFFF51636E6E414D5746FFFF3152587454694CFF6BFF69757341344FFF5036FF3245497665FF33366BFF6F4E5072FF336A5668FF7A7745FF7150556B66FF4579FF784F71496458FF4EFF613979546A7A4DFFFF454662456E394B30FFFF73736272447439FF4AFF786E3771556DFF7246FF3877325744FF4A326FFF4C415943FF6478566DFF327867FF4A38723378FF5367FF64497230624FFF49FF6637484C554863FFFF5A78594A57434843FFFF70395050686F4AFF6EFF74656D417971FF3850FF526D6E6F7AFF425258FF6E545331FF59706542FF487356FF3344555967FF4B62FF57644B7A496EFF30FF6372714C53354CFFFF6851515A5A796B6AFFFF78486C4D6F5A51FF57FF685A5870486DFF594DFF50585A5A62FF325346FF6F59496AFF73714F48FF634267FF56496E5347FF4546FF684B514E5144FF47FF4C424930614A72FFFF5A674C6D7136416EFFFF506F6444346935FF68FF334C79786E4AFF3365FF5342525551FF335379FF39495479FF566A5856FF386C48FF3350445365FF7A50FF43726D4C576BFF4DFF4B6B7067305778FFFF6D6A6C7534634856FFFF3976675051464BFF43FF34354C616B30FF5148FF776B436E45FF47546FFF61427432FF6B6B4342FF59714CFF4E7A4A736DFF514DFF50726D6E7432FF32FF325754776A5A6CFFFF4C4531596B6B4B6CFFFF4E616
```

### PR DESCRIPTION
**Pull request by lance6716**
### What is changed and how it works?

Issue Number: Close #15003

What's Changed:

```commit-message
```

see https://github.com/tikv/tikv/issues/15003#issuecomment-1606957339

server side (this PR): 
- for import sst service, write RPC will only continue when the local region epoch is same as the epoch in request
- for cleanup logic, when the region is not found or region epoch is changed, we can delete the sst file

client side (will open it in TiDB repo):
- for write RPC, retry from write for the error message "RequestTooNew", and retry from rescan region for the error message "RequestTooOld"

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test

see the CI of https://github.com/pingcap/tidb/pull/47667

Side effects

- Performance regression
    - client will wait the slowest peer in a raft group
- Breaking backward compatibility
    - client should adjust the protocol about handle error message

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by lance6716** [comment]
Finally...
https://do.pingcap.net/jenkins/blue/organizations/jenkins/pingcap%2Ftidb%2Fpull_br_integration_test/detail/pull_br_integration_test/485/pipeline

File: components/raftstore/src/store/fsm/store.rs [hunk 1]
```diff
@@ -2809,15 +2764,22 @@ impl<'a, EK: KvEngine, ER: RaftEngine, T: Transport> StoreFsmDelegate<'a, EK, ER
         {
             let meta = self.ctx.store_meta.lock().unwrap();
             for sst in ssts {
-                if let Some(r) = meta.regions.get(&sst.get_region_id()) {
+                if sst.api_version < sst_importer::API_VERSION_2 {
+                    // SST of old versions are created by old TiKV and have different prerequisite
+                    // we can't delete them here. They can only be deleted manually
```
Comment (tonyxuqqi) [inline components/raftstore/src/store/fsm/store.rs:2769]: Is it better to keep the older clean logic here for old SST? Otherwise it may lead to too many support tickets after the upgrade.

File: components/sst_importer/src/import_file.rs [hunk 2]
```diff
@@ -458,20 +458,33 @@ impl ImportDir {
...
         meta.get_region_epoch().get_conf_ver(),
         meta.get_region_epoch().get_version(),
         meta.get_cf_name(),
+        API_VERSION_2,
         SST_SUFFIX,
     )))
 }
 
-pub fn parse_meta_from_path<P: AsRef<Path>>(path: P) -> Result<SstMeta> {
+pub struct SstMetaWithApiVersion {
```
Comment (tonyxuqqi) [inline components/sst_importer/src/import_file.rs:482]: The naming of this struct suggests that it's unncessary to define the struct at all. Just (SstMeta，api_version) is good.

**Comment by tonyxuqqi** [comment]
Others are LGTM.

File: components/sst_importer/src/import_file.rs (hunk 2 above)
Comment (lance6716) [reply components/sst_importer/src/import_file.rs]: https://github.com/tikv/tikv/pull/15795/commits/da8ab023d84d876ffd8e1e766484e4250ddb67df

File: components/raftstore/src/store/fsm/store.rs (hunk 1 above)
Comment (lance6716) [reply components/raftstore/src/store/fsm/store.rs:2769]: I'm worried about the previous panic problem which is caused by this cleanup. 

To make it clear, the affected case is 
- when lightning local backend is importing data while upgrading or fast adding index is running while upgrading. 
- and the ingest RPC does not come so TiKV has no chance to trigger check_sst_for_ingestion then delete the stale SST

I think the affected case is not often happened, so it's not a big problem if disk is occupied by old version SST files. But panic is too severe.

File: src/import/sst_service.rs [hunk 3]
```diff
@@ -675,6 +684,53 @@ impl<E: Engine> ImportSstService<E> {
...
+            let local_region_epoch = local_region_info.region.region_epoch.unwrap();
+
+            // TODO(lance6717): we should only need to check conf_ver because we require all
+            // peers have SST on the disk, and does not care about which one is
+            // leader. But since check_sst_for_ingestion also checks epoch version,
+            // we just keep it here for now.
+
+            // when local region epoch is stale, client can retry write later
+            if is_epoch_stale(&local_region_epoch, epoch) {
+                return Err(Error::Engine(
```
Comment (Connor1996) [inline src/import/sst_service.rs:703]: Should the error type be `Engine`?

File: src/import/sst_service.rs [hunk 4]
```diff
@@ -675,6 +684,53 @@ impl<E: Engine> ImportSstService<E> {
...
+fn check_local_region_stale(
+    region_id: u64,
+    epoch: &RegionEpoch,
+    local_region_info: Option<RegionInfo>,
+) -> Result<()> {
+    match local_region_info {
+        Some(local_region_info) => {
+            let local_region_epoch = local_region_info.region.region_epoch.unwrap();
+
+            // TODO(lance6717): we should only need to check conf_ver because we require all
```
Comment (Connor1996) [inline src/import/sst_service.rs:696]: `version` is not about the leader, it increases after performing split or merge. I don't think we only need to check `conf_ver`

**Review by Connor1996 — COMMENTED** [review]
rest LGTM

File: src/import/sst_service.rs (hunk 3 above)
Comment (lance6716) [reply src/import/sst_service.rs]: https://github.com/tikv/tikv/pull/15795/commits/7c55600d6dcfd5079afb7fcbca6ed723c098828d

File: Makefile [hunk 5]
```diff
@@ -406,6 +406,14 @@ docker_test:
 		${DEV_DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG} \
 		make test
 
+docker_shell:
```
Comment (Connor1996) [inline Makefile:409]: unrelated?

Comment (lance6716) [reply Makefile:409]: My local environment is broken, I need this Makefile entry to debug 😢 Hope it's helpful to others, we already have docker_test to rely on.

File: src/import/sst_service.rs [hunk 6]
```diff
@@ -675,6 +684,62 @@ impl<E: Engine> ImportSstService<E> {
...
+                });
+            }
+
+            // not match means to rescan
+            Ok(())
+        }
+        None => {
+            // when region not found, we can't tell whether it's stale or ahead, so we just
+            // return the safest case
+            Err(Error::Engine(
```
[the remark this answers is not in the document]
Comment (lance6716) [reply src/import/sst_service.rs]: https://github.com/tikv/tikv/pull/15795/commits/8bb6a380d572884493d5bcdb5321cf3428e45d3f I prefer to use two error enum because they have different error message templates and client will check the substring of the message.

File: components/raftstore/src/store/fsm/store.rs (hunk 1 above)
Comment (tonyxuqqi) [reply components/raftstore/src/store/fsm/store.rs:2769]: The panic rarely happens but the old SST files are sure to happen be there forever, which will be challenged by customer for sure. 
Another way is that we can delete old SST files after a safe time, saying 1 week. So that they can be eventually deleted instead of stay there forever.

File: src/import/sst_service.rs [hunk 7]
```diff
@@ -708,29 +760,56 @@ macro_rules! impl_write {
...
                     };
+                    // wait the region epoch on this TiKV to catch up with the epoch
+                    // in request, which comes from PD and represents the majority
+                    // peers' status.
                     let region_id = meta.get_region_id();
+                    let (cb, f) = paired_future_callback();
+                    if let Err(e) = region_info_accessor
+                        .find_region_by_id(region_id, cb)
+                        .map_err(|e| {
+                            Error::Engine(
```
Comment (Connor1996) [inline src/import/sst_service.rs:776]: ditto

File: src/import/sst_service.rs [hunk 8]
```diff
@@ -708,29 +760,56 @@ macro_rules! impl_write {
...
+                    };
+
                     let tablet = match tablets.get(region_id) {
                         Some(t) => t,
                         None => {
-                            return Err(Error::Engine(
-                                format!("region {} not found", region_id).into(),
-                            ));
+                            return (
+                                Err(Error::Engine(
```
Comment (Connor1996) [inline src/import/sst_service.rs:797]: ditto

**Review by Connor1996 — APPROVED** [review]
Rest LGTM

File: src/import/sst_service.rs (hunk 8 above)
Comment (lance6716) [reply src/import/sst_service.rs]: use RequestTooOld in https://github.com/tikv/tikv/pull/15795/commits/d95c7fc35dfbbf65ce2dd91ed02bd1350a776604

File: components/raftstore/src/store/fsm/store.rs (hunk 1 above)
Comment (lance6716) [reply components/raftstore/src/store/fsm/store.rs]: https://github.com/tikv/tikv/pull/15795/commits/d95c7fc35dfbbf65ce2dd91ed02bd1350a776604 

When the tikv has that region, we check the staleness by region epoch. When it's not the case, for api_version_2 we can safely delete the files, for api_version_1 we check last_modified time

**Review by tonyxuqqi — APPROVED** [review]
