### PR TITLE
*: resolve when flashback meets error in the first batch

### LINKED ISSUE #13672: Data inconsistency after flashback
### What version of TiKV are you using?
[root@localhost ~]# /data1/tidb-deploy/tikv-2360/bin/tikv-server -V
TiKV 
Release Version:   6.4.0-alpha
Edition:           Community
Git Commit Hash:   ed64ed21cfa1c734191549a0db66986dab04f4bd
Git Commit Branch: master
UTC Build Time:    2022-10-18 09:38:46
Rust Version:      rustc 1.64.0-nightly (0f4bcadb4 2022-07-30)
Enable Features:   pprof-fp jemalloc mem-profiling portable sse test-engine-kv-rocksdb test-engine-raft-raft-engine cloud-aws cloud-gcp cloud-azure
Profile:           release
[root@localhost ~]# 

### Steps to reproduce
install a tidb cluster with pitr task started
run workload for 10 minutes
flashback to 10 minutes ago
during flashback restart and stop/start tikv/pd/tidb
### What did happened?
MySQL [flashback2]> admin check table user_data1;
ERROR 8223 (HY000): data inconsistency in table: user_data1, index: k_1, handle: 22152, index-values:"" != record-values:"handle: 22152, values: [KindMysqlTime 2022-10-25 13:03:13]"
MySQL [flashback2]>

### LINKED ISSUE #13704: Flashback process is blocked for compaction pending too much data
### What version of TiKV are you using?
TiKV 
Release Version:   6.4.0-alpha
Edition:           Community
Git Commit Hash:   8aa672146661bc719d05b03fc8f40d6bb1b8d24f
Git Commit Branch: HEAD
UTC Build Time:    2022-10-31 08:46:23

### Steps to reproduce
1. start pitr task
2. run workload 10 minutes
3. pause pitr task
4. flashback to the time before pitr task start
5. during flashback restart tikv/tidb/pd/tiflash

### What did you expect?
flashback execute successfully
data is consistent 

### What did happened?
flashback is hang for : 2022-10-31 22:38:47 (GMT+8)TiDB [172.16.6.47:4000](http://172.16.6.47:4000/)[cluster.go:360] ["[ddl] send flashback request"] [region_id=4046518] [start_key=748000000000000014] [end_key=748000000000000019]

check by dev, too much compaction pending

### LINKED ISSUE #13723: flashback during workload, tikv panic lead to tidb down
### What version of TiKV are you using?
[root@localhost ~]# /data1/tidb-deploy/tikv-2360/bin/tikv-server -V
TiKV 
Release Version:   6.4.0-alpha
Edition:           Community
Git Commit Hash:   e0885803a17dfcd26964e74029ce5af9a32cd797
Git Commit Branch: heads/refs/tags/v6.4.0-alpha
UTC Build Time:    2022-10-31 14:26:38
Rust Version:      rustc 1.64.0-nightly (0f4bcadb4 2022-07-30)
Enable Features:   pprof-fp jemalloc mem-profiling portable sse test-engine-kv-rocksdb test-engine-raft-raft-engine cloud-aws cloud-gcp cloud-azure
Profile:           dist_release
[root@localhost ~]# 

### Steps to reproduce
run tpcc workload
run flashback during workload running

### What did you expect?
flashback successfully

### What did happened?
tidb down
```code
[2022/11/02 21:24:33.730 +08:00] [FATAL] [[lib.rs:495](http://lib.rs:495/)] ["assertion failed: row.write.is_none()"] [backtrace="   0: tikv_util::set_panic_hook::{{closure}}\n             at /home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/components/tikv_util/src/lib.rs:494:18\n](http://github.com/pingcap/tikv/components/tikv_util/src/lib.rs:494:18/n)   1: std::panicking::rust_panic_with_hook\n             at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/[panicking.rs:702](http://panicking.rs:702/):17\n   2: std::panicking::begin_panic_handler::{{closure}}\n             at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/[panicking.rs:586](http://panicking.rs:586/):13\n   3: std::sys_common::backtrace::__rust_end_short_backtrace\n             at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/[backtrace.rs:138](http://backtrace.rs:138/):18\n   4: rust_begin_unwind\n             at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/[panicking.rs:584](http://panicking.rs:584/):5\n   5: core::panicking::panic_fmt\n             at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/[panicking.rs:142](http://panicking.rs:142/):14\n   6: core::panicking::panic\n             at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/[panicking.rs:48](http://panicking.rs:48/):5\n   7: resolved_ts::cmd::group_row_changes\n             at /home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/components/resolved_ts/src/cmd.rs:217:29\n](http://github.com/pingcap/tikv/components/resolved_ts/src/cmd.rs:217:29/n)      resolved_ts::cmd::ChangeLog::encode_change_log::{{closure}}\n             at /home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/components/resolved_ts/src/cmd.rs:62:57\n](http://github.com/pingcap/tikv/components/resolved_ts/src/cmd.rs:62:57/n)      core::iter::adapters::map::map_fold::{{closure}}\n             at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/adapters/[map.rs:84](http://map.rs:84/):28\n      core::iter::traits::iterator::Iterator::fold\n             at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/traits/[iterator.rs:2414](http://iterator.rs:2414/):21\n      <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold\n             at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/adapters/[map.rs:124](http://map.rs:124/):9\n      core::iter::traits::iterator::Iterator::for_each\n             at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/traits/[iterator.rs:831](http://iterator.rs:831/):9\n      <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend\n             at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/vec/[spec_extend.rs:40](http://spec_extend.rs:40/):17\n      <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter\n             at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/vec/[spec_from_iter_nested.rs:62](http://spec_from_iter_nested.rs:62/):9\n      alloc::vec::in_place_collect::<impl alloc::vec::spec_from_iter::SpecFromIter<T,I> for alloc::vec::Vec<T>>::from_iter\n             at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/vec/[in_place_collect.rs:164](http://in_place_collect.rs:164/):20\n      <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter\n             at /home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/components/resolved_ts/src/cmd.rs:48:9\n](http://github.com/pingcap/tikv/components/resolved_ts/src/cmd.rs:48:9/n)      core::iter::traits::iterator::Iterator::collect\n             at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/traits/[iterator.rs:1836](http://iterator.rs:1836/):9\n      resolved_ts::cmd::ChangeLog::encode_change_log\n             at /home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/components/resolved_ts/src/cmd.rs:48:9\n](http://github.com/pingcap/tikv/components/resolved_ts/src/cmd.rs:48:9/n)   8: resolved_ts::endpoint::Endpoint<T,E,C>::handle_change_log::{{closure}}\n             at /home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/components/resolved_ts/src/endpoint.rs:538:40\n](http://github.com/pingcap/tikv/components/resolved_ts/src/endpoint.rs:538:40/n)      core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut\n             at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/[function.rs:290](http://function.rs:290/):13\n      core::iter::traits::iterator::Iterator::find_map::check::{{closure}}\n             at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/traits/[iterator.rs:2732](http://iterator.rs:2732/):32\n      core::iter::traits::iterator::Iterator::try_fold\n             at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/traits/[iterator.rs:2238](http://iterator.rs:2238/):21\n      core::iter::traits::iterator::Iterator::find_map\n             at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/traits/[iterator.rs:2738](http://iterator.rs:2738/):9\n      <core::iter::adapters::filter_map::FilterMap<I,F> as core::iter::traits::iterator::Iterator>::next\n             at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/adapters/[filter_map.rs:61](http://filter_map.rs:61/):9\n   9: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter\n             at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/vec/[spec_from_iter_nested.rs:26](http://spec_from_iter_nested.rs:26/):32\n      alloc::vec::in_place_collect::<impl alloc::vec::spec_from_iter::SpecFromIter<T,I> for alloc::vec::Vec<T>>::from_iter\n             at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/vec/[in_place_collect.rs:164](http://in_place_collect.rs:164/):20\n      <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter\n             at /home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/components/resolved_ts/src/endpoint.rs:530:20\n](http://github.com/pingcap/tikv/components/resolved_ts/src/endpoint.rs:530:20/n)      core::iter::traits::iterator::Iterator::collect\n             at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/traits/[iterator.rs:1836](http://iterator.rs:1836/):9\n      resolved_ts::endpoint::Endpoint<T,E,C>::handle_change_log\n             at /home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/components/resolved_ts/src/endpoint.rs:530:20\n](http://github.com/pingcap/tikv/components/resolved_ts/src/endpoint.rs:530:20/n)      <resolved_ts::endpoint::Endpoint<T,E,C> as tikv_util::worker::pool::Runnable>::run\n             at /home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/components/resolved_ts/src/endpoint.rs:748:18\n](http://github.com/pingcap/tikv/components/resolved_ts/src/endpoint.rs:748:18/n)      tikv_util::worker::pool::Worker::start_with_timer_impl::{{closure}}\n             at /home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/components/tikv_util/src/worker/pool.rs:489:25\n](http://github.com/pingcap/tikv/components/tikv_util/src/worker/pool.rs:489:25/n)      <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll\n             at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/[mod.rs:91](http://mod.rs:91/):19\n      yatp::task::future::RawTask<F>::poll\n             at /rust/git/checkouts/yatp-e704b73c3ee279b6/39cb495/src/task/[future.rs:59](http://future.rs:59/):9\n  10: yatp::task::future::TaskCell::poll\n             at /rust/git/checkouts/yatp-e704b73c3ee279b6/39cb495/src/task/[future.rs:103](http://future.rs:103/):9\n      <yatp::task::future::Runner as yatp::pool::runner::Runner>::handle\n             at /rust/git/checkouts/yatp-e704b73c3ee279b6/39cb495/src/task/[future.rs:387](http://future.rs:387/):20\n  11: <tikv_util::yatp_pool::YatpPoolRunner<T> as yatp::pool::runner::Runner>::handle\n             at /home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/components/tikv_util/src/yatp_pool/mod.rs:122:24\n](http://github.com/pingcap/tikv/components/tikv_util/src/yatp_pool/mod.rs:122:24/n)      yatp::pool::worker::WorkerThread<T,R>::run\n             at /rust/git/checkouts/yatp-e704b73c3ee279b6/39cb495/src/pool/[worker.rs:48](http://worker.rs:48/):13\n      yatp::pool::builder::LazyBuilder<T>::build::{{closure}}\n             at /rust/git/checkouts/yatp-e704b73c3ee279b6/39cb495/src/pool/[builder.rs:114](http://builder.rs:114/):25\n      std::sys_common::backtrace::__rust_begin_short_backtrace\n             at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/[backtrace.rs:122](http://backtrace.rs:122/):18\n  12: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}\n             at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/[mod.rs:505](http://mod.rs:505/):17\n      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once\n             at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panic/[unwind_safe.rs:271](http://unwind_safe.rs:271/):9\n      std::panicking::try::do_call\n             at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/[panicking.rs:492](http://panicking.rs:492/):40\n      std::panicking::try\n             at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/[panicking.rs:456](http://panicking.rs:456/):19\n      std::panic::catch_unwind\n             at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/[panic.rs:137](http://panic.rs:137/):14\n      std::thread::Builder::spawn_unchecked_::{{closure}}\n             at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/[mod.rs:504](http://mod.rs:504/):30\n      core::ops::function::FnOnce::call_once{{vtable.shim}}\n             at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/[function.rs:248](http://function.rs:248/):5\n  13: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once\n             at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/[boxed.rs:1935](http://boxed.rs:1935/):9\n      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once\n             at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/[boxed.rs:1935](http://boxed.rs:1935/):9\n      std::sys::unix::thread::Thread::new::thread_start\n             at /rust/toolchains/nightly-2022-07-31-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys/unix/[thread.rs:108](http://thread.rs:108/):17\n  14: start_thread\n  15: clone\n"] [location=components/resolved_ts/src/[cmd.rs:217](http://cmd.rs:217/)] [thread_name=resolved-ts-0]
```

### PR DESCRIPTION
**Pull request by HuSharp**
Signed-off-by: husharp <jinhao.hu@pingcap.com>

### What is changed and how it works?

Issue Number: close #13672  close #13704  close #13723

What's Changed:
```commit-message
resolve when flashback meets error in the first batch.
```
### Check List 

Tests 

- Integration test

### Release note 

```release-note
None
```

### CODE REVIEW

File: src/storage/txn/actions/flashback_to_version.rs [hunk 1]
```diff
@@ -62,22 +62,30 @@ pub fn flashback_to_version_read_write<S: Snapshot>(
     let mut key_old_writes = Vec::with_capacity(FLASHBACK_BATCH_SIZE - key_locks_len);
     // Check the latest commit ts to make sure there is no commit change during the
     // flashback, otherwise, we need to abort the flashback.
-    for (key, commit_ts, old_write) in key_ts_old_writes {
+    for (key, commit_ts, old_write) in key_ts_old_writes.clone() {
```
Comment (JmPotato) [inline src/storage/txn/actions/flashback_to_version.rs:65]: Maybe we can use `iter()` to avoid cloning.

File: src/storage/txn/commands/flashback_to_version_read_phase.rs [hunk 2]
```diff
@@ -99,21 +99,37 @@ impl<S: Snapshot> ReadCommand<S> for FlashbackToVersionReadPhase {
...
-                end_key: self.end_key,
-                key_locks,
-                key_old_writes,
-                next_lock_key,
-                next_write_key,
-            };
-            Ok(ProcessResult::NextCommand {
-                cmd: Command::FlashbackToVersion(next_cmd),
-            })
+            if key_old_writes.is_empty() && key_locks.is_empty() {
```
Comment (JmPotato) [inline src/storage/txn/commands/flashback_to_version_read_phase.rs:102]: Better add a comment to explain that if `key_old_writes` and `key_locks` are both empty, it means there are no keys that need to be flashbacked in this batch, but since the next key is not none, so we have to continue reading the next batch.

File: tests/integrations/server/kv_service.rs [hunk 3]
```diff
@@ -597,13 +597,66 @@ fn test_mvcc_resolve_lock_gc_and_delete() {
...
+        );
+        // Get
+        ts += 1;
+        must_kv_read_equal(&client, ctx.clone(), k.clone(), v.clone(), ts)
+    }
+    // Flashback
+    fail::cfg("flashback_failed_in_first_batch", "return").unwrap();
+    must_flashback_to_version(&client, ctx.clone(), 5, ts + 1, ts + 2);
+    fail::remove("flashback_failed_in_first_batch");
+    // Flashback needs to be continued.
```
Comment (JmPotato) [inline tests/integrations/server/kv_service.rs:641]: Read here once to make sure the rest keys can still be read.

File: tests/integrations/server/kv_service.rs [hunk 4]
```diff
@@ -597,13 +597,66 @@ fn test_mvcc_resolve_lock_gc_and_delete() {
...
+    );
+}
+
 #[test]
 fn test_mvcc_flashback() {
     let (_cluster, client, ctx) = must_new_cluster_and_kv_client();
     let mut ts = 0;
-    let k = b"key".to_vec();
-    for i in 0..10 {
+    let k = b"key@1".to_vec();
```
Comment (JmPotato) [inline tests/integrations/server/kv_service.rs:655]:
```suggestion
```

**Review by JmPotato — COMMENTED** [review]
Can we add a test case that flashback the same data twice to see if there is anything wrong? The rest LGTM.

File: tests/integrations/server/kv_service.rs (hunk 4 above)
Comment (HuSharp) [reply tests/integrations/server/kv_service.rs:655]: This value is needed later in the code and I will change its position.

**Comment by JmPotato** [comment]
/cc @Connor1996 @AndreMouche 

Please help take a look, thx!

File: src/storage/txn/actions/flashback_to_version.rs [hunk 5]
```diff
@@ -62,21 +62,29 @@ pub fn flashback_to_version_read_write<S: Snapshot>(
...
-        if commit_ts == flashback_commit_ts {
-            key_old_writes.clear();
-            return Ok((key_old_writes, false));
+        // Although the first flashback preparation phase make sure there will be no
+        // writes other than flashback after it, we can't return it ASAP.
+        // Suppose the second phase procedure contains two batches to flashback. After
+        // the first batch is committed, if the region is down, client will retry the
+        // flashback from the very first beginning, because the data in the first batch
+        // has been written the flashbacked data with the same commit_ts, So we need to
+        // skip it to make sure to keep writing the data that is needed.
```
Comment (JmPotato) [inline src/storage/txn/actions/flashback_to_version.rs:78]:
```suggestion
        // Although the first flashback preparation phase makes sure there will be no
        // writes other than flashback after it, we CAN NOT return directly here.
        // Suppose the second phase procedure contains two batches to flashback. After
        // the first batch is committed, if the region is down, the client will retry the
        // flashback from the very first beginning, because the data in the first batch
        // has been written the flashbacked data with the same `commit_ts`, So we need to
        // skip it to ensure the following data will be flashbacked continuously.
```

File: src/storage/txn/actions/flashback_to_version.rs [hunk 6]
```diff
@@ -62,21 +62,29 @@ pub fn flashback_to_version_read_write<S: Snapshot>(
...
+        if *commit_ts == flashback_commit_ts {
+            continue;
```
Comment (JmPotato) [inline src/storage/txn/actions/flashback_to_version.rs:80]: Since the modification in the same batch is atomic, I think we can return with the last write directly here.

**Comment by AndreMouche** [comment]
@sticnarf @MyonKeminta PTAL, thanks

File: src/storage/txn/commands/flashback_to_version_read_phase.rs [hunk 7]
```diff
@@ -81,24 +81,42 @@ impl<S: Snapshot> ReadCommand<S> for FlashbackToVersionReadPhase {
...
+        } else if has_remain_writes && key_old_writes.is_empty() {
+            // We haven't read any write yet, so we need to read the writes in the next
+            // batch later.
+            self.next_write_key
+        } else {
+            None
+        };
         if key_locks.is_empty() && key_old_writes.is_empty() {
+            if next_write_key.is_some() || next_lock_key.is_some() {
+                // When there are no keys that need to be flashbacked in this batch, but since
```
Comment (AndreMouche) [inline src/storage/txn/commands/flashback_to_version_read_phase.rs:101]:
```suggestion
                // Although there is no key left in this batch, keep processing the next batch since next key(write or lock) exist.
```

File: src/storage/txn/commands/flashback_to_version_read_phase.rs [hunk 8]
```diff
@@ -81,24 +81,42 @@ impl<S: Snapshot> ReadCommand<S> for FlashbackToVersionReadPhase {
...
             (key_locks.len() + key_old_writes.len()) as f64,
         );
-
+        // Check next key firstly.
+        let next_lock_key = if has_remain_locks {
+            key_locks.pop().map(|(key, _)| key)
+        } else {
+            None
+        };
+        let next_write_key = if has_remain_writes && !key_old_writes.is_empty() {
```
Comment (AndreMouche) [inline src/storage/txn/commands/flashback_to_version_read_phase.rs:90]: How about `using` match instead?
```suggestion
                let next_write_key = match (has_remain_writes, key_old_writes.is_empty()) {
            (true, false) => key_old_writes.pop().map(|(key, _)| key),
            (true, true) => self.next_write_key,
            (..) => None,
        };
```

Comment (HuSharp) [reply src/storage/txn/commands/flashback_to_version_read_phase.rs:90]: get it

File: src/storage/txn/commands/flashback_to_version.rs [hunk 9]
```diff
@@ -75,8 +75,8 @@ impl<S: Snapshot, L: LockManager> WriteCommand<S, L> for FlashbackToVersion {
             &mut reader,
             &mut next_lock_key,
             &mut next_write_key,
-            self.key_locks,
-            self.key_old_writes,
+            self.key_locks.clone(),
```
Comment (Connor1996) [inline src/storage/txn/commands/flashback_to_version.rs:78]: why clone

File: src/storage/txn/commands/flashback_to_version_read_phase.rs [hunk 10]
```diff
@@ -81,24 +81,39 @@ impl<S: Snapshot> ReadCommand<S> for FlashbackToVersionReadPhase {
...
+            None
+        };
+        let next_write_key = match (has_remain_writes, key_old_writes.is_empty()) {
+            (true, false) => key_old_writes.pop().map(|(key, _)| key),
+            // We haven't read any write yet, so we need to read the writes in the next
+            // batch later.
+            (true, true) => self.next_write_key,
+            (..) => None,
+        };
         if key_locks.is_empty() && key_old_writes.is_empty() {
```
Comment (Connor1996) [inline src/storage/txn/commands/flashback_to_version_read_phase.rs:97]: Doesn't it mean all keys are processed?

File: src/storage/txn/commands/flashback_to_version.rs (hunk 9 above)
Comment (JmPotato) [reply src/storage/txn/commands/flashback_to_version.rs:78]: Otherwise, the closure below will use a partially moved value: `self`.

**Comment by JmPotato** [comment]
/cc @AndreMouche @Connor1996 

PTAL again, thx a lot.

File: src/storage/txn/commands/flashback_to_version_read_phase.rs [hunk 11]
```diff
@@ -60,46 +60,54 @@ impl<S: Snapshot> ReadCommand<S> for FlashbackToVersionReadPhase {
...
-            &mut reader,
-            key_locks.len(),
-            &self.next_write_key,
-            &self.end_key,
-            self.version,
-            self.start_ts,
-            self.commit_ts,
-            statistics,
-        )?;
+        // Scan the writes only if there is no more locks to unlock, otherwise, there
```
Comment (Connor1996) [inline src/storage/txn/commands/flashback_to_version_read_phase.rs:69]: how about separating into two stages, then the logic would be clearer, like 
```
match stage {
 ScanLock => xxx,
 ScanWrite => xxx,
}

File: src/storage/txn/actions/flashback_to_version.rs [hunk 12]
```diff
@@ -42,41 +41,56 @@ pub fn flashback_to_version_read_write<S: Snapshot>(
...
         }
-        // Since the first flashback preparation phase make sure there will be no writes
-        // other than flashback after it, so we need to check if there is already a
-        // successful flashback result, and if so, just finish the flashback ASAP.
-        if commit_ts == flashback_commit_ts {
-            key_old_writes.clear();
-            return Ok((key_old_writes, false));
+        // Check the latest commit ts to make sure there is no commit change during the
+        // flashback, otherwise, we need to abort the flashback.
+        for (key, commit_ts, old_write) in key_ts_old_writes.iter() {
```
Comment (Connor1996) [inline src/storage/txn/actions/flashback_to_version.rs:71]:
```suggestion
        for (key, commit_ts, old_write) in key_ts_old_writes.into_iter() {
```

File: src/storage/txn/commands/flashback_to_version_read_phase.rs (hunk 11 above)
Comment (HuSharp) [reply src/storage/txn/commands/flashback_to_version_read_phase.rs]: It has been changed to this, PTAL!

File: src/storage/txn/commands/flashback_to_version_read_phase.rs [hunk 13]
```diff
@@ -58,62 +70,102 @@ impl<S: Snapshot> ReadCommand<S> for FlashbackToVersionReadPhase {
...
+        let next_state = match cur_state {
+            FlashbackToVersionState::ScanLock { next_lock_key, .. } => {
+                let (mut key_locks, has_remain_locks) = flashback_to_version_read_lock(
+                    &mut reader,
+                    &next_lock_key,
+                    &self.end_key,
+                    statistics,
+                )?;
+                let next_state;
+                if key_locks.is_empty() && !has_remain_locks {
```
Comment (Connor1996) [inline src/storage/txn/commands/flashback_to_version_read_phase.rs:91]: let next_state = if { ... } else { ... };

File: src/storage/txn/commands/flashback_to_version_read_phase.rs [hunk 14]
```diff
@@ -58,62 +70,102 @@ impl<S: Snapshot> ReadCommand<S> for FlashbackToVersionReadPhase {
...
+                    &mut reader,
+                    &next_write_key,
+                    &self.end_key,
+                    self.version,
+                    self.start_ts,
+                    self.commit_ts,
+                    statistics,
+                )?;
+                let mut next_state = None;
+                if !key_old_writes.is_empty() {
```
Comment (Connor1996) [inline src/storage/txn/commands/flashback_to_version_read_phase.rs:124]: let next_state = if { .. } else { None };

File: src/storage/txn/commands/flashback_to_version.rs [hunk 15]
```diff
@@ -67,42 +71,50 @@ impl<S: Snapshot, L: LockManager> WriteCommand<S, L> for FlashbackToVersion {
...
         let mut write_data = WriteData::from_modifies(txn.into_modifies());
         write_data.extra.for_flashback = true;
         Ok(WriteResult {
             ctx: self.ctx.clone(),
             to_be_write: write_data,
             rows,
-            pr: if next_lock_key.is_none() && next_write_key.is_none() {
-                ProcessResult::Res
-            } else {
+            pr: (move || {
```
Comment (Connor1996) [inline src/storage/txn/commands/flashback_to_version.rs:99]: can't we just use `{ .. }` instead of closure?

File: src/storage/txn/commands/flashback_to_version_read_phase.rs [hunk 16]
```diff
@@ -58,62 +70,102 @@ impl<S: Snapshot> ReadCommand<S> for FlashbackToVersionReadPhase {
                 commit_ts: self.commit_ts,
             }));
         }
+        let tag = self.tag().get_str();
+        let cur_state = self.state.unwrap_or(FlashbackToVersionState::ScanLock {
```
Comment (Connor1996) [inline src/storage/txn/commands/flashback_to_version_read_phase.rs:74]: why can't we init the state when creating FlashbackToVersionReadPhase

File: src/storage/txn/commands/flashback_to_version_read_phase.rs [hunk 17]
```diff
@@ -58,62 +70,102 @@ impl<S: Snapshot> ReadCommand<S> for FlashbackToVersionReadPhase {
...
+                            // The batch must be full.
+                            assert_eq!(key_locks.len(), FLASHBACK_BATCH_SIZE);
+                            key_locks.pop().map(|(key, _)| key)
+                        } else {
+                            None
+                        },
+                        key_locks,
+                    })
+                };
+                next_state
```
Comment (Connor1996) [inline src/storage/txn/commands/flashback_to_version_read_phase.rs:110]:
```suggestion
                if key_locks.is_empty() && !has_remain_locks {
                    // No more locks to flashback, continue to scan the writes.
                    read_again = true;
                    Some(FlashbackToVersionState::ScanWrite {
                        next_write_key: self.start_write_key.clone(),
                        key_old_writes: Vec::with_capacity(0),
                    })
                } else {
                    tls_collect_keyread_histogram_vec(tag, key_locks.len() as f64);
                    Some(FlashbackToVersionState::ScanLock {
                        next_lock_key: if has_remain_locks {
                            // The batch must be full.
                            assert_eq!(key_locks.len(), FLASHBACK_BATCH_SIZE);
                            key_locks.pop().map(|(key, _)| key)
                        } else {
                            None
                        },
                        key_locks,
                    })
                }
```

File: src/storage/txn/commands/flashback_to_version_read_phase.rs [hunk 18]
```diff
@@ -58,62 +70,102 @@ impl<S: Snapshot> ReadCommand<S> for FlashbackToVersionReadPhase {
...
+                let (mut key_old_writes, has_remain_writes) = flashback_to_version_read_write(
+                    &mut reader,
+                    &next_write_key,
+                    &self.end_key,
+                    self.version,
+                    self.start_ts,
+                    self.commit_ts,
+                    statistics,
+                )?;
+                let next_state = if !key_old_writes.is_empty() {
```
Comment (Connor1996) [inline src/storage/txn/commands/flashback_to_version_read_phase.rs:122]: ditto

File: src/storage/txn/commands/flashback_to_version.rs (hunk 15 above)
Comment (HuSharp) [reply src/storage/txn/commands/flashback_to_version.rs:99]: I think this is for injection testing to meet error in the first batch.🤔

Comment (JmPotato) [reply src/storage/txn/commands/flashback_to_version.rs:99]: We need the failpoint return, so it seems that the closure is necessary.

**Comment by JmPotato** [comment]
All comments are addressed. PTAL, thx!

File: src/storage/txn/commands/flashback_to_version_read_phase.rs [hunk 19]
```diff
@@ -58,62 +91,95 @@ impl<S: Snapshot> ReadCommand<S> for FlashbackToVersionReadPhase {
                 commit_ts: self.commit_ts,
             }));
         }
+        let tag = self.tag().get_str();
+        let cur_state = self.state.unwrap();
```
Comment (Connor1996) [inline src/storage/txn/commands/flashback_to_version_read_phase.rs:95]: option is not needed

File: src/storage/txn/commands/flashback_to_version_read_phase.rs [hunk 20]
```diff
@@ -58,62 +91,95 @@ impl<S: Snapshot> ReadCommand<S> for FlashbackToVersionReadPhase {
...
+                        next_write_key: if has_remain_writes {
+                            assert_eq!(key_old_writes.len(), FLASHBACK_BATCH_SIZE);
+                            key_old_writes.pop().map(|(key, _)| key)
+                        } else {
+                            None
+                        },
+                        key_old_writes,
+                    })
+                } else {
+                    None
```
Comment (Connor1996) [inline src/storage/txn/commands/flashback_to_version_read_phase.rs:151]:
```suggestion
                    return Ok(ProcessResult::Res);
```

File: src/storage/txn/commands/flashback_to_version.rs [hunk 21]
```diff
@@ -67,42 +70,49 @@ impl<S: Snapshot, L: LockManager> WriteCommand<S, L> for FlashbackToVersion {
...
-            self.key_old_writes,
-            self.start_ts,
-            self.commit_ts,
-        )?;
+        // The state must be `ScanLock` or `ScanWrite` here.
+        match self.state.as_mut().unwrap() {
+            FlashbackToVersionState::ScanLock {
+                next_lock_key,
+                key_locks,
+            } => flashback_to_version_lock(&mut txn, &mut reader, next_lock_key, key_locks)?,
```
Comment (Connor1996) [inline src/storage/txn/commands/flashback_to_version.rs:78]:
```suggestion
            FlashbackToVersionState::ScanLock {
                ref mut next_lock_key,
                key_locks,
            } => next_lock_key = flashback_to_version_lock(&mut txn, &mut reader, key_locks)?,
```

File: src/storage/txn/commands/flashback_to_version.rs [hunk 22]
```diff
@@ -67,42 +70,49 @@ impl<S: Snapshot, L: LockManager> WriteCommand<S, L> for FlashbackToVersion {
...
+            FlashbackToVersionState::ScanWrite {
+                next_write_key,
+                key_old_writes,
+            } => flashback_to_version_write(
```
Comment (Connor1996) [inline src/storage/txn/commands/flashback_to_version.rs:82]: ditto

**Comment by sticnarf** [comment]
Why not just use `Vec::new()` instead of `Vec::with_capacity(0)`?

File: src/storage/txn/actions/flashback_to_version.rs [hunk 23]
```diff
@@ -32,7 +32,6 @@ pub fn flashback_to_version_read_lock<S: Snapshot>(
 
 pub fn flashback_to_version_read_write<S: Snapshot>(
     reader: &mut MvccReader<S>,
-    key_locks_len: usize,
     next_write_key: &Option<Key>,
```
Comment (Connor1996) [inline src/storage/txn/actions/flashback_to_version.rs:35]: Option is not needed as well

File: src/storage/txn/commands/flashback_to_version.rs [hunk 24]
```diff
@@ -67,42 +70,58 @@ impl<S: Snapshot, L: LockManager> WriteCommand<S, L> for FlashbackToVersion {
...
+                }
+            }
+            FlashbackToVersionState::ScanWrite {
+                ref mut next_write_key,
+                ref key_old_writes,
+            } => {
+                if let Some(new_next_write_key) = flashback_to_version_write(
+                    &mut txn,
+                    &mut reader,
+                    key_old_writes,
```
Comment (sticnarf) [inline src/storage/txn/commands/flashback_to_version.rs:92]: Small suggestion (you can ignore it now if you're out of time before the freeze)

You can actually `take` this `Vec` out and let `flashback_to_version_write` accept `Vec` instead of `&Vec`. This will save some cloned.

And it's similar for the `key_locks` above. There are also similar cases in the read phase too.

File: src/storage/txn/commands/flashback_to_version_read_phase.rs [hunk 25]
```diff
@@ -58,62 +91,101 @@ impl<S: Snapshot> ReadCommand<S> for FlashbackToVersionReadPhase {
...
+                            next_write_key: Some(self.start_key.clone()),
+                            key_old_writes: Vec::new(),
+                        }
+                    } else {
+                        tls_collect_keyread_histogram_vec(tag, key_locks.len() as f64);
+                        FlashbackToVersionState::ScanLock {
+                            next_lock_key: if has_remain_locks {
+                                // The batch must be full.
+                                assert_eq!(key_locks.len(), FLASHBACK_BATCH_SIZE);
+                                key_locks.pop().map(|(key, _)| key)
```
Comment (Connor1996) [inline src/storage/txn/commands/flashback_to_version_read_phase.rs:127]: If it has remain locks, `key_locks` must be not empty. `next_write_key` and `next_lock_key` don't have to be `Option`

File: src/storage/txn/commands/flashback_to_version_read_phase.rs [hunk 26]
```diff
@@ -58,62 +91,101 @@ impl<S: Snapshot> ReadCommand<S> for FlashbackToVersionReadPhase {
...
+                        &mut reader,
+                        &next_lock_key.unwrap(),
+                        &self.end_key,
+                        statistics,
+                    )?;
+                    if key_locks.is_empty() && !has_remain_locks {
+                        // No more locks to flashback, continue to scan the writes.
+                        read_again = true;
+                        FlashbackToVersionState::ScanWrite {
+                            next_write_key: Some(self.start_key.clone()),
```
Comment (Connor1996) [inline src/storage/txn/commands/flashback_to_version_read_phase.rs:118]: seems always some

**Review by Connor1996 — COMMENTED** [review]
rest LGTM

File: src/storage/txn/commands/flashback_to_version_read_phase.rs (hunk 25 above)
Comment (JmPotato) [reply src/storage/txn/commands/flashback_to_version_read_phase.rs:127]: Very nice catch 👍

File: src/storage/txn/commands/flashback_to_version.rs (hunk 24 above)
Comment (JmPotato) [reply src/storage/txn/commands/flashback_to_version.rs]: Resolved, PTAL.

**Review by sticnarf — APPROVED** [review]
LGTM

**Review by Connor1996 — APPROVED** [review]
LGTM
