### PR TITLE
fix test_follower_slow_split

### LINKED ISSUE #3793: test_follower_slow_split failed
## Bug Report

https://circleci.com/gh/tikv/tikv/14968?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

### PR DESCRIPTION
**Pull request by hicqu**
Signed-off-by: qupeng <qupeng@pingcap.com>

## What have you changed? (mandatory)
Fix test case `test_follower_slow_split`.

The case failed because we didn't call `disable_default_operator`. So after we removed a peer from a cluster with 3 replicas, the expected peer count is `2`, but pd will add a new peer back immediatly so it's still 3. So the test case failed.

## What are the type of the changes? (mandatory)
Improvement.

## How has this PR been tested? (mandatory)
make dev.

## Does this PR affect documentation (docs/docs-cn) update? (mandatory)
No.

## Does this PR affect tidb-ansible update? (mandatory)
No.

## Refer to a related PR or issue link (optional)
Close #3793 .

### CODE REVIEW

**Comment by hicqu** [comment]
Using some `println` to show the reason.
Without `disable_default_operator`:
```
req.peers: [1002, 1003, 1004], self.peers: [id: 1 store_id: 1, id: 3 store_id: 3, id: 1000 store_id: 2]
req.peers: [1002, 1003, 1004], self.peers: [id: 1 store_id: 1, id: 3 store_id: 3, id: 1000 store_id: 2]
```
With `disable_default_operator`:
```
req.peers: [1001, 1002], self.peers: [id: 1 store_id: 1, id: 3 store_id: 3]
req.peers: [1001, 1002], self.peers: [id: 1 store_id: 1, id: 3 store_id: 3]
```

**Comment by hicqu** [comment]
PTAL @BusyJay .

File: tests/failpoints_cases/test_split_region.rs [hunk 1]
```diff
@@ -27,8 +27,9 @@ use test_raftstore::*;
 fn test_follower_slow_split() {
     let _guard = ::setup();
     let mut cluster = new_node_cluster(0, 3);
-    cluster.run();
     let pd_client = Arc::clone(&cluster.pd_client);
+    pd_client.disable_default_operator();
```
Comment (BusyJay) [inline tests/failpoints_cases/test_split_region.rs]: Why is it still necessary?

File: src/raftstore/store/util.rs [hunk 2]
```diff
@@ -256,9 +256,10 @@ pub fn check_region_epoch(
             | AdminCmdType::InvalidAdmin
             | AdminCmdType::ComputeHash
             | AdminCmdType::VerifyHash => {}
-            AdminCmdType::Split | AdminCmdType::BatchSplit => check_ver = true,
```
Comment (siddontang) [inline src/raftstore/store/util.rs]: why does Split need to be checked ConfVer?

File: tests/failpoints_cases/test_split_region.rs (hunk 1 above)
Comment (hicqu) [reply tests/failpoints_cases/test_split_region.rs]: Because 3 peers will cause the test case fail because of unexpected vote-message count.

File: src/raftstore/store/util.rs (hunk 2 above)
Comment (hicqu) [reply src/raftstore/store/util.rs]: The test case did fail with error message `expected peers are 3, but got 2 from request`. So there must be some cases that PD gives TiKVs a `Split` command with lower conf version. However I can't find it, so I just add a unit test for this, instead of an integration test.

**Comment by zhangjinpeng1987** [comment]
Please split into two different PRs.

**Comment by hicqu** [comment]
Things about conf version is moved to #3807 . Please take a look @zhangjinpeng1987 .

**Comment by BusyJay** [comment]
How can it still fail after #3807 ?

**Comment by hicqu** [comment]
@BusyJay The test success depends on `MsgRequestPreVote` count. So if there are 3 peers instead 2, they will send more such messages than the number expected. So we still needs `disable_default_operator`.
