### PR TITLE
resolved_ts: fix OOM due to rts tasks pile up on channel

### LINKED ISSUE #18359: TiKV OOM: resolved-ts worker stuck at 100% CPU with growing memory from pending command size
### What version of TiKV are you using?
v6.5.2 

### What happened?
It was observed on a TiKV cluster that memory usage increased by 30 GB within 10 minutes, eventually leading to an OOM. During this period, the resolved-ts worker was stuck at 100% CPU.

### Analysis 
Raftstore continuously sends ChangeLog entries (including committed writes to the lock cf and write cf) to the resolved-ts worker. When the worker is stuck, tasks will accumulate. There is currently no mechanism to bound the memory consumption of the accumulated tasks.

Monitoring shows that the memory usage curve closely tracks the growth of pending resolved-ts tasks. The Pending Command Size metric reached 7 GB, although it may underestimate the actual memory usage.

Image

### TODO
- Reproduce this on a local cluster by simulating a blocked resolved-ts worker.
- Design a mechanism to bound the memory usage of accumulated tasks for the resolved-ts worker.

### PR DESCRIPTION
**Pull request by overvenus**
### What is changed and how it works?

Issue Number: Close #18359

What's Changed:

```commit-message
This pull request fixes #18359 by introducing improvements to memory
quota management and region re-registration in the resolved-ts
component. The changes ensure that when memory usage exceeds the
configured quota, all observed regions are re-registered to free up
memory, and random backoff is applied to avoid thundering herd problems.
Additionally, the observer and endpoint now share a memory quota
instance, and active checks for memory quota are performed periodically.
```

**Memory quota management and region re-registration:**

* Added logic in `endpoint.rs` to re-register all observed regions when memory quota is exceeded, dropping pending logs and applying a random backoff to each region to avoid simultaneous re-registration. (`components/resolved_ts/src/endpoint.rs`) [[1]](diffhunk://#diff-10705daa95aaa15a28a65ade2c5207efb566f6267991ac2e8f15ddfdfd245119R885-R916) [[2]](diffhunk://#diff-10705daa95aaa15a28a65ade2c5207efb566f6267991ac2e8f15ddfdfd245119R945) [[3]](diffhunk://#diff-10705daa95aaa15a28a65ade2c5207efb566f6267991ac2e8f15ddfdfd245119L921-L925) [[4]](diffhunk://#diff-10705daa95aaa15a28a65ade2c5207efb566f6267991ac2e8f15ddfdfd245119L960-R1006)
* Introduced periodic active memory quota checks in the endpoint's main loop, triggering region re-registration if quota is exceeded. (`components/resolved_ts/src/endpoint.rs`)

**Memory quota sharing and observer updates:**

* Modified the `Observer` struct to accept and use a shared `Arc<MemoryQuota>`, ensuring consistent quota tracking between observer and endpoint. (`components/resolved_ts/src/observer.rs`) [[1]](diffhunk://#diff-bb54c37a7c24d8163143fa395e02b7c5106d169280de371f5eb826da7406e1c1R3-R23) [[2]](diffhunk://#diff-bb54c37a7c24d8163143fa395e02b7c5106d169280de371f5eb826da7406e1c1R46) [[3]](diffhunk://#diff-bb54c37a7c24d8163143fa395e02b7c5106d169280de371f5eb826da7406e1c1R72)
* Updated observer test to initialize with the new memory quota parameter. (`components/resolved_ts/src/observer.rs`)

**Endpoint and configuration improvements:**

* Changed the endpoint to receive the memory quota instance via constructor instead of creating its own, and added tracking for last active memory quota check. (`components/resolved_ts/src/endpoint.rs`) [[1]](diffhunk://#diff-10705daa95aaa15a28a65ade2c5207efb566f6267991ac2e8f15ddfdfd245119R693) [[2]](diffhunk://#diff-10705daa95aaa15a28a65ade2c5207efb566f6267991ac2e8f15ddfdfd245119L712-R715) [[3]](diffhunk://#diff-10705daa95aaa15a28a65ade2c5207efb566f6267991ac2e8f15ddfdfd245119R725) [[4]](diffhunk://#diff-10705daa95aaa15a28a65ade2c5207efb566f6267991ac2e8f15ddfdfd245119R412)
* Enhanced logging to include backoff information and improved error handling by distinguishing between different error causes. (`components/resolved_ts/src/endpoint.rs`) [[1]](diffhunk://#diff-10705daa95aaa15a28a65ade2c5207efb566f6267991ac2e8f15ddfdfd245119L735-R739) [[2]](diffhunk://#diff-10705daa95aaa15a28a65ade2c5207efb566f6267991ac2e8f15ddfdfd245119L853-R857) [[3]](diffhunk://#diff-10705daa95aaa15a28a65ade2c5207efb566f6267991ac2e8f15ddfdfd245119L866-R870) [[4]](diffhunk://#diff-10705daa95aaa15a28a65ade2c5207efb566f6267991ac2e8f15ddfdfd245119L1158-R1218)

**Testing and dependency updates:**

* Updated failpoint and resolved-ts tests to call `suite.run()` for proper initialization. (`components/resolved_ts/tests/failpoints/mod.rs`) [[1]](diffhunk://#diff-ec0d36f74ae27d945af0aca997fb29412f6f5011d7c9591f41528b5b232eb8fcR22) [[2]](diffhunk://#diff-ec0d36f74ae27d945af0aca997fb29412f6f5011d7c9591f41528b5b232eb8fcR68) [[3]](diffhunk://#diff-ec0d36f74ae27d945af0aca997fb29412f6f5011d7c9591f41528b5b232eb8fcR112) [[4]](diffhunk://#diff-ec0d36f74ae27d945af0aca997fb29412f6f5011d7c9591f41528b5b232eb8fcR157)
* Added the `rand` crate as a dependency for generating random backoff durations. (`components/resolved_ts/Cargo.toml`, `components/resolved_ts/src/endpoint.rs`) [[1]](diffhunk://#diff-c2f4882f7a8e8623413aa8f361becbaeb23d4c39f27766b4c599bf6c8d86f794R42) [[2]](diffhunk://#diff-10705daa95aaa15a28a65ade2c5207efb566f6267991ac2e8f15ddfdfd245119R30)

**Other improvements:**

* Improved the accuracy of the `CmdBatch::size()` method to better account for memory usage of command batches. (`components/raftstore/src/coprocessor/mod.rs`)
* Added a failpoint for testing after handling change logs. (`components/resolved_ts/src/endpoint.rs`)

| Without this Fix | With this Fix |
|--------|--------|
| image | image | 

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [ ] Need to cherry-pick to the release branch

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note

```release-note
Fix an OOM issue when resolved-ts thread is busy.
```

### CODE REVIEW

File: components/resolved_ts/src/observer.rs [hunk 1]
```diff
@@ -62,6 +69,7 @@ impl<E: KvEngine> CmdObserver<E> for Observer {
         }
         let size = cmd_batches.iter().map(|b| b.size()).sum::<usize>();
         RTS_CHANNEL_PENDING_CMD_BYTES.add(size as i64);
+        self.memory_quota.alloc_force(size);
         if let Err(e) = self.scheduler.schedule(Task::ChangeLog {
             cmd_batch: cmd_batches,
         }) {
```
Comment (hbisheng) [inline components/resolved_ts/src/observer.rs:75]: Do we need to call `self.memory_quota.free` on the schedule failure path here?

**Comment by hbisheng** [comment]
LGTM overall

File: components/resolved_ts/src/endpoint.rs [hunk 2]
```diff
@@ -1146,6 +1191,16 @@ where
 
     fn run(&mut self, task: Task) {
         debug!("run resolved-ts task"; "task" => ?task);
+        if self.last_active_memory_quota_check.elapsed()
+            >= self.cfg.memory_quota_active_check_interval.0
+        {
+            self.last_active_memory_quota_check = std::time::Instant::now();
+            // Check whether memory quota is exceeded actively.
+            if let Err(e) = self.memory_quota.alloc(0) {
```
Comment (LykxSassinator) [inline components/resolved_ts/src/endpoint.rs:1199]: Is it effective with `alloc(0)` for checking whether the memory quota is exceeded ?

Comment (overvenus) [reply components/resolved_ts/src/endpoint.rs:1199]: Yes.

**Review by hbisheng — APPROVED** [review]

File: components/resolved_ts/src/endpoint.rs (hunk 2 above)
Comment (LykxSassinator) [reply components/resolved_ts/src/endpoint.rs:1199]: Got it after reviewing the implementation of `alloc`.
