### PR TITLE
resolved-ts: speed up advancing when stores get partitioned

### LINKED ISSUE #15679: ResolvedTs lag increases after a TiKV store is partitioned
### What version of TiKV are you using?
Master branch.

### Steps to reproduce
1. create a TiKV cluster with 4 instances;
2. starts a TiCDC task;
3. partitions one TiKV instance with `iptables`;

### What did you expect?

ResolvedTs lag shouldn't increase after a jitter.

### What did happened?

ResolvedTs lag increases after a jitter:
图片

### PR DESCRIPTION
**Pull request by hicqu**
### What is changed and how it works?

Issue Number: Close #15679 

What's Changed:

Speed up resolved-ts advancing when stores get partitioned.

Without the PR, a store will wait all `CheckLeader` RPCs return from target stores and then advance ResolvedTs. If a store is partitioned, the RPC to it can take `5s` to return.

With the PR, after a store has collected enough `CheckLeader` RPCs (majority for all involved regions), it can advance ResolvedTs directly.

```commit-message
```

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

Manual test for the issue:
IXskWsA9Lj

Side effects

### Release note 

```release-note
None
```

### CODE REVIEW

File: components/resolved_ts/src/advance.rs [hunk 1]
```diff
@@ -396,10 +386,16 @@ impl LeadershipResolver {
             match res {
                 Ok((to_store, resp)) => {
                     for region_id in resp.regions {
-                        resp_map
-                            .entry(region_id)
-                            .or_insert_with(|| Vec::with_capacity(store_count))
-                            .push(to_store);
+                        if let Some(prog) = progresses.get_mut(&region_id) {
+                            if prog.resolved {
```
Comment (3pointer) [inline components/resolved_ts/src/advance.rs:390]: can we only check region_id in `valid_regions` here and remove resolved?

File: components/resolved_ts/src/advance.rs [hunk 2]
```diff
@@ -409,21 +405,8 @@ impl LeadershipResolver {
...
-            }
-            if let Some(resp) = resp_map.get(region_id) {
-                if resp.is_empty() {
-                    // No response, maybe the peer lost leadership.
-                    continue;
-                }
-                if region_has_quorum(prs, resp) {
-                    valid_regions.insert(*region_id);
-                }
+            if valid_regions.len() >= progresses.len() {
```
Comment (3pointer) [inline components/resolved_ts/src/advance.rs:408]: And I think we can add a log at the end of this function when `valid_regions.len()` is not equal to `checking_regions.len()`. It's useful to debug some resolve ts not moving forward issue.

**Review by 3pointer — APPROVED** [review]
rest LGTM

File: components/resolved_ts/src/advance.rs (hunk 1 above)
Comment (hicqu) [reply components/resolved_ts/src/advance.rs:390]: Check whether a `region_id` is in `valid_regions` or not utilizes more CPU usage. It may be a problem, although I'm not sure.

File: components/resolved_ts/src/advance.rs (hunk 2 above)
Comment (hicqu) [reply components/resolved_ts/src/advance.rs:408]: Done!

**Review by Connor1996 — APPROVED** [review]
LGTM
