### PR TITLE
cdc: fix unresolved region metrics

### LINKED ISSUE #18306: cdc unresolved region count metrics is wrong
### What version of TiKV are you using?

v8.5.0

### Steps to reproduce

1. create a changfeed with a large table;

### What did you expect?
The unresolved region count should first increase to the number of the regions in the large table and decrease gradually.

### What did happened?
The unresolved region count doesn't increase too much and keep at a steady value for a long time.
Image

### PR DESCRIPTION
**Pull request by lidezhu**
### What is changed and how it works?

Issue Number: Close #18306

What's Changed:

```commit-message
 Include regions that have not completed scan locking in the unresolved region count.
```

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [x] Need to cherry-pick to the release branch

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note

```release-note
None.
```

### CODE REVIEW

File: components/cdc/src/delegate.rs [hunk 1]
```diff
@@ -621,6 +621,7 @@ impl Delegate {
         let locks = match &self.lock_tracker {
             LockTracker::Prepared { locks, .. } => locks,
             _ => {
+                advance.blocked_on_scan += 1;
```
Comment (hicqu) [inline components/cdc/src/delegate.rs:624]: It's better to be `advance.blocked_on_scan += self.downstreams.len()`.

Comment (lidezhu) [reply components/cdc/src/delegate.rs]: Fixed.

**Review by hicqu — APPROVED** [review]

**Review by 3AceShowHand — APPROVED** [review]
