### PR TITLE
raftstore-v2: fix peer destroy not clear in scale-in scene

### LINKED ISSUE #14128: [Dynamic Regions] TiKV scale-in failed
## Bug Report
```
[2023/02/02 16:07:43.835 +08:00] [INFO] [life.rs:285] ["mark peer for destroy"] [peer_id=13390] [region_id=589]
[2023/02/02 16:07:43.835 +08:00] [INFO] [life.rs:330] ["start destroy peer"] [peer_id=13390] [region_id=589]
[2023/02/02 16:07:43.835 +08:00] [INFO] [life.rs:304] ["postponed destroy"] ["pending tombstone tablets size"=0] [persisted_apply_index=5821] [committed_index=5848] [applied_index=5848] [peer_id=13390] [region_id=589]
[2023/02/02 16:07:43.840 +08:00] [INFO] [life.rs:356] ["finish peer destroyed"] [peer_id=13390] [region_id=589]
[2023/02/02 16:07:43.840 +08:00] [INFO] [router.rs:342] ["shutdown mailbox"] [region_id=589]
[2023/02/02 16:08:05.878 +08:00] [INFO] [store.rs:716] ["send raft message right"] [type=MsgHeartbeat] [to_peer_id=13642] [region_id=589]
[2023/02/02 16:08:05.878 +08:00] [INFO] [store.rs:716] ["send raft message right"] [type=MsgHeartbeat] [to_peer_id=13642] [region_id=589]
[2023/02/02 16:08:05.879 +08:00] [INFO] [life.rs:163] ["handle raft message"] [msg_type=MsgHeartbeat] [region_id=589] [to_peer_id=13642] [from_peer_id=13424] [store_id=4]
[2023/02/02 16:08:23.845 +08:00] [INFO] [snapshot.rs:543] ["begin to apply snapshot"] [peer_id=13642] [region_id=589]
[2023/02/02 16:08:23.845 +08:00] [INFO] [compact_log.rs:308] ["remove tombstone tablet"] [persisted=5911] [removed=0] [size=0] [peer_id=13642] [region_id=589]
[2023/02/02 16:08:23.861 +08:00] [INFO] [snapshot.rs:263] ["record new tombstone table"] [prev_path=/var/lib/tikv/tablets/589_5821] [new_path=/var/lib/tikv/tablets/589_5911] [peer_id=13642] [region_id=589]
[2023/02/02 16:08:23.861 +08:00] [INFO] [compact_log.rs:278] ["add new tombstone tablet"] [new_tablet_index=5911] [peer_id=13642] [region_id=589]
[2023/02/02 16:08:23.861 +08:00] [INFO] [snapshot.rs:271] ["apply tablet snapshot completely"] [peer_id=13642] [region_id=589]
```

The root cause: 
1. The CacheTablet doesn't remove the old peer cache after destroied the peer, so when the new peer apply snapshot, the 
`set_tablet().is_some` will be true.

some related code:

 

2. Old tombstone tablet should be deleted after apply new snapshot. 

### What version of TiKV are you using?

nightly
### Steps to reproduce
Scale in one tikv

### What did you expect?
There is no region in the offline store

### PR DESCRIPTION
**Pull request by bufferflies**
Signed-off-by: bufferflies <1045931706@qq.com>

### What is changed and how it works?
In some times, peer tombstone tablets maybe not clear but peer received destroy command. 

Issue Number: close #14128

What's Changed:

```commit-message
1. release tablet in TableCache after peer destroyed
2. release tombstone tablet after applying snapshot 
```

### Check List 

Tests 

- Integration test
- Manual test (add detailed scripts or steps below)
image

Side effects

### Release note 

```release-note
None
```

### CODE REVIEW

File: components/engine_traits/src/tablet.rs [hunk 1]
```diff
@@ -32,7 +32,7 @@ pub struct CachedTablet<EK> {
 }
 
 impl<EK> CachedTablet<EK> {
-    fn release(&mut self) {
+    pub fn release(&mut self) {
```
Comment (BusyJay) [inline components/engine_traits/src/tablet.rs:35]: This should remain private.

File: components/raftstore-v2/src/operation/command/admin/compact_log.rs [hunk 2]
```diff
@@ -291,13 +295,24 @@ impl<EK: KvEngine, ER: RaftEngine> Peer<EK, ER> {
 
     /// Returns if there's any tombstone being removed.
     #[inline]
-    fn remove_tombstone_tablets(&mut self, persisted: u64) -> bool {
+    pub fn remove_tombstone_tablets(&mut self, persisted: u64) -> bool {
+        let size = self
+            .compact_log_context()
+            .tombstone_tablets_wait_index
+            .len();
+        let logger = self.logger.clone();
```
Comment (BusyJay) [inline components/raftstore-v2/src/operation/command/admin/compact_log.rs:303]: Why clone?

File: components/raftstore-v2/src/operation/command/admin/compact_log.rs [hunk 3]
```diff
@@ -291,13 +295,24 @@ impl<EK: KvEngine, ER: RaftEngine> Peer<EK, ER> {
...
         let compact_log_context = self.compact_log_context_mut();
         let removed = compact_log_context
             .tombstone_tablets_wait_index
             .iter()
             .take_while(|i| **i <= persisted)
             .count();
+        info!(logger,
```
Comment (BusyJay) [inline components/raftstore-v2/src/operation/command/admin/compact_log.rs:310]: Verbose logs.

File: components/raftstore-v2/src/operation/life.rs [hunk 4]
```diff
@@ -328,13 +336,14 @@ impl<EK: KvEngine, ER: RaftEngine> Peer<EK, ER> {
...
     pub fn finish_destroy<T>(&mut self, ctx: &mut StoreContext<EK, ER, T>) {
-        info!(self.logger, "peer destroyed");
+        info!(self.logger, "peer destroy completely");
         let region_id = self.region_id();
         ctx.router.close(region_id);
         {
             let mut meta = ctx.store_meta.lock().unwrap();
             meta.remove_region(region_id);
             meta.readers.remove(&region_id);
+            self.release_tablet();
```
Comment (BusyJay) [inline components/raftstore-v2/src/operation/life.rs:346]: Should remove the `CachedTablet` from registry instead.

Comment (tonyxuqqi) [inline components/raftstore-v2/src/operation/life.rs:346]: If releasing the tablet cache is needed, then what about the tablet cache in other threads?

File: components/engine_traits/src/tablet.rs (hunk 1 above)
Comment (bufferflies) [reply components/engine_traits/src/tablet.rs]: fixed

File: components/raftstore-v2/src/operation/command/admin/compact_log.rs (hunk 2 above)
Comment (bufferflies) [reply components/raftstore-v2/src/operation/command/admin/compact_log.rs]: fixed

File: components/raftstore-v2/src/operation/command/admin/compact_log.rs (hunk 3 above)
Comment (bufferflies) [reply components/raftstore-v2/src/operation/command/admin/compact_log.rs]: fixed

File: components/raftstore-v2/src/operation/life.rs (hunk 4 above)
Comment (bufferflies) [reply components/raftstore-v2/src/operation/life.rs]: fixed

Comment (bufferflies) [reply components/raftstore-v2/src/operation/life.rs]: yes, using remove from register instead.

File: components/raftstore-v2/src/operation/command/admin/compact_log.rs [hunk 5]
```diff
@@ -275,6 +275,10 @@ impl<EK: KvEngine, ER: RaftEngine> Peer<EK, ER> {
         old_tablet: EK,
         new_tablet_index: u64,
     ) {
+        info!(self.logger,
+            "record tombstone tablet";
```
Comment (BusyJay) [inline components/raftstore-v2/src/operation/command/admin/compact_log.rs:279]: Should include old_tablet's path.

File: components/raftstore-v2/src/operation/command/admin/compact_log.rs [hunk 6]
```diff
@@ -291,7 +295,11 @@ impl<EK: KvEngine, ER: RaftEngine> Peer<EK, ER> {
 
     /// Returns if there's any tombstone being removed.
     #[inline]
-    fn remove_tombstone_tablets(&mut self, persisted: u64) -> bool {
+    pub fn remove_tombstone_tablets(&mut self, persisted: u64) -> bool {
+        info!(self.logger,
```
Comment (BusyJay) [inline components/raftstore-v2/src/operation/command/admin/compact_log.rs:299]: Useless log.

File: components/raftstore-v2/src/operation/life.rs [hunk 7]
```diff
@@ -271,6 +271,7 @@ impl<EK: KvEngine, ER: RaftEngine> Peer<EK, ER> {
     /// Should set the message only when the target peer is supposed to be
     /// created afterward.
     pub fn mark_for_destroy(&mut self, triggered_msg: Option<Box<RaftMessage>>) {
+        info!(self.logger, "mark peer for destroy");
```
Comment (BusyJay) [inline components/raftstore-v2/src/operation/life.rs:274]: Useless log.

File: components/raftstore-v2/src/operation/life.rs [hunk 8]
```diff
@@ -303,6 +304,7 @@ impl<EK: KvEngine, ER: RaftEngine> Peer<EK, ER> {
         ctx: &mut StoreContext<EK, ER, T>,
         write_task: &mut WriteTask<EK, ER>,
     ) {
+        info!(self.logger, "start destroy peer");
```
Comment (BusyJay) [inline components/raftstore-v2/src/operation/life.rs:307]: Useless and verbose log.

File: components/raftstore-v2/src/operation/life.rs [hunk 9]
```diff
@@ -328,13 +330,14 @@ impl<EK: KvEngine, ER: RaftEngine> Peer<EK, ER> {
     /// Tombstone state is persisted. This method is only for cleaning up
     /// memory states.
     pub fn finish_destroy<T>(&mut self, ctx: &mut StoreContext<EK, ER, T>) {
-        info!(self.logger, "peer destroyed");
+        info!(self.logger, "peer destroy completely");
```
Comment (BusyJay) [inline components/raftstore-v2/src/operation/life.rs:333]: Useless log.

File: components/raftstore-v2/src/operation/ready/snapshot.rs [hunk 10]
```diff
@@ -274,6 +275,10 @@ impl<EK: KvEngine, ER: RaftEngine> Peer<EK, ER> {
                 self.post_split_init(ctx, init);
             }
             self.schedule_apply_fsm(ctx);
+            if self.remove_tombstone_tablets(snapshot_index) {
+                let sched = ctx.schedulers.tablet_gc.clone();
```
Comment (BusyJay) [inline components/raftstore-v2/src/operation/ready/snapshot.rs:279]: Why clone?

File: components/raftstore-v2/tests/integrations/test_conf_change.rs [hunk 11]
```diff
@@ -178,3 +178,89 @@ fn test_remove_by_conf_change() {
     assert_eq!(region_state.get_state(), PeerState::Tombstone);
     assert_eq!(raft_engine.get_raft_state(region_id).unwrap(), None);
 }
+
+#[test]
+fn test_tombstore() {
```
Comment (BusyJay) [inline components/raftstore-v2/tests/integrations/test_conf_change.rs:183]: Can the test pass without fix?

**Review by tonyxuqqi — APPROVED** [review]
LGTM except the logging issue Jay mentioned.

File: components/raftstore-v2/tests/integrations/test_conf_change.rs (hunk 11 above)
Comment (bufferflies) [reply components/raftstore-v2/tests/integrations/test_conf_change.rs:183]: No

Comment (BusyJay) [inline components/raftstore-v2/tests/integrations/test_conf_change.rs:183]:
```suggestion
fn test_tombstone() {
```

Should mention what it's testing and what problem it can encouter.

**Review by BusyJay — COMMENTED** [review]
Rest LGTM

File: components/raftstore-v2/tests/integrations/test_conf_change.rs (hunk 11 above)
Comment (bufferflies) [reply components/raftstore-v2/tests/integrations/test_conf_change.rs]: fixed

**Review by BusyJay — APPROVED** [review]

**Review by iosmanthus — APPROVED** [review]
/merge
