### PR TITLE
sst_importer: do not change block_cache_size in import mode

### LINKED ISSUE #6545: Config for Block-Cache Capacity lose efficacy when we use TiDB Lightning to import data.
### What version of TiKV are you using?

master: 7c679639885172814c4ef28f00d190337ce284a4

### What operating system and CPU are you using?

AWS i3.4xlarge

### Steps to reproduce

We execute 'drop table' in a TiDB-cluster, and then import data to TiKV by TiLightning.
Then I observer the size of block cache decreasing to 4GB from 64GB. 

### What did you expect?
We expect that the capacity of block-cache remain unchanged.
### What did happened?
image

### PR DESCRIPTION
**Pull request by kennytm**
###  What have you changed?

"Import mode" was used by TiKV Importer to speed up import by skewing the balance towards write speed. It works by dynamically changing these 5 CF options:

* block_cache_size
* level0_stop_writes_trigger
* level0_slowdown_writes_trigger
* soft_pending_compaction_bytes_limit
* hard_pending_compaction_bytes_limit

Previously, these are hard-coded as [4 GiB, 1 GiB, 1 GiB, 0, 0] respectively. However, there is a bug in TiKV which prevents lowered block_cache_size from restored to a higher value when shared cache was enabled. This makes switching to import mode permanently lose write efficiency.

Setting block_cache_size to 4 GiB was originally an attempt to prevent OOM due to too many L0 files back in TiKV 2.0. We are now 2 major versions later and probably this is no longer needed. So we just stop overwriting block_cache_size in import mode to fix #6545.

###  What is the type of the changes?

- Bugfix (a change which fixes an issue)

###  How is the PR tested?

- Unit test

###  Does this PR affect documentation (docs) or should it be mentioned in the release notes?

No

###  Does this PR affect `tidb-ansible`?

No

###  Refer to a related PR or issue link (optional)

#6545 

## Release note

* No longer overwrite `block_cache_size` after using Lightning / BR.

### CODE REVIEW

**Comment by kennytm** [comment]
PTAL @Little-Wallace @siddontang

**Comment by siddontang** [comment]
will it affect all versions if we use Lightning?

**Comment by kennytm** [comment]
The hard-coding was create back in [release-2.0](https://github.com/tikv/tikv/blob/release-2.0/src/import/import_mode.rs#L75) and not changed since then, so this bug exists on all versions of TiKV.

File: components/sst_importer/src/import_mode.rs [hunk 1]
```diff
@@ -100,11 +106,11 @@ struct ImportModeCFOptions {
...
 
 impl ImportModeCFOptions {
-    fn new() -> ImportModeCFOptions {
-        ImportModeCFOptions {
-            block_cache_size: 4 << 30,
-            level0_stop_writes_trigger: 1 << 30,
-            level0_slowdown_writes_trigger: 1 << 30,
+    fn optimized_for_import_mode(&self) -> Self {
+        Self {
+            block_cache_size: self.block_cache_size.max(4 << 30),
```
Comment (kennytm) [inline components/sst_importer/src/import_mode.rs]: 🤔 According to the original relevant PR #2875 we're supposed to take the `min` instead of `max` here, the rationale is "avoid OOM".

https://github.com/tikv/tikv/blob/22db38d3c321fa7ee78c213afd59d85f5cab85fd/src/config.rs#L165-L169

Comment (huachaohuang) [reply components/sst_importer/src/import_mode.rs]: As far as I can remember, there are a few things to consider here:
1. During the import process, sometimes there are a lot of files in L0
2. Since we enable the option `pin_l0_filter_and_index_blocks`, L0 files can consume a huge amount of memory
3. We can not change `pin_l0_filter_and_index_blocks` dynamically, so we reduce the block cache size instead, hopefully it will "avoid OOM"
4. Import mode is not designed for read performance at all

So I think the real problem here is the potential memory usage of a lot of L0 files, reducing the block cache size is just a workaround. It did work fine in those days, but we can review other options too.

Comment (yiwu-arbug) [reply components/sst_importer/src/import_mode.rs]: I think that was a conservative setting to avoid a previously seen OOM in import mode. I don't see concrete reason to set it, but we may need a bit of testing.

Comment (kennytm) [reply components/sst_importer/src/import_mode.rs]: Let's remove this setting and keep this master-only at the moment.

**Comment by kennytm** [comment]
Something's wrong with this test case: https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/24445/pipeline/101. Gonna rebase for a clean diff and see.

**Comment by zhangjinpeng1987** [comment]
@kennytm Please pick to 4.0 branch
