### PR TITLE
remove empty log at startup

### LINKED ISSUE #7327: Empty log after welcome
## Bug Report
```
[2020/04/01 18:04:31.181 +08:00] [INFO] [lib.rs:97] ["Welcome to TiKV"]
//----------------------empty log!!!---------------
[2020/04/01 18:04:31.182 +08:00] [INFO] [lib.rs:99] [] 
[2020/04/01 18:04:31.182 +08:00] [INFO] [lib.rs:99] ["Release Version:   3.1.0-beta.2"]
[2020/04/01 18:04:31.182 +08:00] [INFO] [lib.rs:99] ["Git Commit Hash:   acd585d8aba82343f094d094a63f16c841ecfe29"]
[2020/04/01 18:04:31.182 +08:00] [INFO] [lib.rs:99] ["Git Commit Branch: HEAD"]
[2020/04/01 18:04:31.182 +08:00] [INFO] [lib.rs:99] ["UTC Build Time:    2020-03-31 06:43:47"]
[2020/04/01 18:04:31.182 +08:00] [INFO] [lib.rs:99] ["Rust Version:      rustc 1.42.0-nightly (0de96d37f 2019-12-19)"]
```
### What version of TiKV are you using?
 Any version

### What operating system and CPU are you using?

Any system

### Steps to reproduce
just start the tikv

### What did you expect?
The empty log shouldn't exist
### What did happened?
The following logic do not check whether the content is empty before printing the log
```
pub fn log_tikv_info() {
    info!("Welcome to TiKV.");
    for line in tikv_version_info().lines() {
        info!("{}", line);
    }
    info!("");
}
```

### PR DESCRIPTION
**Pull request by TommyCpp**
Signed-off-by: zhongyang.wu <zhongyang.wu@outlook.com>

### What problem does this PR solve?

Issue Number: close #7327  

Problem Summary: extra empty line when Tikv startup

### What is changed and how it works?

Filter empty line before print

### Related changes

None

### Check List 

Tests 

- Manual test
  start `cmd/bin/tikv-server.rs` to check output log
Screenshot from 2020-04-01 22-44-21

Side effects

None

### Release note

### CODE REVIEW

File: src/lib.rs [hunk 1]
```diff
@@ -89,7 +89,7 @@ pub fn tikv_version_info() -> String {
 /// Prints the tikv version information to the standard output.
 pub fn log_tikv_info() {
     info!("Welcome to TiKV");
-    for line in tikv_version_info().lines() {
+    for line in tikv_version_info().lines().filter(|s| !s.is_empty()) {
```
Comment (siddontang) [inline src/lib.rs:92]: PTAL @BusyJay

**Comment by TommyCpp** [comment]
@AndreMouche PTAL
