### PR TITLE
Raftstore: destroy peer after applying snapshot (or aborted) if necessary

### LINKED ISSUE #16561: Resolve ts can't not advance
### What version of TiKV are you using?

TiKV
Release Version:   8.0.0-alpha
Edition:           Community
Git Commit Hash:   9b60505a84d550a6d34582b2d44d3066cff9f75e
Git Commit Branch: heads/refs/tags/v8.0.0-alpha
UTC Build Time:    2024-02-24 11:43:24
Rust Version:      rustc 1.77.0-nightly (89e2160c4 2023-12-27)
Enable Features:   pprof-fp jemalloc mem-profiling portable sse test-engine-kv-rocksdb test-engine-raft-raft-engine cloud-aws cloud-gcp cloud-azure trace-async-tasks openssl-vendored
Profile:           dist_release
### Steps to reproduce

random dml
img_v3_028e_f542993c-3699-4180-977a-f32c1e98526g

### PR DESCRIPTION
**Pull request by tonyxuqqi**
### What is changed and how it works?

Issue Number: Close #16561 

What's Changed:

```commit-message
Destroy peer after applying snapshot (or aborted) if it has destroy peer cmd during applying snapshot.
Before this change, it would require extra destroy message to trigger the destroy, which may not happen in short time if the region is hibernated. And it would block the resolve-ts forward. 
```

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [ ] Need to cherry-pick to the release branch

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

### Release note

```release-note
None
```

### CODE REVIEW

File: components/raftstore/src/store/fsm/peer.rs [hunk 1]
```diff
@@ -1246,6 +1241,9 @@ where
             }
             CasualMessage::SnapshotApplied => {
```
Comment (overvenus) [inline components/raftstore/src/store/fsm/peer.rs:1242]: Could you make it a `SignificantMsg`? Because `CasualMessage` may be dropped if the peer is busy.

File: components/raftstore/src/store/fsm/peer.rs [hunk 2]
```diff
@@ -1246,6 +1241,9 @@ where
...
                 self.fsm.has_ready = true;
+                if self.fsm.peer.destroy_after_apply_snapshot() {
+                    self.maybe_destroy();
+                }
```
Comment (overvenus) [inline components/raftstore/src/store/fsm/peer.rs:1246]: Or we can leave it unchanged and set `apply_snap_ctx` to `None` in `check_snap_status`, so that `check_stale_state` will trigger a GC message later.

**Comment by overvenus** [comment]
The current snapshot cancellation is a best effort mechanism. This means that even if the cancellation request is made before the snapshot is applied, there is still a possibility that the snapshot will be applied successfully. Therefore, we have to consider the successful applied situation every time we issue a cancellation.

Maybe we should remove the snapshot cancellation mechanism? Not only reduce corner cases but also simplify code.

File: components/raftstore/src/store/peer.rs [hunk 3]
```diff
@@ -1259,6 +1261,9 @@ where
                 "region_id" => self.region_id,
                 "peer_id" => self.peer.get_id(),
             );
+            if let Some(snap_ctx) = self.apply_snap_ctx.as_mut() {
+                snap_ctx.destroy_peer_after_apply = true;
```
Comment (Connor1996) [inline components/raftstore/src/store/peer.rs:1265]: why not just set `self.apply_snap_ctx = None`

File: components/raftstore/src/store/peer.rs [hunk 4]
```diff
@@ -469,6 +469,7 @@ pub struct ApplySnapshotContext {
     /// The message should be sent after snapshot is applied.
     pub msgs: Vec<eraftpb::Message>,
     pub persist_res: Option<PersistSnapshotResult>,
+    pub destroy_peer_after_apply: bool,
```
Comment (Connor1996) [inline components/raftstore/src/store/peer.rs:472]: Please add comment

File: components/raftstore/src/store/fsm/peer.rs (hunk 2 above)
Comment (Connor1996) [reply components/raftstore/src/store/fsm/peer.rs:1246]: +1

File: components/raftstore/src/store/peer.rs (hunk 3 above)
Comment (tonyxuqqi) [reply components/raftstore/src/store/peer.rs:1265]: Setting it to None has much bigger impact and error prone, as apply_snap_ctx None or not is critical in many places. 
It breaks the original behavior that apply_snap_ctx is only set when the apply is actually finished or aborted (not cancelling). 
The way of this PR does not impact any original behavior. What we need is a hint so that when apply finished, we redo the destroy peer.

File: components/raftstore/src/store/fsm/peer.rs (hunk 2 above)
Comment (tonyxuqqi) [reply components/raftstore/src/store/fsm/peer.rs:1246]: CheckApplyingSnapStatus::Idle => {
                // FIXME: It's possible that the snapshot applying task is canceled.
                // Although it only happens when shutting down the store or destroying
                // the peer, it's still dangerous if continue to handle ready for the
                // peer. So it's better to revoke `JOB_STATUS_CANCELLING` to ensure all
                // started tasks can get finished correctly.
                if self.apply_snap_ctx.is_some() {
                    return false;
                }
            }
I basically agree with the comments above----if we set apply_snap_ctx to None, the actual apply task may be still running.  It's safer to keep the whole cancelling mechanism unless we replace it completely if needed.

Comment (tonyxuqqi) [reply components/raftstore/src/store/fsm/peer.rs:1246]: Setting apply_snap_ctx to None is dangerous.  Previously, we had the assumption that once apply_snap_ctx is None, the apply task in region.rs would finish running and thus the SST file of the snapshot can be GC-ed. And if we set it None here, the apply task can still be running and Snap file GC may mistakenly delete sst files being used by the apply task.  @overvenus @Connor1996

File: components/raftstore/src/store/fsm/peer.rs (hunk 1 above)
Comment (tonyxuqqi) [reply components/raftstore/src/store/fsm/peer.rs:1242]: @overvenus It would make the code quite ugly if we change CasualMessage to SignificantMsg. This is because the Runner in Region.rs now needs to have two router instances, one for CasualMessage and the other for SignificantMsg. We cannot use one instance for both as in test code we use SyncSender for the parameter `router`, one instance simply cannot be both CasualRouter and SignificantRouter at the same time. 
On the other hand, I think it's acceptable to have this message dropped in very busy case because it's just to accelerate the destroy peer speed, and without it, the correctness is still not impacted.

**Comment by tonyxuqqi** [comment]
> The current snapshot cancellation is a best effort mechanism. This means that even if the cancellation request is made before the snapshot is applied, there is still a possibility that the snapshot will be applied successfully. Therefore, we have to consider the successful applied situation every time we issue a cancellation.
> 
> Maybe we should remove the snapshot cancellation mechanism? Not only reduce corner cases but also simplify code.

The cancellation is best effort as regardless snapshot is applied or not, the region will be destroyed so it does not matter in terms of correctness. I think the purpose is mainly for performance. Without cancellation, the snapshot has to be applied even though the region is going to be destroyed immediately. @overvenus

**Review by Connor1996 — APPROVED** [review]
LGTM

**Review by overvenus — APPROVED** [review]
