### PR TITLE
copr: use manually written json path parser

### LINKED ISSUE #13316: JSON path is is incompatible with MySQL
The json path parser is incompatible with MySQL. It doesn't validate the ECMAScript identifier, fails to return the position of error and is extremely hard to read and extend.

For example, it fails to parse: `$ .  你好`, `$  . $`, through they are all valid identifiers.

And the expected return value should be in form: 

```
ERROR 3143 (42000): Invalid JSON path expression. The error is around character position X.
```

But not a simple error `Invalid JSON path: XXX`

### PR DESCRIPTION
**Pull request by YangKeao**
Signed-off-by: YangKeao <yangkeao@chunibyo.icu>

### What is changed and how it works?

Issue Number: Close #13316

What's Changed:

Use a manually written json path parser to parse the path.

### Check List

Tests

- [x] Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

### Release note

```release-note
Fix the issue that the json path format is incompatible with MySQL
```

### CODE REVIEW

**Comment by YangKeao** [comment]
PTAL @xiongjiwei

File: components/tidb_query_datatype/src/codec/mysql/json/path_expr.rs [hunk 1]
```diff
@@ -73,82 +65,325 @@ impl PathExpression {
...
+
+                Ok(PathExpressionToken::Leg((
+                    PathLeg::Key(PATH_EXPR_ASTERISK.to_string()),
+                    Position {
+                        start,
+                        end: self.current_index(),
+                    },
+                )))
+            }
+            (mut key_start, '"') => {
```
Comment (xiongjiwei) [inline components/tidb_query_datatype/src/codec/mysql/json/path_expr.rs:177]: can you please add a test like `'$."a\t"'`. MySQL will report an invalid path since `"a\t"` is not a valid json string. 

it is a corner case, I think it is ok to add the check in the future. ignore this if the test case is passed

**Review by xiongjiwei — APPROVED** [review]
LGTM

**Comment by xiongjiwei** [comment]
lint failed

File: components/tidb_query_datatype/src/codec/mysql/json/path_expr.rs (hunk 1 above)
Comment (YangKeao) [reply components/tidb_query_datatype/src/codec/mysql/json/path_expr.rs:177]: Oops! I didn't realize it. I'll add a test case and fix.

Comment (YangKeao) [reply components/tidb_query_datatype/src/codec/mysql/json/path_expr.rs:177]: Fixed. I checked the ascii control character. However, after unquote, I cannot tell the concrete position of the original input, so I only return the beginning position of the string literal.

File: components/tidb_query_datatype/src/codec/mysql/json/path_expr.rs [hunk 2]
```diff
@@ -73,82 +65,325 @@ impl PathExpression {
...
+    Start(Position),
+}
+
+impl<'a> Iterator for PathExpressionTokenizer<'a> {
+    type Item = Result<PathExpressionToken>;
+
+    // next will try to parse the next path leg and return
+    // if it returns None, it means the input is over.
+    // if it returns Some(Err(..)), it means the format is error.
+    // if it returns Some(Ok(..)), it means the
```
[the remark this answers is not in the document]
Comment (YangKeao) [reply components/tidb_query_datatype/src/codec/mysql/json/path_expr.rs]: Fixed.

**Comment by YangKeao** [comment]
PTAL @wshwsh12 @gengliqi

**Comment by YangKeao** [comment]
@xhebox PTAL

**Review by xhebox — APPROVED** [review]

File: components/tidb_query_datatype/src/codec/mysql/json/path_expr.rs [hunk 3]
```diff
@@ -73,82 +65,331 @@ impl PathExpression {
...
+                    Some((pos, _)) => {
+                        return Err(box_json_path_err!(pos));
+                    }
+                    None => {
+                        return Err(box_json_path_err!(self.current_index()));
+                    }
+                }
+                self.char_iterator.next().unwrap();
+
+                let index = self.input[number_start..number_end].parse::<i32>().unwrap();
```
Comment (sticnarf) [inline components/tidb_query_datatype/src/codec/mysql/json/path_expr.rs:306]: If it overflows, it will make TiKV panic?

Comment (sticnarf) [reply components/tidb_query_datatype/src/codec/mysql/json/path_expr.rs:306]: And I'm not sure what the max acceptable index should be. I try MySQL 5.7.39 and 8.0.30 in docker, the max allowed index is `2^63-1` and `2^32-1` respectively...

File: components/tidb_query_datatype/src/codec/mysql/json/path_expr.rs [hunk 4]
```diff
@@ -175,76 +416,164 @@ mod tests {
...
+            (
+                "$**",
+                Some("Invalid JSON path expression. The error is around character position 3."),
+                None,
+            ),
+            (
+                "$.\"a\\t\"",
+                Some("Invalid JSON path expression. The error is around character position 4."),
+                None,
+            ),
```
[the remark this answers is not in the document]
Comment (YangKeao) [reply components/tidb_query_datatype/src/codec/mysql/json/path_expr.rs:548]: OK! Add two tests: `$ .a $` and `$ .a . $`, the second one is valid :smiley:

File: components/tidb_query_datatype/src/codec/mysql/json/path_expr.rs (hunk 3 above)
Comment (YangKeao) [reply components/tidb_query_datatype/src/codec/mysql/json/path_expr.rs]: Nice catch! But I didn't modify the data type, so the upper limit of current implementation is still `2^31-1`. We are using signed type here because we use the `-1` as a special digit represent `*`. It should be refractored to be an `enum {Asterisk, Index(u64)}`. I'll add an issue for it.

**Review by sticnarf — APPROVED** [review]
LGTM

**Comment by YangKeao** [comment]
@wshwsh12 @gengliqi PTAL

**Review by gengliqi — COMMENTED** [review]
One comment just for coding style: Use `///` instead of `//` to document symbols(like functions or variables in struct/enum) and capitalize the first letter in comments. (Most codes I have seen obey this rule)
FYI: https://doc.rust-lang.org/book/ch14-02-publishing-to-crates-io.html#making-useful-documentation-comments

**Comment by YangKeao** [comment]
> One comment just for coding style: Use /// instead of // to document symbols(like functions or variables in struct/enum) and capitalize the first letter in comments. (Most codes I have seen obey this rule)

@gengliqi Good! Fixed :heart:

File: components/tidb_query_datatype/src/codec/mysql/json/path_expr.rs [hunk 5]
```diff
@@ -73,82 +65,333 @@ impl PathExpression {
...
-        Some(i) => i,
-        None => return Err(box_err!("Invalid JSON path: {}", path_expr)),
-    };
-    if path_expr
-        .index(0..dollar_index)
-        .char_indices()
-        .any(|(_, c)| !c.is_ascii_whitespace())
-    {
-        return Err(box_err!("Invalid JSON path: {}", path_expr));
+// the position is counted from 1
```
Comment (gengliqi) [inline components/tidb_query_datatype/src/codec/mysql/json/path_expr.rs:68]: should also be changed here.

File: components/tidb_query_datatype/src/codec/mysql/json/path_expr.rs [hunk 6]
```diff
@@ -73,82 +65,333 @@ impl PathExpression {
...
+
+    char_iterator: Peekable<CharIndices<'a>>,
+}
+
+struct Position {
+    start: usize,
+    end: usize,
+}
+
+// PathExpressionToken represents a section in path expression and its position
```
Comment (gengliqi) [inline components/tidb_query_datatype/src/codec/mysql/json/path_expr.rs:89]: ditto.

File: components/tidb_query_datatype/src/codec/mysql/json/path_expr.rs [hunk 7]
```diff
@@ -73,82 +65,333 @@ impl PathExpression {
...
+enum PathExpressionToken {
+    Leg((PathLeg, Position)),
+    // represents the beginning "$" in the expression
```
Comment (gengliqi) [inline components/tidb_query_datatype/src/codec/mysql/json/path_expr.rs:92]: ditto.

File: components/tidb_query_datatype/src/codec/mysql/json/path_expr.rs [hunk 8]
```diff
@@ -73,82 +65,333 @@ impl PathExpression {
...
+    Start(Position),
+}
+
+impl<'a> Iterator for PathExpressionTokenizer<'a> {
+    type Item = Result<PathExpressionToken>;
+
+    /// Next will try to parse the next path leg and return
+    /// if it returns None, it means the input is over.
+    /// if it returns Some(Err(..)), it means the format is error.
+    /// if it returns Some(Ok(..)), it represents the next token.
```
Comment (gengliqi) [inline components/tidb_query_datatype/src/codec/mysql/json/path_expr.rs:102]:
```suggestion
    /// Next will try to parse the next path leg and return.
    /// If it returns None, it means the input is over.
    /// If it returns Some(Err(..)), it means the format is error.
    /// If it returns Some(Ok(..)), it represents the next token.
```

**Review by gengliqi — APPROVED** [review]

**Comment by YangKeao** [comment]
@gengliqi Thanks for pointing out :heart: . Fixed :man_facepalming:
