### PR TITLE
import: track inflight ingests during write stall check

### LINKED ISSUE #18452: Unexpected flow control during add index due to stale L0 file check
## Bug report
During an add index operation, we observed that flow control was triggered unexpectedly even though there's already an L0 file check in place. 
Image

The root cause appears to be the time gap between the L0 file check and the actual execution of `ingest_external_file`, leading to over-admission of ingest requests. The issue is more likely to occur when multiple ingestion requests run in parallel and/or each request involves multiple SST files. 

## Explanation
SST ingest flow: 
1. TiDB calls TiKV’s `ingest` interface. At this point, TiKV checks the current number of L0 files in RocksDB.
2. If L0 file count is below the threshold (e.g., <=10), the request is sent to raftstore.
3. The request is committed and then enters the apply phase.
4. The actual `ingest_external_file` call happens.

As an example, let's say step 3 takes a non-trivial time, then *multiple* ingest requests may pass the initial L0 file count check and proceed in parallel. The cumulative effect may cause the L0 file count to exceed the flow control threshold (e.g., >20), violating the intended protection mechanism. This behavior is similar to a classic _read-then-write_ race, where the write decision was based on an outdated read.

## Possible fix
1. Make the initial L0 check stricter by tracking the number of SSTs that are pending ingestion. 
2. Or add another L0 file check before calling `ingest_external_file` during apply. 

## Reference
**Log**: [tikv.log](https://github.com/user-attachments/files/20201493/tikv.log)

**Relevant code path**: 
Image
Image

### PR DESCRIPTION
**Pull request by hbisheng**
### What is changed and how it works?

Issue Number: Close #18452

What's Changed:

```commit-message
This patch addresses #18452 by serializing the write stall check using 
a mutex and tracking inflight WriteCF SSTs. This ensures all concurrent
ingests are accounted for, making the L0 check more conservative and 
preventing over-admission.
```

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [ ] Need to cherry-pick to the release branch

### Check List

Tests 

- [ ] Unit test
- [x] Integration test (
   - The test failed consistently without this fix.
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note

```release-note
Fix over-admission of SST ingest requests in highly concurrent scenarios.
```

### CODE REVIEW

File: components/engine_rocks/src/misc.rs [hunk 1]
```diff
@@ -314,15 +314,15 @@ impl MiscExt for RocksEngine {
...
+    fn ingest_maybe_slowdown_writes(&self, cf: &str, sst_cnt: u64) -> Result<bool> {
         let handle = util::get_cf_handle(self.as_inner(), cf)?;
         if let Some(n) = util::get_cf_num_files_at_level(self.as_inner(), handle, 0) {
             let options = self.as_inner().get_options_cf(handle);
             let slowdown_trigger = options.get_level_zero_slowdown_writes_trigger();
             let compaction_trigger = options.get_level_zero_file_num_compaction_trigger() as u64;
             // Leave enough buffer to tolerate heavy write workload,
             // which may flush some memtables in a short time.
-            if n > u64::from(slowdown_trigger) / 2 && n >= compaction_trigger {
+            if n + sst_cnt - 1 > u64::from(slowdown_trigger) / 2 && n >= compaction_trigger {
```
Comment (v01dstar) [inline components/engine_rocks/src/misc.rs]: Can you explain why `sst_cnt` should be considered when comparing to `slowdown_trigger`, but not `compaction_trigger`?

Comment (hbisheng) [reply components/engine_rocks/src/misc.rs]: My current thinking is: `n >= compaction_trigger` means compaction is running. If we wait, `n` might decrease — so deferring the ingest may get us into a better situation. But if `n < compaction_trigger`, waiting won’t help, so we might as well allow the ingest. 

I can think of another option: we don't consider `compaction_trigger` at all and always reject if `n + sst_cnt - 1 > u64::from(slowdown_trigger) / 2`. Not sure if that will be more reasonable.

Comment (LykxSassinator) [reply components/engine_rocks/src/misc.rs]: Maybe based on the hypothesis that "each ingest operation with a single sst file to `WRITE_CF` might trigger a `flush` and generate a L0 file" ?

Comment (hbisheng) [reply components/engine_rocks/src/misc.rs]: > Maybe based on the hypothesis that "each ingest operation with a single sst file to WRITE_CF might trigger a flush and generate a L0 file"

Flush may not always be relevant. If the ingested SST overlaps with existing SSTs in L0 or L1, RocksDB will place it into L0. Every ingested SST has the potential of going into L0 (depending on the overlap), and the flow control mechanism here might want to consider the worse-case scenario.

File: src/import/ingest.rs [hunk 2]
```diff
@@ -292,6 +297,22 @@ pub async fn ingest<E: Engine>(
...
+    // Check if there is a write stall.
+    if let Some(errorpb) = check_write_stall(
+        req.get_context().get_region_id(),
+        tablets,
+        store_meta,
+        importer,
+        ingest_latch.count_ssts_in_cf(CF_WRITE),
+    ) {
+        for m in metas {
+            ingest_latch.release_lock(&m).unwrap();
```
Comment (overvenus) [inline src/import/ingest.rs]: Should we track pending ingestion for followers using ingest_latch?

Comment (hbisheng) [reply src/import/ingest.rs]: For followers, it seems tricky because the ingest requests come from raft replication. We would need to pass the `ingest_latch` to the apply batch system, but even with that I'm not sure if there's a way to distinguish leaders and followers there. I'll take a look. But you are right that currently this PR is only throttling ingest requests on leaders.

File: components/engine_rocks/src/misc.rs (hunk 1 above)
Comment (hbisheng) [reply components/engine_rocks/src/misc.rs]: @v01dstar I later realized that `sst_cnt` should be considered as well when comparing to `slowdown_trigger`. Otherwise, if `n < compaction_trigger` but many ingest requests arrive concurrently, they may all be allowed through, violating the admission control.

File: src/import/ingest.rs (hunk 2 above)
Comment (hbisheng) [reply src/import/ingest.rs]: Theoretically, a store with only followers could receive too many ingest requests, since admission control is enforced only on the leader side. I haven’t found a good way to fully prevent that, but there’s currently no sign of it happening in production. So I think I will focus on the issue at hand, which has been observed in real cases.

**Review by overvenus — APPROVED** [review]

**Review by v01dstar — APPROVED** [review]
