### PR TITLE
cdc: add watchdog for cdc conn

### LINKED ISSUE #18169: TiKV-CDC Memory Quota Reached 512 MB After TiCDC Restart, Changefeed Stuck and Unrecoverable
## Bug Report

1. Our production CDC instance running in Kubernetes was restarted.  
2. After the restart, the memory usage of TiKV-CDC began to increase continuously.  
3. Eventually, the memory quota (512 MB) was fully utilized, causing the Changefeed to hang.  
4. Restarting the CDC instance multiple times did not resolve the issue. The memory quota of TiKV-CDC remained at 512 MB, and the Changefeed remained stuck.

### What version of TiKV are you using?

- 14 TiKV nodes with v7.5.4
- 2 TiCDC nodes with v7.5.4

### What did you expect?

- TiKV-CDC should release memory after the restart and operate within the configured memory quota.  
- The Changefeed should resume normal processing after restarting the CDC instance.

### What did happened?

- TiKV-CDC's memory usage continued to increase after the restart and eventually hit the 512 MB quota.  
- The Changefeed was stuck and unable to recover.  
- Restarting the CDC instance multiple times did not free up memory or resolve the issue. The memory quota of TiKV-CDC remained at 512 MB.

### PR DESCRIPTION
**Pull request by asddongmen**
### What is changed and how it works?

Issue Number: Close #18169 

The main intent is to resolve a problem where the CDC sink's memory quota increases indefinitely after a downstream TiCDC node disconnects. This leak persists until the TiKV instance is manually restarted. The underlying cause is suspected to be dangling connections that are not properly released after the downstream becomes unavailable.

In summary, this PR resolves the issue through the following steps:

1. Introduce Watchdog: A background task is created specifically for monitoring.

2. Register Connections: New CDC connections are registered with the watchdog upon creation.

3. Periodic Checks: The watchdog periodically checks the last_flush_time of each connection against a timeout.

4. Release Connections: If a connection is determined to be stuck, the watchdog forcibly disconnects it, releasing its associated memory and resources.

This mechanism ensures that dangling connections are promptly cleaned up even if a downstream TiCDC node becomes unresponsive, preventing the unbounded memory growth and improving the system's stability.

What's Changed:

```commit-message

```

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [x] Need to cherry-pick to the release branch

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [x] Manual test (add detailed scripts or steps below)

1. Make a tikv with failpoint enable. 
```
FAIL_POINT=1 make build
```
2. Start a cluster with this tikv-server.
3. Create 3 changefeeds, and they are normal.
4. Inject the failpoints.
```
curl -X PUT "http://127.0.0.1:20180/fail/cdc_idle_deregister_threshold" -d "return(true)"

curl -X PUT "http://127.0.0.1:20180/fail/cdc_sleep_after_sink_flush"    -d "return(true)"
```
5. It can be seen that all changefeed got stuck and.
6. After 30 seconds, the cdc connections were closed, and the downstream cdc will try to create a new connection 
```
[2025/07/31 16:27:48.884 +08:00] [ERROR] [service.rs:568] ["cdc connection idle for too long, aborting connection"] [seconds_since_last_flush=40] [conn_id=ConnId(217)] [downstream=ipv4:127.0.0.1:49452] [thread_id=170]
[2025/07/31 16:27:48.884 +08:00] [ERROR] [service.rs:568] ["cdc connection idle for too long, aborting connection"] [seconds_since_last_flush=40] [conn_id=ConnId(216)] [downstream=ipv4:127.0.0.1:49452] [thread_id=170]
[2025/07/31 16:27:48.902 +08:00] [ERROR] [service.rs:568] ["cdc connection idle for too long, aborting connection"] [seconds_since_last_flush=40] [conn_id=ConnId(219)] [downstream=ipv4:127.0.0.1:49453] [thread_id=170]
[2025/07/31 16:27:48.902 +08:00] [ERROR] [service.rs:568] ["cdc connection idle for too long, aborting connection"] [seconds_since_last_flush=40] [conn_id=ConnId(218)] [downstream=ipv4:127.0.0.1:49453] [thread_id=170]
[2025/07/31 16:27:49.887 +08:00] [INFO] [service.rs:448] ["cdc connection created"] [conn_id=ConnId(228)] [features="[\"stream-multiplexing\"]"] [downstream=ipv4:127.0.0.1:49737] [thread_id=9]
[2025/07/31 16:27:49.889 +08:00] [INFO] [service.rs:448] ["cdc connection created"] [conn_id=ConnId(229)] [features="[\"stream-multiplexing\"]"] [downstream=ipv4:127.0.0.1:49737] [thread_id=9]
[2025/07/31 16:27:49.904 +08:00] [INFO] [service.rs:448] ["cdc connection created"] [conn_id=ConnId(230)] [features="[\"stream-multiplexing\"]"] [downstream=ipv4:127.0.0.1:49740] [thread_id=10]
[2025/07/31 16:27:49.905 +08:00] [INFO] [service.rs:448] ["cdc connection created"] [conn_id=ConnId(231)] [features="[\"stream-multiplexing\"]"] [downstream=ipv4:127.0.0.1:49740] [thread_id=10]
```
7. Delete all failpoints.
```
curl -X DELETE "http://127.0.0.1:20180/fail/cdc_sleep_after_sink_flush"
curl -X DELETE "http://127.0.0.1:20180/fail/cdc_idle_deregister_threshold"
```
8. Changefeeds resume to normal.

- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note

```release-note
Fix a bug that may cause the sink memory quota not to be released.
```

### CODE REVIEW

File: components/cdc/src/channel.rs [hunk 1]
```diff
@@ -416,13 +421,38 @@ impl<'a> Drain {
                 sink.feed((e, write_flags)).await?;
             }
             sink.flush().await?;
+            sleep_after_sink_flush().await;
+            // Update last flush time if provided
+            if let Some(time_tracker) = last_flush_time {
+                use std::time::{SystemTime, UNIX_EPOCH};
```
Comment (wlwilliamx) [inline components/cdc/src/channel.rs]: It's better to place `use` statements at the top of the function or module rather than inside a block.

File: components/cdc/src/channel.rs [hunk 2]
```diff
@@ -416,13 +421,38 @@ impl<'a> Drain {
...
+async fn sleep_after_sink_flush() {
+    let should_sleep = || {
+        fail::fail_point!("cdc_sleep_after_sink_flush", |_| true);
+        false
+    };
+    if !should_sleep() {
+        return;
+    }
+    info!("inside sleep_after_sink_flush failpoint, sleep 5 minutes!"); 
+    use std::time::{Duration, Instant};
```
Comment (wlwilliamx) [inline components/cdc/src/channel.rs]: It's better to place use statements at the top of the function or module rather than inside a block.

File: components/cdc/src/service.rs [hunk 3]
```diff
@@ -473,17 +491,99 @@ impl Service {
...
+                    last_flush_time_for_forward.store(0, Ordering::Relaxed);
+                }
+            }
+        });
+
+        // Add watchdog loop to monitor connection activity using tokio runtime
+        let pool = self.pool.clone();
+        pool.spawn(async move {
+            use std::time::{SystemTime, UNIX_EPOCH, Duration};
+            use tokio::time::interval;
```
Comment (wlwilliamx) [inline components/cdc/src/service.rs]: It's better to place use statements at the top of the function or module rather than inside a block.

File: components/cdc/src/service.rs [hunk 4]
```diff
@@ -473,17 +491,99 @@ impl Service {
...
             sleep_before_drain_change_event().await;
-            if let Err(e) = event_drain.forward(&mut sink).await {
-                warn!("cdc send failed"; "error" => ?e, "downstream" => peer, "conn_id" => ?conn_id);
-            } else {
-                info!("cdc send closed"; "downstream" => peer, "conn_id" => ?conn_id);
+            tokio::select! {
+                _ = &mut cancel_rx => {
+                    warn!("cdc send cancelled"; "downstream" => peer, "conn_id" => ?conn_id);
+                    let status = RpcStatus::with_message(RpcStatusCode::UNKNOWN, "connection cancelled".to_string());
+                    let _ = sink.fail(status).await;
```
Comment (wlwilliamx) [inline components/cdc/src/service.rs:513]: It's better to close stream as well.

File: components/cdc/src/service.rs [hunk 5]
```diff
@@ -248,16 +254,27 @@ impl EventFeedHeaders {
...
     /// It requires a scheduler of an `Endpoint` in order to schedule tasks.
     pub fn new(scheduler: Scheduler<Task>, memory_quota: Arc<MemoryQuota>) -> Service {
+        let pool = Arc::new(
+            tokio::runtime::Builder::new_multi_thread()
+                .worker_threads(1)
+                .thread_name("cdc-watchdog")
+                .enable_all()
+                .build()
+                .unwrap(),
+        );
```
Comment (wlwilliamx) [inline components/cdc/src/service.rs]: This seems quite similar to using `ctx.spawn`, especially since it's a multi-thread runtime with only one worker thread.

File: components/cdc/src/service.rs [hunk 6]
```diff
@@ -473,17 +491,99 @@ impl Service {
...
-            if let Err(e) = event_drain.forward(&mut sink).await {
-                warn!("cdc send failed"; "error" => ?e, "downstream" => peer, "conn_id" => ?conn_id);
-            } else {
-                info!("cdc send closed"; "downstream" => peer, "conn_id" => ?conn_id);
+            tokio::select! {
+                _ = &mut cancel_rx => {
+                    warn!("cdc send cancelled"; "downstream" => peer, "conn_id" => ?conn_id);
+                    let status = RpcStatus::with_message(RpcStatusCode::UNKNOWN, "connection cancelled".to_string());
+                    let _ = sink.fail(status).await;
+                    return;
```
Comment (wlwilliamx) [inline components/cdc/src/service.rs]: Deregister::Conn should be executed

File: components/cdc/src/service.rs (hunk 5 above)
Comment (asddongmen) [reply components/cdc/src/service.rs]: I wrote it this way to make all Streams share the same pool, thereby reducing the number of threads.

File: components/cdc/src/service.rs (hunk 4 above)
Comment (asddongmen) [reply components/cdc/src/service.rs:513]: It woluld alsoe be close when this function return.

File: components/cdc/src/endpoint.rs [hunk 7]
```diff
@@ -714,30 +714,39 @@ impl<T: 'static + CdcHandle<E>, E: KvEngine, S: StoreRegionMeta> Endpoint<T, E,
...
-                for (region_id, downstream) in conn.unsubscribe_request(request_id) {
-                    let err = Some(Error::Other("region not found".into()));
-                    self.deregister_downstream(region_id, downstream, err);
+                if let Some(conn) = self.connections.get_mut(&conn_id) {
+                    for (region_id, downstream) in conn.unsubscribe_request(request_id) {
+                        let err = Some(Error::Other("region not found".into()));
+                        self.deregister_downstream(region_id, downstream, err);
+                    }
+                } else {
+                    info!("cdc connection already deregistered for request deregister"; "conn_id" => ?conn_id, "request_id" => ?request_id);
```
Comment (overvenus) [inline components/cdc/src/endpoint.rs]:
```suggestion
                    info!(
                        "cdc connection already deregistered for request deregister";
                        "conn_id" => ?conn_id, "request_id" => ?request_id,
                    );
```

File: components/cdc/src/endpoint.rs [hunk 8]
```diff
@@ -714,30 +714,39 @@ impl<T: 'static + CdcHandle<E>, E: KvEngine, S: StoreRegionMeta> Endpoint<T, E,
...
-                if let Some(downstream) = conn.unsubscribe(request_id, region_id) {
-                    let err = Some(Error::Other("region not found".into()));
-                    self.deregister_downstream(region_id, downstream, err);
+                if let Some(conn) = self.connections.get_mut(&conn_id) {
+                    if let Some(downstream) = conn.unsubscribe(request_id, region_id) {
+                        let err = Some(Error::Other("region not found".into()));
+                        self.deregister_downstream(region_id, downstream, err);
+                    }
+                } else {
+                    info!("cdc connection already deregistered for region deregister"; "conn_id" => ?conn_id, "request_id" => ?request_id, "region_id" => region_id);
```
Comment (overvenus) [inline components/cdc/src/endpoint.rs]: Wrap the line.

File: components/cdc/src/service.rs [hunk 9]
```diff
@@ -248,16 +257,27 @@ impl EventFeedHeaders {
...
     ///
     /// It requires a scheduler of an `Endpoint` in order to schedule tasks.
     pub fn new(scheduler: Scheduler<Task>, memory_quota: Arc<MemoryQuota>) -> Service {
+        let pool = Arc::new(
+            tokio::runtime::Builder::new_multi_thread()
+                .worker_threads(1)
+                .thread_name("cdc-watchdog")
+                .enable_all()
+                .build()
+                .unwrap(),
```
Comment (overvenus) [inline components/cdc/src/service.rs]: Please avoid creating new threads. You can use background workers https://github.com/tikv/tikv/blob/d2f1a3705b676d61f7917bbff15e5002d92b9ef5/components/server/src/server.rs#L376

File: components/cdc/src/service.rs [hunk 10]
```diff
@@ -428,7 +448,7 @@ impl Service {
             };
             explicit_features = headers.features;
         }
-        info!("cdc connection created"; "downstream" => ctx.peer(), "features" => ?explicit_features);
+        info!("cdc connection created"; "downstream" => ctx.peer(), "features" => ?explicit_features, "conn_id" => ?conn_id);
```
Comment (overvenus) [inline components/cdc/src/service.rs]: Please wrap long lines in your PR.

File: components/cdc/src/service.rs [hunk 11]
```diff
@@ -473,14 +493,111 @@ impl Service {
...
+            }
+        });
+
+        // Add watchdog loop to monitor connection activity using tokio runtime
+        let pool = self.pool.clone();
+        pool.spawn(async move {
+            // Create an interval that ticks every CDC_WATCHDOG_CHECK_INTERVAL_SECS
+            let mut interval = interval(Duration::from_secs(CDC_WATCHDOG_CHECK_INTERVAL_SECS));
+
+            loop {
```
Comment (overvenus) [inline components/cdc/src/service.rs]: Please extract this loop as a function.

File: components/cdc/src/service.rs [hunk 12]
```diff
@@ -473,14 +493,111 @@ impl Service {
...
+                    }
+                    _ = &mut forward_exit_rx => {
+                        info!("cdc eventDrain.forward exited, watchdog loop will exit";
+                              "downstream" => peer_for_watchdog.clone(),
+                              "conn_id" => ?conn_id);
+                        break;
+                    }
+                }
+
+                let current_time = match SystemTime::now().duration_since(UNIX_EPOCH) {
```
Comment (overvenus) [inline components/cdc/src/service.rs]: Prefer `Instant`.

File: components/cdc/tests/failpoints/test_endpoint.rs [hunk 13]
```diff
@@ -811,3 +811,94 @@ fn test_cdc_unresolved_region_count_before_finish_scan_lock() {
...
+    // Create event feed connection
+    let (mut req_tx, event_feed, _) = new_event_feed(suite.get_region_cdc_client(region.id));
+    let mut req = suite.new_changedata_request(region.id);
+    req.mut_header().set_ticdc_version("7.5.0".into());
+    block_on(req_tx.send((req, WriteFlags::default()))).unwrap();
+
+    // Wait for the connection to be established and initialized
+    thread::sleep(Duration::from_millis(1000));
+
+    eprintln!("Starting watchdog test - waiting for connection to be cancelled");
```
Comment (overvenus) [inline components/cdc/tests/failpoints/test_endpoint.rs]:
```suggestion
    debug!("Starting watchdog test - waiting for connection to be cancelled");
```

Or remove it.

File: components/cdc/src/service.rs (hunk 9 above)
Comment (asddongmen) [reply components/cdc/src/service.rs]: done, PTAL

File: components/cdc/src/endpoint.rs [hunk 14]
```diff
@@ -714,30 +714,41 @@ impl<T: 'static + CdcHandle<E>, E: KvEngine, S: StoreRegionMeta> Endpoint<T, E,
...
-                let conn = self.connections.remove(&conn_id).unwrap();
-                conn.iter_downstreams(|_, region_id, downstream_id, _| {
-                    self.deregister_downstream(region_id, downstream_id, None);
-                });
+                if let Some(conn) = self.connections.remove(&conn_id) {
+                    conn.iter_downstreams(|_, region_id, downstream_id, _| {
+                        self.deregister_downstream(region_id, downstream_id, None);
+                    });
+                } else {
+                    info!("cdc connection already deregistered"; "conn_id" => ?conn_id);
```
Comment (3AceShowHand) [inline components/cdc/src/endpoint.rs:722]: Shall we print the log here? Looks the connection can only be deregistered once by recv_req exit.

File: components/cdc/src/endpoint.rs [hunk 15]
```diff
@@ -714,30 +714,41 @@ impl<T: 'static + CdcHandle<E>, E: KvEngine, S: StoreRegionMeta> Endpoint<T, E,
...
-                    let err = Some(Error::Other("region not found".into()));
-                    self.deregister_downstream(region_id, downstream, err);
+                if let Some(conn) = self.connections.get_mut(&conn_id) {
+                    for (region_id, downstream) in conn.unsubscribe_request(request_id) {
+                        let err = Some(Error::Other("region not found".into()));
+                        self.deregister_downstream(region_id, downstream, err);
+                    }
+                } else {
+                    info!("cdc connection already deregistered for request deregister"; 
+                    "conn_id" => ?conn_id, "request_id" => ?request_id);
```
Comment (3AceShowHand) [inline components/cdc/src/endpoint.rs]: set the `conn_id` the last field, so it will be print at the first, to match other logs.

File: components/cdc/src/endpoint.rs [hunk 16]
```diff
@@ -714,30 +714,41 @@ impl<T: 'static + CdcHandle<E>, E: KvEngine, S: StoreRegionMeta> Endpoint<T, E,
...
-                    let err = Some(Error::Other("region not found".into()));
-                    self.deregister_downstream(region_id, downstream, err);
+                if let Some(conn) = self.connections.get_mut(&conn_id) {
+                    if let Some(downstream) = conn.unsubscribe(request_id, region_id) {
+                        let err = Some(Error::Other("region not found".into()));
+                        self.deregister_downstream(region_id, downstream, err);
+                    }
+                } else {
+                    info!("cdc connection already deregistered for region deregister";
+                     "conn_id" => ?conn_id, "request_id" => ?request_id, "region_id" => region_id);
```
Comment (3AceShowHand) [inline components/cdc/src/endpoint.rs]: ditto

File: components/cdc/src/service.rs [hunk 17]
```diff
@@ -428,7 +444,8 @@ impl Service {
             };
             explicit_features = headers.features;
         }
-        info!("cdc connection created"; "downstream" => ctx.peer(), "features" => ?explicit_features);
+        info!("cdc connection created"; "downstream" => ctx.peer(),
+         "features" => ?explicit_features, "conn_id" => ?conn_id);
```
Comment (3AceShowHand) [inline components/cdc/src/service.rs]: set the feature as first field since downstream print the ip address, it's more important than the feature, which always print `multiplexing`

File: components/cdc/src/service.rs [hunk 18]
```diff
@@ -473,14 +490,121 @@ impl Service {
             }
         });
 
+        // Create atomic variable to track last flush time
```
Comment (3AceShowHand) [inline components/cdc/src/service.rs]: this looks can be removed.

File: components/cdc/src/service.rs [hunk 19]
```diff
@@ -473,14 +490,121 @@ impl Service {
...
+        let last_flush_time = Arc::new(AtomicCell::new(Instant::now()));
+        let last_flush_time_for_forward = last_flush_time.clone();
+        let last_flush_time_for_watchdog = last_flush_time.clone();
+        let peer_for_watchdog = ctx.peer().to_string();
+
         let peer = ctx.peer();
+        let (cancel_tx, mut cancel_rx) = tokio::sync::oneshot::channel::<()>();
+
+        // Create cancelCh for eventDrain.forward exit signal
+        let (forward_exit_tx, forward_exit_rx) = tokio::sync::oneshot::channel::<()>();
```
Comment (3AceShowHand) [inline components/cdc/src/service.rs:504]: It looks that `tikv_util::future::paired_future_callback();` can be used to send signal, it's used in the tikv-cdc.

File: components/cdc/src/service.rs [hunk 20]
```diff
@@ -473,14 +490,121 @@ impl Service {
...
+        let forward_exit_tx_for_forward = forward_exit_tx;
```
Comment (3AceShowHand) [inline components/cdc/src/service.rs]: It looks this can be removed.

File: components/cdc/src/service.rs [hunk 21]
```diff
@@ -473,14 +490,121 @@ impl Service {
...
-                warn!("cdc send failed"; "error" => ?e, "downstream" => peer, "conn_id" => ?conn_id);
-            } else {
-                info!("cdc send closed"; "downstream" => peer, "conn_id" => ?conn_id);
+            tokio::select! {
+                _ = &mut cancel_rx => {
+                    warn!("cdc send cancelled"; "downstream" => peer, "conn_id" => ?conn_id);
+                    let status = RpcStatus::with_message(RpcStatusCode::UNKNOWN, "connection cancelled".to_string());
+                    let _ = sink.fail(status).await;
+                }
+                result = event_drain.forward(&mut sink, Some(&last_flush_time_for_forward)) => {
```
Comment (3AceShowHand) [inline components/cdc/src/service.rs:516]: It looks that we can only let the forward exit, and then the drain is dropped to release the memory quota.

recv_req cannot returned if the gRPC-rs pool is stuck.

File: components/cdc/src/service.rs [hunk 22]
```diff
@@ -473,14 +490,121 @@ impl Service {
...
+        mut forward_exit_rx: tokio::sync::oneshot::Receiver<()>,
+    ) {
+        let last_flush_time_clone = last_flush_time.clone();
+        let peer_clone = peer.clone();
+
+        // Create a custom interval task that can be stopped
+        let _ = pool.pool().spawn(async move {
+            let mut interval = GLOBAL_TIMER_HANDLE
+                .interval(
+                    std::time::Instant::now(),
```
Comment (3AceShowHand) [inline components/cdc/src/service.rs]:
```suggestion
                    Instant::now(),
```

File: components/cdc/src/service.rs [hunk 23]
```diff
@@ -473,14 +490,121 @@ impl Service {
...
+
+                        // Check if last flush was more than the deregister threshold
+                        if elapsed > Duration::from_secs(_idle_threshold) {
+                            error!("cdc connection idle for too long, aborting connection";
+                                   "downstream" => peer_clone.clone(),
+                                   "conn_id" => ?conn_id,
+                                   "seconds_since_last_flush" => elapsed.as_secs());
+                            // Cancel the gRPC connection
+                            let _ = cancel_tx.send(());
+                            CDC_ABORTED_CONNECTIONS.inc();
```
Comment (3AceShowHand) [inline components/cdc/src/service.rs]:
```suggestion
```

File: components/cdc/src/service.rs [hunk 24]
```diff
@@ -473,14 +490,121 @@ impl Service {
...
         ctx.spawn(async move {
             #[cfg(feature = "failpoints")]
             sleep_before_drain_change_event().await;
-            if let Err(e) = event_drain.forward(&mut sink).await {
-                warn!("cdc send failed"; "error" => ?e, "downstream" => peer, "conn_id" => ?conn_id);
-            } else {
-                info!("cdc send closed"; "downstream" => peer, "conn_id" => ?conn_id);
+            tokio::select! {
+                _ = &mut cancel_rx => {
+                    warn!("cdc send cancelled"; "downstream" => peer, "conn_id" => ?conn_id);
```
Comment (3AceShowHand) [inline components/cdc/src/service.rs:511]:
```suggestion
                    warn!("cdc send cancelled"; "downstream" => peer, "conn_id" => ?conn_id);
                    CDC_ABORTED_CONNECTIONS.inc();
```

File: components/cdc/src/service.rs (hunk 19 above)
Comment (3AceShowHand) [reply components/cdc/src/service.rs:504]: `tokio::sync::oneshot::channel` is also good, but it's not widely used in the whole code base. 

It looks good to me, more easier to understand.

File: components/cdc/src/service.rs (hunk 23 above)
Comment (3AceShowHand) [reply components/cdc/src/service.rs]: Let the receiver decide what to do.

**Review by 3AceShowHand — APPROVED** [review]

File: components/cdc/src/service.rs (hunk 9 above)
Comment (overvenus) [reply components/cdc/src/service.rs]: I mean you can spawn wachdog tasks to this background_worker.

**Comment by asddongmen** [comment]
/needs-cherry-pick-release-7.5
