### PR TITLE
Status server: make CN check more fine-grained

### LINKED ISSUE #7987: metrics with TLS should not check the client identity
## Bug Report

We recently (in TiKV 4.0, not 3.0) added the ability to have TLS with client CN verification. There are 2 problems with getting metrics now:

1. If TLS is enabled, the client must authenticate using a certificate with the same CN as any other client.
2. Allowing clients that only need metrics to access the entire API is a security problem.

We still need TLS. The proposed solution is to not check the CN for the metrics route. From a principles perspective separate authentication from authorization. For the metrics route authorization can be different.

It is ideal to also support verifying a different CN for metrics, but I suspect most would prefer to not bother with CN verification for the metrics route since they are read-only and only reveal the operational state of the system.

I believe this issue is present in both PD & TiKV.

### PR DESCRIPTION
**Pull request by hunterlxt**
Signed-off-by: Xintao <hunterlxt@live.com>

### What problem does this PR solve?

Issue Number: close #7987 

Problem Summary:
Some query related requests do not need to be CN checked.

### What is changed and how it works?

- Make CN check more fine-grained.
- SecurityConfig is some fields related to exact one StatusServer, let's migrate it into `new()` function.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Manual test (add detailed scripts or steps below)
1. create 1tikv/1pd with tls
2. Confirm that it can be accessed by curl with a certificate
3. create 1tikv/1pd with tls and set allowed-cn
4. Confirm that it can be accessed by curl with a right certificate
5. Confirm that it showed "role error" by curl with a wrong certificate

Side effects

No

### Release note 

* Skip CN (common name) check when accessing metrics endpoint when TLS is enabled.

### CODE REVIEW

File: src/server/status_server/mod.rs [hunk 1]
```diff
@@ -641,6 +664,82 @@ where
...
+                                Self::dump_rsperf_to_resp(req).await
+                            }
+                            (Method::GET, path) if path.starts_with("/region") => {
+                                Self::dump_region_meta(req, router).await
+                            }
+                            _ => Ok(StatusServer::err_response(
+                                StatusCode::NOT_FOUND,
+                                "path not found",
+                            )),
+                        }
```
Comment (overvenus) [inline src/server/status_server/mod.rs:728]: This is almost identical to https://github.com/tikv/tikv/pull/8064/files#diff-d9e7f217b700ad74e968ee5cfdce6ab0R619-R652, could you unify them?

Comment (hunterlxt) [reply src/server/status_server/mod.rs:728]: Sure, I am looking for a easy solution to solve

File: src/server/status_server/mod.rs [hunk 2]
```diff
@@ -641,6 +664,82 @@ where
...
+        I::Conn: AsyncRead + AsyncWrite + Unpin + Send + 'static,
+    {
+        let cfg_controller = self.cfg_controller.clone();
+        let router = self.router.clone();
+        // Start to tls serve.
+        let server = builder.serve(make_service_fn(move |conn: &SslStream<AddrStream>| {
+            let cfg_controller = cfg_controller.clone();
+            let router = router.clone();
+            let x509 = conn.ssl().peer_certificate();
+            let cert_allowed_cn = cert_allowed_cn.clone();
```
Comment (sticnarf) [inline src/server/status_server/mod.rs:680]: It seems that they are cloned every time a new request comes. Maybe `Arc` is a better idea?

File: src/server/status_server/mod.rs (hunk 1 above)
Comment (hunterlxt) [reply src/server/status_server/mod.rs]: Done, thank for @sticnarf's suggestion.

File: src/server/status_server/mod.rs (hunk 2 above)
Comment (hunterlxt) [reply src/server/status_server/mod.rs]: Fixed

**Comment by hunterlxt** [comment]
cc @BusyJay

File: src/server/status_server/mod.rs [hunk 3]
```diff
@@ -614,13 +623,27 @@ where
                                 Self::get_config(req, &cfg_controller).await
                             }
                             (Method::POST, "/config") => {
-                                Self::update_config(cfg_controller.clone(), req).await
+                                if check_cert(security_config, x509) {
+                                    Self::update_config(cfg_controller.clone(), req).await
```
Comment (yiwu-arbug) [inline src/server/status_server/mod.rs:627]: leave comment to explain what are the endpoints that should call check_cert?

Comment (hunterlxt) [reply src/server/status_server/mod.rs:627]: Done PTAL

File: src/server/status_server/mod.rs [hunk 4]
```diff
@@ -614,13 +623,30 @@ where
                                 Self::get_config(req, &cfg_controller).await
                             }
                             (Method::POST, "/config") => {
-                                Self::update_config(cfg_controller.clone(), req).await
+                                // The operation will modify the configuration of TiKV.
```
Comment (yiwu-arbug) [inline src/server/status_server/mod.rs:626]:
```suggestion
                                // Check cert since the operation will modify the configuration of TiKV.
```

File: src/server/status_server/mod.rs [hunk 5]
```diff
@@ -614,13 +623,30 @@ where
...
+                                        "certificate role error",
+                                    ))
+                                }
                             }
                             (Method::GET, "/debug/pprof/profile") => {
                                 Self::dump_rsperf_to_resp(req).await
                             }
                             (Method::GET, path) if path.starts_with("/region") => {
-                                Self::dump_region_meta(req, router).await
+                                // The operation will get start key and end key. These keys could be actual
```
Comment (yiwu-arbug) [inline src/server/status_server/mod.rs:640]:
```suggestion
                                // Check cert since the operation will get start key and end key. These keys could be actual
```

File: src/server/status_server/mod.rs [hunk 6]
```diff
@@ -614,13 +623,30 @@ where
                                 Self::get_config(req, &cfg_controller).await
                             }
                             (Method::POST, "/config") => {
-                                Self::update_config(cfg_controller.clone(), req).await
+                                // Check cert since the operation will modify the configuration of TiKV.
+                                if check_cert(security_config, x509) {
```
Comment (yiwu-arbug) [inline src/server/status_server/mod.rs:627]: After a second thought, I think the flow should be like this
```
// insert before line 616.
let should_check_cert = match (method, path.as_ref()) {
    (Method::GET, "/metrics") => false,
    (Method::GET, "/status") => false,
    (Method::GET, "/config") => false,
    (Method::GET, "/debug/pprof/profile") => fasle,
    _ => true,
};
if should_check_cert {
   // call check cert
}
// continue the process from line 616.
```

This is to avoid future endpoint missing cert check by mistake.

Comment (hunterlxt) [reply src/server/status_server/mod.rs:627]: Good point.  I will adopt

File: src/server/status_server/mod.rs [hunk 7]
```diff
@@ -604,22 +613,42 @@ where
                             }
                         }
 
-                        match (method, path.as_ref()) {
-                            (Method::GET, "/metrics") => Ok(Response::new(dump().into())),
-                            (Method::GET, "/status") => Ok(Response::default()),
-                            (Method::GET, "/debug/pprof/heap") => {
+                        let should_check_cert = match (&method, path.as_ref()) {
+                            (&Method::GET, "/metrics") => false,
```
[the remark this answers is not in the document]
Comment (gregwebs) [reply src/server/status_server/mod.rs:617]: CN verification is to protect sensitive information (user data in the DB) and write access.

I was thinking of having a route to describe the routes. Eventually convert to using OpenAPI. In this way there is an up to date description of the routes and the permissions they require.
It's certainly possible to not document permissions and let people guess.

File: src/server/status_server/mod.rs [hunk 8]
```diff
@@ -613,12 +639,15 @@ where
...
                                 Self::get_config(req, &cfg_controller).await
                             }
+                            // Check cert since the operation will modify the configuration of TiKV.
                             (Method::POST, "/config") => {
                                 Self::update_config(cfg_controller.clone(), req).await
                             }
                             (Method::GET, "/debug/pprof/profile") => {
                                 Self::dump_rsperf_to_resp(req).await
                             }
+                            // Check cert since the operation will get start key and end key. These keys could
```
[the remark this answers is not in the document]
Comment (hunterlxt) [reply src/server/status_server/mod.rs:649]: I think it's okay, it is best to put the reason of `check_cert` in the actual location

**Comment by yiwu-arbug** [comment]
updated release note.
