### PR TITLE
txn: check memory lock for max ts replica read

### LINKED ISSUE #14715: txn: autocommit point get read is not compatible with follower read
### What version of TiKV are you using?

The master branch 5ce3a6b78dbf498e4decbfcb5b0b7d1d7ea61dba

### What operating system and CPU are you using?

Not matter.

### Steps to reproduce

See https://github.com/pingcap/tidb/issues/43583 for details, when autocommit point get read is used 
with follower read, the linearizability could be broken.

### What did you expect?
The linearizability should not be broken.

### What did happened?
The linearizability could be broken.

### PR DESCRIPTION
**Pull request by cfzjywxk**
### What is changed and how it works?

Issue Number: Close #14715 

What's Changed:
Do check memory lock when replica read is used with max ts.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

Side effects

### Release note 

```release-note
Fix the issue that autocommit point get replica read may break linearizability.
```

### CODE REVIEW

File: components/txn_types/src/lock.rs [hunk 1]
```diff
@@ -429,6 +430,14 @@ impl Lock {
...
+        // linearizability. See https://github.com/pingcap/tidb/issues/43583 for details.
+        if ts == TimeStamp::max() && is_replica_read {
+            return Err(Error::from(ErrorInner::KeyIsLocked(
+                lock.into_owned().into_lock_info(raw_key),
+            )));
+        }
+
         if ts == TimeStamp::max() && raw_key == lock.primary && !lock.use_async_commit {
             // When `ts == TimeStamp::max()` (which means to get latest committed version
             // for primary key), and current key is the primary key, we ignore
```
Comment (you06) [inline components/txn_types/src/lock.rs:443]: What about move check here?

```rust
// Disable replica read for autocommit max ts read, to avoid breaking
// linearizability. See https://github.com/pingcap/tidb/issues/43583 for details.
if ts == TimeStamp::max() && raw_key == lock.primary && !lock.use_async_commit && !is_replica_read {
    // When `ts == TimeStamp::max()` (which means to get latest committed version
    // for primary key), and current key is the primary key, we ignore
    return Ok(());
}
```

**Review by you06 — APPROVED** [review]

**Review by zyguan — APPROVED** [review]

**Review by zyguan — APPROVED** [review]

**Review by tonyxuqqi — APPROVED** [review]
