### PR TITLE
server/node: allow restart with a StoreIdent when cluster not boostrappped

### LINKED ISSUE #4333: TiKV may fail to restart if it fails after writing store ident and before bootstrapping cluster
## Bug Report

**What did you do?**

Make TiKV fails after L149 @ node.rs. In a single node cluster, TiKV can not restart and always return `Err(store x is not empty)`.
https://github.com/tikv/tikv/blob/206209fbcc4c45ae50e1a66fc5df3ac39a6570f1/src/server/node.rs#L146-L159

**What did you expect to see?**

Restart successfully.

### PR DESCRIPTION
**Pull request by overvenus**
## What have you changed? (mandatory)

Allow restart TiKV with a StoreIdent when the cluster is not bootstrapped.

## What are the type of the changes? (mandatory)

- Bug fix (change which fixes an issue)

## How has this PR been tested? (mandatory)

Integration test.

## Does this PR affect documentation (docs) update? (mandatory)

No.

## Does this PR affect tidb-ansible update? (mandatory)

No.

## Refer to a related PR or issue link (optional)

Close #4333

### CODE REVIEW

File: src/server/node.rs [hunk 1]
```diff
@@ -255,58 +223,70 @@ where
...
+        &self,
+        engines: &Engines,
+        store_id: u64,
+    ) -> Result<Option<metapb::Region>> {
+        if let Some(first_region) = engines
             .kv
-            .get_msg::<metapb::Region>(keys::PREPARE_BOOTSTRAP_KEY)?;
-        if res.is_none() {
-            return Ok(());
+            .get_msg::<metapb::Region>(keys::PREPARE_BOOTSTRAP_KEY)?
```
Comment (BusyJay) [inline src/server/node.rs]: Is the type hint really necessary?

File: tests/failpoints/cases/test_bootstrap.rs [hunk 2]
```diff
@@ -0,0 +1,148 @@
...
+        .is_none());
+    assert!(pd_client.is_cluster_bootstrapped().unwrap());
+    let ident = engines
+        .kv
+        .get_msg::<raft_serverpb::StoreIdent>(keys::STORE_IDENT_KEY)
+        .unwrap()
+        .unwrap();
+    let store_id = ident.get_store_id();
+    let sim = Arc::new(RwLock::new(NodeCluster::new(Arc::clone(&pd_client))));
+    let mut cluster = Cluster::new(0, 5, sim, pd_client);
```
Comment (BusyJay) [inline tests/failpoints/cases/test_bootstrap.rs]: Why create a new cluster?

File: tests/failpoints/cases/test_bootstrap.rs [hunk 3]
```diff
@@ -0,0 +1,148 @@
...
+        snap_mgr.clone(),
+        pd_worker,
+        local_reader,
+        coprocessor_host,
+        importer,
+    );
+    node.stop();
+    fail::remove(fp);
+
+    let (_, system) = fsm::create_raft_batch_system(&cfg.raft_store);
```
Comment (BusyJay) [inline tests/failpoints/cases/test_bootstrap.rs]: Why not add a `try_start` function to cluster? So that you don't have to repeat the code here.
