### PR TITLE
server: do not rename directories when migrating raft data

### LINKED ISSUE #12269: when upgrade cluster to v6.0.0, tikv throws an error.
### What version of TiKV are you using?

5.3.1 --> 6.0.0
5.4.0 --> 6.0.0

### What operating system and CPU are you using?

dbaas 

### Steps to reproduce

staging 上从 5.3.1 升级到 6.0.0 orgs/1369847559690647294/projects/1369847559691367831/clusters/1373933076657976100
和
5.4.0 升级到 6.0.0 orgs/1369847559690857266/projects/1369847559691367830/clusters/1373933076657976102 

Options

### What did you expect?
can upgrade successfully.

### What did happened?
 tikv error：
[2022/03/25 08:25:58.681 +00:00] [FATAL] [lib.rs:468] ["failed to load_latest_options \"Invalid argument: [RocksDBOptionsParser Error] : A valid statement must have a '='. (at line 2)\""] [backtrace=" 0: tikv_util::set_panic_hook::{{closure}}\n at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/tikv_util/src/lib.rs:467:18\n 1: std::panicking::rust_panic_with_hook\n at rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/panicking.rs:702:17\n 2: std::panicking::begin_panic_handler::{{closure}}\n at rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/panicking.rs:588:13\n 3: std::sys_common::backtrace::__rust_end_short_backtrace\n at rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/sys_common/backtrace.rs:138:18\n 4: rust_begin_unwind\n at rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/panicking.rs:584:5\n 5: core::panicking::panic_fmt\n at rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/core/src/panicking.rs:143:14\n 6: engine_rocks::raw_util::new_engine_opt::{{closure}}\n at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/engine_rocks/src/raw_util.rs:122:33\n core::result::Result<T,E>::unwrap_or_else\n at rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/core/src/result.rs:1428:23\n engine_rocks::raw_util::new_engine_opt\n at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/engine_rocks/src/raw_util.rs:121:24\n 7: server::server::TiKVServer<raft_log_engine::engine::RaftLogEngine>::init_raw_engines\n at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/server/src/server.rs:1400:26\n server::server::run_tikv\n at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/server/src/server.rs:158:9\n 8: tikv_server::main\n at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/cmd/tikv-server/src/main.rs:190:5\n 9: core::ops::function::FnOnce::call_once\n at rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/core/src/ops/function.rs:227:5\n std::sys_common::backtrace::__rust_begin_short_backtrace\n at rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/sys_common/backtrace.rs:122:18\n 10: main\n 11: __libc_start_main\n 12: <unknown>\n"] [location=components/engine_rocks/src/raw_util.rs:122] [thread_name=main]

### PR DESCRIPTION
**Pull request by tabokie**
Signed-off-by: tabokie <xy.tao@outlook.com>

### What is changed and how it works?

Issue Number: Close #12269

What's Changed:

After directories are renamed, encryption key manager cannot locate encryption keys for old files.

This PR avoids renaming and use marker file to maintain migration state.

```commit-message
```

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Manual test (add detailed scripts or steps below)
  - Reproduce steps in #12269

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by BusyJay** [comment]
Why is a key associated with a path? What's the design consideration?

**Comment by tabokie** [comment]
> Why is a key associated with a path? What's the design consideration?

I believe the encryption key is periodically rotated, so we must persistently maintain keys for individual files.

File: components/tikv_util/src/config.rs [hunk 1]
```diff
@@ -1386,66 +1386,43 @@ macro_rules! numeric_enum_serializing_mod {
...
-    source_staging: PathBuf,
     target: PathBuf,
-    target_staging: PathBuf,
 }
 
 impl RaftDataStateMachine {
-    pub fn new(source: &str, target: &str) -> Self {
+    pub fn new(root: &str, source: &str, target: &str) -> Self {
+        let root = PathBuf::from(root);
+        let in_progress_marker = root.join("MIGRATE");
```
Comment (BusyJay) [inline components/tikv_util/src/config.rs:1402]: How about giving it a more specific name like "MIGRATE-TO-RAFT-ENGINE"?

File: components/tikv_util/src/config.rs [hunk 2]
```diff
@@ -1456,68 +1433,88 @@ impl RaftDataStateMachine {
...
     }
 
     /// Exits the `Migrating` state and enters the `Completed` state.
     pub fn after_dump_data(&mut self) {
+        assert!(Self::data_exists(&self.source));
         assert!(Self::data_exists(&self.target));
-        assert!(!Self::data_exists(&self.source));
-        assert!(!Self::data_exists(&self.target_staging));
-        Self::remove_dir_safe(&self.source_staging);
+        Self::must_remove(&self.source); // Enters the `Completed` state.
```
Comment (glorv) [inline components/tikv_util/src/config.rs:1473]: I think we may need an extra state here by write a 'complete' state before remove source directory. As remove a non-empty directory is not a atomic operation, if some of the files in source directory are removed but some are not, reinit from this state may cause panic because the source state is corrupted.

Comment (tabokie) [reply components/tikv_util/src/config.rs:1473]: The remove is atomic by renaming to "xx.TRASH" first.

**Review by hunterlxt — APPROVED** [review]
LGTM

**Review by glorv — APPROVED** [review]
LGTM

File: components/tikv_util/src/config.rs [hunk 3]
```diff
@@ -1456,68 +1433,88 @@ impl RaftDataStateMachine {
...
+            let real_source = PathBuf::from(fs::read_to_string(&self.in_progress_marker).unwrap());
+            if real_source == self.target {
+                Self::must_remove(&self.source);
+                return false;
+            } else {
+                Self::must_remove(&self.target);
+            }
+        } else {
+            // Init -> Migrating.
+            fs::write(&self.in_progress_marker, self.source.to_str().unwrap()).unwrap();
```
Comment (BusyJay) [inline components/tikv_util/src/config.rs:1463]: What if it crashes here and leave the content of the file truncated?

Comment (tabokie) [reply components/tikv_util/src/config.rs:1463]: Ok, I'll add a double slash at the end as an EOF marker.

Comment (BusyJay) [reply components/tikv_util/src/config.rs:1463]: Then you also need to sync the file.

File: components/tikv_util/src/config.rs [hunk 4]
```diff
@@ -1456,68 +1433,111 @@ impl RaftDataStateMachine {
...
+            // Recover from Completed state.
+            if self.in_progress_marker.exists() {
+                Self::must_remove(&self.in_progress_marker);
+            }
+            return false;
+        } else if self.in_progress_marker.exists() {
+            if let Some(real_source) = self.read_marker() {
+                // Recover from Migrating state.
+                if real_source == self.target {
+                    Self::must_remove(&self.source);
```
Comment (BusyJay) [inline components/tikv_util/src/config.rs:1456]: `target` may not exist.

File: components/tikv_util/src/config.rs [hunk 5]
```diff
@@ -1456,68 +1433,111 @@ impl RaftDataStateMachine {
...
+                    return false;
+                } else {
```
Comment (BusyJay) [inline components/tikv_util/src/config.rs:1458]: Perhaps should also check whether it equals `source`.

File: components/tikv_util/src/config.rs [hunk 6]
```diff
@@ -1456,68 +1433,115 @@ impl RaftDataStateMachine {
...
+            // Recover from Completed state.
+            if self.in_progress_marker.exists() {
+                Self::must_remove(&self.in_progress_marker);
+            }
+            return false;
+        } else if self.in_progress_marker.exists() {
+            if let Some(real_source) = self.read_marker() {
+                // Recover from Migrating state.
+                if real_source == self.target {
+                    assert!(Self::data_exists(&self.target));
```
Comment (BusyJay) [inline components/tikv_util/src/config.rs:1456]: I don't get it. Isn't it a valid case that migrate from target to source but panic before deleting the migrating success mark? I think it's just the same case of L1448 but in the reverse way.

File: components/tikv_util/src/config.rs [hunk 7]
```diff
@@ -1456,68 +1433,115 @@ impl RaftDataStateMachine {
...
+    }
+
+    fn write_marker(&self) {
+        use std::io::Write;
+        let mut f = fs::File::create(&self.in_progress_marker).unwrap();
+        f.write_all(self.source.to_str().unwrap().as_bytes())
+            .unwrap();
+        f.sync_all().unwrap();
+        f.write_all(b"//").unwrap();
+        f.sync_all().unwrap();
```
Comment (BusyJay) [inline components/tikv_util/src/config.rs:1500]: I don't see the point of writing and syncing twice.

File: components/tikv_util/src/config.rs [hunk 8]
```diff
@@ -1456,68 +1433,115 @@ impl RaftDataStateMachine {
...
+        Self::must_remove(&self.in_progress_marker);
+    }
+
+    fn write_marker(&self) {
+        use std::io::Write;
+        let mut f = fs::File::create(&self.in_progress_marker).unwrap();
+        f.write_all(self.source.to_str().unwrap().as_bytes())
+            .unwrap();
+        f.sync_all().unwrap();
+        f.write_all(b"//").unwrap();
```
Comment (BusyJay) [inline components/tikv_util/src/config.rs:1499]: Perhaps `##` is a safer mark as `//` is possible to appear in normal path.

Comment (tabokie) [reply components/tikv_util/src/config.rs:1499]: It appears "#" is allowed in file name, whilst "/" is not, so it's unlikely to have two consecutive slashes in a path.

File: components/tikv_util/src/config.rs (hunk 6 above)
Comment (tabokie) [reply components/tikv_util/src/config.rs:1456]: In that case, target will not be deleted until marker is deleted first.

File: components/tikv_util/src/config.rs (hunk 7 above)
Comment (tabokie) [reply components/tikv_util/src/config.rs:1500]: I'm not sure buffered page will land on disk in sequential order. Writing twice makes sure the path won't be corrupted as long as EOF is written down.

File: components/tikv_util/src/config.rs (hunk 6 above)
Comment (tabokie) [reply components/tikv_util/src/config.rs:1456]: You are right, I'll check why unit test didn't cover this case.

**Review by BusyJay — APPROVED** [review]
