### PR TITLE
log backup: reduce lock lifetime during flush log file

### LINKED ISSUE #19238: Log Backup may get stuck due to async lock held across `.await`
## Bug Report

Under certain configurations, Log Backup may get permanently stuck.

Once this happens:
- Log backup no longer makes progress, no related backup log output
- Pause/Stop task commands do not work

This issue is strongly correlated with holding an async lock across .await, which may stall the Tokio runtime when thread resources are constrained.

### What version of TiKV are you using?

v8.5.3

### What operating system and CPU are you using?

N/A
### Steps to reproduce

It's not easy to reproduce, but a hypothesis version should be
1.	Use a small Tokio runtime thread pool
	•	e.g. reduce `[log-backup] num.threads` to a small number (1–2)
2. Configure log backup with a short flush interval
3. Start normal write workload and wait

### What did you expect?
Log backup works normally.
### What did happened?
Log backup flush stops making progress without reporting any error.

When this happens:
1. Log backup no longer advances
2. Querying /async-tasks shows that async tasks are blocked on S3-related operations
                - These S3 operations are configured with Tokio timeouts, but:
	                  - The timeouts do not trigger
3. Pause / control operations do not work

### PR DESCRIPTION
**Pull request by 3pointer**
### What is changed and how it works?

Issue Number: Close https://github.com/tikv/tikv/issues/19238

What's Changed:

```commit-message
log backup: reduce lock lifetime during flush log file
```

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [ ] Need to cherry-pick to the release branch

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note

```release-note
Fix potential dangerous lock behavior that could cause log backup to get stuck
```

### CODE REVIEW

File: components/backup-stream/src/router.rs [hunk 1]
```diff
@@ -723,34 +723,29 @@ impl RouterInner {
...
-                    }
-                    return None;
-                }
-                // if succeed in flushing, update flush_time. Or retry do_flush immediately.
-                task_handler.update_flush_time();
-                result.ok().flatten()
+        let task_handler = match self.get_task_handler(cx.task_name) {
+            Ok(h) => h,
+            Err(_) => return None,
+        };
```
Comment (Leavrth) [inline components/backup-stream/src/router.rs:729]:
```suggestion
        let task_handler = match self.get_task_handler(cx.task_name).ok()?;
```

**Review by Leavrth — APPROVED** [review]

**Review by YuJuncen — APPROVED** [review]
