### PR TITLE
In-Memory-Engine: move from range-base to region-base

### LINKED ISSUE #17147: In-memory Engine: the tag in `CacheRange` may be inaccurate
## Bug Report

After region split, in-memory engine changes range respectively, but it does not update the tag, because it does not know the region id. As the result, the tag might be misleading during debugging.

See https://github.com/tikv/tikv/pull/17137#discussion_r1637634602

### What version of TiKV are you using?

Nightly, 2024-06-13.

### What did you expect?

The tag should match the actually region ID.

### PR DESCRIPTION
**Pull request by glorv**
### What is changed and how it works?

Issue Number: ref #16141  close #17147

What's Changed:

```commit-message
Move range cache engine's range manager for range-base to region-base
```

This PR refactor the RangeCacheEngine's RangeManager for range-base to region-base.

State Management. The life time of each cached region can be one of following state:
- Pending. Region is triggered to load but not started. 
- Loading. Region is performing loading kvs from rocksdb. under this state, raft apply worker will also write new kvs into skiplist directly.
- Active. Region is cached, ready for read.
- LoadingCanceled. Region is evicted while it's still handling batch loading. 
- PendingEvict. Region should be evicted, but evict is block by on-going apply writ or gc or active snapshot.
- Evicting. Evicted region is still handling delete KVs from skiplist, after the delete finished, this region will be removed from RangeManager.

Region Metadata Management
Each region's metadata is maintained in a single struct called RegionMeta. It manages the region's current epoch version, active snapshot list, gc safe_point, in_gc flag and state.

Batch-Loading behavior changes
This PR simplifies Batch-loading phase by removing the cached entries in memory and directly write new entires to the skiplist. Note that, due to this change, if a batch-loading task is canceled before started, it still need to use region eviction because the raft apply worker may already write new KVs into the skiplist.

 Region Epoch Management
As the new design is region-based, it need to keep up it's local state with raftstore. We use a ApplyObserve to observe raft event and update region meta on some specific events. Note that as region's conf version change does not impact the data layout, so we only track region's epoch version changes but ignore conf-version change.
- LeaderResign. Evict the region as we only cache data for region leader.
- SST Ingestion, DeleteRange. Evict the region because the in-memory kvs are not keep up with rocksdb anymore.
- PrepareMerge, CommitMerge. Evict the region for simplicity because we only merge region when it is not hot.
- Split/BatchSplit. We replace current with new split regions. The new regions should inherit the old region's  state, gc safe_point and in_gc flag. If the old region's snapshot_list is not empty, it is put into the `historical_regions` to track these snapshots.

In addition, as we use a snapshot to handle some time-cost event, e.g. batch loading, it is possible that after handling finished, the region's epoch may already changed, so after some operation, we will check to the region epoch version, if it changes, we will use scan to handle all new regions that overlaps with the original region:
- Pending. We apply worker handle pending region in `prepare_for_region`, if the pending region's version changes, if pending region's range contains the new region's, we replace the pending region with the new region; else, we just discard the pending region.
- Batch Loading. If region epoch version changes, it scans all regions fall in this range and update their state to either "active" or "pending_evict" based on their current state.

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [ ] Need to cherry-pick to the release branch

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note

```release-note
None
```

### CODE REVIEW

File: components/engine_traits/src/range_cache_engine.rs [hunk 1]
```diff
@@ -7,14 +7,30 @@ use std::{
...
+
+pub enum RegionEvent {
+    Split {
+        source: Region,
+        new_regions: Vec<Region>,
+    },
+    Eviction {
+        region: Region,
+    },
+    // range eviction triggered by delte_range
```
Comment (zhangjinpeng87) [inline components/engine_traits/src/range_cache_engine.rs:29]: delete_range

File: components/keys/src/lib.rs [hunk 2]
```diff
@@ -228,16 +228,16 @@ pub fn origin_key(key: &[u8]) -> &[u8] {
 /// Get the `start_key` of current region in encoded form.
 pub fn enc_start_key(region: &Region) -> Vec<u8> {
     // only initialized region's start_key can be encoded, otherwise there must be
-    // bugs somewhere.
-    assert!(!region.get_peers().is_empty());
+    // bugs somewhere. Here we only the region id for test convenience.
```
Comment (zhangjinpeng87) [inline components/keys/src/lib.rs:231]: Please remember to revert it for the final formal PR.

File: components/range_cache_memory_engine/src/range_manager.rs [hunk 3]
```diff
@@ -1,27 +1,51 @@
...
 // read_ts -> ref_count
 #[derive(Default, Debug)]
 pub(crate) struct SnapshotList(pub(crate) BTreeMap<u64, u64>);
 
 impl SnapshotList {
     pub(crate) fn new_snapshot(&mut self, read_ts: u64) {
         // snapshot with this ts may be granted before
-        let count = self.0.get(&read_ts).unwrap_or(&0) + 1;
-        self.0.insert(read_ts, count);
+        *self.0.entry(read_ts).or_default() += 1;
```
Comment (zhangjinpeng87) [inline components/range_cache_memory_engine/src/range_manager.rs:48]: Is it possible multiple thread access function simultaneously?

File: components/range_cache_memory_engine/src/range_manager.rs [hunk 4]
```diff
@@ -44,22 +68,56 @@ impl SnapshotList {
...
+    }
+
+    // update region info due to epoch changes.
+    pub(crate) fn update_region(&mut self, region: &Region) -> bool {
+        assert!(
+            self.region.id == region.id
+                && self.region.get_region_epoch().version < region.get_region_epoch().version
+        );
+        let new_range = CacheRange::from_region(region);
+        if !self.range.contains_range(&new_range) {
```
Comment (zhangjinpeng87) [inline components/range_cache_memory_engine/src/range_manager.rs:114]: So the `update_region` is just for split or epoch update?

File: components/range_cache_memory_engine/src/range_manager.rs [hunk 5]
```diff
@@ -71,124 +129,185 @@ impl RangeMeta {
...
-        &self.range_snapshot_list
+    pub fn get_state(&self) -> RegionState {
+        self.state
     }
-}
 
-#[derive(Default)]
-struct IdAllocator(u64);
+    pub(crate) fn set_state(&mut self, new_state: RegionState) {
+        self.state = new_state;
```
Comment (zhangjinpeng87) [inline components/range_cache_memory_engine/src/range_manager.rs:141]: Do we need to verify the new_state must obey some rules?

File: components/range_cache_memory_engine/src/range_manager.rs [hunk 6]
```diff
@@ -71,124 +129,185 @@ impl RangeMeta {
...
+    pub(crate) fn set_in_gc(&mut self, in_gc: bool) {
+        assert!(self.in_gc != in_gc);
+        self.in_gc = in_gc;
+    }
+
+    pub(crate) fn is_in_gc(&self) -> bool {
+        self.in_gc
+    }
+
+    pub(crate) fn dervie_from(region: Region, source_meta: &Self) -> Self {
```
Comment (zhangjinpeng87) [inline components/range_cache_memory_engine/src/range_manager.rs:164]: Please add comments for this function, like when this function will be called (only when split?).

File: components/range_cache_memory_engine/src/range_manager.rs [hunk 7]
```diff
@@ -71,124 +129,185 @@ impl RangeMeta {
...
+    // which means no further write of it is allowed, and a DeleteRegion task of the range will be
+    // scheduled to cleanup the KVs of this region. However, it is possible that the apply thread
+    // is writting data for this range. Therefore, we have to delay the DeleteRange task until
+    // the range leaves the `ranges_being_written`.
     //
     // The key in this map is the id of the write batch, and the value is a collection
     // the ranges of this batch. So, when the write batch is consumed by the in-memory engine,
     // all ranges of it are cleared from `ranges_being_written`.
-    ranges_being_written: HashMap<u64, Vec<CacheRange>>,
+    regions_being_written: HashMap<u64, Vec<(u64, CacheRange)>>,
```
Comment (zhangjinpeng87) [inline components/range_cache_memory_engine/src/range_manager.rs:240]: What is the `u64`field in the Vec?

File: components/range_cache_memory_engine/src/range_manager.rs [hunk 8]
```diff
@@ -71,124 +129,185 @@ impl RangeMeta {
...
+    }
+
+    pub fn iter_overlapped_regions_mut(
+        &mut self,
+        range: &CacheRange,
+        mut f: impl FnMut(&mut RangeMeta),
+    ) {
+        for (_key, id) in self
+            .regions_by_range
+            .range::<[u8], (Bound<&[u8]>, Bound<&[u8]>)>((Excluded(&range.start), Unbounded))
```
Comment (zhangjinpeng87) [inline components/range_cache_memory_engine/src/range_manager.rs:299]: Why L278 used `range.start.as_slice()` and here use `&range.start`?

File: components/range_cache_memory_engine/src/range_manager.rs [hunk 9]
```diff
@@ -199,127 +318,237 @@ impl RangeManager {
...
-        self.pending_ranges_loading_data
-            .iter()
-            .any(|(r, ..)| r.contains_range(range))
+    pub fn contains_region(&self, region_id: u64) -> bool {
+        self.regions.contains_key(&region_id)
     }
 
-    fn overlap_with_range(&self, range: &CacheRange) -> bool {
-        self.ranges.keys().any(|r| r.overlaps(range))
+    pub fn check_region_status(&mut self, region: &Region) -> Option<RegionState> {
```
Comment (zhangjinpeng87) [inline components/range_cache_memory_engine/src/range_manager.rs:339]: s/check_region_state

File: components/range_cache_memory_engine/src/range_manager.rs [hunk 10]
```diff
@@ -199,127 +318,237 @@ impl RangeManager {
...
+        use RegionState::*;
+        let Some(cached_meta) = self.regions.get_mut(&region.id) else {
+            return None;
+        };
+        if cached_meta.state == Pending
+            && cached_meta.region.get_region_epoch().version != region.get_region_epoch().version
```
Comment (zhangjinpeng87) [inline components/range_cache_memory_engine/src/range_manager.rs:345]: Is it possible region.epoch < cached.region.epoch after some merge and split operations?

File: components/range_cache_memory_engine/src/range_manager.rs [hunk 11]
```diff
@@ -199,127 +318,237 @@ impl RangeManager {
...
+        false
     }
 
-    fn overlap_with_pending_range(&self, range: &CacheRange) -> bool {
-        self.pending_ranges.iter().any(|r| r.overlaps(range))
-            || self
-                .pending_ranges_loading_data
-                .iter()
-                .any(|(r, ..)| r.overlaps(range))
+    /// `check_overlap_with_region` check of there are regions overlap with
```
Comment (zhangjinpeng87) [inline components/range_cache_memory_engine/src/range_manager.rs:373]: s/of/if

File: components/range_cache_memory_engine/src/range_manager.rs [hunk 12]
```diff
@@ -199,127 +318,237 @@ impl RangeManager {
...
             return Err(FailedReason::NotCached);
         };
-        let meta = self.ranges.get_mut(&range_key).unwrap();
+
+        if meta.state != RegionState::Active {
+            return Err(FailedReason::NotCached);
+        }
+
+        if meta.region.get_region_epoch().version != region_epoch {
+            return Err(FailedReason::EpochNotMatch);
```
Comment (zhangjinpeng87) [inline components/range_cache_memory_engine/src/range_manager.rs:417]: What will happen if:
1) region_epoch is older than current meta.region.epoch?
2) region_epoch is newer than current meta.region.epoch? Does it will trigger the update region operation?

File: components/range_cache_memory_engine/src/range_manager.rs [hunk 13]
```diff
@@ -199,127 +318,237 @@ impl RangeManager {
...
+        }
 
         if read_ts <= meta.safe_point {
```
Comment (zhangjinpeng87) [inline components/range_cache_memory_engine/src/range_manager.rs:420]: I think it still can serve the read request if read_ts == safe_point.

File: components/range_cache_memory_engine/src/range_manager.rs [hunk 14]
```diff
@@ -199,127 +318,237 @@ impl RangeManager {
...
-    ) -> Vec<CacheRange> {
-        if let Some(range_key) = self
-            .historical_ranges
-            .iter()
-            .find(|&(range, meta)| {
-                range.contains_range(&snapshot_meta.range) && meta.id == snapshot_meta.range_id
-            })
-            .map(|(r, _)| r.clone())
+    ) -> Vec<Region> {
+        // fast path: in most case, region is change, so we change region first.
```
Comment (zhangjinpeng87) [inline components/range_cache_memory_engine/src/range_manager.rs:437]: s/region is changed/region is not changed

Comment (zhangjinpeng87) [inline components/range_cache_memory_engine/src/range_manager.rs:437]:
```suggestion
        // fast path: in most case, region is not changed, so we change region first.
```

File: components/range_cache_memory_engine/src/range_manager.rs [hunk 15]
```diff
@@ -199,127 +318,237 @@ impl RangeManager {
...
-            .ranges
-            .iter()
-            .find(|&(range, meta)| {
-                range.contains_range(&snapshot_meta.range) && meta.id == snapshot_meta.range_id
-            })
-            .map(|(r, _)| r.clone())
-            .unwrap();
-        let meta = self.ranges.get_mut(&range_key).unwrap();
-        meta.range_snapshot_list
+        // slow path: region not found or epoch version changes, must fell in the
```
Comment (zhangjinpeng87) [inline components/range_cache_memory_engine/src/range_manager.rs:452]: Are you saying every time change the epoch of a region, must move the old one to the historical_regions?

File: components/range_cache_memory_engine/src/range_manager.rs (hunk 3 above)
Comment (glorv) [reply components/range_cache_memory_engine/src/range_manager.rs:48]: Currently no as it requires `&mut self` and it doesn't seem to be the bottleneck because this lock is very short. Maybe we can replace it with `DashMap` in the future if it becomes the bottleneck.

File: components/range_cache_memory_engine/src/range_manager.rs (hunk 4 above)
Comment (glorv) [reply components/range_cache_memory_engine/src/range_manager.rs:114]: Only used for outdated pending regions that missing some newer epoch changes events. For region split, we use remove & add to replace the old region with new split regions.

File: components/range_cache_memory_engine/src/range_manager.rs (hunk 12 above)
Comment (glorv) [reply components/range_cache_memory_engine/src/range_manager.rs:417]: Here, cached region epoch can only be higher than raft's region epoch if not equal. Because cached region's epoch  is updated when write batch is apply, but raft's local reader's epoch is updated after ApplyRes returned, so during this small interval, cached epoch can be higher than raft's. So during this interval, foreground request will fallback to read from rocksdb due to epoch not match.

File: components/range_cache_memory_engine/src/range_manager.rs (hunk 13 above)
Comment (glorv) [reply components/range_cache_memory_engine/src/range_manager.rs:420]: https://github.com/tikv/tikv/blob/26c20c7923fb868cd3976fb8d36d738d4fff4abb/components/range_cache_memory_engine/src/background.rs#L1374-L1409

From the current implementation, KVs' commit_ts == safe_point will also be removed

File: components/range_cache_memory_engine/src/range_manager.rs (hunk 15 above)
Comment (glorv) [reply components/range_cache_memory_engine/src/range_manager.rs:452]: only when region epoch version change and there are active snapshots. Actually, this only happens for region split because we current just evict the region for region merge.

File: components/hybrid_engine/src/snapshot.rs [hunk 16]
```diff
@@ -165,15 +168,17 @@ mod tests {
             assert!(!iter.seek_to_first().unwrap());
         }
         let mut write_batch = hybrid_engine.write_batch();
-        write_batch.prepare_for_range(range.clone());
+        write_batch.prepare_for_region(&region);
         write_batch
             .cache_write_batch
             .set_range_cache_status(RangeCacheStatus::Cached);
-        write_batch.put(b"hello", b"world").unwrap();
+        write_batch.put(b"zhello", b"world").unwrap();
```
Comment (overvenus) [inline components/hybrid_engine/src/snapshot.rs:175]: Out of curiosity, why prefix "z"?

File: components/range_cache_memory_engine/src/keys.rs [hunk 17]
```diff
@@ -154,13 +155,24 @@ impl TryFrom<u8> for ValueType {
...
     pub v_type: ValueType,
     pub sequence: u64,
 }
 
+impl<'a> fmt::Debug for InternalKey<'a> {
+    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
+        write!(
+            f,
+            "(key: {:?}, type: {:?}, seq: {})",
+            self.user_key, self.v_type, self.sequence
```
Comment (overvenus) [inline components/range_cache_memory_engine/src/keys.rs:171]: Need redact.

File: components/range_cache_memory_engine/src/write_batch.rs [hunk 18]
```diff
@@ -1,5 +1,5 @@
+use core::slice::SlicePattern;
```
Comment (overvenus) [inline components/range_cache_memory_engine/src/write_batch.rs:1]: Please add license header.

File: components/engine_traits/src/engine.rs [hunk 19]
```diff
@@ -86,6 +86,10 @@ pub trait KvEngine:
 #[derive(Debug, Clone)]
 pub struct SnapshotContext {
     pub range: Option<CacheRange>,
```
[the remark this answers is not in the document]
Comment (glorv) [reply components/engine_traits/src/engine.rs:88]: No. Range is used to limit the range we can visit in the skiplist.

File: components/engine_traits/src/engine.rs [hunk 20]
```diff
@@ -86,6 +86,10 @@ pub trait KvEngine:
...
+    pub region_id: u64,
+    // the version of region epoch.
+    pub epoch_version: u64,
```
[the remark this answers is not in the document]
Comment (glorv) [reply components/engine_traits/src/engine.rs:91]: But use `metapb::RegionEpoch` is not that convenient here, because we can't check the equality of `RegionEpoch ` since conf_version can be different. Use `RegionEpoch` but only check its `version` is somewhat weird to me.  I think the naming is enough to explain this field's meaning.

File: components/engine_traits/src/range_cache_engine.rs [hunk 21]
```diff
@@ -78,25 +99,15 @@ pub trait RangeCacheEngineExt {
...
 pub trait RangeHintService: Send + Sync {}
 
-#[derive(Clone, Eq)]
+#[derive(Clone, Eq, PartialEq, PartialOrd, Ord)]
 pub struct CacheRange {
     pub start: Vec<u8>,
     pub end: Vec<u8>,
-    // Note: tag may not be accurate due decouple of region split and range split. It's only for
-    // debug purpose.
-    pub tag: String,
```
[the remark this answers is not in the document]
Comment (glorv) [reply components/engine_traits/src/range_cache_engine.rs:87]: `tag` is no more useful as now we have `Region` in the context. The original `tag` is used to store the related `region_id` which is not needed now.

[the remark this answers is not in the document]
Comment (glorv) [reply components/engine_traits/src/range_cache_engine.rs:87]: I'm thinking about using `CacheRegion` to replace the current `metapb::Region`:
```
struct CacheRegion {
  region_id: u64,
  // start and end is the data range.
  start: Vec<u8>,
  end: Vec<u8>,
  epoch_version: u64,
}
```

File: components/hybrid_engine/src/snapshot.rs (hunk 16 above)
Comment (glorv) [reply components/hybrid_engine/src/snapshot.rs:175]: "z" is actually the `DATA_KEY_PREFIX`. Because after this change, the data range is built from region. Thus a region with range ["k00", "k10") actually covers the data key range ["zk00", "zk10")

File: components/range_cache_memory_engine/src/range_manager.rs (hunk 5 above)
Comment (glorv) [reply components/range_cache_memory_engine/src/range_manager.rs:165]: Done

File: components/range_cache_memory_engine/src/range_manager.rs [hunk 22]
```diff
@@ -336,189 +577,247 @@ impl RangeManager {
...
-            } else if r.overlaps(evict_range) {
-                overlapped_ranges.push(r.clone());
             }
         }
 
-        if overlapped_ranges.is_empty() {
-            info!(
-                "evict a range that is not cached";
-                "range" => ?evict_range,
-            );
```
Comment (overvenus) [inline components/range_cache_memory_engine/src/range_manager.rs:380]: Could you add a log like this for recording failed eviction, such as epoch mismatch and not cached?

File: components/engine_traits/src/range_cache_engine.rs (hunk 21 above)
[the remark this answers is not in the document]
Comment (overvenus) [reply components/engine_traits/src/range_cache_engine.rs:87]: I'm okay with this idea. Looks like it can save some repeated code as well.

File: components/range_cache_memory_engine/src/range_manager.rs (hunk 6 above)
Comment (overvenus) [reply components/range_cache_memory_engine/src/range_manager.rs:191]:
```suggestion
    pub(crate) fn derive_from(region: Region, source_meta: &Self) -> Self {
```

File: components/range_cache_memory_engine/src/range_manager.rs [hunk 23]
```diff
@@ -71,124 +137,204 @@ impl RangeMeta {
...
+    // data_end_key --> region_id
+    regions_by_range: BTreeMap<Vec<u8>, u64>,
+    // region_id --> region_meta
+    regions: HashMap<u64, RangeMeta>,
+    // we use this flag to ensure there is only 1 running gc task.
+    is_gc_task_running: AtomicBool,
+    // Outdated regions that are split but still hold some on going snapshots.
+    // These on going snapshot should block regions fell in this range from gc or eviction.
+    // It's possible that multi region with the same end key are in `historical_regions`,
+    // so we add epoch verion into the key to ensure the uniqueness.
```
Comment (overvenus) [inline components/range_cache_memory_engine/src/range_manager.rs:252]:
```suggestion
    // so we add epoch version into the key to ensure the uniqueness.
```

File: components/range_cache_memory_engine/src/range_manager.rs [hunk 24]
```diff
@@ -71,124 +137,204 @@ impl RangeMeta {
...
+// TODO: it's currently impossible to implement a `Borrow`ed instance
+// for `KeyAndVersion` from a borrowed key without clone.
+#[derive(PartialEq, Eq, PartialOrd, Ord, Clone)]
+struct KeyAndVersion(Vec<u8>, u64);
+
+// RegionManger manges the regions for RangeCacheMemoryEngine. Every new region
+// (whether created by new_region/load_region or by split)'s range is unique and
+// is not overlap with any other regions.
+//
+// Eech region is first added with `pending` state. Because `pending` can be
```
Comment (overvenus) [inline components/range_cache_memory_engine/src/range_manager.rs:219]:
```suggestion
// Each region is first added with `pending` state. Because `pending` can be
```

File: components/range_cache_memory_engine/src/range_manager.rs [hunk 25]
```diff
@@ -71,124 +137,204 @@ impl RangeMeta {
...
+// new version, else we just drop the outdated region.
+//
+// In RegionCacheEngine, we only keep region's epoch version updated with
+// raftstore, but not the conf version for simplicity because conf version
+// change doesn't affect the correctness of data. In order to always keep the
+// region epoch version updated, we handle region epoch we use a ApplyObserver
+// to watch following event:
+// - PrepareMerge/CommitMerge. We evict target region currently for simplicity.
+// - Leader Resign. evict the region.
+// - SST Ingestion. evict the regoin.
```
Comment (overvenus) [inline components/range_cache_memory_engine/src/range_manager.rs:234]:
```suggestion
// - SST Ingestion. evict the region.
```

File: components/range_cache_memory_engine/src/range_manager.rs [hunk 26]
```diff
@@ -71,124 +137,204 @@ impl RangeMeta {
...
+// - Split/BatchSplit. For split event, we just replace the source region with
+//   the split new reigons. The new regions should inherit the state of the
```
Comment (overvenus) [inline components/range_cache_memory_engine/src/range_manager.rs:236]:
```suggestion
//   the split new regions. The new regions should inherit the state of the
```

File: components/range_cache_memory_engine/src/range_manager.rs [hunk 27]
```diff
@@ -71,124 +137,204 @@ impl RangeMeta {
...
     // It is used to avoid the conccurency issue between delete range and write to memory: after
-    // the range is evicted or failed to load, the range is recorded in `ranges_being_deleted`
-    // which means no further write of it is allowed, and a DeleteRange task of the range will be
-    // scheduled to cleanup the dirty data. However, it is possible that the apply thread is
-    // writting data for this range. Therefore, we have to delay the DeleteRange task until the
-    // range leaves the `ranges_being_written`.
+    // the range is evicted or failed to load, the range is marked as `PendingEvict`
+    // which means no further write of it is allowed, and a DeleteRegion task of the range will be
+    // scheduled to cleanup the KVs of this region. However, it is possible that the apply thread
+    // is writting data for this range. Therefore, we have to delay the DeleteRange task until
```
Comment (overvenus) [inline components/range_cache_memory_engine/src/range_manager.rs:261]:
```suggestion
    // is writing data for this range. Therefore, we have to delay the DeleteRange task until
```

File: components/range_cache_memory_engine/src/range_manager.rs [hunk 28]
```diff
@@ -199,127 +345,222 @@ impl RangeManager {
...
+    fn check_overlap_with_region(&mut self, region: &Region) -> Option<RegionState> {
+        let region_range = CacheRange::from_region(region);
+        let mut removed_region = vec![];
+        let mut overlapped_region_state = None;
+        self.iter_overlapped_regions(&region_range, |region_meta| {
+            if region_meta.state != RegionState::Pending
+                || region_meta.region.get_region_epoch().version
+                    >= region.get_region_epoch().version
+            {
+                tikv_util::warn!("load region overlaps with existing region"; "region" => ?region, "exist_meta" => ?region_meta);
```
Comment (overvenus) [inline components/range_cache_memory_engine/src/range_manager.rs:413]:
```suggestion
                tikv_util::warn!("load region overlaps with existing region";
                    "region" => ?region,
                    "exist_meta" => ?region_meta);
```

File: components/range_cache_memory_engine/src/range_manager.rs [hunk 29]
```diff
@@ -336,189 +577,247 @@ impl RangeManager {
...
-            if r.contains_range(evict_range) {
-                if self.evict_within_range(evict_range, &r.clone(), evict_reason) {
-                    return vec![evict_range.clone()];
-                } else {
-                    return vec![];
-                }
-            } else if r.overlaps(evict_range) {
-                overlapped_ranges.push(r.clone());
             }
         }
```
Comment (overvenus) [inline components/range_cache_memory_engine/src/range_manager.rs:601]: Could you add a log for recording failed eviction? Eg, epoch mistmatch or region not found.

File: components/range_cache_memory_engine/src/range_manager.rs [hunk 30]
```diff
@@ -336,189 +577,247 @@ impl RangeManager {
...
+            if evict_range.start >= meta.range.end {
+                return false;
+            }
+            evict_ids.push(meta.region.id);
+            true
+        });
+        for rid in evict_ids {
+            if let Some(region) = self.do_evict_region(rid, evict_region, evict_reason) {
+                deleteable_regions.push(region);
+            }
```
Comment (overvenus) [inline components/range_cache_memory_engine/src/range_manager.rs:615]: Is there any ABA problem? An outdated region may cover newly loaded regions.

File: components/range_cache_memory_engine/src/range_manager.rs [hunk 31]
```diff
@@ -336,189 +577,247 @@ impl RangeManager {
...
-            assert!(!ranges.unwrap().is_empty());
+            assert!(!regions.unwrap().is_empty());
         }
     }
 
-    pub fn on_gc_finished(&mut self, range: BTreeSet<CacheRange>) {
-        assert_eq!(range, std::mem::take(&mut self.ranges_in_gc));
+    pub fn add_pinned_range(&mut self, _cache_range: CacheRange) {
+        // TODO: handle pinned range later
     }
```
Comment (overvenus) [inline components/range_cache_memory_engine/src/range_manager.rs]: Deadcode?

File: components/range_cache_memory_engine/src/range_manager.rs [hunk 32]
```diff
@@ -336,189 +577,247 @@ impl RangeManager {
...
+            assert!(
+                region_meta.region.get_region_epoch().version
+                    < source_region.get_region_epoch().version
+            );
+            new_regions.retain(|r| {
+                r.start_key <= source_region.start_key
+                    && (source_region.end_key.is_empty()
+                        || (source_region.end_key >= r.end_key && !r.end_key.as_slice().is_empty()))
+            });
+            info!("[IME] handle split region met pending region epoch stale"; "cached" => ?region_meta, "split_source" => ?source_region, "cache_new_regions" => ?new_regions);
```
Comment (overvenus) [inline components/range_cache_memory_engine/src/range_manager.rs:785]: Please keep line width within 100 chars (80 even better).

File: components/range_cache_memory_engine/src/range_manager.rs (hunk 30 above)
Comment (glorv) [reply components/range_cache_memory_engine/src/range_manager.rs:615]: This is only possible when the region is evicted due to statistics. Region is merge/split before the background work start the eviction. But in this case, I think we still want to evict the new region(s) as we expect that range should be evicted due to our statistics data.

File: components/range_cache_memory_engine/src/range_manager.rs (hunk 32 above)
Comment (glorv) [reply components/range_cache_memory_engine/src/range_manager.rs:785]: Is it possible the let cargo format due this for us automatically?🤔

File: components/engine_traits/src/range_cache_engine.rs (hunk 21 above)
[the remark this answers is not in the document]
Comment (glorv) [reply components/engine_traits/src/range_cache_engine.rs:87]: Ok. I will try it after this PR is merged.

File: components/range_cache_memory_engine/src/range_manager.rs (hunk 22 above)
Comment (glorv) [reply components/range_cache_memory_engine/src/range_manager.rs:380]: Done.

File: components/range_cache_memory_engine/src/range_manager.rs [hunk 33]
```diff
@@ -71,124 +137,204 @@ impl RangeMeta {
...
+        };
+        valid_new_states.contains(&new_state)
+    }
 
-impl IdAllocator {
-    fn allocate_id(&mut self) -> u64 {
-        self.0 += 1;
-        self.0
+    pub(crate) fn set_state(&mut self, new_state: RegionState) {
+        assert!(self.validate_update_region_state(new_state));
```
[the remark this answers is not in the document]
Comment (glorv) [reply components/range_cache_memory_engine/src/range_manager.rs:165]: Done.

File: components/range_cache_memory_engine/src/range_manager.rs (hunk 32 above)
Comment (overvenus) [reply components/range_cache_memory_engine/src/range_manager.rs]: rustfmt does not work well for complex macros.

File: components/engine_traits/src/range_cache_engine.rs [hunk 34]
```diff
@@ -41,6 +65,8 @@ pub trait RangeCacheEngine:
     // provide atomic write
     fn snapshot(
         &self,
+        region_id: u64,
+        region_epoch: u64,
```
Comment (SpadeA-Tang) [inline components/engine_traits/src/range_cache_engine.rs:69]: why not pass in &metapb::Region directly, so we have id, epoch and range

File: components/hybrid_engine/src/observer.rs [hunk 35]
```diff
@@ -13,14 +13,18 @@ use raftstore::coprocessor::{
 
 #[derive(Clone)]
 pub struct Observer {
-    pending_evict: Arc<Mutex<Vec<(CacheRange, EvictReason)>>>,
+    // observer is per thread so ther is no need to use mutex here,
```
Comment (SpadeA-Tang) [inline components/hybrid_engine/src/observer.rs:16]:
```suggestion
    // observer is per thread so ther is no need to use mutex here,
```// observer is per thread so their is no need to use mutex here,

File: components/range_cache_memory_engine/src/range_manager.rs [hunk 36]
```diff
@@ -44,22 +69,64 @@ impl SnapshotList {
...
+    #[inline]
+    pub fn region(&self) -> &Region {
+        &self.region
+    }
+
+    // update region info due to epoch version changes. This can only
+    // happen for pending region because otherwise we will always update
+    // the region epoch with ApplyObserver(for loading/active regions) or
+    // no need to update the epoch for evicting regions.
+    pub(crate) fn update_region(&mut self, region: &Region) -> bool {
```
Comment (SpadeA-Tang) [inline components/range_cache_memory_engine/src/range_manager.rs:117]: Seems this is for pending region only, rename it to amend_pending_region?

File: components/engine_traits/src/range_cache_engine.rs (hunk 34 above)
Comment (glorv) [reply components/engine_traits/src/range_cache_engine.rs:69]: Region's range is different from CacheRange(data range). I'm consider replace `Region` and `CacheRange` with：
```
struct CacheRegion {
  region_id: u64,
  epoch_version: u64,
  start: Vec<u8>,
  end: Vec<u8>,
}
```
Will try it in next PR.

File: components/range_cache_memory_engine/src/write_batch.rs [hunk 37]
```diff
@@ -55,16 +57,14 @@ pub struct RangeCacheWriteBatch {
...
     save_points: Vec<usize>,
     sequence_number: Option<u64>,
     memory_controller: Arc<MemoryController>,
     memory_usage_reach_hard_limit: bool,
-
-    current_range: Option<CacheRange>,
-    // the ranges that reaches the hard limit and need to be evicted
-    ranges_to_evict: BTreeSet<CacheRange>,
+    region_save_point: usize,
+    currnet_region_evicted: bool,
```
Comment (overvenus) [inline components/range_cache_memory_engine/src/write_batch.rs:66]:
```suggestion
    current_region_evicted: bool,
```

File: components/range_cache_memory_engine/src/background.rs [hunk 38]
```diff
@@ -434,133 +480,117 @@ impl BackgroundRunnerCore {
...
-            ),
-        );
+        let region_meta = core.range_manager.mut_region_meta(region.id).unwrap();
+        let mut remove_regions = vec![];
+
+        let mut mark_region_evicted = |meta: &mut RangeMeta| {
+            assert!(
+                meta.get_state() == RegionState::Loading
+                    || meta.get_state() == RegionState::LoadingCanceled
+            );
```
[the remark this answers is not in the document]
Comment (glorv) [reply components/range_cache_memory_engine/src/background.rs:570]: There is also a check in `mark_evict` but it accept an extra state "Active".

File: components/range_cache_memory_engine/src/range_manager.rs [hunk 39]
```diff
@@ -199,127 +352,224 @@ impl RangeManager {
...
+    /// `check_overlap_with_region` check whether there are regions overlap with
+    /// target region. If there are regions with `pending` state and whose
+    /// epoch version is smaller than target region, the pending regions will
+    /// be removed first.
+    fn check_overlap_with_region(&mut self, region: &Region) -> Option<RegionState> {
+        let region_range = CacheRange::from_region(region);
+        let mut removed_region = vec![];
+        let mut overlapped_region_state = None;
+        self.iter_overlapped_regions(&region_range, |region_meta| {
+            if region_meta.state != RegionState::Pending
```
Comment (SpadeA-Tang) [inline components/range_cache_memory_engine/src/range_manager.rs:416]: maybe `if region_meta.state == RegionState::pending && region_meta.region.get_region_epoch().version < region.get_region_epoch().version { removed_region ... }` is easier to read?

File: components/range_cache_memory_engine/src/range_manager.rs (hunk 12 above)
Comment (SpadeA-Tang) [reply components/range_cache_memory_engine/src/range_manager.rs:453]: We can add a assert here and add some comments, so we can change this != to >

File: components/range_cache_memory_engine/src/range_manager.rs [hunk 40]
```diff
@@ -336,189 +604,254 @@ impl RangeManager {
...
+            let meta = self.remove_region(id);
+            info!(
+                "evict overlap pending region in cache range engine";
+                "reason" => ?evict_reason,
+                "target_region" => ?evict_region,
+                "overlap_region" => ?meta.region,
+                "state" => ?prev_state,
+            );
+            return None;
+        } else if prev_state >= RegionState::LoadingCanceled {
```
Comment (SpadeA-Tang) [inline components/range_cache_memory_engine/src/range_manager.rs:677]: I prefer not using Ordering between state. Reader needs to remember the order of them and if we are to add a new state in the future, it's easy to make mistakes.

File: components/range_cache_memory_engine/src/range_manager.rs [hunk 41]
```diff
@@ -336,189 +604,254 @@ impl RangeManager {
...
+        } else {
+            info!("split source region not cached"; "region_id" => source_region.id);
+            return;
         }
-        if self.overlap_with_range_in_gc(&cache_range) {
-            return Err(LoadFailedReason::InGc);
+
+        let region_meta = self.remove_region(source_region.id);
+        assert!(region_meta.state <= RegionState::Active);
+        if region_meta.region.get_region_epoch().version != source_region.get_region_epoch().version
```
Comment (SpadeA-Tang) [inline components/range_cache_memory_engine/src/range_manager.rs:803]: In which case will cached region epoch version == source region epoch version?

Comment (SpadeA-Tang) [inline components/range_cache_memory_engine/src/range_manager.rs:803]: Source here means region before split or after? In which cases the version equals and not equals?

Comment (glorv) [reply components/range_cache_memory_engine/src/range_manager.rs:803]: `Source` is region before split. So if the region is in "ReadyToLoad, Loading, Active" state, the source region epoch should equal to the cached region epoch.

**Comment by SpadeA-Tang** [comment]
Overall LGTM

File: components/range_cache_memory_engine/src/range_manager.rs (hunk 40 above)
Comment (glorv) [reply components/range_cache_memory_engine/src/range_manager.rs]: Done.

**Comment by glorv** [comment]
@overvenus @SpadeA-Tang  Most comments are resolved, Please take a look again, thanks~

**Comment by SpadeA-Tang** [comment]
> @overvenus @SpadeA-Tang Most comments are resolved, Please take a look again, thanks~

It LGTM，see if @overvenus has any comments.

**Review by overvenus — APPROVED** [review]

**Review by SpadeA-Tang — APPROVED** [review]
