### PR TITLE
GC: fix error log printed unexpectedly by gc worker

### LINKED ISSUE #18213: GC worker still uses ConcurrencyManager::new which leads to annoying error logs
### What version of TiKV are you using?

v8.5.1

### What operating system and CPU are you using?

unreleated

### Steps to reproduce

run tikv-server

### What did you expect?

No annoying error message

### What did happened?

TiKV prints a lot of following logs because GC worker still uses ConcurrencyManager::new

```
[2025/02/12 14:15:22.320 +08:00] [ERROR] [lib.rs:133 ["improper setting: limit_valid_duration >= max_ts_drift_allowance; consider increasing max-ts-drift-allowance or decreasing max-ts-sync-interval"] [max_ts_drift_allowance=0ns] [limit_valid_duration=45s] [thread_id=32]
[2025/02/12 14:15:22.321 +08:00] [ERROR] [lib.rs:133 ["improper setting: limit_valid_duration >= max_ts_drift_allowance; consider increasing max-ts-drift-allowance or decreasing max-ts-sync-interval"] [max_ts_drift_allowance=0ns] [limit_valid_duration=45s] [thread_id=32]
```

The backtrace
```
backtrace="   0: tikv_util::set_panic_hook::{{closure}}
             at /home/ywxk/src/tikv_master/components/tikv_util/src/lib.rs:480:18
   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /home/ywxk/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2029:9
   2: std::panicking::rust_panic_with_hook
             at /home/ywxk/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:783:13
   3: std::panicking::begin_panic_handler::{{closure}}
             at /home/ywxk/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:649:13
   4: std::sys_common::backtrace::__rust_end_short_backtrace
             at /home/ywxk/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:171:18
   5: rust_begin_unwind
             at /home/ywxk/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:645:5
   6: core::panicking::panic_fmt
             at /home/ywxk/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panicking.rs:72:14
   7: concurrency_manager::ConcurrencyManager::new_with_config
             at /home/ywxk/src/tikv_master/components/concurrency_manager/src/lib.rs:136:13
   8: concurrency_manager::ConcurrencyManager::new
             at /home/ywxk/src/tikv_master/components/concurrency_manager/src/lib.rs:109:9
   9: tikv::server::gc_worker::gc_worker::GcRunnerCore<E>::new_txn
             at /home/ywxk/src/tikv_master/src/server/gc_worker/gc_worker.rs:371:35
  10: tikv::server::gc_worker::gc_worker::GcRunnerCore<E>::gc_keys
             at /home/ywxk/src/tikv_master/src/server/gc_worker/gc_worker.rs:466:27
  11: tikv::server::gc_worker::gc_worker::GcRunnerCore<E>::gc
             at /home/ywxk/src/tikv_master/src/server/gc_worker/gc_worker.rs:417:13
  12: tikv::server::gc_worker::gc_worker::GcRunnerCore<E>::run
             at /home/ywxk/src/tikv_master/src/server/gc_worker/gc_worker.rs:973:27
  13: <tikv::server::gc_worker::gc_worker::GcRunner<E> as tikv_util::worker::pool::Runnable>::run::{{closure}}
             at /home/ywxk/src/tikv_master/src/server/gc_worker/gc_worker.rs:1132:13
  14: yatp::task::future::RawTask<F>::poll
             at /home/ywxk/.cargo/git/checkouts/yatp-e704b73c3ee279b6/793be4d/src/task/future.rs:59:9
  15: yatp::task::future::TaskCell::poll
             at /home/ywxk/.cargo/git/checkouts/yatp-e704b73c3ee279b6/793be4d/src/task/future.rs:103:9
  16: <yatp::task::future::Runner as yatp::pool::runner::Runner>::handle
             at /home/ywxk/.cargo/git/checkouts/yatp-e704b73c3ee279b6/793be4d/src/task/future.rs:387:20
  17: <tikv_util::yatp_pool::YatpPoolRunner<T> as yatp::pool::runner::Runner>::handle
             at /home/ywxk/src/tikv_master/components/tikv_util/src/yatp_pool/mod.rs:199:24
  18: yatp::pool::worker::WorkerThread<T,R>::run
             at /home/ywxk/.cargo/git/checkouts/yatp-e704b73c3ee279b6/793be4d/src/pool/worker.rs:48:13
  19: yatp::pool::builder::LazyBuilder<T>::build::{{closure}}
             at /home/ywxk/.cargo/git/checkouts/yatp-e704b73c3ee279b6/793be4d/src/pool/builder.rs:114:25
  20: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /home/ywxk/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:155:18
  21: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
             at /home/ywxk/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:529:17
  22: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /home/ywxk/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panic/unwind_safe.rs:272:9
  23: std::panicking::try::do_call
             at /home/ywxk/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:552:40
  24: __rust_try
  25: std::panicking::try
             at /home/ywxk/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:516:19
  26: std::panic::catch_unwind
             at /home/ywxk/.rustup/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:142:14
```

When `compaction filter is disabled` by setting 
```
[gc]
enable-compaction-filter = false
```
it is likely to happen.

### PR DESCRIPTION
**Pull request by cfzjywxk**
### What is changed and how it works?

Issue Number: Close #18213 

What's Changed:

```commit-message
Fix error log printed unexpectedly by gc worker.
```

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [ ] Need to cherry-pick to the release branch

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note

```release-note
None.
```

### CODE REVIEW

File: components/concurrency_manager/src/lib.rs [hunk 1]
```diff
@@ -105,13 +105,15 @@ pub struct ConcurrencyManager {
...
+    // This method should be used in test only. To create a new concurrency manager,
+    // please use `new_with_config` instead.
     pub fn new(latest_ts: TimeStamp) -> Self {
         Self::new_with_config(
             latest_ts,
             DEFAULT_LIMIT_VALID_DURATION,
             ActionOnInvalidMaxTs::Panic,
             None,
-            Duration::ZERO,
+            DEFAULT_LIMIT_VALID_DURATION + Duration::from_secs(1),
```
Comment (ekexium) [inline components/concurrency_manager/src/lib.rs:116]: We need to update the unit tests accordingly.
Alternatively, we could make this method UT-specific and create a separate one for GC (as a temporary solution)

**Review by ekexium — APPROVED** [review]

File: components/concurrency_manager/src/lib.rs (hunk 1 above)
Comment (zyguan) [reply components/concurrency_manager/src/lib.rs:116]: How about:
- rename `ConcurrencyManager::new` to sth like `ConcurrencyManager::new_dummy` and make it `#[cfg(test)]`
- let `GcRunnerCore::new_txn` use `ConcurrencyManager::new_with_config` directly (or "create a separate one for GC", eg `ConcurrencyManager::new_for_gc`).

Comment (cfzjywxk) [reply components/concurrency_manager/src/lib.rs:116]: Yes `#[cfg(test)]` is a cleaner way but introduces many changes, I'll try it another time.

Comment (cfzjywxk) [reply components/concurrency_manager/src/lib.rs]: @ekexium @zyguan 
Refactored the `new` to `new_for_test` and a new `new_for_gc` is created as a temporary solution, PTAL

**Review by zyguan — APPROVED** [review]

**Comment by cfzjywxk** [comment]
> @cfzjywxk could you please cherry pick it into release-8.5 branch

@Tema It is picked in https://github.com/tikv/tikv/pull/18295.
