### PR TITLE
log_backup: stop task while memory out of quota

### LINKED ISSUE #15414: PiTR resolver may cause TiKV OOM
## Bug Report

Similar to https://github.com/tikv/tikv/issues/14864, PiTR (backup-stream) has its own resolver, and it may cause OOM too.

### What version of TiKV are you using?

\> v6.5.0

### Steps to reproduce

Run a large txn that is much greater than TiKV memory size.

### What did you expect?

No OOM.

### What did happened?

OOM.

### PR DESCRIPTION
**Pull request by YuJuncen**
### What is changed and how it works?

Issue Number: Close #15414

What's Changed:

```commit-message
This PR have refactored the subscription manager.
Generally, this:
- Replace the instance itself with a handle. This make it a real reactor(with an real event loop).
- Handle the result of subscripting a region via the message system instead of asynchronously, this will be the basis of making subscription tracker thread safe and (someday, hopefully) merge the basic libraries with TiCDC.

Based on the changes above, this PR also allows a region to be temporarily deregistered while we are about to reach the memory quota.
```

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Integration test
- Manual test (add detailed scripts or steps below)

### Release note 

```release-note
Reduced the possibility of run out of memory when there are huge transactions.
```

### CODE REVIEW

File: components/backup-stream/src/subscription_manager.rs [hunk 1]
```diff
@@ -630,42 +659,81 @@ where
...
                 .with_label_values(&["stale-command"])
                 .inc();
-            return Ok(());
+            return Ok(false);
+        }
+        Ok(true)
+    }
+
+    async fn retry_observe(&self, region: Region, handle: ObserveHandle) -> Result<bool> {
+        let failure_count = *self.failure_count.get(&region.id).unwrap_or_else(|| {
```
Comment (3pointer) [inline components/backup-stream/src/subscription_manager.rs:710]: perhaps move `*self.failure_count.entry(region_id).or_insert(0) += 1;` here. to avoid panic.

File: components/error_code/src/backup_stream.rs [hunk 2]
```diff
@@ -11,6 +11,10 @@ define_error_codes! {
         "A task not found.",
         "Please check the spell of your task name."
     ),
+    OUT_OF_QUOTA => ("OutOfQuota",
+        "Some of quota has been exceed, hence the task cannot continue.",
+        "For memory quotas, please check whether there are huge transactions. You may also increase the quota by modifying config."
```
Comment (overvenus) [inline components/error_code/src/backup_stream.rs:16]: Could you add the config name?

File: components/backup-stream/src/errors.rs [hunk 3]
```diff
@@ -147,8 +154,9 @@ macro_rules! annotate {
 }
 
 impl Error {
+    #[track_caller]
     pub fn report(&self, context: impl Display) {
-        warn!("backup stream meet error"; "context" => %context, "err" => %self, "verbose_err" => ?self);
+        warn!("backup stream meet error"; "context" => %context, "err" => %self, "verbose_err" => ?self, "position" => ?Location::caller());
```
Comment (overvenus) [inline components/backup-stream/src/errors.rs:159]: Better to keep lines within 80 chars.

File: components/backup-stream/src/errors.rs [hunk 4]
```diff
@@ -18,16 +19,19 @@ use crate::{endpoint::Task, metrics};
...
-    #[error("Protobuf meet error {0}")]
-    Protobuf(#[from] ProtobufError),
     #[error("No such task {task_name:?}")]
     NoSuchTask { task_name: String },
     #[error("Observe have already canceled for region {0} (version = {1:?})")]
     ObserveCanceled(u64, RegionEpoch),
     #[error("Malformed metadata {0}")]
     MalformedMetadata(String),
+    #[error("Out of quota for region {region_id}")]
+    OutOfQuota { region_id: u64 },
```
Comment (overvenus) [inline components/backup-stream/src/errors.rs:29]: Why we need the region id?

File: components/backup-stream/src/endpoint.rs [hunk 5]
```diff
@@ -906,7 +944,14 @@ where
     /// Modify observe over some region.
     /// This would register the region to the RaftStore.
     pub fn on_modify_observe(&self, op: ObserveOp) {
-        self.pool.block_on(self.region_operator.request(op));
+        self.pool
+            .block_on(self.region_operator.send(op))
+            .map_err(|err| {
+                Error::Other(
```
Comment (overvenus) [inline components/backup-stream/src/endpoint.rs:950]: How about `box_err!`?

File: components/backup-stream/src/subscription_manager.rs [hunk 6]
```diff
@@ -485,10 +446,106 @@ where
...
+            "mem_usage" => %self.memory_manager.used_ratio(), 
+            "mem_max" => %self.memory_manager.capacity());
+        if let Some(region) = act_region {
+            self.schedule_start_observe(delay, region, None);
         }
     }
 
+    fn schedule_start_observe(
+        &self,
+        after: Duration,
```
Comment (overvenus) [inline components/backup-stream/src/subscription_manager.rs:528]: How about `backoff`?

File: components/backup-stream/src/subscription_manager.rs [hunk 7]
```diff
@@ -485,10 +446,106 @@ where
...
+        info!("log backup triggering high memory usage."; 
+            "region" => %inconsistent_region_id, 
+            "mem_usage" => %self.memory_manager.used_ratio(), 
+            "mem_max" => %self.memory_manager.capacity());
+        if let Some(region) = act_region {
+            self.schedule_start_observe(delay, region, None);
         }
     }
 
+    fn schedule_start_observe(
```
Comment (overvenus) [inline components/backup-stream/src/subscription_manager.rs:526]: Make it `async fn` then we don't need `tokio::spawn(async move {}) at line 540.

File: components/backup-stream/src/subscription_manager.rs [hunk 8]
```diff
@@ -630,42 +659,81 @@ where
...
-            return Ok(());
+            return Ok(false);
         }
         let new_region_info = new_region_info.unwrap();
         if new_region_info.role != StateRole::Leader {
             metrics::SKIP_RETRY.with_label_values(&["not-leader"]).inc();
-            return Ok(());
+            return Ok(false);
+        }
+        if raftstore::store::util::compare_region_epoch(
```
Comment (overvenus) [inline components/backup-stream/src/subscription_manager.rs:675]: How about `is_epoch_stale`?

File: components/backup-stream/src/errors.rs (hunk 4 above)
Comment (YuJuncen) [reply components/backup-stream/src/errors.rs:29]: Because we have aborted the initial scanning of this region, then we must deregister the region and reinitialize it then.

File: components/backup-stream/src/subscription_manager.rs (hunk 7 above)
Comment (YuJuncen) [reply components/backup-stream/src/subscription_manager.rs:526]: Even this become an async fn we still cannot await in this function because it may be executed on the event loop.

File: components/error_code/src/backup_stream.rs (hunk 2 above)
Comment (YuJuncen) [reply components/error_code/src/backup_stream.rs:16]: For now there isn't an universal memory quota config flag for log backup and I'm going to unify the current two memory quota configs. I think we can add that config name then or once the config term changed I'm afraid this may confuse the user.

**Review by overvenus — APPROVED** [review]

**Review by 3pointer — COMMENTED** [review]
rest LGTM

File: components/backup-stream/src/subscription_manager.rs [hunk 9]
```diff
@@ -567,62 +625,36 @@ where
...
-                    "retry time exceeds for region {:?}",
-                    utils::debug_region(&region)
-                )
-                .into(),
-            ));
-        }
-
-        let (tx, rx) = crossbeam::channel::bounded(1);
+    #[instrument(skip_all)]
+    async fn check_not_stale(&self, region: &Region, handle: &ObserveHandle) -> Result<bool> {
```
[the remark this answers is not in the document]
Comment (YuJuncen) [reply components/backup-stream/src/subscription_manager.rs:656]: The result of this function is whether the request is NOT stale. I think `check_stale` will be a misleading name too. 
I think a positive predicate will be fine. Renaming it to `is_available`.
