### PR TITLE
tikv-ctl: Don't send compact commands to TiFlash stores

### LINKED ISSUE #16189: tikv-ctl compact-cluster doesn't work when TiFlash nodes exist
### What version of TiKV are you using?
7.1.1

### Steps to reproduce

Create cluster with a TiFlash node. Run tikv-ctl compact-cluster.

### What did you expect?
compact-cluster to finish successfully

### What did happened?
```
DebugClient::compact: RpcFailure: 12-UNIMPLEMENTED
```

Note: I have a PR for this coming shortly.

### PR DESCRIPTION
**Pull request by frew**
### What is changed and how it works?
Issue Number: Close #16189

What's Changed:

```commit-message
tikv-ctl compact-cluster now works with clusters that have TiFlash nodes
```

### Check List

Tests 

- [ ] Manual test (add detailed scripts or steps below)

Side effects

None

### Release note

```release-note
tikv-ctl compact-cluster now works with clusters that have TiFlash nodes
```

### CODE REVIEW

**Comment by frew** [comment]
Just let me know if there's any bookkeeping steps or questions for this commit. If you could make the bot build tikv-ctl (I think this is easy?) I'll test it on my cluster.

File: cmd/tikv-ctl/src/main.rs [hunk 1]
```diff
@@ -796,12 +796,18 @@ fn compact_whole_cluster(
...
 ) {
-    let stores = pd_client
+    let all_stores = pd_client
         .get_all_stores(true) // Exclude tombstone stores.
         .unwrap_or_else(|e| perror_and_exit("Get all cluster stores from PD failed", e));
 
+    let tikv_stores = all_stores.iter().filter(|s| {
+        !s.get_labels()
+            .iter()
+            .any(|l| l.get_key() == "engine" && l.get_value() == "tiflash")
```
Comment (bufferflies) [inline cmd/tikv-ctl/src/main.rs:806]: maybe you need to consider this code to check the store belongs the tiflash.
https://github.com/tikv/tikv/blob/312e0fb7f9f77e6002d0a336a58e84f3c4c12216/components/raftstore/src/store/worker/region.rs#L839-L842

Comment (frew) [reply cmd/tikv-ctl/src/main.rs:806]: Sure - I think it's equivalent, but can use the constants. Is there a place that it would make sense to pull this out into a common utility function, or should I just copy and paste the code?

Comment (bufferflies) [reply cmd/tikv-ctl/src/main.rs:806]: yes, it's little different that the key and values need to lower case.

**Review by tonyxuqqi — APPROVED** [review]
LGMT. It's better to have a utility function for tiflash store check as now it has been used by two places. @frew

**Review by overvenus — APPROVED** [review]
Thanks!
