### PR TITLE
backup-stream: don't close the server stream when encountered errors

### LINKED ISSUE #14426: tikv panic with fatal error when run ha-tidb-random-to-all-network-partition-last-for-10m
### What version of TiKV are you using?
[2023/03/19 13:13:59.601 +08:00] [INFO] [lib.rs:91] ["Release Version:   6.7.0-alpha"]
[2023/03/19 13:13:59.601 +08:00] [INFO] [lib.rs:91] ["Edition:           Community"]
[2023/03/19 13:13:59.601 +08:00] [INFO] [lib.rs:91] ["Git Commit Hash:   4baf9e72b97b20d8199b25f97376f5204560ce46"]
[2023/03/19 13:13:59.601 +08:00] [INFO] [lib.rs:91] ["Git Commit Branch: heads/refs/tags/v6.7.0-alpha"]
[2023/03/19 13:13:59.601 +08:00] [INFO] [lib.rs:91] ["UTC Build Time:    Unknown (env var does not exist when building)"]
[2023/03/19 13:13:59.601 +08:00] [INFO] [lib.rs:91] ["Rust Version:      rustc 1.67.0-nightly (96ddd32c4 2022-11-14)"]
[2023/03/19 13:13:59.601 +08:00] [INFO] [lib.rs:91] ["Enable Features:   pprof-fp jemalloc mem-profiling portable sse test-engine-kv-rocksdb test-engine-raft-raft-engine cloud-aws cloud-gcp cloud-azure"]
[2023/03/19 13:13:59.601 +08:00] [INFO] [lib.rs:91] ["Profile:           dist_release"]

### What operating system and CPU are you using?
8c/32g

### Steps to reproduce
https://tcms.pingcap.net/dashboard/executions/plan/1682471
ha-tidb-random-to-all-network-partition-last-for-10m

### What did you expect?
tikv shoud not panic

### What did happened?
[2023/03/19 13:13:54.604 +08:00] [FATAL] [lib.rs:497] ["Resolved future is not supposed to be polled again."] [backtrace="   0: tikv_util::set_panic_hook::{{closure}}\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/tikv_util/src/lib.rs:496:18\n   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2032:9\n      std::panicking::rust_panic_with_hook\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:692:13\n   2: std::panicking::begin_panic::{{closure}}\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:608:9\n   3: std::sys_common::backtrace::__rust_end_short_backtrace\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:137:18\n   4: std::panicking::begin_panic\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:607:12\n   5: <grpcio::task::CqFuture<T> as core::future::future::Future>::poll\n             at rust/registry/src/github.com-1ecc6299db9ec823/grpcio-0.10.4/src/task/mod.rs:90:13\n   6: grpcio::call::SinkBase::poll_ready\n             at rust/registry/src/github.com-1ecc6299db9ec823/grpcio-0.10.4/src/call/mod.rs:796:24\n   7: <grpcio::call::server::ServerStreamingSink<T> as futures_sink::Sink<(T,grpcio::call::WriteFlags)>>::poll_close\n             at rust/registry/src/github.com-1ecc6299db9ec823/grpcio-0.10.4/src/call/server.rs:562:28\n      <&mut S as futures_sink::Sink<Item>>::poll_close\n             at rust/registry/src/github.com-1ecc6299db9ec823/futures-sink-0.3.15/src/lib.rs:130:9\n      <futures_util::sink::close::Close<Si,Item> as core::future::future::Future>::poll\n             at rust/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.15/src/sink/close.rs:30:9\n      backup_stream::checkpoint_manager::SubscriptionManager::remove_subscription::{{closure}}\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/backup-stream/src/checkpoint_manager.rs:113:21\n      <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:91:19\n      backup_stream::checkpoint_manager::SubscriptionManager::emit_events::{{closure}}\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/backup-stream/src/checkpoint_manager.rs:104:41\n      <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:91:19\n      backup_stream::checkpoint_manager::SubscriptionManager::main_loop::{{closure}}\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/backup-stream/src/checkpoint_manager.rs:73:45\n      <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:91:19\n      tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}\n             at rust/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/core.rs:184:17\n      tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut\n             at rust/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/loom/std/unsafe_cell.rs:14:9\n      tokio::runtime::task::core::CoreStage<T>::poll\n             at rust/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/core.rs:174:13\n   8: tokio::runtime::task::harness::poll_future::{{closure}}\n             at rust/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/harness.rs:480:19\n      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panic/unwind_safe.rs:271:9\n      std::panicking::try::do_call\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:483:40\n      std::panicking::try\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:447:19\n      std::panic::catch_unwind\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:137:14\n      tokio::runtime::task::harness::poll_future\n             at rust/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/harness.rs:468:18\n      tokio::runtime::task::harness::Harness<T,S>::poll_inner\n             at rust/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/harness.rs:104:27\n      tokio::runtime::task::harness::Harness<T,S>::poll\n             at rust/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/harness.rs:57:15\n      tokio::runtime::task::raw::poll\n             at rust/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/raw.rs:194:5\n   9: tokio::runtime::task::raw::RawTask::poll\n             at rust/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/raw.rs:134:18\n      tokio::runtime::task::LocalNotified<S>::run\n             at rust/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/mod.rs:385:9\n      tokio::runtime::scheduler::multi_thread::worker::Context::run_task::{{closure}}\n             at rust/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/scheduler/multi_thread/worker.rs:421:13\n      tokio::coop::with_budget::{{closure}}\n             at rust/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/coop.rs:102:9\n      std::thread::local::LocalKey<T>::try_with\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:446:16\n      std::thread::local::LocalKey<T>::with\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:422:9\n      tokio::coop::with_budget\n             at rust/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/coop.rs:95:5\n      tokio::coop::budget\n             at rust/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/coop.rs:72:5\n      tokio::runtime::scheduler::multi_thread::worker::Context::run_task\n             at rust/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/scheduler/multi_thread/worker.rs:420:9\n  10: tokio::runtime::scheduler::multi_thread::worker::Context::run\n             at rust/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/scheduler/multi_thread/worker.rs:387:24\n      tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}\n             at rust/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/scheduler/multi_thread/worker.rs:372:17\n      tokio::macros::scoped_tls::ScopedKey<T>::set\n             at rust/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/macros/scoped_tls.rs:61:9\n      tokio::runtime::scheduler::multi_thread::worker::run\n             at rust/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/scheduler/multi_thread/worker.rs:369:5\n      tokio::runtime::scheduler::multi_thread::worker::Launch::launch::{{closure}}\n             at rust/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/scheduler/multi_thread/worker.rs:348:45\n      <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll\n             at rust/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/blocking/task.rs:42:21\n      tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}\n             at rust/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/core.rs:184:17\n      tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut\n             at rust/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/loom/std/unsafe_cell.rs:14:9\n      tokio::runtime::task::core::CoreStage<T>::poll\n             at rust/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/core.rs:174:13\n      tokio::runtime::task::harness::poll_future::{{closure}}\n             at rust/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/harness.rs:480:19\n      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panic/unwind_safe.rs:271:9\n      std::panicking::try::do_call\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:483:40\n      std::panicking::try\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:447:19\n      std::panic::catch_unwind\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:137:14\n      tokio::runtime::task::harness::poll_future\n             at rust/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/harness.rs:468:18\n      tokio::runtime::task::harness::Harness<T,S>::poll_inner\n             at rust/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/harness.rs:104:27\n      tokio::runtime::task::harness::Harness<T,S>::poll\n             at rust/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/harness.rs:57:15\n      tokio::runtime::task::raw::poll\n             at rust/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/raw.rs:194:5\n  11: tokio::runtime::task::raw::RawTask::poll\n             at rust/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/raw.rs:134:18\n      tokio::runtime::task::UnownedTask<S>::run\n             at rust/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/mod.rs:422:9\n      tokio::runtime::blocking::pool::Task::run\n             at rust/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/blocking/pool.rs:111:9\n      tokio::runtime::blocking::pool::Inner::run\n             at rust/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/blocking/pool.rs:346:17\n      tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}\n             at rust/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/blocking/pool.rs:321:13\n      std::sys_common::backtrace::__rust_begin_short_backtrace\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:121:18\n  12: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:551:17\n      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panic/unwind_safe.rs:271:9\n      std::panicking::try::do_call\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:483:40\n      std::panicking::try\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:447:19\n      std::panic::catch_unwind\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:137:14\n      std::thread::Builder::spawn_unchecked_::{{closure}}\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:550:30\n      core::ops::function::FnOnce::call_once{{vtable.shim}}\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:513:5\n  13: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2000:9\n      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2000:9\n      std::sys::unix::thread::Thread::new::thread_start\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys/unix/thread.rs:108:17\n  14: start_thread\n  15: __GI___clone\n"] [location=/rust/registry/src/github.com-1ecc6299db9ec823/grpcio-0.10.4/src/task/mod.rs:90] [thread_name=backup-stream]

### PR DESCRIPTION
**Pull request by YuJuncen**
### What is changed and how it works?

Issue Number: Close #14426

What's Changed:
This PR make us won't close the grpc server stream when encountered some errors.

```commit-message
```

### Check List 

Tests 

- Manual test (add detailed scripts or steps below)
There is a tricky unit test added, these tests can pass, however I'm not sure whether they should be added to the code.

<details><summary>Details</summary>

```diff
diff --git a/components/backup-stream/src/checkpoint_manager.rs b/components/backup-stream/src/checkpoint_manager.rs
index 1191b6010..9d0ac9ea7 100644
--- a/components/backup-stream/src/checkpoint_manager.rs
+++ b/components/backup-stream/src/checkpoint_manager.rs
@@ -51,10 +51,12 @@ impl std::fmt::Debug for CheckpointManager {
 enum SubscriptionOp {
     Add(Subscription),
     Emit(Box<[FlushEvent]>),
+    #[cfg(test)]
+    Inspect(Box<dyn FnOnce(&SubscriptionManager) + Send>),
 }
 
-struct SubscriptionManager {
-    subscribers: HashMap<Uuid, Subscription>,
+pub(crate) struct SubscriptionManager {
+    pub(crate) subscribers: HashMap<Uuid, Subscription>,
     input: Receiver<SubscriptionOp>,
 }
 
@@ -72,8 +74,13 @@ impl SubscriptionManager {
                 SubscriptionOp::Emit(events) => {
                     self.emit_events(events).await;
                 }
+                #[cfg(test)]
+                SubscriptionOp::Inspect(f) => {
+                    f(&self);
+                }
             }
         }
+        // NOTE: Maybe close all subscription streams here.
     }
 
     async fn emit_events(&mut self, events: Box<[FlushEvent]>) {
@@ -121,8 +128,12 @@ impl SubscriptionManager {
 }
 
 // Note: can we make it more generic...?
+#[cfg(not(test))]
 pub type Subscription = ServerStreamingSink<kvproto::logbackuppb::SubscribeFlushEventResponse>;
 
+#[cfg(test)]
+pub type Subscription = tests::MockSink;
+
 /// The result of getting a checkpoint.
 /// The possibility of failed to getting checkpoint is pretty high:
 /// because there is a gap between region leader change and flushing.
@@ -326,6 +337,29 @@ impl CheckpointManager {
     pub fn get_resolved_ts(&self) -> Option<TimeStamp> {
         self.resolved_ts.values().map(|x| x.checkpoint).min()
     }
+
+    #[cfg(test)]
+    pub(crate) fn sync_with_subs_mgr<T: Send + 'static>(
+        &mut self,
+        f: impl FnOnce(&SubscriptionManager) -> T + Send + 'static,
+    ) -> T {
+        use std::sync::Mutex;
+
+        let (tx, rx) = std::sync::mpsc::sync_channel(1);
+        let t = Arc::new(Mutex::new(None));
+        let tr = Arc::clone(&t);
+        self.manager_handle
+            .as_mut()
+            .unwrap()
+            .try_send(SubscriptionOp::Inspect(Box::new(move |x| {
+                *tr.lock().unwrap() = Some(f(x));
+                tx.send(()).unwrap();
+            })))
+            .unwrap();
+        rx.recv().unwrap();
+        let mut t = t.lock().unwrap();
+        t.take().unwrap()
+    }
 }
 
 fn not_leader(r: u64) -> PbError {
@@ -525,17 +559,21 @@ pub mod tests {
     use std::{
         assert_matches,
         collections::HashMap,
-        sync::{Arc, RwLock},
+        sync::{Arc, Mutex, RwLock},
         time::Duration,
     };
 
-    use futures::future::ok;
-    use kvproto::metapb::*;
+    use futures::{future::ok, Sink};
+    use grpcio::{RpcStatus, RpcStatusCode};
+    use kvproto::{logbackuppb::SubscribeFlushEventResponse, metapb::*};
     use pd_client::{PdClient, PdFuture};
     use txn_types::TimeStamp;
 
     use super::{BasicFlushObserver, FlushObserver, RegionIdWithVersion};
-    use crate::GetCheckpointResult;
+    use crate::{
+        subscription_track::{CheckpointType, ResolveResult},
+        GetCheckpointResult,
+    };
 
     fn region(id: u64, version: u64, conf_version: u64) -> Region {
         let mut r = Region::new();
@@ -547,6 +585,158 @@ pub mod tests {
         r
     }
 
+    #[derive(Clone)]
+    pub struct MockSink(Arc<Mutex<MockSinkInner>>);
+
+    impl MockSink {
+        fn with_fail_once(code: RpcStatusCode) -> Self {
+            let mut failed = false;
+            let inner = MockSinkInner {
+                items: Vec::default(),
+                closed: false,
+                on_error: Box::new(move || {
+                    if failed {
+                        RpcStatusCode::OK
+                    } else {
+                        failed = true;
+                        code
+                    }
+                }),
+            };
+            Self(Arc::new(Mutex::new(inner)))
+        }
+
+        fn trivial() -> Self {
+            let inner = MockSinkInner {
+                items: Vec::default(),
+                closed: false,
+                on_error: Box::new(|| RpcStatusCode::OK),
+            };
+            Self(Arc::new(Mutex::new(inner)))
+        }
+
+        pub async fn fail(&self, status: RpcStatus) -> crate::errors::Result<()> {
+            panic!("failed in a case should never fail: {}", status);
+        }
+    }
+
+    struct MockSinkInner {
+        items: Vec<SubscribeFlushEventResponse>,
+        closed: bool,
+        on_error: Box<dyn FnMut() -> grpcio::RpcStatusCode + Send>,
+    }
+
+    impl Sink<(SubscribeFlushEventResponse, grpcio::WriteFlags)> for MockSink {
+        type Error = grpcio::Error;
+
+        fn poll_ready(
+            self: std::pin::Pin<&mut Self>,
+            _cx: &mut std::task::Context<'_>,
+        ) -> std::task::Poll<Result<(), Self::Error>> {
+            Ok(()).into()
+        }
+
+        fn start_send(
+            self: std::pin::Pin<&mut Self>,
+            item: (SubscribeFlushEventResponse, grpcio::WriteFlags),
+        ) -> Result<(), Self::Error> {
+            let mut guard = self.0.lock().unwrap();
+            let code = (guard.on_error)();
+            if code != RpcStatusCode::OK {
+                return Err(grpcio::Error::RpcFailure(RpcStatus::new(code)));
+            }
+            guard.items.push(item.0);
+            Ok(())
+        }
+
+        fn poll_flush(
+            self: std::pin::Pin<&mut Self>,
+            _cx: &mut std::task::Context<'_>,
+        ) -> std::task::Poll<Result<(), Self::Error>> {
+            Ok(()).into()
+        }
+
+        fn poll_close(
+            self: std::pin::Pin<&mut Self>,
+            _cx: &mut std::task::Context<'_>,
+        ) -> std::task::Poll<Result<(), Self::Error>> {
+            let mut guard = self.0.lock().unwrap();
+            guard.closed = true;
+            Ok(()).into()
+        }
+    }
+
+    fn simple_resolve_result() -> ResolveResult {
+        let mut region = Region::new();
+        region.set_id(42);
+        ResolveResult {
+            region,
+            checkpoint: 42.into(),
+            checkpoint_type: CheckpointType::MinTs,
+        }
+    }
+
+    #[test]
+    fn test_rpc_sub() {
+        let rt = tokio::runtime::Builder::new_multi_thread()
+            .worker_threads(1)
+            .build()
+            .unwrap();
+        let mut mgr = super::CheckpointManager::default();
+        rt.spawn(mgr.spawn_subscription_mgr());
+
+        let trivial_sink = MockSink::trivial();
+        rt.block_on(mgr.add_subscriber(trivial_sink.clone()))
+            .unwrap();
+
+        mgr.resolve_regions(vec![simple_resolve_result()]);
+        mgr.flush();
+        mgr.sync_with_subs_mgr(|_| {});
+        assert_eq!(trivial_sink.0.lock().unwrap().items.len(), 1);
+    }
+
+    #[test]
+    fn test_rpc_retry() {
+        let rt = tokio::runtime::Builder::new_multi_thread()
+            .worker_threads(1)
+            .build()
+            .unwrap();
+        let mut mgr = super::CheckpointManager::default();
+        rt.spawn(mgr.spawn_subscription_mgr());
+
+        let error_sink = MockSink::with_fail_once(RpcStatusCode::UNAVAILABLE);
+        rt.block_on(mgr.add_subscriber(error_sink.clone())).unwrap();
+
+        mgr.resolve_regions(vec![simple_resolve_result()]);
+        mgr.flush();
+        assert_eq!(mgr.sync_with_subs_mgr(|item| { item.subscribers.len() }), 1);
+        mgr.resolve_regions(vec![simple_resolve_result()]);
+        mgr.flush();
+        mgr.sync_with_subs_mgr(|_| {});
+        assert_eq!(error_sink.0.lock().unwrap().items.len(), 1);
+    }
+
+    #[test]
+    fn test_rpc_failure() {
+        let rt = tokio::runtime::Builder::new_multi_thread()
+            .worker_threads(1)
+            .build()
+            .unwrap();
+        let mut mgr = super::CheckpointManager::default();
+        rt.spawn(mgr.spawn_subscription_mgr());
+
+        let error_sink = MockSink::with_fail_once(RpcStatusCode::INTERNAL);
+        rt.block_on(mgr.add_subscriber(error_sink.clone())).unwrap();
+
+        mgr.resolve_regions(vec![simple_resolve_result()]);
+        mgr.flush();
+        assert_eq!(mgr.sync_with_subs_mgr(|item| { item.subscribers.len() }), 0);
+        let sink = error_sink.0.lock().unwrap();
+        assert_eq!(sink.items.len(), 0);
+        // The stream shouldn't be closed when exit by a failure.
+        assert_eq!(sink.closed, false);
+    }
+
     #[test]
     fn test_flush() {
         let mut mgr = super::CheckpointManager::default();
diff --git a/components/backup-stream/src/service.rs b/components/backup-stream/src/service.rs
index 9d312a984..43d4ede2f 100644
--- a/components/backup-stream/src/service.rs
+++ b/components/backup-stream/src/service.rs
@@ -94,8 +94,13 @@ impl LogBackup for Service {
         &mut self,
         _ctx: grpcio::RpcContext<'_>,
         _req: kvproto::logbackuppb::SubscribeFlushEventRequest,
-        sink: grpcio::ServerStreamingSink<kvproto::logbackuppb::SubscribeFlushEventResponse>,
+        #[allow(unused_variables)] sink: grpcio::ServerStreamingSink<
+            kvproto::logbackuppb::SubscribeFlushEventResponse,
+        >,
     ) {
+        #[cfg(test)]
+        panic!("Service should not be used in an unit test");
+        #[cfg(not(test))]
         try_send!(
             self.endpoint,
             Task::RegionCheckpointsOp(RegionCheckpointOperation::Subscribe(sink))
```

</details> 

### Release note 

```release-note
None
```
This is a fix over bug in master branch.

### CODE REVIEW

**Comment by YuJuncen** [comment]
The changes which would infect non-test code are only in the commit https://github.com/tikv/tikv/pull/14432/commits/18867c4dd1f66bdd1a8e5b748dfd9db2c9b9f8c0.

File: components/backup-stream/src/checkpoint_manager.rs [hunk 1]
```diff
@@ -89,14 +96,12 @@ impl SubscriptionManager {
                 sub.flush().await
             };
 
-            match send_all.await {
-                Err(grpcio::Error::RemoteStopped) => {
+            if let Err(err) = send_all.await {
+                let can_retry = matches!(&err, grpcio::Error::RpcFailure(rpc_err) if rpc_err.code() == RpcStatusCode::UNAVAILABLE);
```
Comment (BusyJay) [inline components/backup-stream/src/checkpoint_manager.rs:100]: Why this error can retry?

Comment (YuJuncen) [reply components/backup-stream/src/checkpoint_manager.rs:100]: By default `grpc-go` would retry it. (Should we also add `RESOURCE_EXHAUSTED`?)

https://pkg.go.dev/github.com/grpc-ecosystem/go-grpc-middleware/retry#pkg-variables

Comment (YuJuncen) [reply components/backup-stream/src/checkpoint_manager.rs:100]: And it seems there is transparent retry [inside gRPC implementation](https://github.com/grpc/proposal/blob/master/A6-client-retries.md)(Though I have neither checked nor configured that.), perhaps we can remove this? What do you think? @BusyJay

Comment (BusyJay) [reply components/backup-stream/src/checkpoint_manager.rs]: I have no idea. I'm just curious why only this error can be retried.

File: components/backup-stream/src/checkpoint_manager.rs [hunk 2]
```diff
@@ -107,11 +109,10 @@ impl SubscriptionManager {
...
     async fn remove_subscription(&mut self, id: &Uuid) {
         match self.subscribers.remove(id) {
-            Some(mut sub) => {
+            Some(sub) => {
                 info!("client is gone, removing subscription"; "id" => %id);
-                sub.close()
-                    .await
-                    .report_if_err(format_args!("during removing subscription {}", id))
+                // The stream is an endless stream -- we don't need to close it.
+                drop(sub);
```
[the remark this answers is not in the document]
Comment (YuJuncen) [reply components/backup-stream/src/checkpoint_manager.rs:115]: According to @BusyJay, we should call `close` iff we have finished sending all items. In fact this stream is an infinite stream, so I think we don't need to close it in any conditions (Perhaps except server shutting down?).

File: components/backup-stream/src/checkpoint_manager.rs (hunk 1 above)
Comment (YuJuncen) [reply components/backup-stream/src/checkpoint_manager.rs]: Well, I have removed the retry, because the client would retry sooner when the connection closed.

File: components/backup-stream/src/checkpoint_manager.rs [hunk 3]
```diff
@@ -51,10 +51,12 @@ impl std::fmt::Debug for CheckpointManager {
 enum SubscriptionOp {
     Add(Subscription),
     Emit(Box<[FlushEvent]>),
+    #[cfg(test)]
+    Inspect(Box<dyn FnOnce(&SubscriptionManager) + Send>),
 }
 
-struct SubscriptionManager {
-    subscribers: HashMap<Uuid, Subscription>,
+pub(crate) struct SubscriptionManager {
```
Comment (BusyJay) [inline components/backup-stream/src/checkpoint_manager.rs:58]: All these `pub(crate)` are unnecessary.

**Review by BusyJay — APPROVED** [review]
The change look OK to me.

**Comment by YuJuncen** [comment]
@BusyJay Hi could you help to /merge this?

**Comment by YuJuncen** [comment]
/test
`test::resolved_follower` again, but I can swear this config won't influence this case :(
