### PR TITLE
titan: Estimate raw blob size based on Titan metrics

### LINKED ISSUE #18600: Region too large due to size underestimation with Titan on highly compressible data
### What version of TiKV are you using?
nightly

### Steps to reproduce

Write highly compressible 500KB values to TiKV with Titan enabled:
```
def compressible_str(length):
    base = ''.join(random.choices("abcde", k=8))  # small alphabet
    return (base * (length // len(base) + 1))[:length]
```

### What did you expect?
Regions should split once they reach the configured size threshold.

### What did happened?
No region split occurred. Even though actual data size grew significantly, the approximate_region_size remained low.

### Cause
When estimating the size of a region that includes Titan blobs, TiKV uses the compressed size of the blobs recorded in the blob index. As a result, under high compression ratios, the estimated region size can be significantly smaller than the actual data size, leading to delayed region splits and large regions.

### Proposed Fix
Add a `raw_size` field to BlobIndex, recording the uncompressed size of each blob. During region size estimation, TiKV should use `raw_size` instead of compressed blob size. Note: We need to ensure data format compatibility for existing blob indexes.

### PR DESCRIPTION
**Pull request by hbisheng**
### What is changed and how it works?

Issue Number: Close #18600

What's Changed:

```commit-message
This PR introduces a mechanism to estimate Titan blob raw size based on
metrics collected from Titan during flush. 

A sliding window of recent (raw, compressed) size samples is used to 
compute an average expansion factor. This factor is then used to 
estimate the raw size of a blob when building SST table properties. 
This approach assumes that the compression ratio remains relatively 
stable for the workload.

Apparently this is not a perfect solution, but a workaround. A more 
direct solution—recording the uncompressed size in the blob index 
format—was previously proposed[1]. However, changing the data format 
would break backward compatibility and prevent rollbacks, which can be 
risky.

[1] https://github.com/tikv/titan/pull/334#issuecomment-3026813148
```

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [ ] Need to cherry-pick to the release branch

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
   - With this PR, the region-not-split issue did not reproduce in the scenario described in #18600. 
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note

```release-note
Address region size underestimation by estimating Titan blob raw size from metrics.
```

### CODE REVIEW

File: components/engine_rocks/src/properties.rs [hunk 1]
```diff
@@ -33,17 +39,92 @@ const PROP_RANGE_INDEX: &str = "tikv.range_index";
...
         _ => Err(()),
     }
 }
 
+/// Tracks recent Titan blob compression stats to estimate raw blob size from
+/// compressed size. Maintains a sliding window of recent (raw, compressed)
+/// pairs and the largest blob seen.
+pub struct TitanBlobSizeEstimator {
+    history: Mutex<VecDeque<(u64, u64)>>, // (raw, compressed)
+    expansion_factor: AtomicU64,          // total_raw / total_compressed
```
Comment (hhwyt) [inline components/engine_rocks/src/properties.rs]: I think compression_factor is a better name.

**Review by hhwyt — COMMENTED** [review]
compression

File: components/engine_rocks/src/properties.rs (hunk 1 above)
Comment (hbisheng) [reply components/engine_rocks/src/properties.rs]: sounds good, let me change it

File: components/engine_rocks/src/properties.rs [hunk 2]
```diff
@@ -33,17 +39,92 @@ const PROP_RANGE_INDEX: &str = "tikv.range_index";
...
+            return;
+        }
+
+        // Loosely update max blob value seen
+        if max_blob_size_seen > self.max_blob_value.load(Ordering::Relaxed) {
+            self.max_blob_value
+                .store(max_blob_size_seen, Ordering::Relaxed);
+        }
+
+        let mut history = self.history.lock().unwrap();
```
Comment (hhwyt) [inline components/engine_rocks/src/properties.rs]: This logic is similar to `tikv_util::Smoother`. Could we reuse that code?

File: components/engine_rocks/src/properties.rs [hunk 3]
```diff
@@ -33,17 +39,92 @@ const PROP_RANGE_INDEX: &str = "tikv.range_index";
 pub const DEFAULT_PROP_SIZE_INDEX_DISTANCE: u64 = 4 * 1024 * 1024;
 pub const DEFAULT_PROP_KEYS_INDEX_DISTANCE: u64 = 40 * 1024;
 
+/// Caps the expansion factor to avoid unrealistic estimates due to
+/// miscalculation or noise.
+const TITAN_MAX_EXPANSION_FACTOR: f64 = 5000.0;
```
Comment (hhwyt) [inline components/engine_rocks/src/properties.rs]: is 5000x too high?

File: components/engine_rocks/src/properties.rs [hunk 4]
```diff
@@ -33,17 +39,92 @@ const PROP_RANGE_INDEX: &str = "tikv.range_index";
...
+        TitanBlobSizeEstimator::new();
+}
+
 fn get_entry_size(value: &[u8], entry_type: DBEntryType) -> std::result::Result<u64, ()> {
     match entry_type {
         DBEntryType::Put => Ok(value.len() as u64),
         DBEntryType::BlobIndex => match TitanBlobIndex::decode(value) {
-            Ok(index) => Ok(index.blob_size + value.len() as u64),
+            Ok(index) => {
+                let estimated_raw_size = TITAN_BLOB_SIZE_ESTIMATOR.estimate(index.blob_size);
```
Comment (v01dstar) [inline components/engine_rocks/src/properties.rs]: You already use atomic operations, however, I still worry about the performance impact, since `get_entry_size()` is called for every entry in the compaction job. Would you please do a benchmark? Or change it to a "lighter" implementation, e.g. cache it in the collector?

Comment (hbisheng) [reply components/engine_rocks/src/properties.rs]: That's a good point. It should be possible to cache the compression ratio in the collector. We'll only reload the compression ratio when it's the first `RangePropertiesCollector::add` after a `RangePropertiesCollector::finish`.

File: components/engine_rocks/src/properties.rs (hunk 2 above)
Comment (hbisheng) [reply components/engine_rocks/src/properties.rs]: good idea, reused it

File: components/engine_rocks/src/properties.rs (hunk 3 above)
Comment (hbisheng) [reply components/engine_rocks/src/properties.rs]: My extremely repeatitive workload was able to achive this compression factor, but I agree that it is much higher than what would occur in practice.

However, the estimated blob size is capped by the other Titan statistics `max_blob_size_seen`, so the final result remains within a realistic range. This 5000x cap on the compression factor is more like a second line of defense.

File: components/engine_rocks/src/properties.rs [hunk 5]
```diff
@@ -33,11 +39,32 @@ const PROP_RANGE_INDEX: &str = "tikv.range_index";
...
 
-fn get_entry_size(value: &[u8], entry_type: DBEntryType) -> std::result::Result<u64, ()> {
+/// Caps the compaction factor to avoid unrealistic estimates.
+pub const TITAN_MAX_COMPACTION_FACTOR: f64 = 5000.0;
+const FIVE_MINS_IN_SECONDS: u64 = 5 * 60;
+
+lazy_static! {
+    pub static ref TITAN_COMPRESSION_FACTOR_SMOOTHER: Mutex<Smoother<f64, 30, FIVE_MINS_IN_SECONDS, 0>> =
+        Mutex::new(Smoother::<f64, 30, FIVE_MINS_IN_SECONDS, 0>::default());
+    pub static ref TITAN_COMPRESSION_FACTOR: AtomicU64 = AtomicU64::new(0);
```
Comment (v01dstar) [inline components/engine_rocks/src/properties.rs]: Although, it is guaranteed to be 1 in runtime. I feel that initialized it as 1 brings less confusion.

File: components/engine_rocks/src/properties.rs [hunk 6]
```diff
@@ -33,11 +39,32 @@ const PROP_RANGE_INDEX: &str = "tikv.range_index";
...
+    pub static ref TITAN_MAX_BLOB_SIZE_SEEN: AtomicU64 = AtomicU64::new(0);
```
Comment (v01dstar) [inline components/engine_rocks/src/properties.rs]: Same here, `u64::MAX` feels better. Imagine compression factor has been instantiated, while max_blob_size has not.

File: components/engine_rocks/src/properties.rs (hunk 4 above)
Comment (hbisheng) [reply components/engine_rocks/src/properties.rs]: Ran the sysbench oltp_insert benchmark (30 min per run) and observed no performance regression beyond normal fluctuations:

| Run       | TPS   | QPS   | Avg Latency (ms) | P99 Latency (ms) | P999 Latency (ms) |
|-----------|-------|-------|-------------------|-------------------|--------------------|
| Baseline  | 44792 | 44767 | 2.17              | 5.29              | 26.8               |
| PR        | 44143 | 44118 | 2.20              | 5.61              | 27.1               |
| Baseline  | 43829 | 43804 | 2.20              | 5.40              | 27.7               |
| PR        | 45093 | 45069 | 2.15              | 5.23              | 26.1               |

File: components/engine_rocks/src/properties.rs (hunk 6 above)
Comment (hbisheng) [reply components/engine_rocks/src/properties.rs]: Updated it to u64::MAX

File: components/engine_rocks/src/properties.rs [hunk 7]
```diff
@@ -33,11 +39,32 @@ const PROP_RANGE_INDEX: &str = "tikv.range_index";
 pub const DEFAULT_PROP_SIZE_INDEX_DISTANCE: u64 = 4 * 1024 * 1024;
 pub const DEFAULT_PROP_KEYS_INDEX_DISTANCE: u64 = 40 * 1024;
 
-fn get_entry_size(value: &[u8], entry_type: DBEntryType) -> std::result::Result<u64, ()> {
+/// Caps the compaction factor to avoid unrealistic estimates.
+pub const TITAN_MAX_COMPACTION_FACTOR: f64 = 5000.0;
+const FIVE_MINS_IN_SECONDS: u64 = 5 * 60;
+
+lazy_static! {
+    pub static ref TITAN_COMPRESSION_FACTOR_SMOOTHER: Mutex<Smoother<f64, 30, FIVE_MINS_IN_SECONDS, 0>> =
```
Comment (LykxSassinator) [inline components/engine_rocks/src/properties.rs:50]: Can u add some necessary annotations for this sliding window ?

File: components/engine_rocks/src/rocks_metrics.rs [hunk 8]
```diff
@@ -1235,6 +1241,30 @@ pub fn flush_engine_statistics(statistics: &RocksStatistics, name: &str, is_tita
...
+                smoother.observe(compression_factor);
+                TITAN_COMPRESSION_FACTOR.store(smoother.get_avg().to_bits(), Ordering::Relaxed);
+                TITAN_COMPRESSION_FACTOR_GAUGE.set(smoother.get_avg());
+            }
+
+            // Update the Titan max blob size seen, used to cap blob size
+            // estimation.
+            let current = TITAN_MAX_BLOB_SIZE_SEEN.load(Ordering::Relaxed);
+            if current == u64::MAX || v.max as u64 > current {
+                TITAN_MAX_BLOB_SIZE_SEEN.store(v.max as u64, Ordering::Relaxed);
```
Comment (LykxSassinator) [inline components/engine_rocks/src/rocks_metrics.rs:1264]: Can we use `P9999` or `P99` as the candidate rather than `max` ? 

If the size distribution has an extreme outlier (e.g., `P9999` < `60KiB` but a singularity point == 10MiB), could this significantly skew the estimation?

Comment (hbisheng) [reply components/engine_rocks/src/rocks_metrics.rs:1264]: I'm not sure if `p9999` is a better choice. With `p9999` it's still possible that we underestimate the region size and cause the split check to be skipped, which is the main issue that we are trying to fix. 

In contrast, `max` might overestimate the region size, but that’s likely less problematic because the actual size will be determined during the scan in the split check phase.

Comment (LykxSassinator) [reply components/engine_rocks/src/rocks_metrics.rs:1264]: Got.

File: components/engine_rocks/src/rocks_metrics.rs [hunk 9]
```diff
@@ -1235,6 +1241,30 @@ pub fn flush_engine_statistics(statistics: &RocksStatistics, name: &str, is_tita
         }
     }
     if is_titan {
+        if let Some(v) = statistics.get_histogram(HistType::TitanValueSize) {
+            // Update the Titan compression factor, which is used to estimate
+            // blob raw size when building SST table properties.
+            let keys_cnt = statistics.get_ticker_count(TickerType::TitanBlobFileNumKeysWritten);
```
Comment (Connor1996) [inline components/engine_rocks/src/rocks_metrics.rs:1247]: tickers are just reset on L1235, you won't get a reasonable result here.

Comment (hbisheng) [reply components/engine_rocks/src/rocks_metrics.rs:1247]: L1235 only resets non-Titan tickers; Titan tickers are reset on L1269. Also, I've tested the PR locally and the region-not-split issue did not reproduce.

**Comment by hbisheng** [comment]
@Connor1996 @v01dstar @LykxSassinator @hhwyt PTAL again, thanks

**Review by LykxSassinator — APPROVED** [review]
LGTM

**Review by v01dstar — APPROVED** [review]

**Comment by hbisheng** [comment]
/retest

failed due to unrelated flaky tests
image

**Review by hhwyt — APPROVED** [review]
LGTM
