### PR TITLE
raftstore-v2: support warm up log cache and enable tests

### LINKED ISSUE #14845: [Dynamic Regions] Entry cache does not warm up before transferring leader
## Bug Report

Raftstore v2 does not yet support warming up entry cache before transferring leader.

### What version of TiKV are you using?

v7.0.0

### What did you expect?

Warm up cache before transferring leader.

### What did happened?

Does not warm up.

### PR DESCRIPTION
**Pull request by overvenus**
### What is changed and how it works?

Issue Number: Close #14845

What's Changed:

```commit-message
raftstorev2: support warm up log cache and enable tests
```

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Integration test

### Release note 

```release-note
None
```

### CODE REVIEW

File: components/raftstore-v2/src/operation/command/admin/compact_log.rs [hunk 1]
```diff
@@ -487,12 +507,13 @@ impl<EK: KvEngine, ER: RaftEngine> Peer<EK, ER> {
...
                 error!(self.logger, "failed to compact raft logs"; "err" => ?e);
             }
+            self.compact_log_context_mut().set_last_compacted_idx(index);
             // Extra write set right above.
         }
 
         let context = self.compact_log_context_mut();
         let applied = context.last_applying_index;
-        let total_cnt = applied - old_truncated;
+        let total_cnt = applied - prev_first_index;
```
Comment (SpadeA-Tang) [inline components/raftstore-v2/src/operation/command/admin/compact_log.rs:516]: let total_cnt = applied - prev_first_index + 1; ?

Comment (overvenus) [reply components/raftstore-v2/src/operation/command/admin/compact_log.rs:516]: I think without `+1` makes it identical to with raftstore v1, see `PeerFsmDelegate::on_ready_compact_log`.

**Review by SpadeA-Tang — APPROVED** [review]

File: components/raftstore-v2/src/operation/command/admin/compact_log.rs [hunk 2]
```diff
@@ -476,8 +495,9 @@ impl<EK: KvEngine, ER: RaftEngine> Peer<EK, ER> {
             .unwrap();
         self.set_has_extra_write();
 
-        // All logs < perssited_apply will be deleted, so should check with +1.
-        if old_truncated + 1 < self.storage().apply_trace().persisted_apply_index()
+        // All logs < persisted_apply will be deleted.
+        let prev_first_index = first_index;
+        if prev_first_index < self.storage().apply_trace().persisted_apply_index()
```
Comment (tonyxuqqi) [inline components/raftstore-v2/src/operation/command/admin/compact_log.rs:500]: I have a bit worry on this change that it may lead to too many entries cached when evict leader happens. 
Because in Multi-RocksDB, the persisted apply index is updated only after the region's memtable is flushed.  So it can be much bigger entry count than single rocksdb.  It would possibly lead to append message reject because of too many memory usage by raft entry cache. 
I'm wondering if it's better to add the cap of the entries to be cached.

Comment (overvenus) [reply components/raftstore-v2/src/operation/command/admin/compact_log.rs:500]: I have filed an issue for tracking the enhancement #14884. Will implement it in a later PR.

**Review by tonyxuqqi — APPROVED** [review]
