### PR TITLE
resolved_ts: return early after regions already had quorum

### LINKED ISSUE #11351: resolved ts lag increased after stoping a tikv
## Bug Report

image

Here it will wait until all check leader requests returned, which may cause resolved ts lag increased if one tikv was disconnected.

https://github.com/tikv/tikv/blob/999ca556005ed5c3b7ccbceb511806a5da365c45/components/cdc/src/endpoint.rs#L1072

### PR DESCRIPTION
**Pull request by 5kbpers**
Signed-off-by: 5kbpers <tangminghua@pingcap.com>

### What problem does this PR solve?

Issue Number: close #11351 

Problem Summary:

### What is changed and how it works?

What's Changed:
* export `region_resolved_ts_store` from `resolved_ts` and import it in `cdc`
* use `select_all` instead of `join_all` for returning early

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test

### Release note 

```release-note
Fix resolved ts lag increased after stoping a tikv
```

### CODE REVIEW

**Review by NingLin-P — APPROVED** [review]
LGTM

File: components/resolved_ts/src/advance.rs [hunk 1]
```diff
@@ -135,129 +137,140 @@ impl<E: KvEngine> AdvanceTsWorker<E> {
...
-        pd_client: Arc<dyn PdClient>,
-        security_mgr: Arc<SecurityManager>,
-        env: Arc<Environment>,
-        cdc_clients: Arc<Mutex<HashMap<u64, TikvClient>>>,
-        min_ts: TimeStamp,
-    ) -> Vec<u64> {
-        #[cfg(feature = "failpoint")]
-        (|| fail_point!("before_sync_replica_read_state", |_| regions))();
+// Confirms leadership of region peer before trying to advance resolved ts.
+// This function broadcasts a special message to all stores, get the leader id of them to confirm whether
```
Comment (liuzix) [inline components/resolved_ts/src/advance.rs:143]:
```suggestion
// This function broadcasts a special message to all stores, gets the leader id of them to confirm whether
```

File: components/resolved_ts/src/advance.rs [hunk 2]
```diff
@@ -135,129 +137,140 @@ impl<E: KvEngine> AdvanceTsWorker<E> {
...
+// current peer has a quorum which accept its leadership.
```
Comment (liuzix) [inline components/resolved_ts/src/advance.rs:144]:
```suggestion
// current peer has a quorum which accepts its leadership.
```

File: components/resolved_ts/src/advance.rs [hunk 3]
```diff
@@ -135,129 +137,140 @@ impl<E: KvEngine> AdvanceTsWorker<E> {
...
-                    .into_iter()
-                    .map(move |region_id| (store_id, region_id))
-            })
-            .flatten()
-            .for_each(|(store_id, region_id)| {
+            .boxed()
+        })
+        .collect();
+    for _ in 0..store_count {
+        let (res, _, remains) = select_all(stores).await;
```
Comment (liuzix) [inline components/resolved_ts/src/advance.rs:226]: Can you add comments on why using `select_all` as opposed to the original solution using `join_all`?

File: components/resolved_ts/src/advance.rs [hunk 4]
```diff
@@ -135,129 +137,140 @@ impl<E: KvEngine> AdvanceTsWorker<E> {
...
-                    );
-                    None
+                if region_has_quorum(&region_map[&region_id], &resp_map[&region_id]) {
+                    valid_regions.insert(region_id);
                 }
-            })
-            .collect()
+            }
+        }
+        if valid_regions.len() == regions.len() {
```
Comment (liuzix) [inline components/resolved_ts/src/advance.rs:236]:
```suggestion
        if valid_regions.len() == regions.len() {
            // break here because all regions have quorum,
            // so there is no need waiting for other stores to respond.
```

File: components/resolved_ts/src/advance.rs [hunk 5]
```diff
@@ -135,129 +137,140 @@ impl<E: KvEngine> AdvanceTsWorker<E> {
...
-            .map_or(0, |regions| regions[0].compute_size());
-        let stores = store_map.into_iter().map(|(store_id, regions)| {
-            let cdc_clients = cdc_clients.clone();
+        region_map.insert(region_id, peer_list);
+    }
+    // Approximate `LeaderInfo` size
+    let leader_info_size = store_map
+        .values()
+        .next()
+        .map_or(0, |regions| regions[0].compute_size());
```
Comment (liuzix) [inline components/resolved_ts/src/advance.rs:198]: Can there be `0` regions?

File: components/resolved_ts/src/advance.rs [hunk 6]
```diff
@@ -135,129 +137,140 @@ impl<E: KvEngine> AdvanceTsWorker<E> {
...
-        // region_id -> `(Vec<Peer>, LeaderInfo)`
-        let info_map = region_read_progress.dump_leader_infos(&regions);
+    // store_id -> leaders info, record the request to each stores
+    let mut store_map: HashMap<u64, Vec<LeaderInfo>> = HashMap::default();
+    // region_id -> region, cache the information of regions
+    let mut region_map: HashMap<u64, Vec<Peer>> = HashMap::default();
+    // region_id -> peers id, record the responses
+    let mut resp_map: HashMap<u64, Vec<u64>> = HashMap::default();
+    // region_id -> `(Vec<Peer>, LeaderInfo)`
+    let info_map = region_read_progress.dump_leader_infos(&regions);
```
Comment (liuzix) [inline components/resolved_ts/src/advance.rs:170]: How expensive is this function?

Comment (5kbpers) [reply components/resolved_ts/src/advance.rs:170]: O(n), n is the number of regions

File: components/resolved_ts/src/advance.rs [hunk 7]
```diff
@@ -135,129 +140,144 @@ impl<E: KvEngine> AdvanceTsWorker<E> {
...
+    min_ts: TimeStamp,
+) -> Result<(u64, CheckLeaderResponse)> {
+    if tikv_clients.lock().unwrap().get(&store_id).is_none() {
+        let store = box_try!(pd_client.get_store_async(store_id).await);
+        let cb = ChannelBuilder::new(env.clone());
+        let channel = security_mgr.connect(cb, &store.address);
+        tikv_clients
+            .lock()
+            .unwrap()
+            .insert(store_id, TikvClient::new(channel));
```
Comment (overvenus) [inline components/resolved_ts/src/advance.rs:266]: When do we release these connections?

Comment (NingLin-P) [reply components/resolved_ts/src/advance.rs:266]: There is an issue https://github.com/tikv/tikv/issues/11400 about it, I think we can fix it in another PR.

Comment (5kbpers) [reply components/resolved_ts/src/advance.rs]: Fixed

**Review by overvenus — APPROVED** [review]
LGTM

**Review by hicqu — APPROVED** [review]
