### PR TITLE
copr: fix cast real, decimal to time bug on overflow

### LINKED ISSUE #10045: cast function result not same as MySQL
### What version of TiKV are you using?

master branch

### What operating system and CPU are you using?

x86_64

### Steps to reproduce

```sql
mysql> create table t (a double);
mysql> insert into t values(-790822912);
mysql> select a from t where cast(a as time);
+------------+
| a          |
+------------+
| -790822912 |
+------------+
1 row in set, 1 warning (0.01 sec)
```

### What did you expect?

Empty result set.

### What did happened?

Related with https://github.com/pingcap/tidb/issues/23993, when cast Int, Real or Decimal into Time if there has Truncated error the result should be NULL.

### PR DESCRIPTION
**Pull request by blacktear23**
### What problem does this PR solve?

Issue Number: close #10045 

Problem Summary:

cast real, decimal to time if overflow or truncated should return NULL.

### What is changed and how it works?

What's Changed:

Let cast real and decimal to time return NULL if truncated.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test

Side effects

- No

### Release note 

- *: fix cast from real or decimal to time bug.

### CODE REVIEW

File: components/tidb_query_expr/src/impl_cast.rs [hunk 1]
```diff
@@ -998,9 +998,15 @@ fn cast_bytes_like_as_duration(
     ctx: &mut EvalContext,
     extra: &RpnFnCallExtra,
     val: &[u8],
+    overflow_return_null: bool,
```
Comment (lzmhhh123) [inline components/tidb_query_expr/src/impl_cast.rs:1001]:
```suggestion
    overflow_as_null: bool,
```

File: components/tidb_query_datatype/src/codec/mysql/duration.rs [hunk 2]
```diff
@@ -429,14 +433,25 @@ impl Duration {
     /// See: <http://dev.mysql.com/doc/refman/5.7/en/fractional-seconds.html>
     pub fn parse(ctx: &mut EvalContext, input: &str, fsp: i8) -> Result<Duration> {
         let fsp = check_fsp(fsp)?;
-        parser::parse(ctx, input, fsp, true)
+        parser::parse(ctx, input, fsp, true, false)
+            .ok_or_else(|| Error::truncated_wrong_val("TIME", input))
+    }
+
+    pub fn parse2(
```
Comment (lzmhhh123) [inline components/tidb_query_datatype/src/codec/mysql/duration.rs:440]:
```suggestion
    pub fn parse_consider_overflow(
```

Why not merge it with `parse`?

Comment (blacktear23) [reply components/tidb_query_datatype/src/codec/mysql/duration.rs:440]: this will break a lot of test code. If rust has parameter default value like python, Ithink it will be the best way, but not. And also no override. So I just create another function.

**Review by lzmhhh123 — APPROVED** [review]

**Review by skyzh — APPROVED** [review]
LGTM. By the way, I would suggest changing the PR title to "copr: ...." as this is indeed part of TiKV coprocessor.

At the same time, I would also suggest adding test case on `cast_real_as_duration` and `cast_decimal_as_duration`.

**Comment by blacktear23** [comment]
@skyzh PTAL

**Comment by skyzh** [comment]
/retitle copr: fix cast real, decimal to time bug on overflow

**Comment by skyzh** [comment]
@blacktear23 Please merge the PR at TiDB side first. Otherwise, copr-integration test won't pass.

**Comment by blacktear23** [comment]
@skyzh I think we should cherry-pick this PR to 5.0 branch.
