### PR TITLE
Throttle background traffic 

### LINKED ISSUE #19401: backgound traffic doesn't get throttled
## Bug Report
background traffic doesn't get throttled if online traffic consumes majority of the cpu. 

### What version of TiKV are you using?

8.5
### Steps to reproduce

This test checks whether background traffic configured with no limit is throttled once CPU utilization reaches 100%.
Steps
1. Start online traffic
2. Ramps up background traffic to bring TiKV CPU utilization to 100%
Results
Latency increases for online traffic from 9 ms to 20 ms.

### PR DESCRIPTION
**Pull request by mittalrishabh**
<!--
Thank you for contributing to TiKV!

If you haven't already, please read TiKV's [CONTRIBUTING](https://github.com/tikv/tikv/blob/master/CONTRIBUTING.md) document.

If you're unsure about anything, just ask; somebody should be along to answer within a day or two.

PR Title Format:
1. module [, module2, module3]: what's changed
2. *: what's changed
-->

### What is changed and how it works?
<!--
Please create an issue first to describe the problem.

There MUST be one line starting with "Issue Number:  " and 
linking the relevant issues via the "close" or "ref".

For more info, check https://github.com/tikv/tikv/blob/master/CONTRIBUTING.md#linking-issues.
-->

Issue Number: Close #19401

<!--
You could use "commit message" code block to add more description to the final commit message.
For more info, check https://github.com/tikv/tikv/blob/master/CONTRIBUTING.md#format-of-the-commit-message.
-->
What's Changed:

```commit-message
1. Introduced compaction-pressure tracking to dynamically throttle write operations under high compaction load.
2. Modify that how it calculate CPU resources and back off background traffic if online traffic uses majority of the resources. 
```

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [ ] Need to cherry-pick to the release branch

### Check List

Tests <!-- At least one of them must be included. -->

- [X] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note

<!-- 
Compatibility change, improvement, bugfix, and new feature need a release note.

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

If you don't think this PR needs a release note then fill it with None.
If this PR will be picked to release branch, then a release note is probably required.
-->

```release-note
Introduced compaction-pressure tracking to dynamically throttle write operations under high compaction load.
```

## Resource Control: Background Task Throttling Configuration                                                                                                                
                                                                                                                                                                               
  Four new dynamic configuration options for controlling background task resource usage and compaction-pressure-based write IO throttling.                                     
                                                                                                                                                                               
  ### `resource-control.bg-resource-threshold`
                                                                                                                                                                               
  Overall resource utilization percentage (CPU/IO) above which background tasks are throttled. Also caps the background utilization limit. When system utilization exceeds this
   threshold, background task budgets are linearly scaled down toward a minimum floor, freeing resources for online traffic.

  - **Type:** Float (percentage, 1.0–99.0)
  - **Default:** `70.0`
  - **Dynamic:** Yes

  ### `resource-control.bg-compaction-pressure-threshold`

  Compaction pending bytes ratio (percentage) at which background write IO throttling begins. Below this threshold, write IO ramps up toward the ceiling. At and above this
  threshold, write IO is linearly scaled down from ceiling to floor as pressure approaches 100%.

  - **Type:** Float (percentage, 1.0–99.0)
  - **Default:** `70.0`
  - **Dynamic:** Yes

  ### `resource-control.bg-write-io-ceiling`

  Maximum write IO rate for background tasks. Applied when compaction pressure is below the threshold. This is the upper bound that write IO will ramp up to when there is no
  compaction pressure.

  - **Type:** ReadableSize (bytes/s)
  - **Default:** `100GB`
  - **Dynamic:** Yes

  ### `resource-control.bg-write-io-floor`

  Minimum write IO rate that background tasks are always allowed, even under maximum compaction pressure. This is the lower bound — write IO will never be throttled below this
   value.

  - **Type:** ReadableSize (bytes/s)
  - **Default:** `10MB`
  - **Dynamic:** Yes


<!-- This is an auto-generated comment: release notes by coderabbit.ai -->
## Summary by CodeRabbit

* **New Features**
  * Added compaction-pressure tracking to coordinate throttling across components.

* **Improvements**
  * Dynamic write-IO throttling based on compaction pressure and per-group usage.
  * Dedicated write IO limiter for finer-grained throttling.
  * Quota adjustment now applies a capped background utilization and proportional distribution.
  * New runtime config: compaction pressure threshold (default 70%).

* **Tests**
  * Tests updated to cover compaction-pressure–aware throttling and multi-group distribution.
<!-- end of auto-generated comment: release notes by coderabbit.ai -->

### CODE REVIEW

File: components/resource_control/src/worker.rs [hunk 1]
```diff
@@ -30,6 +33,10 @@ use crate::{
 pub const BACKGROUND_LIMIT_ADJUST_DURATION: Duration = Duration::from_secs(10);
 
 const MICROS_PER_SEC: f64 = 1_000_000.0;
+/// CPU utilization threshold (percentage) above which background traffic is
+/// throttled. Also used as the cap for the background utilization limit and
+/// the compaction-pressure write-IO throttle onset.
+const BG_RESOURCE_THRESHOLD: f64 = 70.0;
```
[the remark this answers is not in the document]
Comment (mittalrishabh) [reply components/resource_control/src/worker.rs]: is it used at other places too.

**Review by Connor1996 — COMMENTED** [review]
Could you add a test?

**Comment by mittalrishabh** [comment]
> Could you add a test?

unit tests are already there. I will do e2e test too.

**Comment by mittalrishabh** [comment]
> Could you add a test?

e2e test
**For read traffic** 
1. Started sysbench with background traffic. TiKV CPU utilization reached 70%. As load increased further, latency degraded from 4 ms to 7 ms.
2. While background traffic continued, started a second sysbench instance with online traffic running the same workload. Online traffic latency converged from 50 ms to 6 ms within 40 seconds, while background traffic latency remained elevated at 50 ms.
3. After ramping down online traffic, background traffic latency recovered to 7 ms. 

**For write traffic**
Repeat the above experiment with write traffic. 

**For compaction**
set these parameters to creation compaction pressure. 
`mysql> SET CONFIG tikv `rocksdb.rate-bytes-per-sec` = '10MB';
Query OK, 0 rows affected, 1 warning (0.32 sec)

mysql> SET CONFIG tikv `rocksdb.defaultcf.disable-auto-compactions` = 'false';
Query OK, 0 rows affected, 1 warning (0.36 sec)

mysql> SET CONFIG tikv `rocksdb.writecf.disable-auto-compactions` = 'false';
Query OK, 0 rows affected, 1 warning (0.29 sec)

mysql> SET CONFIG tikv `rocksdb.rate-limiter-auto-tuned` = 'false';
Query OK, 0 rows affected, 1 warning (0.28 sec)

mysql> SET CONFIG tikv `rocksdb.defaultcf.soft-pending-compaction-bytes-limit` = '500MB';
Query OK, 0 rows affected, 1 warning (0.32 sec)`

background resource usage dropped with the increase in pending compaction bytes

**Comment by Connor1996** [comment]
PTAL @glorv

**Review by Connor1996 — COMMENTED** [review]
Findings

- High: components/resource_control/src/worker.rs:316-322 in the PR can panic on low-CPU deployments. The new CPU floor is fixed at one full core, then applied with clamp(min_floor, target). If TiKV is running with less than about 1.43 cores of quota, target < min_floor and the adjust loop panics instead of throttling.
- Medium: components/resource_control/src/worker.rs:160-173 and :283-314 hard-cap background work at 70% even with no foreground pressure. That silently overrides higher background_settings.utilization_limit values and regresses background-only throughput beyond the scope of issue #19401.
- Medium: components/resource_control/src/worker.rs:351-399 fails open for newly active or recently idle writers under high compaction pressure. When the previous interval’s write delta is zero, the new write-only limiter is reset to INFINITY, so a bursty background job can run unthrottled for a full 10-second adjustment cycle.

File: components/resource_control/src/config.rs [hunk 2]
```diff
@@ -12,13 +12,25 @@ pub struct Config {
     #[online_config(skip)]
     pub enabled: bool,
     pub priority_ctl_strategy: PriorityCtlStrategy,
+    /// Compaction pressure percentage at which background write IO throttling
+    /// begins. Dynamically configurable at runtime.
+    pub compaction_pressure_threshold: f64,
+    /// Maximum write IO rate (MB/s) allowed for background tasks when
+    /// compaction pressure is lower than the threshold.
+    pub write_io_ceiling: f64,
```
Comment (glorv) [inline components/resource_control/src/config.rs]:
```suggestion
    pub write_io_ceiling: ReadableSize,
```

File: components/resource_control/src/worker.rs [hunk 3]
```diff
@@ -138,19 +155,24 @@ impl<R: ResourceStatsProvider> GroupQuotaAdjustWorker<R> {
...
-        if background_util_limit == 0 {
-            background_util_limit = 100;
+        if bg_util_limit == 0 {
+            bg_util_limit = 100;
         }
+        // Cap utilization limit to BG_RESOURCE_THRESHOLD. Background
+        // tasks should never consume more than this fraction of total resources.
+        // When CPU utilization exceeds the threshold, the headroom goes negative
+        // and the background rate limit is reduced.
+        bg_util_limit = bg_util_limit.min(BG_RESOURCE_THRESHOLD as u64);
```
Comment (glorv) [inline components/resource_control/src/worker.rs]: Maybe it's better to set bg_util_limit to the default `BG_RESOURCE_THRESHOLD` if it's unset with default value 0. As we should prefer explicitly set value over a default value.

File: components/resource_control/src/worker.rs [hunk 4]
```diff
@@ -242,95 +263,119 @@ impl<R: ResourceStatsProvider> GroupQuotaAdjustWorker<R> {
...
-        // rg1, rg3, rg2 so the final rate limit assigned is: (rg1, 1000), (rg3,
-        // 5250(9000/12*7)), (rg2, 3750(9000/12*5))
-        for g in bg_group_stats {
-            let limit = g
-                .expect_cost_rate
-                .min(available_resource_rate / total_ru_quota * g.ru_quota);
+        let new_total_bg_budget = new_total_bg_budget.clamp(min_floor, target);
+
+        // Distribute proportionally by RU quota.
+        for g in bg_group_stats.iter() {
```
Comment (glorv) [inline components/resource_control/src/worker.rs:332]: Distribute proportionally is not a good strategy here. The ru_per_secs setting can differ from each other very largely and in general, few resource group will have background traffic. So the even distribution strategy will likely limit the active background traffic to very low threshold.

File: components/resource_control/src/worker.rs [hunk 5]
```diff
@@ -242,95 +263,119 @@ impl<R: ResourceStatsProvider> GroupQuotaAdjustWorker<R> {
...
+        }
+    }
+
+    /// Adjust the write-only IO limiter based on compaction pressure.
+    /// When pressure >= threshold, linearly scale write IO from ceiling to
+    /// floor. Below threshold, write IO is unlimited (infinity).
+    ///
+    /// Ceiling and floor are read from config (write_io_ceiling,
+    /// write_io_floor) in MB/s.
+    fn adjust_write_io_by_compaction_pressure(
```
Comment (glorv) [inline components/resource_control/src/worker.rs:347]: Compaction pending bytes is a good metrics for measuring the pressure on the foreground write path. But the background io also include other traffic that does not impact the compaction pending bytes, e.g. the write traffic by tidb-lightning/import into, as the traffic is coming from writing sst file, and the corresponding SST ingestion is unlikely to increase the compaction pending bytes. So using compaction pending bytes to determine the background write io limit, the mechanism will not good for gating the write flow of sst ingestion(import/fast ddl).

**Review by glorv — COMMENTED** [review]
overall LGTM.

File: components/resource_control/src/worker.rs (hunk 4 above)
Comment (mittalrishabh) [reply components/resource_control/src/worker.rs:332]: it only considers the resource group which has background traffic in it. I am open to ideas. I couldn't find simpler way to implement it. 

Ideally, i want to get rid of distribute proportionally by RU quota completely and have one rate limiter for all background traffic. That's how I will be using it  -- all background traffic is assigned to default resource group. I think this way, it is more easier for customer to understand that when background traffic is throttled.  I can make this change (may be in another PR) if you agree.

File: components/resource_control/src/worker.rs (hunk 5 above)
Comment (mittalrishabh) [reply components/resource_control/src/worker.rs:347]: good point. i will remove this rate limiter in sst ingestion path

File: components/resource_control/src/worker.rs (hunk 3 above)
Comment (mittalrishabh) [reply components/resource_control/src/worker.rs]: i will add the config to tune BG_RESOURCE_THRESHOLD. i can not set it to bg_util_limit by default. if bg_set_limit is set to 20%. i don't want to start throttling background traffic at 20% cpu.

I personally don't like adding too many config parameters because it confuses the customers. I am not sure what is pingcap opinion on this.

**Comment by mittalrishabh** [comment]
> Findings
> 
> * High: components/resource_control/src/worker.rs:316-322 in the PR can panic on low-CPU deployments. The new CPU floor is fixed at one full core, then applied with clamp(min_floor, target). If TiKV is running with less than about 1.43 cores of quota, target < min_floor and the adjust loop panics instead of throttling.

[rishabh] fixed

> * Medium: components/resource_control/src/worker.rs:160-173 and :283-314 hard-cap background work at 70% even with no foreground pressure. That silently overrides higher background_settings.utilization_limit values and regresses background-only throughput beyond the scope of issue #19401.

[rishabh] I added a config `resource-control.bg-resource-threshold`. after this thresold, it starts applyback pressure based on background_settings.utilization_limit  and current cpu utilization. it doesn't mean bg cpu resources won't go more than `resource-control.bg-resource-threshold`.

> * Medium: components/resource_control/src/worker.rs:351-399 fails open for newly active or recently idle writers under high compaction pressure. When the previous interval’s write delta is zero, the new write-only limiter is reset to INFINITY, so a bursty background job can run unthrottled for a full 10-second adjustment cycle.

[rishabh]NA. I changed this code

**Comment by mittalrishabh** [comment]
@glorv @Connor1996 i addressed the comments.

**Comment by zph** [comment]
Following this b/c we want it too in my org

File: components/resource_control/src/worker.rs (hunk 4 above)
Comment (glorv) [reply components/resource_control/src/worker.rs:332]: I'm ok with the idea of using a single quota limiter for all background tasks. Quota per-resource_group seems more sophisticated but it's very hard to impl a effective algorithm to assign proper quota dynamically. /cc @Connor1996 What do you think?

Comment (mittalrishabh) [reply components/resource_control/src/worker.rs:332]: i will make this change in the follow up PR.

**Comment by mittalrishabh** [comment]
@Connor1996 please review

**Review by Connor1996 — APPROVED** [review]
LGTM

File: components/resource_control/src/worker.rs (hunk 4 above)
Comment (Connor1996) [reply components/resource_control/src/worker.rs:332]: I'm okay with using a single quota limiter for all background tasks

**Comment by Connor1996** [comment]
PTAL again @glorv

File: components/resource_control/src/worker.rs (hunk 4 above)
Comment (glorv) [reply components/resource_control/src/worker.rs:332]: @mittalrishabh As above discussed, please check the background quota limiters to a single quota limiter. You can put this global quota limiter under the default group or direct update the global ResourceGroupManager. And the per-group background-types should still be used to judge whether apply this limiter to specific request.

Comment (mittalrishabh) [reply components/resource_control/src/worker.rs:332]: can i fix this comment in the follow up PR as it is not completely related to throttle background traffic. I will create follow up PR by end of this week.

**Review by glorv — APPROVED** [review]
