### PR TITLE
resolved_ts: fix oom and add more metrics

### LINKED ISSUE #12159: TiKV OOM under TPCC workload when two tikv down for 10 minutes
## Bug Report

TiKV OOM.

### What version of TiKV are you using?

```
$ /tikv-server -V 
TiKV 
Release Version:  6.0.0-alpha 
Edition:          Community 
Git Commit Hash:  8954a76e2b87575d80336f502a4d078e5da1508f 
Git Commit Branch: heads/refs/tags/v6.0.0-nightly 
UTC Build Time:   2022-03-09 18:10:26 
Rust Version:     rustc 1.60.0-nightly (1e12aef3f 2022-02-13) 
Enable Features:  jemalloc mem-profiling portable sse test-engines-rocksdb cloud-aws cloud-gcp cloud-azure 
Profile:          dist_release
```

### Steps to reproduce

0. create a cluster with 5 replicas
    ```
    [replication]
    max-replicas = 5
    ```
2. run tpcc workload for 10 minutes (go-tpc)
3. down 2 tikvs for about 10 minutes

After the 2 tikvs were down, the other 3 tikvs's memory kept increasing.

### What did you expect?
No OOM.

### What did happened?
TiKV OOM.
image
image

For more details, see https://pingcap.feishu.cn/docs/doccnTugaMBp2jB62ZDwWX0Vv2c# .

### PR DESCRIPTION
**Pull request by 5kbpers**
### What is changed and how it works?

Issue Number: Close #12159

What's Changed:

```commit-message
* Do not hold mutex during calling `get_store_async`
* Add more metrics
```

### Check List 

Tests 

- Unit test
- Integration test

### Release note 

```release-note
None
```

### CODE REVIEW

File: components/resolved_ts/src/advance.rs [hunk 1]
```diff
@@ -359,23 +365,24 @@ async fn get_tikv_client(
...
-            client
+    {
+        let clients = tikv_clients.lock().await;
+        if let Some(client) = clients.get(&store_id).cloned() {
+            return Ok(client);
         }
-    };
-    Ok(client)
+    }
+    let store = box_try!(pd_client.get_store_async(store_id).await);
```
Comment (overvenus) [inline components/resolved_ts/src/advance.rs:374]: Could you add a unit test?

File: components/resolved_ts/src/advance.rs [hunk 2]
```diff
@@ -359,23 +365,24 @@ async fn get_tikv_client(
...
+    let mut clients = tikv_clients.lock().await;
+    let start = Instant::now_coarse();
+    // let store = box_try!(pd_client.get_store_async(store_id).await);
```
Comment (hicqu) [inline components/resolved_ts/src/advance.rs:377]: The line can be removed.

File: components/resolved_ts/src/advance.rs (hunk 1 above)
Comment (5kbpers) [reply components/resolved_ts/src/advance.rs:374]: We don't have a good way to inject a failure for `get_store_async` since `failpoint` doesn't support async/await

**Review by hicqu — APPROVED** [review]

File: components/resolved_ts/src/advance.rs (hunk 1 above)
Comment (NingLin-P) [inline components/resolved_ts/src/advance.rs:374]: Should we also add a timeout for `get_store_async`?

File: components/resolved_ts/src/advance.rs [hunk 3]
```diff
@@ -359,23 +365,24 @@ async fn get_tikv_client(
...
+    {
+        let clients = tikv_clients.lock().await;
+        if let Some(client) = clients.get(&store_id).cloned() {
+            return Ok(client);
         }
-    };
-    Ok(client)
+    }
+    let store = box_try!(pd_client.get_store_async(store_id).await);
+    let mut clients = tikv_clients.lock().await;
```
Comment (NingLin-P) [inline components/resolved_ts/src/advance.rs:375]: How about acquiring the lock after the client is created to shorten the time of holding the lock.

**Review by overvenus — APPROVED** [review]

File: components/resolved_ts/src/advance.rs (hunk 3 above)
Comment (5kbpers) [reply components/resolved_ts/src/advance.rs:375]: `TikvClient` has `!Send` so it cannot cross await point.

**Review by NingLin-P — APPROVED** [review]

**Comment by tabokie** [comment]
This PR needs to be reverted, PD can't handle these amount of concurrent `get_store`. Before and after:

image

**Comment by hehechen** [comment]
> 



> This PR needs to be reverted, PD can't handle these amount of concurrent `get_store`. Before and after:
> 
> image
> 
> Edit: Normally this would work fine, but for cluster with large number of tiflash nodes, the `check_leader_async` will return error and trigger another round of requesting. So instead of reverting this one, we should filter "unimplemented" error from `check_leader_async` RPC and avoid reconnection. It will also close #12092.

In fact, TiFlash has implemented check_leader RPC, the "unimplemented" error just because the [address is wrong.](https://github.com/tikv/tikv/issues/13310)
