### PR TITLE
raftstore,raftstore-v2: fix unsafe vote after start

### LINKED ISSUE #15035: Leader holds an invalid lease if one node is isolated and one node restarts
## Bug Report

Suppose there are three peers, A, B, C and A is the leader. Linearizability may be violated by following steps:

1. B is isolated from A.
2. A renews its lease.
3. C restarts right after step 2.
4. B starts election right after step 3.
5. B becomes leader before A lease expire.

Now we get two leaders, and both of them think they hold a valid lease.

A possible solution: Peers delay respond request vote after restart, within one election timeout.

```rust
#[test]
fn test_node_lease_restart_during_isolation() {
    let mut cluster = new_node_cluster(0, 3);
    configure_for_lease_read(&mut cluster.cfg, Some(1000), Some(3));
    cluster.run();

    let key = b"k";

    let region = cluster.get_region(key);
    let region_id = region.get_id();
    let peer1 = find_peer(&region, 1).unwrap();
    let peer2 = find_peer(&region, 2).unwrap();

    cluster.must_put(key, b"v0");
    cluster.must_transfer_leader(region_id, peer1.clone());
    must_read_on_peer(&mut cluster, peer1.clone(), region.clone(), key, b"v0");
    cluster.must_transfer_leader(region_id, peer2.clone());
    must_read_on_peer(&mut cluster, peer2.clone(), region.clone(), key, b"v0");

    cluster.add_send_filter(IsolationFilterFactory::new(2));

    // Restart node 3.
    cluster.stop_node(3);
    cluster.run_node(3).unwrap();

    // Let peer1 start election.
    let mut timeout = RaftMessage::default();
    timeout.mut_message().set_to(peer1.get_id());
    timeout
        .mut_message()
        .set_msg_type(MessageType::MsgTimeoutNow);
    timeout
        .mut_message()
        .set_msg_type(MessageType::MsgTimeoutNow);
    timeout.set_region_id(region.get_id());
    timeout.set_from_peer(peer2.clone());
    timeout.set_to_peer(peer1.clone());
    timeout.set_region_epoch(region.get_region_epoch().clone());
    cluster.send_raft_msg(timeout).unwrap();

    let (tx, rx) = mpsc::channel();
    let append_resp_notifier = Box::new(MessageTypeNotifier::new(
        MessageType::MsgAppendResponse,
        tx,
        Arc::from(AtomicBool::new(true)),
    ));
    cluster.sim.wl().add_send_filter(3, append_resp_notifier);
    rx.recv_timeout(Duration::from_secs(5)).unwrap();

    let mut put = new_request(
        region.get_id(),
        region.get_region_epoch().clone(),
        vec![new_put_cmd(key, b"v1")],
        false,
    );
    put.mut_header().set_peer(peer1.clone());
    let resp = cluster.call_command(put, Duration::from_secs(5)).unwrap();
    assert!(!resp.get_header().has_error(), "{:?}", resp);
    must_read_on_peer(&mut cluster, peer2.clone(), region.clone(), key, b"v0");
    must_read_on_peer(&mut cluster, peer1.clone(), region.clone(), key, b"v1");
}
```

### What did you expect?

No stale read.

### What did happened?

Stale read.

### PR DESCRIPTION
**Pull request by overvenus**
### What is changed and how it works?

Issue Number: Close #15035

What's Changed:

```commit-message
A peer should not grant vote for an election timeout after node start, otherwise, it may cause two leaders holding leader lease.

See https://github.com/tikv/tikv/issues/15035
```

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Integration test

### Release note 

```release-note
Fix an issue that may cause inconsistent reads when a TiKV node is isolated while another node restarts
```

### CODE REVIEW

File: components/raftstore-v2/src/batch/store.rs [hunk 1]
```diff
@@ -97,6 +96,11 @@ pub struct StoreContext<EK: KvEngine, ER: RaftEngine, T> {
     /// A background pool used for high-priority works.
     pub high_priority_pool: FuturePool,
 
+    // current_time and node_start_time relate to leader lease,
```
Comment (tonyxuqqi) [inline components/raftstore-v2/src/batch/store.rs:99]:
```suggestion
    /// current time from monotonic_raw_now
    pub current_time: Option<Timespec>,
    
    /// node start time from monotonic_raw_now
    pub node_start_time: Option<Timespec>,
```

File: components/raftstore/src/store/config.rs [hunk 2]
```diff
@@ -197,6 +197,15 @@ pub struct Config {
...
     pub renew_leader_lease_advance_duration: ReadableDuration,
 
+    // Set true to allow handling request vote messages within one election time
+    // after TiKV start.
+    //
+    // Note: set to true may break leader lease. It should only be true in tests.
+    #[doc(hidden)]
+    #[serde(skip)]
+    #[online_config(skip)]
+    pub allow_unsafe_vote_after_start: bool,
```
Comment (tonyxuqqi) [inline components/raftstore/src/store/config.rs:207]: If it's a test only setting, can it be test-only field in compile time.

**Review by tonyxuqqi — APPROVED** [review]

File: components/raftstore-v2/src/batch/store.rs [hunk 3]
```diff
@@ -97,6 +96,11 @@ pub struct StoreContext<EK: KvEngine, ER: RaftEngine, T> {
...
+    // must use monotonic_raw_now.
+    pub current_time: Option<Timespec>,
+    pub node_start_time: Option<Timespec>,
```
Comment (Connor1996) [inline components/raftstore-v2/src/batch/store.rs:102]: how about using `unsafe_vote_deadline` and calculate it by start time at start. A optional start time is confusing.

File: components/raftstore/src/store/config.rs (hunk 2 above)
Comment (Connor1996) [inline components/raftstore/src/store/config.rs:207]: why do we need a config?

**Review by Connor1996 — COMMENTED** [review]
rest LGTM

File: components/raftstore-v2/src/batch/store.rs (hunk 3 above)
Comment (overvenus) [reply components/raftstore-v2/src/batch/store.rs:102]: By taking timespec, it can skip comparing timespec and saves accessing monotic_raw_now clock (it's a syscall).

File: components/raftstore/src/store/config.rs (hunk 2 above)
Comment (overvenus) [reply components/raftstore/src/store/config.rs:207]: To speed up tests, it's allowed in testing.

Comment (overvenus) [reply components/raftstore/src/store/config.rs:207]: Note that this config will not be serialized or deserialized so it won't cause any configuration compatibility issues.

**Review by Connor1996 — APPROVED** [review]
LGTM
