### PR TITLE
storage, raftstore, causal-ts: Get snapshot before raw put(delete) to ensure that causal ts provider flush correctly

### LINKED ISSUE #13502: RawKV API V2 timestamp causality violation
### What version of TiKV are you using?

Master branch with PR https://github.com/tikv/tikv/pull/13326.

### Steps to reproduce

1. run endless rawkv apiv2 test case [causality_100](https://github.com/pingcap/endless/blob/c56f06a04f5324a8c906bcec3d0cfccc29f1fdd4/testcase/rawkv/api_v2/api_v2_test.go#L584)

### What did you expect?

Test case pass.

### What did happened?

Test case fail with causality issue.

Expect value0, but get value1. 
```
------------------------------
• Failure [51.544 seconds]
RawKV
/home/jenkins/agent/workspace/endless-master-build/pkg/util/dsl.go:29
  ApiV2
  /home/jenkins/agent/workspace/endless-master-build/testcase/rawkv/api_v2/api_v2_test.go:230
    Causality test by all workloads #causality_100# [It]
    /home/jenkins/agent/workspace/endless-master-build/pkg/util/dsl.go:61
    key: cc0000000816002860
    Expected
        <[]uint8 | len:74, cap:80>: 816002860_0000000000000000000000000000000000000000000000000000000000000000
    to equal
        <[]uint8 | len:74, cap:80>: 816002861_0000000000000000000000000000000000000000000000000000000000000000
    /home/jenkins/agent/workspace/endless-master-build/testcase/rawkv/api_v2/workload.go:41
------------------------------
```

### PR DESCRIPTION
**Pull request by zeminzhou**
### What is changed and how it works?

Issue Number: Close #13502, #13550

What's Changed:

```commit-message
1. Move causal ts provider's `flush` from coprocessor observer to raftstore pd woker. 
   When implementing asynchronous refresh, `storage` can check whether the causal ts
   provider has completed the refresh through the flag `max_ts_sync_status`.
2. To check `max_ts_sync_status` in `storage`, we need get snapshot.
```

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM

### Release note 

```release-note
Causal ts for APIV2
```

### CODE REVIEW

File: src/storage/mod.rs [hunk 1]
```diff
@@ -1847,47 +1847,32 @@ impl<E: Engine, L: LockManager, F: KvFormat> Storage<E, L, F> {
...
-        if let Some(p) = ts_provider {
-            match p.get_ts() {
-                Ok(ts) => Ok(Some(ts)),
-                Err(e) => Err(box_err!("Fail to get ts: {}", e)),
-            }
-        } else {
-            Ok(None)
-        }
-    }
+    async fn check_causal_ts_synced(ctx: &mut Context) -> Result<()> {
```
Comment (haojinming) [inline src/storage/mod.rs:1850]: I think it's no need to check for non-apiv2 scenario.

Comment (zeminzhou) [reply src/storage/mod.rs]: Yesh, I added judgment, thanks.

File: src/storage/mod.rs [hunk 2]
```diff
@@ -1847,47 +1847,34 @@ impl<E: Engine, L: LockManager, F: KvFormat> Storage<E, L, F> {
...
-        if let Some(p) = ts_provider {
-            match p.get_ts() {
-                Ok(ts) => Ok(Some(ts)),
-                Err(e) => Err(box_err!("Fail to get ts: {}", e)),
-            }
-        } else {
-            Ok(None)
-        }
-    }
+    async fn check_causal_ts_synced(ctx: &mut Context, api_version: ApiVersion) -> Result<()> {
```
Comment (haojinming) [inline src/storage/mod.rs:1850]: This is an `async` func, but the name is `synced`?

**Review by haojinming — APPROVED** [review]
REST LGTM

File: src/storage/mod.rs (hunk 2 above)
Comment (haojinming) [reply src/storage/mod.rs:1850]: I get the reason, this func is check `the casual is synced or not`. Is it? It's a liittle confused.

Comment (zeminzhou) [reply src/storage/mod.rs:1850]: Yes, it is used for checking `causal-ts-provider` is synced. Ok, I try to rename it.

File: src/storage/txn/commands/atomic_store.rs [hunk 3]
```diff
@@ -59,7 +87,7 @@ impl<S: Snapshot, L: LockManager> WriteCommand<S, L> for RawAtomicStore {
             rows,
             pr: ProcessResult::Res,
             lock_info: None,
-            lock_guards: vec![],
+            lock_guards,
```
Comment (pingyu) [inline src/storage/txn/commands/atomic_store.rs:90]: `lock_guards: lock_guard.into_iter().collect(),`

File: src/storage/txn/commands/compare_and_swap.rs [hunk 4]
```diff
@@ -218,15 +252,17 @@ mod tests {
     }
 
     fn test_cas_process_write_impl<F: KvFormat>() {
+        let ts_provider = if F::TAG == kvproto::kvrpcpb::ApiVersion::V2 {
```
Comment (pingyu) [inline src/storage/txn/commands/compare_and_swap.rs:255]: Suggest to extract this block to a utility function.

File: src/storage/mod.rs [hunk 5]
```diff
@@ -1847,47 +1847,34 @@ impl<E: Engine, L: LockManager, F: KvFormat> Storage<E, L, F> {
...
+        if api_version == ApiVersion::V2 {
```
Comment (pingyu) [inline src/storage/mod.rs:1851]: `F::TAG` can be utilized to avoid pass the `api_version` argument.

File: tests/failpoints/cases/test_rawkv.rs [hunk 6]
```diff
@@ -64,6 +64,26 @@ impl TestSuite {
...
+        let client = self.get_client(region_id);
+        let ctx = self.get_context(region_id);
+
+        let mut put_req = RawPutRequest::default();
+        put_req.set_context(ctx);
+        put_req.key = key.to_vec();
+        put_req.value = value.to_vec();
+
+        let put_resp = client.raw_put(&put_req).unwrap();
+        assert!(put_resp.has_region_error());
```
Comment (pingyu) [inline tests/failpoints/cases/test_rawkv.rs:78]: Suggest to also verify the error type.

File: src/storage/txn/commands/atomic_store.rs (hunk 3 above)
Comment (zeminzhou) [reply src/storage/txn/commands/atomic_store.rs]: fixed, thanks!

File: src/storage/txn/commands/compare_and_swap.rs (hunk 4 above)
Comment (zeminzhou) [reply src/storage/txn/commands/compare_and_swap.rs]: fixed, thanks!

File: src/storage/mod.rs (hunk 5 above)
Comment (zeminzhou) [reply src/storage/mod.rs]: I used F::TAG instead of argument, thanks.

File: tests/failpoints/cases/test_rawkv.rs (hunk 6 above)
Comment (zeminzhou) [reply tests/failpoints/cases/test_rawkv.rs]: added, thanks.

File: components/raftstore/src/store/worker/pd.rs [hunk 7]
```diff
@@ -1600,29 +1604,56 @@ where
...
-                                initial_status | 1,
-                                Ordering::SeqCst,
-                                Ordering::SeqCst,
-                            )
-                            .is_ok();
-                        break;
-                    }
-                    Err(e) => {
+                if let Some(causal_ts_provider) = &causal_ts_provider {
+                    if let Err(e) = causal_ts_provider.async_flush().await {
```
[the remark this answers is not in the document]
Comment (zeminzhou) [reply components/raftstore/src/store/worker/pd.rs]: All comments except `test async commit with api v2` have been addressed, thanks for your suggestion,  PTAL~

File: tests/failpoints/cases/test_rawkv.rs [hunk 8]
```diff
@@ -64,6 +64,25 @@ impl TestSuite {
         must_raw_put(&client, ctx, key.to_vec(), value.to_vec())
     }
 
+    pub fn raw_put_err(&mut self, key: &[u8], value: &[u8]) {
```
Comment (pingyu) [inline tests/failpoints/cases/test_rawkv.rs:67]: Suggest:
1. name as `raw_put_err_by_timestamp_not_synced`, or
2. return error and verify outside, to make this method more common.

File: components/raftstore/src/store/worker/pd.rs [hunk 9]
```diff
@@ -1600,22 +1605,42 @@ where
...
+                        initial_status | 1,
+                        Ordering::SeqCst,
+                        Ordering::SeqCst,
+                    )
+                    .is_ok();
+            };
+
             while txn_ext.max_ts_sync_status.load(Ordering::SeqCst) == initial_status {
-                match pd_client.get_tso().await {
+                // `causal_ts_provier` need flush for rawkv apiv2. `causal_ts_provider`
```
[the remark this answers is not in the document]
Comment (zeminzhou) [reply components/raftstore/src/store/worker/pd.rs]: I modified comment, and add test for `test_async_commit_prewrite_with_stale_max_ts`, `test_sync_max_ts_after_region_merge`, `test_sync_max_ts_after_leader_transfer` with API v2, thinks.

[the remark this answers is not in the document]
Comment (zeminzhou) [reply components/raftstore/src/store/worker/pd.rs]: I modified comment, and add test for test_async_commit_prewrite_with_stale_max_ts, test_sync_max_ts_after_region_merge, test_sync_max_ts_after_leader_transfer with API v2, thanks.

File: src/storage/txn/commands/compare_and_swap.rs [hunk 10]
```diff
@@ -74,20 +89,39 @@ impl<S: Snapshot, L: LockManager> WriteCommand<S, L> for RawCompareAndSwap {
                     ApiVersion::API => API::encode_raw_value_owned(raw_value),
                 }
             );
-            if let Some(ts) = self.data_ts {
+
+            let lock_guard = block_on(get_raw_key_guard(&provider, concurrency_manager)).map_err(
+                |err: StorageError| ErrorInner::Other(box_err!("failed to key guard: {:?}", err)),
+            )?;
+            let lock_guards = if let Some(lock_guard) = lock_guard {
```
[the remark this answers is not in the document]
Comment (zeminzhou) [reply src/storage/txn/commands/compare_and_swap.rs]: fixed, thanks!

File: tests/failpoints/cases/test_rawkv.rs (hunk 8 above)
Comment (zeminzhou) [reply tests/failpoints/cases/test_rawkv.rs]: I rename it with `raw_put_err_by_timestamp_not_synced`.

File: src/storage/mod.rs (hunk 2 above)
Comment (zeminzhou) [reply src/storage/mod.rs]: I renamed `check_causal_ts_synced` to `check_causal_ts_flushed`.What do you think?

Comment (haojinming) [reply src/storage/mod.rs]: I‘m ok with it.

File: src/storage/txn/commands/compare_and_swap.rs [hunk 11]
```diff
@@ -52,7 +57,17 @@ impl CommandExt for RawCompareAndSwap {
 }
 
 impl<S: Snapshot, L: LockManager> WriteCommand<S, L> for RawCompareAndSwap {
-    fn process_write(self, snapshot: S, _: WriteContext<'_, L>) -> Result<WriteResult> {
+    fn process_write(self, snapshot: S, wctx: WriteContext<'_, L>) -> Result<WriteResult> {
+        if !snapshot.ext().is_max_ts_synced() {
```
[the remark this answers is not in the document]
Comment (haojinming) [reply src/storage/txn/commands/compare_and_swap.rs]: agreed.

File: components/raftstore/src/store/worker/pd.rs [hunk 12]
```diff
@@ -1616,7 +1641,6 @@ where
                                 Ordering::SeqCst,
                             )
                             .is_ok();
-                        break;
```
Comment (pingyu) [inline components/raftstore/src/store/worker/pd.rs:1619]: The `break` must not be removed.

File: src/storage/mod.rs [hunk 13]
```diff
@@ -1847,47 +1847,34 @@ impl<E: Engine, L: LockManager, F: KvFormat> Storage<E, L, F> {
...
+                return Err(Error::from(txn::Error::from(
+                    TxnError::MaxTimestampNotSynced {
+                        region_id: ctx.get_region_id(),
+                        start_ts: TimeStamp::zero(),
+                    },
+                )));
+            }
+            let term = snapshot.ext().get_term();
+            if let Some(term) = term {
+                ctx.set_term(term.get());
```
Comment (pingyu) [inline src/storage/mod.rs:1868]: Why we need `set_term` here ? And there is no this block in atomic commands.

File: tests/failpoints/cases/test_storage.rs [hunk 14]
```diff
@@ -509,7 +509,15 @@ fn test_pipelined_pessimistic_lock() {
 
 #[test]
 fn test_async_commit_prewrite_with_stale_max_ts() {
-    let mut cluster = new_server_cluster(0, 2);
+    test_kv_format_impl!(test_async_commit_prewrite_with_stale_max_ts_impl);
```
Comment (pingyu) [inline tests/failpoints/cases/test_storage.rs:512]: Suggest to write as other test cases do (see [here](https://github.com/tikv/tikv/blob/a68a44e09dd4ef7de59db22b11593e7abd4e94df/src/storage/mod.rs#L7039)):
```
test_async_commit_prewrite_with_stale_max_ts_impl::<ApiV1>();
test_async_commit_prewrite_with_stale_max_ts_impl::<ApiV2>();
```

File: src/storage/mod.rs (hunk 13 above)
Comment (zeminzhou) [reply src/storage/mod.rs:1868]: For ABA, if event `leader tranfer from A to B` & `leader tranfer from B to A` happend between after `check_causal_ts_flushed` and before `raft propose`. For atomic commands, ref[ here](https://github.com/tikv/tikv/blob/master/src/storage/txn/scheduler.rs#L599)

File: components/raftstore/src/store/worker/pd.rs (hunk 12 above)
Comment (zeminzhou) [reply components/raftstore/src/store/worker/pd.rs]: added back, thanks

File: tests/failpoints/cases/test_storage.rs (hunk 14 above)
Comment (zeminzhou) [reply tests/failpoints/cases/test_storage.rs]: fixed, thanks for your suggestion, PTAL~

File: src/storage/mod.rs (hunk 13 above)
Comment (pingyu) [reply src/storage/mod.rs:1868]: Got it.

**Review by pingyu — APPROVED** [review]
LGTM~

File: tests/failpoints/cases/test_storage.rs [hunk 15]
```diff
@@ -541,15 +547,15 @@ fn test_async_commit_prewrite_with_stale_max_ts() {
         storage
             .sched_txn_command(
                 commands::Prewrite::new(
-                    vec![Mutation::make_put(Key::from_raw(b"k1"), b"v".to_vec())],
-                    b"k1".to_vec(),
+                    vec![Mutation::make_put(Key::from_raw(b"xk1"), b"v".to_vec())],
```
Comment (BusyJay) [inline tests/failpoints/cases/test_storage.rs:550]: Why the change?

File: components/causal_ts/src/lib.rs [hunk 16]
```diff
@@ -31,22 +30,22 @@ pub trait CausalTsProvider: Send + Sync {
         block_on(self.async_get_ts())
     }
 
-    /// Flush (cached) timestamps to keep causality on some events, such as
-    /// "leader transfer".
-    fn flush(&self) -> Result<()> {
+    /// Flush (cached) timestamps and return first timestamp to keep causality
+    /// on some events, such as "leader transfer".
+    fn flush(&self) -> Result<TimeStamp> {
```
Comment (BusyJay) [inline components/causal_ts/src/lib.rs:35]: Is it still used?

File: tests/failpoints/cases/test_storage.rs (hunk 15 above)
Comment (zeminzhou) [reply tests/failpoints/cases/test_storage.rs:550]: Txn key must start with 'x' in ApiV2.

File: components/causal_ts/src/lib.rs (hunk 16 above)
Comment (zeminzhou) [reply components/causal_ts/src/lib.rs:35]: backup component need it, ref [here](https://github.com/tikv/tikv/blob/master/components/backup/src/endpoint.rs#L985).

Comment (BusyJay) [reply components/causal_ts/src/lib.rs:35]: How about inlining  the implementation? So users may not misuse the function.

File: src/storage/mod.rs [hunk 17]
```diff
@@ -2614,22 +2628,13 @@ impl<E: Engine, L: LockManager, F: KvFormat> Storage<E, L, F> {
         }
         let provider = self.causal_ts_provider.clone();
         let sched = self.get_scheduler();
-        let concurrency_manager = self.get_concurrency_manager();
         self.sched_raw_command(CMD, async move {
             // Raw atomic cmd has two locks, one is concurrency_manager and the other is txn
```
Comment (BusyJay) [inline src/storage/mod.rs:2632]: These comments may not be in the correct place anymore.

File: src/storage/txn/commands/atomic_store.rs [hunk 18]
```diff
@@ -41,10 +49,27 @@ impl CommandExt for RawAtomicStore {
...
+            return Err(ErrorInner::MaxTimestampNotSynced {
+                region_id: self.ctx.get_region_id(),
+                start_ts: TimeStamp::zero(),
+            }
+            .into());
+        }
+
+        let provider = self.causal_ts_provider.clone();
+        let concurrency_manager = wctx.concurrency_manager;
+        let lock_guard = block_on(get_raw_key_guard(&provider, concurrency_manager)).map_err(
```
Comment (BusyJay) [inline src/storage/txn/commands/atomic_store.rs:63]: Why block?

File: src/storage/mod.rs (hunk 17 above)
Comment (zeminzhou) [reply src/storage/mod.rs:2632]: Yesh, these comments should be moved, thanks!

File: src/storage/txn/commands/atomic_store.rs (hunk 18 above)
Comment (zeminzhou) [reply src/storage/txn/commands/atomic_store.rs:63]: Because `get_raw_key_guard` is a async func.

File: components/causal_ts/src/lib.rs (hunk 16 above)
Comment (zeminzhou) [reply components/causal_ts/src/lib.rs:35]: Why `#[inline]` can prevent users from misusing？
I try to understand that call `block_on` in a async func is not illegal, but call `block_on` in a sync func is illegal even if the sync func is called in a async func. So we can use `#[inline]`  to prevent users misusing. Am I understanding that right?

Comment (zeminzhou) [reply components/causal_ts/src/lib.rs:35]: Based on the above, I try to add `#[inline(always)]` for `get_ts`, and call `get_ts` in [a async func](https://github.com/tikv/tikv/blob/master/components/cdc/src/endpoint.rs#L1028), but I don't get error. Now, I am confused.

Comment (BusyJay) [reply components/causal_ts/src/lib.rs:35]: What I mean is calling `block_on(async_flush())` instead of calling `flush`, so that `flush` can be removed.

File: src/storage/txn/commands/atomic_store.rs (hunk 18 above)
Comment (BusyJay) [reply src/storage/txn/commands/atomic_store.rs:63]: I don't think it's a good implementation. Blocking the thread can starve all the other tasks.

File: components/causal_ts/src/lib.rs (hunk 16 above)
Comment (zeminzhou) [reply components/causal_ts/src/lib.rs]: Allright, I removed it, thanks!

File: src/storage/txn/commands/mod.rs [hunk 19]
```diff
@@ -526,12 +526,15 @@ pub trait CommandExt: Display {
     fn gen_lock(&self) -> latch::Lock;
 }
 
+type ApiV2Context = (Option<TimeStamp>, Option<KeyHandleGuard>);
```
Comment (pingyu) [inline src/storage/txn/commands/mod.rs:529]: Suggest:
```rust
struct RawExt {
    pub ts: Timestamp,
    pub key_guard: KeyHandleGuard,
}
```

File: src/storage/txn/scheduler.rs [hunk 20]
```diff
@@ -1238,6 +1263,41 @@ impl<E: Engine, L: LockManager> Scheduler<E, L> {
...
+                    .map_err(|err: StorageError| {
+                        ErrorInner::Other(box_err!("failed to key guard: {:?}", err))
+                    })?;
+                let ts =
+                    get_causal_ts(&causal_ts_provider)
+                        .await
+                        .map_err(|err: StorageError| {
+                            ErrorInner::Other(box_err!("failed to get casual ts: {:?}", err))
+                        })?;
+                return Ok((ts, lock_guard));
```
Comment (pingyu) [inline src/storage/txn/scheduler.rs:1293]: `ts` & `lock_guard` must be `Some()` here.
Suggest to try using just one tier of `Option`. Two tier is a little too complicated.
`raw_ext: Option<RawExt {TimeStamp, KeyHandleGuard}>` or `raw_ext: RawExt {Option<TimeStamp>, Option<KeyHandleGuard>}`

File: src/storage/txn/commands/mod.rs [hunk 21]
```diff
@@ -526,12 +526,15 @@ pub trait CommandExt: Display {
...
+
 pub struct WriteContext<'a, L: LockManager> {
     pub lock_mgr: &'a L,
     pub concurrency_manager: ConcurrencyManager,
     pub extra_op: ExtraOp,
     pub statistics: &'a mut Statistics,
     pub async_apply_prewrite: bool,
+    pub apiv2_ctx: Option<ApiV2Context>, // use for apiv2
```
Comment (pingyu) [inline src/storage/txn/commands/mod.rs:537]: `apiv2_ctx` -> `raw_ext`.

File: src/storage/txn/commands/atomic_store.rs [hunk 22]
```diff
@@ -103,15 +101,17 @@ mod tests {
...
         let mut statistic = Statistics::default();
         let snap = engine.snapshot(Default::default()).unwrap();
+        let apiv2_ctx = super::super::test_util::get_apiv2_ctx(F::TAG);
         let context = WriteContext {
             lock_mgr: &DummyLockManager {},
             concurrency_manager: cm,
             extra_op: kvproto::kvrpcpb::ExtraOp::Noop,
             statistics: &mut statistic,
             async_apply_prewrite: false,
+            apiv2_ctx,
```
Comment (pingyu) [inline src/storage/txn/commands/atomic_store.rs:114]: Suggest to also verify the `key_guard` field.

File: src/storage/txn/commands/mod.rs [hunk 23]
```diff
@@ -925,11 +931,20 @@ pub mod test_util {
...
+            apiv2_ctx: None,
         };
 
         let ret = cmd.cmd.process_write(snap, context)?;
         let ctx = Context::default();
         engine.write(&ctx, ret.to_be_write).unwrap();
         Ok(())
     }
+
+    pub fn get_apiv2_ctx(api_version: ApiVersion) -> Option<ApiV2Context> {
```
Comment (pingyu) [inline src/storage/txn/commands/mod.rs:943]: Suggest to name as `mock_raw_ext`, to make it explicitly different with the real one.

File: src/storage/txn/commands/atomic_store.rs [hunk 24]
```diff
@@ -124,7 +127,7 @@ mod tests {
             };
             modifies_with_ts.push(Modify::Put(
                 CF_DEFAULT,
-                F::encode_raw_key_owned(raw_keys[i].to_vec(), encode_ts),
+                F::encode_raw_key_owned(raw_keys[i].to_vec(), Some(100.into())),
```
Comment (pingyu) [inline src/storage/txn/commands/atomic_store.rs:130]: Suggest to also verify the `lock_guards` of `write_result`.

File: src/storage/txn/commands/mod.rs [hunk 25]
```diff
@@ -925,11 +935,31 @@ pub mod test_util {
...
         engine.write(&ctx, ret.to_be_write).unwrap();
         Ok(())
     }
+
+    pub async fn mock_raw_ext(
+        api_ver: ApiVersion,
+        concurrency_manager: ConcurrencyManager,
+    ) -> Option<RawExt> {
+        if api_ver == ApiVersion::V2 {
+            let raw_key = vec![api_version::api_v2::RAW_KEY_PREFIX];
```
Comment (pingyu) [inline src/storage/txn/commands/mod.rs:952]: Suggest to reuse `get_raw_key_guard`. Then we can also verify the `get_raw_key_guard` here.

File: src/storage/txn/commands/compare_and_swap.rs [hunk 26]
```diff
@@ -1,12 +1,13 @@
 // Copyright 2021 TiKV Project Authors. Licensed under Apache-2.0.
 
 // #[PerformanceCriticalPath]
+
```
Comment (pingyu) [inline src/storage/txn/commands/compare_and_swap.rs:4]: Revert unnecessary new line.

File: src/storage/txn/commands/compare_and_swap.rs [hunk 27]
```diff
@@ -240,23 +251,24 @@ mod tests {
...
             statistics: &mut statistic,
             async_apply_prewrite: false,
+            raw_ext,
         };
         let cmd: Command = cmd.into();
         let write_result = cmd.process_write(snap, context).unwrap();
         let modifies_with_ts = vec![Modify::Put(
             CF_DEFAULT,
-            F::encode_raw_key(raw_key, encode_ts),
+            F::encode_raw_key(raw_key, Some(100.into())),
```
Comment (pingyu) [inline src/storage/txn/commands/compare_and_swap.rs:271]: Suggest to also verify `write_result.lock_guards`.

**Review by pingyu — COMMENTED** [review]
Please consider to enhance [`test_atomic_cas_lock_by_latch`](https://github.com/tikv/tikv/blob/c48b0cfa8630d949a6e32a14a74fad7fdbc78c02/tests/failpoints/cases/test_storage.rs#L1125) for API v2 scenario, with additional failpoint test for `!is_max_ts_synced`, `async_get_ts` failed, etc (maybe in another PR, as this PR is already big).
Also consider to add similar test for `RawStore` command.

File: src/storage/txn/commands/atomic_store.rs (hunk 18 above)
Comment (zeminzhou) [reply src/storage/txn/commands/atomic_store.rs]: Thanks for such a good suggestion, I removed block by removing `asynchronous operation` from atomic_store's `process_write` to scheduler's `[process_write](https://github.com/zeminzhou/tikv/blob/new-flush-for-causalts/src/storage/txn/scheduler.rs#L859)` . PTAL~

File: src/storage/txn/scheduler.rs [hunk 28]
```diff
@@ -843,16 +850,34 @@ impl<E: Engine, L: LockManager> Scheduler<E, L> {
         let pipelined =
             task.cmd.can_be_pipelined() && pessimistic_lock_mode == PessimisticLockMode::Pipelined;
         let txn_ext = snapshot.ext().get_txn_ext().cloned();
+        let max_ts_synced = snapshot.ext().is_max_ts_synced();
+        let causal_ts_provider = self.inner.causal_ts_provider.clone();
+        let concurrency_manager = self.inner.concurrency_manager.clone();
+
+        let apiv2_ctx = get_apiv2_ctx(
```
[the remark this answers is not in the document]
Comment (zeminzhou) [reply src/storage/txn/scheduler.rs]: I renamed it, thanks!

File: src/storage/txn/scheduler.rs [hunk 29]
```diff
@@ -1238,6 +1263,41 @@ impl<E: Engine, L: LockManager> Scheduler<E, L> {
     }
 }
 
+async fn get_apiv2_ctx(
```
[the remark this answers is not in the document]
Comment (zeminzhou) [reply src/storage/txn/scheduler.rs]: I renamed it, thanks!

File: src/storage/txn/commands/mod.rs (hunk 19 above)
Comment (zeminzhou) [reply src/storage/txn/commands/mod.rs]: good suggestion, thanks!

File: src/storage/txn/scheduler.rs [hunk 30]
```diff
@@ -843,16 +852,34 @@ impl<E: Engine, L: LockManager> Scheduler<E, L> {
...
+
+        let raw_ext = get_raw_ext(
+            causal_ts_provider,
+            concurrency_manager.clone(),
+            max_ts_synced,
+            &task.cmd,
+        )
+        .await;
+        if let Err(err) = raw_ext {
+            debug!("get apiv2 context failed"; "cid" => cid, "err" => ?err);
```
[the remark this answers is not in the document]
Comment (zeminzhou) [reply src/storage/txn/scheduler.rs:867]: fixed, thanks!

File: src/storage/txn/commands/mod.rs (hunk 25 above)
Comment (zeminzhou) [reply src/storage/txn/commands/mod.rs]: yesh, I reused it for compare_and_swap test case and atomic_store test case, thinks!

File: src/storage/txn/commands/compare_and_swap.rs (hunk 26 above)
Comment (zeminzhou) [reply src/storage/txn/commands/compare_and_swap.rs]: removed, thanks.

File: src/storage/txn/commands/mod.rs (hunk 21 above)
Comment (zeminzhou) [reply src/storage/txn/commands/mod.rs]: renamed, thanks!

File: src/storage/txn/scheduler.rs (hunk 20 above)
Comment (zeminzhou) [reply src/storage/txn/scheduler.rs]: fixed, thanks.

File: components/causal_ts/src/tso.rs [hunk 31]
```diff
@@ -900,8 +918,8 @@ pub mod tests {
         assert_eq!(provider.tso_remain(), 0);
         assert_eq!(provider.tso_usage(), 100);
 
-        provider.flush().unwrap(); // allocated: [1201, 2200]
-        for ts in 1201..=1260u64 {
+        assert_eq!(provider.flush().unwrap(), TimeStamp::from(1201)); // allocated: [1101, 1200]
```
[the remark this answers is not in the document]
Comment (zeminzhou) [reply components/causal_ts/src/tso.rs]: fixed, thanks!

**Review by BusyJay — COMMENTED** [review]
Generally LGTM

**Review by pingyu — COMMENTED** [review]
LGTM~
