### PR TITLE
config: support configuring rocksdb enum item with string literals

### LINKED ISSUE #11028: `compaction-style` setting is broken
### What version of TiKV are you using?

using tiup for deployment.
```
TiKV
Release Version:   5.2.1
Edition:           Community
Git Commit Hash:   2c99f317d4ba125b772a8b94a6c3c0eb9d07ac59
Git Commit Branch: heads/refs/tags/v5.2.1
UTC Build Time:    2021-09-08 02:32:36
Rust Version:      rustc 1.56.0-nightly (2faabf579 2021-07-27)
Enable Features:   jemalloc mem-profiling portable sse protobuf-codec test-engines-rocksdb cloud-aws cloud-gcp
Profile:           dist_release
```

### What operating system and CPU are you using?

It seems to be a machine-independent bug.

### Steps to reproduce

The server will not start if the following settings are made.

```yaml
# tiup-topology.yaml
server_configs:
  # tidb:
  tikv:
    rocksdb:
      defaultcf:
        compaction-style: universal
```

```toml
# /opt/tidb/deploy/tikv-20160/conf/tikv.toml
[rocksdb]
[rocksdb.defaultcf]
compaction-style = "universal"
```

```
Error: init config failed: 192.168.50.3:20160: executor.ssh.execute_failed: Failed to execute command over SSH for '********@********:22' {ssh_stderr: thread 'main' panicked at 'invalid auto generated configuration file /opt/tidb/deploy/tikv-20160/conf/tikv.toml, err invalid type: string "level", expected valid DBCompactionStyle for key `rocksdb.defaultcf.compaction-style` at line 10 column 20', src/config.rs:2836:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
, ssh_stdout: , ssh_command: export LANG=C; PATH=$PATH:/bin:/sbin:/usr/bin:/usr/sbin /opt/tidb/deploy/tikv-20160/bin/tikv-server --config-check --config=/opt/tidb/deploy/tikv-20160/conf/tikv.toml --pd "" --data-dir "/opt/tidb/data/tikv-20160"}, cause: Process exited with status 101: check config failed
```

### What did you expect?

The reference looks like a correct description.
https://docs.pingcap.com/tidb/stable/tikv-configuration-file#compaction-style

### What did happened?

If specify `compaction-style: 1`, it appears to start successfully.

### PR DESCRIPTION
**Pull request by yuqi1129**
Signed-off-by: yuqi1129 <yuqi4733@gmail.com>

### What problem does this PR solve?

Issue Number: close #11028 

Problem Summary:

### What is changed and how it works?

1.  Change macro `numeric_enum_mod` and add method `visit_string` to support string-like value about configuration of `DBCompactionStyle`、DBRateLimiterMode` and so on. 

2. Add mirror struct of `DBCompactionStyle`, `DBRateLimiterMode` etc.

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- PR to update `pingcap/tidb-ansible`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

```release-note
 None.
```

### CODE REVIEW

**Comment by yuqi1129** [comment]
@tabokie OK, Thanks for your comment and suggestion, i will take this suggestions and resolve the problem in CI test

**Comment by yuqi1129** [comment]
@tabokie Can you help to review again ?

**Comment by tabokie** [comment]
@yuqi1129 Added a comment about the macro part, you should try squeezing more codes into the macro.

BTW you should write `ref #11028` in one of your new commits' message, because we recently install a format checker in @ti-chi-bot. And for the third time😭, please please write something other than the PR title in your commit message. You can check on [one](https://github.com/tikv/tikv/pull/10945) of @brson 's PRs for best practice.

File: components/engine_rocks/src/config.rs [hunk 1]
```diff
@@ -334,31 +354,80 @@ macro_rules! numeric_enum_mod {
...
 }
 
+#[derive(Copy, Clone, Debug, PartialEq, Serialize, Deserialize)]
+#[serde(rename_all = "kebab-case")]
+pub enum CompactionPriority {
+    ByCompensatedSize = 0,
+    OldestLargestSeqFirst = 1,
+    OldestSmallestSeqFirst = 2,
+    MinOverlappingRatio = 3,
+}
```
[the remark this answers is not in the document]
Comment (tabokie) [reply components/engine_rocks/src/config.rs:364]: And rename `numeric_enum_mod` to something like `impl_enum_mirror_type`

File: components/engine_rocks/Cargo.toml [hunk 2]
```diff
@@ -47,6 +47,7 @@ kvproto = { git = "https://github.com/pingcap/kvproto.git" }
 raft = { version = "0.6.0-alpha", default-features = false, features = ["protobuf-codec"] }
 protobuf = "2"
 fail = "0.4"
+case_macros = {path = "../case_macros", default-features = false}
```
Comment (tabokie) [inline components/engine_rocks/Cargo.toml:50]:
```suggestion
case_macros = { path = "../case_macros" }
```

File: components/engine_rocks/src/config.rs (hunk 1 above)
[the remark this answers is not in the document]
Comment (yuqi1129) [reply components/engine_rocks/src/config.rs:364]: > Can put these inside macro too 

You mean we can put the definition of enums like `CompactionPriority ` inside the macro `numeric_enum_mod`

>  And rename numeric_enum_mod to something like impl_enum_mirror_type

Reasonable. Since this enum not only support numberic value when deserialization, we need to change it to a more proper name

File: components/engine_rocks/Cargo.toml (hunk 2 above)
Comment (yuqi1129) [reply components/engine_rocks/Cargo.toml:50]: OK

File: components/engine_rocks/src/config.rs [hunk 3]
```diff
@@ -263,51 +262,76 @@ impl From<BlobRunMode> for DBTitanDBBlobRunMode {
...
+                $($variant = $value, )*
+            }
+
+            impl From<$enum> for T {
+                fn from(m: $enum) -> Self {
+                    match m {
+                        $( $enum::$variant => T::$variant, )*
+                    }
+                }
+            }
```
Comment (tabokie) [inline components/engine_rocks/src/config.rs:285]: Oh, seems I was wrong. We don't actually need this anymore. Because we don't actually use the mirror type in other modules.

File: components/engine_rocks/src/config.rs [hunk 4]
```diff
@@ -263,51 +262,76 @@ impl From<BlobRunMode> for DBTitanDBBlobRunMode {
     }
 }
 
-macro_rules! numeric_enum_mod {
+macro_rules! impl_enum_with_mirror_type_mod {
```
Comment (tabokie) [inline components/engine_rocks/src/config.rs:265]: Then this should be rocksdb_enum_mod

File: src/config.rs [hunk 5]
```diff
@@ -4318,4 +4318,38 @@ mod tests {
...
+    }
+
+    #[test]
+    #[should_panic]
+    fn test_bad_compaction_style2() {
+        let bad_string_config = r#"
+            compaction-style = 4
+        "#;
+        let _: DefaultCfConfig = toml::from_str(bad_string_config).unwrap();
+    }
```
Comment (tabokie) [inline src/config.rs:4354]: You can put these three tests into one test case. And use `panic_hook::recover_safe` instead of `#[should_panic]` to catch panics more accurately.

Comment (yuqi1129) [reply src/config.rs:4354]: Ok, thanks

File: components/engine_rocks/src/config.rs (hunk 3 above)
Comment (yuqi1129) [reply components/engine_rocks/src/config.rs:285]: Nice, i will reduce the code again

**Comment by yuqi1129** [comment]
@tabokie I have resolved all the comments, Could you have a look again?   Thanks for your patience for this simple issue :joy:

**Review by tabokie — APPROVED** [review]
LGTM

**Review by tabokie — COMMENTED** [review]
BTW, you should change config-template.toml and the `test_custom` test to use string. It's the recommended way now.

**Comment by yuqi1129** [comment]
@tabokie  
> BTW, you should change config-template.toml and the test_custom test to use string. It's the recommended way now.

Done

File: etc/config-template.toml [hunk 6]
```diff
@@ -558,14 +558,14 @@
...
-##    3 : AllIo
+##    "read-only"
+##    "write-only"
+##    "all-io"
 ## 4. rate-limiter-auto_tuned enables dynamic adjustment of rate limit within the range
 ##    [10MB/s, rate_bytes_per_sec], according to the recent demand for background I/O.
 # rate-bytes-per-sec = "10GB"
 # rate-limiter-refill-period = "100ms"
-# rate-limiter-mode = 2
+# rate-limiter-mode = "all-io"
```
Comment (tabokie) [inline etc/config-template.toml:568]:
```suggestion
# rate-limiter-mode = "write-only"
```

Comment (yuqi1129) [reply etc/config-template.toml]: :rofl:, Except `DBRateLimiterMode`, all enum start from 0, `DBRateLimiterMode` starts from 1

**Comment by yuqi1129** [comment]
@Connor1996 , Can you take time to help review this PR

**Review by Connor1996 — COMMENTED** [review]
It will break the forward compatibility. Seems we should discuss with PM first. @tabokie

**Comment by tabokie** [comment]
> It will break the forward compatibility. Seems we should discuss with PM first. @tabokie

@Connor1996 No, it still supports numeric values. (`deserialize_any`)

File: src/config.rs [hunk 7]
```diff
@@ -4318,4 +4318,41 @@ mod tests {
...
+        // Test backward compatibility with numeric value
+        let normal_string_config = r#"
+            compaction-style = 1
+        "#;
+        let config: DefaultCfConfig = toml::from_str(normal_string_config).unwrap();
+        assert_eq!(config.compaction_style, DBCompactionStyle::Universal);
+        assert!(
+            toml::to_string(&config)
+                .unwrap()
+                .contains("compaction-style = \"universal\"")
```
Comment (Connor1996) [inline src/config.rs:4339]: it will deserialize to a string, and older versions can't recognize that. @tabokie

**Comment by yuqi1129** [comment]
You mean we should consider compatibility when downgrating?

Connor ***@***.***>于2021年11月10日 周三18:03写道：

File: src/config.rs (hunk 7 above)
Comment (tabokie) [reply src/config.rs:4339]: Ok, then let's serialize to integers. @yuqi1129

Comment (Connor1996) [reply src/config.rs:4339]: I'm not sure if it's really necessary, just to notice you discuss with PM first.

Comment (tabokie) [reply src/config.rs:4339]: Storing integers is better. I don't want to break anything even if rolling back major version isn't mandatory.

Comment (yuqi1129) [reply src/config.rs:4339]: If we just use Integers, this PR seems to be redundant. After all if we revert to integer, this issue only make one change: configuration values can accept both numeric or string value. Under this circumstance, All we need to do is just to change the user doc.

Comment (tabokie) [reply src/config.rs:4339]: No, serializing to integer doesn't mean we don't accept strings. It's just keeping a copy of configuration as integer, in `last_tikv.toml`. This way, if user didn't specify these configs in `tikv.toml`, it can rollback without problem.

See https://github.com/tikv/tikv/blob/5552758d277b0ab2761deb88c9a82525ecac8980/src/config.rs#L2918

**Comment by tabokie** [comment]
Pin @Connor1996

File: src/config.rs [hunk 8]
```diff
@@ -4318,4 +4318,41 @@ mod tests {
             assert_eq!(Module::from(name), module);
         }
     }
+
+    #[test]
+    fn test_compaction_style() {
+        let normal_string_config = r#"
+            compaction-style = 1
```
Comment (Connor1996) [inline src/config.rs:4325]:
```suggestion
            compaction-style = "universal"
```

File: src/config.rs [hunk 9]
```diff
@@ -4318,4 +4318,41 @@ mod tests {
...
+        "#;
+        let config: DefaultCfConfig = toml::from_str(normal_string_config).unwrap();
+        assert_eq!(config.compaction_style, DBCompactionStyle::Universal);
+
+        // Test backward compatibility with numeric value
+        let normal_string_config = r#"
+            compaction-style = "universal"
```
Comment (Connor1996) [inline src/config.rs:4332]:
```suggestion
            compaction-style = 1
```

File: src/config.rs [hunk 10]
```diff
@@ -4318,4 +4318,41 @@ mod tests {
...
+
+    #[test]
+    fn test_compaction_style() {
+        let normal_string_config = r#"
+            compaction-style = 1
+        "#;
+        let config: DefaultCfConfig = toml::from_str(normal_string_config).unwrap();
+        assert_eq!(config.compaction_style, DBCompactionStyle::Universal);
+
+        // Test backward compatibility with numeric value
```
Comment (Connor1996) [inline src/config.rs:4330]: the comment should be updated

Comment (yuqi1129) [reply src/config.rs:4330]: 👌 :

**Comment by yuqi1129** [comment]
Pin @Connor1996

**Review by Connor1996 — APPROVED** [review]
LGTM

**Comment by tabokie** [comment]
@yuqi1129 You need to change [the configuration docs](https://github.com/pingcap/docs/blob/master/tikv-configuration-file.md) later.
1. Update master branch to use string literals
2. Update the compaction-style docs in 5.2 branch to use integers, and cherry-pick to every release versions after 3.0

**Comment by yuqi1129** [comment]
@tabokie  Got it
