### PR TITLE
local_reader: solve the race condition when acquiring the snapshot

### LINKED ISSUE #13553: Batch snapshot is unsound
### What version of TiKV are you using?
Nightly

### What operating system and CPU are you using?
Doesn't matter

### Steps to reproduce
Concurrent read and conf change may read incomplete data.

### What did happened?
https://github.com/tikv/tikv/pull/7878 introduces batch snapshot across regions. It reorders the snapshot operation and lease check operation, so snapshot is taken after checking lease. It's possible that after checking the lease and before snapshot is taken, the region is removed by conf change. So the snapshot may not contain the complete data.

To solve the problems, we need to make sure snapshot is taken before lease check.

/cc @hicqu

### PR DESCRIPTION
**Pull request by SpadeA-Tang**
### What is changed and how it works?

Issue Number: Close #13553

What's Changed:

The current code encounters the case that after passing the lease check and before the acquiring the snapshot, the lease expires.
This PR fixes it by implementing `SnapCacheContext` which ensures the timestamp used for the lease check is generated before the snapshot acquisition.

### Check List 

Tests 

- Unit test
- Integration test

### Release note 

```release-note
None
```

### CODE REVIEW

File: tests/failpoints/cases/test_local_read.rs [hunk 1]
```diff
@@ -0,0 +1,59 @@
...
+    let mut req = new_request(
+        region_id,
+        region.get_region_epoch().clone(),
+        vec![new_snap_cmd()],
+        false,
+    );
+    req.mut_header().set_peer(leader);
+
+    let (cb, rx) = make_cb(&req);
+    let handle = thread::spawn(move || {
```
Comment (BusyJay) [inline tests/failpoints/cases/test_local_read.rs:46]: If using `new_server_cluster`, you don't need to spawn a new thread.

File: tests/failpoints/cases/test_local_read.rs [hunk 2]
```diff
@@ -0,0 +1,59 @@
...
+        thread::sleep(Duration::from_millis(200));
+        // This is equivalent to expiring the lease
+        fail::cfg("local_reader_fail_lease_check", "return").unwrap();
+        fail::cfg("before_execute_get_snapshot", "off").unwrap();
+    });
+    cluster.sim.wl().async_read(node_id, None, req, cb);
+
+    // Request should be redirected to the raftstore, but the failpoint above makes
+    // it just return. So cb will not be called.
+    let _ = rx.recv_timeout(Duration::from_secs(5)).unwrap_err();
```
Comment (BusyJay) [inline tests/failpoints/cases/test_local_read.rs:56]: Should test on the result instead of code path. Code path can be changed, optimized, but the result should stay the same.

File: components/raftstore/src/store/worker/read.rs [hunk 3]
```diff
@@ -763,20 +867,22 @@ where
...
                         };
-                        if !delegate.is_in_leader_lease(snapshot_ts) {
+
+                        let mut snap_cache_ctx =
+                            SnapCacheContext::new(&mut self.snap_cache, read_id);
+                        snap_cache_ctx.maybe_update_snapshot(delegate.get_tablet());
+
+                        let region = Arc::clone(&delegate.region);
+                        let response =
+                            delegate.execute(&req, &region, None, Some(&mut snap_cache_ctx));
```
Comment (BusyJay) [inline components/raftstore/src/store/worker/read.rs:877]: Should check lease before executing requests.

File: tests/failpoints/cases/test_local_read.rs (hunk 1 above)
Comment (SpadeA-Tang) [reply tests/failpoints/cases/test_local_read.rs]: Good suggestion.

File: tests/failpoints/cases/test_local_read.rs (hunk 2 above)
Comment (SpadeA-Tang) [reply tests/failpoints/cases/test_local_read.rs]: Good catch.

File: components/raftstore/src/store/worker/read.rs (hunk 3 above)
Comment (SpadeA-Tang) [reply components/raftstore/src/store/worker/read.rs]: Good catch.

File: components/raftstore/src/store/worker/read.rs [hunk 4]
```diff
@@ -208,12 +214,80 @@ where
...
 
 /// #[RaftstoreCommon]: LocalReadContext combines some LocalReader's fields for temporary usage.
-pub struct LocalReadContext<'a, E>
+pub struct SnapCacheContext<'a, E>
 where
     E: KvEngine,
 {
-    read_id: &'a mut ThreadReadId,
-    snap_cache: &'a mut Box<Option<Arc<E::Snapshot>>>,
+    // read_id: &'a mut ThreadReadId,
```
Comment (TonsnakeLin) [inline components/raftstore/src/store/worker/read.rs:221]: The comments and code are not corresponded

Comment (SpadeA-Tang) [reply components/raftstore/src/store/worker/read.rs]: Good catch. I forget to update it.

File: components/raftstore/src/store/worker/read.rs [hunk 5]
```diff
@@ -207,13 +213,80 @@ where
...
+pub struct SnapshotContext<'a, E>
 where
     E: KvEngine,
 {
-    read_id: &'a mut ThreadReadId,
-    snap_cache: &'a mut Box<Option<Arc<E::Snapshot>>>,
+    read_id: Option<ThreadReadId>,
+    snap_cache: &'a mut SnapCache<E>,
+
+    snapshot: Option<Arc<E::Snapshot>>,
```
Comment (BusyJay) [inline components/raftstore/src/store/worker/read.rs:226]: Why not always update `snap_cache`? What's the point of duplicated definition?

Comment (SpadeA-Tang) [reply components/raftstore/src/store/worker/read.rs]: Good suggestion.

File: components/raftstore/src/store/worker/mod.rs [hunk 6]
```diff
@@ -1,5 +1,4 @@
 // Copyright 2016 TiKV Project Authors. Licensed under Apache-2.0.
-
```
[the remark this answers is not in the document]
Comment (SpadeA-Tang) [reply components/raftstore/src/store/worker/mod.rs]: By accident.

File: components/raftstore-v2/src/operation/query/local.rs [hunk 7]
```diff
@@ -88,8 +88,7 @@ where
 
     fn get_snapshot(
         &mut self,
-        _: Option<ThreadReadId>,
-        _: &mut Option<raftstore::store::LocalReadContext<'_, E>>,
+        _: &mut Option<&mut raftstore::store::LocalReadContext<'_, E>>,
```
Comment (BusyJay) [inline components/raftstore-v2/src/operation/query/local.rs:91]: Bad style. Should import it.

File: tests/failpoints/cases/test_local_read.rs [hunk 8]
```diff
@@ -0,0 +1,81 @@
...
+            .async_remove_peer(region_id, leader)
+            .unwrap()
+            .recv()
+            .unwrap()
+            .get_header()
+            .has_error()
+    );
+
+    // Wait for data to be cleaned
+    thread::sleep(Duration::from_millis(2000));
```
Comment (BusyJay) [inline tests/failpoints/cases/test_local_read.rs:77]: How do you know data is cleaned?

File: components/raftstore/src/store/worker/read.rs [hunk 9]
```diff
@@ -551,8 +646,10 @@ where
     // region id -> ReadDelegate
     // The use of `Arc` here is a workaround, see the comment at `get_delegate`
     pub delegates: LruCache<u64, D>,
-    snap_cache: Box<Option<Arc<E::Snapshot>>>,
-    cache_read_id: ThreadReadId,
+    // snap_cache: Box<Option<Arc<E::Snapshot>>>,
```
Comment (BusyJay) [inline components/raftstore/src/store/worker/read.rs:649]: Why keeping these?

File: components/raftstore/src/store/worker/read.rs [hunk 10]
```diff
@@ -207,13 +213,61 @@ where
...
+        Self {
+            snap_cache,
+            read_id,
+        }
+    }
+
+    // Update the snapshot in the `snap_cache` if the read_id is None or does not
+    // match. When the read_id is None, it ok to just update the snapshot without
+    // touching the `cached_read_id` because only a consecutive requests will
+    // have the same read_id, which means this `cached_read_id` will not be matched
```
Comment (BusyJay) [inline components/raftstore/src/store/worker/read.rs:238]: > which means this `cached_read_id` will not be matched anymore

If that's the case, then clear `cached_read_id` seems also OK.

File: components/raftstore-v2/src/operation/query/local.rs (hunk 7 above)
Comment (SpadeA-Tang) [reply components/raftstore-v2/src/operation/query/local.rs:91]: Done.

File: components/raftstore/src/store/worker/read.rs (hunk 10 above)
Comment (SpadeA-Tang) [reply components/raftstore/src/store/worker/read.rs]: Fine

File: components/raftstore/src/store/worker/read.rs [hunk 11]
```diff
@@ -207,13 +213,66 @@ where
...
+    // match.
+    // When the read_id is None, it means the `snap_cache` has been cleared
+    // before and the `cached_read_id` of it is None because only a consecutive
+    // requests will have the same cache and the cache will be cleared after the
+    // last request of the batch.
+    fn maybe_update_snapshot(&mut self, engine: &E, delegate_last_valid_ts: Timespec) -> bool {
+        if let Some(read_id) = self.read_id.as_ref() {
+            if self.snap_cache.cached_read_id.is_some()
+                && *self.snap_cache.cached_read_id.as_ref().unwrap() == *read_id
+                && self.snap_cache.cached_snapshot_ts >= delegate_last_valid_ts
```
Comment (BusyJay) [inline components/raftstore/src/store/worker/read.rs:245]: Should compare read_id's create time instead of snapshot time. For example, if the snapshot is taken before the peer is created, the check can pass, but no data can be read.

File: components/raftstore/src/store/worker/read.rs [hunk 12]
```diff
@@ -207,13 +213,66 @@ where
...
+    }
+
+    // Update the snapshot in the `snap_cache` if the read_id is None or does not
+    // match.
+    // When the read_id is None, it means the `snap_cache` has been cleared
+    // before and the `cached_read_id` of it is None because only a consecutive
+    // requests will have the same cache and the cache will be cleared after the
+    // last request of the batch.
+    fn maybe_update_snapshot(&mut self, engine: &E, delegate_last_valid_ts: Timespec) -> bool {
+        if let Some(read_id) = self.read_id.as_ref() {
```
[the remark this answers is not in the document]
Comment (SpadeA-Tang) [reply components/raftstore/src/store/worker/read.rs:242]: What if they are both None?

File: components/raftstore/src/store/worker/read.rs [hunk 13]
```diff
@@ -93,8 +100,7 @@ pub trait ReadExecutor<E: KvEngine> {
         msg: &RaftCmdRequest,
         region: &Arc<metapb::Region>,
         read_index: Option<u64>,
-        mut ts: Option<ThreadReadId>,
-        mut read_context: Option<LocalReadContext<'_, E>>,
+        mut snap_cache_ctx: Option<&mut LocalReadContext<'_, E>>,
```
[the remark this answers is not in the document]
Comment (SpadeA-Tang) [reply components/raftstore/src/store/worker/read.rs:103]: Good catch.

File: components/raftstore/src/store/worker/read.rs [hunk 14]
```diff
@@ -207,13 +213,66 @@ where
...
+    E: KvEngine,
+{
+    fn new(snap_cache: &'a mut SnapCache<E>, read_id: Option<ThreadReadId>) -> Self {
+        Self {
+            snap_cache,
+            read_id,
+        }
+    }
+
+    // Update the snapshot in the `snap_cache` if the read_id is None or does not
```
[the remark this answers is not in the document]
Comment (SpadeA-Tang) [reply components/raftstore/src/store/worker/read.rs:235]: Done

File: components/raftstore-v2/src/operation/query/local.rs [hunk 15]
```diff
@@ -86,11 +86,7 @@ where
         self.cached_tablet.latest().unwrap()
     }
 
-    fn get_snapshot(
-        &mut self,
-        _: Option<ThreadReadId>,
-        _: &mut Option<raftstore::store::LocalReadContext<'_, E>>,
-    ) -> Arc<E::Snapshot> {
+    fn get_snapshot(&mut self, _: &mut Option<&mut LocalReadContext<'_, E>>) -> Arc<E::Snapshot> {
```
Comment (TonsnakeLin) [inline components/raftstore-v2/src/operation/query/local.rs:89]: Why changed `&mut Option<LocalReadContext` to ` &mut Option<&mut LocalReadContext` ?

Comment (SpadeA-Tang) [reply components/raftstore-v2/src/operation/query/local.rs]: Good catch. It does not need to be mut now.

File: components/raftstore/src/store/worker/read.rs (hunk 12 above)
[the remark this answers is not in the document]
Comment (tonyxuqqi) [reply components/raftstore/src/store/worker/read.rs:240]: > What if they are both None?

The self.read_id.is_some()

File: components/raftstore/src/store/worker/read.rs [hunk 16]
```diff
@@ -811,6 +879,13 @@ where
                     }
                     _ => unreachable!(),
                 };
+
+                TLS_LOCAL_READ_METRICS.with(|m| m.borrow_mut().local_executed_requests.inc());
```
Comment (tonyxuqqi) [inline components/raftstore/src/store/worker/read.rs:883]: I think these metrics update can be moved to maybe_update_snapshot.
Then no need to handle snap_updated or not

Comment (SpadeA-Tang) [reply components/raftstore/src/store/worker/read.rs:883]: What if lease does not pass?

File: components/raftstore/src/store/worker/read.rs (hunk 12 above)
[the remark this answers is not in the document]
Comment (SpadeA-Tang) [reply components/raftstore/src/store/worker/read.rs]: My bad.

File: components/raftstore/src/store/worker/read.rs (hunk 16 above)
Comment (tonyxuqqi) [reply components/raftstore/src/store/worker/read.rs:882]: > What if lease does not pass?

OK.

**Review by tonyxuqqi — APPROVED** [review]

File: components/raftstore/src/store/worker/read.rs [hunk 17]
```diff
@@ -6,6 +6,7 @@ use std::{
     fmt::{self, Display, Formatter},
     ops::Deref,
     sync::{
+        atomic,
```
Comment (BusyJay) [inline components/raftstore/src/store/worker/read.rs:9]: Should be `atomic::{self, AtomicU64, Ordering}`.

File: components/raftstore/src/store/worker/read.rs [hunk 18]
```diff
@@ -47,22 +48,32 @@ pub trait ReadExecutor {
     type Tablet: KvEngine;
 
     fn get_tablet(&mut self) -> &Self::Tablet;
+
+    /// Get the snapshot fo the tablet.
+    ///
+    /// If the tablet has not been ready, `None` is returned.
```
Comment (BusyJay) [inline components/raftstore/src/store/worker/read.rs:54]:
```suggestion
    /// If the tablet is not ready, `None` is returned.
```

File: components/raftstore/src/store/worker/read.rs [hunk 19]
```diff
@@ -187,13 +199,66 @@ where
...
+        // before and the `cached_read_id` of it is None because only a consecutive
+        // requests will have the same cache and the cache will be cleared after the
+        // last request of the batch.
+
+        if self.read_id.is_some() {
+            if self.snap_cache.cached_read_id == self.read_id
+                && self.read_id.as_ref().unwrap().create_time >= delegate_last_valid_ts
+            {
+                // Cache hit
+                assert!(self.snap_cache.snapshot.as_ref().is_some());
```
Comment (BusyJay) [inline components/raftstore/src/store/worker/read.rs:234]: Useless assert.

File: components/raftstore/src/store/worker/read.rs [hunk 20]
```diff
@@ -187,13 +199,66 @@ where
...
+                return false;
+            }
+
+            self.snap_cache.cached_read_id = self.read_id.clone();
+        } else {
+            // snap_cache should already have been cleared
+            assert!(self.snap_cache.cached_read_id.is_none());
```
Comment (BusyJay) [inline components/raftstore/src/store/worker/read.rs:241]: It's OK if it's not cleared.

File: components/raftstore/src/store/worker/read.rs [hunk 21]
```diff
@@ -566,6 +632,46 @@ impl Progress {
     }
 }
 
+struct SnapCache<E>
+where
+    E: KvEngine,
+{
+    cached_read_id: Option<ThreadReadId>,
+    snapshot: Box<Option<Arc<E::Snapshot>>>,
```
Comment (BusyJay) [inline components/raftstore/src/store/worker/read.rs:640]: Why put it in `Box`?

File: components/raftstore/src/store/worker/read.rs (hunk 17 above)
Comment (SpadeA-Tang) [reply components/raftstore/src/store/worker/read.rs]: Good catch.

File: components/raftstore/src/store/worker/read.rs (hunk 21 above)
Comment (SpadeA-Tang) [reply components/raftstore/src/store/worker/read.rs]: It is insider Box before. I think I can remove it.

File: components/raftstore/src/store/worker/read.rs [hunk 22]
```diff
@@ -837,12 +923,14 @@ where
                             return;
                         }
 
-                        let read_ctx = self.local_read_context();
+                        let mut local_read_ctx =
+                            LocalReadContext::new(&mut self.snap_cache, read_id);
+                        snap_updated = local_read_ctx
+                            .maybe_update_snapshot(delegate.get_tablet(), last_valid_ts);
```
[the remark this answers is not in the document]
Comment (SpadeA-Tang) [reply components/raftstore/src/store/worker/read.rs:929]: It is used before.
And does batch get command support stale read?

File: components/raftstore/src/store/worker/read.rs [hunk 23]
```diff
@@ -1570,111 +1647,100 @@ mod tests {
         let mut delegate = delegate.unwrap();
         let tablet = delegate.get_tablet();
         assert_eq!(kv_engine.as_inner().path(), tablet.as_inner().path());
-        let snapshot = delegate.get_snapshot(read_id_copy, &mut read_context);
+        let snapshot = delegate.get_snapshot(&read_context).unwrap();
```
[the remark this answers is not in the document]
Comment (SpadeA-Tang) [reply components/raftstore/src/store/worker/read.rs:1650]: I think I can simplify this test to test read executor provider only.

File: components/raftstore/src/store/worker/read.rs (hunk 22 above)
[the remark this answers is not in the document]
Comment (BusyJay) [reply components/raftstore/src/store/worker/read.rs:928]: Not sure. Can you find out the answer?

File: components/raftstore/src/store/worker/read.rs [hunk 24]
```diff
@@ -1546,135 +1627,274 @@ mod tests {
...
-        let snapshot = delegate.get_snapshot(read_id_copy, &mut read_context);
+    }
+
+    #[test]
+    fn test_snap_across_regions() {
+        let store_id = 2;
+        let store_meta = Arc::new(Mutex::new(StoreMeta::new(0)));
+        let (_tmp, mut reader, rx) = new_reader("test-local-reader", store_id, store_meta.clone());
+
+        fn prepare_read_delegate(
```
Comment (BusyJay) [inline components/raftstore/src/store/worker/read.rs:1651]: Bad style, should avoid nested function.

File: tests/failpoints/cases/test_local_read.rs [hunk 25]
```diff
@@ -0,0 +1,81 @@
...
+    get_req.set_context(ctx);
+    get_req.key = b"key1".to_vec();
+    let mut receiver = client.raw_get_async(&get_req).unwrap();
+
+    thread::sleep(Duration::from_millis(200));
+
+    let mut peer = leader.clone();
+    cluster.must_transfer_leader(1, new_peer(2, 2));
+    pd_client.must_remove_peer(region_id, leader);
+    peer.id += 1000;
```
Comment (BusyJay) [inline tests/failpoints/cases/test_local_read.rs:67]: Very confusing. If you just want to assign a new ID, then assign it directly instead of adding arbitrary number.

File: components/raftstore/src/store/worker/read.rs [hunk 26]
```diff
@@ -1546,135 +1627,274 @@ mod tests {
...
+            ep.set_conf_ver(1);
+            ep.set_version(3);
+            ep
+        };
+        let term6 = 6;
+
+        // Register region1
+        let pr_ids1 = vec![2, 3, 4];
+        let prs1 = new_peers(store_id, pr_ids1.clone());
+        prepare_read_delegate(
```
Comment (BusyJay) [inline components/raftstore/src/store/worker/read.rs:1705]: Why not just use `new_reader`?

File: components/raftstore/src/store/worker/read.rs [hunk 27]
```diff
@@ -1546,135 +1627,274 @@ mod tests {
...
+                assert_eq!(snap.get_region().id, 2);
+                assert_eq!(
+                    snap.get_snapshot().get_value(b"a1").unwrap().unwrap(),
+                    b"val1"
+                );
+            })),
+        );
+        must_not_redirect_with_read_id(&mut reader, &rx, task, read_id);
+        assert_eq!(
+            TLS_LOCAL_READ_METRICS.with(|m| m.borrow_mut().local_executed_snapshot_cache_hit.get()),
```
Comment (BusyJay) [inline components/raftstore/src/store/worker/read.rs:1780]: Or you can just check if `Arc` is the same by `Arc::ptr_eq`.

File: components/raftstore/src/store/worker/read.rs (hunk 24 above)
Comment (SpadeA-Tang) [reply components/raftstore/src/store/worker/read.rs]: Done

File: tests/failpoints/cases/test_local_read.rs (hunk 25 above)
Comment (SpadeA-Tang) [reply tests/failpoints/cases/test_local_read.rs]: Done

File: components/raftstore/src/store/worker/read.rs (hunk 27 above)
Comment (SpadeA-Tang) [reply components/raftstore/src/store/worker/read.rs]: Done

**Review by BusyJay — APPROVED** [review]
Rest LGTM

File: components/raftstore-v2/src/operation/query/local.rs [hunk 28]
```diff
@@ -386,8 +371,8 @@ impl<'r> SnapRequestInspector<'r> {
             return Ok(RequestPolicy::ReadIndex);
         }
 
-        // If applied index's term is different from current raft's term, leader
-        // transfer must happened, if read locally, we may read old value.
+        // If applied index's term is differ from current raft's term, leader transfer
```
Comment (tonyxuqqi) [inline components/raftstore-v2/src/operation/query/local.rs:374]: minor: is differ --> differs

File: components/raftstore/src/store/worker/read.rs (hunk 22 above)
[the remark this answers is not in the document]
Comment (SpadeA-Tang) [reply components/raftstore/src/store/worker/read.rs:927]: `batch_get_command` will set read_id be None for stale read so it will not use cache.
