### PR TITLE
encryption: Fix errors related to file ingestion

### LINKED ISSUE #7785: encryption: failed to apply snap: SstImporter file already exists
### What version of TiKV are you using?

```
/ # ./tikv-server -V
TiKV
Release Version:   4.1.0-alpha
Git Commit Hash:   1bdab7bf652b1663d707725decc15114cf7d4c5a
Git Commit Branch: master
UTC Build Time:    2020-05-06 07:21:28
Rust Version:      rustc 1.42.0-nightly (0de96d37f 2019-12-19)
Enable Features:   jemalloc portable sse protobuf-codec
Profile:           dist_release
```
### What operating system and CPU are you using?

run in contianer
### Steps to reproduce

can't reproduce currently
### What did you expect?
tikv is works well
### What did happened?
tikv report error 
```
[2020/05/06 13:25:03.147 +00:00] [FATAL] [lib.rs:483] ["[region 18] 34 applying snapshot failed"] [backtrace="stack backtrace:\n   0: tikv_util::set_panic_hook::{{closure}}\n             at components/tikv_util/src/lib.rs:482\n   1: std::panicking::rust_panic_with_hook\n             at src/libstd/panicking.rs:475\n   2: rust_begin_unwind\n             at src/libstd/panicking.rs:375\n   3: std::panicking::begin_panic_fmt\n             at src/libstd/panicking.rs:326\n   4: raftstore::store::peer_storage::PeerStorage<EK,ER>::check_applying_snap
```
for running in container the report is not complete

### PR DESCRIPTION
**Pull request by yiwu-arbug**
Signed-off-by: Yi Wu <yiwu@pingcap.com>

### What problem does this PR solve?

Issue Number: close #7785 

Problem Summary: There was multiple issues with file ingestion:
* `prepare_sst_for_ingestion()` was not calling `key_manager.delete_file` when it remove a stale clone of the sst, cause it end up with "file already exists" error when linking a new clone.
* `link_file`, `delete_file` and `rename_file` methods in `DataKeyManager` was returning error when the file being query is not found in file dictionary. Those files should be plaintext files pre-exists before enabling encryption and not being tracked by file dictionary. The correct behavior is to return `Ok` without doing anything.

### What is changed and how it works?

What's Changed: Fixing the above issues. Updated unit test for `prepare_sst_for_ingestion()`, which would caught the above issues.

### Related changes

No.

### Check List 

Tests 
See the updated unit test.

### Release note 

* Fix snapshot ingestion error when encryption is enabled.

### CODE REVIEW

File: components/test_util/src/encryption.rs [hunk 1]
```diff
@@ -0,0 +1,36 @@
+// Copyright 2020 TiKV Project Authors. Licensed under Apache-2.0.
+
+use std::{fs::File, io::Write, time::Duration};
+
+use encryption::{DataKeyManager, FileConfig, MasterKeyConfig, Result};
+use kvproto::encryptionpb::EncryptionMethod;
+
+pub fn create_test_key_file(path: &str) {
+    let mut file = File::create(path.clone()).unwrap();
```
Comment (hicqu) [inline components/test_util/src/encryption.rs:9]: Is `clone` necessary?

Comment (yiwu-arbug) [reply components/test_util/src/encryption.rs]: fixed.

File: components/encryption/src/manager/mod.rs [hunk 2]
```diff
@@ -177,12 +177,13 @@ impl Dicts {
...
-            Error::Io(IoError::new(
-                ErrorKind::NotFound,
-                format!("file not found, {}", fname),
-            ))
-        })?;
+        let file = match self.file_dict.files.remove(fname) {
+            Some(file_info) => file_info,
+            None => {
+                // Could be a plaintext file not tracked by file dictionary.
+                return Ok(());
```
Comment (overvenus) [inline components/encryption/src/manager/mod.rs:184]: Instead of returning Ok, how about handle NotFound error at a higher level? I worry about we may miss some error somewhere.

Comment (yiwu-arbug) [reply components/encryption/src/manager/mod.rs:184]: Discussed offline, will add more info log instead.

File: components/encryption/src/manager/mod.rs [hunk 3]
```diff
@@ -177,33 +177,34 @@ impl Dicts {
...
-            Error::Io(IoError::new(
-                ErrorKind::NotFound,
-                format!("file not found, {}", fname),
-            ))
-        })?;
+        let file = match self.file_dict.files.remove(fname) {
+            Some(file_info) => file_info,
+            None => {
+                // Could be a plaintext file not tracked by file dictionary.
+                info!("delete untracked plaintext file"; "fname" => fname);
```
Comment (hicqu) [inline components/encryption/src/manager/mod.rs:184]: How about add a log into `new_file`?
