### PR TITLE
encryption: fix key collision handling

### LINKED ISSUE #14585: encryption key id collision will erase old key
### What version of TiKV are you using?

[v5.0.0](https://github.com/tikv/tikv/releases/tag/v5.0.0) forward, introduced in https://github.com/tikv/tikv/pull/8805

### What operating system and CPU are you using?

N/A

### PR DESCRIPTION
**Pull request by tabokie**
### What is changed and how it works?

Issue Number: Close #14585

What's Changed:

The old key handling logic is mistakenly reverted in https://github.com/tikv/tikv/pull/8805, restoring them now.

```commit-message
Fix a bug that a newly generated encryption key might erase an old key and make data unreadable
```

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

### Release note 

```release-note
Fix a bug that a newly generated encryption key might erase an old key and make data unreadable
```

### CODE REVIEW

File: components/encryption/src/manager/mod.rs [hunk 1]
```diff
@@ -287,19 +288,23 @@ impl Dicts {
         Ok(Some(()))
     }
 
-    fn rotate_key(&self, key_id: u64, key: DataKey, master_key: &dyn Backend) -> Result<()> {
+    fn rotate_key(&self, key_id: u64, key: DataKey, master_key: &dyn Backend) -> Result<bool> {
```
Comment (BusyJay) [inline components/encryption/src/manager/mod.rs:291]: The returned value doesn't seem to be used.

**Review by BusyJay — APPROVED** [review]

File: components/encryption/src/manager/mod.rs (hunk 1 above)
Comment (tabokie) [reply components/encryption/src/manager/mod.rs:291]: used at L362

**Review by overvenus — APPROVED** [review]
