### PR TITLE
raftstore: set term when catch up logs for merge 

### LINKED ISSUE #11526: After inserted 1 billions data in to tidb, the one of TiKV never able to startup, neither restart.
### What version of TiKV are you using?

> [root@ip-172-16-5-33 bin]# ./tikv-server --version
TiKV 
Release Version:   5.2.2
Edition:           Community
Git Commit Hash:   7acaec5d9c809439b9b0017711f114b44ffd9a49
Git Commit Branch: heads/refs/tags/v5.2.2
UTC Build Time:    2021-10-25 12:00:54
Rust Version:      rustc 1.56.0-nightly (2faabf579 2021-07-27)
Enable Features:   jemalloc mem-profiling portable sse protobuf-codec test-engines-rocksdb cloud-aws cloud-gcp
Profile:           dist_release

### What operating system and CPU are you using?

> 40 cpus, 2 numa nodes. 
processor	: 39
vendor_id	: GenuineIntel
cpu family	: 6
model		: 79
model name	: Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz
stepping	: 1
microcode	: 0xb00001f
cpu MHz		: 1994.958
cache size	: 25600 KB
physical id	: 1
siblings	: 20
core id		: 12
cpu cores	: 10
apicid		: 57
initial apicid	: 57
fpu		: yes
fpu_exception	: yes
cpuid level	: 20
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb cat_l3 cdp_l3 invpcid_single intel_pt tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a rdseed adx smap xsaveopt cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts
bogomips	: 4399.36
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:

### Steps to reproduce

- Using BR to restore 60K empty tables (60K table generate by [betting](https://github.com/yongpan0709/workloads))
- Using betting to generate 1 billions data
`nohup ./bin/go-ycsb load mysql -P workloads/betting -p recordcount=1000000000 -p mysql.host=172.16.4.2 -p mysql.user=root -p mysql.port=44000 --threads 200 -p dbnameprefix=test_betting_ -p databaseproportions=1.0 -p unitnameprefix=unit1_ -p unitscount=200 -p tablecount=60000 -p loadbatchsize=1000&`

Manual: https://pingcap.feishu.cn/docs/doccnijeesmUrKiHLHay6rMwnaf

### What did you expect?
TiKV can work without problem.
### What did happened?
TiKV down and never able to startup
W1SzCKWuFj

Error log from tikv_stderr:
>[2021/12/01 15:23:21.831 +08:00] [FATAL] [mod.rs:376] ["logger encountered error"] [err="Cannot allocate memory (os error 12)"]

other error log:
28492 [2021/12/01 16:05:09.604 +08:00] [FATAL] [server.rs:831] ["failed to start node: Engine(Other(\"[components/raftstore/src/store/fsm/store.rs:1056]: \\\"[components/raftstore/src/store/peer_storage.rs:768]: [region 36305] 36307 validate state fail: Other(\\\\\\\"[c      omponents/raftstore/src/store/peer_storage.rs:678]: term of raft state < commit term of apply state, region 36305, raft state hard_state { term: 13 vote: 36307 commit: 815 } last_index: 815, apply state applied_index: 815 commit_index: 815 commit_term: 14 truncate      d_state { index: 772 term: 11 }\\\\\\\")\\\"\"))"]

Kernel log:
dYNplGHNuh

dmesg -T:
zliAC9HuPM

Linux has enough memory:
F7AqrUnbbX

check NUMA nodes:
middle_img_v2_9f444510-cb64-4a72-8625-b35b5c7d9a5g

more log in 172.16.5.33:/data4/log/

### PR DESCRIPTION
**Pull request by BusyJay**
### What is changed and how it works?

Prepare merge may includes logs from different terms, which may be even
larger than the term of a follower that is lag behind. So when catching
up logs by commit merge, its term should also be set to get a correct
metadata.

Close #11526.

### Check List 

Tests 

- Unit test
- Integration test

### Release note 

```release-note
Fix metadata corruption in an unlikely condition that prepare merge is triggered after new election without informing an isolated peer
```

### CODE REVIEW

**Review by gengliqi — APPROVED** [review]

File: components/raftstore/src/store/peer.rs [hunk 1]
```diff
@@ -821,6 +821,16 @@ where
...
         let log_term = self.get_index_term(log_idx);
 
+        let last_log_term = entries.last().unwrap().term;
+        if last_log_term > self.term() {
+            // Hack: In normal flow, when leader sends the entries, it will use a term that's not less
+            // than the last log term. And follower will update its states correctly. For merge, we append
+            // the log without raft, so we have to take care of term explicitly to get correct metadata.
+            self.raft_group
+                .raft
+                .become_follower(last_log_term, INVALID_ID);
```
Comment (NingLin-P) [inline components/raftstore/src/store/peer.rs:831]: Better add some logs to indicate that the peer becomes a follower because of appending merge entries.

**Review by NingLin-P — APPROVED** [review]
