### PR TITLE
raftstore: remove unnecessary assert on merge check

### LINKED ISSUE #9980: raftstore panics during merge
### What version of TiKV are you using?

`b2fad976da192006888e2fc80746f9196cf425b6`

### What operating system and CPU are you using?

x86-64 CentOS 7.6

### Steps to reproduce

Running tests on TiCDC with a large write throughput and CDC scan throughput.

### What did you expect?
That everything works.

### What did happened?

```
[2021/04/07 16:23:44.597 +08:00] [FATAL] [lib.rs:455] ["assertion failed: min_matched >= min_committed"] [backtrace="stack backtrace:\n   0: tikv_util::set_panic_hook::{{closure}}\n   1: std::panicking::rust_panic_with_hook\n             at /rustc/bc39d4d9c514e5fdb40a5782e6ca08924f979c35//library/std/src/panicking.rs:595\n   2: std::panicking::begin_panic_handler::{{closure}}\n             at /rustc/bc39d4d9c514e5fdb40a5782e6ca08924f979c35//library/std/src/panicking.rs:495\n   3: std::sys_common::backtrace::__rust_end_short_backtrace\n             at /rustc/bc39d4d9c514e5fdb40a5782e6ca08924f979c35//library/std/src/sys_common/backtrace.rs:141\n   4: rust_begin_unwind\n             at /rustc/bc39d4d9c514e5fdb40a5782e6ca08924f979c35//library/std/src/panicking.rs:493\n   5: core::panicking::panic_fmt\n             at /rustc/bc39d4d9c514e5fdb40a5782e6ca08924f979c35//library/core/src/panicking.rs:92\n   6: core::panicking::panic\n             at /rustc/bc39d4d9c514e5fdb40a5782e6ca08924f979c35//library/core/src/panicking.rs:50\n   7: raftstore::store::peer::Peer<EK,ER>::propose_normal\n   8: raftstore::store::fsm::peer::PeerFsmDelegate<EK,ER,T>::propose_raft_command\n   9: raftstore::store::fsm::peer::PeerFsmDelegate<EK,ER,T>::handle_msgs\n  10: <raftstore::store::fsm::store::RaftPoller<EK,ER,T> as batch_system::batch::PollHandler<raftstore::store::fsm::peer::PeerFsm<EK,ER>,raftstore::store::fsm::store::StoreFsm<EK>>>::handle_normal\n  11: batch_system::batch::Poller<N,C,Handler>::poll\n  12: std::sys_common::backtrace::__rust_begin_short_backtrace\n  13: core::ops::function::FnOnce::call_once{{vtable.shim}}\n  14: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once\n             at /rustc/bc39d4d9c514e5fdb40a5782e6ca08924f979c35/library/alloc/src/boxed.rs:1484\n      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once\n             at /rustc/bc39d4d9c514e5fdb40a5782e6ca08924f979c35/library/alloc/src/boxed.rs:1484\n      std::sys::unix::thread::Thread::new::thread_start\n             at /rustc/bc39d4d9c514e5fdb40a5782e6ca08924f979c35//library/std/src/sys/unix/thread.rs:71\n  15: start_thread\n  16: __clone\n"] [location=/home/tidb/tikv/components/raftstore/src/store/peer.rs:2813] [thread_name=raftstore-1-0]
```

### PR DESCRIPTION
**Pull request by NingLin-P**
Signed-off-by: linning <linningde25@gmail.com>

### What problem does this PR solve?

Issue Number: close #9980 

Problem Summary:

The `raft-r`'s `pr.committed_index` may be inaccurate (see https://github.com/tikv/raft-rs/issues/426) and cause panic on `pre_propose_prepare_merge` check

### What is changed and how it works?

What's Changed:

Replace the assert with a warning log since the assert just for robustness and is not a fatal error if it fail

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- No code

### Release note 
- No release note

### CODE REVIEW

**Review by BusyJay — APPROVED** [review]

File: components/raftstore/src/store/peer.rs [hunk 1]
```diff
@@ -2814,7 +2814,15 @@ where
...
         }
-        assert!(min_matched >= min_committed);
+        if min_matched < min_committed {
+            warn!(
+                "min_matched < min_committed, raft progress is inaccurate";
+                "region_id" => self.region_id,
+                "peer_id" => self.peer.get_id(),
+                "min_matched" => min_matched,
+                "min_committed" => min_committed,
+            );
```
Comment (gengliqi) [inline components/raftstore/src/store/peer.rs:2824]: We can set `min_matched` to `min_committed` to reduce the entry size.

Comment (gengliqi) [reply components/raftstore/src/store/peer.rs:2824]: Oh. I think we can do this in `get_min_progress` because `min_matched >= min_committed` should always true.

Comment (gengliqi) [reply components/raftstore/src/store/peer.rs:2824]: And the `warn` log can also be printed in `get_min_progress`.

Comment (NingLin-P) [reply components/raftstore/src/store/peer.rs]: Done.

File: components/raftstore/src/store/peer.rs [hunk 2]
```diff
@@ -2792,7 +2792,20 @@ where
...
+        if min_m < min_c {
+            warn!(
+                "min_matched < min_committed, raft progress is inaccurate";
+                "region_id" => self.region_id,
+                "peer_id" => self.peer.get_id(),
+                "min_matched" => min_m,
+                "min_committed" => min_c,
+            );
+            // Reset `min_matched` to `min_committed`, since a raft log is committed,
+            // the peer should also has replicated it
```
Comment (BusyJay) [inline components/raftstore/src/store/peer.rs:2805]: Why? For example, a former leader can have log conflict and `matched` is 0. Its committed index doesn't necessary to be the minimized value of other peers.

Comment (NingLin-P) [reply components/raftstore/src/store/peer.rs:2805]: Enlarge `min_matched` can reduce the entry size for merge check, also `min_matched` and `min_committed` are unnecessary belong to the same peer

Comment (BusyJay) [reply components/raftstore/src/store/peer.rs:2805]: You miss my point. The reason why `min_matched` can be set to `min_committed` is because `committed_index` is reported by follower and guaranteed logs at the index and before it are also persisted. It implies follower's actual `matched` should not be less than `committed_index`. And actual `min_matched` should not less than `min_committed`. It has nothing to do with whether the log is committed.

Comment (NingLin-P) [reply components/raftstore/src/store/peer.rs:2805]: Yes, it is the same reason I reset `min_matched`, the "a raft log" I mentioned in the comment is referring to the one at `min_committed`, I update the comment to make it more clear, PTAL again

**Review by BusyJay — APPROVED** [review]

**Review by gengliqi — APPROVED** [review]
LGTM

File: components/raftstore/src/store/peer.rs (hunk 1 above)
Comment (BusyJay) [reply components/raftstore/src/store/peer.rs]: This can be unsafe. The actual `min_match` can be greater than `min_committed`, if resetting inaccurate `min_match` (like 0) to `min_committed` then it may requires more logs that even beyond the first index of existing peer to propose commit merge. Hence lead to panic like #12663.
