### PR TITLE
log_backup: always wait force flush RPCs

### LINKED ISSUE #18262: log_backup: force flush should wait until flush done
## Development Task
Caller may just want to make sure the store is recently flushed. But if force flush fails when encountering running flush, the client then has no idea about when this flush will finish.

An example is when doing rolling restart, we want every store flushed before it restarted. Hence a `FlushNow` wan sent, but then when it responses "another flush is running" we can do few things but back off and retry; it will be better to wait the running flush and return "success" after the running flush finished.

### PR DESCRIPTION
**Pull request by YuJuncen**
### What is changed and how it works?

Issue Number: Close #18262

What's Changed:

```commit-message
This will make `force-flush` wait the last flush if there is a running one instead of just return an error.
```

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [ ] Need to cherry-pick to the release branch

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note

```release-note
None
```

### CODE REVIEW

File: components/backup-stream/src/endpoint.rs [hunk 1]
```diff
@@ -881,33 +883,43 @@ where
...
                         })
                         .await;
                     }
                     Err(_) => {
-                        let res = FlushResult {
-                            task: hnd.task.info.name.to_owned(),
-                            error: Some(Error::Other(box_err!("task is flushing"))),
-                        };
-                        let _ = sender.send(res).await;
+                        info!("")
```
Comment (3pointer) [inline components/backup-stream/src/endpoint.rs:922]: miss something?

**Review by 3pointer — APPROVED** [review]
rest LGTM

File: components/backup-stream/src/endpoint.rs [hunk 2]
```diff
@@ -1088,9 +1097,23 @@ where
...
+    fn on_flushed(&mut self, result: FlushResult) {
+        if let Some(sender) = self.flush_done_subscribers.remove(&result.task) {
+            // Send the message after the subscription manager have tried to sent this flush
+            // result to subscribers.
+            self.checkpoint_mgr.sync_with_subs_mgr(move |_| {
+            if let Err(err) = sender.try_send(result) {
+                let err_msg = err.to_string();
+                info!("failed to send flush result, waiter is gone or channel blocked"; "err" => %err_msg, "result" => ?err.into_inner());
+            }
+        })
```
Comment (Leavrth) [inline components/backup-stream/src/endpoint.rs:1116]:
```suggestion
            self.checkpoint_mgr.sync_with_subs_mgr(move |_| {
                if let Err(err) = sender.try_send(result) {
                    let err_msg = err.to_string();
                    info!("failed to send flush result, waiter is gone or channel blocked"; "err" => %err_msg, "result" => ?err.into_inner());
                }
            })
```

File: components/backup-stream/src/endpoint.rs (hunk 1 above)
Comment (Leavrth) [reply components/backup-stream/src/endpoint.rs:922]: +1

**Review by Leavrth — COMMENTED** [review]
rest LGTM

**Review by Leavrth — APPROVED** [review]

**Review by iosmanthus — APPROVED** [review]
