### PR TITLE
raftstore: polish the availability check on conf change requests

### LINKED ISSUE #16465: (dr-autosync) v6.5.8 scale in one node from primary datacenter failed during async mode
### What version of TiKV are you using?

v6.5.8

### Steps to reproduce

1. deploy one tidb cluster with 12 stores, and config it with 5 replicas in dr-auto-sync mode.
2. down two tikvs in the backup center, make replication mode switch to async.
3. Try to scale-in one node in the primary center.

### What did you expect?
Scale in succeeded.

### What did happened?
Scale in hung.

Didn't hit it before https://github.com/tikv/tikv/pull/16174.

### PR DESCRIPTION
**Pull request by tonyxuqqi**
### What is changed and how it works?

Issue Number: Close #16465

What's Changed:

```commit-message
When calculating the impact of conf change, include all operations into considerations.
```

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [ ] Need to cherry-pick to the release branch

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by LykxSassinator — APPROVED** [review]
LGTM

File: components/raftstore/src/store/util.rs [hunk 1]
```diff
@@ -1123,77 +1129,98 @@ pub fn check_conf_change(
...
-                normal_voters_count += 1;
+                normal_voters.push(*id);
             } else {
-                slow_voters_count += 1;
+                slow_voters.push(*id);
             }
         }
     }
 
+    let is_healthy = normal_voters.len() > slow_voters.len();
```
Comment (LykxSassinator) [inline components/raftstore/src/store/util.rs:1169]: One more tip, if `is_healthy` already is `false`, the following steps for checking could be skipped.

**Review by Connor1996 — APPROVED** [review]
LGTM
