### PR TITLE
test: fix test test_ingest_key_manager_delete_file_failed

### LINKED ISSUE #9138: cases::test_import_service::test_ingest_key_manager_delete_file_failed failed
cases::test_import_service::test_ingest_key_manager_delete_file_failed

 Latest failed builds: 
https://internal.pingcap.net/idc-jenkins/job/tikv_ghpr_test/36408/consoleFull

### PR DESCRIPTION
**Pull request by glorv**
### What problem does this PR solve?

Issue Number: close #9138

Problem Summary:

### What is changed and how it works?
Add a loop of sleep to wait until the async action `clean sst` finished before exec the second upload.

### Check List 

Tests 
- Unit test

Side effects

### Release note 
- No Release Note

### CODE REVIEW

File: tests/failpoints/cases/test_import_service.rs [hunk 1]
```diff
@@ -113,11 +116,25 @@ fn test_ingest_key_manager_delete_file_failed() {
...
+    let node_id = *cluster.sim.rl().get_node_ids().iter().next().unwrap();
+    let save_path = cluster
+        .sim
+        .rl()
+        .importers
+        .get(&node_id)
+        .unwrap()
+        .get_path(&meta);
+    // wait until the raw uploaded file is deleted by the async clean up task.
+    loop {
```
Comment (kennytm) [inline tests/failpoints/cases/test_import_service.rs:130]: add some exit condition to avoid this test running forever.

**Comment by BusyJay** [comment]
PTAL, the case has made the success rate go down to 65%.

**Review by kennytm — APPROVED** [review]
Lgtm

**Review by overvenus — APPROVED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]
