### PR TITLE
snapshot generating and receiving share I/O limiter fairly

### LINKED ISSUE #9918: Add learner too slow which cause the PD operator timeout
### What version of TiKV are you using?
5.0 branch (4db8ee36f69b3ec2d5c5281800e1161ee7af7665)

### What operating system and CPU are you using?
Not related

### Steps to reproduce

Just offline the store.

### What did you expect?

The offline operator can be successfully executed.

### What did happened?
```
[operator_controller.go:566] ["operator timeout"] [region-id=375619799] [takes=20m3.453927516s] [operator="\"replace-rule-offline-peer {mv peer: store [442652643] to [220163081]} (kind:leader,region,replica, region:375619799(51833,1446), createAt:2021-03-29 10:16:25.152050758 +0800 CST m=+67530.662320625, startAt:2021-03-29 10:16:25.170851946 +0800 CST m=+67530.681121812, currentStep:0, steps:[add learner peer 442702203 on store 220163081, transfer leader from store 442652643 to store 3, use joint consensus, promote learner peer 442702203 on store 220163081 to voter, demote voter peer 442671526 on store 442652643 to learner, leave joint state, promote learner peer 442702203 on store 220163081 to voter, demote voter peer 442671526 on store 442652643 to learner, remove peer on store 442652643]) timeout\""]
```

And from the TiKV log:
```
[2021/03/29 10:16:25.169 +08:00] [Info] [pd.rs:824] ["try to change peer"] [peer="id: 442702203 store_id: 220163081 role: Learner"] [change_type=AddLearnerNode] [region_id=375619799]
[2021/03/29 10:16:25.169 +08:00] [Info] [peer.rs:3145] ["propose conf change peer"] [kind=Simple] [changes="[change_type: AddLearnerNode peer { id: 442702203 store_id: 220163081 role: Learner }]"] [peer_id=442671526] [region_id=375619799]
[2021/03/29 10:16:25.170 +08:00] [Info] [apply.rs:1248] ["execute admin command"] [command="cmd_type: ChangePeer change_peer { change_type: AddLearnerNode peer { id: 442702203 store_id: 220163081 role: Learner } }"] [index=91] [term=56] [peer_id=442671526] [region_id=3756
19799]
[2021/03/29 10:16:25.170 +08:00] [Info] [apply.rs:1613] ["exec ConfChange"] [epoch="conf_ver: 1446 version: 51833"] [type=AddLearner] [peer_id=442671526] [region_id=375619799]
[2021/03/29 10:16:25.170 +08:00] [Info] [apply.rs:1753] ["add learner successfully"] [region="id: 375619799 start_key: 7480000000000006FF755F72F0000004A0FF5302720000000000FA end_key: 7480000000000006FF755F72F0000004A1FF070D2C0000000000FA region_epoch { conf_ver: 1446 vers
ion: 51833 } peers { id: 375619801 store_id: 40 } peers { id: 376209730 store_id: 3 } peers { id: 383497265 store_id: 218740296 role: Learner } peers { id: 442671526 store_id: 442652643 }"] [peer="id: 442702203 store_id: 220163081 role: Learner"] [peer_id=442671526] [regi
on_id=375619799]
[2021/03/29 10:16:25.170 +08:00] [Info] [raft.rs:2443] ["switched to configuration"] [config="Configuration { voters: Configuration { incoming: Configuration { voters: {376209730, 375619801, 442671526} }, outgoing: Configuration { voters: {} } }, learners: {383497265, 442
702203}, learners_next: {}, auto_leave: false }"] [raft_id=442671526] [region_id=375619799]
[2021/03/29 10:16:25.170 +08:00] [Info] [peer.rs:2095] ["notify pd with change peer region"] [region="id: 375619799 start_key: 7480000000000006FF755F72F0000004A0FF5302720000000000FA end_key: 7480000000000006FF755F72F0000004A1FF070D2C0000000000FA region_epoch { conf_ver: 1
447 version: 51833 } peers { id: 375619801 store_id: 40 } peers { id: 376209730 store_id: 3 } peers { id: 383497265 store_id: 218740296 role: Learner } peers { id: 442671526 store_id: 442652643 } peers { id: 442702203 store_id: 220163081 role: Learner }"] [peer_id=4426715
26] [region_id=375619799]
[2021/03/29 10:16:25.171 +08:00] [Info] [peer_storage.rs:986] ["requesting snapshot"] [request_index=0] [peer_id=442671526] [region_id=375619799]
[2021/03/29 10:41:22.692 +08:00] [Info] [pd.rs:824] ["try to change peer"] [peer="id: 442702203 store_id: 220163081 role: Learner"] [change_type=RemoveNode] [region_id=375619799]
[2021/03/29 10:41:22.692 +08:00] [Info] [peer.rs:3145] ["propose conf change peer"] [kind=Simple] [changes="[change_type: RemoveNode peer { id: 442702203 store_id: 220163081 role: Learner }]"] [peer_id=442671526] [region_id=375619799]
[2021/03/29 10:41:22.693 +08:00] [Info] [apply.rs:1248] ["execute admin command"] [command="cmd_type: ChangePeer change_peer { change_type: RemoveNode peer { id: 442702203 store_id: 220163081 role: Learner } }"] [index=92] [term=56] [peer_id=442671526] [region_id=375619799]
[2021/03/29 10:41:22.693 +08:00] [Info] [apply.rs:1613] ["exec ConfChange"] [epoch="conf_ver: 1447 version: 51833"] [type=RemoveNode] [peer_id=442671526] [region_id=375619799]
[2021/03/29 10:41:22.693 +08:00] [Info] [apply.rs:1721] ["remove peer successfully"] [region="id: 375619799 start_key: 7480000000000006FF755F72F0000004A0FF5302720000000000FA end_key: 7480000000000006FF755F72F0000004A1FF070D2C0000000000FA region_epoch { conf_ver: 1447 version: 51833 } peers { id: 375619801 store_id: 40 } peers { id: 376209730 store_id: 3 } peers { id: 383497265 store_id: 218740296 role: Learner } peers { id: 442671526 store_id: 442652643 } peers { id: 442702203 store_id: 220163081 role: Learner }"] [peer="id: 442702203 store_id: 220163081 role: Learner"] [peer_id=442671526] [region_id=375619799]
```

### PR DESCRIPTION
**Pull request by hicqu**
### What problem does this PR solve?

Currently snapshot receiving has much higher priority than generating. It will cause snapshot generating take too long time during snapshot receiving. The reason is snapshot generating and receiving share one I/O limiter, but the receiving procedure acquires much more bytes than generating.

It's a part to resolve #9918.

### What is changed and how it works?

Make snapshot generating and receiving procedures share I/O limiter fairly.

### Check List 

Tests 

- Integration test

### Release note 
* No release note.

### CODE REVIEW

File: tests/integrations/raftstore/test_snap.rs [hunk 1]
```diff
@@ -514,3 +523,143 @@ fn test_inspected_snapshot() {
...
+    // Read a snapshot meta.
+    let mut meta_bytes = Vec::with_capacity(1024);
+    fs::File::open(meta_path)
+        .and_then(|mut f| f.read_to_end(&mut meta_bytes))
+        .unwrap();
+    let mut snap_meta = SnapshotMeta::default();
+    snap_meta.merge_from_bytes(&meta_bytes).unwrap();
+
+    // Construct a snapshot data.
+    let mut snap_data = RaftSnapshotData::default();
```
Comment (BusyJay) [inline tests/integrations/raftstore/test_snap.rs:629]: Can the functions from snap.rs be reused?

Comment (hicqu) [reply tests/integrations/raftstore/test_snap.rs:629]: I guess no because `RaftSnapshotData` is constructed in `Snap::build`, which is not usefule here.

**Comment by hicqu** [comment]
I have benchmarked `SNAP_IO_CHUNK=4k` with code:
```
use async_speed_limit::Limiter;
use std::time::{Duration, Instant};

fn bench_a_round(speed: usize, chunk: usize) -> Duration {
    let limiter = <Limiter>::new(speed as f64);
    let now = Instant::now();
    (0..(speed / chunk)).for_each(|_| limiter.blocking_consume(chunk));
    now.elapsed()
}

fn do_bench(speed: usize, chunk: usize) {
    let mut samples = Vec::with_capacity(10);
    (0..10).for_each(|_| samples.push(bench_a_round(speed, chunk).as_millis()));
    let avg = samples.into_iter().fold(0, |s, i| s + i) / 10;
    println!("[speed={}, chunk={}] -> {} ms", speed, chunk, avg);
}

fn main() {
    do_bench(100 * 1000 * 1000, 4 * 1000);
    do_bench(100 * 1000 * 1000, 128 * 1000);
    do_bench(100 * 1000 * 1000, 1000 * 1000);
}
```
Here is the result:
```
[speed=100000000, chunk=4000] -> 904 ms
[speed=100000000, chunk=128000] -> 910 ms
[speed=100000000, chunk=1000000] -> 990 ms
```
And CPU usage keeps low.

So, let's choose `4k` as the chunk size.

File: tests/failpoints/cases/test_snap.rs [hunk 2]
```diff
@@ -478,7 +478,6 @@ fn test_gen_snapshot_with_no_committed_entries_ready() {
 #[test]
 fn test_cancel_snapshot_generating() {
     let mut cluster = new_node_cluster(0, 5);
-    cluster.cfg.server.snap_max_write_bytes_per_sec = ReadableSize(10);
```
[the remark this answers is not in the document]
Comment (hicqu) [reply tests/failpoints/cases/test_snap.rs:481]: It can fail the case because generating snapshot becomes too slow. It can pass before the PR because the configuration doesn't make any effects exactly.

File: components/raftstore/src/store/snap/io.rs [hunk 3]
```diff
@@ -113,9 +113,16 @@ where
 {
     let mut sst_writer = create_sst_file_writer::<E>(engine, cf, path)?;
     let mut stats = BuildStatistics::default();
+    let mut remained_quota = 0;
     box_try!(snap.scan_cf(cf, start_key, end_key, false, |key, value| {
         let entry_len = key.len() + value.len();
-        io_limiter.blocking_consume(entry_len);
+        while entry_len > remained_quota {
+            // It's possible to acquire more than necessary, but let it be.
+            io_limiter.blocking_consume(IO_LIMITER_CHUNK_SIZE);
```
Comment (Connor1996) [inline components/raftstore/src/store/snap/io.rs:121]: This PR makes them fair by underestimating the generating traffic and overestimating the receiving traffic? What if there is only generating traffic? The real generating traffic will be limited far below what we actually want.

Comment (hicqu) [reply components/raftstore/src/store/snap/io.rs:121]: No, it just make them share the I/O limiter fairly. Without the PR snapshot receiving will acquire more bytes from the limiter, which will slow down generating.

**Review by Connor1996 — APPROVED** [review]
LGTM

**Review by BusyJay — APPROVED** [review]
