### PR TITLE
resolved_ts: fix high tail latency cause by time-consuming operation in raftstore 

### LINKED ISSUE #10342: raftstore: with large number of region the CheckLeader rpc may increase the tail latency of propose wait/append log
## Bug Report

The `CheckLeader` rpc also sync the `(apply index, safe ts)` from leader to follower, it is done by `RegionReadProgress:: update_safe_ts` which invoke lock acquiring, although the lock is usually not contended, but when the number of regions is large, it may acquiring lot of lock and being time-consuming. As result, the tail latency of propose wait and append log duration may increase:

image

image

### PR DESCRIPTION
**Pull request by NingLin-P**
### What problem does this PR solve?

Issue Number: close #10342 

Problem Summary:

Currently, the `CheckLeader` rpc is handled in `raftstore`, when the number of regions info in the `CheckLeader` request is large, handling the request could be time-consuming, and may increase the tail latency of `Append log duration`/`Propose wait duration`.

### What is changed and how it works?

What's Changed:

This PR fix the issue by:
- move the handling of `CheckLeader` request to the `resolved-ts` worker
- instead of `StoreMeta`, using another fine-grained mutex for `region_read_progress`

### Related changes

- Need to cherry-pick to the release branch

### Check List 

- Existing integration test

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by BusyJay** [comment]
How does it perform comparing to no check-leaders at all?

**Comment by NingLin-P** [comment]
> How does it perform comparing to no check-leaders at all?

image

截屏2021-06-17 下午11 41 22

The `CheckLeader` is disabled by dynamically changing the `resolved-ts.advance-ts-interval` to 1h at about 23:15

File: components/raftstore/src/store/util.rs [hunk 1]
```diff
@@ -905,6 +994,60 @@ impl RegionReadProgress {
...
+                    if !core.pause {
+                        self.safe_ts.store(ts, AtomicOrdering::Release);
+                    }
+                }
+            }
+        }
+        // whether the provided `LeaderInfo` is same as ours
+        core.leader_info.leader_term == leader_info.term
+            && core.leader_info.leader_id == leader_info.peer_id
+            && region_epoch_equal(&core.leader_info.epoch, leader_info.get_region_epoch())
```
Comment (Yisaer) [inline components/raftstore/src/store/util.rs:1017]: Why not check leaderInfo first?

**Review by Yisaer — COMMENTED** [review]
Rest LGTM

File: components/raftstore/src/store/util.rs (hunk 1 above)
Comment (NingLin-P) [reply components/raftstore/src/store/util.rs:1017]: So that we can return the result directly instead of assigning the result to a temporary variable and return it at the end.

**Review by Yisaer — APPROVED** [review]

File: components/raftstore/src/store/worker/check_leader.rs [hunk 2]
```diff
@@ -0,0 +1,164 @@
+// Copyright 2016 TiKV Project Authors. Licensed under Apache-2.0.
```
Comment (BusyJay) [inline components/raftstore/src/store/worker/check_leader.rs:1]: Should be 2021.

File: components/raftstore/src/store/fsm/store.rs [hunk 3]
```diff
@@ -614,9 +614,23 @@ impl<'a, EK: KvEngine + 'static, ER: RaftEngine + 'static, T: Transport>
                     self.on_store_unreachable(store_id);
                 }
                 StoreMsg::Start { store } => self.start(store),
-                StoreMsg::CheckLeader { leaders, cb } => self.on_check_leader(leaders, cb),
+                StoreMsg::CheckLeader { leaders, cb } => {
```
Comment (BusyJay) [inline components/raftstore/src/store/fsm/store.rs:617]: Why have to go through raftstore?

Comment (NingLin-P) [reply components/raftstore/src/store/fsm/store.rs:617]: I have tried to redirect the request at the server layer through the `resolved-ts` worker scheduler but failed due to cycle dependency of `resolved-ts` and `tikv` crate.

Comment (BusyJay) [reply components/raftstore/src/store/fsm/store.rs:617]: I don't get it. Seems what's needed is just a channel sender, why need to include all the dependency?

Comment (NingLin-P) [reply components/raftstore/src/store/fsm/store.rs]: It needs the worker's `Task`, but since we move the `CheckLeader` handler to another worker, I think we can use that worker's scheduler to redirect requests now.

**Comment by NingLin-P** [comment]
I have done more benchmark about this PR, the result looks good:

image

The first three workloads are running on the master branch with the `CheckLeader` interval set to `1s`, `5s` and `1h` (which can consider as disable `CheckLeader`) respectively, we can see the `.999` and `.99` latency is highly affected by the CheckLeader interval and with this PR the effect is not more exist.

File: components/raftstore/src/store/worker/check_leader.rs [hunk 4]
```diff
@@ -0,0 +1,166 @@
...
+                .filter(|ts| *ts != 0) // ts == 0 means the peer is uninitialized
+                .min()
+                .unwrap_or(0)
+            })
+        } else {
+            // `store_safe_ts` won't be accessed frequently (like per-request or per-transaction),
+            // also this branch won't entry because the request key range is empty currently (in v5.1)
+            // keep this branch for robustness and future use, so it is okay getting `store_safe_ts`
+            // from `store_meta` (behide a mutex)
+            let meta = self.store_meta.lock().unwrap();
```
Comment (BusyJay) [inline components/raftstore/src/store/worker/check_leader.rs:73]: This can be moved to L77.

File: components/raftstore/src/store/worker/check_leader.rs [hunk 5]
```diff
@@ -0,0 +1,166 @@
...
+            let (start_key, end_key) = (
+                data_key(key_range.get_start_key()),
+                data_end_key(key_range.get_end_key()),
+            );
+            meta.region_read_progress.map(|registry| {
+                meta.region_ranges
+                // get overlapped regions
+                .range((Excluded(start_key.clone()), Unbounded))
```
Comment (BusyJay) [inline components/raftstore/src/store/worker/check_leader.rs:81]: Why clone?

File: components/raftstore/src/store/util.rs [hunk 6]
```diff
@@ -836,6 +844,90 @@ impl Display for MsgType<'_> {
...
+            .unwrap()
+            .get(region_id)
+            .map(|rp| rp.safe_ts())
+    }
+
+    // Update `safe_ts` with the provided `LeaderInfo` and return the regions that have the
+    // same `LeaderInfo`
+    pub fn handle_check_leaders(&self, leaders: Vec<LeaderInfo>) -> Vec<u64> {
+        let mut regions = Vec::with_capacity(leaders.len());
+        let registry = self.registry.lock().unwrap();
```
Comment (BusyJay) [inline components/raftstore/src/store/util.rs:890]: Can be dropped at L898.

File: components/raftstore/src/store/util.rs (hunk 1 above)
Comment (BusyJay) [reply components/raftstore/src/store/util.rs:1017]: Then why it's checked first in the original implementation?

File: components/raftstore/src/store/peer.rs [hunk 7]
```diff
@@ -982,6 +983,10 @@ where
         // becoming a leader.
         self.maybe_update_read_progress(reader, progress);
 
+        // Update leader info
+        self.read_progress
```
Comment (BusyJay) [inline components/raftstore/src/store/peer.rs:987]: I find it's confusing. There are `maybe_update_read_progress` and `read_progress`, and they refer to different things.

File: components/raftstore/src/store/util.rs (hunk 1 above)
Comment (NingLin-P) [reply components/raftstore/src/store/util.rs:1017]: Just for robustness I think, the check is unnecessary since even it passes in this peer doesn't mean it can pass among majority peers. The `read_state` item should be promised valid when it is published by the leader instead of letting the receiver validated it with the receiver's limited information.

File: components/raftstore/src/store/peer.rs (hunk 7 above)
Comment (NingLin-P) [reply components/raftstore/src/store/peer.rs:987]: How about rename the `maybe_update_read_progress` to `maybe_update_leader_read_progress` or `maybe_update_lease_read_progress`?

File: components/raftstore/src/store/worker/check_leader.rs (hunk 5 above)
Comment (NingLin-P) [reply components/raftstore/src/store/worker/check_leader.rs:81]: Because `map` takes `FnMut`, I change it to `FnOnce` and remove the `clone` now.

File: components/raftstore/src/store/util.rs (hunk 1 above)
Comment (BusyJay) [reply components/raftstore/src/store/util.rs:1019]: /cc @5kbpers

File: components/raftstore/src/store/peer.rs (hunk 7 above)
Comment (BusyJay) [reply components/raftstore/src/store/peer.rs:987]: How about renaming `RegionReadProgress` to `SafeReadTracker`?

File: components/raftstore/src/store/fsm/store.rs [hunk 8]
```diff
@@ -126,8 +124,8 @@ pub struct StoreMeta {
     /// source_region_id -> need_atomic
     /// Used for reminding the source peer to switch to ready in `atomic_snap_regions`.
     pub destroyed_region_for_snap: HashMap<u64, bool>,
-
-    pub region_read_progress: HashMap<u64, Arc<RegionReadProgress>>,
+    /// region_id -> `RegionReadProgress`
+    pub region_read_progress: RegionReadProgressRegistry,
```
Comment (5kbpers) [inline components/raftstore/src/store/fsm/store.rs:128]: Should we remove `leaders` of `StoreMeta`?

File: components/resolved_ts/src/advance.rs [hunk 9]
```diff
@@ -136,68 +143,54 @@ impl<E: KvEngine> AdvanceTsWorker<E> {
...
-                                .push(leader_info);
-                        }
-                        region_map.insert(region_id, region.clone());
+        // region_id -> `(Vec<Peer>, LeaderInfo)`
+        let info_map = region_read_progress.dump_leader_infos(&regions);
+
+        for (region_id, (peer_list, leader_info)) in info_map {
+            let leader_id = leader_info.get_peer_id();
+            // Check if the leader in this store
+            match find_store_id(&peer_list, leader_id) {
```
Comment (BusyJay) [inline components/resolved_ts/src/advance.rs:163]: You mean `find_store_id(&peer_list, leader_id) != Some(store_id)`?

File: components/resolved_ts/src/advance.rs [hunk 10]
```diff
@@ -136,68 +143,54 @@ impl<E: KvEngine> AdvanceTsWorker<E> {
...
+                        continue;
                     }
                 }
             }
+            for peer in &peer_list {
+                if peer.store_id == store_id && peer.id == leader_id {
+                    resp_map.entry(region_id).or_default().push(store_id);
+                    continue;
+                }
+                store_map
```
Comment (BusyJay) [inline components/resolved_ts/src/advance.rs:176]: Why learner doesn't need to be filtered anymore?

File: components/resolved_ts/src/advance.rs (hunk 9 above)
Comment (NingLin-P) [reply components/resolved_ts/src/advance.rs:163]: Yes

File: components/resolved_ts/src/advance.rs (hunk 10 above)
Comment (NingLin-P) [reply components/resolved_ts/src/advance.rs:176]: The `CheckLeader` handling is port from `cdc`, and it is original for just checking leadership so filter learner to reduce request size, but now with `resolved-ts` it is also used to sync `read_state` from leader to follower/learner, so we don't filter learner anymore.

File: components/raftstore/src/store/peer.rs (hunk 7 above)
Comment (NingLin-P) [reply components/raftstore/src/store/peer.rs:987]: Renaming `RegionReadProgress` would be a huge change, if just to resolve the naming conflict I think it is better to change the less used one.

File: components/resolved_ts/src/advance.rs (hunk 10 above)
Comment (BusyJay) [reply components/resolved_ts/src/advance.rs:176]: Seems a bug, any test case?

File: components/resolved_ts/src/advance.rs [hunk 11]
```diff
@@ -127,6 +133,7 @@ impl<E: KvEngine> AdvanceTsWorker<E> {
     async fn region_resolved_ts_store(
```
Comment (5kbpers) [inline components/resolved_ts/src/advance.rs:133]: Could you update the related code in cdc or add a TODO comment there?

File: components/raftstore/src/store/fsm/store.rs [hunk 12]
```diff
@@ -126,8 +124,8 @@ pub struct StoreMeta {
     /// source_region_id -> need_atomic
     /// Used for reminding the source peer to switch to ready in `atomic_snap_regions`.
     pub destroyed_region_for_snap: HashMap<u64, bool>,
-
-    pub region_read_progress: HashMap<u64, Arc<RegionReadProgress>>,
+    /// region_id -> `RegionReadProgress`
```
[the remark this answers is not in the document]
Comment (NingLin-P) [reply components/raftstore/src/store/fsm/store.rs:127]: It is kept for `cdc` usage, we can remove it after `cdc` adopt the same change as `resolved-ts`

File: components/raftstore/src/store/util.rs [hunk 13]
```diff
@@ -836,6 +844,92 @@ impl Display for MsgType<'_> {
...
+        for leader_info in leaders {
+            let region_id = leader_info.get_region_id();
+            if let Some(rp) = registry.get(&region_id) {
+                if rp.consume_leader_info(leader_info) {
```
[the remark this answers is not in the document]
Comment (NingLin-P) [reply components/raftstore/src/store/util.rs:894]: `consume_leader_info` not just for checking leader info but also updating `safe_ts`, it do two jobs at once to reduce one `Mutex::lock` calling, `is_leader_info_valid` may not best fit.

File: components/resolved_ts/src/advance.rs (hunk 11 above)
Comment (NingLin-P) [reply components/resolved_ts/src/advance.rs:133]: Done

File: components/resolved_ts/src/advance.rs (hunk 10 above)
Comment (NingLin-P) [reply components/resolved_ts/src/advance.rs:171]: added, PTAL

File: components/raftstore/src/store/peer.rs (hunk 7 above)
Comment (NingLin-P) [reply components/raftstore/src/store/peer.rs:987]: Leave a TODO for now, will change it later.

File: components/raftstore/src/store/peer.rs [hunk 14]
```diff
@@ -1498,6 +1503,10 @@ where
             "term" => term,
             "peer_id" => self.peer_id(),
         );
+
+        self.read_progress
+            .update_leader_info(leader_id, term, self.region());
```
Comment (BusyJay) [inline components/raftstore/src/store/peer.rs:1508]: `region` may not be correct here. If it's an uninitialized peer, region's peer list can be empty.

Comment (NingLin-P) [reply components/raftstore/src/store/peer.rs:1508]: Yes, but we only use the leader's peer list. The `leader_info` will also be updated after snapshot applied and epoch changed, so the peer's `leader_info` will be corrected as it catches up with more data.

Comment (BusyJay) [reply components/raftstore/src/store/peer.rs:1508]: I don't think so. `update_leader_info` is only called when leadership changes, so even for leader, the peer list can become wrong after applying configuration change.

Comment (NingLin-P) [reply components/raftstore/src/store/peer.rs:1508]: Actaully,  `update_leader_info` is called inside `Peer::set_config`, `Peer::on_leader_changed` and `PeerFsmDelegate::on_ready_apply_snapshot`, it has cover all cases where the peer list, region epoch and leader id will change.

**Review by BusyJay — APPROVED** [review]

**Review by 5kbpers — APPROVED** [review]
