### PR TITLE
raftstore: match ready by batch_offset

### LINKED ISSUE #9388: ready can be advanced by a wrong peer
## Bug Report

Supposing peer (1, 1) is split into (1, 2) and (1, 1) on store 1. If it takes too long for peer 1 to apply snapshot and then split, an uninitialized peer 2 can be created first and then the split one will replace then uninitialized one.

If before peer 1 is split, peer 2 receives a message, then the uninitialized peer and split peer may be fetched in one batch. Because batch system maps ready to peer by ID, so if the uninitialized peer doesn't generate readiness, then the readiness generated by split peer will be mapped to uninitialized one as they have the same region ID.

In the past, uninitialized peer has to be a follower and can't be in merge state, so all messages in readiness will be sent and no other actions will be performed. Because peer is uninitialized, so no proposal has been handled, no read states will be queued. For the split peer, although ready is not advanced, but raft will happily create a duplicated ready and all paused progresses will be resumed except committed logs. Duplicated committed logs can make apply thread panic. Fortunately, there will usually be no committed logs for a just split peer.

Now we have used async ready, unmatched ready will lead to panic directly as the numbers probably don't matched.

/cc @NingLin-P @gengliqi

### PR DESCRIPTION
**Pull request by BusyJay**
### What problem does this PR solve?

Issue Number: close #9388 

What's Changed:

This PR adds a new field batch_offset to ready collection, which
indicates the offset of origin peer in the batch.

Stores the ready inside Fsm is an alternative, but it can occupy
unnecessary memory.

Using memory address of Fsm is also an alternative, though seems a
little hacky.

Both of the alternatives require a loop, using offset only needs to
query once. It may have improvement in clusters that have a lot of
regions and ticking usually doesn't generate readiness.

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- PR to update `pingcap/tidb-ansible`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 
- Fix wrong mapping between readies and peers by offset

### CODE REVIEW

**Review by NingLin-P — APPROVED** [review]

File: tests/failpoints/cases/test_split_region.rs [hunk 1]
```diff
@@ -380,3 +381,162 @@ fn test_split_not_to_split_exist_tombstone_region() {
...
+            if is_pending {
+                pending_msg.insert(from_peer_id, msg);
+                let sender = self.pending_count_sender.lock().unwrap();
+                sender.send(pending_msg.len()).unwrap();
+            } else {
+                to_send.push(msg);
+            }
+        }
+        msgs.extend(to_send);
+        Ok(())
```
Comment (gengliqi) [inline tests/failpoints/cases/test_split_region.rs:433]: How about using `check_messages(msgs)`?

File: tests/failpoints/cases/test_split_region.rs [hunk 2]
```diff
@@ -380,3 +381,162 @@ fn test_split_not_to_split_exist_tombstone_region() {
     fail::remove("on_raft_gc_log_tick");
     fail::remove(peer_check_stale_state_fp);
 }
+
+/// A filter that collects all snapshots.
+///
+/// It's different from the one in simulate_transport in two aspects:
+/// 1. It will not flush the collected snapshots.
+/// 2. It will not report error when collecting snapshots.
+/// 3. It callers can access the collected snapshots.
```
Comment (gengliqi) [inline tests/failpoints/cases/test_split_region.rs:390]: It seems three aspects.

**Review by gengliqi — COMMENTED** [review]
Rest LGTM

**Review by gengliqi — APPROVED** [review]

**Review by NingLin-P — APPROVED** [review]

**Review by ti-srebot — APPROVED** [review]
