### PR TITLE
test: fix unstable test test_node_merge_write_data_to_source_region_after_m…

### LINKED ISSUE #7909: cases::test_merge::test_node_merge_write_data_to_source_region_after_merging failed
cases::test_merge::test_node_merge_write_data_to_source_region_after_merging

 Latest failed builds: 
https://internal.pingcap.net/idc-jenkins/job/tikv_master_test_coverage/1268/consoleFull

### PR DESCRIPTION
**Pull request by NingLin-P**
…erging

Signed-off-by: linning <linningde25@gmail.com>

### What problem does this PR solve?

Issue Number: close #7909 

Problem Summary:

the test `test_node_merge_write_data_to_source_region_after_merging` first split then merge and then split at the same `split_key` again, the test panic because failed at the second split.

In the test, after the first split and before merge commit, the leader of the new region `s1` that generated by splitting, is isolated, but it keeps sending region epoch to PD with `epoch { conf_ver: 2, ver: 3 }`, the `conf_ver` increased because it is the source region.  The second split generated region `s2` which has the same start and end key with `s1`, and has` epoch { conf_ver: 1, ver: 5 }`, also sending region heartbeat to PD. But if `s1`'s request arrives before `s2` then `s2`'s request will be rejected and hence the test panic at `must_split`.

### What is changed and how it works?

What's Changed:

Changing how `check_stale_region` check epoch, let `ver` have higher priority than `conf_ver`, so that `epoch { conf_ver: 1, ver: 5 }` >= `epoch { conf_ver: 2, ver: 3 }`.

Tests 

- Integration test

### Release note 
- No release note

### CODE REVIEW

**Review by gengliqi — COMMENTED** [review]
I think maybe it's better to separate the `same` regions and the `different` regions.
If they are different regions, just check the version and panic if two versions are equal because it should not happen.
If they are the same, the check order is unnecessary because the epoch should be unique.

**Comment by NingLin-P** [comment]
> I think maybe it's better to separate the `same` regions and the `different` regions.
> If they are different regions, just check the version and panic if two versions are equal because it should not happen.
> If they are the same, the check order is unnecessary because the epoch should be unique.

The changes to `check_stale_region` are not for the case where `version` equal and `conf_ver` not, but to define order for cases like `epoch { conf_ver: 2, ver: 3 }` and `epoch { conf_ver: 1, ver: 5 }` where `a.ver` > `b.ver` but `b.conf_ver` > `a.conf_ver`.

**Comment by gengliqi** [comment]
> > I think maybe it's better to separate the `same` regions and the `different` regions.
> > If they are different regions, just check the version and panic if two versions are equal because it should not happen.
> > If they are the same, the check order is unnecessary because the epoch should be unique.
> 
> The changes to `check_stale_region` are not for the case where `version` equal and `conf_ver` not, but to define order for cases like `epoch { conf_ver: 2, ver: 3 }` and `epoch { conf_ver: 1, ver: 5 }` where `a.ver` > `b.ver` but `b.conf_ver` > `a.conf_ver`.

It's not possible if these two regions are the same.

**Comment by NingLin-P** [comment]
Depend on how you define two regions is the *same*. By the key range (which is also how `test_raftstore::TestPdClient` do), it's exactly what happens on `test_node_merge_write_data_to_source_region_after_merging`, checkout the abovementioned detail. @gengliqi

**Comment by gengliqi** [comment]
> Depend on how you define two regions is the _same_. By the key range (which is also how `test_raftstore::TestPdClient` do), it's exactly what happens on `test_node_merge_write_data_to_source_region_after_merging`, checkout the abovementioned detail. @gengliqi

The definition of two same regions is based on region id. If two regions are different, their epoch version can be compared if and only if their key ranges are overlapped.

**Comment by NingLin-P** [comment]
> The definition of two same regions is based on region id. If two regions are different, their epoch version can be compared if and only if their key ranges are overlapped.

That is what I mean depend on key range. In normal cases, both `confchange` and `split/merge` that can change epoch will show up in raft log, one by one in order, so incoming epoch should >= exist epoch on both `ver` and `conf_ver`, but when applying `prepare_merge` both `ver` and `conf_ver` of the source region will be increased, that is how the case where `a.ver > b.ver` but `b.conf_ver > a.conf_ver` happens.

File: components/test_raftstore/src/pd.rs [hunk 1]
```diff
@@ -415,118 +415,52 @@ impl Cluster {
...
-                    assert_eq!(peers.len(), 1);
-                    assert!(setdiff_peers(&cur_region, &region).is_empty());
-                }
-            }
-
-            // update the region.
-            assert!(self.regions.insert(end_key, region.clone()).is_some());
-        } else {
-            must_same_peers(&cur_region, &region);
+        // remove overlap regions
```
Comment (BusyJay) [inline components/test_raftstore/src/pd.rs:455]: Should it skip if incoming region is the same as existing one?

**Review by BusyJay — APPROVED** [review]

**Review by hicqu — APPROVED** [review]

**Review by ti-srebot — APPROVED** [review]
