### PR TITLE
raftstore: fix online config change panic for periodic-full-compact-start-time

### LINKED ISSUE #17066: tikv panic when update config online for “raftstore.periodic-full-compact-start-times”
### What version of TiKV are you using?
TiKV 
Release Version:   8.2.0-alpha
Edition:           Community
Git Commit Hash:   fba1fb2f65620b7ab1c03a9cf918ef3968969398
Git Commit Branch: heads/refs/tags/v8.2.0-alpha
UTC Build Time:    2024-05-23 11:38:52
Rust Version:      rustc 1.77.0-nightly (89e2160c4 2023-12-27)
Enable Features:   memory-engine pprof-fp jemalloc mem-profiling portable sse test-engine-kv-rocksdb test-engine-raft-raft-engine trace-async-tasks openssl-vendored
Profile:           dist_release

### What operating system and CPU are you using?
8c/32g

### Steps to reproduce
1、set config tikv `raftstore.periodic-full-compact-start-times`='["12:00 +0800","14:00 +0800"]';

### What did you expect?
no panic

### What did happened?
tikv panic when update config online for “raftstore.periodic-full-compact-start-times”

`{"level":"FATAL","log":"[lib.rs:477] [\"internal error: entered unreachable code\"] [backtrace=\"   0: tikv_util::set_panic_hook::{{closure}}\\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/tikv_util/src/lib.rs:476:18\\n   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call\\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2029:9\\n      std::panicking::rust_panic_with_hook\\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:783:13\\n   2: std::panicking::begin_panic_handler::{{closure}}\\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:649:13\\n   3: std::sys_common::backtrace::__rust_end_short_backtrace\\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:171:18\\n   4: rust_begin_unwind\\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:645:5\\n   5: core::panicking::panic_fmt\\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panicking.rs:72:14\\n   6: core::panicking::panic\\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panicking.rs:144:5\\n   7: tikv::config::to_change_value\\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/src/config/mod.rs:4654:14\\n      tikv::config::to_config_change::helper\\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/src/config/mod.rs:4613:38\\n   8: tikv::config::to_config_change::helper\\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/src/config/mod.rs:4607:32\\n   9: tikv::config::to_config_change\\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/src/config/mod.rs:4637:9\\n  10: tikv::config::ConfigController::update\\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/src/config/mod.rs:4799:20\\n  11: tikv::server::status_server::StatusServer<R>::update_config::{{closure}}\\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/src/server/status_server/mod.rs:310:17\\n  12: tikv::server::status_server::StatusServer<R>::start_serve::{{closure}}::{{closure}}::{{closure}}::{{closure}}\\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/src/server/status_server/mod.rs:700:82\\n  13: <hyper::proto::h1::dispatch::Server<S,hyper::body::body::Body> as hyper::proto::h1::dispatch::Dispatch>::poll_msg\\n             at var/cache/cargohome/registry/src/index.crates.io-6f17d22bba15001f/hyper-0.14.23/src/proto/h1/dispatch.rs:491:35\\n      hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_write\\n             at var/cache/cargohome/registry/src/index.crates.io-6f17d22bba15001f/hyper-0.14.23/src/proto/h1/dispatch.rs:297:43\\n      hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_loop\\n             at var/cache/cargohome/registry/src/index.crates.io-6f17d22bba15001f/hyper-0.14.23/src/proto/h1/dispatch.rs:161:21\\n      hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_inner\\n             at var/cache/cargohome/registry/src/index.crates.io-6f17d22bba15001f/hyper-0.14.23/src/proto/h1/dispatch.rs:137:16\\n      hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_catch\\n             at var/cache/cargohome/registry/src/index.crates.io-6f17d22bba15001f/hyper-0.14.23/src/proto/h1/dispatch.rs:120:28\\n      <hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T> as core::future::future::Future>::poll\\n             at var/cache/cargohome/registry/src/index.crates.io-6f17d22bba15001f/hyper-0.14.23/src/proto/h1/dispatch.rs:424:9\\n      <hyper::server::conn::ProtoServer<T,B,S,E> as core::future::future::Future>::poll\\n             at var/cache/cargohome/registry/src/index.crates.io-6f17d22bba15001f/hyper-0.14.23/src/server/conn.rs:952:50\\n  14: <hyper::server::conn::upgrades::UpgradeableConnection<I,S,E> as core::future::future::Future>::poll\\n             at var/cache/cargohome/registry/src/index.crates.io-6f17d22bba15001f/hyper-0.14.23/src/server/conn.rs:1012:30\\n      <hyper::common::drain::Watching<F,FN> as core::future::future::Future>::poll\\n      <hyper::server::server::new_svc::NewSvcTask<I,N,S,E,W> as core::future::future::Future>::poll\\n             at var/cache/cargohome/registry/src/index.crates.io-6f17d22bba15001f/hyper-0.14.23/src/server/server.rs:741:36\\n  15: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}\\n             at var/cache/cargohome/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.25.3/src/runtime/task/core.rs:223:17\\n      tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut\\n             at var/cache/cargohome/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.25.3/src/loom/std/unsafe_cell.rs:14:9\\n      tokio::runtime::task::core::Core<T,S>::poll\\n             at var/cache/cargohome/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.25.3/src/runtime/task/core.rs:212:13\\n      tokio::runtime::task::harness::poll_future::{{closure}}\\n             at var/cache/cargohome/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.25.3/src/runtime/task/harness.rs:476:19\\n      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once\\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panic/unwind_safe.rs:272:9\\n      std::panicking::try::do_call\\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:552:40\\n      std::panicking::try\\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:516:19\\n      std::panic::catch_unwind\\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:142:14\\n      tokio::runtime::task::harness::poll_future\\n             at var/cache/cargohome/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.25.3/src/runtime/task/harness.rs:464:18\\n      tokio::runtime::task::harness::Harness<T,S>::poll_inner\\n             at var/cache/cargohome/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.25.3/src/runtime/task/harness.rs:198:27\\n      tokio::runtime::task::harness::Harness<T,S>::poll\\n             at var/cache/cargohome/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.25.3/src/runtime/task/harness.rs:152:15\\n      tokio::runtime::task::raw::poll\\n             at var/cache/cargohome/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.25.3/src/runtime/task/raw.rs:255:5\\n  16: tokio::runtime::task::raw::RawTask::poll\\n             at var/cache/cargohome/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.25.3/src/runtime/task/raw.rs:200:18\\n      tokio::runtime::task::LocalNotified<S>::run\\n             at var/cache/cargohome/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.25.3/src/runtime/task/mod.rs:394:9\\n      tokio::runtime::scheduler::multi_thread::worker::Context::run_task::{{closure}}\\n             at var/cache/cargohome/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.25.3/src/runtime/scheduler/multi_thread/worker.rs:464:18\\n      tokio::runtime::coop::with_budget\\n             at var/cache/cargohome/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.25.3/src/runtime/coop.rs:102:5\\n      tokio::runtime::coop::budget\\n             at var/cache/cargohome/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.25.3/src/runtime/coop.rs:68:5\\n      tokio::runtime::scheduler::multi_thread::worker::Context::run_task\\n             at var/cache/cargohome/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.25.3/src/runtime/scheduler/multi_thread/worker.rs:463:9\\n  17: tokio::runtime::scheduler::multi_thread::worker::Context::run\\n             at var/cache/cargohome/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.25.3/src/runtime/scheduler/multi_thread/worker.rs:426:24\\n      tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}\\n             at var/cache/cargohome/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.25.3/src/runtime/scheduler/multi_thread/worker.rs:406:17\\n      tokio::macros::scoped_tls::ScopedKey<T>::set\\n             at var/cache/cargohome/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.25.3/src/macros/scoped_tls.rs:61:9\\n      tokio::runtime::scheduler::multi_thread::worker::run\\n             at var/cache/cargohome/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.25.3/src/runtime/scheduler/multi_thread/worker.rs:403:5\\n  18: tokio::runtime::scheduler::multi_thread::worker::Launch::launch::{{closure}}\\n             at var/cache/cargohome/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.25.3/src/runtime/scheduler/multi_thread/worker.rs:365:45\\n      <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll\\n             at var/cache/cargohome/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.25.3/src/runtime/blocking/task.rs:42:21\\n      tokio::runtime::task::core::Core<T,S>::poll::{{closure}}\\n             at var/cache/cargohome/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.25.3/src/runtime/task/core.rs:223:17\\n      tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut\\n             at var/cache/cargohome/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.25.3/src/loom/std/unsafe_cell.rs:14:9\\n      tokio::runtime::task::core::Core<T,S>::poll\\n             at var/cache/cargohome/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.25.3/src/runtime/task/core.rs:212:13\\n      tokio::runtime::task::harness::poll_future::{{closure}}\\n             at var/cache/cargohome/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.25.3/src/runtime/task/harness.rs:476:19\\n      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once\\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panic/unwind_safe.rs:272:9\\n      std::panicking::try::do_call\\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:552:40\\n      std::panicking::try\\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:516:19\\n      std::panic::catch_unwind\\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:142:14\\n      tokio::runtime::task::harness::poll_future\\n             at var/cache/cargohome/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.25.3/src/runtime/task/harness.rs:464:18\\n      tokio::runtime::task::harness::Harness<T,S>::poll_inner\\n             at var/cache/cargohome/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.25.3/src/runtime/task/harness.rs:198:27\\n      tokio::runtime::task::harness::Harness<T,S>::poll\\n             at var/cache/cargohome/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.25.3/src/runtime/task/harness.rs:152:15\\n      tokio::runtime::task::raw::poll\\n             at var/cache/cargohome/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.25.3/src/runtime/task/raw.rs:255:5\\n  19: tokio::runtime::task::raw::RawTask::poll\\n             at var/cache/cargohome/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.25.3/src/runtime/task/raw.rs:200:18\\n      tokio::runtime::task::UnownedTask<S>::run\\n             at var/cache/cargohome/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.25.3/src/runtime/task/mod.rs:431:9\\n      tokio::runtime::blocking::pool::Task::run\\n             at var/cache/cargohome/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.25.3/src/runtime/blocking/pool.rs:159:9\\n      tokio::runtime::blocking::pool::Inner::run\\n             at var/cache/cargohome/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.25.3/src/runtime/blocking/pool.rs:511:17\\n      tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}\\n             at var/cache/cargohome/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.25.3/src/runtime/blocking/pool.rs:469:13\\n      std::sys_common::backtrace::__rust_begin_short_backtrace\\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:155:18\\n  20: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}\\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:529:17\\n      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once\\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panic/unwind_safe.rs:272:9\\n      std::panicking::try::do_call\\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:552:40\\n      std::panicking::try\\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:516:19\\n      std::panic::catch_unwind\\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:142:14\\n      std::thread::Builder::spawn_unchecked_::{{closure}}\\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:528:30\\n      core::ops::function::FnOnce::call_once{{vtable.shim}}\\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5\\n  21: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once\\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2015:9\\n      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once\\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2015:9\\n      std::sys::unix::thread::Thread::new::thread_start\\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys/unix/thread.rs:108:17\\n  22: start_thread\\n  23: clone\\n\"] [location=src/config/mod.rs:4654] [thread_name=status-server] [thread_id=132]","pod":"tc-tikv-0","container":"tikv","namespace":"testbed-glh-5rtws"}`

### PR DESCRIPTION
**Pull request by SpadeA-Tang**
### What is changed and how it works?

Issue Number: Close #17066

What's Changed:

```commit-message
fix online config change panic for periodic-full-compact-start-time
```
image

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [ ] Need to cherry-pick to the release branch

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by SpadeA-Tang** [comment]
@afeinberg PTAL

**Review by LykxSassinator — COMMENTED** [review]
LGTM

**Review by LykxSassinator — APPROVED** [review]

File: src/config/mod.rs [hunk 1]
```diff
@@ -4651,7 +4652,11 @@ fn to_change_value(v: &str, typed: &ConfigValue) -> CfgResult<ConfigValue> {
         ConfigValue::Usize(_) => ConfigValue::from(v.parse::<usize>()?),
         ConfigValue::Bool(_) => ConfigValue::from(v.parse::<bool>()?),
         ConfigValue::String(_) => ConfigValue::String(v.to_owned()),
-        _ => unreachable!(),
+        ConfigValue::Schedule(_) => {
+            let schedule = v.parse::<ReadableSchedule>()?;
+            ConfigValue::from(schedule)
+        }
+        ConfigValue::Skip | ConfigValue::None | ConfigValue::Module(_) => unreachable!(),
```
Comment (overvenus) [inline src/config/mod.rs:4659]: How about logging  and returning an error?

Comment (SpadeA-Tang) [reply src/config/mod.rs:4659]: ConfigValue::Skip | ConfigValue::None | ConfigValue::Module(_) will and should not be reached. I think it's fine as unlike the previous `_ => unreachable!()`, which may forget to implement some type, it is intentional.

**Review by Connor1996 — APPROVED** [review]
LGTM

File: tests/integrations/config/test_config_client.rs [hunk 2]
```diff
@@ -25,6 +26,29 @@ fn test_update_config() {
...
+        .update(change(
+            "raftstore.periodic-full-compact-start-times",
+            "[\"12:00 +0800\",\"14:00 +0800\"]",
+        ))
+        .unwrap();
+    cfg.raft_store.periodic_full_compact_start_times = ReadableSchedule(vec![
+        ReadableOffsetTime::from_str("12:00 +0800").unwrap(),
+        ReadableOffsetTime::from_str("14:00 +0800").unwrap(),
+    ]);
+    assert_eq!(cfg_controller.get_current(), cfg);
```
Comment (zhangjinpeng87) [inline tests/integrations/config/test_config_client.rs:39]: This case will fail if run in timezone different with +8.
