### PR TITLE
txn_status_cache: avoid deadlock in txn_status_cache with Pipelined DML

### LINKED ISSUE #18384: Deadlock in txn_status_cache with Pipelined DML
### What version of TiKV are you using?

master

### Steps to reproduce

Run a long Pipelined DML and it has an opportunity to happen

### What did you expect?

No deadlock.

### What did happened?

There is a deadlock in the scheduler pool. According to the metrics, the threads seem to be hanging.
Pending tasks in scheduler and resolved-ts both pile up

### PR DESCRIPTION
**Pull request by ekexium**
### What is changed and how it works?

Issue Number: Close #18384 

What's Changed:

```commit-message
Fix the deadlock issue in txn_status_cache.
When both large_txn_cache and normal_cache needs locking, always acquire large_txn_cache first.
```

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [ ] Need to cherry-pick to the release branch

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note

```release-note
Fix the deadlock issue in txn_status_cache.
```

### CODE REVIEW

File: src/storage/txn/txn_status_cache.rs [hunk 1]
```diff
@@ -1513,4 +1522,53 @@ mod tests {
...
+        thread::sleep(Duration::from_millis(300));
+
+        // Release the failpoints
+        fail::remove("txn_status_cache_get_after_large_before_normal");
+        fail::remove("txn_status_cache_upsert_after_normal_before_large");
+
+        // if deadlock, thread1 will not join, test will hang here
+        thread1.join().unwrap();
+        thread2.join().unwrap();
+        drop(scenario);
```
Comment (MyonKeminta) [inline src/storage/txn/txn_status_cache.rs:1572]: Is this needed?

**Review by cfzjywxk — APPROVED** [review]

File: src/storage/txn/txn_status_cache.rs (hunk 1 above)
Comment (ekexium) [reply src/storage/txn/txn_status_cache.rs:1572]: Not necessary, but just to make the usage explcit. Removed

**Review by MyonKeminta — APPROVED** [review]
