### PR TITLE
codec: add compile time assert to guarantee safety

### LINKED ISSUE #11356: `try_decode_first_internal` is unsafe as incorrect implemented trait can lead to undefined behavior
## Development Task

If `T::get_raw_padding_ptr()` returns a pointer, which points to a buffer less than `padding_size`, out of bound access may occur in `memcmp`.

https://github.com/tikv/tikv/blob/37e3395231bfb477895884126734526e898f9d26/components/codec/src/byte.rs#L374-L380

Fortunately, the trait is correctly implemented for all structs currently.

### PR DESCRIPTION
**Pull request by BusyJay**
### What problem does this PR solve?

Issue Number: close #11356.

### Check List 

Tests 

- Unit test
- Integration test

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by skyzh — COMMENTED** [review]
Why is this a compile-time check? It seems that `padding_size` is calculated by `let padding_size = T::parse_padding_size(*src_ptr.add(MEMCMP_GROUP_SIZE));`, which can only be known at runtime.

File: components/codec/src/byte.rs [hunk 1]
```diff
@@ -372,7 +367,8 @@ impl MemComparableByteCodec {
                     // is faster than checking pad bytes one by one, since it will compare multiple
                     // bytes at once.
                     let base_padding_ptr = dest_ptr.sub(padding_size);
-                    let expected_padding_ptr = T::get_raw_padding_ptr();
+                    // Force a compile time check to ensure safety. The check will be optimized away.
+                    let expected_padding_ptr = T::PADDING[..padding_size].as_ptr();
```
Comment (breeswish) [inline components/codec/src/byte.rs:371]: padding_size is not a constant but a variable, how would compiler discover that there is out of bound possibility?

Comment (BusyJay) [reply components/codec/src/byte.rs:371]: Because L362 has checked that `padding_size <= MEMCMP_GROUP_SIZE`, and the len of `T::PADDING` is exact `MEMCMP_GROUP_SIZE`. /cc @skyzh

Comment (skyzh) [reply components/codec/src/byte.rs:373]: This sounds reasonable to me.

**Review by skyzh — APPROVED** [review]

**Review by breeswish — APPROVED** [review]

**Comment by BusyJay** [comment]
/test

The failed case is traced at #11365.
