### PR TITLE
util: avoid panic in RotatingFileLogger

### LINKED ISSUE #4312: RotatingFileLoggerPanics on drop
It's not ok generally to panic in destructors because of the risk of double-panic ([see api guide](https://rust-lang-nursery.github.io/api-guidelines/dependability.html#destructors-never-fail-c-dtor-fail)), which causes an abort.

RotatingFileLogger's drop method calls `close` which calls `flush` on a file, which can fail. It then unwraps that result, potentially panicking. The best that con be done by the time the dtor is called is to silently ignore the failed call to `close` and hope for the best.

### PR DESCRIPTION
**Pull request by kennytm**
## What have you changed? (mandatory)

Refactored RotatingFileLogger such that the `file` member can never be `None`, using the fact that it's fine to rename an open file on Unix. This removed all `.unwrap()`s and `assert!`s associated with `file`, which may be triggered if `rotate()` errored in the middle. 

Additionally, rewritten `rotation_file_path_with_timestamp()` so it won't panic even if the log path contains non-UTF-8 bytes (won't happen in reality since the config is a `String`). 

Now the only source of panic is when `log_file` is literally `"/"` or from the standard library.

On `drop()` we just flush the file and ignore any error, which fixes #4312.

## What are the type of the changes? (mandatory)

- Bug fix (change which fixes an issue)

## How has this PR been tested? (mandatory)

Unit test.

## Does this PR affect documentation (docs) update? (mandatory)

No

## Does this PR affect tidb-ansible update? (mandatory)

No.

### CODE REVIEW

File: src/util/logger/file_log.rs [hunk 1]
```diff
@@ -75,23 +68,27 @@ impl RotatingFileLogger {
...
         Utc::now() > self.next_rotation_time
     }
 
     /// Rotates the current file and updates the next rotation time.
     fn rotate(&mut self) -> io::Result<()> {
-        self.close()?;
+        self.flush()?;
+
         let new_path = rotation_file_path_with_timestamp(&self.file_path, &Utc::now());
+        let mut tmp_new_path = new_path.clone().into_os_string();
```
Comment (BusyJay) [inline src/util/logger/file_log.rs]: Why not just move L85 and L90 to L80? Temp files seem unnecessary.

Comment (kennytm) [reply src/util/logger/file_log.rs]: OK fixed in 00b77ea.

File: src/util/logger/file_log.rs [hunk 2]
```diff
@@ -75,23 +68,21 @@ impl RotatingFileLogger {
...
     fn should_rotate(&mut self) -> bool {
         Utc::now() > self.next_rotation_time
     }
 
     /// Rotates the current file and updates the next rotation time.
     fn rotate(&mut self) -> io::Result<()> {
-        self.close()?;
+        self.flush()?;
+
+        // Note: renaming files while they're open only works on Linux and macOS.
```
Comment (Hoverbear) [inline src/util/logger/file_log.rs]: Why not close it? Seems it's more compatible.

Comment (kennytm) [reply src/util/logger/file_log.rs]: So that even if the new file failed to be opened for whatever reason we could still write logs to the old file. Plus `File::close` doesn't exist 🙃

**Comment by kennytm** [comment]
/run-integration-ddl-test

👀 

> dial tcp 127.0.0.1:5000: connect: connection refused ("dial tcp 127.0.0.1:5000: connect: connection refused")
