### PR TITLE
raftstore: handle conf change with snapshot correctly

### LINKED ISSUE #6344: Panic on late arriving confchange result
## Bug Report

TiKV panicked on https://github.com/tikv/tikv/blob/29bf2ac8f72f737f17988889b2cbfb2eb5e1e010/src/raftstore/store/fsm/peer.rs#L1442-L1445

```
[2019/12/26 07:42:17.689 +00:00] [INFO] [apply.rs:1050] ["execute admin command"] [command="cmd_type: ChangePeer change_peer { peer { id: 2767 store_id: 5 } }"] [index=422636] [term=1557] [peer_id=2553] [region_id=2]
[2019/12/26 07:42:17.689 +00:00] [INFO] [apply.rs:1382] ["exec ConfChange"] [epoch="conf_ver: 81 version: 51"] [type=AddNode] [peer_id=2553] [region_id=2]
[2019/12/26 07:42:17.689 +00:00] [INFO] [apply.rs:1437] ["add peer successfully"] [region="id: 2 start_key: 7480000000000000FF2B5F728000000038FFC5CFB90000000000FA region_epoch { conf_ver: 81 version: 51 } peers { id: 2553 store_id: 4 } peers { id: 2685 store_id: 1 } peers { id: 2749 store_id: 6 } peers { id: 2767 store_id: 5 is_learner: true }"] [peer="id: 2767 store_id: 5"] [peer_id=2553] [region_id=2]

[2019/12/26 07:42:18.664 +00:00] [INFO] [snap.rs:223] ["saving snapshot file"] [file=/var/lib/tikv/data/snap/rev_2_1558_425640_(default|lock|write).sst] [snap_key=2_1558_425640]
[2019/12/26 07:42:18.669 +00:00] [INFO] [raft.rs:2244] ["[commit: 422678, lastindex: 422679, lastterm: 1557] starts to restore snapshot [index: 425640, term: 1558]"] [tag="[region 2] 2553"] [snapshot_term=1558] [snapshot_index=425640] [last_term=1557] [last_index=422679] [commit=422678] [id=2553]
[2019/12/26 07:42:18.669 +00:00] [INFO] [raft_log.rs:519] ["[region 2] 2553 log [committed=422678, applied=422590, unstable.offset=422680, unstable.entries.len()=0] starts to restore snapshot [index: 425640, term: 1558]"] [snapshot_term=1558] [snapshot_index=425640] [log="committed=422678, applied=422590, unstable.offset=422680, unstable.entries.len()=0"] [tag="[region 2] 2553"] [tag="[region 2] 2553"]
[2019/12/26 07:42:18.669 +00:00] [INFO] [raft.rs:2176] ["[commit: 425640, term: 1558] restored snapshot [index: 425640, term: 1558]"] [tag="[region 2] 2553"] [snapshot_term=1558] [snapshot_index=425640] [commit=425640] [term=1558] [id=2553]

[2019/12/26 07:42:19.096 +00:00] [FATAL] [lib.rs:481] ["[region 2] 2553 apply conf change ChangePeer { conf_change: node_id: 2767 context: 0A0F0802120508BD1510062A04085110331A0B08011207120508CF151005, peer: id: 2767 store_id: 5, region: id: 2 start_key: 7480000000000000FF2B5F728000000038FFC5CFB90000000000FA region_epoch { conf_ver: 82 version: 51 } peers { id: 2553 store_id: 4 } peers { id: 2685 store_id: 1 } peers { id: 2749 store_id: 6 } peers { id: 2767 store_id: 5 } } fails: Exists(2767, \"voters\")"] [backtrace="stack backtrace:\n   0: tikv_util::set_panic_hook::{{closure}}\n             at components/tikv_util/src/lib.rs:480\n   1: std::panicking::rust_panic_with_hook\n             at src/libstd/panicking.rs:481\n   2: std::panicking::continue_panic_fmt\n             at src/libstd/panicking.rs:384\n   3: std::panicking::begin_panic_fmt\n             at src/libstd/panicking.rs:339\n   4: tikv::raftstore::store::fsm::peer::PeerFsmDelegate<T,C>::on_ready_result\n             at /home/jenkins/agent/workspace/tikv_ghpr_build_release/tikv/src/raftstore/store/fsm/peer.rs:0\n   5: tikv::raftstore::store::fsm::peer::PeerFsmDelegate<T,C>::on_apply_res\n             at /home/jenkins/agent/workspace/tikv_ghpr_build_release/tikv/src/raftstore/store/fsm/peer.rs:825\n   6: tikv::raftstore::store::fsm::peer::PeerFsmDelegate<T,C>::handle_msgs\n             at /home/jenkins/agent/workspace/tikv_ghpr_build_release/tikv/src/raftstore/store/fsm/peer.rs:301\n   7: <tikv::raftstore::store::fsm::store::RaftPoller<T,C> as tikv::raftstore::store::fsm::batch::PollHandler<tikv::raftstore::store::fsm::peer::PeerFsm,tikv::raftstore::store::fsm::store::StoreFsm>>::handle_normal\n             at /home/jenkins/agent/workspace/tikv_ghpr_build_release/tikv/src/raftstore/store/fsm/store.rs:649\n      tikv::raftstore::store::fsm::batch::Poller<N,C,Handler>::poll\n             at /home/jenkins/agent/workspace/tikv_ghpr_build_release/tikv/src/raftstore/store/fsm/batch.rs:322\n      tikv::raftstore::store::fsm::batch::BatchSystem<N,C>::spawn::{{closure}}\n             at /home/jenkins/agent/workspace/tikv_ghpr_build_release/tikv/src/raftstore/store/fsm/batch.rs:393\n      std::sys_common::backtrace::__rust_begin_short_backtrace\n             at /rustc/c6e9c76c59e3c10acd63ca9ec157a8894ea1a068/src/libstd/sys_common/backtrace.rs:77\n2019/12/26 07:42:19 daemon.go:236: ESC[0;33m[warning] daemon tikv exit with error exit status 1ESC[0m
```

The panic is caused by confchange result arrives after applying snapshot, so there is a chance that the membership has been updated before calling `apply_conf_change`, and it may panic as the log above.

A simple fix would be stashing snapshot message if `ready_to_handle_pending_snap` is false, so we can ensure all pending apply results are handled before stepping the snapshot message.

### PR DESCRIPTION
**Pull request by hicqu**
###  What have you changed?

Handle conf change with snapshot correctly. Close #6344 .

###  What is the type of the changes?
- Bugfix (a change which fixes an issue)

###  How is the PR tested?
- [x] No code

###  Does this PR affect documentation (docs) or should it be mentioned in the release notes?
No.

###  Does this PR affect `tidb-ansible`?
No.

###  Refer to a related PR or issue link (optional)
For some other fields in `Raft` which is changed on apply:
apply index: because `Raft::restore(snap)` won't change `applied_index`, so it's ok.

### CODE REVIEW

File: src/raftstore/store/fsm/peer.rs [hunk 1]
```diff
@@ -1439,10 +1439,13 @@ impl<'a, T: Transport, C: PdClient> PeerFsmDelegate<'a, T, C> {
     fn on_ready_change_peer(&mut self, cp: ChangePeer) {
         let change_type = cp.conf_change.get_change_type();
         if let Err(e) = self.fsm.peer.raft_group.apply_conf_change(&cp.conf_change) {
-            panic!(
-                "{} apply conf change {:?} fails: {:?}",
-                self.fsm.peer.tag, cp, e
-            );
+            match e {
+                raft::Error::Exists(_, _) | raft::Error::NotExists(_, _) => {}
```
Comment (overvenus) [inline src/raftstore/store/fsm/peer.rs]: As a bugfix, please add some comments and a test to cover the change.

Comment (overvenus) [reply src/raftstore/store/fsm/peer.rs]: Could add some comment here to explain why these errors can be ignored?

File: tests/integrations/raftstore/test_conf_change.rs [hunk 2]
```diff
@@ -926,3 +927,41 @@ where
...
+
+// The test is for this situation:
+// suppose there are 3 peers (1, 2, and 3) in a Raft group, and then
+// 1. propose to add peer 4 on the current leader 1;
+// 2. leader 1 thinks 3 is pending, and prepares a snapshot to peer 3;
+// 3. leadership is transfered to peer 2, and peer 2 sends append entries to 3;
+// 4. the snapshot reaches peer 3, and peer 3 restores it;
+// 5. peer 3 handles apply entries result, could find a redundant confchange.
+#[test]
+fn test_redundant_conf_change_by_snapshot() {
```
Comment (overvenus) [inline tests/integrations/raftstore/test_conf_change.rs]: The test is failed on CI, could you fix it?

File: tests/integrations/raftstore/test_conf_change.rs [hunk 3]
```diff
@@ -926,3 +927,41 @@ where
...
+    test_util::setup_for_ci();
```
Comment (overvenus) [inline tests/integrations/raftstore/test_conf_change.rs]: It should be removed.

File: tests/integrations/raftstore/test_conf_change.rs [hunk 4]
```diff
@@ -926,3 +927,41 @@ where
...
+            .direction(Direction::Send)
+            .msg_type(MessageType::MsgAppend),
+    );
+    cluster.sim.wl().add_send_filter(1, filter);
+    for _ in 0..5 {
+        cluster.must_put(b"k1", b"v1");
+    }
+    sleep_ms(100);
+
+    cluster.pd_client.must_add_peer(1, new_peer(4, 4));
```
Comment (overvenus) [inline tests/integrations/raftstore/test_conf_change.rs]: I think test can pass even without the fix.

File: src/raftstore/store/fsm/peer.rs [hunk 5]
```diff
@@ -1443,12 +1443,19 @@ impl<'a, T: Transport, C: PdClient> PeerFsmDelegate<'a, T, C> {
...
+            // Please take a look at test case test_redundant_conf_change_by_snapshot.
+            return;
+        }
+
         let change_type = cp.conf_change.get_change_type();
-        if let Err(e) = self.fsm.peer.raft_group.apply_conf_change(&cp.conf_change) {
-            panic!(
+        match self.fsm.peer.raft_group.apply_conf_change(&cp.conf_change) {
+            Ok(_) => {}
+            Err(raft::Error::NotExists(_, _)) | Err(raft::Error::Exists(_, _)) => {}
```
Comment (overvenus) [inline src/raftstore/store/fsm/peer.rs]: Could you remove this line, because they should not happen with changes L1446-L1449.

Comment (hicqu) [reply src/raftstore/store/fsm/peer.rs]: It can still happen. Because PD could send a command many times.

File: tests/failpoints/cases/test_conf_change.rs [hunk 6]
```diff
@@ -204,3 +207,59 @@ fn test_stale_peer_cache() {
     fail::cfg("stale_peer_cache_2", "return").unwrap();
     cluster.must_put(b"k2", b"v2");
 }
+
+// The test is for this situation:
+// suppose there are 3 peers (1, 2, and 3) in a Raft group, and then
+// 1. propose to add peer 4 on the current leader 1;
+// 2. leader 1 appends entries to peer 3, and peer 3 applys them;
+// 3. the leadersip is transfered to peer 2, and peer 2 sends a snapshot to 3;
```
Comment (BusyJay) [inline tests/failpoints/cases/test_conf_change.rs]: If peer 2 sends a snapshot to 3, it means the snapshot has to contain configuration (1, 2, 3, 4). How can step 6 happen?

File: src/raftstore/store/fsm/peer.rs [hunk 7]
```diff
@@ -1451,12 +1451,19 @@ impl<'a, T: Transport, C: PdClient> PeerFsmDelegate<'a, T, C> {
...
+            Err(e) => panic!(
```
[the remark this answers is not in the document]
Comment (hicqu) [reply src/raftstore/store/fsm/peer.rs]: Seems other errors is covered other lines. So it will be unreachable.

File: tests/failpoints/cases/test_conf_change.rs [hunk 8]
```diff
@@ -204,3 +209,79 @@ fn test_stale_peer_cache() {
...
+        RegionPacketFilter::new(1, 3)
+            .direction(Direction::Send)
+            .msg_type(MessageType::MsgAppend)
+            .when(Arc::new(AtomicBool::new(false)))
+            .set_msg_callback(cb),
+    );
+    cluster.sim.wl().add_send_filter(3, filter);
+
+    cluster.must_transfer_leader(1, new_peer(3, 3));
+    assert!(rx.recv_timeout(Duration::from_secs(3)).is_err());
```
Comment (BusyJay) [inline tests/failpoints/cases/test_conf_change.rs]: Try recv is enough. If peer (4, 4) is in memory, a request vote must have been sent already.

File: tests/failpoints/cases/test_conf_change.rs [hunk 9]
```diff
@@ -204,3 +209,79 @@ fn test_stale_peer_cache() {
...
+        }
+    }) as Arc<dyn Fn(&RaftMessage) + Send + Sync>;
+    let filter = Box::new(
+        RegionPacketFilter::new(1, 3)
+            .direction(Direction::Send)
+            .msg_type(MessageType::MsgAppend)
+            .when(Arc::new(AtomicBool::new(false)))
+            .set_msg_callback(cb),
+    );
+    cluster.sim.wl().add_send_filter(3, filter);
```
Comment (BusyJay) [inline tests/failpoints/cases/test_conf_change.rs]: Better add the filter before L264.

File: tests/failpoints/cases/test_conf_change.rs [hunk 10]
```diff
@@ -204,3 +209,79 @@ fn test_stale_peer_cache() {
...
+
+    // Transfer leader to peer 2, and append more entries to compact raft logs.
+    cluster.must_transfer_leader(1, new_peer(2, 2));
+    cluster.pd_client.must_remove_peer(1, new_peer(4, 4));
+    (0..10).for_each(|_| cluster.must_put(b"k2", b"v2"));
+    sleep_ms(50);
+
+    // Clear filters on peer 3, so it can receive and restore a snapshot.
+    cluster.sim.wl().clear_recv_filters(3);
+    sleep_ms(100);
```
Comment (BusyJay) [inline tests/failpoints/cases/test_conf_change.rs]: Why sleep?

Comment (hicqu) [reply tests/failpoints/cases/test_conf_change.rs]: Without sleep the snapshot may come after peer 3 calling `apply_conf_change`.

File: tests/failpoints/cases/test_conf_change.rs (hunk 9 above)
Comment (hicqu) [reply tests/failpoints/cases/test_conf_change.rs]: Why? I think only need to be before transferring leadership to peer 3.
