### PR TITLE
raftstore-v2: persist applied index after ingset sst

### LINKED ISSUE #15461: [Dynamic Regions] many sst files left in the import directory after br restore
### What version of TiKV are you using?

nightly

### Steps to reproduce

I used br to restore about 500GB data into a fresh cluster with partition-raft-kv enabled. After br finished I found there were about 1200 sst filed under the import dir with a total size about 55GB. And after 24h, these sst files were still not cleaned up.

And when I restart the cluster I could see a lot of ingest sst operations in the tikv log. This also make the restart much longer than expected before the foreground qps is stable.

### What did you expect?
No or little sst files should be left for a long time after br restore.

### PR DESCRIPTION
**Pull request by glorv**
### What is changed and how it works?

Issue Number: Close #15461

What's Changed:

```
Add ingest sst index to ApplyRes and return it to raftstore and store these ingest index in apply trace. In check advance admin index, if there are and sst ingest before this flush, directly trigger a new flush. And also try to gc stale sst files after the write task is persisted.
```

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
 - In my local env, after this change there is no sst files leat in the import dir after br restore. Before this change, there are handreds of ssts there.
- No code

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

```release-note
None
```

### CODE REVIEW

File: components/raftstore-v2/src/operation/ready/apply_trace.rs [hunk 1]
```diff
@@ -283,17 +312,40 @@ impl ApplyTrace {
...
             self.admin.flushed = candidate;
-            if self.admin.flushed > self.persisted_applied + 100 {
+            if has_ingested_sst || (self.admin.flushed > self.persisted_applied + 100) {
                 self.try_persist = true;
             }
         }
         // TODO: persist admin.flushed every 10 minutes.
     }
 
+    fn advance_flushed_index_for_ingest(&mut self, max_index: u64) -> bool {
```
Comment (SpadeA-Tang) [inline components/raftstore-v2/src/operation/ready/apply_trace.rs:329]: I think what we want is use pending_sst_ranges to advance admin.flushed. The code here just decides whether to persist admin.flushed but not trully advance it.

File: components/raftstore-v2/src/operation/ready/apply_trace.rs [hunk 2]
```diff
@@ -809,6 +923,56 @@ mod tests {
...
+                    assert_eq!(r, e);
+                });
+        }
+
+        trace.on_modify(CF_DEFAULT, 8);
+        let ingested_ssts_idx =
+            make_sst_apply_index(vec![(CF_DEFAULT, 6), (CF_WRITE, 6), (CF_DEFAULT, 7)]);
+        trace.on_sst_ingested(&ingested_ssts_idx);
+        trace.maybe_advance_admin_flushed(8);
+        assert_eq!(5, trace.admin.flushed);
```
Comment (SpadeA-Tang) [inline components/raftstore-v2/src/operation/ready/apply_trace.rs:925]: Follows above comment. Here take the DEFAULT as example. The [flushed, last_modified] is [5, 8] and we have default pending sst range [6, 8), so we can actually view DEFAULT has flushed_index 7 to be engaged in admin advance progress.

File: components/raftstore-v2/src/operation/ready/apply_trace.rs (hunk 1 above)
Comment (glorv) [reply components/raftstore-v2/src/operation/ready/apply_trace.rs:329]: Actually, in the current logic sst ingestion doesn't not block the `admin.flushed` index advance because we don't make the applied_index as modified if it's an ingestion. So if the admin.flushed can't be advanced, it mean there is at least one cf that has not flushed write. 
The only change in this pr is to trigger global flushed index if it meets a ingestion, in the old logic, it will wait at least 100 index diff, so after this change we won't expect many ingestion reapply.

File: components/raftstore-v2/src/operation/ready/apply_trace.rs (hunk 2 above)
Comment (SpadeA-Tang) [reply components/raftstore-v2/src/operation/ready/apply_trace.rs:925]: Elaborate this case for each CF.
For CF_LOCK, it's [5, 5]. So does not block admin_index advance.
For CF_DEFAULT, it's [5, 8], but we have range[6, 8) which just follows flushed_index 5, so we can use 7 here.
For CF_WRITE, it's [5, 6] (trace.on_modify(CF_WRITE, 6) should have been called), but we  have range [6, 7), so we can deem it as [6, 6]. So does not block admin_index advance.
Therefore, we can advance admin_index to 7.

File: components/raftstore-v2/src/operation/ready/apply_trace.rs (hunk 1 above)
Comment (SpadeA-Tang) [reply components/raftstore-v2/src/operation/ready/apply_trace.rs:329]: For example, if we only have sst ingestion, say 10000 ingestions. Then our persisted_apply will not be changed and if restart, we will replay all of them.

Comment (glorv) [reply components/raftstore-v2/src/operation/ready/apply_trace.rs]: This is not correct. The bad case is that there are 10000 ingestion and a write after that, in the old logic, the index won't advance before the write is flushed. But anyway I have changed it as you said.

File: components/raftstore-v2/src/operation/ready/apply_trace.rs (hunk 2 above)
Comment (glorv) [reply components/raftstore-v2/src/operation/ready/apply_trace.rs]: done

**Comment by SpadeA-Tang** [comment]
Maybe better to add an integration test for what we solved in this PR.

**Comment by glorv** [comment]
> Maybe better to add an integration test for what we solved in this PR.

@SpadeA-Tang  Done.

File: components/raftstore-v2/src/raft/apply.rs [hunk 3]
```diff
@@ -64,6 +64,7 @@ pub struct Apply<EK: KvEngine, R> {
     admin_cmd_result: Vec<AdminCmdResult>,
     flush_state: Arc<FlushState>,
     sst_apply_state: SstApplyState,
+    pub(crate) sst_applied_index: Vec<SstApplyIndex>,
```
Comment (overvenus) [inline components/raftstore-v2/src/raft/apply.rs:67]: Please use getter and setter to keep it consistent.

Comment (glorv) [reply components/raftstore-v2/src/raft/apply.rs]: done

**Comment by glorv** [comment]
@overvenus PTAL again

**Review by overvenus — APPROVED** [review]
