### PR TITLE
raftstore: add a timeout for sending snapshot

### LINKED ISSUE #16435: raftstore: Add a timeout mechanism on snapshot send
### What version of TiKV are you using?

7.6 or older

### Steps to reproduce

In an environment where network is very slow,  it's possible that a region's leader cannot transfer leader to other peer.
  "[2024/01/18 08:39:09.814 +00:00] [INFO] [peer.rs:3274] [\"reject to transfer leader\"] [last_index=118] [index=118] [reason=\"pending snapshot\"] [to=\"id: 1013401971 store_id: 3163 role: IncomingVoter\"] [peer_id=1013386609] [region_id=1012011487]",
  
  And this is because the send_snapshot may be stuck and it does not return success or failure, as the log below shows, it did not show either snapshot sent success or failure. 
```
    "[2024/01/18 08:21:11.882 +00:00] [INFO] [snap.rs:1050] [\"scan snapshot\"] [takes=1.354081432s] [size=6574425] [key_count=83914] [snapshot=/var/lib/tikv/snap/gen_1012011487_12_116_(default|lock|write).sst] [region_id=1012011487]",

[2024/01/18 08:21:10.528 +00:00] [INFO] [peer_storage.rs:520] [\"requesting snapshot\"] [request_peer=1013195901] [request_index=0] [peer_id=1013386609] [region_id=1012011487]
```
### What did you expect?
Send snapshot should have timeout mechanism. 
### What did happened?
Send snapshot may be stuck there forever and the leader cannot get rid of the "pending snapshot" status.

### PR DESCRIPTION
**Pull request by glorv**
### What is changed and how it works?

Issue Number: Close #16435

What's Changed:

```
Add a timeout for sending snapshot. If there is some problem in the network, this can allow the snapshot task fail early and trigger retry sending. 
```

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [ ] Need to cherry-pick to the release branch

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note

```release-note
None
```

### CODE REVIEW

File: src/server/snap.rs [hunk 1]
```diff
@@ -191,10 +208,30 @@ pub fn send_snap(
...
 
     let send_task = async move {
-        let mut sink = sink.sink_map_err(Error::from);
-        sink.send_all(&mut chunks).await?;
-        sink.close().await?;
-        let recv_result = receiver.map_err(Error::from).await;
+        let send_and_recv = async {
+            let mut sink = sink.sink_map_err(Error::from);
+
+            #[cfg(feature = "failpoints")]
```
Comment (mittalrishabh) [inline src/server/snap.rs:214]: sink.sink_map_err() and receiver.map_err(Error::from) should return error if there is a network error. Right ?

I am trying to understand that how the timeout is helping here other than it fails early and can retry.

Comment (glorv) [reply src/server/snap.rs:214]: Yes, if the send fails due to network error, send snapshot will fail immediately, Timeout has no effect in this case. This timeout is to handle cases that the task does not fail but also not progress, thus if it can finished in specifical duration, that means there must be something wrong with the netwrok, we may just abort this task and try again latter.

Comment (mittalrishabh) [reply src/server/snap.rs:214]: I am not sure if it is right RCA. Node was stuck in Snaphost pending state for days in our cluster. Are we saying that sink or receiver is hung internally forever.

**Review by Connor1996 — APPROVED** [review]
LGTM

**Comment by glorv** [comment]
> My concern is what if the leader sends another snapshot quickly and then stuck again.

In this case, the result would just like the logic without this retry. If normal raft log can be sent successfully, it's likely the network isn't that bad and the snapshot can be sent after retry.

File: src/server/snap.rs (hunk 1 above)
Comment (glorv) [reply src/server/snap.rs:214]: Sorry, I'm also not sure why the snapshot was stuck for such a long time. If you meet this problem again, we can catch a stack trace and it should help us locate the root cause of this stuck.

File: src/server/snap.rs [hunk 2]
```diff
@@ -560,3 +597,41 @@ impl<R: RaftExtension + 'static> Runnable for Runner<R> {
...
 }
+
+#[pin_project]
+struct TimeoutFuture<F, T> {
+    #[pin]
+    f: F,
+    #[pin]
+    timer: Compat01As03<Delay>,
+    on_timeout: T,
+}
```
Comment (overvenus) [inline src/server/snap.rs:608]: Prefer [`select`](https://docs.rs/futures/latest/futures/future/fn.select.html), less code.

File: src/server/snap.rs [hunk 3]
```diff
@@ -50,6 +55,18 @@ pub type Callback = Box<dyn FnOnce(Result<()>) + Send>;
 
 pub const DEFAULT_POOL_SIZE: usize = 4;
 
+// the max duration before a snapshot send task is canceled.
+const SNAP_SEND_TIMEOUT_DURATION: Duration = Duration::from_secs(600);
```
Comment (overvenus) [inline src/server/snap.rs:59]: What if leader sends a huge snapshot that may takes more than 600s?

File: src/server/snap.rs [hunk 4]
```diff
@@ -191,10 +208,30 @@ pub fn send_snap(
...
+                        .compat()
+                        .await;
+                }
+            }
+            sink.send_all(&mut chunks).await?;
+            sink.close().await?;
+            Ok(receiver.map_err(Error::from).await)
+        };
+        let sink_timeout = TimeoutFuture::new(send_and_recv, get_snap_timeout(), || {
+            Err(Error::Other(box_err!("send snapshot timeout")))
```
Comment (overvenus) [inline src/server/snap.rs:232]: Could you add a metric or log here?

Comment (glorv) [reply src/server/snap.rs:232]: There is error log in the caller of this function.

File: src/server/snap.rs (hunk 3 above)
Comment (glorv) [reply src/server/snap.rs:58]: Ok. I changed get_snap_timeout to also consider snap size. The new timeout will be max(SNAP_SEND_TIMEOUT_DURATION, snap_size / 1MiB * time.Seconds).

**Review by mittalrishabh — APPROVED** [review]

**Comment by mittalrishabh** [comment]
when are you planning to merge this change to 6.5

**Comment by glorv** [comment]
@overvenus PTAL

**Review by overvenus — APPROVED** [review]

File: src/server/snap.rs (hunk 3 above)
Comment (glorv) [reply src/server/snap.rs:58]: done.

**Comment by glorv** [comment]
> when are you planning to merge this change to 6.5

@mittalrishabh  sorry for the late reply. We have cherry-picked this PR to the release-6.5 branch in #16530, so it will be included in the incoming bugfix version.
