### PR TITLE
raftstore: address the corner case on WakeUp hibernate regions.

### LINKED ISSUE #16368: qps recover after 13mins when inject one of tikv io hang
### What version of TiKV are you using?
v6.5.7
git hash：5f1ac992c5f4515ec493634795f1af7a726c1ec9

### What operating system and CPU are you using?
8c/32g

deploy with 6 tikv + 3 pd + 2 tidb

### Steps to reproduce
1、run tpcc 
image

2、inject one of tikv io hang last for 20mins
image

### What did you expect?
qps can recover within 5mins after inject one of tikv io hang

### What did happened?
qps recover after 13mins when inject one of tikv io hang

img_v3_026u_3d4bb9f4-51dc-497a-8ba6-527ad26aaa2g

clinic：https://clinic.pingcap.com.cn/portal/#/orgs/31/clusters/7317786419213168837?from=1703858383&to=1703862621

### PR DESCRIPTION
**Pull request by LykxSassinator**
### What is changed and how it works?

Issue Number: Close #16368

What's Changed:

```commit-message
This pull request addresses a corner case where `WakeUp` messages were being
ignored during I/O hang scenarios.
```

Previously, in the nightly branch, there was a possibility of Peers entering the `PreChaos` state by `on_check_peer_stale_state_tick` scheduler before handling `WakeUp` messages. In such cases,
these Peers would ignore `WakeUp` messages triggered by the "awaken hibernate regions" mechanism. 
Consequently, the recovery duration would last longer than expected.

In this pull request, when the `raftstore` forcibly receives `WakeUp` messages -- indicating the presence of I/O hang problems in the cluster -- the relevant `raftstore` will promptly notify the affected Peers to directly enter the `Chaos` state. 

This facilitates the re-election of new leaders in a shorter duration as expected.

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [ ] Need to cherry-pick to the release branch

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

| - | Nightly version (Exists Bugs) | **This PR (BugFix)** |
| ---- | ---- | ---- |
| Leaders Distribution | image | image |
| Peers state | image | image |

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note

```release-note
None.
```

### CODE REVIEW

File: tests/integrations/raftstore/test_hibernate.rs [hunk 1]
```diff
@@ -499,3 +501,48 @@ fn test_leader_demoted_when_hibernated() {
...
+    message.region_id = 1;
+    message.set_from_peer(new_peer(3, 3));
+    message.set_to_peer(new_peer(3, 3));
+    message.mut_region_epoch().version = 1;
+    message.mut_region_epoch().conf_ver = 3;
+    let mut msg = ExtraMessage::default();
+    msg.set_type(ExtraMessageType::MsgRegionWakeUp);
+    msg.forcely_awaken = true;
+    message.set_extra_msg(msg);
+    router.send_raft_message(message).unwrap();
```
Comment (overvenus) [inline tests/integrations/raftstore/test_hibernate.rs:547]: Maybe need to verify its hibernate state?

Comment (LykxSassinator) [reply tests/integrations/raftstore/test_hibernate.rs]: Fixed

**Review by SpadeA-Tang — APPROVED** [review]

**Review by overvenus — APPROVED** [review]
