### PR TITLE
raftstore: check last heartbeat time before doing conf change remove node

### LINKED ISSUE #15799: Change placement rule from 5 replicas to 3 replicas with some tikv down, tpcc report error: [tikv:9005]Region is unavailable
### What version of TiKV are you using?

v6.5.5

### Steps to reproduce

image

### What did you expect?
No error was reported by workload.

### What did happened?
After running step 3 , the workload hit the following error. 
```
[2023/10/19 11:56:52.130 +08:00] [INFO] [region_request.go:1285] ["send request on region error failed, err: region unavailable"] [req-ts=445038019152969738] [req-type=CheckSecondaryLocks] [region="{ region id: 411, ver: 72, confVer: 70 }"] [region-is-valid=true] [retry-times=1] [replica-read-type=leader] [replica-selector-state=tryFollower] [stale-read=false] [replica-status="peer: 412, store: 1, isEpochStale: false, attempts: 0, replica-epoch: 1, store-epoch: 1, store-state: resolved, store-liveness-state: unreachable; peer: 567, store: 546, isEpochStale: false, attempts: 1, replica-epoch: 0, store-epoch: 0, store-state: resolved, store-liveness-state: reachable; peer: 644, store: 545, isEpochStale: false, attempts: 0, replica-epoch: 1, store-epoch: 1, store-state: resolved, store-liveness-state: unreachable; peer: 1313, store: 7, isEpochStale: false, attempts: 1, replica-epoch: 0, store-epoch: 0, store-state: resolved, store-liveness-state: reachable"] [total-backoff-ms=40020] [total-backoff-times=94] [total-region-errors=not_leader:2]
[2023/10/19 11:56:52.130 +08:00] [INFO] [conn.go:1181] ["command dispatched failed"] [conn=8710434469334483365] [connInfo="id:8710434469334483365, addr:10.200.61.95:38466 status:11, collation:utf8mb4_general_ci, user:root"] [command=Execute] [status="inTxn:1, autocommit:1"] [sql="SELECT c_discount, c_last, c_credit, w_tax FROM customer, warehouse WHERE w_id = ? AND c_w_id = w_id AND c_d_id = ? AND c_id = ? [arguments: (7, 2, 2511)]"] [txn_mode=PESSIMISTIC] [timestamp=445038663293206530] [err="[tikv:9005]Region is unavailable\nSELECT c_discount, c_last, c_credit, w_tax FROM customer, warehouse WHERE w_id = ? AND c_w_id = w_id AND c_d_id = ? AND c_id = ? [arguments: (7, 2, 2511)]\ngithub.com/pingcap/tidb/server.(*clientConn).executePreparedStmtAndWriteResult\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/server/conn_stmt.go:426\ngithub.com/pingcap/tidb/server.(*clientConn).executePlanCacheStmt\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/server/conn_stmt.go:234\ngithub.com/pingcap/tidb/server.(*clientConn).handleStmtExecute\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/server/conn_stmt.go:226\ngithub.com/pingcap/tidb/server.(*clientConn).dispatch\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/server/conn.go:1430\ngithub.com/pingcap/tidb/server.(*clientConn).Run\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/server/conn.go:1152\ngithub.com/pingcap/tidb/server.(*Server).onConn\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/server/server.go:648\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1594"]
```

### PR DESCRIPTION
**Pull request by tonyxuqqi**
### What is changed and how it works?

Issue Number: Close #15799

What's Changed:

```commit-message
Check the last heartbeat time before doing remove node operation. It defines 8*heartbeat interval as the threshold of slow peer. And if the remove node operation will lead to at least half of the peers are slow, then the remove node operation will fail. 
```

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [x] Need to cherry-pick to the release branch

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [x] Manual test (add detailed scripts or steps below)

### Release note

```release-note
Check the last heartbeat time before doing remove node operation. It defines 8*heartbeat interval as the threshold of slow peer. And the remove node operation will lead to at least half of the peers are slow, then the remove node operation will fail. 
```

### CODE REVIEW

File: components/raftstore/src/store/util.rs [hunk 1]
```diff
@@ -1123,6 +1125,41 @@ pub fn check_conf_change(
     }
 }
 
+pub fn check_remove_node(
```
Comment (overvenus) [inline components/raftstore/src/store/util.rs:1128]:
```suggestion
fn check_remove_node(
```

File: components/raftstore/src/store/util.rs [hunk 2]
```diff
@@ -1123,6 +1125,41 @@ pub fn check_conf_change(
...
+    let mut slow_peer_count: u32 = 0;
+    for last_heartbeat in peer_heartbeat.values() {
+        if last_heartbeat.elapsed() > MAX_MISSED_HEARTBEATS * cfg.raft_heartbeat_interval() {
+            slow_peer_count += 1;
+        }
+    }
+
+    for cp in change_peers {
+        let (change_type, peer) = (cp.get_change_type(), cp.get_peer());
+        if change_type == ConfChangeType::RemoveNode {
```
Comment (overvenus) [inline components/raftstore/src/store/util.rs:1144]: Should we consider `AddLearnerNode` too?

File: tests/integrations/raftstore/test_conf_change.rs [hunk 3]
```diff
@@ -863,3 +863,34 @@ fn test_conf_change_fast() {
     must_get_equal(&cluster.get_engine(2), b"k1", b"v1");
     assert!(timer.saturating_elapsed() < Duration::from_secs(5));
 }
+
+#[test_case(test_raftstore::new_node_cluster)]
+#[test_case(test_raftstore::new_server_cluster)]
+fn test_remove_node_on_partition() {
+    let count = 6;
+    let mut cluster = new_cluster(0, count);
```
Comment (overvenus) [inline tests/integrations/raftstore/test_conf_change.rs:871]:
```suggestion
    let mut cluster = new_cluster(0, 3);
```

File: tests/integrations/raftstore/test_conf_change.rs [hunk 4]
```diff
@@ -863,3 +863,34 @@ fn test_conf_change_fast() {
     must_get_equal(&cluster.get_engine(2), b"k1", b"v1");
     assert!(timer.saturating_elapsed() < Duration::from_secs(5));
 }
+
+#[test_case(test_raftstore::new_node_cluster)]
+#[test_case(test_raftstore::new_server_cluster)]
```
Comment (overvenus) [inline tests/integrations/raftstore/test_conf_change.rs:868]:
```suggestion
#[test_case(test_raftstore_v2::new_node_cluster)]
```

File: tests/integrations/raftstore/test_conf_change.rs [hunk 5]
```diff
@@ -863,3 +863,34 @@ fn test_conf_change_fast() {
...
+    must_get_equal(&cluster.get_engine(2), b"k0", b"v0");
+    pd_client.must_add_peer(r1, new_peer(3, 3));
+    must_get_equal(&cluster.get_engine(3), b"k0", b"v0");
+
+    // peer 3 isolation
+    cluster.add_send_filter(IsolationFilterFactory::new(3));
+    // sleep for 10 heartbeat interval
+    thread::sleep(cluster.cfg.raft_store.raft_heartbeat_interval() * 10);
+    pd_client.remove_peer(r1, new_peer(2, 2));
+    thread::sleep(Duration::from_millis(500));
```
Comment (overvenus) [inline tests/integrations/raftstore/test_conf_change.rs:890]:
```suggestion
    pd_client.remove_peer(r1, new_peer(2, 2));
    thread::sleep(Duration::from_millis(500));
    cluster.must_put(b"k1", b"v1");
```

Make sure region is available after every conf change.

File: tests/integrations/raftstore/test_conf_change.rs [hunk 6]
```diff
@@ -863,3 +863,34 @@ fn test_conf_change_fast() {
...
+    // remove peer 2 should not work
+    pd_client.must_have_peer(r1, new_peer(2, 2));
+
+    // remove peer 3 should work
+    pd_client.must_remove_peer(r1, new_peer(3, 3));
```
Comment (overvenus) [inline tests/integrations/raftstore/test_conf_change.rs:895]:
```suggestion
    pd_client.must_remove_peer(r1, new_peer(3, 3));
    cluster.must_put(b"k2", b"v2");
```

File: components/raftstore/src/store/util.rs [hunk 7]
```diff
@@ -1123,6 +1125,41 @@ pub fn check_conf_change(
...
+            if let Some(last_heartbeat) = peer_heartbeat.get(&peer.get_id()) {
+                // peer itself is *not* slow peer, but current slow peer is >= total peers/2
+                if last_heartbeat.elapsed() <= MAX_MISSED_HEARTBEATS * cfg.raft_heartbeat_interval()
+                    && slow_peer_count >= peer_heartbeat.len() as u32 / 2
```
Comment (Connor1996) [inline components/raftstore/src/store/util.rs:1148]: maybe use `peer.raft_group.raft.prs().has_quorum(peers_except_slow)`

File: components/raftstore/src/store/util.rs (hunk 2 above)
Comment (tonyxuqqi) [reply components/raftstore/src/store/util.rs:1147]: There's no harm to AddLearnerNode.

File: components/raftstore/src/store/util.rs (hunk 7 above)
Comment (tonyxuqqi) [reply components/raftstore/src/store/util.rs:1151]: @Connor1996 Good point. I thought it initially too, but end up this simple check instead because of unit test issue.  Do you know how to construct a proper ProgressTracker in unit test (like the test_check_conf_change_upon_slow_peers I added). 
I found it's very hard to create a valid ProgressTracker instance for unit testing. And it's even harder to create a proper peer or raft_group object.

Comment (tonyxuqqi) [reply components/raftstore/src/store/util.rs:1151]: OK, used a quite tedious way to create a usable ProgressTracker object.

File: tests/integrations/raftstore/test_conf_change.rs (hunk 4 above)
Comment (overvenus) [reply tests/integrations/raftstore/test_conf_change.rs:868]: No need to test server cluster, the test case is not related to the transport layer.

File: components/raftstore/src/store/util.rs (hunk 2 above)
Comment (overvenus) [reply components/raftstore/src/store/util.rs:1157]: I think we should also forbid adding node in such case. Otherwise, it may block write until the new peer applies snapshot.

```rust
#[test]
fn test_add_node_on_partition() {
    let count = 4;
    let mut cluster = new_node_cluster(0, count);
    let pd_client = Arc::clone(&cluster.pd_client);
    // Disable default max peer number check.
    pd_client.disable_default_operator();
    cluster.cfg.raft_store.raft_heartbeat_ticks = 1;
    cluster.cfg.raft_store.raft_base_tick_interval = ReadableDuration::millis(10);
    let r1 = cluster.run_conf_change();

    cluster.must_put(b"k0", b"v0");
    pd_client.must_add_peer(r1, new_peer(2, 2));
    must_get_equal(&cluster.get_engine(2), b"k0", b"v0");
    pd_client.must_add_peer(r1, new_peer(3, 3));
    must_get_equal(&cluster.get_engine(3), b"k0", b"v0");

    // peer 3 isolation
    cluster.add_send_filter(IsolationFilterFactory::new(3));

    // Block peer (4, 4) at receiving snapshot.
    cluster.add_send_filter(CloneFilterFactory(
        RegionPacketFilter::new(r1, 4).msg_type(MessageType::MsgSnapshot),
    ));
    pd_client.must_add_peer(r1, new_peer(4, 4));
    cluster.must_put(b"k1", b"v1"); # This case panics here, timeout.
}
```

File: components/raftstore/src/store/util.rs (hunk 7 above)
Comment (tonyxuqqi) [reply components/raftstore/src/store/util.rs]: @Connor1996 It turns out that there's a problem with has_quorum() here. Because the remove_node cmd is supposed to change the raft group members, but has_quorum() assumes the members are not going to be changed when calculating quorum.  
So for example, if we have two peers' raft group and want to remove a peer, with this change it will not succeed. Because the remaining one peer will not achieve quorum under current progress object.

File: components/raftstore/src/store/util.rs (hunk 2 above)
Comment (tonyxuqqi) [reply components/raftstore/src/store/util.rs:1157]: @overvenus 
The failure here is because the new peer (peer4) is slow.  I think this is a valid concern. But this PR is to look at the existing peers' slowness by their last heartbeat time and prevent the remove node(s) if it's going to disrupt the quorum. 
For the new peer, we don't know if it's slow or not until the peer is added.  Maybe we should check the health of the new node before adding a peer, but it's another problem.

Comment (tonyxuqqi) [reply components/raftstore/src/store/util.rs:1151]: @overvenus I got your point. Do you mean AddLearnerNode on existing peer (which means it's a demote). We need to check it as well indeed. Updated the code.

File: components/raftstore/src/store/util.rs [hunk 8]
```diff
@@ -1123,6 +1125,65 @@ pub fn check_conf_change(
...
+        } else {
+            slow_peer_count += 1;
+        }
+    }
+
+    let mut normal_peers_to_remove = vec![];
+    for cp in change_peers {
+        let (change_type, peer) = (cp.get_change_type(), cp.get_peer());
+        if change_type == ConfChangeType::RemoveNode
+            || change_type == ConfChangeType::AddLearnerNode
```
Comment (overvenus) [inline components/raftstore/src/store/util.rs:1152]: Could you further check if the demote peer is actually in the region peer list? So it does not accidentally block adding peers.

**Review by overvenus — COMMENTED** [review]
Rest LGTM

File: components/raftstore/src/store/util.rs (hunk 8 above)
Comment (tonyxuqqi) [reply components/raftstore/src/store/util.rs:1152]: @overvenus Yes, it's checked in the code below. We thought it's a demote only when peer_beartbeat finds the peer_id

**Review by Connor1996 — APPROVED** [review]
LGTM

**Review by overvenus — APPROVED** [review]
