### PR TITLE
tidb_query: fix UB causing by `from_raw_parts`

### LINKED ISSUE #7613: Undefined behavior in tidb_query_datatype's RowSlice
## Bug Report

`RowSlice` does an unsafe pointer cast that is often unaligned. This is undefined behavior, which could potentially lead to miscompilation.

Here is the source: https://github.com/tikv/tikv/blob/7565efc9af7be6ef0f1adb6b51152c2c455a0f9c/components/tidb_query_datatype/src/codec/row/v2/row_slice.rs#L149

The fix isn't simple, so I'm just filing a bug cc @breeswish.

Potential fixes are to accumulate the casted items into a new buffer instead of slicing the original buffer, but that costs an allocation. Another fix would be to change the serialization such that the cast always ends up aligned, while adding an assertion here that the alignment is correct.

Tested against commit adf3a9408c4ec20cb8b19676d79c9087c3e72b40

Found with miri (cc @oli-obk 👍 ).

### PR DESCRIPTION
**Pull request by zhongzc**
Signed-off-by: zhongzc <zhongzc_arch@outlook.com>

### What problem does this PR solve?

Issue Number: close #7613 

Problem Summary:

From stdlib doc:
> Behavior is undefined if any of the following conditions are violated:
> * data must be valid for reads for len * mem::size_of::<T>() many bytes, and it must be properly __aligned__.
> * ...

We didn't provide this promise.

### What is changed and how it works?

What's Changed:

Introduce a new type `LEBytes`. Implement `binary_search` for this type by explicitly calling `std::ptr::read_unaligned`.

### Check List 

Tests 

- Unit test

### CODE REVIEW

**Comment by zhongzc** [comment]
@breeswish PTAL

File: components/tidb_query_datatype/src/codec/row/v2/row_slice.rs [hunk 1]
```diff
@@ -69,11 +71,11 @@ impl RowSlice<'_> {
                 if let Ok(idx) = non_null_ids.binary_search(&(id as u32)) {
                     let offset = offsets.get(idx).ok_or(Error::ColumnOffset(idx))?;
                     let start = if idx > 0 {
-                        offsets[idx - 1] as usize
+                        offsets.get_unchecked(idx - 1) as usize
```
Comment (breeswish) [inline components/tidb_query_datatype/src/codec/row/v2/row_slice.rs:74]: There might not be sufficient elements in the offsets (if the data is corrupted). We'd better handle it.

Previously this case result in panic. Now it result in memory issue, which is worse. Better to change it to return error.

File: components/tidb_query_datatype/src/codec/row/v2/row_slice.rs [hunk 2]
```diff
@@ -138,44 +140,98 @@ impl RowSlice<'_> {
...
+    }
+
+    #[inline]
+    fn binary_search(&self, value: &T) -> std::result::Result<usize, usize> {
+        let mut size = self.slice.len() / std::mem::size_of::<T>();
+        if size == 0 {
+            return Err(0);
+        }
+        let mut base = 0usize;
+        while size > 1 {
```
Comment (breeswish) [inline components/tidb_query_datatype/src/codec/row/v2/row_slice.rs:196]: Make sure to support a case that when data is corrupted (i.e. the data in `value` is not in order at all) we will never fall into infinite loop. Search to got nothing is allowed in this case.

File: components/tidb_query_datatype/src/codec/row/v2/row_slice.rs [hunk 3]
```diff
@@ -138,44 +140,106 @@ impl RowSlice<'_> {
...
+    #[inline]
+    fn binary_search(&self, value: &T) -> std::result::Result<usize, usize> {
+        let mut size = self.slice.len() / std::mem::size_of::<T>();
+        if size == 0 {
+            return Err(0);
+        }
+        let mut base = 0usize;
+
+        // Note that the count of ids is not greater than (2 >> 16). The number
+        // of binary search steps will not over 16 unless the data is corruted.
```
Comment (breeswish) [inline components/tidb_query_datatype/src/codec/row/v2/row_slice.rs:198]: supply some fuzz test? also there is a typo in word "corruted"

Comment (zhongzc) [reply components/tidb_query_datatype/src/codec/row/v2/row_slice.rs:198]: Haven't. I'll try it tomorrow. (I also reversed the shift left XD)

Comment (zhongzc) [reply components/tidb_query_datatype/src/codec/row/v2/row_slice.rs]: Fuzz test works well. PTAL

File: components/tidb_query_datatype/src/codec/row/v2/row_slice.rs (hunk 1 above)
Comment (brson) [reply components/tidb_query_datatype/src/codec/row/v2/row_slice.rs:74]: I see this conversation marked as resolved, but what was the resolution? Why is this unchecked indexing ok?

File: components/tidb_query_datatype/src/codec/row/v2/row_slice.rs [hunk 4]
```diff
@@ -138,44 +140,106 @@ impl RowSlice<'_> {
...
+    fn get(&self, index: usize) -> Option<T> {
+        if std::mem::size_of::<T>() * index >= self.slice.len() {
+            None
+        } else {
+            Some(self.get_unchecked(index))
+        }
+    }
+
+    #[inline]
+    fn get_unchecked(&self, index: usize) -> T {
```
Comment (brson) [inline components/tidb_query_datatype/src/codec/row/v2/row_slice.rs:181]: This function should be marked as unsafe since it allows the caller to do unsafe memory access.

File: components/tidb_query_datatype/src/codec/row/v2/row_slice.rs (hunk 1 above)
Comment (brson) [reply components/tidb_query_datatype/src/codec/row/v2/row_slice.rs:74]: Doing an unsafe array access here isn't obviously important to performance. @zhongzc are you sure this needs to be unchecked?

Comment (zhongzc) [reply components/tidb_query_datatype/src/codec/row/v2/row_slice.rs:74]: @brson  Previous `offsets.get(idx)` indicates `offsets.get_unchecked(idx - 1)` is okay.
