### PR TITLE
raft-store-v2: fix report down peers

### LINKED ISSUE #15316: raft-store-v2: tikv does not report down peers after 1 tikv is down
### What version of TiKV are you using?

nightly

### Steps to reproduce

Strat a 3 tikv nightly cluster and insert some data.
Stop 1 tikv instance for more than 10 minutes.

### What did you expect?
These will be some down peers in pd `region health` panel.

### What did happened?
PD detected 1 down store but none down peers.

### PR DESCRIPTION
**Pull request by glorv**
### What is changed and how it works?

Issue Number: Close #15316

What's Changed:

```
Fix wrong expression in calculating region down duration
```

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

Side effects

### Release note 

```release-note
None
```

### CODE REVIEW

File: components/raftstore-v2/src/raft/peer.rs [hunk 1]
```diff
@@ -603,7 +603,7 @@ impl<EK: KvEngine, ER: RaftEngine> Peer<EK, ER> {
                 continue;
             }
             if let Some(instant) = self.peer_heartbeats.get(&p.get_id()) {
-                let elapsed = instant.saturating_duration_since(now);
+                let elapsed = now.saturating_duration_since(*instant);
```
Comment (tonyxuqqi) [inline components/raftstore-v2/src/raft/peer.rs:606]: Good catch!
A minor comment: we can use instant.saturating_elapsed() to achieve the same purpose.  No need to have `now` variable explicitly.

**Review by tonyxuqqi — APPROVED** [review]

File: components/raftstore-v2/src/raft/peer.rs (hunk 1 above)
Comment (glorv) [reply components/raftstore-v2/src/raft/peer.rs:606]: Yes, the current impl defines now in the out loop, maybe to avoid calculate now() for multiple times but I think it's not the bottleneck so just use saturating_elapsed should be ok here.

File: tests/integrations/raftstore/test_region_heartbeat.rs [hunk 2]
```diff
@@ -7,94 +7,88 @@ use std::{
...
-    cluster.must_transfer_leader(1, leader);
-    wait_down_peers(cluster, 0, None);
-    wait_down_peers(cluster, 1, Some(1));
-    assert!(
-        cluster.get_down_peers()[&1].get_down_seconds() < timer.saturating_elapsed().as_secs() + 1
-    );
 }
 
-#[test]
+#[test_case(test_raftstore::new_node_cluster)]
```
Comment (nolouch) [inline tests/integrations/raftstore/test_region_heartbeat.rs:76]: no need for v2? v2 doesn't supports hibernate?

Comment (overvenus) [reply tests/integrations/raftstore/test_region_heartbeat.rs:76]: Yes, v2 no longer supports hibernate.

File: tests/integrations/raftstore/test_region_heartbeat.rs [hunk 3]
```diff
@@ -7,94 +7,88 @@ use std::{
...
     // more frequently.
     cluster.cfg.raft_store.peer_stale_state_check_interval = ReadableDuration::millis(500);
-    test_down_peers(&mut cluster);
+    test_down_peers!(&mut cluster);
 }
 
-#[test]
+#[test_case(test_raftstore::new_node_cluster)]
+#[test_case(test_raftstore_v2::new_node_cluster)]
 fn test_server_down_peers_without_hibernate_regions() {
```
Comment (overvenus) [inline tests/integrations/raftstore/test_region_heartbeat.rs:88]: raftstore v2 no longer support hibernate region.

**Review by nolouch — APPROVED** [review]

**Review by Connor1996 — APPROVED** [review]
