### PR TITLE
txn: collect mvcc for err `TxnLockNotFound` when commit secondary failed

### LINKED ISSUE #18425: collect mvcc info for error `TxnLockNoutFound` while committing secondary,
## Development Task

See: https://github.com/tikv/client-go/issues/1631 

The txn lock should always be present when committing secondaries. If not, it means something is wrong and it's probably a bug of transaction. At this time, it's better to collect mvcc info for further debugging.

### PR DESCRIPTION
**Pull request by lcwangchao**
### What is changed and how it works?

Issue Number: Close #18425 

What's Changed:

```commit-message
txn: collect mvcc for err `TxnLockNotFound` when commit secondary failed
```

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [ ] Need to cherry-pick to the release branch

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note

```release-note
None
```

### CODE REVIEW

File: src/storage/txn/actions/commit.rs [hunk 1]
```diff
@@ -62,19 +64,36 @@ pub fn commit<S: Snapshot>(
         _ => {
```
Comment (cfzjywxk) [inline src/storage/txn/actions/commit.rs:64]: It is also unexpected to see a pessimistic type lock with the same `start_ts` committing secondary locks, the `mvcc` information is needed to be printed here too.

File: src/storage/txn/actions/commit.rs [hunk 2]
```diff
@@ -403,4 +441,83 @@ pub mod tests {
...
+                    assert_matches!(mvcc_info.clone(), None, "key: {}", key_str);
+                    true
+                }
+            );
+        }
+
+        // Should collect mvcc for debugging when secondary commit returns an error
+        // TxnLockNotFound.
+        // - k2, lock rollback.
+        // - k3, no lock.
```
Comment (cfzjywxk) [inline src/storage/txn/actions/commit.rs:488]: // - k4, lock exists but it is pessimistic lock type, which is also an unexpected situation.

File: src/storage/errors.rs [hunk 3]
```diff
@@ -407,10 +407,42 @@ pub fn extract_key_error(err: &Error) -> kvrpcpb::KeyError {
...
+
+            warn!("txn conflicts"; "err" => ?err_without_mvcc);
+            key_error.set_retryable(format!("{:?}", err_without_mvcc));
+            let mut txn_lock_not_found = kvrpcpb::TxnLockNotFound::default();
+            txn_lock_not_found.set_key(key.clone());
+            key_error.set_txn_lock_not_found(txn_lock_not_found);
+            // if mvcc_info is present, fill the debug_info for client's further debugging.
+            if let Some(mvcc_info) = mvcc_info {
+                // remove the values in default CF to reduce the size of the response.
+                let mut mvcc_info = mvcc_info.clone();
```
Comment (cfzjywxk) [inline src/storage/errors.rs:435]: Could this `clone` be saved and just consume the original `mvcc_info`?

Comment (lcwangchao) [reply src/storage/errors.rs:435]: One way is:

```
if let Some(mvcc_info) = mvcc_info.take() {
    ...
```

However, this will remove the MVCC info from the original error. If the outside code want to use the input error again , this info will be lost.

File: src/storage/txn/actions/commit.rs (hunk 2 above)
Comment (lcwangchao) [reply src/storage/txn/actions/commit.rs:488]: OK, I'll add this case

File: src/storage/txn/actions/commit.rs (hunk 1 above)
Comment (lcwangchao) [reply src/storage/txn/actions/commit.rs:64]: OK

File: src/storage/txn/actions/mvcc.rs [hunk 4]
```diff
@@ -0,0 +1,215 @@
...
+
+use crate::storage::mvcc::{Lock as MvccLock, MvccReader};
+
+type LockWritesVals = (
+    Option<MvccLock>,
+    Vec<(TimeStamp, Write)>,
+    Vec<(TimeStamp, Value)>,
+);
+
+pub fn find_mvcc_infos_by_key<S: Snapshot>(
```
Comment (ekexium) [inline src/storage/txn/actions/mvcc.rs:14]: What is the semantic definition or interface contract of this function? For WRITE CF, it seems to use a timestamp as an upper bound, while for DEFAULT CF, it scans all versions. Is this understanding correct?

Comment (ekexium) [reply src/storage/txn/actions/mvcc.rs:14]: How about retrieving data from both CFs for all versions, but setting a maximum result size to prevent performance issues in extreme cases??

Comment (lcwangchao) [reply src/storage/txn/actions/mvcc.rs:14]: `find_mvcc_infos_by_key` is an existing function moved from https://github.com/tikv/tikv/pull/18426/files#diff-1d92ed342cae0478fe17f515900c6aa5d3db4ad58a4eb06f743d6c9dc220094bL570. Maybe we should keep it as before in this PR to keep the existing API behavior unchanged and schedule another PR if we want to do this kind of enhancement

File: src/storage/txn/actions/commit.rs (hunk 1 above)
Comment (lcwangchao) [reply src/storage/txn/actions/commit.rs:64]: Seems it is an expected case which may happen sometimes?

https://github.com/tikv/tikv/blob/1f44fd9a8e59d06c39834cfa0bd4d47e2c3c2959/src/storage/txn/actions/commit.rs#L44-L57

Comment (lcwangchao) [reply src/storage/txn/actions/commit.rs:67]: Just print mvcc without returning an error in this case

**Review by cfzjywxk — APPROVED** [review]
LGTM

**Review by you06 — COMMENTED** [review]
BTW, shall we also set gc_fence and overlapped rollback here?

https://github.com/tikv/tikv/blob/0387c2fd0d9115ad4151876812f4be7f17018dc8/src/storage/types.rs#L55

```rust
write_info.set_has_overlapped_rollback(write.has_overlapped_rollback);
if let Some(gc_fence) = write.gc_fence {
    write_info.set_has_gc_fence(true);
    write_info.set_gc_fence(gc_fence.into_inner());
}
```

File: src/storage/txn/actions/mvcc.rs [hunk 5]
```diff
@@ -0,0 +1,194 @@
...
+    reader: &mut MvccReader<S>,
+    key: &Key,
+    // TODO: add some argument such as `limit` to limit the max size of mvcc info
+) -> crate::storage::txn::Result<LockWritesVals> {
+    let mut writes = vec![];
+    let mut values = vec![];
+    let lock = reader.load_lock(key)?;
+    let mut ts = TimeStamp::max();
+    loop {
+        let opt = reader.seek_write(key, ts)?;
```
[the remark this answers is not in the document]
Comment (lcwangchao) [reply src/storage/txn/actions/mvcc.rs:24]: Seems `MvccByStartTs` needs to seek the position, it is expected:

https://github.com/tikv/tikv/blob/0387c2fd0d9115ad4151876812f4be7f17018dc8/src/storage/txn/commands/mvcc_by_start_ts.rs#L39-L45

I've updated `collect_mvcc_info_for_debug` to receive snapshot as argument instead of reader.

**Review by you06 — APPROVED** [review]
