### PR TITLE
avoid stale result for read index command

### LINKED ISSUE #9351: Stale read when using read_index request
## Bug Report

Similar to #9208, ReadIndex request can be given a stale index after just transferring leader. The API doesn't seem to be used anymore, so the best way to solve it is removing the API completely.

@NingLin-P @gengliqi PTAL

/cc @solotzg, just make sure tiflash will not use the API in the future.

### PR DESCRIPTION
**Pull request by hicqu**
Signed-off-by: qupeng <qupeng@pingcap.com>

### What problem does this PR solve?

Close #9351 .

### What is changed and how it works?

Avoid stale result for read index command.

### Check List 

Tests 
- Integration test

Side effects

### Release note 
* No release note.

### CODE REVIEW

File: components/raftstore/src/store/peer.rs [hunk 1]
```diff
@@ -1946,10 +1946,15 @@ where
                 continue;
             }
             if !replica_read {
-                if read_index.is_none() {
+                match (read_index, read.read_index) {
+                    // `read_index` could be less than `read.read_index` because the former is
+                    // filled with `committed index` when proposed, and the latter is filled after
+                    // a read-index procedure finished.
+                    (Some(i_test), Some(i_got)) if i_test < i_got => read_index = read.read_index,
```
Comment (BusyJay) [inline components/raftstore/src/store/peer.rs:1953]: Confusing names. How about `lower_bound` and `batch_index`?

**Review by NingLin-P — APPROVED** [review]
LGTM

File: components/raftstore/src/store/peer.rs [hunk 2]
```diff
@@ -1953,7 +1953,14 @@ where
                 continue;
             }
             if !replica_read {
-                if read_index.is_none() {
+                if read_index.is_some() && read.read_index.is_some() {
```
Comment (gengliqi) [inline components/raftstore/src/store/peer.rs:1956]: It seems the `read.read_index` can not be `None` when calling `response_read` in any case.

Comment (gengliqi) [reply components/raftstore/src/store/peer.rs:1956]: I prefer to change here. https://github.com/tikv/tikv/blob/bf92a4a9b56f410f3c0eefe8056c22923a08ceee/components/raftstore/src/store/peer.rs#L2599 
If `self.get_store().term(commit_index).unwrap() == self.term()` is not true, we should not set it.
If so, here logic is the same as before. The only place that needs to be updated is the comment "Actually, the read_index is none if and only if..."

Comment (gengliqi) [reply components/raftstore/src/store/peer.rs:1956]: Hmmm, I think we can use the commit index in raft-rs directly here. It's right because
1. the first read index request has already checked if the term of last committed entry is the same as current term. (we can add an assert here)
2. the response is sent after getting the raft ready so the `on_leader_commit_idx_changed` is called.

Comment (gengliqi) [reply components/raftstore/src/store/peer.rs:1956]: @NingLin-P  said using raft-rs's commit index may be too large and the caller needs to wait for a long time.
I am ok with these two choices.

Comment (BusyJay) [reply components/raftstore/src/store/peer.rs:1956]: Checking `commit_index` before setting it should be the same as this patch. This patch can be a last protection against any wrong modification. Do you have any reasons to prefer checking term instead?

**Review by 5kbpers — APPROVED** [review]

**Comment by 5kbpers** [comment]
Please resolve conflicts.
