### PR TITLE
raftstore-v2: consider `None` when getting mailbox

### LINKED ISSUE #14233: [dynamic regions] potential unwrap on None when getting mailbox
## Bug Report

image
The unwrap is not safe. The batch system may be shutdown concurrently.

### PR DESCRIPTION
**Pull request by SpadeA-Tang**
### What is changed and how it works?

Issue Number: Close #14233 Ref #12842

What's Changed:

```commit-message
consider None when getting mailbox
```

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test

### Release note 

```release-note
None
```

### CODE REVIEW

File: components/raftstore-v2/src/operation/command/admin/split.rs [hunk 1]
```diff
@@ -704,15 +704,23 @@ impl<EK: KvEngine, ER: RaftEngine> Peer<EK, ER> {
         let region_id = self.region_id();
         if self.storage().has_dirty_data() {
             let tablet_index = self.storage().tablet_index();
-            let mailbox = store_ctx.router.mailbox(region_id).unwrap();
+            let mailbox = store_ctx.router.mailbox(region_id);
+            if mailbox.is_none() {
```
Comment (tonyxuqqi) [inline components/raftstore-v2/src/operation/command/admin/split.rs:708]: what if it's not shutdown? This will miss a code bug. Maybe we should check tikv_util::thread_group::is_shutdown. If it's not shutdown, it should panic.

Comment (SpadeA-Tang) [reply components/raftstore-v2/src/operation/command/admin/split.rs:708]: Good catch. I have added the assertion.

File: components/raftstore-v2/src/operation/command/admin/split.rs [hunk 2]
```diff
@@ -704,15 +704,24 @@ impl<EK: KvEngine, ER: RaftEngine> Peer<EK, ER> {
...
```
Comment (bufferflies) [inline components/raftstore-v2/src/operation/command/admin/split.rs:708]:
```suggestion
            if mailbox.is_none() {
            if let Some(mailbox) = mailbox {
               ....
               schedule()
            }else{
                  assert!(tikv_util::thread_group::is_shutdown(!cfg!(test)));
            }
```

**Review by bufferflies — APPROVED** [review]
Rest LGTM

File: components/raftstore-v2/src/operation/command/admin/split.rs (hunk 2 above)
Comment (SpadeA-Tang) [reply components/raftstore-v2/src/operation/command/admin/split.rs]: Good suggestion.

**Review by tabokie — APPROVED** [review]

File: components/raftstore-v2/src/operation/command/admin/split.rs [hunk 3]
```diff
@@ -706,17 +706,23 @@ impl<EK: KvEngine, ER: RaftEngine> Peer<EK, ER> {
...
+                        self.tablet().unwrap().clone(),
+                        self.region(),
+                        move || {
+                            let _ = mailbox.force_send(PeerMsg::TabletTrimmed { tablet_index });
+                        },
+                    ));
+            } else {
+                // None means the node is shutdown concurrently and thus the
+                // mailboxes in router have been cleared
+                assert!(tikv_util::thread_group::is_shutdown(!cfg!(test)));
```
Comment (BusyJay) [inline components/raftstore-v2/src/operation/command/admin/split.rs:723]: You can check it with `router.is_shutdown()`.

**Review by BusyJay — APPROVED** [review]

File: components/raftstore-v2/src/operation/command/admin/split.rs (hunk 3 above)
Comment (SpadeA-Tang) [reply components/raftstore-v2/src/operation/command/admin/split.rs]: Good suggestion.
