### PR TITLE
raftstore: add hibernate-timeout to prevent leader become hibernated too fast  (#7955)

### LINKED ISSUE #7747: Fail to evict leader when rolling update a new hibernated cluster
## Bug Report

If there are too many leaders or transfer leader just goes too slow, rolling update a cluster can take too much time. If the cluster enables hibernate region at the time, it's possible that all updated nodes will not have any leader because updated leader becomes hibernated very quickly and outdated follower will start election when lost heartbeat from leader for a long time. So it becomes slower because more leaders need to be evicted during rolling update.

A possible solution is to add a hibernate timeout configuration. Leader will not go to sleep before the timeout. So it's safe as long as the hibernate timeout is larger than the update time. And the timeout can be set to a smaller value after the cluster has enabled hibernate region on all nodes.

Another solution is make the configuration be changed online. So users can enable/disable hibernate regions whenever they feel safe.

We need to fix the issue in 3.0.x, 3.1.x and 4.0.

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #7955 to release-4.0

---

Signed-off-by: linning <linningde25@gmail.com>

### What problem does this PR solve?

Issue Number: close #7747 

Problem Summary:

Rolling update to hibernated cluster may take too long, because the hibernated leader will not send heartbeat to non-hibernated followers and cause them to start election.

### What is changed and how it works?

What's Changed:

Add `hibernate-timeout` config to raftstore, new elected leader will not be hibernated within this timeout, and this config can be changed online when the rolling update is finished.

### Release note 
- add hibernate-timeout config to prevent leader become hibernated too fast

### CODE REVIEW

**Comment by NingLin-P** [comment]
/run-idc-jenkins-ci-tikv/integration-compatibility-test

**Comment by NingLin-P** [comment]
/run-idc-jenkins-ci-tikv/integration-ddl-test

File: components/raftstore/src/store/fsm/peer.rs [hunk 1]
```diff
@@ -952,8 +952,9 @@ impl<'a, T: Transport, C: PdClient> PeerFsmDelegate<'a, T, C> {
 
         self.fsm.peer.mut_store().flush_cache_metrics();
 
-        // Keep ticking if there are still pending read requests.
+        // Keep ticking if there are still pending read requests or this node is within hibernate timeout.
         if res.is_none() /* hibernate_region is false */ ||
+            (self.fsm.peer.is_leader() && !self.ctx.is_hibernate_timeout()) ||
```
Comment (BusyJay) [inline components/raftstore/src/store/fsm/peer.rs:957]: Maybe move to L958 is better. As the calculation is almost always false.

File: components/raftstore/src/store/fsm/store.rs [hunk 2]
```diff
@@ -975,6 +990,7 @@ where
             queued_snapshot: HashSet::default(),
             current_time: None,
             perf_context_statistics: PerfContextStatistics::new(self.cfg.value().perf_level),
+            node_start_time: Some(Instant::now()),
```
Comment (BusyJay) [inline components/raftstore/src/store/fsm/store.rs:993]: How about `now_coarse()`?

File: tests/integrations/config/mod.rs [hunk 3]
```diff
@@ -193,6 +193,7 @@ fn test_serde_custom_tikv_config() {
         store_batch_system,
         future_poll_size: 2,
         hibernate_regions: false,
+        hibernate_timeout: ReadableDuration::minutes(10),
```
Comment (BusyJay) [inline tests/integrations/config/mod.rs:196]: Should be a value different from default.

**Review by BusyJay — COMMENTED** [review]
Rest LGTM

**Review by nolouch — APPROVED** [review]
LGTM

**Review by gengliqi — APPROVED** [review]
