### PR TITLE
tikv_alloc: remove thread from thread_arena_map when thread exits

### LINKED ISSUE #19478: The `tikv_allocator_thread_stats` returns incorrect result
### What version of TiKV are you using?

nightly

### Steps to reproduce

Image

The total memory quota is 128GB but the value of some threads are much larger.

### PR DESCRIPTION
**Pull request by glorv**
### What is changed and how it works?

Issue Number: Close #19478

What's Changed:

```commit-message
Fix inaccurate `tikv_allocator_thread_stats` reporting in the jemalloc-backed
  allocator metrics.

  `tikv_allocator_thread_stats` is derived from per-arena jemalloc stats grouped
  by
  trimmed thread name. The collector could over-report in two cases:

  1. `THREAD_ARENA_MAP` entries were not removed when a thread exited, so stale
     arena stats could remain visible in the metric.
  2. Arena stats were summed without deduplicating `(thread_name, arena_index)`,
     so the same arena could be counted more than once for one logical thread
     group.

  This patch fixes both issues by removing the current thread from
  `THREAD_ARENA_MAP` in `remove_thread_memory_accessor()` and deduplicating
  arena
  indices during `iterate_arena_allocation_stats()`
```

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [ ] Need to cherry-pick to the release branch

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note

```release-note
None
```

## Summary by CodeRabbit

* **Bug Fixes**
  * Prevented double-counting in memory allocation statistics by deduplicating entries that map to the same arena after trimming thread identifiers.
  * Ensured thread memory tracking is fully removed when a thread is cleared so stale entries no longer persist.

* **Tests**
  * Added tests to confirm thread memory tracking is cleaned up correctly.
  * Added tests verifying allocation-statistics deduplication yields a single reported entry for equivalent mappings.

### CODE REVIEW

File: components/tikv_alloc/src/jemalloc.rs [hunk 1]
```diff
@@ -231,9 +237,14 @@ pub fn iterate_arena_allocation_stats(mut f: impl FnMut(&str, u64, u64, u64)) {
     // skip advancing the epoch here.
     let thread_arena_map = THREAD_ARENA_MAP.lock().unwrap();
     let mut collected = HashMap::<&str, (u64, u64, u64)>::with_capacity(thread_arena_map.len());
+    let mut seen = HashSet::<(&str, usize)>::with_capacity(thread_arena_map.len());
```
Comment (LykxSassinator) [inline components/tikv_alloc/src/jemalloc.rs:240]: How about make `seen` as a global recorder to record the shared arena_map ? With that, it's no need to rebuild this cache repeatedly when calling `iterate_arena_allocation_stats`.

**Comment by glorv** [comment]
> Better figure out why these threads with same arena

Seems jemalloc will try to reuse arena when thread exited. And there are some modules like "backup-io" it destory and recreate the thread pool when the thread pool thread count config changes. So when reconfig happens, the new thread pool is likely reuses the same arenas as the old pool release them.

File: components/tikv_alloc/src/jemalloc.rs (hunk 1 above)
Comment (glorv) [reply components/tikv_alloc/src/jemalloc.rs:240]: Currently, `iterate_arena_allocation_stats` is only called at metrics collection which by default is 15s interval. As the frequency is very low, there is no need to make it global which will increase the impl complexity.
