### PR TITLE
statistic: more stable test for query test

### LINKED ISSUE #10380: test case is not stable
Here is a stack trace for a failure:
```
[2021-06-17T08:16:25.075Z] test raftstore::test_stats::test_query_stats ... thread 'main' panicked at 'assertion failed: check_query_num_write(&cluster, store_id, QueryKind::Put, 1)', tests/integrations/raftstore/test_stats.rs:339:9
[2021-06-17T08:16:25.075Z] stack backtrace:
[2021-06-17T08:16:25.333Z]    0: rust_begin_unwind
[2021-06-17T08:16:25.333Z]              at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/std/src/panicking.rs:493:5
[2021-06-17T08:16:25.333Z]    1: core::panicking::panic_fmt
[2021-06-17T08:16:25.333Z]              at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/core/src/panicking.rs:92:14
[2021-06-17T08:16:25.333Z]    2: core::panicking::panic
[2021-06-17T08:16:25.333Z]              at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/core/src/panicking.rs:50:5
[2021-06-17T08:16:25.333Z]    3: integrations::raftstore::test_stats::test_query_num::{{closure}}
[2021-06-17T08:16:25.333Z]              at /home/jenkins/tikv-src/tests/integrations/raftstore/test_stats.rs:339:9
[2021-06-17T08:16:25.333Z]    4: integrations::raftstore::test_stats::test_query_num
[2021-06-17T08:16:25.333Z]              at /home/jenkins/tikv-src/tests/integrations/raftstore/test_stats.rs:380:5
[2021-06-17T08:16:25.333Z]    5: integrations::raftstore::test_stats::test_query_stats
[2021-06-17T08:16:25.333Z]              at /home/jenkins/tikv-src/tests/integrations/raftstore/test_stats.rs:268:5
[2021-06-17T08:16:25.333Z]    6: integrations::raftstore::test_stats::test_query_stats::{{closure}}
[2021-06-17T08:16:25.333Z]              at /home/jenkins/tikv-src/tests/integrations/raftstore/test_stats.rs:135:1
[2021-06-17T08:16:25.333Z]    7: core::ops::function::FnOnce::call_once
[2021-06-17T08:16:25.333Z]              at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/core/src/ops/function.rs:227:5
[2021-06-17T08:16:25.333Z]    8: test_util::runner::run_test_with_hook::{{closure}}::{{closure}}
[2021-06-17T08:16:25.333Z]              at /home/jenkins/tikv-src/components/test_util/src/runner.rs:64:21
[2021-06-17T08:16:25.333Z]    9: core::ops::function::FnOnce::call_once{{vtable.shim}}
[2021-06-17T08:16:25.333Z]              at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/core/src/ops/function.rs:227:5
[2021-06-17T08:16:25.333Z]   10: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
[2021-06-17T08:16:25.333Z]              at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/alloc/src/boxed.rs:1546:9
[2021-06-17T08:16:25.333Z] note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[2021-06-17T08:16:25.333Z] FAILED
```

### PR DESCRIPTION
**Pull request by lhy1024**
Signed-off-by: lhy1024 <admin@liudos.us>

### What problem does this PR solve?

Issue Number: close #10380 

Problem Summary:

query test is unstable, for write request statistics it will be occasionally inaccurate

### What is changed and how it works?

What's Changed:

Add more detections while being compatible with occasional redundant qps statistics

### Check List 

Tests 

- Unit test
- Integration test
- Manual test
```
rm t.log
for i in {1..100}
do
    cargo test --package tests --test integrations -- raftstore::test_stats::test_query_stats --exact --nocapture &>> t.log
    sleep 1
done
cat t.log | grep panic
```
there is only panic with `No address added out of total 1 resolved`
image

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by hicqu — APPROVED** [review]

**Review by MyonKeminta — APPROVED** [review]

File: tests/integrations/raftstore/test_stats.rs [hunk 1]
```diff
@@ -399,16 +399,20 @@ fn check_query_num_read(
...
     expect: u64,
 ) -> bool {
-    for _ in 0..100 {
-        let hot_peers = cluster.pd_client.get_store_hotspots(store_id).unwrap();
-        let peer_stat = hot_peers.get(&region_id).unwrap();
-        let query_stat = peer_stat.get_query_stats();
-        if QueryStats::get_query_num(query_stat, kind) == expect {
-            return true;
-        }
+    let start = std::time::SystemTime::now();
```
Comment (BusyJay) [inline tests/integrations/raftstore/test_stats.rs:402]: Why `SystemTime` is used?

File: tests/integrations/raftstore/test_stats.rs [hunk 2]
```diff
@@ -399,16 +399,20 @@ fn check_query_num_read(
...
+    loop {
         sleep_ms(10);
+        if let Some(hot_peers) = cluster.pd_client.get_store_hotspots(store_id) {
+            let peer_stat = hot_peers.get(&region_id).unwrap();
+            let query_stat = peer_stat.get_query_stats();
+            if QueryStats::get_query_num(query_stat, kind) == expect {
```
Comment (BusyJay) [inline tests/integrations/raftstore/test_stats.rs:408]: Since the query is not aggregated, how can it be 100% matching `expect`?

File: tests/integrations/raftstore/test_stats.rs (hunk 1 above)
Comment (lhy1024) [reply tests/integrations/raftstore/test_stats.rs:402]: used to determine whether to enter an infinite loop

File: tests/integrations/raftstore/test_stats.rs (hunk 2 above)
Comment (lhy1024) [reply tests/integrations/raftstore/test_stats.rs:408]: what means ‘aggregated’?

File: tests/integrations/raftstore/test_stats.rs (hunk 1 above)
Comment (BusyJay) [reply tests/integrations/raftstore/test_stats.rs:402]: Why can't `std::time::Instant` detect it?

Comment (lhy1024) [reply tests/integrations/raftstore/test_stats.rs:402]: ok
