### PR TITLE
raftstore: handle `ReadyToDestroyPeer` with incorrect order if the sender is delayed.

### LINKED ISSUE #19004: TiKV panicked during jepsen test
### What version of TiKV are you using?

master

### What operating system and CPU are you using?

k8s

### Steps to reproduce

run jepsen test

### What did you expect?

no panic

### What did happened?

```
[2025/09/20 05:17:24.026 +00:00] [FATAL] [lib.rs:555] ["assertion failed: self.fsm.peer.pending_remove"] [context="(components/raftstore/src/store/fsm/store.rs:1076) peer_id=>3509, (components/raftstore/src/store/fsm/store.rs:1076) region_id=>3505"] [backtrace="   0: tikv_util::set_panic_hook::{{closure}}\n             at /workspace/source/tikv/components/tikv_util/src/lib.rs:546:18\n   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call\n             at /root/.rustup/toolchains/nightly-2025-02-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:1986:9\n      std::panicking::rust_panic_with_hook\n             at /root/.rustup/toolchains/nightly-2025-02-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:839:13\n   2: std::panicking::begin_panic_handler::{{closure}}\n             at /root/.rustup/toolchains/nightly-2025-02-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:697:13\n   3: std::sys::backtrace::__rust_end_short_backtrace\n             at /root/.rustup/toolchains/nightly-2025-02-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys/backtrace.rs:168:18\n   4: rust_begin_unwind\n             at /root/.rustup/toolchains/nightly-2025-02-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:695:5\n   5: core::panicking::panic_fmt\n             at /root/.rustup/toolchains/nightly-2025-02-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panicking.rs:75:14\n   6: core::panicking::panic\n             at /root/.rustup/toolchains/nightly-2025-02-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panicking.rs:145:5\n   7: raftstore::store::fsm::peer::PeerFsmDelegate<EK,ER,T>::on_significant_msg\n             at /workspace/source/tikv/components/raftstore/src/store/fsm/peer.rs:1637:17\n   8: raftstore::store::fsm::peer::PeerFsmDelegate<EK,ER,T>::handle_msgs\n             at /workspace/source/tikv/components/raftstore/src/store/fsm/peer.rs:718:49\n   9: <raftstore::store::fsm::store::RaftPoller<EK,ER,T> as batch_system::batch::PollHandler<raftstore::store::fsm::peer::PeerFsm<EK,ER>,raftstore::store::fsm::store::StoreFsm<EK>>>::handle_normal\n             at /workspace/source/tikv/components/raftstore/src/store/fsm/store.rs:1119:9\n  10: batch_system::batch::Poller<N,C,Handler>::poll\n             at /workspace/source/tikv/components/batch-system/src/batch.rs:458:27\n  11: raftstore::store::worker::refresh_config::PoolController<N,C,H>::increase_by::{{closure}}\n             at /workspace/source/tikv/components/raftstore/src/store/worker/refresh_config.rs:84:21\n      <std::thread::Builder as tikv_util::sys::thread::StdThreadBuildWrapper>::spawn_wrapper::{{closure}}\n             at /workspace/source/tikv/components/tikv_util/src/sys/thread.rs:441:13\n      std::sys::backtrace::__rust_begin_short_backtrace\n             at /root/.rustup/toolchains/nightly-2025-02-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys/backtrace.rs:152:18\n  12: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}\n             at /root/.rustup/toolchains/nightly-2025-02-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:559:17\n      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once\n             at /root/.rustup/toolchains/nightly-2025-02-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panic/unwind_safe.rs:272:9\n      std::panicking::try::do_call\n             at /root/.rustup/toolchains/nightly-2025-02-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:587:40\n      std::panicking::try\n             at /root/.rustup/toolchains/nightly-2025-02-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:550:19\n      std::panic::catch_unwind\n             at /root/.rustup/toolchains/nightly-2025-02-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:359:14\n      std::thread::Builder::spawn_unchecked_::{{closure}}\n             at /root/.rustup/toolchains/nightly-2025-02-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:557:30\n      core::ops::function::FnOnce::call_once{{vtable.shim}}\n             at /root/.rustup/toolchains/nightly-2025-02-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5\n  13: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once\n             at /root/.rustup/toolchains/nightly-2025-02-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:1972:9\n      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once\n             at /root/.rustup/toolchains/nightly-2025-02-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:1972:9\n      std::sys::pal::unix::thread::Thread::new::thread_start\n             at /root/.rustup/toolchains/nightly-2025-02-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys/pal/unix/thread.rs:109:17\n  14: start_thread\n  15: __clone3\n"] [location=/workspace/source/tikv/components/raftstore/src/store/fsm/peer.rs:1637] [thread_name=raftstore-2-0] [thread_id=139]
```

The full logs can be downloaded via [this script](http://fileserver.pingcap.net/download/pingcap/qa/tests/jepsen/logs/250920/jepsen-tps-7956930-1-394/bank-mixed-inplace-follower-procerr/download-logs.sh).

### PR DESCRIPTION
**Pull request by LykxSassinator**
### What is changed and how it works?

Issue Number: Close #19004

Fix the bug introduced by the previous work https://github.com/tikv/tikv/pull/18805 and https://github.com/tikv/tikv/pull/18984, which makes the `raftstore` thread panic on the assertation that a new peer with the same peer-id of the pending removing peer handled the `ReadyToDestroyPeer` unexpectedly.

What's Changed:

```commit-message
Address the corner case that the `raftstore` thread is panic on handling `ReadyToDestroyPeer `.
```

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [ ] Need to cherry-pick to the release branch

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note

```release-note
None.
```

### CODE REVIEW

File: components/raftstore/src/store/peer.rs [hunk 1]
```diff
@@ -691,6 +691,20 @@ impl SplitCheckTrigger {
     }
 }
 
+bitflags! {
+    /// A bitmap contains some useful flags to represent different reason for pending remove.
+    pub struct PendingRemoveReason: u8 {
+        const MERGE   = 0b0000_0001;
+        const DESTROY = 0b0000_0010;
+    }
```
Comment (overvenus) [inline components/raftstore/src/store/peer.rs]: Nit, you can use enum if you do not need bitwise operations, `FlagA | FlagB`.

enum → one-of-many, exclusive choice.

bitflags → many-at-once, combinable options.

File: components/raftstore/src/store/fsm/peer.rs [hunk 2]
```diff
@@ -4259,6 +4271,10 @@ where
         merged_by_target: bool,
         clear_stat: PeerClearMetaStat,
     ) -> bool {
+        assert_eq!(
+            self.fsm.peer.pending_remove,
+            Some(PendingRemoveReason::DESTROY)
+        );
```
Comment (overvenus) [inline components/raftstore/src/store/fsm/peer.rs:4293]:
```suggestion
        assert_eq!(
            self.fsm.peer.pending_remove,
            Some(PendingRemoveReason::DESTROY),
            "{}", ...
        );
```

Nit, add more debug info in case the assert fails.

File: components/raftstore/src/store/fsm/peer.rs [hunk 3]
```diff
@@ -1694,10 +1697,18 @@ where
...
                 clear_stat,
             } => {
-                assert!(self.fsm.peer.pending_remove);
+                if to_peer_id != self.fsm.peer_id() {
+                    // Ignore redundant or stale messages from an outdated peer for the same region.
+                    // This handles the corner case where a stale peer is being removed
+                    // asynchronously while a new peer for the region is added.
+                    // If the async cleanup thread returns a delayed message
+                    // aimed to the removed peer, skip it to avoid acting on stale state.
+                    return;
```
Comment (overvenus) [inline components/raftstore/src/store/fsm/peer.rs:1714]: Add an info log before return, it may be useful if we met other issues related to `ReadyToDestroyPeer`

File: components/raftstore/src/store/fsm/peer.rs [hunk 4]
```diff
@@ -2573,12 +2584,13 @@ where
                     "peer_id" => self.fsm.peer_id(),
                     "res" => ?res,
                 );
-                if self.fsm.peer.wait_data {
+                if self.fsm.peer.wait_data
+                    || self.fsm.peer.pending_remove == Some(PendingRemoveReason::DESTROY)
```
Comment (overvenus) [inline components/raftstore/src/store/fsm/peer.rs]: Please add some comments.

**Review by overvenus — APPROVED** [review]

File: components/raftstore/src/store/fsm/peer.rs [hunk 5]
```diff
@@ -1694,10 +1697,22 @@ where
...
             } => {
-                assert!(self.fsm.peer.pending_remove);
+                if to_peer_id != self.fsm.peer_id() {
+                    // Ignore redundant or stale messages from an outdated peer for the same region.
+                    // This handles the corner case where a stale peer is being removed
+                    // asynchronously while a new peer for the region is added.
+                    // If the async cleanup thread returns a delayed message
+                    // aimed to the removed peer, skip it to avoid acting on stale state.
+                    // This is a corner case after introducing `async destroy peer` by PR#18805.
+                    info!("delayed destroy peer message";
```
Comment (hbisheng) [inline components/raftstore/src/store/fsm/peer.rs:1711]:
```suggestion
                    info!("ignore delayed destroy peer message";
```

**Review by hbisheng — APPROVED** [review]
