### PR TITLE
raftstore,resolved_ts: advance resolved ts as needed

### LINKED ISSUE #13110: Stale read meet `Data not ready` for a long time
### What version of TiKV are you using?
6.1.0

### What did happened?
There only 17 regions, and 9 TiKVs, them distributed in three regions: Tokyo, USA, and Singapore.

### Phenomenon
Login Tokyo node `172.33.0.141` and run MySQL client, querying the data using stale read with `closest-replicas`. on the Tokyo node, read xjpnew1 data of the table will trigger `dataNotReady`:
image
image

### Placement Settings:
image

### Regions of Table
image

### Replicas' Distrubution

```
mysql> select peer_id, a.store_id, b.ADDRESS, b.label from information_schema.tikv_region_peers a left join information_schema.tikv_store_status b on a.store_id=b.store_id  where region_id=1020;
+---------+----------+---------------------+----------------------------------------------------------------------+
| peer_id | store_id | ADDRESS             | label                                                                |
+---------+----------+---------------------+----------------------------------------------------------------------+
|    1022 |       19 | 172.34.0.94:20162   | [{"key": "host", "value": "tikv2"}, {"key": "zone", "value": "xjp"}] |
|    1025 |       21 | 172.34.0.136:20163  | [{"key": "host", "value": "tikv3"}, {"key": "zone", "value": "xjp"}] |
|    1028 |       20 | 172.34.0.178:20161  | [{"key": "host", "value": "tikv1"}, {"key": "zone", "value": "xjp"}] |
|    1048 |        3 | 172.31.13.146:20162 | [{"key": "host", "value": "tikv2"}, {"key": "zone", "value": "mg"}]  |
|    2727 |        2 | 172.31.10.140:20163 | [{"key": "host", "value": "tikv3"}, {"key": "zone", "value": "mg"}]  |
|    2938 |     2808 | 172.33.0.82:20163   | [{"key": "host", "value": "tikv3"}, {"key": "zone", "value": "dj"}]  |
|    2939 |        6 | 172.33.0.141:20161  | [{"key": "host", "value": "tikv1"}, {"key": "zone", "value": "dj"}]  |
+---------+----------+---------------------+----------------------------------------------------------------------+
7 rows in set (0.50 sec)
```

### TiKV Debug Logs
```
$ tail -f tikv.log|grep reject
[2022/07/19 04:16:30.346 +00:00] [DEBUG] [read.rs:332] ["reject stale read by safe ts"] ["read ts"=434688276561920000] ["safe ts"=0] [tag="[region 1020] 2938"]
[2022/07/19 04:16:35.714 +00:00] [DEBUG] [read.rs:332] ["reject stale read by safe ts"] ["read ts"=434688277872640000] ["safe ts"=0] [tag="[region 1020] 2938"]

$ tail -f tikv.log |grep reject
[2022/07/19 04:33:00.354 +00:00] [DEBUG] [read.rs:332] ["reject stale read by safe ts"] ["read ts"=434688536084480000] ["safe ts"=0] [tag="[region 1020] 2938"]
[2022/07/19 04:33:03.570 +00:00] [DEBUG] [read.rs:332] ["reject stale read by safe ts"] ["read ts"=434688536870912000] ["safe ts"=0] [tag="[region 1020] 2938"]
``` 

we can see the safe ts is always 0.

### LINKED ISSUE #14122: Stale read request timeout when resolved-ts is slow
## Bug Report

This is a mirror issue of https://github.com/pingcap/tidb/issues/40903

### What version of TiKV are you using?

v6.5.0

### PR DESCRIPTION
**Pull request by overvenus**
### What is changed and how it works?

Issue Number: Close #14122 

Close #13110
Close https://github.com/pingcap/tidb/issues/40903 

What's Changed:

```commit-message
Fix an issue that stale read fails when a leader is slowly.
```

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test

### Release note 

```release-note
Fix an issue that stale read fails when a leader is slowly.
```

### CODE REVIEW

File: components/raftstore/src/store/peer.rs [hunk 1]
```diff
@@ -4791,7 +4791,7 @@ where
             }
         }
         let flags = WriteBatchFlags::from_bits_check(req.get_header().get_flags());
-        if flags.contains(WriteBatchFlags::STALE_READ) {
+        if flags.contains(WriteBatchFlags::STALE_READ) && !self.is_leader() {
```
Comment (BusyJay) [inline components/raftstore/src/store/peer.rs:4794]: Can you explain more on why it can lead to timeout?

File: components/raftstore/src/store/peer.rs [hunk 2]
```diff
@@ -4791,7 +4791,10 @@ where
             }
         }
         let flags = WriteBatchFlags::from_bits_check(req.get_header().get_flags());
-        if flags.contains(WriteBatchFlags::STALE_READ) {
+        // Leader has the latest data, so we can skip safe_ts check, otherwise
```
Comment (BusyJay) [inline components/raftstore/src/store/peer.rs:4794]: It may not have latest data if it just becomes leader.

Comment (BusyJay) [reply components/raftstore/src/store/peer.rs:4794]: Even if it has latest data, who to do with locks? For example, if it reads using ts1 while some transaction is being committed using ts1 - 1, how to handle the race?

Comment (overvenus) [reply components/raftstore/src/store/peer.rs:4794]: `KeyIsLocked` will be returned to TiDB. So I suppose TiDB or user will handle the race.

Comment (BusyJay) [reply components/raftstore/src/store/peer.rs:4794]: Can you verify that? As if it's a stale read and read ts is less than safe ts, then all locks can just be ignored.

Comment (overvenus) [reply components/raftstore/src/store/peer.rs:4794]: > As if it's a stale read and read ts is less than safe ts

Wait... in this case, it's safe to read even if in a follower.

Comment (BusyJay) [reply components/raftstore/src/store/peer.rs]: Yes, as long as *read ts <= safe ts is checked".

**Comment by overvenus** [comment]
/hold

There is a case that a stale read transaction may read different data between follower and leader if leader skips read_ts check.
When follower applies raft log faster than leader, stale read may read version B on follower and read version A on leader.
```
---------------------------------->
      ^ version A
             ^ version B
                 ^ read_ts
  ^ leader applied_idx
                      ^ follower applied_idx
```

File: components/raftstore/src/store/peer.rs [hunk 3]
```diff
@@ -4776,6 +4782,7 @@ where
         req: RaftCmdRequest,
         check_epoch: bool,
         read_index: Option<u64>,
+        is_read_index: bool,
```
Comment (JmPotato) [inline components/raftstore/src/store/peer.rs:4785]: Can we determine whether this is a read index request according to the above `read_index` option?

**Review by JmPotato — COMMENTED** [review]
The rest LGTM.

File: components/raftstore/src/store/peer.rs (hunk 3 above)
Comment (overvenus) [reply components/raftstore/src/store/peer.rs:4785]: No, because read_local also sets read_index. See `Peer::read_local`.

**Review by JmPotato — APPROVED** [review]

File: components/raftstore/src/store/peer.rs [hunk 4]
```diff
@@ -4795,6 +4795,7 @@ where
             let read_ts = decode_u64(&mut req.get_header().get_flag_data()).unwrap();
             let safe_ts = self.read_progress.safe_ts();
             if safe_ts < read_ts {
+                self.read_progress.notify_advance_resolved_ts();
```
Comment (BusyJay) [inline components/raftstore/src/store/peer.rs:4798]: It can be expansive for every read request to lock.

Comment (overvenus) [reply components/raftstore/src/store/peer.rs:4798]: It's not for every read, but for rejected read.

Comment (BusyJay) [reply components/raftstore/src/store/peer.rs:4798]: Once safe ts is not advanced, rejection should be the major branches.

Comment (overvenus) [reply components/raftstore/src/store/peer.rs:4798]: In practice, there won't be many requests reach the branch, because the latency is high (in my tests, ~4 seconds) it will block clients from sending further requests. Anyway, I will address your comments.

File: tests/failpoints/cases/test_replica_stale_read.rs [hunk 5]
```diff
@@ -116,7 +116,7 @@ fn test_stale_read_1pc_flow_replicate() {
     );
     let read_ts = get_tso(&pd_client);
     // wait for advance_resolved_ts.
-    sleep_ms(200);
+    sleep_ms(1000);
```
Comment (BusyJay) [inline tests/failpoints/cases/test_replica_stale_read.rs:119]: Why the change?

File: components/resolved_ts/src/advance.rs [hunk 6]
```diff
@@ -88,15 +92,22 @@ impl AdvanceTsWorker {
...
         advance_ts_interval: Duration,
-        cfg_update_notify: Arc<Notify>,
+        advance_notify: Arc<Notify>,
     ) {
         let cm = self.concurrency_manager.clone();
         let pd_client = self.pd_client.clone();
         let scheduler = self.scheduler.clone();
         let timeout = self.timer.delay(advance_ts_interval);
+        let min_timeout = self.timer.delay(
+            if DEFAULT_MIN_ADVANCE_TS_INTERVAL < self.advance_ts_interval {
```
Comment (BusyJay) [inline components/resolved_ts/src/advance.rs:102]: You mean `cmp::min`?

File: components/raftstore/src/store/peer.rs [hunk 7]
```diff
@@ -4796,6 +4799,13 @@ where
             let read_ts = decode_u64(&mut req.get_header().get_flag_data()).unwrap();
             let safe_ts = self.read_progress.safe_ts();
             if safe_ts < read_ts {
+                let now = Instant::now();
```
Comment (BusyJay) [inline components/raftstore/src/store/peer.rs:4802]: It's neither a cheap call. Maybe you can check if safe_ts is way less than read_ts first.

File: tests/failpoints/cases/test_replica_stale_read.rs (hunk 5 above)
Comment (overvenus) [reply tests/failpoints/cases/test_replica_stale_read.rs:119]: To stable the test.

Comment (BusyJay) [reply tests/failpoints/cases/test_replica_stale_read.rs:119]: How the change can affect the test case?

Comment (overvenus) [reply tests/failpoints/cases/test_replica_stale_read.rs:119]: I add 200ms delay in resolved-ts advance to prevent frequent notify

Comment (BusyJay) [reply tests/failpoints/cases/test_replica_stale_read.rs:119]: Can it be speed up for tests? Otherwise I'm afraid the test time can be way longer.

**Review by BusyJay — APPROVED** [review]
Rest LGTM
