### PR TITLE
pd_client: make `update_service_safe_point` returns error when stale

### LINKED ISSUE #16910: pd_client: make `update_service_gc_safepoint`  return error when the safepoint wasn't uploaded.
## Development Task
For now, this function was only called by `br-stream`. Which in fact doesn't have well defined behavior (but just logging) when encountering failed to upload service GC safepoint. So in fact the lack of error reporting won't really make things worse. But anyway the API is then get pretty weird, we need to enhance it.

### PR DESCRIPTION
**Pull request by YuJuncen**
### What is changed and how it works?

Issue Number: Close #16910

What's Changed:

```commit-message
Let `update_service_safe_point` return an error when the provided service gc safepoint is stale.
```

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [ ] Need to cherry-pick to the release branch

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note

```release-note
None
```

### CODE REVIEW

File: components/backup-stream/src/endpoint.rs [hunk 1]
```diff
@@ -230,7 +230,14 @@ where
                     TimeStamp::new(safepoint.saturating_sub(1)),
                     safepoint_ttl,
                 )
-                .await?;
+                .await
+                .or_else(|err| match err {
+                    pd_client::Error::UnsafeServiceGcSafePoint { .. } => {
+                        warn!("gc safe point exceeds the task checkpoint. skipping uploading..."; "err" => %err);
+                        Ok(())
+                    }
```
[the remark this answers is not in the document]
Comment (MyonKeminta) [reply components/backup-stream/src/endpoint.rs:238]:
```suggestion
                .or_else(|err| match err {
                    pd_client::Error::UnsafeServiceGcSafePoint { .. } => {
                        warn!("gc safe point exceeds the task checkpoint. skipping uploading"; "err" => %err);
                        Ok(())
                    }
```

By the way I think there don't need to be "..." here as it doesn't need any subsequent operations to perform the skipping.

File: components/test_pd/src/mocker/service.rs [hunk 2]
```diff
@@ -353,4 +355,31 @@ impl PdMocker for Service {
...
         Some(Ok(resp))
     }
+
+    fn update_service_gc_safe_point(
+        &self,
+        req: &UpdateServiceGcSafePointRequest,
+    ) -> Option<Result<UpdateServiceGcSafePointResponse>> {
+        let val = self
+            .service_gc_safepoint
+            .fetch_update(Ordering::SeqCst, Ordering::SeqCst, |v| {
```
Comment (MyonKeminta) [inline components/test_pd/src/mocker/service.rs:365]: Doesn't the mock pd distinguish service safe points of different services?

Comment (YuJuncen) [reply components/test_pd/src/mocker/service.rs:365]: Nope, because I'm only going to test the function `check_update_service_safe_point_resp`, so I think perhaps we don't need a full-featured PD mock?

File: components/backup-stream/src/endpoint.rs (hunk 1 above)
[the remark this answers is not in the document]
Comment (YuJuncen) [reply components/backup-stream/src/endpoint.rs:238]: In this context, we are going to pause GC when a log backup task encounters some error that cannot be recovered internally. Hence we extend the lifetime of the service GC safepoint here for possible manual operations. 

When the gc safe point is greater than the task's checkpoint, the task itself technically cannot be restored by any operation. We just need to write a "tombstone" for the task here.

File: components/test_pd_client/src/pd.rs [hunk 3]
```diff
@@ -928,7 +928,7 @@ pub struct TestPdClient {
 
 #[derive(Debug, PartialEq, Clone)]
 pub struct GcSafePoint {
-    pub serivce: String,
+    pub service: String,
```
[the remark this answers is not in the document]
Comment (YuJuncen) [reply components/test_pd_client/src/pd.rs:931]: It seems the spellchecker didn't work when this code was written. :sad:

File: components/test_pd/src/mocker/service.rs (hunk 2 above)
Comment (MyonKeminta) [reply components/test_pd/src/mocker/service.rs:365]: It perhaps doesn't matter much though, I think it might be able to avoid some possible confusion or misunderstanding if someone want to do more stuff with it if we implement it completely.

**Review by MyonKeminta — APPROVED** [review]
Rest LGTM

File: components/test_pd/src/mocker/service.rs (hunk 2 above)
Comment (YuJuncen) [reply components/test_pd/src/mocker/service.rs:365]: Perhaps I can add some assertions that make sure the user won't misuse this. Implementing a full-featured simulation is also an option (and I guess there won't be much more codes needed than the former), but I still prefer the assert method, because we are in fact not going to test that part and won't add code to test the full-featured implementation (who tests test code?), if the full-featured implementation was wrong, it will be even more confusing for the future users.

Comment (YuJuncen) [reply components/test_pd/src/mocker/service.rs:365]: (Well, I have just noticed that implementing the full-featured version is far easier than make a sound assertion...)

**Review by MyonKeminta — APPROVED** [review]

**Comment by YuJuncen** [comment]
/merge

(It seems the clippy server is down?)
