### PR TITLE
log-backup: an ad-hoc way for hot reloading TLS certs

### LINKED ISSUE #14071: Log backup: failed to register task after online reload certification when TLS enable
### What version of TiKV are you using?

v6.5.0

### What operating system and CPU are you using?

N/A

### Steps to reproduce

1. deploy a cluster.
2. replace TiKV certifications without restart and wait for the old certifications expired.
3. start a log backup task

### What did you expect?
tasks run normally(support online reload TLS certifications)

### What did happened?
receive bad certificate error when mTLS handshake.

### PR DESCRIPTION
**Pull request by YuJuncen**
Signed-off-by: hillium <yujuncen@pingcap.com>

### What is changed and how it works?

Issue Number: Close #14071 

What's Changed:
This PR have modified the `LazyEtcd` and made it checks the TLS certification every time when retrieving the client.
Once it find the TLS certification has been modified, it would reconnect to the server.

```commit-message
Log backup would aware TLS certifications changing.
```

### Related changes

- Need to cherry-pick to the release branch

#### Tests 

It is integrated with etcd, hence hard to make unit tests.

- Manual test (add detailed scripts or steps below)

The manual test creates a cluster where *TLS certifications are reloaded every 5 mins* and *all TLS certification lives for 10 mins*.
with the script:
```bash
#! /bin/bash

set -eu

lib=${lib:-/root/lovecloudnative/scripts}
out=${out:-/root/lovecloudnative/ssl}
profile=${profile:-internal-debug}
namespace=${namespace:-tidb-cluster}
cluster_name=${cluster_name:-basic}
cd "$out"

for comp in tidb tikv pd; do
    cfssl gencert -ca=$out/ca.pem -ca-key=$out/ca-key.pem -config=$out/ca-config.json -profile="$profile" <($lib/csr-for $comp) | cfssljson -bare $comp-server 
    kubectl delete secret/${cluster_name}-$comp-cluster-secret || true
    kubectl create secret generic ${cluster_name}-$comp-cluster-secret --namespace=${namespace} --from-file=tls.crt=$comp-server.pem --from-file=tls.key=$comp-server-key.pem --from-file=ca.crt=ca.pem
done

cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config=ca-config.json -profile=client <($lib/csr-for client) | cfssljson -bare client
kubectl delete secret/${cluster_name}-cluster-client-secret || true
kubectl create secret generic ${cluster_name}-cluster-client-secret --namespace=${namespace} --from-file=tls.crt=$comp-server.pem --from-file=tls.key=$comp-server-key.pem --from-file=ca.crt=ca.pem
```
Where the config `internal-debug` yields certs with a TTL of 10 mins.
```json
"internal-debug": {
                "expiry": "10m",
                "usages": [
                    "signing",
                    "key encipherment",
                    "server auth",
                    "client auth"
                ]
            },
```

In such a cluster, we start the `shuffle-leader-shceduler` and run it for a long time. If log backup works properly in this cluster, we can make sure that the TLS certifications reloading are well-handled.

In this cluster, we are going to do after 10mins:
- Start a task.
- Check whether the task's checkpoint can be advanced normally.
- Pause / Restart it, check whether it works normally.
- Stop the task and start a new task, check whether the task works normally.

### Release note 

```release-note
Now, log backup supports hot-reloading the TLS certifications.
```

### CODE REVIEW

File: components/backup-stream/src/metadata/store/lazy_etcd.rs [hunk 1]
```diff
@@ -130,23 +148,34 @@ where
...
+        let store = EtcdStore::from(store);
+        self.cli = Some(store);
+        Ok(self.cli.as_ref().unwrap())
     }
 
-    pub async fn get_cli(&self) -> Result<&EtcdStore> {
-        let store = self.cli.get_or_try_init(|| self.connect()).await?;
-        Ok(store)
+    pub async fn get_cli(&mut self) -> Result<&EtcdStore> {
+        let modified = self.conf.tls.get_config().is_modified(&mut self.last_modified)
```
Comment (3pointer) [inline components/backup-stream/src/metadata/store/lazy_etcd.rs:170]: when update last_modified?

Comment (YuJuncen) [reply components/backup-stream/src/metadata/store/lazy_etcd.rs:170]: `is_modified` would update it. (How amazing!)
```rust
pub fn is_modified(&self, last: &mut Option<SystemTime>) -> Result<bool, Box<dyn Error>> {
        let this = fs::metadata(&self.cert_path)?.modified()?;
        if let Some(last) = last {
            if *last == this {
                return Ok(false);
            }
        }
        *last = Some(this);
        Ok(true)
    }
```

Comment (3pointer) [reply components/backup-stream/src/metadata/store/lazy_etcd.rs:170]: Ok

**Review by 3pointer — APPROVED** [review]

**Review by hicqu — APPROVED** [review]
