### PR TITLE
CDC: fix rawkv resolved ts issue

### LINKED ISSUE #13144: RawKV CDC does not advance in some scenario
### What version of TiKV are you using?
master branch/nightly

### Steps to reproduce
1. Deploy two tikv clusters, up and downstream, up is with tikv-cdc node
2. Preload some data, for example 5 million ycsb workloada rawkv mode.
3. Start ycsb wordloada with rawkv mode.
4. Create tikv-cdc changefeed.
5. Wait 5 minutes and stop ycsb workload
6. Wait cdc sink finish and compare checksum of two  tikv cluster.
### What did you expect?

Raw checksum is the same.

### What did happened?
1. For debug, the `resolved_ts` does not advance and hang.

### PR DESCRIPTION
**Pull request by haojinming**
Signed-off-by: haojinming <jinming.hao@pingcap.com>

### What is changed and how it works?

Issue Number: Close #13144 

What's Changed:

1. Track raw ts only after downstream is initializing or normal state.
2. Add raw region judgement with start/end key.
3. Fix raw untrack ts issue, use prev ts, see comments in the code.
4. Donot fill cache when increment scan.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)

Side effects

### Release note 

```release-note
None
```

### CODE REVIEW

File: components/cdc/src/endpoint.rs [hunk 1]
```diff
@@ -950,7 +950,7 @@ impl<T: 'static + RaftStoreRouter<E>, E: KvEngine> Endpoint<T, E> {
                     resolved_regions.push(region_id, resolved_ts.min());
                     // The judge of raw region is not accuracy here, and we may miss at most one
                     // "normal" raw region. But this will not break the correctness of outlier detection.
-                    if resolved_ts.is_min_ts_from_raw() {
+                    if resolved_ts.is_min_ts_from_raw() || delegate.is_raw_region() {
```
Comment (pingyu) [inline components/cdc/src/endpoint.rs:953]: Suggest to add test case for the scenario that `txn_ts == raw_ts`.

File: components/cdc/src/observer.rs [hunk 2]
```diff
@@ -106,6 +126,8 @@ impl<E: KvEngine> CmdObserver<E> for CdcObserver {
     ) {
         assert!(!cmd_batches.is_empty());
         fail_point!("before_cdc_flush_apply");
+        // Untrack raw ts here because it's tracked in CausalObserver::pre_propose_query.
+        self.untrack_raw_ts(cmd_batches);
```
Comment (pingyu) [inline components/cdc/src/observer.rs:130]: There is gap between "untrack raw ts" and "on_multi_batch". It is possible that a `on_min_ts` is inserted in the gap.

File: components/cdc/src/observer.rs [hunk 3]
```diff
@@ -91,6 +92,25 @@ impl CdcObserver {
             .get(&region_id)
             .cloned()
     }
+
+    // Ignore err result, raw dead lock is detected in `Endpoint::on_min_ts`
+    // TODO: optimize this if cdc is not registered.
+    fn untrack_raw_ts(&self, cmd_batches: &mut Vec<CmdBatch>) {
+        match get_max_raw_ts(cmd_batches) {
```
[the remark this answers is not in the document]
Comment (haojinming) [reply components/cdc/src/observer.rs]: done

File: components/cdc/src/delegate.rs [hunk 4]
```diff
@@ -44,6 +44,46 @@ use crate::{
...
+            continue;
+        }
+        let region_id = batch.region_id;
+        let cdc_id = batch.cdc_id;
+        let cmd = &batch.cmds.last().unwrap();
+        let raw_put_requests: Vec<&PutRequest> = cmd
+            .request
+            .get_requests()
+            .iter()
+            .filter(|req| {
```
[the remark this answers is not in the document]
Comment (haojinming) [reply components/cdc/src/delegate.rs]: good suggestion, thanks.

File: components/cdc/src/observer.rs (hunk 2 above)
Comment (haojinming) [reply components/cdc/src/observer.rs]: done, schedule `RawUntrackTs` task after `MultiBatch task` or level is not All.

File: components/cdc/src/observer.rs [hunk 5]
```diff
@@ -91,6 +103,58 @@ impl CdcObserver {
...
+            return;
+        }
+        if let Err(e) = self.sched.schedule(Task::RawUntrackTs { raw_region_ts }) {
+            warn!("cdc schedule task failed"; "error" => ?e);
+        }
+    }
+
+    // parse rawkv cmd from CmdBatch Vec and return the max ts of every region.
+    pub fn get_raw_region_ts(&self, cmd_batches: &Vec<CmdBatch>) -> Vec<RawRegionTs> {
+        let mut region_ts = vec![];
```
Comment (pingyu) [inline components/cdc/src/observer.rs:118]: Suggest to check `api_version = V2` to reduce un-necessary scan.

File: components/cdc/src/observer.rs [hunk 6]
```diff
@@ -91,6 +103,58 @@ impl CdcObserver {
...
+            let region_id = batch.region_id;
+            let cdc_id = batch.cdc_id;
+            if let Some(ob_id) = self.is_subscribed(region_id) {
+                if ob_id != cdc_id {
+                    continue;
+                }
+            } else {
+                continue;
+            }
+            let cmd = &batch.cmds.last().unwrap();
```
Comment (pingyu) [inline components/cdc/src/observer.rs:132]: Other items in `cmds` should also be scan, in case the last raw put entry is not in the last `cmd`.

File: components/cdc/src/observer.rs [hunk 7]
```diff
@@ -91,6 +103,58 @@ impl CdcObserver {
...
+    // parse rawkv cmd from CmdBatch Vec and return the max ts of every region.
+    pub fn get_raw_region_ts(&self, cmd_batches: &Vec<CmdBatch>) -> Vec<RawRegionTs> {
+        let mut region_ts = vec![];
+        for batch in cmd_batches {
+            if batch.is_empty() {
+                continue;
+            }
+            let region_id = batch.region_id;
+            let cdc_id = batch.cdc_id;
+            if let Some(ob_id) = self.is_subscribed(region_id) {
```
Comment (pingyu) [inline components/cdc/src/observer.rs:125]: Suggest:
```if !self.is_subscribed(region_id).map_or(false, |ob_id| ob_id == cdc_id)```

File: components/cdc/src/endpoint.rs [hunk 8]
```diff
@@ -2027,6 +2049,7 @@ mod tests {
             conn_id,
             ChangeDataRequestKvApi::RawKv,
         );
+        downstream.get_state().store(DownstreamState::Normal);
```
Comment (pingyu) [inline components/cdc/src/endpoint.rs:2052]: It should be not necessary.

File: components/cdc/src/endpoint.rs [hunk 9]
```diff
@@ -2091,6 +2114,7 @@ mod tests {
...
```
Comment (pingyu) [inline components/cdc/src/endpoint.rs:2117]: Ditto.

File: components/cdc/src/endpoint.rs [hunk 10]
```diff
@@ -2166,6 +2190,7 @@ mod tests {
                 conn_id,
                 ChangeDataRequestKvApi::RawKv,
             );
+            downstream.get_state().store(DownstreamState::Normal);
```
Comment (pingyu) [inline components/cdc/src/endpoint.rs:2193]: Ditto.

File: components/cdc/src/delegate.rs [hunk 11]
```diff
@@ -908,6 +908,16 @@ impl Delegate {
         // To inform transaction layer no more old values are required for the region.
         self.txn_extra_op.store(TxnExtraOp::Noop);
     }
+
+    // if raw data and tidb data both exist in this region, it will return false.
+    pub fn is_raw_region(&self) -> bool {
```
Comment (pingyu) [inline components/cdc/src/delegate.rs:913]: Suggest to add unit test for this new method.

File: components/cdc/src/delegate.rs [hunk 12]
```diff
@@ -614,19 +614,20 @@ impl Delegate {
...
         }
         // the entry's timestamp is non-decreasing, the last has the max ts.
-        let max_raw_ts = TimeStamp::from(entries.last().unwrap().commit_ts);
+        // use prev ts, see reason at CausalObserver::pre_propose_query
+        let max_raw_ts = max_ts.prev();
         match self.resolver {
             Some(ref mut resolver) => {
-                // use prev ts, see reason at CausalObserver::pre_propose_query
-                resolver.raw_untrack_lock(max_raw_ts.prev());
+                resolver.raw_untrack_lock(max_raw_ts);
```
Comment (pingyu) [inline components/cdc/src/delegate.rs:630]: Suggest to try adding unit test for the condition that `self.resolver` is none.

Comment (haojinming) [reply components/cdc/src/delegate.rs:630]: added test case in `test_raw_pending_lock`

File: components/cdc/src/observer.rs (hunk 5 above)
Comment (haojinming) [reply components/cdc/src/observer.rs:124]: `api_version` is added in CdcObserver and filter the non-apiv2 cmd, thus TiDB should not be affect if user does not enable apiv2.

File: components/cdc/src/observer.rs (hunk 6 above)
Comment (haojinming) [reply components/cdc/src/observer.rs]: Done

File: components/cdc/src/observer.rs (hunk 7 above)
Comment (haojinming) [reply components/cdc/src/observer.rs]: Done

File: components/cdc/src/delegate.rs (hunk 11 above)
Comment (haojinming) [reply components/cdc/src/delegate.rs:913]: @pingyu All comments are aderessed, PTAL~

File: components/cdc/src/endpoint.rs (hunk 1 above)
Comment (haojinming) [reply components/cdc/src/endpoint.rs:978]: Added in `test_raw_dead_lock` test case.

File: components/cdc/src/observer.rs [hunk 13]
```diff
@@ -106,6 +181,11 @@ impl<E: KvEngine> CmdObserver<E> for CdcObserver {
     ) {
         assert!(!cmd_batches.is_empty());
         fail_point!("before_cdc_flush_apply");
+        // Untrack raw ts regardless of the ob level
+        // Because RawTrackTask cannot get the ob level in
```
Comment (pingyu) [inline components/cdc/src/observer.rs:185]: Suggest: Because RawKV locks is tracked regradless of observe level, as it is in Raft propose procedure and can not get an accurate observe level.

File: components/cdc/src/observer.rs [hunk 14]
```diff
@@ -368,4 +452,179 @@ mod tests {
...
+
+        // non-rawkv
+        let data3 = vec![
+            put_cf(
+                CF_WRITE,
+                ApiV2::encode_raw_key(b"ra", Some(TimeStamp::from(500))).as_encoded(),
+                b"v1",
+            ),
+            put_cf(
+                CF_WRITE, // this is onn-rawkv
```
Comment (pingyu) [inline components/cdc/src/observer.rs:596]:
```suggestion
                CF_WRITE, // this is non-rawkv
```

File: components/cdc/src/delegate.rs [hunk 15]
```diff
@@ -1265,4 +1275,48 @@ mod tests {
             }
         }
     }
+
+    #[test]
+    fn test_is_raw_region() {
+        let region_id = 10;
+        let mut region = Region::default();
+        region.set_id(region_id);
+        region.set_start_key(vec![b'r', 0, 0, 0, b'a']);
```
Comment (pingyu) [inline components/cdc/src/delegate.rs:1284]: Nit: codes of the 4 cases are duplicated. Suggest to use a vector to organize cases and iterate on it.

File: components/cdc/src/observer.rs [hunk 16]
```diff
@@ -106,6 +181,11 @@ impl<E: KvEngine> CmdObserver<E> for CdcObserver {
     ) {
         assert!(!cmd_batches.is_empty());
         fail_point!("before_cdc_flush_apply");
+        // Untrack raw ts regardless of the ob level
```
Comment (pingyu) [inline components/cdc/src/observer.rs:184]: Nit: Suggest to add blank lines before and after this new block. To make the procedure more clear.

**Review by pingyu — COMMENTED** [review]
Rest LGTM.

**Review by pingyu — APPROVED** [review]
LGTM~

**Review by overvenus — APPROVED** [review]
