### PR TITLE
raftstore-v2: gc removed_records and merged_records on tombstone store 

### LINKED ISSUE #15669: [Dynamic Regions] Leader keeps sending GcPeerRequests to peers on tombstone store
## Bug Report

As title, instead, leader should remove such peers directly.

### What version of TiKV are you using?

v7.3.0

### Steps to reproduce

```rust
#[test_case(test_raftstore_v2::new_server_cluster)]
fn test_gc_peer_on_tombstone_store() {
    let mut cluster = new_cluster(0, 3);
    configure_for_merge(&mut cluster.cfg);
    cluster.cfg.raft_store.gc_peer_check_interval = ReadableDuration::millis(500);
    let pd_client = Arc::clone(&cluster.pd_client);
    pd_client.disable_default_operator();
    cluster.run();
    cluster.must_put(b"k1", b"v1");

    let region = cluster.get_region(b"k1");

    let peer_on_store1 = find_peer(&region, 1).unwrap().clone();
    let peer_on_store3 = find_peer(&region, 3).unwrap().clone();
    cluster.must_transfer_leader(region.get_id(), peer_on_store1);
    cluster.add_send_filter(IsolationFilterFactory::new(3));
    pd_client.must_remove_peer(region.get_id(), peer_on_store3.clone());

    // Immediately invalidate store address cache.
    fail::cfg("mock_store_refresh_interval_secs", "return(0)").unwrap();

    // Shutdown store 3 and wait for gc peer ticks.
    cluster.stop_node(3);
    cluster.clear_send_filters();
    sleep_ms(3 * cluster.cfg.raft_store.gc_peer_check_interval.as_millis());

    cluster.must_empty_region_removed_records(region.get_id());
}
```

### PR DESCRIPTION
**Pull request by overvenus**
### What is changed and how it works?

Issue Number: Close #15669

What's Changed:

```commit-message
Let leader directly GC removed_records and merged_records on tombstone store,
instead of sending GcPeerRequests to such store.
```

### Check List 

Tests 

- Integration test

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by tonyxuqqi — APPROVED** [review]

File: src/server/resolve.rs [hunk 1]
```diff
@@ -95,9 +108,20 @@ where
             // it explicitly.
             Err(pd_client::Error::StoreTombstone(_)) => {
                 RESOLVE_STORE_COUNTER_STATIC.tombstone.inc();
-                return Err(box_err!("store {} has been removed", store_id));
+                self.router.report_store_maybe_tombstone(store_id);
```
Comment (Connor1996) [inline src/server/resolve.rs:111]: should avoid calling it too frequent as `broadcast_normal` is a quite time-consuming operation holding lock which would affect raftstore

File: components/raftstore-v2/src/operation/life.rs [hunk 2]
```diff
@@ -713,6 +713,37 @@ impl<EK: KvEngine, ER: RaftEngine> Peer<EK, ER> {
...
     }
 
+    // Clean up removed and merged records for peers on tombstone stores,
+    // otherwise it may keep sending gc peer request to the tombstone store.
+    pub fn on_store_maybe_tombstone_gc_peer(&mut self, store_id: u64) {
+        let mut peers_on_tombstone = vec![];
+        let state = self.storage().region_state();
+        for peer in state.get_removed_records() {
+            if peer.get_store_id() == store_id {
+                peers_on_tombstone.push(peer.clone());
```
[the remark this answers is not in the document]
Comment (overvenus) [reply components/raftstore-v2/src/operation/life.rs:723]: It may have multiple peers on that store.

File: src/server/resolve.rs (hunk 1 above)
Comment (overvenus) [reply src/server/resolve.rs:111]: For now, it's a blank implementation for raftstore v1, and only works for raftstore v2 which has fewer regions. It might be okay (?) I think. I will add a metric to mentoring the cost.

Comment (overvenus) [reply src/server/resolve.rs:111]: Turns out there is already a metric for broadcast duration, `tikv_broadcast_normal_duration_seconds`.

**Review by Connor1996 — APPROVED** [review]
LGTM
