### PR TITLE
fix: find the correct last_change_ts after upgrade from versions < 6.5

### LINKED ISSUE #14780: Clusters upgraded from <6.5 to >=6.5 may suffer additional bad performance from accumulated lock records
### The problem

There used to be a problem that `WriteType::Lock` records may accumulate in write CF and slow down read performance. Before 6.5, we have an optimization that change `Lock` records into `Put` records in some limited cases, but it's not complete and sometimes causes problems.

Later a complete solution to the problem (https://github.com/tikv/tikv/issues/13694) was proposed and implemented, and then the old solution was reverted (https://github.com/pingcap/tidb/pull/42488). However, there are still some unfinished stuff here:

1. The optimization may not take effect for some old data from upgraded clusters. It's unimplemented yet as said in [the tracking issue](https://github.com/tikv/tikv/issues/13694). If a key has a `Lock` or `Rollback` record from old version (doesn't have the `last_change_ts` field), a new `Lock` record written on it won't have the field either. We used to thought it at least won't make anything worse. However since [an old optimization was reverted](https://github.com/pingcap/tidb/pull/42488), cases that benefits from the old optimization may suddenly run into problem after upgrading to new version.
2. The last version information was not properly set for `Rollback` records (in `rollback` and `check_txn_status` requests). It may cause more severe problem than we expected: if a key that's frequently locked without changing (accumulates `Lock` records), and occationally a rollback occurs on it, then due to the behavior we mentioned above that *`Lock` records written after another `Lock` or `Rollback` records without last version info will keep not containing last version info*, unoptimized lock records will then accumulate on this key. Actually, setting last version info for rollback record was once implemented, but later reverted since it's found to have correctness issue (see: https://github.com/tikv/tikv/pull/13834). It can't be simply implemented as how we do for `Lock` records.

#### Approach 1: Continue scanning write records after skipping

It's already proposed in this comment: https://github.com/tikv/tikv/pull/13717#discussion_r1011270636

When calculating the last version info, if the most recent write record is a `Lock` or `Rollback` record without last version info (which may come from old version), we still make the next record point to it. When reading the latest `Lock`/`Rollback` record and jumps into another `Lock`/`Rollback` record (without last version info), we let the reader continue scanning versions one by one as how the old reading logic did.

```
Reading
   |  _______skipping______
   ↓ /                      ↘  ----next-->  ----next-->
   * Lock@15    * Lock@13   | * Lock@10    * Lock@8    *Put@5
     last->10     last->10  |
                            |
                            ^ Upgrading
```

#### Approach 2: Scan and calculate the accurate `last_change_ts` when writting

When calculating the last version info (usually in acquire_pessimistic_lock and prewrite), if we find the most recent version is a `Lock` or `Rollback` without last vesion info, we scan Write CF until finding a valid version (or finding the key is empty). We may add the scanning logic to the function `Write::next_last_change_info`, and pass a reader to it for scanning earlier versions.

In both way, the problem caused by not setting last version info for `Rollback` record can be solved, assuming that `Rollback` recorcds won't accumulate too much.

Currently, we prefer **the second idea** as it looks much easier to implement, and we believe the occational performace cost during writing is acceptable. For the first solution, we'll have to ensure all reading logic supports this behavior and cover all of them by tests.

References: 
* https://github.com/pingcap/tidb/issues/25659
* https://github.com/pingcap/tidb/issues/33393
* https://github.com/tikv/tikv/issues/13694

Fixing this also closes #13694 .

### PR DESCRIPTION
**Pull request by ekexium**
### What is changed and how it works?

Issue Number: Close #14780

What's Changed:

```commit-message
When making a LOCK record, if we do not know `last_change_ts`, iterate to the 
last actual write to find out.
This also fixes the problem that ROLLBACK may prevent LOCKs making using of 
the optimization as mentioned in https://github.com/tikv/tikv/pull/13834
NOTE a implementation change:
If versions_to_last_change > 0 but last_change_ts == 0, the key does not
have a PUT/DELETE record before this write record, **OR the previous change is a DELETE**.
```

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

```release-note
Fix the bug that accumulated LOCKs may slow read operations after upgrade.
```

### CODE REVIEW

File: src/storage/txn/actions/common.rs [hunk 1]
```diff
@@ -0,0 +1,46 @@
...
+    key: &Key,
+    write: &Write,
+    start_ts: TimeStamp,
+    reader: &SnapshotReader<S>,
+    commit_ts: TimeStamp,
+) -> Result<(TimeStamp, u64)> {
+    match write.write_type {
+        WriteType::Put | WriteType::Delete => Ok((commit_ts, 1)),
+        WriteType::Lock | WriteType::Rollback => {
+            if !write.last_change_ts.is_zero() || write.versions_to_last_change != 0 {
```
Comment (cfzjywxk) [inline src/storage/txn/actions/common.rs:21]: if the `last_change_ts` is not zero, it looks the `versions_to_last_change` should always be greater than zero, do we need to add a check and assertion here for the unexpected path?

File: src/storage/txn/actions/common.rs [hunk 2]
```diff
@@ -0,0 +1,46 @@
...
+                // TODO: can we reuse the reader?
+                let snapshot = reader.reader.snapshot().clone();
+                let mut reader = SnapshotReader::new(start_ts, snapshot, true);
+                match reader.get_write_with_commit_ts(key, commit_ts)? {
+                    // last_change_ts == 0 && versions_to_last_change > 0 means the key does not
+                    // exist.
+                    None => Ok((TimeStamp::zero(), 1)),
+                    Some((w, last_change_ts)) => {
+                        assert!(matches!(w.write_type, WriteType::Put | WriteType::Delete));
+                        // we don't know how many versions there are, make `versions_to_last_change`
```
Comment (cfzjywxk) [inline src/storage/txn/actions/common.rs:38]: There may be some statistic information in the `reader` or the request tracker, we could check if they are useful.

File: src/storage/mvcc/reader/reader.rs [hunk 3]
```diff
@@ -2442,4 +2448,76 @@ pub mod tests {
...
+        feature_gate.set_version("6.5.0").unwrap();
+        set_tls_feature_gate(feature_gate);
+
+        engine.lock(k, 30, 31);
+        let snap = RegionSnapshot::<RocksSnapshot>::from_raw(db, region);
+        let mut reader = MvccReader::new(snap, None, false);
+        let res = reader
+            .get_write_with_commit_ts(&Key::from_raw(k), 100.into(), None)
+            .unwrap();
+        assert!(res.is_some());
```
Comment (cfzjywxk) [inline src/storage/mvcc/reader/reader.rs:2486]: Better to check if the value is equal, the `DELETE` path should be coverred too.

File: src/storage/txn/actions/common.rs (hunk 1 above)
Comment (ekexium) [reply src/storage/txn/actions/common.rs:21]: It is better to encapsulate the 2 variables into one enum so such worries can be avoided. I made an attempt but it seems to large for a bugfix. I will refactor it in a following PR.

File: src/storage/mvcc/reader/reader.rs [hunk 4]
```diff
@@ -2442,4 +2448,76 @@ pub mod tests {
...
+        assert_eq!(reader.statistics.write.seek, 1);
+        assert_eq!(reader.statistics.write.next, 0);
+    }
+
+    #[test]
+    fn test_locks_interleaving_rollbacks() {
+        // a ROLLBACK inside a chain of LOCKs won't prevent LOCKs  from tracking the
+        // correct `last_change_ts`
+        let path = tempfile::Builder::new()
+            .prefix("_test_storage_mvcc_reader_skip_lock_after_upgrade_6_5")
```
[the remark this answers is not in the document]
Comment (ekexium) [reply src/storage/mvcc/reader/reader.rs:2497]: Copilot you failed me

File: src/storage/txn/actions/common.rs [hunk 5]
```diff
@@ -0,0 +1,48 @@
...
+                let mut reader = SnapshotReader::new(start_ts, snapshot, true);
+                let res = reader.get_write_with_commit_ts(key, commit_ts);
+                let stat = reader.take_statistics();
+                original_reader.reader.statistics.add(&stat);
+                match res? {
+                    // last_change_ts == 0 && versions_to_last_change > 0 means the key does not
+                    // exist.
+                    None => Ok((TimeStamp::zero(), 1)),
+                    Some((w, last_change_ts)) => {
+                        assert!(matches!(w.write_type, WriteType::Put | WriteType::Delete));
```
[the remark this answers is not in the document]
Comment (ekexium) [reply src/storage/txn/actions/common.rs:41]: Yes.

**Review by MyonKeminta — COMMENTED** [review]
Rest LGTM

**Review by MyonKeminta — APPROVED** [review]

**Review by cfzjywxk — APPROVED** [review]

File: src/storage/txn/actions/common.rs (hunk 2 above)
Comment (ekexium) [reply src/storage/txn/actions/common.rs]: I just found the stat of reader shall be used more carefullly otherwise may lead to more `seek`s than expected. Simply `SEEK_BOUND+1` doesn't hurt much and is robust. I'm gonna leave it as is and optimize this later in another PR.
