### PR TITLE
raftstore-v2: test_read is not stable

### LINKED ISSUE #13625: test_read of raftstore-v2 is not stable and often fails in CI

### PR DESCRIPTION
**Pull request by SpadeA-Tang**
### What is changed and how it works?

Issue Number: Close #13625

What's Changed:

It fails in CI occasionally.
The main reason for it I think is the lease expires unexpectedly due to the slow execution.
This  PR change the lease from 1 sec to 10 sec and refactor the test to make less thread creation.

### Check List 

Tests 

- Unit test
- Integration test

### Release note 

```release-note
None
```

### CODE REVIEW

File: components/raftstore-v2/src/operation/query/local.rs [hunk 1]
```diff
@@ -552,7 +564,7 @@ mod tests {
         let leader2 = prs[0].clone();
         region1.set_region_epoch(epoch13.clone());
         let term6 = 6;
-        let mut lease = Lease::new(Duration::seconds(1), Duration::milliseconds(250));
+        let mut lease = Lease::new(Duration::seconds(10), Duration::milliseconds(250));
```
Comment (sticnarf) [inline components/raftstore-v2/src/operation/query/local.rs:567]: It would look more reasonable that `renew_leader_lease_advance_duration` is changed to 2.5s according to the new max lease?

**Review by sticnarf — APPROVED** [review]

File: components/raftstore-v2/src/operation/query/local.rs (hunk 1 above)
Comment (SpadeA-Tang) [reply components/raftstore-v2/src/operation/query/local.rs:567]: Good suggestio.

**Review by tonyxuqqi — APPROVED** [review]
