### PR TITLE
cop: fix the scan panic when checksum is enabled

### LINKED ISSUE #16371: tikv panic when enable row level checksum and insert some data
### What version of TiKV are you using?

```
["Release Version:   8.0.0-alpha"]
["Git Commit Hash:   8130cb35731d894fe0b5bf7dcf9496b9fcd57bc8"]
```

### Steps to reproduce

1. deploy tidb cluser
```
tiup playground v7.6.0-alpha-instant  --db 1 --kv 1 --pd 1 --tiflash 0 --without-monitor
```

2. enable the row checksum.
```
set global tidb_enable_row_level_checksum=true;
```

3. exit the mysql client, and entry it again, source the following file
```
https://github.com/pingcap/tiflow/blob/master/tests/integration_tests/kafka_simple_basic_avro/data/data.sql
```

### What did you expect?

nothing

### What did happened?

```
[2024/01/12 16:55:02.845 +08:00] [FATAL] [lib.rs:478] ["called `Option::unwrap()` on a `None` value"] [backtrace="   0: backtrace::capture::Backtrace::new\n   1: tikv_util::set_panic_hook::{{closure}}\n   2: std::panicking::rust_panic_with_hook\n   3: std::panicking::begin_panic_handler::{{closure}}\n   4: std::sys_common::backtrace::__rust_end_short_backtrace\n   5: _rust_begin_unwind\n   6: core::panicking::panic_fmt\n   7: core::panicking::panic\n   8: tidb_query_datatype::codec::row::v2::row_slice::RowSlice::cut_checksum_bytes\n   9: tidb_query_datatype::codec::row::v2::row_slice::RowSlice::from_bytes\n  10: <tidb_query_executors::table_scan_executor::TableScanExecutorImpl as tidb_query_executors::util::scan_executor::ScanExecutorImpl>::process_kv_pair\n  11: <tidb_query_executors::util::scan_executor::ScanExecutor<S,I,F> as tidb_query_executors::interface::BatchExecutor>::next_batch::{{closure}}\n  12: <tidb_query_executors::table_scan_executor::BatchTableScanExecutor<S,F> as tidb_query_executors::interface::BatchExecutor>::next_batch::{{closure}}\n  13: <tidb_query_common::execute_stats::WithSummaryCollector<C,T> as tidb_query_executors::interface::BatchExecutor>::next_batch::{{closure}}\n  14: <alloc::boxed::Box<T> as tidb_query_executors::interface::BatchExecutor>::next_batch::{{closure}}\n  15: <tidb_query_executors::selection_executor::BatchSelectionExecutor<Src> as tidb_query_executors::interface::BatchExecutor>::next_batch::{{closure}}\n  16: <tidb_query_common::execute_stats::WithSummaryCollector<C,T> as tidb_query_executors::interface::BatchExecutor>::next_batch::{{closure}}\n  17: <alloc::boxed::Box<T> as tidb_query_executors::interface::BatchExecutor>::next_batch::{{closure}}\n  18: tidb_query_executors::runner::BatchExecutorsRunner<SS>::internal_handle_request::{{closure}}\n  19: <tikv::coprocessor::dag::BatchDagHandler as tikv::coprocessor::RequestHandler>::handle_request::{{closure}}\n  20: <tikv::coprocessor::interceptors::tracker::Tracker<F,E> as core::future::future::Future>::poll\n  21: tikv::read_pool::ReadPoolHandle::spawn_handle::{{closure}}\n  22: <resource_control::future::ControlledFuture<F> as core::future::future::Future>::poll\n  23: yatp::task::future::RawTask<F>::poll\n  24: <yatp::task::future::Runner as yatp::pool::runner::Runner>::handle\n  25: <yatp::queue::multilevel::TrackedRunner<R> as yatp::pool::runner::Runner>::handle\n  26: std::sys_common::backtrace::__rust_begin_short_backtrace\n  27: core::ops::function::FnOnce::call_once{{vtable.shim}}\n  28: std::sys::unix::thread::Thread::new::thread_start\n  29: __pthread_joiner_wake\n"] [location=components/tidb_query_datatype/src/codec/row/v2/row_slice.rs:244] [thread_name=unified-read-pool-2] [thread_id=0x5]

```

### PR DESCRIPTION
**Pull request by cfzjywxk**
### What is changed and how it works?

Issue Number: Close #16371

What's Changed:
When all column values are "NULL", the `offset` array could be empty, and skip it when processing row value.

```commit-message
Fix the scan panic issue when checksum is enabled.
```

### Related changes

- [x] Need to cherry-pick to the release branch

### Check List

Tests 

- [x] Unit test

Side effects

### Release note

```release-note
Fix the scan panic issue when checksum is enabled.
```

### CODE REVIEW

File: components/tidb_query_datatype/src/codec/row/v2/row_slice.rs [hunk 1]
```diff
@@ -233,6 +233,9 @@ impl RowSlice<'_> {
             RowSlice::Big {
                 offsets, values, ..
             } => {
+                if non_null_col_num == 0 {
+                    return values.slice;
```
Comment (zyguan) [inline components/tidb_query_datatype/src/codec/row/v2/row_slice.rs:237]: `*values = LeBytes::new(&slice[..0])` before return, otherwise the `values` still point to the checksum part (although there might be no access to `values` since non_null_col_num is 0).

File: components/tidb_query_datatype/src/codec/row/v2/row_slice.rs [hunk 2]
```diff
@@ -241,6 +244,9 @@ impl RowSlice<'_> {
             RowSlice::Small {
                 offsets, values, ..
             } => {
+                if non_null_col_num == 0 {
+                    return values.slice;
```
Comment (zyguan) [inline components/tidb_query_datatype/src/codec/row/v2/row_slice.rs:248]: ditto

File: components/tidb_query_datatype/src/codec/row/v2/row_slice.rs (hunk 1 above)
Comment (cfzjywxk) [reply components/tidb_query_datatype/src/codec/row/v2/row_slice.rs]: It's refactored, PTAL again thx

**Review by zyguan — APPROVED** [review]

**Review by you06 — APPROVED** [review]

**Review by MyonKeminta — APPROVED** [review]
