### PR TITLE
raftstore-v2: clean up import sst file only if flushed epoch is stale.

### LINKED ISSUE #15018: [Dynamic Region] the available size is a big gap between tikvs and leading to the capacity of one tikv is insufficient
### What version of TiKV are you using?
./tikv-server -V
 TiKV 
Release Version:   7.3.0-alpha
Edition:           Community
Git Commit Hash:   de3d6655c3bb0eceac068207fe7ec8be30bdbcc7
Git Commit Branch: heads/refs/tags/v7.3.0-alpha
UTC Build Time:    2023-06-26 11:13:06
Rust Version:      rustc 1.67.0-nightly (96ddd32c4 2022-11-14)
Enable Features:   pprof-fp jemalloc mem-profiling portable sse test-engine-kv-rocksdb test-engine-raft-raft-engine cloud-aws cloud-gcp cloud-azure
Profile:           dist_release
2023-06-27T08:30:36.095+0800	INFO	k8s/client.go:132	it should be noted that a long-running command will not be interrupted even the use case has ended. For more information, please refer to https://github.com/pingcap/test-infra/discussions/129

### What operating system and CPU are you using?
8c/32g

### Steps to reproduce
1、run tpcc
2、inject network_partition fault between one tikv and others tikv
3、after 10min，recover the fault

### What did you expect?
the available size between tikvs is balanced

### What did happened?
the available size is a big gap between tikvs and leading to the capacity of one tikv is insufficient 
bc9863ae-668b-4f00-b522-3d572fd780ad
d848a265-715b-49dc-a803-ced39bcdbeef
2169c5ea-34bc-447b-87a4-ea64e51a388f
img_v2_1f6911c9-183d-47af-8eac-f4a15304087g

### PR DESCRIPTION
**Pull request by bufferflies**
### What is changed and how it works?

Issue Number: Close #15018

What's Changed:

```commit-message
1.  delete sst by using flushed epoch  not raft epoch to avoid replay this log（flushed epoch is the epoch in raft enginem, which is related with flushed admin index）
2. delete sst divide into two place：
   a. cf flush, the cf flushed index is bigger than the sst applied index 
   b. CleanUpSstTick, the sst epoch is stable than the flushed epoch. 
```

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)

Side effects

### Release note 

```release-note
raftstore-v2: clean up import sst file only if flushed epoch is stale.
```

### CODE REVIEW

File: components/engine_traits/src/flush.rs [hunk 1]
```diff
@@ -61,7 +62,8 @@ struct FlushProgress {
 /// if the flushed index greater than it .
 #[derive(Debug, Clone)]
 pub struct SstApplyState {
-    sst_map: Arc<RwLock<HashMap<Vec<u8>, u64>>>,
+    // Map from cf to SstApplyEntry.
+    sst_map: Arc<RwLock<HashMap<usize, Vec<SstApplyEntry>>>>,
```
Comment (SpadeA-Tang) [inline components/engine_traits/src/flush.rs:66]: It's better to replace HashMap by vec.

File: components/raftstore-v2/src/operation/ready/apply_trace.rs [hunk 2]
```diff
@@ -543,6 +559,24 @@ impl<EK: KvEngine, ER: RaftEngine> Peer<EK, ER> {
         let apply_trace = self.storage_mut().apply_trace_mut();
         apply_trace.on_flush(cf, index);
         apply_trace.maybe_advance_admin_flushed(apply_index);
+        let stale_ssts = self.sst_apply_state().stale_ssts(cf, index);
+        if stale_ssts.is_empty() {
+            return;
+        }
+        info!(
+            self.logger,
+            "delete stale ssts after flush";
```
Comment (SpadeA-Tang) [inline components/raftstore-v2/src/operation/ready/apply_trace.rs:568]: I think it's somewhat misleading. Maybe "schedule delete stale ssts after flush".

File: components/engine_traits/src/flush.rs [hunk 3]
```diff
@@ -72,25 +74,51 @@ impl Default for SstApplyState {
...
+        vec![]
     }
 
-    pub fn delete_ssts(&self, uuids: Vec<Vec<u8>>) {
-        let mut map = self.sst_map.write().unwrap();
-        for uuid in uuids {
-            map.remove(&uuid);
+    pub fn delete_ssts(&self, ssts: &Vec<SstMeta>) {
+        let mut map: std::sync::RwLockWriteGuard<'_, HashMap<usize, Vec<SstApplyEntry>>> =
+            self.sst_map.write().unwrap();
```
Comment (overvenus) [inline components/engine_traits/src/flush.rs:116]: Can we skip type hint?

```suggestion
        let mut map = self.sst_map.write().unwrap();
```

File: components/raftstore-v2/src/raft/storage.rs [hunk 4]
```diff
@@ -129,6 +132,18 @@ impl<EK: KvEngine, ER> Storage<EK, ER> {
     pub fn has_dirty_data(&self) -> bool {
         self.has_dirty_data
     }
+
+    #[inline]
+    pub fn set_flushed_epoch(&mut self, epoch: RegionEpoch) {
+        if util::is_epoch_stale(&self.flushed_epoch, &epoch) {
+            self.flushed_epoch = epoch;
+        }
```
Comment (overvenus) [inline components/raftstore-v2/src/raft/storage.rs:140]: Better to clone epoch when we need.

```suggestion
    pub fn set_flushed_epoch(&mut self, epoch: &RegionEpoch) {
        if util::is_epoch_stale(&self.flushed_epoch, epoch) {
            self.flushed_epoch = epoch.clone();
        }
```

File: components/raftstore-v2/src/operation/ready/snapshot.rs [hunk 5]
```diff
@@ -698,6 +698,7 @@ impl<EK: KvEngine, ER: RaftEngine> Storage<EK, ER> {
         for cf in ALL_CFS {
             lb.put_flushed_index(region_id, cf, last_index, last_index)
                 .unwrap();
+            self.set_flushed_epoch(self.region_state().get_region().get_region_epoch().clone());
```
Comment (overvenus) [inline components/raftstore-v2/src/operation/ready/snapshot.rs:701]: The region has not been persisted yet, is it okay to update flushed epoch?

File: components/raftstore-v2/src/operation/ready/apply_trace.rs [hunk 6]
```diff
@@ -529,11 +537,19 @@ impl<EK: KvEngine, ER: RaftEngine> Storage<EK, ER> {
             .unwrap();
         trace.try_persist = false;
         trace.persisted_applied = trace.admin.flushed;
+
+        self.set_flushed_epoch(epoch);
```
Comment (overvenus) [inline components/raftstore-v2/src/operation/ready/apply_trace.rs:541]: The region has not been persisted yet, is it okay to update flushed epoch?

File: components/raftstore-v2/src/operation/ready/apply_trace.rs [hunk 7]
```diff
@@ -519,6 +522,18 @@ impl<EK: KvEngine, ER: RaftEngine> Storage<EK, ER> {
         }
         let region_id = self.region().get_id();
         let raft_engine = self.entry_storage().raft_engine();
+        let last_epoch = self.region().get_region_epoch();
+        if util::is_epoch_stale(self.flushed_epoch(), last_epoch) {
```
Comment (SpadeA-Tang) [inline components/raftstore-v2/src/operation/ready/apply_trace.rs:526]: why not compare self.flushed_epoch with epoch of line527 directly?

File: components/raftstore-v2/src/operation/ready/apply_trace.rs [hunk 8]
```diff
@@ -609,6 +648,15 @@ impl<EK: KvEngine, ER: RaftEngine> Peer<EK, ER> {
...
                     ctx.engine.consume(&mut lb, true).unwrap();
+                    let epoch = ctx
+                        .engine
+                        .get_region_state(region_id, admin_flush)
+                        .unwrap()
+                        .unwrap()
+                        .get_region()
+                        .get_region_epoch()
+                        .clone();
+                    self.storage_mut().set_flushed_epoch(epoch);
```
Comment (SpadeA-Tang) [inline components/raftstore-v2/src/operation/ready/apply_trace.rs:659]: why is this necessary? the cluster is about to close.

File: components/raftstore-v2/src/operation/ready/snapshot.rs (hunk 5 above)
Comment (bufferflies) [reply components/raftstore-v2/src/operation/ready/snapshot.rs]: yes, I have moved it to persisted msg.

File: components/raftstore-v2/src/operation/ready/apply_trace.rs (hunk 6 above)
Comment (bufferflies) [reply components/raftstore-v2/src/operation/ready/apply_trace.rs]: ditto

File: components/raftstore-v2/src/operation/ready/apply_trace.rs (hunk 7 above)
Comment (bufferflies) [reply components/raftstore-v2/src/operation/ready/apply_trace.rs:526]: I afraid  the cost of `raft_engine.get_region_state()` is high.

File: components/raftstore-v2/src/operation/ready/apply_trace.rs (hunk 2 above)
Comment (bufferflies) [reply components/raftstore-v2/src/operation/ready/apply_trace.rs:573]: yesy, fixed it.

File: components/raftstore-v2/src/operation/ready/apply_trace.rs (hunk 8 above)
Comment (bufferflies) [reply components/raftstore-v2/src/operation/ready/apply_trace.rs:659]: yes, stale sst will delete after flush. I wiil remove it.

File: components/raftstore-v2/src/raft/storage.rs (hunk 4 above)
Comment (bufferflies) [reply components/raftstore-v2/src/raft/storage.rs:140]: good suggestion.

File: components/raftstore-v2/src/operation/ready/apply_trace.rs (hunk 7 above)
Comment (SpadeA-Tang) [reply components/raftstore-v2/src/operation/ready/apply_trace.rs:526]: I think it's fine. `get_region_state` is an in-memory operation and furthermore, `record_apply_trace` is rarely called.

File: components/raftstore-v2/src/raft/storage.rs [hunk 9]
```diff
@@ -183,6 +199,7 @@ impl<EK: KvEngine, ER: RaftEngine> Storage<EK, ER> {
             gen_snap_task: RefCell::new(Box::new(None)),
             split_init: None,
             apply_trace,
+            flushed_epoch: epoch,
```
Comment (3pointer) [inline components/raftstore-v2/src/raft/storage.rs:202]: It seems this epoch is the newly epoch and irrelevant with `flush`.
Will it delete the file before ingest replayed after restart?

Comment (bufferflies) [reply components/raftstore-v2/src/raft/storage.rs:202]: Q1: `epoch` refresh only if `trace.admin.index` has writed in the disk.
Q2: sst will be delete if the sst's epoch is stale than the `flush epoch`

**Review by SpadeA-Tang — APPROVED** [review]

File: components/raftstore-v2/src/operation/command/write/ingest.rs [hunk 10]
```diff
@@ -80,38 +80,27 @@ impl<EK: KvEngine, ER: RaftEngine> Peer<EK, ER> {
...
             return;
         }
-        let uuids = stale_ssts
-            .iter()
-            .map(|sst| sst.get_uuid().to_vec())
-            .collect();
-        self.sst_apply_state().delete_ssts(uuids);
+        info!(
+            self.logger,
+            "clean up import sst file by interval task";
```
Comment (overvenus) [inline components/raftstore-v2/src/operation/command/write/ingest.rs:93]:
```suggestion
            "clean up import sst file by CleanupImportSst task";
```

File: components/raftstore-v2/src/operation/ready/apply_trace.rs [hunk 11]
```diff
@@ -519,6 +522,17 @@ impl<EK: KvEngine, ER: RaftEngine> Storage<EK, ER> {
...
+        let epoch = raft_engine
+            .get_region_state(region_id, trace.admin.flushed)
+            .unwrap()
+            .unwrap()
+            .get_region()
+            .get_region_epoch()
+            .clone();
+        if util::is_epoch_stale(self.flushed_epoch(), &epoch) {
+            write_task.flushed_epoch = Some(epoch);
+        }
```
Comment (overvenus) [inline components/raftstore-v2/src/operation/ready/apply_trace.rs:534]: It may cause some IO, Maybe we could compare `self.region().get_region_epoch()`?

```suggestion
        if util::is_epoch_stale(self.flushed_epoch(), self.region().get_region_epoch()) {
            write_task.flushed_epoch = Some(self.region().get_region_epoch().clone());
        }
```

Comment (bufferflies) [reply components/raftstore-v2/src/operation/ready/apply_trace.rs:534]: all the region states are in memory.

**Review by overvenus — APPROVED** [review]
