### PR TITLE
config: Fix titan blob-run-mode setting

### LINKED ISSUE #15978: tikv-ctl modify titan config Invalid argument error
### What version of TiKV are you using?

TiKV
Release Version:   7.6.0-alpha
Edition:           Community
Git Commit Hash:   e0fe14d57136f645457bcf14ee5ae1a478be04b8
Git Commit Branch: heads/refs/tags/v7.6.0-alpha
UTC Build Time:    2023-11-03 11:51:51
Rust Version:      rustc 1.67.0-nightly (96ddd32c4 2022-11-14)
Enable Features:   pprof-fp jemalloc mem-profiling portable sse test-engine-kv-rocksdb test-engine-raft-raft-engine cloud-aws cloud-gcp cloud-azure
Profile:           dist_release
### Steps to reproduce

[root@tc-tikv-2 /]# /tikv-ctl --host [127.0.0.1:20160](http://127.0.0.1:20160/) modify-tikv-config -n rocksdb.defaultcf.titan.blob-run-mode -v fallback
DebugClient::modify_tikv_config: RpcFailure: 2-UNKNOWN "failed to update config, err: Other(\"[components/engine_rocks/src/[cf_options.rs:28](http://cf_options.rs:28/)]: Invalid argument: No blob_run_mode defined for fallback\")"

[root@tc-tikv-2 /]# /tikv-ctl --host [127.0.0.1:20160](http://127.0.0.1:20160/) modify-tikv-config -n rocksdb.defaultcf.titan.blob-run-mode -v read_only
DebugClient::modify_tikv_config: RpcFailure: 2-UNKNOWN "failed to update config, err: \"expect: normal, read-only or fallback, got: \\\"read_only\\\"\""

### LINKED ISSUE #15987: fail to update titan config by tikv-ctl or tikv status API
### What version of TiKV are you using?

master
### Steps to reproduce

./tikv-ctl --host tikv_ip:tikv_port modify-tikv-config -n rocksdb.defaultcf.titan.blob-run-mode -v fallback
### What did you expect?
success
### What did happened?
failed

DebugClient::modify_tikv_config: RpcFailure: 2-UNKNOWN "failed to update config, err: Other(\"[components/engine_rocks/src/[cf_options.rs:28](http://cf_options.rs:28/)]: Invalid argument: No blob_run_mode defined for fallback\")"

### PR DESCRIPTION
**Pull request by tonyxuqqi**
### What is changed and how it works?

Issue Number: Close #15987, Close #15978

What's Changed:

```commit-message
Fix titan config blob-run-mode's from<ConfigValue> implementation.  
```

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Manual test (add detailed scripts or steps below)

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by v01dstar** [comment]
Seems https://github.com/tikv/tikv/blob/6e826308b9ca246ee5572bcdd24e6b26fd19c156/src/config/mod.rs#L197 titan blob run mode is transformed directly from the struct instead of the "string"

**Comment by tonyxuqqi** [comment]
> Seems
> 
> https://github.com/tikv/tikv/blob/6e826308b9ca246ee5572bcdd24e6b26fd19c156/src/config/mod.rs#L197
> 
> titan blob run mode is transformed directly from the struct instead of the "string"

There're two paths to set the blob run mode. One is from the BlobRunMode, the other is from the string directly. 
Below code is from string directly, which is used by update_config in tikv's status API.
```
impl<T: ConfigurableDb + Send + Sync> ConfigManager for DbConfigManger<T> {
    fn dispatch(&mut self, change: ConfigChange) -> Result<(), Box<dyn Error>> {
....
    if !cf_change.is_empty() {
                    let cf_change = config_value_to_string(cf_change.into_iter().collect());
                    let cf_change_slice = config_to_slice(&cf_change);
                    self.set_cf_config(cf_name, &cf_change_slice)?;
                }
```

File: components/engine_rocks/src/config.rs [hunk 1]
```diff
@@ -366,8 +366,11 @@ impl FromStr for BlobRunMode {
             "normal" => Ok(BlobRunMode::Normal),
             "read-only" => Ok(BlobRunMode::ReadOnly),
             "fallback" => Ok(BlobRunMode::Fallback),
+            "kNormal" => Ok(BlobRunMode::Normal),
```
[the remark this answers is not in the document]
Comment (tonyxuqqi) [reply components/engine_rocks/src/config.rs:369]: > let's only support `normal/read-only/fallback`

In fact initial version only supports normal/read-only/fallback. However, I tested it did not work. Because there's some code path that requires the transition from  kNormal to BlobRunMode. It would complain kNormal is not supported even if in the cmdline, I used normal instead.  @Connor1996

File: components/engine_rocks/src/config.rs [hunk 2]
```diff
@@ -340,9 +340,9 @@ pub enum BlobRunMode {
 impl From<BlobRunMode> for ConfigValue {
     fn from(mode: BlobRunMode) -> ConfigValue {
         let str_value = match mode {
-            BlobRunMode::Normal => "normal",
-            BlobRunMode::ReadOnly => "read-only",
-            BlobRunMode::Fallback => "fallback",
+            BlobRunMode::Normal => "kNormal",
```
Comment (Connor1996) [inline components/engine_rocks/src/config.rs:343]: the output in the config toml would be `kNormal`?

Comment (v01dstar) [reply components/engine_rocks/src/config.rs:343]: I wonder if we ever export the config or just do import. If we do export, then this may be problematic.

Comment (tonyxuqqi) [reply components/engine_rocks/src/config.rs:343]: It's still normal/read-only/fallback (Verified) @v01dstar @Connor1996 
Because the export of config would use serde serialization/deserialization.

**Review by Connor1996 — APPROVED** [review]
LGTM

**Review by LykxSassinator — APPROVED** [review]
