### PR TITLE
external_storage: update to rusoto 0.34

### LINKED ISSUE #7096: TiKV BR S3 backend storage does not support IAM web identity
## Bug Report

Currently, TiKV uses [rusuto](https://github.com/rusoto/rusoto) https://github.com/tikv/tikv/blob/b4f1c014fb01bd19929cf4d9f28bfa8b7b6971eb/components/external_storage/Cargo.toml#L20
Rusoto 0.43.0-beta.1(2020-02-07) supports web identity provider, which enables IAM roles for Kubernetes service accounts. https://github.com/rusoto/rusoto/blob/e5c91ba1088ede54c194aee410c9720b9cfaa6ef/CHANGELOG.md#L34

In order to use BR on EKS, TiKV needs to update rusoto dependency to 0.43.0-beta-1 or later.

### PR DESCRIPTION
**Pull request by yiwu-arbug**
Signed-off-by: Yi Wu <yiwu@pingcap.com>

###  What have you changed?

update rusoto (aws lib) to 0.34, which provides IAM support. It changes a few API to use newer futures/tokio version. Update accordingly.

Fixes #7096 

###  What is the type of the changes?
Improvement, Engineering

###  How is the PR tested?
build

###  Does this PR affect documentation (docs) or should it be mentioned in the release notes?
No

###  Does this PR affect `tidb-ansible`?
No

### CODE REVIEW

File: components/tikv_util/src/file.rs [hunk 1]
```diff
@@ -109,7 +109,7 @@ impl<R> Sha256Reader<R> {
 
 impl<R: Read> Read for Sha256Reader<R> {
     fn read(&mut self, buf: &mut [u8]) -> io::Result<usize> {
-        let len = self.reader.read(buf)?;
+        let len = self.reader.lock().unwrap().read(buf)?;
```
Comment (BusyJay) [inline components/tikv_util/src/file.rs]: Why need to lock it? Isn't `self` is borrowed exclusively?

Comment (yiwu-arbug) [reply components/tikv_util/src/file.rs]: `ExternalStorage::write` now require `Sync` trait, which is because rusoto's `PutObjectRequest::body` require `Sync` trait. The `reader` here is a `DBSequentialFile`, which is not thread-safe.

Comment (yiwu-arbug) [reply components/tikv_util/src/file.rs]: are you suggesting `unsafe impl Sync for Sha256Reader`?

Comment (BusyJay) [reply components/tikv_util/src/file.rs]: I suggest to require `R` to be `Sync`, so that if reader is Sync already, it doesn't have to pay for the cost of mutex. By the way, why is `DBSequentialFile` not `Sync`?

Comment (yiwu-arbug) [reply components/tikv_util/src/file.rs]: rocksdb `SequentialFile` maintains some internal state and is not thread-safe, so marking it `Sync` is improper, from my understanding.

Comment (yiwu-arbug) [reply components/tikv_util/src/file.rs]: I changed to `get_mut` instead of `lock` to avoid actual locking, are you okay with it?

**Comment by yiwu-arbug** [comment]
> LGTM.
> 
> I've got some changes to remove the `Sync` requirements on the reader, but let's defer that refactoring later.

How do you remove the `Sync` requirement?

**Comment by kennytm** [comment]
@yiwu-arbug by reimplementing that `FramedRead`, where the replacement itself holds the Mutex.

<details>

(This was written before #6675 so some restriction (e.g. reusing the buffer) can be relaxed. The `try_lock()` should be replaced by `get_mut()`.)

```rust
/// Wrapper of an `AsyncRead` instance, exposed as a `Sync` `Stream` of `Bytes`.
pub struct AsyncReadAsSyncStreamOfBytes<R> {
    // we need this Mutex to ensure the type is Sync (provided R is Send).
    // this is because rocksdb::SequentialFile is *not* Sync
    // (according to the documentation it cannot be Sync either,
    // requiring "external synchronization".)
    reader: Mutex<R>,
    // we use this member to ensure every call to `poll_next()` reuse the same
    // buffer.
    buf: Vec<u8>,
}

impl<R> AsyncReadAsSyncStreamOfBytes<R> {
    pub fn with_capacity(reader: R, capacity: usize) -> Self {
        Self {
            reader: Mutex::new(reader),
            buf: vec![0; capacity],
        }
    }
}

impl<R: AsyncRead + Unpin> Stream for AsyncReadAsSyncStreamOfBytes<R> {
    type Item = io::Result<Bytes>;

    fn poll_next(self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Option<Self::Item>> {
        let this = self.get_mut();
        let mut reader = match this.reader.try_lock() {
            Ok(guard) => guard,
            Err(TryLockError::WouldBlock) => return Poll::Pending,
            Err(TryLockError::Poisoned(poison)) => panic!("cannot acquire lock: {}", poison),
        };

        let read_size = Pin::new(&mut *reader).poll_read(cx, &mut this.buf);
        drop(reader);

        match read_size {
            Poll::Pending => Poll::Pending,
            Poll::Ready(Err(e)) => Poll::Ready(Some(Err(e))),
            Poll::Ready(Ok(0)) => Poll::Ready(None),
            Poll::Ready(Ok(n)) => Poll::Ready(Some(Ok(Bytes::copy_from_slice(&this.buf[..n])))),
        }
    }
}
```

</details>

**Comment by yiwu-arbug** [comment]
> @yiwu-arbug by reimplementing that `FramedRead`, where the replacement itself holds the Mutex.
> 

I thought about it but hesitate to do so. It adds maintenance cost by having more code. I think requiring `Sync` is good for now.
