### PR TITLE
*: Update rustc to update time crate

### LINKED ISSUE #19355: Clippy failed due to RUSTSEC-2026-0009
### What version of TiKV are you using?

master
### Steps to reproduce

```
make clippy
```
### What did you expect?
No error reported
### What did happened?
Clippy failed due to https://rustsec.org/advisories/RUSTSEC-2026-0009

### PR DESCRIPTION
**Pull request by v01dstar**
### What is changed and how it works?

Issue Number: Close #19355

What's Changed:

```commit-message
Update time crate to fix RUSTSEC-2026-0009.
```

Updating time crate requires:

1.  Update rustc nightly version
  1.1. Requires removing let-chains usage unless edition is set to 2024, `feature(let_chains)` does not work
  1.2. It is more "readable" removing all `let_chains` rather than bump Rust edition to 2024, I recommend we upgrade Rust edition to 2024 separately, and upgrade each module individually. created https://github.com/tikv/tikv/issues/19368 for tracking
2. Update raft-engine serde version, see the comment  here https://github.com/tikv/tikv/issues/19355#issuecomment-3874163894
  2.1 The raft-engine PR is https://github.com/tikv/raft-engine/pull/390

### Can we separate this into multiple smaller PRs:
Yes and No. TiKV CI is failing, any PR requires fixing RUSTSEC, fixing RUSTSEC requires update nightly version, and here we are again...

### Files need attentions:
```
components/compact-log-backup/src/execute/mod.rs
components/raftstore/src/coprocessor/config.rs
components/raftstore/src/store/fsm/peer.rs
components/raftstore/src/store/worker/split_check.rs
components/tidb_query_datatype/src/codec/mysql/time/mod.rs
components/tidb_query_expr/src/impl_time.rs
src/config/mod.rs
src/storage/txn/actions/prewrite.rs
```

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [ ] Need to cherry-pick to the release branch

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note

```release-note
None
```

## Summary by CodeRabbit

* **Refactor**
  * Simplified conditional and branching logic across the codebase for clearer, more maintainable control flow.

* **Chores**
  * Removed reliance on an unstable Rust feature to improve compatibility with stable toolchains.
  * Updated the Rust toolchain to a newer nightly release.

### CODE REVIEW

**Comment by LykxSassinator** [comment]
Since `rustc 1.88.0 stable` has made [`let_chains` stablized](https://blog.rust-lang.org/2025/06/26/Rust-1.88.0/#let-chains), how about directly upgrading the rustc and remove `feature(let_chains)` ?

**Comment by v01dstar** [comment]
> Since `rustc 1.88.0 stable` has made [`let_chains` stablized](https://blog.rust-lang.org/2025/06/26/Rust-1.88.0/#let-chains), how about directly upgrading the rustc and remove `feature(let_chains)` ?

Rustc is already upgrade in this PR, and `feature(let_chains)`s are removed. The thing is that rustc 1.88+ not only stabilize `let_chain` but also disallow us using `let_chain` unless we set `edition = 2024`. We have to set `edition = 2024` if we want to use `let_chain`, however, like I mentioned in the PR description, it is a larger change doing that. 2024 edition has some styling changing over borrow/lifetime declaration, it is nearly impossible to review doing it all at once for TiKV project, that's why I recommended just deprecate `let_chain` to fix the CI, and then migrate the whole TiKV project to 2024 edition gradually later

File: components/raftstore-v2/src/batch/store.rs [hunk 1]
```diff
@@ -775,18 +775,20 @@ impl<EK: KvEngine, ER: RaftEngine> StoreSystem<EK, ER> {
...
-                            && let Some(t) = t.latest()
-                        {
-                            match t.flush_oldest_cf(true, Some(threshold)) {
-                                Err(e) => warn!(logger, "failed to flush oldest cf"; "err" => %e),
-                                Ok(true) => {
-                                    to_flush -= 1;
-                                    let time =
-                                        std::time::Instant::now() + limiter.consume_duration(1);
-                                    let _ = GLOBAL_TIMER_HANDLE.delay(time).compat().await;
+                        if let Some(mut t) = registry.get(r) {
```
Comment (glorv) [inline components/raftstore-v2/src/batch/store.rs:778]: I saw many other changes are "replacing nested if with let-chains", but why here it replaced the if-let-chains back to nested if blocks?

File: components/raftstore-v2/src/fsm/store.rs [hunk 2]
```diff
@@ -63,29 +63,29 @@ impl<EK> StoreMeta<EK> {
...
-                );
-            } else {
-                assert!(
-                    self.region_ranges
-                        .contains_key(&(data_end_key(prev.get_end_key()), version)),
-                    "{} region corrupted",
-                    SlogFormat(logger)
-                );
-                return;
+        if let Some((prev, prev_init)) = prev {
```
Comment (glorv) [inline components/raftstore-v2/src/fsm/store.rs:66]: ditto

File: components/raftstore-v2/src/operation/command/admin/merge/commit.rs [hunk 3]
```diff
@@ -343,20 +343,22 @@ impl<EK: KvEngine, ER: RaftEngine> Peer<EK, ER> {
...
-                "failed to propose commit merge";
-                "source" => source_id,
-                "res" => ?res,
-            );
-            fail::fail_point!(
-                "on_propose_commit_merge_fail_store_1",
-                store_ctx.store_id == 1,
-                |_| {}
-            );
+        if let Some(res) = res.take_result() {
```
Comment (glorv) [inline components/raftstore-v2/src/operation/command/admin/merge/commit.rs:346]: ditto

File: rust-toolchain.toml [hunk 4]
```diff
@@ -1,5 +1,5 @@
 [toolchain]
 #WARN: Before upgrading to a new toolchain, please ensure https://github.com/rust-lang/rust/issues/141306 is fixed.
-channel = "nightly-2025-02-28"
+channel = "nightly-2026-01-30"
```
Comment (glorv) [inline rust-toolchain.toml:2]: You can also remove this WARN as the bug has already been fixed before this new version.

File: components/raftstore-v2/src/batch/store.rs (hunk 1 above)
Comment (v01dstar) [reply components/raftstore-v2/src/batch/store.rs:778]: It depends on whether we "can" set a specific module's edition to 2024 in its `Cargo.toml`. After upgrading Rust nightly, to use `let_chains`, we have to set edition to 2024, `feature(let_chains)` no longer work. I set some of the modules to use 2024 edition, if the module requires minimum changes. For some modules like `raftstore`, setting edition to 2024 also force us to do massive styling changes related to `borrow/lifetime`, thats why I created a separate issue to track this in this PR's description

**Review by glorv — APPROVED** [review]

**Comment by you06** [comment]
There is the same clippy failure in release-8.5 branch. Shall we pick this PR to 8.5 or just ignore the "RUSTSEC-2026-0009" in release-8.5's `deny.toml`?
