### PR TITLE
raftstore: ignore error when sending messages

### LINKED ISSUE #4717: Sending messages should be more tolerant
https://github.com/tikv/tikv/blob/69680545b2721810581cdedeb5c4a975ddc4dc2b/src/raftstore/store/peer.rs#L2046-L2055

If returns error early, all the following messages will be discard and other peers may not receive logs until next heartbeat, which can cause unexpected delay.

In my opinion, sending message may not report error at all, because there will be no special handing except logging.

### PR DESCRIPTION
**Pull request by BusyJay**
## What have you changed? (mandatory)

Fix #4717, I'm still trying to write a test case to reproduce it reliably.

## What are the type of the changes? (mandatory)

- Bug fix (change which fixes an issue)

## How has this PR been tested? (mandatory)

manual tests

## Does this PR affect documentation (docs) or release note? (mandatory)

No.

## Does this PR affect tidb-ansible update? (mandatory)

No.

## Refer to a related PR or issue link (optional)

#4717

### CODE REVIEW

**Comment by siddontang** [comment]
@zhangjinpeng1987 

have you ensured using this can avoid 1s latency jitter now?

File: src/binutil/setup.rs [hunk 1]
```diff
@@ -31,10 +32,27 @@ pub fn initial_logger(config: &TiKvConfig) {
     let log_rotation_timespan =
         chrono::Duration::from_std(config.log_rotation_timespan.clone().into())
             .expect("config.log_rotation_timespan is an invalid duration.");
+
+    // Collects following targets.
+    const ENABLED_TARGETS: &[&str] = &[
```
Comment (siddontang) [inline src/binutil/setup.rs]: oh, seem now we have not filtered any message, right? @BusyJay

Comment (BusyJay) [reply src/binutil/setup.rs]: Yes. And it's expected not to filter any messages. Here is just for debug purpose, will remove later.

File: src/raftstore/store/peer.rs [hunk 2]
```diff
@@ -838,6 +837,15 @@ impl Peer {
                         "peer_id" => self.peer.get_id(),
                         "lease" => ?self.leader_lease,
                     );
+                    // If predecessor read index during transferring leader and received quorum's
```
Comment (siddontang) [inline src/raftstore/store/peer.rs]: PTAL @dcalvin

File: src/raftstore/store/peer.rs [hunk 3]
```diff
@@ -911,6 +910,15 @@ impl Peer {
...
+                    // heartbeat response, it may waiting for advancing apply to current term to
```
Comment (siddontang) [inline src/raftstore/store/peer.rs]: it may wait

File: src/raftstore/store/peer.rs [hunk 4]
```diff
@@ -911,6 +910,15 @@ impl Peer {
...
+                    // apply the read. So broadcast eargerly to avoid unexpected latency.
+                    //
+                    // TODO: Maybe the predecessor should just drop all the read requests directly?
+                    // All the requests need to be redirected in the end anyway and executing
+                    // prewrites or commits will be just a waste.
+                    self.last_urgent_proposal_idx = self.raft_group.raft.raft_log.last_index();
```
Comment (siddontang) [inline src/raftstore/store/peer.rs]: any test to cover it?

File: src/raftstore/store/peer.rs (hunk 2 above)
Comment (dcalvin) [reply src/raftstore/store/peer.rs]:
```suggestion
                    // If the predecessor read index receives quorum's heart response during
```

File: src/raftstore/store/peer.rs (hunk 3 above)
Comment (dcalvin) [reply src/raftstore/store/peer.rs]: > waiting for advancing apply to current term to apply the read.
What does "advancing apply to current term" mean?  @BusyJay

**Comment by BusyJay** [comment]
PTAL

File: components/test_raftstore/src/transport_simulate.rs [hunk 5]
```diff
@@ -527,6 +527,50 @@ impl Filter for DropSnapshotFilter {
...
+impl Filter for LeadingFilter {
+    fn before(&self, msgs: &mut Vec<RaftMessage>) -> Result<()> {
+        let mut filtered_msg = self.first_filtered_msg.lock().unwrap();
+        let mut to_send = vec![];
+        for msg in msgs.drain(..) {
+            if msg.get_message().get_msg_type() == self.filter_type {
+                if filtered_msg.is_none() {
+                    *filtered_msg = Some(msg);
+                }
+            } else if msg.get_message().get_msg_type() == self.flush_type {
```
Comment (hicqu) [inline components/test_raftstore/src/transport_simulate.rs]: Doesn't not need to `break` here?

File: src/raftstore/store/peer.rs [hunk 6]
```diff
@@ -2123,6 +2107,10 @@ impl Peer {
     }
 
     pub fn get_peer_from_cache(&self, peer_id: u64) -> Option<metapb::Peer> {
+        if peer_id == 0 {
```
Comment (hicqu) [inline src/raftstore/store/peer.rs]: Why add it?

File: components/test_raftstore/src/transport_simulate.rs (hunk 5 above)
Comment (BusyJay) [reply components/test_raftstore/src/transport_simulate.rs]: Following messages may still apply the rules, it may not be appropriate to break as a general filter.

File: src/raftstore/store/peer.rs (hunk 6 above)
Comment (BusyJay) [reply src/raftstore/store/peer.rs]: When there is no leader, `peer_id` may be 0 as it represents leader id. Add a check to skip slow path.

**Comment by hicqu** [comment]
LGTM.
