### PR TITLE
raftstore: enhance split check

### LINKED ISSUE #15863: A 12GB region is not splitted automatically, cause TiSpark's failure due to too large coproc response.
### What version of TiKV are you using?

v6.5

### Steps to reproduce

Import many SST files to a region to make it larger than region-max-size.
### What did you expect?
The region can be split correctly
### What did happened?
The region is not split. 

Logs:
tikv-2023-10-21T04-19-59.819.log:{"level":"INFO","caller":"peer.rs:5773","message":"on split","time":"2023/10/21 04:06:55.797 +00:00","source":"split checker","split_keys":"10 keys range from ? to ?","peer_id":69583985,"region_id":69583975}
tikv-2023-10-21T04-19-59.819.log:{"level":"INFO","caller":"pd.rs:1098","message":"try to batch split region","time":"2023/10/21 04:06:55.798 +00:00","task":"batch_split","region":"id: 69583975 start_key: ? end_key: ? region_epoch { conf_ver: 302 version: 5278 } peers { id: 69583977 store_id: 29 } peers { id: 69583979 store_id: 68611552 } peers { id: 69583985 store_id: 36 } peers { id: 69583986 store_id: 12007 role: Learner }","new_region_ids":"[new_region_id: 77356595 new_peer_ids: 77356596 new_peer_ids: 77356597 new_peer_ids: 77356598 new_peer_ids: 77356599, new_region_id: 77356600 new_peer_ids: 77356601 new_peer_ids: 77356602 new_peer_ids: 77356603 new_peer_ids: 77356604, new_region_id: 77356605 new_peer_ids: 77356606 new_peer_ids: 77356607 new_peer_ids: 77356608 new_peer_ids: 77356609, new_region_id: 77356610 new_peer_ids: 77356611 new_peer_ids: 77356612 new_peer_ids: 77356613 new_peer_ids: 77356614, new_region_id: 77356615 new_peer_ids: 77356616 new_peer_ids: 77356617 new_peer_ids: 77356618 new_peer_ids: 77356619, new_region_id: 77356620 new_peer_ids: 77356621 new_peer_ids: 77356622 new_peer_ids: 77356623 new_peer_ids: 77356624, new_region_id: 77356625 new_peer_ids: 77356626 new_peer_ids: 77356627 new_peer_ids: 77356628 new_peer_ids: 77356629, new_region_id: 77356630 new_peer_ids: 77356631 new_peer_ids: 77356632 new_peer_ids: 77356633 new_peer_ids: 77356634, new_region_id: 77356635 new_peer_ids: 77356636 new_peer_ids: 77356637 new_peer_ids: 77356638 new_peer_ids: 77356639, new_region_id: 77356640 new_peer_ids: 77356641 new_peer_ids: 77356642 new_peer_ids: 77356643 new_peer_ids: 77356644]","region_id":69583975}
tikv-2023-10-23T17-57-02.378.log:{"level":"INFO","caller":"peer.rs:4770","message":"propose conf change peer","time":"2023/10/21 04:34:35.597 +00:00","kind":"Simple","changes":"[change_type: AddLearnerNode peer { id: 77887276 store_id: 27 role: Learner }]","peer_id":69583985,"region_id":69583975}

As we can see the split check runs, but some how the batch split does not go through, probably because propose failure for some reason.  Right now we don't log the propose failure so the exact reason of propose failure is unknown, but generally propose failure is normal scenario. 
What's not normal in this case is that the split check should run again later to make sure the region get splitted.

### PR DESCRIPTION
**Pull request by tonyxuqqi**
### What is changed and how it works?

Issue Number: Close #15863

What's Changed:

```
When split check task is sure that the region should be split, it notifies Raftstore's peer so that split check tick will keep running until the region is split. 
```

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)

Side effects

- None

### Release note 

```release-note
Enhance the split check to eliminate these large regions because of temporarily failure on split.  
```

### CODE REVIEW

File: components/raftstore/src/store/fsm/peer.rs [hunk 1]
```diff
@@ -5974,15 +5998,41 @@ where
...
 
-    fn on_approximate_region_keys(&mut self, keys: u64) {
-        self.fsm.peer.approximate_keys = Some(keys);
+    fn on_approximate_region_keys(&mut self, keys: Option<u64>, may_split: Option<bool>) {
+        // if keys is none, it means no estimated keys
+        if keys.is_some() {
+            self.fsm.peer.approximate_keys = keys;
+        }
+
+        if may_split.is_some() {
```
Comment (Connor1996) [inline components/raftstore/src/store/fsm/peer.rs:6027]: write in `if let` clause with below?

File: components/raftstore/src/store/fsm/peer.rs [hunk 2]
```diff
@@ -5897,8 +5915,14 @@ where
         }
         self.fsm.peer.size_diff_hint = 0;
```
Comment (Connor1996) [inline components/raftstore/src/store/fsm/peer.rs:5916]: If we do not reset it here, seems the split check would simply retry to avoid the split propose is failed for some reason?

File: components/raftstore/src/store/worker/split_check.rs [hunk 3]
```diff
@@ -748,6 +762,7 @@ impl<EK: KvEngine, S: StoreHandle> Runner<EK, S> {
             let mut skip_on_kv = false;
             while let Some(e) = iter.next() {
                 if skip_on_kv && skip_check_bucket {
+                    split_keys = host.split_keys();
```
Comment (LykxSassinator) [inline components/raftstore/src/store/worker/split_check.rs:765]:
```suggestion
```
Redundant.

File: components/raftstore/src/store/fsm/peer.rs [hunk 4]
```diff
@@ -5897,8 +5915,14 @@ where
...
         self.fsm.peer.compaction_declined_bytes = 0;
-        // the task is scheduled, next tick may skip it.
-        self.fsm.peer.may_skip_split_check = true;
+        // the task is scheduled, next tick may skip it only when the size and keys are
+        // small If either size or keys are big enough to do a split,
+        // keep split check tick until split is done
+        if !matches!(self.fsm.peer.may_split_size, Some(true))
+            && !matches!(self.fsm.peer.may_split_keys, Some(true))
+        {
+            self.fsm.peer.may_skip_split_check = true;
```
Comment (Connor1996) [inline components/raftstore/src/store/fsm/peer.rs:5924]: `may_skip_split_check` complicates the mechanism which looks quite confusing

File: components/raftstore/src/store/peer.rs [hunk 5]
```diff
@@ -670,8 +670,10 @@ where
     pub compaction_declined_bytes: u64,
     /// Approximate size of the region.
     pub approximate_size: Option<u64>,
+    pub may_split_size: Option<bool>,
```
Comment (LykxSassinator) [inline components/raftstore/src/store/peer.rs:673]: FYI, maybe we can combine the `may_split_size` and `may_split_keys` into one object, naming as `maybe_splittable` to represent the given `Peer` maybe splittable by size or keys?
```Rust
/// Mark this region maybe splittable in previous check.
pub maybe_splittable: Option<bool>,
```

File: components/raftstore/src/store/fsm/peer.rs [hunk 6]
```diff
@@ -5897,8 +5915,14 @@ where
         }
         self.fsm.peer.size_diff_hint = 0;
         self.fsm.peer.compaction_declined_bytes = 0;
-        // the task is scheduled, next tick may skip it.
-        self.fsm.peer.may_skip_split_check = true;
+        // the task is scheduled, next tick may skip it only when the size and keys are
+        // small If either size or keys are big enough to do a split,
+        // keep split check tick until split is done
+        if !matches!(self.fsm.peer.may_split_size, Some(true))
+            && !matches!(self.fsm.peer.may_split_keys, Some(true))
```
Comment (LykxSassinator) [inline components/raftstore/src/store/fsm/peer.rs:5922]: How about
```suggestion
        if !matches!(self.fsm.peer.maybe_splittable, Some(true))
```

File: components/raftstore/src/store/fsm/peer.rs [hunk 7]
```diff
@@ -5974,15 +5998,41 @@ where
         }
     }
 
-    fn on_approximate_region_size(&mut self, size: u64) {
-        self.fsm.peer.approximate_size = Some(size);
+    fn on_approximate_region_size(&mut self, size: Option<u64>, may_split: Option<bool>) {
```
Comment (LykxSassinator) [inline components/raftstore/src/store/fsm/peer.rs:6001]:
```suggestion
    fn on_approximate_region_size(&mut self, size: Option<u64>, splittable: Option<bool>) {
```

File: components/raftstore/src/store/worker/split_check.rs [hunk 8]
```diff
@@ -810,6 +825,8 @@ impl<EK: KvEngine, S: StoreHandle> Runner<EK, S> {
                 }
             }
 
+            split_keys = host.split_keys();
```
Comment (LykxSassinator) [inline components/raftstore/src/store/worker/split_check.rs:828]:
```suggestion
            let maybe_splittable = !host.split_keys().is_empty();
```

File: components/raftstore/src/store/worker/split_check.rs [hunk 9]
```diff
@@ -823,8 +840,17 @@ impl<EK: KvEngine, S: StoreHandle> Runner<EK, S> {
                 "bucket_count" => buckets.len(),
                 "bucket_size" => bucket_size,
             );
-            self.router.update_approximate_size(region.get_id(), size);
-            self.router.update_approximate_keys(region.get_id(), keys);
+
+            self.router.update_approximate_size(
+                region.get_id(),
+                Some(size),
+                Some(!split_keys.is_empty()),
```
Comment (LykxSassinator) [inline components/raftstore/src/store/worker/split_check.rs:847]:
```suggestion
                Some(maybe_splittable),
```

File: components/raftstore/src/store/worker/split_check.rs [hunk 10]
```diff
@@ -823,8 +840,17 @@ impl<EK: KvEngine, S: StoreHandle> Runner<EK, S> {
...
+            );
+            self.router.update_approximate_keys(
+                region.get_id(),
+                Some(keys),
+                Some(!split_keys.is_empty()),
```
Comment (LykxSassinator) [inline components/raftstore/src/store/worker/split_check.rs:852]: ditto.

File: components/tikv_util/src/log.rs [hunk 11]
```diff
@@ -83,6 +83,18 @@ macro_rules! trace(($($args:tt)+) => {
     ::slog_global::trace!($($args)+)
 };);
 
+/// Logs a infor or debug level message using the slog global logger.
```
Comment (LykxSassinator) [inline components/tikv_util/src/log.rs:86]:
```suggestion
/// Logging an info or debug level message using the slog global logger.
```

File: components/raftstore/src/store/fsm/peer.rs [hunk 12]
```diff
@@ -5897,8 +5915,14 @@ where
         }
         self.fsm.peer.size_diff_hint = 0;
         self.fsm.peer.compaction_declined_bytes = 0;
-        // the task is scheduled, next tick may skip it.
-        self.fsm.peer.may_skip_split_check = true;
+        // the task is scheduled, next tick may skip it only when the size and keys are
+        // small If either size or keys are big enough to do a split,
+        // keep split check tick until split is done
```
Comment (LykxSassinator) [inline components/raftstore/src/store/fsm/peer.rs:5920]:
```suggestion
        // The task is scheduled, the next tick may skip it only when the size and keys are
        // small. If either size or keys are big enough to do a split,
        // keep split check tick until split is done
```

File: components/raftstore/src/store/fsm/peer.rs [hunk 13]
```diff
@@ -5974,15 +5998,41 @@ where
         }
     }
 
-    fn on_approximate_region_size(&mut self, size: u64) {
-        self.fsm.peer.approximate_size = Some(size);
+    fn on_approximate_region_size(&mut self, size: Option<u64>, may_split: Option<bool>) {
+        // if size is none, it means no estimated size
```
Comment (LykxSassinator) [inline components/raftstore/src/store/fsm/peer.rs:6002]:
```suggestion
        // If size is none, it means no estimated size
```

File: components/raftstore/src/store/fsm/peer.rs [hunk 14]
```diff
@@ -5974,15 +5998,41 @@ where
...
+        if size.is_some() {
+            self.fsm.peer.approximate_size = size;
+        }
+
+        if may_split.is_some() {
+            self.fsm.peer.may_split_size = may_split;
+        }
+
+        // if the region is truely splittable,
```
Comment (LykxSassinator) [inline components/raftstore/src/store/fsm/peer.rs:6011]: ditto

File: components/raftstore/src/store/fsm/peer.rs [hunk 15]
```diff
@@ -5974,15 +5998,41 @@ where
...
+        }
         self.register_split_region_check_tick();
         self.register_pd_heartbeat_tick();
         fail_point!("on_approximate_region_size");
     }
 
-    fn on_approximate_region_keys(&mut self, keys: u64) {
-        self.fsm.peer.approximate_keys = Some(keys);
+    fn on_approximate_region_keys(&mut self, keys: Option<u64>, may_split: Option<bool>) {
+        // if keys is none, it means no estimated keys
```
Comment (LykxSassinator) [inline components/raftstore/src/store/fsm/peer.rs:6022]: ditto

File: components/raftstore/src/store/fsm/peer.rs [hunk 16]
```diff
@@ -5974,15 +5998,41 @@ where
...
+        if keys.is_some() {
+            self.fsm.peer.approximate_keys = keys;
+        }
+
+        if may_split.is_some() {
+            self.fsm.peer.may_split_keys = may_split;
+        }
+
+        // if the region is truely splittable,
```
Comment (LykxSassinator) [inline components/raftstore/src/store/fsm/peer.rs:6031]: ditto.

File: components/raftstore/src/store/worker/split_check.rs [hunk 17]
```diff
@@ -695,6 +695,19 @@ impl<EK: KvEngine, S: StoreHandle> Runner<EK, S> {
         };
 
         if !split_keys.is_empty() {
+            // notify peer that if the region is truely splittable.
```
Comment (LykxSassinator) [inline components/raftstore/src/store/worker/split_check.rs:698]:
```suggestion
            // Notify peer that if the region is truly splittable.
```

File: components/raftstore/src/coprocessor/split_check/size.rs [hunk 18]
```diff
@@ -303,11 +319,25 @@ pub mod tests {
...
+                })
+                | Ok(SchedTask::UpdateApproximateKeys {
+                    region_id,
+                    may_split,
+                    ..
+                }) => {
+                    assert_eq!(region_id, exp_region.get_id());
+                    if let Some(may_split) = may_split {
+                        split = split || may_split;
+                    }
```
Comment (LykxSassinator) [inline components/raftstore/src/coprocessor/split_check/size.rs:338]:
```suggestion
                    split = split || may_split.unwrap_or(false);
```

File: components/raftstore/src/coprocessor/split_check/size.rs [hunk 19]
```diff
@@ -265,11 +266,25 @@ pub mod tests {
...
+                })
+                | Ok(SchedTask::UpdateApproximateSize {
+                    region_id,
+                    may_split,
+                    ..
+                }) => {
+                    assert_eq!(region_id, exp_region.get_id());
+                    if let Some(may_split) = may_split {
+                        split = may_split || split;
+                    }
```
Comment (LykxSassinator) [inline components/raftstore/src/coprocessor/split_check/size.rs:285]:
```suggestion
                    split = split || may_split.unwrap_or(false);
```

File: components/raftstore/src/store/fsm/peer.rs (hunk 4 above)
Comment (tonyxuqqi) [reply components/raftstore/src/store/fsm/peer.rs:5924]: It's necessary, otherwise too much cost on split check task.

File: components/raftstore/src/store/worker/split_check.rs (hunk 8 above)
Comment (tonyxuqqi) [reply components/raftstore/src/store/worker/split_check.rs:828]: host.split_keys() is not reentrant (only called once)

File: components/raftstore/src/store/fsm/peer.rs (hunk 1 above)
Comment (tonyxuqqi) [reply components/raftstore/src/store/fsm/peer.rs:6027]: But with "if let",  it would then use "Some(may_split)" instead of may_split directly.

File: components/raftstore/src/store/fsm/peer.rs (hunk 2 above)
Comment (tonyxuqqi) [reply components/raftstore/src/store/fsm/peer.rs:5916]: Do you mean do not reset `compaction_declined_bytes` or `size_diff_hint`? 

Yes, if we keep them unreset, split check will re-run.  But we do need to reset them here otherwise if the split check says it's not splitable, there's no point to run the split-check again. And also these two variables do not cover the SST ingestion scenario as they might be all zero.  So we still need may_skip_split_check. 

Today we use three variables to trigger split check:
1) size_diff_hint: if the write/delete is big enough, trigger split check.
2) compaction_declined_bytes: after compaction is done, the enough diff size triggers split check to update the approximate size. 
3) may_skip_split_check:  trigger the split check after SST ingestion is done. 

I cannot think of anything that can simplify the code without impacting the correctness and efficiency.

Comment (tonyxuqqi) [reply components/raftstore/src/store/fsm/peer.rs:5916]: To prevent the unnecessary split check task run is critical, as it's very expensive.

File: components/raftstore/src/store/fsm/peer.rs (hunk 6 above)
Comment (tonyxuqqi) [reply components/raftstore/src/store/fsm/peer.rs:5922]: There's a problem with single maybe_splittable. Because what if keys checker says it's not splitable, but size check says it's splitable? The maybe_splittable could be incorrectly overwritten by either of the value (though today the caller use same splitable value, it's possible in the future it can be different).  So having two variables is more robust.

File: components/raftstore/src/store/peer.rs (hunk 5 above)
Comment (tonyxuqqi) [reply components/raftstore/src/store/peer.rs:673]: There's a problem with single maybe_splittable. Because what if keys checker says it's not splitable, but size check says it's splitable? The maybe_splittable could be incorrectly overwritten by either of the value (though today the caller use same splitable value, it's possible in the future it can be different). So having two variables is more robust.

File: components/tikv_util/src/log.rs (hunk 11 above)
Comment (tonyxuqqi) [reply components/tikv_util/src/log.rs:86]: It keeps consistent with other log functions

**Review by Connor1996 — COMMENTED** [review]
rest LGTM

**Review by LykxSassinator — APPROVED** [review]
Rest LGTM

**Review by Connor1996 — APPROVED** [review]
LGTM
