### PR TITLE
engine_rocks: introduce `force_partition_range` in compact guard

### LINKED ISSUE #18865: unexpect sst ingestion in l0 even if there is no overlapped data
### Steps to reproduce

We have met SST ingested not to the bottom level in different scenarios while the newly ingested SST files are not overlap with any existing data. In some cases, the sst files are ingested into l0 and cause flow-control; while in other cases, the SST files are ingested to other file that triggers huge compaction and impact the tail latency.

The root cause is the compatition guard current only split SST file when its size exceed a certain threshold(see [compaction-guard-min-output-file-size](https://docs.pingcap.com/tidb/dev/tikv-configuration-file/#compaction-guard-min-output-file-size)), so it is possible that there is a existing sst file at the bottom level with a huge range that can block any incoming sst from being ingested into the bottom level.

### PR DESCRIPTION
**Pull request by glorv**
### What is changed and how it works?

Issue Number: Close #18865

What's Changed:

```commit-message
- introduce `force_partition_range` in compact guard to force partition specific range to ensure SST ingestion under this range can be ingested to the bottom level.
- Add 2 new API in SST service to manage the `force_partition_range`. The `add_force_partition_range` will also trigger a manual compaction to ensure existing SST will be partitioned.
```

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [ ] Need to cherry-pick to the release branch

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by Connor1996 — APPROVED** [review]
LGTM

File: components/raftstore/src/store/compaction_guard.rs [hunk 1]
```diff
@@ -228,6 +388,27 @@ impl<P: RegionInfoProvider> SstPartitioner for CompactionGuardGenerator<P> {
...
+                    } else {
+                        &[]
+                    };
+                    let next_pos = if self.pos > 0 && self.pos < self.boundaries.len() - 1 {
+                        self.boundaries[self.pos + 1].as_slice()
+                    } else {
+                        &[]
+                    };
+
+                    tikv_util::info!("sst partition due to force partition ranges";
```
Comment (v01dstar) [inline components/raftstore/src/store/compaction_guard.rs:411]: It seems that `self.current_next_level_size >= self.max_compaction_size` may also bring us here. I know it is just for logging, but do we need to distinguish it?

File: tests/integrations/import/test_sst_service.rs [hunk 2]
```diff
@@ -727,3 +727,57 @@ fn test_concurrent_ingest_admission_control() {
...
+    let (cluster, ctx, _tikv, import) = new_cluster_and_tikv_import_client();
+    let temp_dir = Builder::new()
+        .prefix("test_force_partition_range")
+        .tempdir()
+        .unwrap();
+    let sst_path = temp_dir.path().join("test.sst");
+
+    // ingest a sst with a big range
+    let (mut meta, data) =
+        gen_sst_file_with_tidb_kvs(sst_path.clone(), &[(b"a", b"a"), (b"z", b"z")], None);
```
Comment (v01dstar) [inline tests/integrations/import/test_sst_service.rs:758]: Insteading of ingest a generated SST, how about writing to TiKV with txn APIs. Because there is a key encoding logic in `add_force_partition_range`

Comment (glorv) [reply tests/integrations/import/test_sst_service.rs:758]: Yes, this is a tricky workaround, because we need to write a large amount of data to let rocksdb trigger flush and generate sst files. So I just let `gen_sst_file_with_tidb_kvs ` generate the rocksdb format data kv, there should be no difference.

File: components/raftstore/src/store/compaction_guard.rs [hunk 3]
```diff
@@ -19,11 +24,140 @@ lazy_static! {
...
+    pub fn iter_all_ranges(&self, mut func: impl FnMut(&[u8], &[u8], u64)) {
+        let now = Instant::now_coarse();
+        let mut need_clean = false;
+        self.force_partition_ranges
+            .read()
+            .unwrap()
+            .iter()
+            .for_each(|r| {
+                let ttl = r.ttl.saturating_duration_since(now);
+                if ttl == Duration::ZERO {
```
Comment (hbisheng) [inline components/raftstore/src/store/compaction_guard.rs]: nit: use a consistent style for time comparison
```suggestion
                let expired = r.ttl < now;
                if expired {
```

File: components/raftstore/src/store/compaction_guard.rs [hunk 4]
```diff
@@ -19,11 +24,140 @@ lazy_static! {
     static ref COMPACTION_GUARD: CString = CString::new(b"CompactionGuard".to_vec()).unwrap();
 }
 
+#[derive(Eq, PartialEq, PartialOrd, Clone)]
+// `Instant` does not implement the "Ord" trait.
+#[allow(clippy::derive_ord_xor_partial_ord)]
+struct TtlRange {
+    start: Vec<u8>,
+    end: Vec<u8>,
+    ttl: Instant,
```
Comment (hbisheng) [inline components/raftstore/src/store/compaction_guard.rs]: nit: TTL usually means a duration rather than a time point. `expires_at` is probably better.
```suggestion
    expires_at: Instant,
```

**Review by hbisheng — COMMENTED** [review]
LGTM

File: components/raftstore/src/store/compaction_guard.rs (hunk 1 above)
Comment (glorv) [reply components/raftstore/src/store/compaction_guard.rs:411]: fixed

**Comment by glorv** [comment]
@zhangjinpeng87 PTAL

**Review by zhangjinpeng87 — APPROVED** [review]
LGTM
