### PR TITLE
duration: keep duration parser compatible with tidb

### LINKED ISSUE #12932: cast string as time behaviour is incompatible with TiDB
### What version of TiKV are you using?

TiKV 
Release Version:   6.2.0-alpha
Edition:           Community
Git Commit Hash:   6bd1d4510652279e4d260317b628aafa6c5fbd27
Git Commit Branch: heads/refs/tags/v6.2.0-alpha
UTC Build Time:    2022-06-28 14:26:53
Rust Version:      rustc 1.62.0-nightly (7c4b47696 2022-04-30)
Enable Features:   pprof-fp jemalloc sse test-engine-kv-rocksdb test-engine-raft-raft-engine cloud-aws cloud-gcp cloud-azure
Profile:           dist_release

### Steps to reproduce

TiDB changes its cast string as time behaviour to fix this issue:
https://github.com/pingcap/tidb/issues/34539
However, TiKV seems not, which will cause copr-test failure.
You can reproduce this issue for running [copr-test](https://github.com/tikv/copr-test)
```
16:49:57  2022/06/28 16:49:38 Test fail: Outputs are not matching.
16:49:57  Test case: sql/randgen-topn/4_cast_1.sql
16:49:57  Statement: #454 -  SELECT BINARY NULL AS field1, CONVERT( ( CONVERT( `col_datetime_key` USING latin1 ) ), CHAR(7) ) AS field2, CONVERT( `col_float_unsigned_key`, DECIMAL(0,0) ) AS field3 FROM `table20_int_autoinc` WHERE CAST( ( CONVERT( ( CONVERT( `col_decimal_unsigned_key`, BINARY(7) ) ), BINARY ) ) AS TIME ) ORDER BY field1, field2, field3 LIMIT 8 /* QNO 459 CON_ID 104 */ ;
16:49:57  NoPushDown Output: 
16:49:57  field1	field2	field3
16:49:57  NULL	0000-00	NULL
16:49:57  NULL	0000-00	NULL
16:49:57  NULL	2008-10	NULL
16:49:57  
16:49:57  
16:49:57  WithPushDown Output: 
16:49:57  field1	field2	field3
16:49:57  
16:49:57  
16:49:57  
```
### What did you expect?
copr-test randgen-topn/4_cast_1.sql would pass

### What did happened?
copr-test randgen-topn/4_cast_1.sql failed

### PR DESCRIPTION
**Pull request by Willendless**
### What is changed and how it works?

Issue Number: Close #12932 

What's Changed:

1. add `format_can_match_datetime` to check whether an input string can potentially be parsed using datetime format, this function is similar to [`tidb::types::format_can_match_datetime`](https://github.com/pingcap/tidb/blob/a33d971adde7e5750cbddb2db2664b3389b0ab69/types/time.go#L1748)
2. allow duration parser partially parse input string using `hhmmss_compact` when origin input string len is less than 12 and (`fallback_to_datetime` is false or `format_can_match_datetime` check fails)
3. modify origin duration test to match modification results
4. add unit tests for trivial and boundary cases, some of them are as follows
    - `0000-00-00` from origin tidb issue
    -  `20100-02-12`
    - `99999-99-99`
    - `1-----`
    - consider overflow test: `99990000`

### Related changes

- PR from tidb side: [#35455](https://github.com/pingcap/tidb/pull/35455)

### Check List 

Tests 

- Unit test

Side effects

- Breaking backward compatibility

### Release note 

```release-note
None
```

### CODE REVIEW

File: components/tidb_query_datatype/src/codec/mysql/duration.rs [hunk 1]
```diff
@@ -204,20 +204,46 @@ mod parser {
         Ok((rest, frac * TEN_POW[NANO_WIDTH.saturating_sub(len)]))
     }
 
+    /// a string can match datetime format only if it starts with a series of digits
+    /// whose length matches the full format of DateTime literal (12, 14)
+    /// or the string start with a date literal
+    fn format_can_match_datetime(input: &str) -> IResult<(), (), ()> {
```
Comment (gengliqi) [inline components/tidb_query_datatype/src/codec/mysql/duration.rs:210]: Seems this function does the exact same logic judgment as `hhmmss_datetime`. Is it really necessary?

Comment (Willendless) [reply components/tidb_query_datatype/src/codec/mysql/duration.rs:210]: This function serves as an exact counterpart of [tidb::types::format_can_match_datetime](https://github.com/pingcap/tidb/blob/a33d971adde7e5750cbddb2db2664b3389b0ab69/types/time.go#L1748). And if we use hhmmss_datetime instead to check if the string matches the datetime format, there might be some other cases that will fail the check.

File: components/tidb_query_datatype/src/codec/mysql/duration.rs [hunk 2]
```diff
@@ -204,20 +204,46 @@ mod parser {
...
     ) -> Option<Duration> {
         let input = input.trim();
         if input.is_empty() {
-            return Some(Duration::zero());
+            return None;
         }
 
         let (rest, neg) = negative(input).ok()?;
         let (rest, _) = space0::<_, ()>(rest).ok()?;
+        let fallback_to_datetime = format_can_match_datetime(rest).is_ok() && fallback_to_datetime;
```
[the remark this answers is not in the document]
Comment (Willendless) [reply components/tidb_query_datatype/src/codec/mysql/duration.rs:243]: sure, I will use a new variable instead to represent the return value of `format_can_match_datetime ` in order to avoid introducing `mut` modifier for the argument.

[the remark this answers is not in the document]
Comment (gengliqi) [reply components/tidb_query_datatype/src/codec/mysql/duration.rs]: If `fallback_to_datetime` is false, it's a waste to run `format_can_match_datetime`. 
What's the disadvantage to add a `mut` for `fallback_to_datetime`?

[the remark this answers is not in the document]
Comment (Willendless) [reply components/tidb_query_datatype/src/codec/mysql/duration.rs]: I think bitwise & for boolean is not short-circuit operator.

File: components/tidb_query_datatype/src/codec/mysql/duration.rs (hunk 1 above)
Comment (Willendless) [reply components/tidb_query_datatype/src/codec/mysql/duration.rs:210]: Got it.

File: components/tidb_query_datatype/src/codec/mysql/duration.rs (hunk 2 above)
[the remark this answers is not in the document]
Comment (gengliqi) [reply components/tidb_query_datatype/src/codec/mysql/duration.rs]: Indeed. So it should be `let fallback_to_datetime = fallback_to_datetime && format_can_match_datetime(rest).is_ok();`.

[the remark this answers is not in the document]
Comment (Willendless) [reply components/tidb_query_datatype/src/codec/mysql/duration.rs]: fine

**Review by gengliqi — APPROVED** [review]
LGTM. Small comment issues.

File: components/tidb_query_datatype/src/codec/mysql/duration.rs [hunk 3]
```diff
@@ -230,16 +242,27 @@ mod parser {
...
+                    }
+                    truncated_parse = true;
                 }
 
                 Some(Duration::new_from_parts(
                     neg, hhmmss[0], hhmmss[1], hhmmss[2], frac, fsp as i8,
                 ))
             });
 
+        // In order to keep compatible with TiDB, when input string can only be partially parsed by hhmmss_compact
```
Comment (gengliqi) [inline components/tidb_query_datatype/src/codec/mysql/duration.rs:256]:
```suggestion
        // In order to keep compatible with TiDB, when input string can only be partially parsed by `hhmmss_compact`
```

File: components/tidb_query_datatype/src/codec/mysql/duration.rs [hunk 4]
```diff
@@ -150,28 +150,35 @@ mod parser {
...
-            return Err(nom::Err::Error(()));
+        if matches!(rest.chars().next(), Some(c) if c == 'T' || c == ' ') {
+            Ok(((), ()))
+        } else {
+            Err(nom::Err::Error(()))
         }
+    }
 
+    /// Caller should make sure the input string can match datetime format
+    /// according to format_can_match_datetime.
```
Comment (gengliqi) [inline components/tidb_query_datatype/src/codec/mysql/duration.rs:176]:
```suggestion
    /// according to `format_can_match_datetime`.
```

File: components/tidb_query_datatype/src/codec/mysql/duration.rs [hunk 5]
```diff
@@ -230,16 +242,27 @@ mod parser {
...
+        // and it can match the datetime format, we fallback to parse it using datetime format.
+        if truncated_parse && fallback_to_datetime {
+            return hhmmss_datetime(ctx, rest, fsp).map_or(None, |(_, duration)| Some(duration));
+        }
+
         match duration {
-            Some(Ok(duration)) => Some(duration),
+            Some(Ok(duration)) => ctx
+                .handle_truncate(truncated_parse)
+                .map_or(Some(duration), |_| Some(duration)),
```
Comment (gengliqi) [inline components/tidb_query_datatype/src/codec/mysql/duration.rs:265]: A little bit strange. How about
```suggestion
            Some(Ok(duration)) => {
                ctx.handle_truncate(truncated_parse);
                Some(duration)
            }
```

**Review by gengliqi — COMMENTED** [review]
Sorry, a few more comments.

File: components/tidb_query_datatype/src/codec/mysql/duration.rs (hunk 5 above)
Comment (Willendless) [reply components/tidb_query_datatype/src/codec/mysql/duration.rs:265]: This is what I wrote at first. Unfortunately, compiler doesn't like this and will complain by warning since the return value of handle_truncate is result and does not be handled.

```rust
warning: unused `std::result::Result` that must be used
   --> components/tidb_query_datatype/src/codec/mysql/duration.rs:264:17
    |
264 | /                 ctx
265 | |                 .handle_truncate(truncated_parse);
    | |__________________________________________________^
    |
    = note: `#[warn(unused_must_use)]` on by default
    = note: this `Result` may be an `Err` variant, which should be handled
```

**Comment by gengliqi** [comment]
LGTM

**Comment by gengliqi** [comment]
https://github.com/tikv/tikv/issues/13057 `test_stale_read_while_applying_snapshot` is a flaky test.

**Comment by Willendless** [comment]
> Seems this case is broken for certain:
> 
> ```
> 
> [2022-07-20T13:26:09.452Z] 2022/07/20 21:26:09 2022/07/20 21:25:55 Test fail: Outputs are not matching.
> 
> [2022-07-20T13:26:09.452Z] Test case: sql/randgen/10_agg.sql
> 
> [2022-07-20T13:26:09.452Z] Statement: #603 -  SELECT BIT_OR( `col_varbinary_32` * `col_timestamp_key` ) AS field1 FROM `table20_int_autoinc` WHERE `col_enum_key` GROUP BY `col_char_2` ORDER BY `col_char_2` /* QNO 610 CON_ID 1137 */ ;
> 
> [2022-07-20T13:26:09.452Z] NoPushDown Output: 
> 
> [2022-07-20T13:26:09.452Z] Error 1690: constant 1.4192255912751713e+22 overflows bigint
> 
> [2022-07-20T13:26:09.452Z] 
> 
> [2022-07-20T13:26:09.452Z] WithPushDown Output: 
> 
> [2022-07-20T13:26:09.452Z] field1
> 
> [2022-07-20T13:26:09.452Z] 0
> 
> [2022-07-20T13:26:09.452Z] 0
> 
> [2022-07-20T13:26:09.452Z] 0
> 
> [2022-07-20T13:26:09.452Z] 0
> 
> [2022-07-20T13:26:09.452Z] 0
> 
> [2022-07-20T13:26:09.452Z] 0
> 
> [2022-07-20T13:26:09.452Z] 0
> 
> [2022-07-20T13:26:09.452Z] 0
> 
> [2022-07-20T13:26:09.452Z] 0
> 
> [2022-07-20T13:26:09.452Z] 9223372036854775807
> 
> [2022-07-20T13:26:09.452Z] 0
> ```

Sure I am looking into it.

**Review by BornChanger — APPROVED** [review]
LGTM~

**Review by wshwsh12 — APPROVED** [review]

**Comment by solotzg** [comment]
add new issue #36400
