### PR TITLE
server: support tls for the status server

### LINKED ISSUE #5340: Metrics page not using HTTPS after TLS enabled
## Bug Report
When creating a TiDB cluster with TLS support enabled (on server side), the metrics page of TiKV still uses plain HTTP to serve connections, while TiDB and PD are using HTTPS, so Prometheus can't scrape metrics in an unique way.

### What version of TiKV are you using?

```
Release Version:   3.0.2
Git Commit Hash:   a65d10c6f5fb62d3aafcab6cfdcd5b36c2b33d35
Git Commit Branch: HEAD
UTC Build Time:    2019-08-07 02:31:51
Rust Version:      rustc 1.37.0-nightly (0e4a56b4b 2019-06-13)
```

### What operating system and CPU are you using?

Running in a Kubernetes cluster, but that doesn't matter.

### Steps to reproduce

Create a cluster with TLS enabled, and try to access each node's `/metrics` page.

TiDB:
```
# curl -Ik --cacert ./ca.crt --cert ./client.crt --key ./client.key https://10.233.48.147:10080/metrics
HTTP/1.1 200 OK
Content-Length: 244902
Content-Type: text/plain; version=0.0.4; charset=utf-8
Date: Tue, 27 Aug 2019 03:59:56 GMT
```

PD:
```
# curl -Ik --cacert ./ca.crt --cert ./client.crt --key ./client.key https://10.233.61.189:2379/metrics
HTTP/1.1 200 OK
Access-Control-Allow-Headers: accept, content-type, authorization
Access-Control-Allow-Methods: POST, GET, OPTIONS, PUT, DELETE
Access-Control-Allow-Origin: *
Content-Length: 252488
Content-Type: text/plain; version=0.0.4; charset=utf-8
Date: Tue, 27 Aug 2019 04:00:33 GMT
```

TiKV:
```
# curl -kv --cacert ./ca.crt --cert ./client.crt --key ./client.key https://10.233.77.255:20180/metrics
* About to connect() to 10.233.77.255 port 20180 (#0)
*   Trying 10.233.77.255...
* Connected to 10.233.77.255 (10.233.77.255) port 20180 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
* NSS error -12263 (SSL_ERROR_RX_RECORD_TOO_LONG)
* SSL received a record that exceeded the maximum permissible length.
* Closing connection 0
curl: (35) SSL received a record that exceeded the maximum permissible length.
```

TiKV with HTTP:
```
# curl -v http://10.233.77.255:20180/metrics
* About to connect() to 10.233.77.255 port 20180 (#0)
*   Trying 10.233.77.255...
* Connected to 10.233.77.255 (10.233.77.255) port 20180 (#0)
> GET /metrics HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 10.233.77.255:20180
> Accept: */*
> 
< HTTP/1.1 200 OK
< content-length: 291021
< date: Tue, 27 Aug 2019 04:06:42 GMT
< 
{ [data not shown]
# HELP process_cpu_seconds_total Total user and system CPU time spent in seconds.
# TYPE process_cpu_seconds_total counter
process_cpu_seconds_total 521.56
# HELP process_max_fds Maximum number of open file descriptors.
# TYPE process_max_fds gauge
process_max_fds 1048576
....
```

### What did you expect?
All requests are served as HTTPS when TLS is enabled, and client certificate should be validated, the same as TiDB/PD's behavior.

### What did happened?
TiKV doesn't use HTTPS for metrics page on TLS cluster.

### PR DESCRIPTION
**Pull request by rleungx**
###  What have you changed?

This PR is trying to support TLS by using rustls for the status server. 

###  What is the type of the changes?

- New feature 

###  How is the PR tested?

For now, it is temporarily tested manually. I will add some tests to cover it. 

###  Does this PR affect documentation (docs) or should it be mentioned in the release notes?

Yes

###  Does this PR affect `tidb-ansible`?

Yes

###  Refer to a related PR or issue link (optional)

Close #5340.

### CODE REVIEW

File: cmd/src/server.rs [hunk 1]
```diff
@@ -324,9 +324,13 @@ fn run_raft_server(pd_client: RpcClient, cfg: &TiKvConfig, security_mgr: Arc<Sec
     let mut status_server = StatusServer::new(server_cfg.status_thread_pool_size, cfg.clone());
     if status_enabled {
         // Start the status server.
-        if let Err(e) = status_server.start(server_cfg.status_addr) {
+        if let Err(e) = if cfg.security.cert_path.is_empty() && cfg.security.key_path.is_empty() {
```
Comment (Connor1996) [inline cmd/src/server.rs]: why not do this check in `status_server.start` directly?

File: src/server/status_server.rs [hunk 2]
```diff
@@ -210,43 +212,84 @@ impl StatusServer {
...
-                        let path = req.uri().path().to_owned();
-                        let method = req.method().to_owned();
-
-                        #[cfg(feature = "failpoints")]
-                        {
-                            if path.starts_with(FAIL_POINTS_REQUEST_PATH) {
-                                return handle_fail_points_request(req);
-                            }
-                        }
+            service_fn(move |req| Self::service(req, config.clone()))
```
Comment (Connor1996) [inline src/server/status_server.rs]: no need clone?

Comment (rleungx) [reply src/server/status_server.rs]: It doesn't implement Copy trait.

File: cmd/src/server.rs (hunk 1 above)
Comment (hicqu) [inline cmd/src/server.rs]: What if only one of `cert_path` or `key_path` is empty?

File: src/server/status_server.rs [hunk 3]
```diff
@@ -210,43 +212,84 @@ impl StatusServer {
...
-    pub fn start(&mut self, status_addr: String) -> Result<()> {
+    fn service(
+        req: Request<Body>,
+        config: Arc<TiKvConfig>,
+    ) -> Box<dyn Future<Item = Response<Body>, Error = hyper::Error> + Send> {
+        let path = req.uri().path().to_owned();
+        let method = req.method().to_owned();
+
+        #[cfg(feature = "failpoints")]
+        {
```
Comment (hicqu) [inline src/server/status_server.rs]: Is it possible to use `fail_point!` with the condition directly?

File: cmd/src/server.rs (hunk 1 above)
Comment (rleungx) [reply cmd/src/server.rs]: It cannot pass the configuration validation.

File: src/server/status_server.rs (hunk 2 above)
Comment (Connor1996) [reply src/server/status_server.rs]: already cloned it on Line 273

File: src/server/status_server.rs [hunk 4]
```diff
@@ -348,6 +391,33 @@ fn handle_fail_points_request(
     }
 }
 
+// Load public certificate from file.
+fn load_certs(filename: &str) -> io::Result<Vec<rustls::Certificate>> {
+    let certfile = fs::File::open(filename)
+        .map_err(|e| error(format!("failed to open {}: {}", filename, e)))?;
+    let mut reader = io::BufReader::new(certfile);
```
Comment (overvenus) [inline src/server/status_server.rs]: Why we need a buffered reader?

File: Cargo.toml [hunk 5]
```diff
@@ -110,6 +110,9 @@ vlog = "0.1.4"
 mime = "0.3.13"
 farmhash = "1.1.5"
 failure = "0.1"
+rustls = "0.16"
+tokio-rustls = "0.10"
```
Comment (overvenus) [inline Cargo.toml]: Why not use openssl, it helps compile time since it's already in the dependency tree.

```toml
openssl = "0.10"
tokio-openssl = "0.2"
```

**Comment by overvenus** [comment]
Any update?

File: src/server/status_server.rs [hunk 6]
```diff
@@ -210,43 +212,84 @@ impl StatusServer {
...
+            (Method::GET, "/pprof/profile") => Self::dump_prof_to_resp(req),
+            (Method::GET, "/config") => Self::config_handler(config),
+            _ => Box::new(ok(Response::builder()
+                .status(StatusCode::NOT_FOUND)
+                .body(Body::empty())
+                .unwrap())),
+        }
+    }
+
+    pub fn start_with_tls(&mut self, status_addr: String) -> Result<()> {
```
Comment (Hoverbear) [inline src/server/status_server.rs]: Why split this and the non-TLS?

**Comment by tennix** [comment]
@rleungx Any progress on this?
