### PR TITLE
backup: move verbose errors to warn level

### LINKED ISSUE #18493: br: reduce non-fatal error logs' level
## Development Task
There are some logs aren't actually `error` level (requires manual operation right now) but logged as error level. They can be reduced to `warn` level.

- `backup snapshot failed`
- `error during backup`
- `backup raw kv snapshot failed`
- `backup writer failed`
- `backup build sst failed`
- `backup scan entries failed`

### PR DESCRIPTION
**Pull request by YuJuncen**
### What is changed and how it works?

Issue Number: Close #18493 

What's Changed:

```commit-message
Some of non-fatal error level logs during backing up are now warn level.
```

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [ ] Need to cherry-pick to the release branch

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note

```release-note
Some of non-fatal error level logs during backing up are now warn level.
```

### CODE REVIEW

File: components/backup/src/endpoint.rs [hunk 1]
```diff
@@ -863,7 +863,6 @@ impl<R: RegionInfoProvider> Progress<R> {
             }),
         );
         if let Err(e) = res {
-            // TODO: handle error.
```
Comment (YuJuncen) [inline components/backup/src/endpoint.rs:866]: This was removed because BR client somehow handles this by the range tree.

**Review by 3pointer — APPROVED** [review]

**Review by Leavrth — APPROVED** [review]

**Review by iosmanthus — APPROVED** [review]
