### PR TITLE
raftstore: notify stale callbacks before applying

### LINKED ISSUE #9070: committed_cb is always invoked which affects the correctness of async apply
### What version of TiKV are you using?

master

### What operating system and CPU are you using?

not releated

### Steps to reproduce

1. Partition the leader and followers.
2. Propose a write request on the leader.
3. A new leader is elected and commits a new entry.
4. Recover the network partition.
5. The old proposal should be dropped and the committed_cb shouldn't be invoked.

### Root cause
All proposals are sent to the apply system even if some of them aren't committed. We can filter them.
image

### PR DESCRIPTION
**Pull request by NingLin-P**
Signed-off-by: linning <linningde25@gmail.com>

### What problem does this PR solve?

Issue Number: close #9070 

Problem Summary:

Async commit need to invoke the callbacks of committed entries in the store thread, but some callbacks may belong to entries that can't be committed

### What is changed and how it works?

Filter and notify these stale callbacks

Tests 

- Unit test

### Release note 
- No release note

### CODE REVIEW

File: components/raftstore/src/store/peer.rs [hunk 1]
```diff
@@ -79,46 +79,64 @@ struct ProposalQueue<S>
...
+                if p.index == index {
+                    return if p.cb.is_none() { None } else { Some(p) };
+                } else {
+                    panic!(
+                        "{} unexpected callback at term {}, found index {}, expected {}",
+                        self.tag, term, p.index, index
+                    );
+                }
+            } else {
+                apply::notify_stale_req(current_term, p.cb);
```
Comment (BusyJay) [inline components/raftstore/src/store/peer.rs:132]: I don't think it's a good idea. It can cause requests failure during transferring leader.

File: components/raftstore/src/store/peer.rs [hunk 2]
```diff
@@ -1721,24 +1739,32 @@ where
                     self.raft_group.skip_bcast_commit(true);
                     self.last_urgent_proposal_idx = u64::MAX;
                 }
+                let current_term = self.term();
+                let cbs = committed_entries
+                    .iter()
+                    .filter_map(|e| {
```
Comment (BusyJay) [inline components/raftstore/src/store/peer.rs:1745]: How about using `retain`?

File: components/raftstore/src/store/peer.rs (hunk 1 above)
Comment (NingLin-P) [reply components/raftstore/src/store/peer.rs:132]: `find_proposal` is called for each committed entries one by one in order, since `term` is increasing among log entries, proposals enter this branch is impossible to commit (same behavior as before).

File: components/raftstore/src/store/peer.rs (hunk 2 above)
Comment (NingLin-P) [reply components/raftstore/src/store/peer.rs:1745]: The purpose is to find `Proposal` for each committed entry, not changing `committed_entries`

File: components/raftstore/src/store/peer.rs [hunk 3]
```diff
@@ -1721,24 +1739,32 @@ where
                     self.raft_group.skip_bcast_commit(true);
                     self.last_urgent_proposal_idx = u64::MAX;
                 }
+                let current_term = self.term();
+                let cbs = committed_entries
```
Comment (BusyJay) [inline components/raftstore/src/store/peer.rs:1743]: How about checking if `self.proposals` is empty first?

File: components/raftstore/src/store/peer.rs [hunk 4]
```diff
@@ -2103,7 +2129,8 @@ where
                 }
                 self.should_wake_up = true;
                 let p = Proposal {
-                    is_conf_change: req_admin_cmd_type == Some(AdminCmdType::ChangePeer),
+                    is_conf_change: req_admin_cmd_type == Some(AdminCmdType::ChangePeer)
+                        || req_admin_cmd_type == Some(AdminCmdType::ChangePeerV2),
```
Comment (BusyJay) [inline components/raftstore/src/store/peer.rs:2133]: Is it a bug?

**Review by BusyJay — COMMENTED** [review]
Any test case?

File: components/raftstore/src/store/peer.rs (hunk 4 above)
Comment (NingLin-P) [reply components/raftstore/src/store/peer.rs:2133]: Not, it is a mistake but not a bug, because we use `Callback::None` as the callbacks for `ChangePeer` cmds and we will not send these callbacks to the apply thread. Also, if these callbacks did send to the apply thread, some test cases will not pass.

https://github.com/tikv/tikv/blob/9b8785a42f6e03621c0d0ce66799761b3e00f9cc/components/raftstore/src/store/worker/pd.rs#L858

https://github.com/tikv/tikv/blob/9b8785a42f6e03621c0d0ce66799761b3e00f9cc/components/raftstore/src/store/peer.rs#L113-L115

File: components/raftstore/src/store/peer.rs (hunk 3 above)
Comment (NingLin-P) [reply components/raftstore/src/store/peer.rs:1743]: It is checked at

https://github.com/tikv/tikv/blob/9b8785a42f6e03621c0d0ce66799761b3e00f9cc/components/raftstore/src/store/peer.rs#L1717

**Comment by BusyJay** [comment]
I think you need a case to verify the problem mentioned in #9070 is solved.

**Comment by NingLin-P** [comment]
> I think you need a case to verify the problem mentioned in #9070 is solved.

Setting the callback at integration test is quite complicated, I add a unit test instead, PTAL

**Review by BusyJay — COMMENTED** [review]
LGTM

**Comment by NingLin-P** [comment]
PTAL @MyonKeminta @gengliqi

**Review by youjiali1995 — COMMENTED** [review]
/LGTM

File: components/raftstore/src/store/peer.rs [hunk 5]
```diff
@@ -1794,7 +1827,6 @@ where
         // needs to be sent to the apply system.
         // Always sending snapshot task behind apply task, so it gets latest
         // snapshot.
-        // TODO: maybe we should move this code to other place to make the logic more clear.
```
Comment (gengliqi) [inline components/raftstore/src/store/peer.rs:1797]: This TODO work has not been done yet. BTW, I find a bug that the snapshot may not be generated if there is not new committed entry. So the code below should be moved outside. Furthermore, it is unnecessary to send the snapshot task to apply fsm. I will fix them later.

**Review by gengliqi — COMMENTED** [review]
Rest LGTM

File: components/raftstore/src/store/peer.rs (hunk 5 above)
Comment (NingLin-P) [reply components/raftstore/src/store/peer.rs]: I revert this change, PTAL again

**Review by gengliqi — APPROVED** [review]
