### PR TITLE
raftstorev2: fix cached tablet bug

### LINKED ISSUE #12842: Support physical isolation between regions
RFC: tikv/rfcs#93

Summary:

Make every region stores its own data in an isolated LSM tree, in our case RocksDB.

This is the second step to make TiKV to operate fast and at low cost for big cluster.

The first step can be found in #11515.

Tasks:

- [ ] raftstore v2
    - [x] implement read
        - https://github.com/tikv/tikv/pull/13039
        - https://github.com/tikv/tikv/pull/13202
    - [x] implement write
    - [x] implement split
    - [ ] implement merge
    - [x] implement conf change
    - [x] coprocessor hooks
    - [x] memory trace
    - [x] flow control
    - [x] peer lifetime trace
    - [ ] use unified thread pool for apply batch system
    - [x] support driving basic raft activity
        - https://github.com/tikv/tikv/pull/12843
        - https://github.com/tikv/tikv/pull/12877
        - https://github.com/tikv/tikv/pull/12921
        - https://github.com/tikv/tikv/pull/13013
        - https://github.com/tikv/tikv/pull/13115
        - https://github.com/tikv/tikv/pull/13127
        - https://github.com/tikv/tikv/pull/13157
        - https://github.com/tikv/tikv/pull/13227
        - https://github.com/tikv/tikv/pull/13245
- [x] introduce tablet
- [x] implement snapshot

More to be added.

### PR DESCRIPTION
**Pull request by tabokie**
### What is changed and how it works?

Issue Number: Ref #12842

What's Changed:

Some cleaning-ups while reading the code.
- Fix the issue that `CachedTablet::latest()` always acquires lock.
- Initialize buffer capacity when creating a `ApplyPoller`.
- Remove util function `check_or_prepare_bootstrap_first_region` for more clarity.
- Minor improvements to function comments.

```commit-message
None
```

### Check List 

Tests 

- Unit test

### Release note 

```release-note
None
```

### CODE REVIEW

File: components/raftstore-v2/src/bootstrap.rs [hunk 1]
```diff
@@ -71,7 +83,9 @@ impl<'a, ER: RaftEngine> Bootstrap<'a, ER> {
         Ok(Some(ident.get_store_id()))
     }
 
-    fn inner_bootstrap_store(&mut self) -> Result<u64> {
+    /// Allocates a store ID from PD and bootstraps the engine with it. Returns
+    /// the store ID if success.
+    fn bootstrap_store_imp(&mut self) -> Result<u64> {
```
Comment (Connor1996) [inline components/raftstore-v2/src/bootstrap.rs:88]: seems unnecessary to extract a impl

File: components/raftstore-v2/src/bootstrap.rs [hunk 2]
```diff
@@ -33,8 +33,8 @@ pub struct Bootstrap<'a, ER: RaftEngine> {
     logger: Logger,
 }
 
-// Although all methods won't change internal state, but they still receive `&mut self` as it's
-// not thread safe to bootstrap concurrently.
+// Although all methods won't change internal state, but they still receive
```
Comment (Connor1996) [inline components/raftstore-v2/src/bootstrap.rs:36]: Maybe sketch the process of bootstrap here?

File: components/raftstore-v2/src/bootstrap.rs (hunk 1 above)
Comment (tabokie) [reply components/raftstore-v2/src/bootstrap.rs:88]: It's renamed from `inner_bootstrap_store` to `bootstrap_store_imp`.

Comment (Connor1996) [reply components/raftstore-v2/src/bootstrap.rs:88]: I know, but it can be merged into `bootstrap_store` directly

File: components/raftstore-v2/src/bootstrap.rs (hunk 2 above)
Comment (tabokie) [reply components/raftstore-v2/src/bootstrap.rs:36]: Honestly I don't know what is "first region", could you help clarify?

Comment (Connor1996) [reply components/raftstore-v2/src/bootstrap.rs:36]: the initial region whose start key and end key are both empty to cover the whole keyspace range. Other regions would be split from this region after performing some writes

File: components/raftstore-v2/src/bootstrap.rs [hunk 3]
```diff
@@ -52,19 +57,33 @@ impl<'a, ER: RaftEngine> Bootstrap<'a, ER> {
...
-        };
-
-        Ok(store_id)
+        if let Some(id) = self.check_engine_store_id()? {
+            return Ok(id);
+        }
+        let id = self.pd_client.alloc_id()?;
+        debug!(self.logger, "alloc store id"; "store_id" => id);
+        let mut ident = StoreIdent::default();
+        if !self.engine.is_empty()? {
```
Comment (Connor1996) [inline components/raftstore-v2/src/bootstrap.rs:71]: move to L68

File: components/raftstore-v2/src/bootstrap.rs [hunk 4]
```diff
@@ -50,9 +55,35 @@ impl<'a, ER: RaftEngine> Bootstrap<'a, ER> {
...
+        self.engine.sync()?;
+        fail_point!("node_after_bootstrap_store", |_| Err(box_err!(
+            "injected error: node_after_bootstrap_store"
+        )));
+        Ok(id)
+    }
+
+    /// Gets and validates the store ID from engine if it's already
+    /// bootstrapped.
+    fn check_engine_store_id(&mut self) -> Result<Option<u64>> {
```
Comment (Connor1996) [inline components/raftstore-v2/src/bootstrap.rs:86]: how about `check_store_id_in_engine`

File: components/raftstore-v2/src/bootstrap.rs [hunk 5]
```diff
@@ -71,33 +102,115 @@ impl<'a, ER: RaftEngine> Bootstrap<'a, ER> {
...
+                        }
+                        Err(e) => {
+                            warn!(self.logger, "get the first region failed"; "err" => ?e);
+                        }
+                    }
+                }
+                Err(e) => {
+                    error!(
+                        self.logger,
+                        "bootstrap cluster";
```
Comment (Connor1996) [inline components/raftstore-v2/src/bootstrap.rs:187]: failed to bootstrap cluster

**Review by Connor1996 — COMMENTED** [review]
rest LGTM

File: components/raftstore-v2/src/tablet.rs [hunk 6]
```diff
@@ -76,7 +76,14 @@ mod tests {
         // Setting tablet will refresh cache immediately.
         cached_tablet.set(2);
         assert_eq!(cached_tablet.cache().cloned(), Some(2));
-        assert_eq!(cached_tablet.latest().cloned(), Some(2));
+        // Test `latest()` will use cache.
+        {
```
Comment (BusyJay) [inline components/raftstore-v2/src/tablet.rs:80]: This is not the TiKV style.

File: components/raftstore-v2/src/raft/storage.rs [hunk 7]
```diff
@@ -58,8 +58,8 @@ pub struct Storage<ER> {
 impl<ER: RaftEngine> Storage<ER> {
     /// Creates a new storage.
     ///
-    /// All metadata should be initialized before calling this method. If the region is destroyed
-    /// `None` will be returned.
+    /// All metadata should be initialized before calling this method. If the
```
Comment (BusyJay) [inline components/raftstore-v2/src/raft/storage.rs:61]: Why the change?

File: components/raftstore-v2/src/bootstrap.rs [hunk 8]
```diff
@@ -167,75 +255,4 @@ impl<'a, ER: RaftEngine> Bootstrap<'a, ER> {
         box_try!(self.engine.consume(&mut wb, true));
         Ok(())
     }
-
-    fn inner_bootstrap_first_region(
```
Comment (BusyJay) [inline components/raftstore-v2/src/bootstrap.rs:171]: Why move them around?

File: components/raftstore-v2/src/batch/apply.rs [hunk 9]
```diff
@@ -50,15 +50,17 @@ pub struct ApplyPoller {
...
     pub fn new(apply_ctx: ApplyContext, cfg_tracker: Tracker<Config>) -> ApplyPoller {
-        ApplyPoller {
+        let mut poller = ApplyPoller {
             apply_task_buf: Vec::new(),
             pending_latency_inspect: Vec::new(),
             apply_ctx,
             cfg_tracker,
-        }
+        };
+        poller.apply_buf_capacity();
```
Comment (BusyJay) [inline components/raftstore-v2/src/batch/apply.rs:59]: I don't think it's necessary, it's always applied in `begin`.

Comment (tabokie) [reply components/raftstore-v2/src/batch/apply.rs:59]: Okay, I just copied it from store poller.

File: components/raftstore-v2/src/raft/storage.rs (hunk 7 above)
Comment (tabokie) [reply components/raftstore-v2/src/raft/storage.rs:61]: 80c limit.

Comment (BusyJay) [reply components/raftstore-v2/src/raft/storage.rs:61]: In Rust, it's 99.

File: components/raftstore-v2/src/tablet.rs (hunk 6 above)
Comment (tabokie) [reply components/raftstore-v2/src/tablet.rs:80]: What is not? Be a little more specific?

File: components/raftstore-v2/src/bootstrap.rs (hunk 8 above)
Comment (tabokie) [reply components/raftstore-v2/src/bootstrap.rs:171]: Which part are you referring to? This function is removed because @Connor1996 suggested it and I agree it looks better. Or are you referring to the ordering between public function and private sub-routines? My habit is to read public functions first, private methods later (just like C++ code). If you have a better reason suggesting the opposite I'm willing to change it back.

File: components/raftstore-v2/src/tablet.rs (hunk 6 above)
Comment (BusyJay) [reply components/raftstore-v2/src/tablet.rs:80]: Wrapping test steps in a pair of brackets. We usually use a blank line.

File: components/raftstore-v2/src/raft/storage.rs (hunk 7 above)
Comment (tabokie) [reply components/raftstore-v2/src/raft/storage.rs:61]: I don't think so. Rust fmt default configures it as 80: https://rust-lang.github.io/rustfmt/?version=v1.5.1&search=#comment_width, and rust source code uses 80 too.

File: components/raftstore-v2/src/tablet.rs (hunk 6 above)
Comment (tabokie) [reply components/raftstore-v2/src/tablet.rs:80]: Okay. The intention really is to scope the unsafe modifications of `data`.

File: components/raftstore-v2/src/bootstrap.rs (hunk 8 above)
Comment (BusyJay) [reply components/raftstore-v2/src/bootstrap.rs:171]: I refer to the ordering of functions. Everyone has their habits. To me, related functions should be put together no matter what access level they are. However, I don't think it's a good idea to reorder them again after they are committed to the code base unless for common sense.

File: components/raftstore-v2/src/raft/storage.rs (hunk 7 above)
Comment (BusyJay) [reply components/raftstore-v2/src/raft/storage.rs:61]: Got it, never expect length of comment line is different from source code.

Comment (BusyJay) [reply components/raftstore-v2/src/raft/storage.rs:61]: Turns out I'm not the only one has the confusion: https://github.com/rust-lang/rustfmt/issues/3349#issuecomment-622522913

Comment (tabokie) [reply components/raftstore-v2/src/raft/storage.rs:61]: Having looked closer, apparently rust source code uses different comment width as well.. Personally I think 80c comment is perfect, whilst source code is easier to digest because they are structured.

File: components/raftstore-v2/src/bootstrap.rs (hunk 8 above)
Comment (Connor1996) [reply components/raftstore-v2/src/bootstrap.rs:171]: `inner_bootstrap_first_region` is extracted without any sense, it can be just placed into `bootstrap_first_region`. Moreover, `inner_bootstrap_first_region` disturbs the ordering for reading code, you need to read back and forth. Now, it's clean and neat.

Comment (tabokie) [reply components/raftstore-v2/src/bootstrap.rs:171]: So we can all agree related functions should be grouped together. As for the ordering, I believe it's favorable to arrange code as we read them. In the old days this is mostly impossible because of name resolution constraints, but with Rust I think we should arrange things naturally whenever we can (which is top down, reading flow, in contrary to writing flow).

Comment (BusyJay) [reply components/raftstore-v2/src/bootstrap.rs:171]: I think reading several small functions with meaningful names is a lot easier than reading a long functions with a lot of comments. But this function is not too long to be split, so I'm OK with the change.

File: components/raftstore-v2/src/batch/store.rs [hunk 10]
```diff
@@ -64,19 +64,17 @@ struct StorePoller<EK: KvEngine, T> {
 
 impl<EK: KvEngine, T> StorePoller<EK, T> {
     pub fn new(poll_ctx: StoreContext<T>, cfg_tracker: Tracker<Config>) -> Self {
-        let mut poller = Self {
+        StorePoller {
```
Comment (BusyJay) [inline components/raftstore-v2/src/batch/store.rs:67]: I use `Self` on purpose. I have found it very convenient when the name is changed several times during development. Though I'm OK with either way.

File: components/raftstore-v2/src/bootstrap.rs (hunk 8 above)
Comment (BusyJay) [reply components/raftstore-v2/src/bootstrap.rs:171]: > I think we should arrange things naturally whenever we can

I don't think so as there is no consensus on what's natural. For example, for peer struct, what's the natural way to order all those the functions?

And when reading using vscode/vim/ides, there is no much difference between top/down or jumping using builtin support tools.

I consider reordering functions evil as it's hard to review. If the suggestion is proposed the first time PR is sent, it's acceptable.

**Review by Connor1996 — APPROVED** [review]
LGTM

File: components/raftstore-v2/src/bootstrap.rs (hunk 8 above)
Comment (tabokie) [reply components/raftstore-v2/src/bootstrap.rs:171]: > If the suggestion is proposed the first time PR is sent, it's acceptable.

Clearly we need some basic style guides here, at least some sense of what is considered more readable. I can relate that ordering is not very important. Especially when the member functions keep growing and get further intertwined.

> I think reading several small functions with meaningful names is a lot easier than reading a long functions with a lot of comments.

However, I want to fight a little on this (even though it's not the point of this PR). Splitting a function creates cognitive load for the reader. When reading the code, one has to keep the control flow context inside the (human) memory, the same way that a computer would keep stack variables around. So I want to make sure we can all agree that function calling depth should be kept low if possible.

Furthermore for raftstore code, most functions mutate some internal states (let it be engine data, memory states, network states). Creating sub-routines make the state mutation hard to track.

Both of these two points can't be addressed with IDE. And since we are rebuilding the raftstore code, I think it makes sense to push for this and make the code easier to read than v1.

For reference, I love this post and some related HN discussions: https://hn.algolia.com/?dateRange=all&page=0&prefix=true&query=inlined%20code&sort=byPopularity&type=story

File: components/raftstore-v2/src/raft/storage.rs (hunk 7 above)
Comment (Connor1996) [reply components/raftstore-v2/src/raft/storage.rs:61]: Let's limit the comment width automatically by rustfmt, then it's no need to discuss it again and again. https://github.com/tikv/tikv/pull/13139 some comments should be adjusted after auto wrap, will work on fixing it once we get an agreement on the comment width.

File: components/raftstore-v2/src/bootstrap.rs (hunk 8 above)
Comment (BusyJay) [reply components/raftstore-v2/src/bootstrap.rs:171]: > I can relate that ordering is not very important.

Yes, to me it's not important. If the comment is sent back in the time, I will happily change it. The most important thing is:
1. Don't randomly change the order of committed code as it's hard to read and it causes trouble of future cherry-picks of potential bugs;
2. Functions with related purpose should be put together to ease context switch. That's the purpose why v2 has `operations` module to split code by operations.

> Splitting a function creates cognitive load for the reader. 

Note the prerequisite is **small functions with meaningful names**. As long as the function name makes sense, all we need to look to is whether the implementation represents its name. So there will be no such requirement to keep tracking variables. For example:
```
if store.needs_continue_bootstrapping() {
    store.bootstrap();
}
```
One can easily know what the flow is by name. Though I'm not suggesting the original naming is precise and correct, just suggesting reusing codes is not the only purpose of extracting functions.

**Review by BusyJay — APPROVED** [review]

File: components/raftstore-v2/src/bootstrap.rs (hunk 8 above)
Comment (tabokie) [reply components/raftstore-v2/src/bootstrap.rs:171]: Yes, it's a good point. Though many would argue that using function as a way to "group code" isn't really better than just writing some comments. Because to understand `needs_continue_bootstrapping`, you still need to do a context switch. It's against human's nature to put the questions aside and take the function name as its implementation.

In our situation, I am advising strongly on calling depth and state mutations. Good function names can only do as much. And take a second thought before doing a refactor. Veteran devs such as yourself sometimes just get too comfortable with sub-routines and treating them like "common sense", meanwhile for newcomer it would take a long while to get around.

File: components/raftstore-v2/src/batch/store.rs [hunk 11]
```diff
@@ -64,19 +64,17 @@ struct StorePoller<EK: KvEngine, T> {
...
-        let mut poller = Self {
+        Self {
             store_msg_buf: Vec::new(),
             peer_msg_buf: Vec::new(),
             poll_ctx,
             cfg_tracker,
             last_flush_time: TiInstant::now(),
             need_flush_events: false,
-        };
-        poller.apply_buf_capacity();
```
Comment (BusyJay) [inline components/raftstore-v2/src/batch/store.rs:75]: Receiving messages depends on the capacity. Without initializing the capacity, it will never receive any messages.

Comment (tabokie) [reply components/raftstore-v2/src/batch/store.rs:75]: I deleted it because of your https://github.com/tikv/tikv/pull/13127#discussion_r930583660. But yes, apparently I wasn't paying attention either.

Comment (BusyJay) [reply components/raftstore-v2/src/batch/store.rs:75]: I have another PR fixing it by passing an argument explicitly. Using capacity is too obscure.
