### PR TITLE
tikv_util: fix tokio-timer panic when clock goes backward

### LINKED ISSUE #14518: monotonic time jumped back
### What version of TiKV are you using?
v6.1.2

### What operating system and CPU are you using?
ubuntu

### Steps to reproduce
Run Jepsen test configured with the append workload and the kill/pause/partition nemesis

### What did you expect?
monotonic time should be always increasing 

### What happened?
We didn't configure any clock changing nemesis, but the monotonic time jumped back. The following is the bug report from the logs:
`./20230316T152153.412Z/n4/kv.log:[2023/03/16 15:22:53.812 +00:00] [ERROR] [time.rs:372] ["monotonic time jumped back, 7968842.265 -> 7968842.265"]`

### LINKED ISSUE #16623: tikv crash or panic: "monotonic time jumped back"
### What version of TiKV are you using?
TiKV 
Release Version:   7.1.3
Edition:           Community
Git Commit Hash:   cd2c94fa9ce310d7342e52678e1bf45ac499c649
Git Commit Branch: heads/refs/tags/v7.1.3
UTC Build Time:    2023-12-18 14:55:09
Rust Version:      rustc 1.67.0-nightly (96ddd32c4 2022-11-14)
Enable Features:   pprof-fp jemalloc mem-profiling portable sse test-engine-kv-rocksdb test-engine-raft-raft-engine cloud-aws cloud-gcp cloud-azure
Profile:           dist_release

### What operating system and CPU are you using?
processor       : 15
vendor_id       : AuthenticAMD
cpu family      : 23
model           : 49
model name      : AMD EPYC 7K62 48-Core Processor
stepping        : 0
microcode       : 0x1000065
cpu MHz         : 2595.124
cache size      : 512 KB
physical id     : 0
siblings        : 16
core id         : 27
cpu cores       : 16
apicid          : 15
initial apicid  : 15
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm rep_good nopl cpuid extd_apicid amd_dcm tsc_known_freq pni pclmulqdq ssse3 fma cx16 sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm cmp_legacy cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw topoext ibpb vmmcall fsgsbase bmi1 avx2 smep bmi2 rdseed adx smap clflushopt sha_ni xsaveopt xsavec xgetbv1 arat
bugs            : fxsave_leak sysret_ss_attrs spectre_v1 spectre_v2 spec_store_bypass
bogomips        : 5190.24
TLB size        : 1024 4K pages
clflush size    : 64
cache_alignment : 64
address sizes   : 48 bits physical, 48 bits virtual
power management:

### Steps to reproduce
I don't know how to reproduce .

### What did you expect?
how to fix it or how to make tikv to work normally，not to be crash .
### What did happened?
I am not sure how to it happened .
there are error logs about tikv when it crashed.
`[2024/03/07 17:59:29.043 +08:00] [ERROR] [time.rs:374] ["monotonic time jumped back, 1581214.068 -> 1581214.057"]
[2024/03/07 17:59:29.043 +08:00] [ERROR] [time.rs:374] ["monotonic time jumped back, 1581214.068 -> 1581214.057"]
[2024/03/07 17:59:29.045 +08:00] [FATAL] [lib.rs:510] ["elapsed=56976988; when=56976976"] [backtrace="   0: tikv_util::set_panic_hook::{{closure}}\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/tikv_util/src/lib.rs:509:18\n   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2032:9\n      std::panicking::rust_panic_with_hook\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:692:13\n   2: std::panicking::begin_panic_handler::{{closure}}\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:579:13\n   3: std::sys_common::backtrace::__rust_end_short_backtrace\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:137:18\n   4: rust_begin_unwind\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:575:5\n   5: core::panicking::panic_fmt\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panicking.rs:65:14\n   6: tokio_timer::wheel::Wheel<T>::poll\n   7: tokio_timer::timer::Timer<T,N>::process\n             at rust/git/checkouts/tokio-8e927faba632ed16/4394380/tokio-timer/src/timer/mod.rs:272:33\n      <tokio_timer::timer::Timer<T,N> as tokio_executor::park::Park>::park\n             at rust/git/checkouts/tokio-8e927faba632ed16/4394380/tokio-timer/src/timer/mod.rs:379:9\n      tokio_timer::timer::Timer<T,N>::turn\n             at rust/git/checkouts/tokio-8e927faba632ed16/4394380/tokio-timer/src/timer/mod.rs:256:21\n   8: tikv_util::timer::start_global_steady_timer::{{closure}}\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/tikv_util/src/timer.rs:209:17\n      <std::thread::Builder as tikv_util::sys::thread::StdThreadBuildWrapper>::spawn_wrapper::{{closure}}\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/tikv_util/src/sys/thread.rs:427:23\n      std::sys_common::backtrace::__rust_begin_short_backtrace\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:121:18\n   9: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:551:17\n      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panic/unwind_safe.rs:271:9\n      std::panicking::try::do_call\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:483:40\n      std::panicking::try\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:447:19\n      std::panic::catch_unwind\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:137:14\n      std::thread::Builder::spawn_unchecked_::{{closure}}\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:550:30\n      core::ops::function::FnOnce::call_once{{vtable.shim}}\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:513:5\n  10: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2000:9\n      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2000:9\n      std::sys::unix::thread::Thread::new::thread_start\n             at rust/toolchains/nightly-2022-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys/unix/thread.rs:108:17\n  11: start_thread\n  12: __GI___clone3\n"] [location=/rust/git/checkouts/tokio-8e927faba632ed16/4394380/tokio-timer/src/wheel/mod.rs:225] [thread_name=steady-timer]`

### PR DESCRIPTION
**Pull request by overvenus**
### What is changed and how it works?

Issue Number: Close #16623 Close #14518

What's Changed:

```commit-message
This commit workarounds a panic[^1] in tokio-timer when the clock goes
backward, which is possible in some environments, e.g., aliyun ECS g7.

[^1]: https://github.com/tokio-rs/tokio/pull/515
```

### Related changes

- Need to cherry-pick to the release branch

### Check List

Tests 

- Unit test

### Release note

```release-note
Fix the issue that TiKV panics due to system clock goes backward
```

### CODE REVIEW

File: components/tikv_util/src/timer.rs [hunk 1]
```diff
@@ -196,28 +188,91 @@ impl Default for SteadyTimer {
...
+    let clock = Clock::new_with_now(ratchet_clock);
     Builder::new()
-        .name(thd_name!("steady-timer"))
+        .name(thd_name!(name))
         .spawn_wrapper(move || {
-            let c = Clock::new_with_now(clock_);
-            let mut timer = tokio_timer::Timer::new_with_now(ParkThread::new(), c);
+            crate::thread_group::set_properties(props);
+
+            let mut timer = tokio_timer::Timer::new_with_now(ParkThread::new(), clock);
```
Comment (glorv) [inline components/tikv_util/src/timer.rs:262]: I if understand correctly, the timer thread is a single-threaded, it's seems unnecessary to let the clock to be thread safe.

Comment (overvenus) [reply components/tikv_util/src/timer.rs:262]: The `Now` trait requires `Sync + Send + 'static`, so it has to be thread-safe.

Comment (glorv) [reply components/tikv_util/src/timer.rs:262]: I think in this use case, the `Sync` bound is too strong and unnecessary if the clock is only used in the timer thread.

BTW, in the current implementation, you suppose the cloud can be visited by different threads concurrently. If this is true, then the comparison of time value from different threads is meaningless as they don't have a causal order.

Comment (overvenus) [reply components/tikv_util/src/timer.rs:262]: Although the `RatchetClock` has to be thread-safe, the `Clock` that wraps it can only be accessed by the timer thread. So the `RatchetClock` will not be accessed by multiple threads.

Note that the `Now` trait is defined by the tokio-timer crate, and yes, the thread-safety requirement does seem an unnecessary in the current usage.

File: components/tikv_util/src/timer.rs [hunk 2]
```diff
@@ -196,28 +185,88 @@ impl Default for SteadyTimer {
...
+///
+/// It is used to workaround a panic[^1] in tokio-timer when the clock goes
+/// backward, which is possible in some environments, e.g., aliyun ECS g7.
+///
+/// [^1]: https://github.com/tokio-rs/tokio/pull/515
+struct RatchetClock<T: Now> {
+    // Although the RatchetClock has to be thread-safe (Now requires Sync+Send),
+    // the [`tokio_timer::timer::Clock`] that wraps it can only be accessed by
+    // the timer thread. Therefore, performance penalty of using a Mutex is negligible.
+    state: Mutex<RatchetClockState<T>>,
```
Comment (glorv) [inline components/tikv_util/src/timer.rs:203]: While I still think a `Cell<u64>` is enough here, using a Mutex here is acceptable to me as there should be no performance impact.

**Review by glorv — APPROVED** [review]
LGTM

**Review by LykxSassinator — APPROVED** [review]
