### PR TITLE
pd-client:  pd client should update if the grpc stream sender failed.

### LINKED ISSUE #12934: Master: two tikv don't report region heartbeat after inject fault to pd leader
### What version of TiKV are you using?

./tikv-server -V
 TiKV
Release Version:   6.2.0-alpha
Edition:           Community
Git Commit Hash:   a9c3e56552c803642f640e9b3fa8725aa3072400
Git Commit Branch: heads/refs/tags/v6.1.0-nightly
UTC Build Time:    2022-06-24 11:02:31
### Steps to reproduce

plan/850383
clinic
    /portal/#/orgs/31/clusters/7113750135811495492?from=1656298923&to=1656335643

[2022/06/27 12:58:56.346 +08:00] [INFO] [chaos.go:93] ["Run chaos"] [name="pd io delay"] [selectors="[endless-oltp-tps-850383-1-635/tc-pd-1]"] [SelectorsRetainPolicy(selectors)="[endless-oltp-tps-850383-1-635/tc-pd-1]"] [targetSelectors="[nil]"] [
TargetSelectorsRetainPolicy(targetSelectors)="[nil]"] [experimentSpec="IODelaySpec{Duration: \"\", Scheduler: <nil>, Delay: \"438ms\", Path: \"\", Percent: 72}"]
[2022/06/27 13:03:56.369 +08:00] [INFO] [chaos.go:156] ["Clean chaos"] [name="pd io delay"] [chaosId="ns=endless-oltp-tps-850383-1-635,kind=io-delay,name=io-delay-xknijuyf,spec=&k8s.ChaosIdentifier{Namespace:\"endless-oltp-tps-850383-1-635\", Name
:\"io-delay-xknijuyf\", Spec:IODelaySpec{Duration: \"\", Scheduler: <nil>, Delay: \"438ms\", Path: \"\", Percent: 72}}"]

### What did you expect?
tikv should works fine

### What did happened?
Two tikvs don't report region heartbeat.
image

### PR DESCRIPTION
**Pull request by bufferflies**
### What is changed and how it works?

Issue Number: Close #12934

What's Changed: the error should be  retryable error instead of unkown , this  unkown error will not retry update pd client if the sender failed. 

```commit-message
```

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Integration test
- Manual test (add detailed scripts or steps below)

Side effects

### Release note 

```release-note
fix the bug that the consume should be refresh if region heartbeat send failed.
```

### CODE REVIEW

**Comment by BusyJay** [comment]
I don't get it. If the connection is broken, then the RPC will be rebuilt automatically.

File: components/test_pd/src/mocker/service.rs [hunk 1]
```diff
@@ -238,6 +238,7 @@ impl PdMocker for Service {
             .insert(region_id, req.get_leader().clone());
 
         let mut resp = RegionHeartbeatResponse::default();
+        resp.set_region_id(req.get_region().get_id());
```
Comment (AndreMouche) [inline components/test_pd/src/mocker/service.rs:241]: why?

File: components/pd_client/src/client.rs [hunk 2]
```diff
@@ -643,7 +646,7 @@ impl PdClient for RpcClient {
                 .expect("expect region heartbeat sender");
             let ret = sender
                 .unbounded_send(req)
-                .map_err(|e| Error::Other(Box::new(e)));
+                .map_err(|_e|Error::Grpc(grpcio::Error::RemoteStopped));
```
Comment (nolouch) [inline components/pd_client/src/client.rs:649]: why drop the origin errors? can we unwrap the `Other Error`?

**Comment by bufferflies** [comment]
> I don't get it. If the connection is broken, then the RPC will be rebuilt automatically.

it will not rebuilt if pd  closed the stream or some net package loss.

File: components/test_pd/src/mocker/service.rs (hunk 1 above)
Comment (bufferflies) [reply components/test_pd/src/mocker/service.rs:241]: It returns the the default region not the requested the region.

**Comment by BusyJay** [comment]
> it will not rebuilt if pd closed the stream or some net package loss.

Any test case to show that "it will not rebuilt"? At least the code says it will.

https://github.com/tikv/tikv/blob/b1952dcaf8af9ab218916b26eb5dd3ce72a8d638/components/pd_client/src/util.rs#L384

**Comment by bufferflies** [comment]
> > it will not rebuilt if pd closed the stream or some net package loss.
> 
> Any test case to show that "it will not rebuilt"? At least the code says it will.
> 
> https://github.com/tikv/tikv/blob/b1952dcaf8af9ab218916b26eb5dd3ce72a8d638/components/pd_client/src/util.rs#L384

The grpc connection work well but the the region heartbeat rpc broken once .

File: components/pd_client/src/client.rs (hunk 2 above)
Comment (bufferflies) [reply components/pd_client/src/client.rs]: fix

File: tests/integrations/pd/test_rpc_client.rs [hunk 3]
```diff
@@ -475,6 +475,62 @@ fn test_change_leader_async() {
...
+        let stat = RegionStat::default();
+        poller.spawn(client.region_heartbeat(
+            store::RAFT_INIT_LOG_TERM,
+            region.clone(),
+            peer.clone(),
+            stat.clone(),
+            None,
+        ));
+        let rsp=rx.recv_timeout(Duration::from_millis(100));
+        if ok{
```
Comment (5kbpers) [inline tests/integrations/pd/test_rpc_client.rs:510]: format

Comment (bufferflies) [reply tests/integrations/pd/test_rpc_client.rs]: fix

**Review by 5kbpers — APPROVED** [review]

**Review by nolouch — APPROVED** [review]
lgtm

**Review by Connor1996 — APPROVED** [review]
