### PR TITLE
router: synthesis timestamps when PD ts is unavailable

### LINKED ISSUE #19269: log_backup: metadata file might collide when cannot connect to PD
### What version of TiKV are you using?
release-8.5

### What operating system and CPU are you using?
N/A

### Steps to reproduce
Run TiKV among 3 AZs, start log backup and TPCC workload, inject partial network isolation into 2 of them. 

### What did you expect?
When restoring, we should be able to restore to a consistent point-in-time.

### What did happened?
Some of data were lost, see https://github.com/pingcap/tidb/issues/65312#issuecomment-3709815441

### PR DESCRIPTION
**Pull request by YuJuncen**
### What is changed and how it works?

Issue Number: , close #19269, close https://github.com/pingcap/tidb/issues/65312

What's Changed:

```commit-message
This PR makes TiKV use local clock to synthesis flush ts when PD is unavailable, also this enhanced some logs during flushing.
```

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [ ] Need to cherry-pick to the release branch

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note

```release-note
Fixed an issue that may cause metadata lost when PD is unavailable.
```

### CODE REVIEW

**Review by 3pointer — APPROVED** [review]

File: components/backup-stream/src/router.rs [hunk 1]
```diff
@@ -3337,4 +3354,35 @@ mod tests {
...
+            "v1/backupmeta/000000000000012C-0000000000000032-0000000000000064-00000000000000C8.meta"
+        );
+
+        // Case 2: flush_ts is 0
+        let path_synthetic = meta.path_to_meta(50, 0);
+        let another_path_synthetic = meta.path_to_meta(50, 0);
+        // synthetic paths should be unique due to different UUIDs
+        assert_ne!(another_path_synthetic, path_synthetic);
+
+        assert!(path_synthetic.contains("-SYNTHETIC"));
```
Comment (pingyu) [inline components/backup-stream/src/router.rs]: How about verify by regex ? That would be more readable.

**Review by iosmanthus — APPROVED** [review]
