### PR TITLE
txn: introduce pessimistic rollback read phase

### LINKED ISSUE #16158: server: lock wait should not consider expired pessimistic locks
## Development Task

If a pessimistic transaction encounters residual pessimistic locks, it might wait for each lock until the lock timeout expires before attempting to resolve it. Currently, we haven't checked the time-to-live (TTL) of the lock or whether the request carries expiration information.
The https://docs.pingcap.com/tidb/stable/tikv-configuration-file#wait-for-lock-timeout is `1s` by default, which means the lock resolve would happen only after the `1s` interval. In cases that the transaction coordinator for example the tidb-server crashes, resolving and cleaning the left locks may take a lot of time nearly one lock per `1s`.

An improvement in this case is to check the lock TTL first before starts to wait for the lock. If the lock already expires, it's not needed to wait for the lock release and start resolving immediately.

### PR DESCRIPTION
**Pull request by cfzjywxk**
### What is changed and how it works?

Issue Number: Close #16158 

What's Changed:

Depending on https://github.com/tikv/tikv/pull/16180, by now it's not completed yet.
From the debugging test, 
```
CREATE TABLE t1 (id BIGINT NOT NULL PRIMARY KEY auto_increment, pad1 BLOB, pad2 BLOB, pad3 BLOB, int_col INT NOT NULL DEFAULT 0);
INSERT INTO t1 SELECT NULL, RANDOM_BYTES(1024), RANDOM_BYTES(1024), RANDOM_BYTES(1024), 0 FROM dual;
INSERT INTO t1 SELECT NULL, RANDOM_BYTES(1024), RANDOM_BYTES(1024), RANDOM_BYTES(1024), 0 FROM t1 a JOIN t1 b JOIN t1 c LIMIT 10000;
INSERT INTO t1 SELECT NULL, RANDOM_BYTES(1024), RANDOM_BYTES(1024), RANDOM_BYTES(1024), 0 FROM t1 a JOIN t1 b JOIN t1 c LIMIT 10000;
INSERT INTO t1 SELECT NULL, RANDOM_BYTES(1024), RANDOM_BYTES(1024), RANDOM_BYTES(1024), 0 FROM t1 a JOIN t1 b JOIN t1 c LIMIT 10000;
-- session 1
begin
update t1 set t1.pad1 = RANDOM_BYTES(1024) where id < 3000;  
-- kill tidb-server, the pessimistic locks are left
-- reconnect to the tidb-server and execute the same statement again
begin
update t1 set t1.pad1 = RANDOM_BYTES(1024) where id < 3000; 
```

The master branch:
mysql> begin; update t1 set t1.pad1 = RANDOM_BYTES(1024) where id < 3000 ;
ERROR 2013 (HY000): Lost connection to MySQL server during query
No connection. Trying to reconnect...
Connection id:    4208984066
Current database: test
Query OK, 0 rows affected (0.01 sec)
Query OK, 1010 rows affected (**1 min 5.12 sec**)
Rows matched: 1010  Changed: 1010  Warnings: 0

This PR:
mysql> begin; update t1 set t1.pad1 = RANDOM_BYTES(1024) where id < 3000 ;
ERROR 2013 (HY000): Lost connection to MySQL server during query
No connection. Trying to reconnect...
Connection id:    1874853890
Current database: test
Query OK, 0 rows affected (0.00 sec)
Query OK, 1010 rows affected (**10.37 sec**)
Rows matched: 1010  Changed: 1010  Warnings: 0

```commit-message
Reduce the cost of expired lock cleaning by introducing pessimsitic rollback read phase, the expired 
pessimistic locks belonging to the same transcation could be cleaned up within one RPC request. 
```

### Check List

Tests 

- [x] Unit test
- [x] Integration test

Side effects

### Release note

```release-note
None
```

### CODE REVIEW

File: src/storage/txn/commands/pessimistic_rollback_read_phase.rs [hunk 1]
```diff
@@ -0,0 +1,87 @@
...
+        statistics.add(&reader.statistics);
+        let (locks, has_remain) = res?;
+        tls_collect_keyread_histogram_vec(tag.get_str(), locks.len() as f64);
+
+        if locks.is_empty() {
+            Ok(ProcessResult::MultiRes { results: vec![] })
+        } else {
+            let next_scan_key = if has_remain {
+                // There might be more locks.
+                locks.last().map(|(k, _lock)| k.clone())
```
Comment (MyonKeminta) [inline src/storage/txn/commands/pessimistic_rollback_read_phase.rs:69]: As this key is already processed, we can append a zero to the key to exclude it in the next scan. Not very important though.

File: src/storage/mod.rs [hunk 2]
```diff
@@ -1459,37 +1458,20 @@ impl<E: Engine, L: LockManager, F: KvFormat> Storage<E, L, F> {
...
                             |_, lock| lock.start_ts <= max_ts,
-                            limit,
-                        )
-                        .map_err(txn::Error::from);
-                    let (memory_lock_kv_pairs, _) = memory_locks?;
-                    let result = reader
-                        .scan_locks(
-                            start_key.as_ref(),
-                            end_key.as_ref(),
                             |lock| lock.ts <= max_ts,
```
[the remark this answers is not in the document]
Comment (cfzjywxk) [reply src/storage/mod.rs]: A new type `TxnLock` is abstracted, PTAL.

File: src/storage/mvcc/reader/reader.rs [hunk 3]
```diff
@@ -278,12 +279,52 @@ impl<S: EngineSnapshot> MvccReader<S> {
         Ok(())
     }
 
-    pub fn load_in_memory_pessimisitic_lock_range<F>(
+    pub fn scan_pessimistic_locks_with_memory<F1, F2>(
```
[the remark this answers is not in the document]
Comment (cfzjywxk) [reply src/storage/mvcc/reader/reader.rs]: The names are changed accordingly.

File: src/storage/mvcc/reader/reader.rs [hunk 4]
```diff
@@ -278,12 +279,52 @@ impl<S: EngineSnapshot> MvccReader<S> {
...
+            source,
+        )?;
+        let (kv_pairs, kv_pair_has_remain) =
+            self.scan_locks(start_key, end_key, filter_lock_cf, limit)?;
+        // Merge the results from in-memory pessimistic locks and the lock cf.
+        // The result order is decided by the key.
+        let memory_lock_iter = memory_locks.into_iter();
+        let lock_iter = kv_pairs.into_iter();
+        let merged_iter =
+            memory_lock_iter.merge_by(lock_iter, |(memory_key, _), (key, _)| memory_key <= key);
```
[the remark this answers is not in the document]
Comment (cfzjywxk) [reply src/storage/mvcc/reader/reader.rs]: Thanks for the reminding, the merge logic is rewriten, PTAL.

File: src/storage/txn/commands/pessimistic_rollback_read_phase.rs [hunk 5]
```diff
@@ -0,0 +1,87 @@
...
+            .scan_pessimistic_locks_with_memory(
+                self.scan_key.as_ref(),
+                None,
+                |_, lock| {
+                    lock.start_ts == self.start_ts && lock.for_update_ts <= self.for_update_ts
+                },
+                |lock| {
+                    lock.ts == self.start_ts
+                        && lock.is_pessimistic_lock()
+                        && lock.for_update_ts <= self.for_update_ts
```
[the remark this answers is not in the document]
Comment (cfzjywxk) [reply src/storage/txn/commands/pessimistic_rollback_read_phase.rs]: Good idea, I'll check about the `for_update_ts` constraints and try to improve it maybe in the latter PR.

File: src/storage/mvcc/reader/reader.rs [hunk 6]
```diff
@@ -278,15 +284,117 @@ impl<S: EngineSnapshot> MvccReader<S> {
...
+        start_key: Option<&Key>,
+        end_key: Option<&Key>,
+        filter: F,
+    ) -> Result<Option<(Key, Lock)>>
+    where
+        F: Fn(&Key, TxnLock<'_>) -> bool,
+    {
+        self.create_lock_cursor()?;
+        let cursor = self.lock_cursor.as_mut().unwrap();
+        if !self.lock_cursor_seeked {
```
Comment (MyonKeminta) [inline src/storage/mvcc/reader/reader.rs:298]: I don't suggest introducing such a new state to reader actually. The caller must know how the first call to this function determines the reader's state, and then the reader cannot be used to perform another `scan_lock` any more. Actually we don't like the fact for a long time that cursors in the reader are already stateful stuff.

For our current need, I think it would be better to work with cursors directly in the function `scan_locks`, instead of splitting to another function, and using `lock_cursor.next` directly when iterating.

File: src/storage/mvcc/reader/reader.rs [hunk 7]
```diff
@@ -278,12 +279,103 @@ impl<S: EngineSnapshot> MvccReader<S> {
...
+        filter: F,
+        limit: usize,
+        source: ScanLockReadTimeSource,
+    ) -> Result<(Vec<(Key, Lock)>, bool)>
+    where
+        F: Fn(&Key, TxnLockRef<'_>) -> bool,
+    {
+        let (memory_locks, memory_has_remain) = self.load_in_memory_pessimistic_lock_range(
+            start_key,
+            end_key,
```
Comment (zyguan) [inline src/storage/mvcc/reader/reader.rs:298]: Reminded by https://github.com/tikv/tikv/pull/16180#discussion_r1430442189 , should we limit the scan range here to `[max(start_key, snapshot.lower_bound), min(end_key, snapshot.upper_bound))`? For example, let
```
snap1: { lower: k0, upper: k1, locks: [l0] }
snap2: { lower: k1, upper: k2, locks: [l1] }
...
mem: [
    l2, // k0 < l2.key < k1
    l3, // k2 < l3.key
    ...
]
```
would `scan_locks(limit=3)` return `[l0,l2,l3]`? (note `l2.key < l1.key < l3.key`)

Comment (cfzjywxk) [reply src/storage/mvcc/reader/reader.rs:298]: The `scan_lock` is not a snapshot read when considering in-memory pessimistic locks. The storage read and memory read could be processed independently to get locks within [start_key, end_key) I think.

I don't quite undestand the example above, could you explain more about it?

Comment (zyguan) [reply src/storage/mvcc/reader/reader.rs:298]: Let:
```
snap1: { lower: nil, upper: 'b', locks: [l1{key:'a1'}] }
snap2: { lower: 'b', upper: 'c', locks: [l2{key:'b1'}] }
snap3: { lower: 'c', upper: nil, locks: [l3{key:'c1'}] }
mem: [
    ml1{key:'a2'},
    ml2{key:'c2'},
]
```
According to the following gc resolve lock logic:
```go
ResolveLocksForRange(startKey, endKey) {
    key := startKey
    for {
        locks, loc, err := resolver.ScanLocksInOneRegion(bo, key, maxVersion, scanLimit)
        if len(locks) < int(scanLimit) {
            stat.CompletedRegions++
            key = loc.EndKey
        } else {
            key = locks[len(locks)-1].Key
        }
        if len(key) == 0 || (len(endKey) != 0 && bytes.Compare(key, endKey) >= 0) {
            break
        }
    }
}
```
l2 and l3 might be omitted? since
- ResolveLocksForRange(nil, nil, scanLimit=3)
  - ScanLocksInOneRegion(nil, 3) -> [l1, ml1, ml2]
  - ScanLocksInOneRegion('c2', 3) -> []

Comment (zyguan) [reply src/storage/mvcc/reader/reader.rs:298]: The above case would not happen because the end key of region is specified [here](https://github.com/tikv/client-go/blob/c7d29aafa7073f64555532d0d10f19714bc8e6c2/tikv/gc.go#L229C13-L229C13). I just worry about if there are some similar issues.

Comment (zyguan) [reply src/storage/mvcc/reader/reader.rs:298]: Oh, my fault, I forget that the mem keys are also managed by each region.

Comment (cfzjywxk) [reply src/storage/mvcc/reader/reader.rs:298]: I see, thanks for the reminding.
The problem is that the next scan key could not be the `lock[len(locks - 1)].key` after introducing  the `merge` operation for memory and storage locks.

For the `scan_lock` itself, it would be easier to use just considering [start_key, end_key), another approach to resolve this is to return `next_scan_key` explicitly in the `scan_lock` responses if there are remaining results, and the `next_scan_key` could be `min(snapshot_start_key, lock[len(locks - 1)].key)`.

Comment (cfzjywxk) [reply src/storage/mvcc/reader/reader.rs:298]: @zyguan @MyonKeminta 
What do you think? Any other ideas?

Comment (cfzjywxk) [reply src/storage/mvcc/reader/reader.rs:298]: It seems that unlike the `Scanner`which would do `verify_range` there is no region range check when scanning locks from storage by now.
@MyonKeminta @zyguan 
Is it necessary to add such checks for scanning locks?

Comment (zyguan) [reply src/storage/mvcc/reader/reader.rs:298]: I think it's probably unnecessary, [here](https://github.com/tikv/tikv/blob/master/components/raftstore/src/store/txn_ext.rs#L29) mem locks are guaranteed to be within the range of the region?

File: src/storage/mvcc/reader/reader.rs [hunk 8]
```diff
@@ -278,12 +279,103 @@ impl<S: EngineSnapshot> MvccReader<S> {
...
+            while cursor.valid()? {
+                let key = Key::from_encoded_slice(cursor.key(&mut self.statistics.lock));
+                if let Some(end) = end_key {
+                    if key >= *end {
+                        return Ok(None);
+                    }
+                }
+                let lock = Lock::parse(cursor.value(&mut self.statistics.lock))?;
+                if filter(&key, TxnLockRef::Persisted(&lock)) {
+                    return Ok(Some((key, lock)));
```
[the remark this answers is not in the document]
Comment (cfzjywxk) [reply src/storage/mvcc/reader/reader.rs:334]: Thanks for the reminding, it's added.

**Review by zyguan — APPROVED** [review]

File: src/storage/mvcc/reader/reader.rs [hunk 9]
```diff
@@ -278,12 +279,104 @@ impl<S: EngineSnapshot> MvccReader<S> {
...
+            limit,
+            source,
+        )?;
+        if memory_locks.is_empty() {
+            return self.scan_locks_from_storage(start_key, end_key, &filter, limit);
+        }
+
+        let mut lock_cursor_seeked = false;
+        let mut next_pair_from_storage = || -> Result<Option<(Key, Lock)>> {
+            self.create_lock_cursor()?;
```
Comment (ekexium) [inline src/storage/mvcc/reader/reader.rs:309]: The method should have another name like "create-if-not-exist"..

File: src/storage/mvcc/reader/reader.rs [hunk 10]
```diff
@@ -278,12 +279,104 @@ impl<S: EngineSnapshot> MvccReader<S> {
...
+            let cursor = self.lock_cursor.as_mut().unwrap();
+            if !lock_cursor_seeked {
+                let ok = match start_key {
+                    Some(x) => cursor.seek(x, &mut self.statistics.lock)?,
+                    None => cursor.seek_to_first(&mut self.statistics.lock),
+                };
+                if !ok {
+                    return Ok(None);
+                }
+                lock_cursor_seeked = true;
```
Comment (ekexium) [inline src/storage/mvcc/reader/reader.rs:319]: If `!ok`, in each iteration `seek` is called once. It could be avoided if we know we've tried and found nothing.

File: src/storage/mvcc/reader/reader.rs (hunk 7 above)
Comment (MyonKeminta) [reply src/storage/mvcc/reader/reader.rs:298]: It might be a good idea to return a KeyNotInRegion error if the specified start_key or end_key is non-empty and out of the range of the region. TiDB's GCWorker is expected to get a region info and limit the range specified in the request within the region's range. Then, if TiKV here gets a snapshot successfully without reporting an EpochNotMatch error but the specified range exceeds the region, it must be caused by TiDB sending request wrongly.
But it still doesn't make full sense, as an empty start_key or end_key, which represents unlimited, is in fact still limited by the region range.
So I think such a check might make sense, but it's not strongly necessary. Of course it's not necessary to be done with in this PR, after all

**Review by MyonKeminta — COMMENTED** [review]
Rest LGTM

File: src/storage/mvcc/reader/reader.rs (hunk 10 above)
Comment (cfzjywxk) [reply src/storage/mvcc/reader/reader.rs]: Good catch, a status variable is added to check if it's exausted, PTAL.

File: src/storage/mvcc/reader/reader.rs [hunk 11]
```diff
@@ -580,21 +673,21 @@ impl<S: EngineSnapshot> MvccReader<S> {
...
+    pub fn scan_locks_from_storage<F>(
         &mut self,
         start: Option<&Key>,
         end: Option<&Key>,
         filter: F,
         limit: usize,
     ) -> Result<(Vec<(Key, Lock)>, bool)>
     where
-        F: Fn(&Lock) -> bool,
+        F: Fn(&Key, TxnLockRef<'_>) -> bool,
```
[the remark this answers is not in the document]
Comment (cfzjywxk) [reply src/storage/mvcc/reader/reader.rs]: It's refactored, PTAL

**Review by MyonKeminta — APPROVED** [review]
