### PR TITLE
snap_recovery: added keep leader

### LINKED ISSUE #15122: snap_restore: when there are message dropping, snap_restore may fail
### What version of TiKV are you using?
v6.5.3

### What operating system and CPU are you using?
Linux, amd64

### Steps to reproduce
Run snapshot restore with about 20k regions per store.

### What did you expect?
Restore success.

### What did happened?
Restore got stuck. That is probably because there are some election messages are dropped due to `full`.

### PR DESCRIPTION
**Pull request by YuJuncen**
### What is changed and how it works?

Issue Number: Close #15122 

What's Changed:
This PR added a structure named `LeaderKeeper` in `RecoveryRegion` API. That will use `LeaderCallback` to check whether the leader is lost and if so, send `Campaign` if there were leadership lost.

```commit-message
```

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by tonyxuqqi** [comment]
@YuJuncen Could you elaborate how does this PR to solve the https://github.com/tikv/tikv/issues/15122?
Is it by reducing election message count?

**Comment by YuJuncen** [comment]
@tonyxuqqi This simply poll the leader state (via `LeaderCallback`) every 30s, and if it found there are regions that should be but not be leader, we manually request it campaign again.

File: components/snap_recovery/src/leader_keeper.rs [hunk 1]
```diff
@@ -0,0 +1,260 @@
...
+
+            not_leader: to_keep.into_iter().collect(),
+            _ek: PhantomData,
+        }
+    }
+
+    pub async fn wait_until_all_leader_ready(&mut self) {
+        loop {
+            let now = Instant::now();
+            GLOBAL_TIMER_HANDLE
```
Comment (hicqu) [inline components/snap_recovery/src/leader_keeper.rs:71]: So for the best case, it still wait 30s?

File: components/snap_recovery/src/services.rs [hunk 2]
```diff
@@ -233,7 +236,6 @@ impl<ER: RaftEngine> RecoverData for RecoveryService<ER> {
                 }
             }
 
-            let mut rxs = Vec::with_capacity(leaders.len());
             for &region_id in &leaders {
                 if let Err(e) = raft_router.send_casual_msg(region_id, CasualMessage::Campaign) {
```
Comment (hicqu) [inline components/snap_recovery/src/services.rs:240]: How about moving the logic into leader_keeper?

File: components/snap_recovery/src/leader_keeper.rs [hunk 3]
```diff
@@ -0,0 +1,260 @@
...
+
+    pub async fn step(&mut self) -> StepResult {
+        const CONCURRENCY: usize = 256;
+        let r = RefCell::new(StepResult::default());
+        let success = RefCell::new(HashSet::new());
+        for batch in &self.not_leader.iter().chunks(CONCURRENCY) {
+            let tasks = batch.map(|region_id| async {
+                match self.check_leader(*region_id).await {
+                    Ok(_) => {
+                        success.borrow_mut().insert(*region_id);
```
Comment (hicqu) [inline components/snap_recovery/src/leader_keeper.rs:92]: If it's running in a multi-thread pool, this may panic? Maybe a rwlock is better.

File: components/snap_recovery/src/leader_keeper.rs (hunk 1 above)
Comment (YuJuncen) [reply components/snap_recovery/src/leader_keeper.rs:71]: 192.168.3.1

File: components/snap_recovery/src/leader_keeper.rs (hunk 3 above)
Comment (YuJuncen) [reply components/snap_recovery/src/leader_keeper.rs:92]: Generally `RefCell` and the `RaftStoreRouter` will forbid we from running it at a multi-threaded pool. Anyway using Mutex won't make things worse.

File: components/snap_recovery/src/services.rs (hunk 2 above)
Comment (YuJuncen) [reply components/snap_recovery/src/services.rs:240]: Sounds good, let me try it.

File: components/snap_recovery/src/leader_keeper.rs (hunk 1 above)
Comment (hicqu) [reply components/snap_recovery/src/leader_keeper.rs:71]: How about 5s?

File: components/snap_recovery/src/leader_keeper.rs (hunk 3 above)
Comment (hicqu) [reply components/snap_recovery/src/leader_keeper.rs:92]: I see. Now I think it's OK.

File: components/snap_recovery/src/leader_keeper.rs [hunk 4]
```diff
@@ -0,0 +1,260 @@
...
+                "got error: {:?}",
+                header.get_error()
+            )));
+        }
+        Ok(())
+    }
+
+    fn force_leader(&self, region_id: u64) -> Result<()> {
+        let msg = CasualMessage::Campaign;
+        self.router.send(region_id, msg)?;
```
Comment (hicqu) [inline components/snap_recovery/src/leader_keeper.rs:129]: Is it necessary to keep the log "region starts to campaign"?

**Review by hicqu — APPROVED** [review]

File: components/snap_recovery/src/leader_keeper.rs (hunk 4 above)
Comment (YuJuncen) [reply components/snap_recovery/src/leader_keeper.rs:129]: I'm not sure, somethings it gets so verbose that some of logs will be dropped.

**Review by Leavrth — APPROVED** [review]

**Review by tonyxuqqi — APPROVED** [review]
