### PR TITLE
Titan: Fix turning off compatibility issue

### LINKED ISSUE #18434: TiKV crash when applying snapshots after turning off Titan
`[2025/04/24 04:00:55.452 +00:00] [ERROR] [region.rs:540] ["failed to apply snap!!!"] [err_code=KV:Raftstore:SnapUnknown] [err="Other(\"[components/raftstore/src/store/worker/region.rs:727]: Storage Engine Status { code: IoError, sub_code: None, sev: NoError, state: \\\"Corruption: Error while decoding blob index: Corrupted blob offset\\\" }\")"] [thread_id=0x4]`
`[2025/04/24 04:01:44.814 +00:00] [FATAL] [lib.rs:510] ["[region 1195903179] 4294177462 applying snapshot failed"] [backtrace="   0: tikv_util::set_panic_hook::{{closure}}\n   `

### PR DESCRIPTION
**Pull request by v01dstar**
### What is changed and how it works?

Issue Number: Close #18434

What's Changed:

```commit-message
Fixing Titan blob indices causing snapshot apply failures after Titan is turned off bug.
```

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [x] Need to cherry-pick to the release branch

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note

```release-note
Fixing Titan blob indices causing snapshot apply failures after Titan is turned off bug.
```

### CODE REVIEW

File: tests/failpoints/cases/test_titan.rs [hunk 1]
```diff
@@ -111,7 +111,7 @@ fn test_titan() {
         db.get_property_int_cf(defaultcf, "rocksdb.num-files-at-level5")
             .unwrap()
     );
-    // lv5: file1 [k1: deleted]
+    // lv5: file1 [k1: deletion]
```
Comment (hbisheng) [inline tests/failpoints/cases/test_titan.rs]: In `BlobRunMode::Fallback`, should k1 be rewritten into the LSM instead of getting deleted?

Comment (v01dstar) [reply tests/failpoints/cases/test_titan.rs]: Yes, thanks for catching this

File: tests/failpoints/cases/test_titan.rs [hunk 2]
```diff
@@ -155,6 +156,8 @@ fn test_titan() {
             .async_add_peer(region1.get_id(), peer.clone())
             .unwrap(),
     )));
+
+    cluster.must_transfer_leader(region1.get_id(), peer.clone());
```
Comment (overvenus) [inline tests/failpoints/cases/test_titan.rs:160]: Please send a read request and a write after it becomes leader.

Comment (v01dstar) [reply tests/failpoints/cases/test_titan.rs:160]: done
