### PR TITLE
raftstore: iops aggregation adaptive optimization

### LINKED ISSUE #19392: Raftstore: support new adaptive batching strategy
## Development Task
Previous work in https://github.com/tikv/tikv/pull/17029 introduced a mechanism in v8.3.0+ to wait to gain a larger batch until reaching either size or timeout. It introduces an adaptive batching strategy controlled by two key parameters: wait_duration (default: 20us) and batch_size_hint (default: 8KB). It dynamically adjusts the wait_duration to maintain an optimal balance, constraining it strictly between 0.5x and 2.0x of the configured value according to the observed batch trend. The problem with the current strategy is that when the wait_duration is configured to a large value, performance regression and latency increase may occur due to the limited range of variation.
We need a new adaptive batching strategy which can adjusts the wait_duration within a larger range to optimize the trade-off between write batching efficiency (reducing IOPS) and QPS throughput/request latency.

### PR DESCRIPTION
**Pull request by jiadebin**
### What is changed and how it works?

Issue Number: Close #19392

What's Changed:
The v8.x has introduced an adaptive batching strategy controlled by two key parameters: wait_duration (default: 20us) and batch_size_hint (default: 8KB). It dynamically adjusts the wait_duration to maintain an optimal balance, constraining it strictly between 0.5x and 2.0x of the configured value according to the batch trend. The problem with the current strategy is that when the wait_duration is configured to a large value, performance regression and latency increase may occur due to the limited range of variation.      
The [new adaptive batching strategy](https://pingcap.feishu.cn/wiki/FgIWwaXoriexbPkzG5uclLiWn2b) dynamically adjusts the wait_duration within a larger range in raftstore write path to optimize the trade-off between write batching efficiency (reducing IOPS) and QPS throughput / request latency.    

As the [Test Report](https://pingcap.feishu.cn/wiki/LgRtw7BkUi501ZkOeLZcHph8nsb) shows, in the local SSD environment (IDC), compared with the default configuration (wait_duration=20us), the new strategy achieves IOPS reduction; compared with the old version with the same configuration, it delivers better trade-off control. In the EBS environment (Cloud), we tested the standard and plus storage types, and the new strategy has almost no IOPS reduction effect. This is because the latency of EBS itself is already relatively high, and the current version can automatically aggregate I/Os. But the new strategy achieves a dual optimization of "increased throughput (QPS) and decreased latency".     

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [ ] Need to cherry-pick to the release branch

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note

```release-note
Raftstore: add an optional adaptive write-batching feature that dynamically tunes raft write wait duration based on observed write QPS and batch-achievement ratio. This improves batching efficiency under high concurrency to reduce IOPS amplification, while backing off quickly when waiting becomes less effective under lighter traffic. The feature is controlled by `raftstore.adaptive_batch_enabled` and is disabled by default, so existing behavior remains unchanged unless explicitly enabled. 
```

## Summary by CodeRabbit

* **New Features**
  * Opt-in adaptive batching for write operations (default: off).
  * New config fields to enable adaptive batching and set a high-QPS threshold.
  * Exposed an adaptive-batching gauge and two histograms to observe wait-duration behavior.

* **Improvements**
  * Runtime-tuned batching and wait-duration adjustments based on recent QPS and concurrency.
  * Smoothing, clamping and safeguards to avoid futile or extreme waits; enhanced adaptive logging.

* **Tests**
  * Expanded tests covering adaptive wait-duration logic and boundary conditions.

### CODE REVIEW

File: components/raftstore/src/store/async_io/write.rs [hunk 1]
```diff
@@ -469,8 +585,24 @@ impl WriteTaskBatchRecorder {
...
+
+        // Fallback to old strategy: if wait_duration drops too low (<=40us), reset to
+        // 20us This is only applied when adaptive_batch_enabled is true
+        // This prevents the new adaptive algorithm from preforming too aggressively to
+        // increase IOPS unexpectedly.
+        if adaptive_batch_enabled {
+            if self.wait_duration_adaptive.as_nanos()
+                <= (2 * RAFT_WB_WAIT_DURATION_DEFAULT_NS).into()
+            {
+                self.wait_duration = Duration::from_nanos(RAFT_WB_WAIT_DURATION_DEFAULT_NS);
```
[the remark this answers is not in the document]
Comment (jiadebin) [reply components/raftstore/src/store/async_io/write.rs]: This logic aims to extend the adjustment range for wait_duration (admit very small wait_duration compared with hint value) to avoid very large latency when the workload is quite light.
I've changed to initialize wait_duration_adaptive to min(wait_duration, 20µs).

File: components/raftstore/src/store/async_io/write.rs [hunk 2]
```diff
@@ -416,13 +524,15 @@ impl WriteTaskBatchRecorder {
             avg: 0,
             trend: 1.0,
             wait_duration,
+            wait_duration_adaptive: Duration::from_nanos(RAFT_WB_WAIT_DURATION_DEFAULT_NS),
+            wait_duration_hint: wait_duration,
             wait_count: 0,
```
[the remark this answers is not in the document]
Comment (jiadebin) [reply components/raftstore/src/store/async_io/write.rs]: This logic aims to extend the adjustment range for wait_duration (admit very small wait_duration compared with hint value) to avoid very large latency when the workload is quite light.

[the remark this answers is not in the document]
Comment (jiadebin) [reply components/raftstore/src/store/async_io/write.rs]: ok, I've changed to initialize wait_duration_adaptive to min(wait_duration, 20µs).

**Review by LykxSassinator — APPROVED** [review]
LGTM

File: components/raftstore/src/store/async_io/write.rs [hunk 3]
```diff
@@ -469,8 +587,24 @@ impl WriteTaskBatchRecorder {
         batch_size < self.batch_size_hint && self.wait_count < self.wait_max_count
     }
 
-    fn wait_for_a_while(&mut self) {
+    fn wait_for_a_while(&mut self, adaptive_batch_enabled: bool) {
         self.wait_count += 1;
+
+        // Fallback to old strategy: if wait_duration drops too low (<=40us), reset to
```
Comment (hbisheng) [inline components/raftstore/src/store/async_io/write.rs:516]: The comment seems a bit confusing: it says “preventing aggressive behavior,” but resetting to the 20µs default is actually more aggressive than waiting 40µs (it waits less), so the wording doesn’t match what the code does.

File: components/raftstore/src/store/async_io/write.rs [hunk 4]
```diff
@@ -469,8 +587,24 @@ impl WriteTaskBatchRecorder {
...
+        // 20us. This is only applied when adaptive_batch_enabled is true
+        // This prevents the new adaptive algorithm from preforming too aggressively to
```
Comment (hbisheng) [inline components/raftstore/src/store/async_io/write.rs]:
```suggestion
        // This prevents the new adaptive algorithm from performing too aggressively to
```

File: components/raftstore/src/store/async_io/write.rs [hunk 5]
```diff
@@ -469,8 +587,24 @@ impl WriteTaskBatchRecorder {
...
+        // increase IOPS unexpectedly.
+        if adaptive_batch_enabled {
```
Comment (hbisheng) [inline components/raftstore/src/store/async_io/write.rs:520]: Would it be useful to add metrics for both the effective wait duration (what wait_for_a_while() actually uses) and the calculated/adaptive wait duration (controller output)? This would improve observability for troubleshooting. Not sure if histogram is needed or a gauge would be sufficient.

File: components/raftstore/src/store/async_io/write.rs [hunk 6]
```diff
@@ -810,9 +1029,544 @@ where
...
+        if now.saturating_duration_since(self.last_adaptive_update) < Duration::from_secs(2) {
+            return;
+        }
+
+        self.last_adaptive_update = now;
+
+        // Calculate median QPS for more stable metrics
+        let mut sorted_qps: Vec<u64> = self.qps_history.iter().cloned().collect();
+        sorted_qps.sort();
+        let avg_qps = sorted_qps[sorted_qps.len() / ADAPTIVE_MEDIAN_INDEX_DIVISOR]; // Median
```
Comment (hbisheng) [inline components/raftstore/src/store/async_io/write.rs]: `medium_qps` is more accurate?

**Comment by hbisheng** [comment]
The test report is not public; maybe paste a short summary into the PR description?

**Comment by hbisheng** [comment]
LGTM overall

**Comment by hhwyt** [comment]
Could you please give a test port summary in the PR description?

File: components/raftstore/src/store/async_io/write.rs [hunk 7]
```diff
@@ -68,6 +68,112 @@ const RAFT_WB_SPLIT_SIZE: usize = ReadableSize::gb(1).0 as usize;
 /// The default size of the raft write batch recorder.
 const RAFT_WB_DEFAULT_RECORDER_SIZE: usize = 30;
 
+const RAFT_WB_WAIT_DURATION_UPPER_BOUND_NS: u64 = 1_000_000; // 1ms
```
Comment (hhwyt) [inline components/raftstore/src/store/async_io/write.rs:71]: Great benchmark results, especially on cloud (QPS +40%, P99 -40%).

The algorithm with 50+ constants feels over-engineered for the core idea. Could we simplify it? A much simpler approach might achieve 80% of the benefit with far less code, and be much easier to maintain and debug.

**Comment by jiadebin** [comment]
> The test report is not public; maybe paste a short summary into the PR description?

Done, and the report should be available now.

File: components/raftstore/src/store/async_io/write.rs (hunk 3 above)
Comment (jiadebin) [reply components/raftstore/src/store/async_io/write.rs:516]: In fact, the purpose of resetting to 20µs here is to ensure that requests within 40µs still follow the default strategy.In the default strategy, wait_duration varies within the range [0.5 * 20µs, 2 * 20µs].This avoids regression of the new strategy compared to the default strategy within this range, making it more user-friendly.When wait_duration exceeds 40µs, the decision is entirely determined by the new strategy.

**Comment by jiadebin** [comment]
> Could you please give a test port summary in the PR description?

Added it.

File: components/raftstore/src/store/async_io/write.rs (hunk 5 above)
Comment (jiadebin) [reply components/raftstore/src/store/async_io/write.rs:520]: Add two histogram metrics to record these values.

File: components/raftstore/src/store/async_io/write.rs (hunk 7 above)
Comment (jiadebin) [reply components/raftstore/src/store/async_io/write.rs:71]: Thanks for the feedback. The adaptive algorithm has been simplified and the total number of constants reduced to 11 (5 for boundary/time/length, 6 for core strategy). The new simplified version will be much easier to maintain. And test result shows that it mainly holds the IOPS optimization effect of the old version except performance regression at some cases.

Comment (hhwyt) [reply components/raftstore/src/store/async_io/write.rs:71]: Good job!
